### ISSUE TITLE
Legacy debugger causing exponential resource loading times in Node.js 14

### ISSUE THREAD

**Issue by DJ4ddi** [microsoft/vscode-js-debug#1000]
**Description**
I am debugging an Electron app using node launch and chrome attach configurations (to access both the launcher and the renderer process). This previously worked fine using the old debugger (`"debug.javascript.usePreview": false`), but is now having issues after migrating to Node.js 14 (Electron 12.0.7).

Specifically, the resource loading times are increasing exponentially while the debugger is attached, starting at milliseconds but quickly reaching minutes for a single image. All of the resources are on localhost. The loading is taking up so much CPU time that the profiler is missing samples, I uploaded a profile of the issue along with the logs.

This does not happen using the preview debugger, but due to a number of other issues I can not upgrade to that (unbound breakpoints in late loaded scripts, broken restart/reload and a few others that I don't want to get into in this ticket). This also did not happen on the preevious Electron 11.2.3 (Node.js 12).

**Files**
Profile: https://hash-co.de/vscode/profile.json
Launcher log: https://hash-co.de/vscode/debugadapter-legacy.txt
Debugger log: https://hash-co.de/vscode/vscode-chrome-debug.txt
Launch config: https://hash-co.de/vscode/launch.json

**Versions**
VSCode: 1.56.2
Node.js: 14.16.0
Electron: 12.0.7
Debugger for Chrome 4.12.12

**Comment by connor4312** [comment]
We no longer support the legacy debugger. Please open issues for any bugs you have with the new debugger.
