### ISSUE TITLE
Breakpoints not binding within async function with default parameter

### ISSUE THREAD

**Issue by scottdrichards** [microsoft/vscode-js-debug#1001]
**Describe the bug**
When debugging a Typescript app made using Create-React-App I noticed that if an async function has a default parameter value `const fn=async(p="default)=>...` then most breakpoints will disappear on launch of Chrome, except for breakpoints within an await block. 

**To Reproduce**
1. Create react app `npx create-react-app my-app --template typescript`
2. Add the following code to App.tsx (after function App(){...:
```
  const asyncFn = async(param:string="default")=>{
    console.log("Can't break here");
    await new Promise((res,rej)=>{
      console.log("Can break here")
      res(true)
    })
    console.log("Can't break here")
  }    
  console.log("Can break here")
  asyncFn()
```
3. Add breakpoints throughout
4. Start server (npm start)
5. Start debug with chrome

Before starting debug session:
![image](https://user-images.githubusercontent.com/28912482/119237765-8cbb0300-bb0c-11eb-9e90-c769eac98071.png)

During debug session (note missing breakpoints, though you can step through to these sections):
![image](https://user-images.githubusercontent.com/28912482/119237761-862c8b80-bb0c-11eb-8304-91e105a0c184.png)

It works as expected when the default parameter value is removed. 

**VS Code Version:** 1.56.2
Debugger for Chrome: v4.12.12
tsconfig target: es5

**Comment by connor4312** [comment]
This was a bug in Chrome which was fixed in Chrome 91.

**Comment by verikono** [comment]
Still doing it. I'm working on a graphql project using typescript (see tsconfig below - needs a refactor, i know ;))

```code 

{
  "compilerOptions": {
    "module": "CommonJS",
    "target": "es2018",
    "lib": ["es2018", "esnext.asynciterable"],
    "outDir": "dist",
    "rootDir": ".",
    "strict": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "resolveJsonModule": true,
    "esModuleInterop": true
  }
}
````

settings.json is very bog standard:

```code
{
    "mochaExplorer.files": "tests/**/*.ts",
    "mochaExplorer.require": "ts-node/register"
}
```

my guess is the typescript target might refactor the default arguments when compiled setting the debugger crazy... any ideas are welcome.

**Comment by connor4312** [comment]
Please ensure you're not on a Node.js version affected by the same issue (e.g. update to the most recent 16.x version)
