### ISSUE TITLE
Chrome attach restart/reload not working

### ISSUE THREAD

**Issue by DJ4ddi** [microsoft/vscode-js-debug#1004]
**Description**
I am using an Electron configuration with a main process accessed using node launch and a renderer process using chrome attach. My goal is to reload the window by sending the restart command to the Chrome debugger, which worked as expected using the legacy debugger.

With the new debugger, executing the restart command of the chrome attach configuration does nothing except that the debug output is cleared. The window is not reloaded (expected behavior) and the debugger does not disconnect.

**Files**
[vscode-debugadapter-0ae1454e.json.gz](https://github.com/microsoft/vscode-js-debug/files/6528136/vscode-debugadapter-0ae1454e.json.gz) (Main process)
[vscode-debugadapter-3e4e8ed6.json.gz](https://github.com/microsoft/vscode-js-debug/files/6528137/vscode-debugadapter-3e4e8ed6.json.gz) (Renderer process)
[launch.zip](https://github.com/microsoft/vscode-js-debug/files/6528139/launch.zip) (Launch configurations for both)

**Versions**
VSCode: 1.56.2
Node.js: 14.16.0
Electron: 12.0.7
Debugger for Chrome 4.12.12

**Comment by connor4312** [comment]
Thanks for the issue! This'll be in tomorrow's [nightly](https://github.com/microsoft/vscode-js-debug#nightly-extension)
