### ISSUE TITLE
Stopped events are not delivered when launching with `pwa-node`

### ISSUE THREAD

**Issue by lhchavez** [microsoft/vscode-js-debug#1009]
**Describe the bug**
When launching a `pwa-node` app through the terminal, the DAP does not deliver any Stopped events.

**To Reproduce**
1. With the following DAP messages: (full repro here: https://replit.com/@luisreplit/NodeDAP#driver.py)
```json
{
  "command": "initialize",
  "arguments": {
    "clientID": "replit",
    "clientName": "replit.com",
    "pathFormat": "path",
    "linesStartAt1": True,
    "columnsStartAt1": True,
    "supportsVariableType": True,
    "supportsVariablePaging": True,
    "supportsRunInTerminalRequest": True,
    "locale": "en-us",
    "supportsProgressReporting": True,
    "supportsInvalidatedEvent": True
  }
}
{
  "command": "setBreakpoints",
  "arguments": {
    "source": {
      "name": "main.js",
      "path": "/home/runner/NodeDAP/main.js"
    },
    "breakpoints": [{
      "line": 4
    }],
    "sourceModified": False
  }
}
{
  "command": "launch",
  "arguments": {
    "type": "pwa-node",
    "request": "launch",
    "program": "/home/runner/NodeDAP/main.js",
    "args": [],
    "stopOnEntry": False,
    "pauseForSourceMap": False,
    "sourceMaps": True,
    "smartStep": True,
    "cwd": "/home/runner/NodeDAP",
    "environment": [],
    "console": "externalTerminal",
    "trace": {
      "level": "verbose",
      "logFile": "/home/runner/NodeDAP/adapter.log"
    }
  },
}
{
  "command": "configurationDone"
}
```
3. There are no Stopped events when the breakpoint is reached, but there are `Debugger.paused` events!

**Log File**
https://gist.githubusercontent.com/lhchavez/e6d3f50c213d53c752e285131240774d/raw/26211f7e66b0943ebec1805d1b382a9aa79d0e1d/nodedap.txt

**VS Code Version:** 1.56.2

**Additional context**
I've been able to reproduce this in VSCode, but not reliably. Not sure what the difference is.

**Comment by connor4312** [comment]
@lhchavez were you able to verify that this is fixed for you?

**Comment by lhchavez** [comment]
yes, thank you so much for merging :D
