### ISSUE TITLE
Extension issue : Source Map Not Found

### ISSUE THREAD

**Issue by mehulchauhan** [microsoft/vscode-js-debug#1012]
- Issue Type: `Bug`
- Extension Name: `js-debug-nightly`
- Extension Version: `2021.5.2717`
- OS Version: `Linux x64 5.8.0-53-generic`
- VS Code version: `1.56.2`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 997,
		"activateCallTime": 19,
		"activateResolvedTime": 0,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-vscode.js-debug-nightly",
				"_lower": "ms-vscode.js-debug-nightly"
			},
			"activationEvent": "onCommand:extension.js-debug.clearAutoAttachVariables"
		}
	},
	"runtimeErrors": []
}
```
Below is a sample error, but throwing error for all "*.map" files in the extension directory. 
These errors are making a significant increase in the activation time.
```javascript
Could not read source map for 
file:///home/{user}/.vscode/extensions/aaron-bond.better-comments-2.1.0/out/extension.js:

ENOENT: no such file or directory, open 
'/home/{user}/.vscode/extensions/aaron-bond.better-comments-2.1.0/out/extension.js.map'
```

**Comment by connor4312** [comment]
Those errors are not caused by or related to the activation of js-debug. Please describe the problem you're hitting in more detail.
