### ISSUE TITLE
Only when I use Debugger for Chrome, I get an error with Precache in Service Worker.

### ISSUE THREAD

**Issue by akiot-b** [microsoft/vscode-js-debug#1019]
**Describe the bug**
Only when I use Debugger for Chrome, I get an error with Precache in Service Worker.

When I start js and Debugger for Chrome in the following project, I get an error.
"Uncaught (in promise) DOMException: Entry already exists."
It works fine in normal Chrome.

The debugger for chrome website states that web workers scenarios are not supported. Is this the case with this error?

I'm hoping that Precache will work correctly, because I don't want to be able to debug Service Worker.

**To Reproduce**
https://github.com/akiot-b/issue-2021060801
1. yarn install
2. launch vscode and project folder
3. run 'vuejs' and 'vuejs: chrome'
4. open chrome console
5. See error

**Log File**
https://github.com/akiot-b/issue-2021060801/tree/main/log

**VS Code Version:**
vscode 1.56.2
Debugger for Chrome 4.12.12

**relevant section**
service-worker.js
```

importScripts(
  'https://storage.googleapis.com/workbox-cdn/releases/6.1.5/workbox-sw.js'
)

if (workbox) {
  console.log(`Yay! Workbox is loaded `)
} else {
  console.log(`Boo! Workbox didn't load `)
}

const precacheController = new workbox.precaching.PrecacheController()

const files = ['/v.jpg']
const precacheManifest = files.map((element) => {
  return { url: element, revision: '1234' }
})
precacheController.addToCacheList(precacheManifest)

addEventListener('install', (event) => {
  // Uncaught (in promise) DOMException: Entry already exists.
  event.waitUntil(precacheController.install(event))
})

addEventListener('activate', (event) => {
  event.waitUntil(precacheController.activate(event))
})
```

**Comment by connor4312** [comment]
Thanks for the issue and repro!

I end up getting a different error, `DOMException: Unexpected internal error`. From doing some background research, this seems to be a bug on Chrome's end, and I'm not seeing any evidence to suggest it's related to something the debugger is doing. I suggest opening a bug on Chromium by hitting "New Issue" on https://bugs.chromium.org/p/chromium/issues/list. They're pretty responsive and should triage your issue quickly.

**Comment by akiot-b** [comment]
Thanks, I've posted it on chromium.
https://bugs.chromium.org/p/chromium/issues/detail?id=1218798
