### ISSUE TITLE
Run npm script before opening the browser

### ISSUE THREAD

**Issue by ilanb1996** [microsoft/vscode-js-debug#1025]
**Is your feature request related to a problem? Please describe.**
Hi, I'm working on a product that is a 3rd party script that a site is loading after it has been served, for that i need to first build and start my webserver and then access a url that will request my 3rd party script.
What i need to do now is to manually run a script from the terminal and then i start a debug session, where i put the url of the site that loads my script.

**Describe the feature you'd like**
I would like to have a new configuration option that will allow me to run set up script before i start the debug session.

**Comment by connor4312** [comment]
You can do this using the [preLaunchTask](https://code.visualstudio.com/docs/editor/debugging#_launchjson-attributes) attribute of the launch.json. [More about tasks](https://code.visualstudio.com/docs/editor/tasks).
