### ISSUE TITLE
[BUG] Unable to resolve the correct path

### ISSUE THREAD

**Issue by FishOrBear** [microsoft/vscode-js-debug#1026]
```
console.error(error.stack);
```

in Debugger for Chrome4.12.12

```
TypeError: e.aaa is not a function
    at Test.exec (webpack-internal:///./src/test.ts:15:15)
```

in Debugger for Chrome4.11.7
```
TypeError: e.aaa is not a function
    at Test.exec (e:\WebProject\Web\src\test.ts:20:15)
```

**Comment by connor4312** [comment]
Please share a sample reproduction, or a log using instructions in the issue template.

**Comment by FishOrBear** [comment]
[test_project.zip](https://github.com/microsoft/vscode-js-debug/files/6635407/test_project.zip)

yarn
yarn dev
f5 start debug

chrome-debug 4.12.12
![image](https://user-images.githubusercontent.com/19372111/121622301-5a178100-caa0-11eb-8574-c60f23c672d8.png)

**Comment by connor4312** [comment]
I'm not able to reproduce this:

![](https://memes.peet.io/img/21-06-3914d683-7a89-46ce-918b-8401178e6180.png)

Please collect a log using the instructions in the issue template
