### ISSUE TITLE
Add Chrome inspector integration (same like Edge)

### ISSUE THREAD

**Issue by j0k4rX** [microsoft/vscode-js-debug#1027]
**Is your feature request related to a problem? Please describe.**
in [v1.57 update](https://github.com/microsoft/vscode-js-debug/blob/main/CHANGELOG.md#v1570---2021-06-02), you have added edge inspector integration.
description [here](https://code.visualstudio.com/updates/v1_57#_debugging)

**Describe the feature you'd like**
I would like "Chrome inspector integration" feature in my vscode

<img src="https://code.visualstudio.com/assets/updates/1_57/debug-inspect-button.png" img>

<img src="https://code.visualstudio.com/assets/updates/1_57/js-debug-edge.gif" img>

**Comment by drysart** [comment]
[Does it not already do what you're asking for?](https://code.visualstudio.com/blogs/2016/02/23/introducing-chrome-debugger-for-vs-code)

**Comment by j0k4rX** [comment]
No, inspection tool is not available for chrome (only available for
Microsoft Edge)

I attached discussion link above... Go to that link and you'll understand
what i meant.

**Comment by j0k4rX** [comment]
@drysart "integrated inspect tool" to be exact
released in the latest version 1.57
https://code.visualstudio.com/updates/v1_57#_debugging

![Screenshot from 2021-06-11 16-14-38](https://user-images.githubusercontent.com/71499522/121671269-27857c80-cad0-11eb-8c7e-bafda67c101c.png)

**Comment by connor4312** [comment]
Integration for the Edge devtools is possible because they made an effort to make their devtools portable, and usable in VS Code. If the Chromium team went to the same effort I would be happy to integrate with them, but who knows when or if that will happen.
