### ISSUE TITLE
Attaching to CEF based desktop app is broken.

### ISSUE THREAD

**Issue by mmarczell-graphisoft** [microsoft/vscode-js-debug#1030]
**Describe the bug**
This is a regression from the previous debugger. The use case is a web app running locally, inside a desktop app, using Chromium Embedded Framework. Requests made by the web app are made to a nonexistent domain, intercepted and served directly using the C++ interface of CEF. I believe the previous debugger must have used the debugged browser to fetch the sourcemaps, therefore it could retrieve them despite the nonexistent domain. The current debugger AFAICT tries to do these network requests outside of the debugged browser and fails.

**To Reproduce**
Well you'd need to build a CEF based desktop app to reproduce, but this is my launch config:
```
        {
            "name": "Attach to CEF app",
            "type": "chrome",
            "request": "attach",
            "port": 9222,
            "webRoot": "${workspaceFolder}/dist"
        }
```

The error message I'm getting:

> Could not read source map for http://somefakedomain.com/main-es2015.js: Unexpected 503 response from http://somefakedomain.com/main-es2015.js.map: getaddrinfo ENOTFOUND somefakedomain.com

**Log File**
I sent it via email.

**VS Code Version:** 1.57.0

**Comment by connor4312** [comment]
Good ways to fix this are to:

- Have your tooling produce inline sourcemaps (this is what we do in vscode) or
- Have your tooling produce absolute file URIs

Duplicates https://github.com/microsoft/vscode-js-debug/issues/425

**Comment by mmarczell-graphisoft** [comment]
@connor4312 I'm trying to make use of the recommendation in #904 like this:
```
"debug.javascript.resourceRequestOptions": {
	"prefixUrl": "file:///${workspaceRoot}/dist/"
}
```
but "got" doesn't seem to support the file: protocol:

> Could not read source map for http://somefakedomain.com/polyfills-es2015.js: Unexpected 503 response from http://somefakedomain.com/polyfills-es2015.js.map: Unsupported protocol "file:"

Could your second suggestion be supported somehow or is inline sourcemaps my only option?
