### ISSUE TITLE
Slow processing of variables on hitting a breakpoint

### ISSUE THREAD

**Issue by RedMickey** [microsoft/vscode-js-debug#1033]
Hello,
I'm a maintainer of [React Native Tools](https://github.com/microsoft/vscode-react-native) VS Code extension. The extension is used for debugging React Native applications. Under the hood the extension uses `vscode-js-debug` debugger to debug javascript apps.

**Describe the bug**
After the update of VS Code to the version 1.57.0 we detected that processing of variables on the first hitting of a breakpoint can take quite a long time. However further breakpoints hittings are handled fine. We found out that such behavior appeared after the implementation of `Support for renamed identifiers in sourcemaps` feature in [this PR](https://github.com/microsoft/vscode-js-debug/commit/fef31854ed822896177ea8990d835c61ba16c100). We looked through CDP logs and revealed that now `js-debug` retrieves the whole bundled code of the application (via "Debugger.getScriptSource" method) and processes it. We assume that this could take a long time.

https://user-images.githubusercontent.com/33267199/122180131-d17a5580-ce90-11eb-9d6f-f8a265b27e8b.mp4

**To Reproduce**
The issue can be reproduced using a node attach scenario, but it requires some preparations.

1. Prepare development environment for Android React Native following [this guide](https://reactnative.dev/docs/environment-setup#installing-dependencies)
2. Create a React Native app using the command: 
    ```
    npx react-native init AwesomeProject
    ```
3. We prepared a special version of RNT extension, in which we suppressed attachment to an application in debugging scenarios. You can download this [VSIX](https://github.com/microsoft/vscode-js-debug/files/6661642/vscode-react-native-1.5.1.vsix.zip) and install it.
4.  Open your RN project in VS code and create `Debug Android` debugging configuration
    ```
    {
      "name": "Debug Android",
      "cwd": "${workspaceFolder}",
      "type": "reactnative",
      "request": "launch",
      "platform": "android"
    }
    ```
5. Open `App.js` file and set a breakpoint on the 62 line (return statement)
6. Run the `Debug Android` debugging scenario and wait until you see something like this in Debug console
    ```
    Starting debugger app worker.
    Attaching to the application
    Launching the application
    Established a connection with the Proxy (Packager) to the React Native application
    Debugger worker loaded runtime on port 9468
    ```
    The debugging scenario should launch the RN app on an Android emulator.
6. Enable debugging in the launched application following [this guide](https://reactnative.dev/docs/debugging). If after that  an error is shown in the app, click `Reload` button.
7. Create the `Attach` debugging scenario
    ```
    {
      "type": "pwa-node",
      "request": "attach",
      "name": "Attach",
      "port": 9468,
      "sourceMaps": true,
      "continueOnAttach": true,
      "resolveSourceMapLocations": [
        "!**/debuggerWorker.js"
      ]
    }
    ```
    The port should be the same as a debugger worker has.
8. Run the `Attach` scenario
9. Continue on the first technical breakpoint (the debuggerWorker process is launched in `--inspect-brk` mode)
10. After that, your previously set breakpoint should be reached

**Probable solution**
We are not sure about the solution, but it might make sense to add a special parameter to debugging configurations to enable/disable the “Support for renamed identifiers in sourcemaps” feature. So, users can configure it if they really need additional processing of variables while debugging.

**Log File**
Js-debug logs: 
[vscode-debugadapter-f39647b7.json.gz](https://github.com/microsoft/vscode-js-debug/files/6661600/vscode-debugadapter-f39647b7.json.gz)
CDP logs:
[currentCDPlogs.txt](https://github.com/microsoft/vscode-js-debug/files/6661638/currentCDPlogs.txt)
[previousCDPlogs_vs_code_1_56.txt](https://github.com/microsoft/vscode-js-debug/files/6661639/previousCDPlogs_vs_code_1_56.txt)

**VS Code Version:** 1.57.0

**Comment by connor4312** [comment]
I've made a change so that we only request source content if `names` are present in the sourcemap. Previously we were eagerly getting it for each file. Let me know if that resolves it for you.

**Comment by RedMickey** [comment]
Hi @connor4312 and thanks for your answer. 
I've tried out the new version of `js-debug` and it seems the issue still persists. I inspected the [index.map](https://github.com/microsoft/vscode-js-debug/files/6669012/index.map.zip) file provided by the RN app and it contained a lot of `names` arrays. Therefore, [`createFromSourceMap` function](https://github.com/microsoft/vscode-js-debug/blob/main/src/common/sourceMaps/renameProvider.ts#L82-L116) is called, it seems that it takes most of the processing time (about 3-8 sec.).
I believe that this is a useful feature, and it seems to be the expected behavior if there are `names` arrays in the `.map` file. I'm just a little worried about the processing time.

**Comment by nthtrung09it** [comment]
<img width="91" alt="Screen Shot 2021-06-24 at 12 52 57 AM" src="https://user-images.githubusercontent.com/7716509/123145059-9b3b6800-d486-11eb-9e2c-19672b6c36d9.png">

Experiencing the same issue. It takes about 2 minutes to be able to continue debugging.
**Version: 1.57.1**
MacOS.

**Comment by connor4312** [comment]
You can now set `sourceMapRenames: false` in the launch config to disable this functionality

**Comment by connor4312** [comment]
@RedMickey does this work for you?

**Comment by connor4312** [comment]
I pinged the author for verification. You can also try the Launch Minified Program in the demo folder https://github.com/microsoft/vscode-js-debug/tree/main/demos/node.

To verify:

1. Open the demo folder https://github.com/microsoft/vscode-js-debug/tree/main/demos/node
2. Run the `Launch Minified Program` configuration, and set a breakpoint here: https://github.com/microsoft/vscode-js-debug/blob/58311075a4e0cf8096176d02f63dffcd4a9ce44c/demos/node/main.js#L19. Verify the variable names are their original, source names in the "Variable" view
3. Add `sourceMapRenames: false` in the launch configuration
4. Do step 2 again. The variables name should now be their minified names (from main.min.js)

**Comment by connor4312** [comment]
If you have any ideas on how to make sourcemap names mapping work better in a way that doesn't require loading scripts, I'm happy to hear it, but I don't think it's possible.

**Comment by lagnat** [comment]
Truthfully I don't know enough about this so these ideas may be nonsense.  All I could think of would be to process the map files on a worker thread right away vs. waiting for the first breakpoint.  Another thought would be some kind of cache with incremental processing of map files.
