### ISSUE TITLE
Improve debugger pointer visual layout

### ISSUE THREAD

**Issue by rickstaa** [microsoft/vscode-js-debug#1037]
Currently in both the normal and insider vscode versions when debugging a javascript file two debug step pointers are shown. Further, the line that is active is also moved to the right. Maybe this is intended behaviour but I was wondering if it is possible to just show one debug pointer and prevent the line to be moved to the right?

![image](https://user-images.githubusercontent.com/17570430/122534127-855f1a80-d022-11eb-9191-c34329131cc3.png)

In the python debugger just one debug pointer is shown and the line is kept as it is:

![image](https://user-images.githubusercontent.com/17570430/122534292-ad4e7e00-d022-11eb-93f6-a021574f40d2.png)

**Describe the feature you'd like**

It would be nice to have only one pointer and have the debugged line stay where it is. A setting to change this behaviour would also be sufficient.

**Comment by connor4312** [comment]
This is a design decision in VS Code Core to show the location in the line where the debugger is paused for debuggers that send column information. Python doesn't, so they aren't shown there. Related: https://github.com/microsoft/vscode/issues/14784

**Comment by rickstaa** [comment]
@connor4312 Ah I see in languages that can contain multiple commands on one line this feature is very helpful. Thanks a lot for clearing that up.
