### ISSUE TITLE
Opening Javascript debug terminal in intergrated terminal gives `o.provideTerminalProfile is not a function` error

### ISSUE THREAD

**Issue by rickstaa** [microsoft/vscode-js-debug#1038]
**Describe the bug**

I noticed that in the new insider version, an `o.provideTerminalProfile is not a function` error is thrown when you try to open a Javascript debug terminal using the integrated terminal open terminal chooser menu (see gif below). This issue is not present in the stable vscode release.

![javascript_debug_bug](https://user-images.githubusercontent.com/17570430/122588770-c590be00-d05f-11eb-81ae-7fb6aac9b106.gif)

I'm wasn't sure if this is an issue with the [vscode-js-debug](https://github.com/microsoft/vscode-js-debug/) extension or with [vscode](https://github.com/microsoft/vscode) so feel free to transfer my issue to the [vscode](https://github.com/microsoft/vscode) GitHub if you seem fit.

**System info**

Version: 1.58.0-insider
Commit: 7dea6d7402b55671410a129661cad24b55aed9f4
Date: 2021-06-18T14:00:35.723Z
Electron: 12.0.11
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.8.0-55-generic

**To Reproduce**
1. Open visual studio code insiders.
2. Open or create a javascript file.
3. Open the integrated terminal using the `ctrl+``` shortcut.
4. Use the terminal add chooser to add a Javascript Debug terminal.
5. See the error appear,
6. Now go to the debug tab `ctrl+shitf+D` and open the Javascript Debug terminal from there
7. Now, there is no error, and the terminal is opened.

**Developer tools logFile**

![image](https://user-images.githubusercontent.com/17570430/122588601-92e6c580-d05f-11eb-8501-27aaacea25d5.png)

**Comment by dalexander-mdsol** [comment]
As a workaround opening the Command Palette and choosing "Debug: JavaScript Debug Terminal" appears to work fine.
