### ISSUE TITLE
Show Javscript Debug Terminal also when `jsx` files are opened

### ISSUE THREAD

**Issue by rickstaa** [microsoft/vscode-js-debug#1039]
**Describe the feature you'd like**

Currently, in the debug tab, the Javascript Debug terminal option is only shown when a js file is opened. I think it would also be a nice addition to show it when a `jsx` file is opened (or give users the ability to enable this option). I added a gif to display the behaviour.

![javascvript_debugger_behavoir](https://user-images.githubusercontent.com/17570430/122615765-65af0d00-d089-11eb-878f-da18c0ede426.gif)

**Additional info**

I added the following to my settings.json in trying to get this behaviour to work:

```json
"files.associations": {
    "*.jsx": "javascriptreact"
}
```

**Comment by connor4312** [comment]
Please verify in [nightly](https://github.com/microsoft/vscode-js-debug#nightly-extension)

**Comment by rickstaa** [comment]
@connor4312 Verified in:

**Version:** 1.58.0-insider
**Commit:** 4c952751a88154ff4c375b1ca78293ab53a5792a
**Date:** 2021-07-06T21:30:49.113Z
**Electron:** 12.0.13
**Chrome:** 89.0.4389.128
**Node.js:** 14.16.0
**V8:** 8.9.255.25-electron.0
**OS:** Linux x64 5.8.0-59-generic

Thanks a lot for fixing this issue.
