### ISSUE TITLE
Can't continue debugging React Native TypeScript app once breakpoint is hit

### ISSUE THREAD

**Issue by lukaspechar** [microsoft/vscode-js-debug#1041]
@lukaspechar After some more investigation, we noticed that the hang occurs while processing the result of the Debugger.getScriptSource method. Based on the CDP Proxy logs, this method was not called in vscode `v1.56.2`.

![image](https://user-images.githubusercontent.com/43934531/122797885-9f218b80-d2c8-11eb-8cbb-141955d1292e.png)

It seems that the problem caused by updating `js-debug` version, which `React Native Tools` uses to debug applications. You may open an issue in the [`js-debug` repository](https://github.com/microsoft/vscode-js-debug). For now, there is a workaround to downgrade the version of your vscode up to version `v1.56.2`. Feel free to contact us if you have any other questions or need our help in solving this problem.

_Originally posted by @JiglioNero in https://github.com/microsoft/vscode-react-native/issues/1598#issuecomment-865252330_

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-js-debug/issues/1033
