### ISSUE TITLE
`process.binding` overwrite invalidate

### ISSUE THREAD

**Issue by sl8520** [microsoft/vscode-js-debug#1042]
Sorry for my bad english.
I am using [http-parser-js](https://github.com/creationix/http-parser-js) to solve the site response malformed.
But using vscode to debug cause `process.binding` overwrite  to fail.
I tried change `launch.json` console to externalTerminal to print debug real command.

`/usr/bin/env 'NODE_OPTIONS=--require "d:/Users/DCT/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js" --inspect-publish-uid=http' 'VSCODE_INSPECTOR_OPTIONS={"inspectorIpc":"\\\\.\\pipe\\node-cdp.20280-25.sock","deferredMode":false,"waitForDebugger":"","execPath":"C:\\Program Files\\nodejs\\node.exe","onlyEntrypoint":false,"autoAttachMode":"always","fileCallback":"C:\\Users\\DCT\\AppData\\Local\\Temp\\node-debug-callback-1469954c63b606a0"}' "C:\\Program Files\\nodejs\\node.exe" .\\index.js`

I tried to remove `'NODE_OPTIONS=--require "d:/Users/DCT/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js" --inspect-publish-uid=http'` take it away, it works perfectly

Its my example code
```
process.binding('http_parser').HTTPParser = require('http-parser-js').HTTPParser
const got = require('got')

async function test() {
    try {
      const res = await got('https://vcbdigibank.vietcombank.com.vn/', {
        method: 'GET',
      })
      console.log(res)
    } catch (error) {
      console.error(error)
    }
}

(async() => {
  await test()
})()
```

**Comment by connor4312** [comment]
I would accept a PR for this, but don't have plans to put a fix in for it.
