### ISSUE TITLE
JS Debug can send the initialized event more than once per session, and sends it before the initialize request is received

### ISSUE THREAD

**Issue by EricCornelson** [microsoft/vscode-js-debug#1043]
See title. We're seeing initialized and thread events come across before the initialized event, which Visual Studio does not like and will force close thes session. I believe this was introduced with https://github.com/microsoft/vscode-js-debug/pull/1010

We are seeing this on every launch in VS, and completely unable to debug on VS 2022 as a result.

[visualstudio-js-debugger.txt](https://github.com/microsoft/vscode-js-debug/files/6719099/visualstudio-js-debugger.txt)

![image](https://user-images.githubusercontent.com/38218905/123491269-2de51f80-d5cb-11eb-9e23-288fd0b71837.png)

**Comment by TylerLeonhardt** [comment]
@connor4312 can we have some verification steps? Perhaps @EricCornelson could verify this on the VS side?

**Comment by rzhao271** [comment]
Confirmed with Eric that the issue has been fixed on their end (author verified).
