### ISSUE TITLE
Auto-attach fails when PID > 1,000,000

### ISSUE THREAD

**Issue by istnv** [microsoft/vscode-js-debug#1045]
**Describe the bug**
I am using vscode on linux. I posted this issue in the legacy repo and was told it was fixed in this (new preview) debugger.  Setting 'Debug > JavaScript: Use Preview' to true, he new debugger exhibits the same symptoms. When the Process ID (PID) is greater than 6 digits, Auto-Attach fails.
After rebooting, *everything works*. 
My system takes about 4 days to start generating PIDs > 1000000.
After that, the attach (Auto, Smart, --inspect only) fails to attach any (fork) subprocesses.

**To Reproduce**
1. Wait for system PIDs to increase past 1000000
2. Load a project with sub-processes
3. Start a debug session
4. ... 

**Log File**
I tried the 'trace' option, nothing shows up on any console. I do see this entry in the log for each fork:
Debugger listening on ws://127.0.0.1:9342/4f214db3-8231-4393-b3bf-3553f16c3c80

**VS Code Version:** 
Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:26:56.255Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.8.0-59-generic

**Additional context**

**Comment by istnv** [comment]
Manually attaching the debugger works OK. It is the auto-attach that fails.

**Comment by connor4312** [comment]
This is a known issue on the old debugger, but I'm not able to reproduce this on Ubuntu in the new debugger:

![](https://memes.peet.io/img/21-07-a6b18851-503a-4788-ac17-a83365464618.png)

Please provide more info on how I can do so. Thanks!
