### ISSUE TITLE
Existing Beakpoints Grayed / Disabled but New Breakpoints OK on Runtime

### ISSUE THREAD

**Issue by chopin2256** [microsoft/vscode-js-debug#1046]
**Describe the bug**
If a breakpoint is placed before runtime, it shows as "activated".  However, when chrome debugger is launched, it becomes deactivated.  Then when you remove and add the breakpoint, it is now activated (during runtime)

**To Reproduce**
1. I'm in Node.  But in frontend Javascript, place a breakpoint.
2. Run the debugger (Chrome deubugger, and request is set to "launch")
3. Check the breakpoint.  It goes from red to gray
4. Now, remove and add the breakpoint.  It is now active

**Log File**
[vscode-debugadapter-6c10013d.json.gz](https://github.com/microsoft/vscode-js-debug/files/6742569/vscode-debugadapter-6c10013d.json.gz)

**VS Code Version:**
- VS Code Version: 1.57.1
- OS Version: Windows 10

**Additional context**
It is very possible this is isolated to my setup.  However, the reason why I think this may be a bug, I never had this problem before.  When updating VS Code to 1.57.1 I started noticing that existing breakpoints are disabled by default during runtime.  But when adding breakpoints (during runtime), everything works as designed.

This is a workflow disrupter since every time I refresh the page, the breakpoints are all deactivated and I have to manually remove and add breakpoints for testing.

Thanks!

**Comment by connor4312** [comment]
Please collect a log file using the instructions in the issue template.

**Comment by chopin2256** [comment]
I've updated my issue with the log file and more info.

**Comment by connor4312** [comment]
It looks like your webroot is set to something like `${workspaceFolder}/../mj/`. Since the URL is `http://yc:8080/mj/...` already, I think you want to make the webroot just ``${workspaceFolder}/..`

**Comment by connor4312** [comment]
It looks like your webroot is set to something like `${workspaceFolder}/../mj/`. Since the URL is `http://yc:8080/mj/...` already, I think you want to make the webroot just `${workspaceFolder}/..` so that that segment is preserved in the path.

It looks like the behavior subdirectories plus sub-paths might not match exactly with the old debugger.

**Comment by chopin2256** [comment]
My file structure is like this:

mj (root folder)
- module1
- module2
- module3
- module4
- mj (webRoot)

module4 has the debugger that has my launch.json.  So I think `${workspaceFolder}/../mj/` should be right.  At this point I am perplexed as there should be no reason why the breakpoints are behaving this way.  The only thing I can think of, is perhaps moving my web files into the "module4" location, but I wanted to separate the frontend web files from the source code modules for maintenance purposes.

**Comment by connor4312** [comment]
What I'm seeing is:

1. Your webroot is set to `G:/mj_vscode/mj/mj/`, and your URL is set to `http://yc:8080/mj/`. This debugger _does not_ use the URL path segment as part of its path arthemtic
2. So we see a breakpoint in the file `g:/mj_vscode/mj/mj/js/Events/MainWindow/_ScoreObjects.js`
3. That maps to the relative path `./js/Events/MainWindow/_ScoreObjects.js`
4. Which then is appended to the URL like `http://yc:8080/js/Events/MainWindow/_ScoreObjects.js`

**Comment by chopin2256** [comment]
Ok, so there is a slight behavioral change (a bit better) by removing the `/mj`.  If I set a breakpoint, then run the debugger, it is still grayed out.  But this time, I can remove and add it again (ok, at this point, same behavior).  But the difference now is, I can keep refreshing the page and the breakpoint is persistent.

So existing breakpoints still are giving me issues, but perhaps slightly better during runtime (and refreshes).  The workflow is still annoying, but doable.  I'm only noticing it more because I am beginning the heavy frontend development portion of my application.

**Comment by connor4312** [comment]
Hm, okay, interesting. I'll take a look at this next week after our current release goes out.

If you're able to, it would be helpful to be able to run your project (either if you put it on Github or provide me access). If that's not possible I'll just do my best to reproduce and replicate locally.

**Comment by chopin2256** [comment]
Thanks!  I understand you need access to my project to help me out with this issue.  However, I may have to put up with the bad workflow if you can't reproduce locally.  My software project is in a very early stage right now and is not open source.

**Comment by connor4312** [comment]
Ok, no worries. I'll see what I can do.

**Comment by chopin2256** [comment]
Totally get it.  What I will do is work with you and generate log files as needed!

**Comment by chopin2256** [comment]
You can probably close this.  I've done a bit of research to get the debugging to work in typescript which is way more efficient and easier to manage the files. Took a bit of work to figure out, but making use of webpack and babel (with a typescript preset) now makes for a beautiful debugging workflow environment.

**Comment by alexr00** [comment]
@connor4312 does this need to be verified?

**Comment by connor4312** [comment]
I think this should still be open since I still want to root cause the original issue
