### ISSUE TITLE
Can you search through breakpoint hover similar to file explorer (within Breakpoint Hover)

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode-js-debug#1049]
When you hover over an object (with breakpoints triggered) you can get a list of properties, sometimes a long list if its a window-like object.

Is it possible to support keyboard-search like file explorer does, so if I start typing a letter it focuses down to that property?

The keyboard is effectively inactive during this point because focus is on the hover and not the editor so it should be safe to allow some keybindings at this stage.

**Comment by connor4312** [comment]
Does this duplicate https://github.com/microsoft/vscode/issues/127716?

**Comment by jasonwilliams** [comment]
Ah yes it does thank you I thought I didn’t create the issue as I didn’t see it here. I wish GitHub sends you a notification when your issue moves.
