### ISSUE TITLE
Incorrect usage of vscode.findTextInFiles while processing outfiles parameter

### ISSUE THREAD

**Issue by nktknshn** [microsoft/vscode-js-debug#1051]
If `outfiles` parameter contains more than one glob pattern then method `vscode.workspace.findTextInFiles` will be called with these patterns concatenated to a comma separated list of the glob patterns, meanwhile `findTextInFiles` expects a single glob pattern as argument. This leads to the grepping utility `ripgrep` being called in such a way:

Having `outfiles` like
```js
{
  //...
  "outFiles": [
          "${workspaceFolder}/out/**/*.js",
          "${workspaceFolder}/vscode/extensions/debug-auto-launch/out/**/*.js"
        ],
  //...
}
```

console output while running the `extensionHost` configuration

```
DEBUG SearchService#search /home/user1/Workspace/thirdparty/vscode/node_modules/vscode-ripgrep/bin/rg --hidden --case-sensitive -g '!*' -g '/out' -g '/out/**' -g '/out/**/*.js, vscode' -g '/out/**/*.js, vscode/extensions' -g '/out/**/*.js, vscode/extensions/debug-auto-launch' -g '/out/**/*.js, vscode/extensions/debug-auto-launch/out' -g '/out/**/*.js, vscode/extensions/debug-auto-launch/out/**' -g '/out/**/*.js, vscode/extensions/debug-auto-launch/out/**/*.js' --max-filesize '17179869184' --no-ignore --follow --crlf --fixed-strings --no-config --no-ignore-global --json -- 'sourceMappingURL' '.'
 - cwd: /home/user1/Workspace/thirdparty/vscode-js-debug
```

This command returns matches for only `"${workspaceFolder}/out/**/*.js"`. Also, these matches will be filtered out as not matching the initial glob pattern `/out/**/*.js, /vscode/extensions/debug-auto-launch/out/**/*.js`

**VS Code Version:** OSS Dev, 1.58.0

The bug I stumbled upon while trying to fix unresolved source maps in my project. This bug wasn't the reason in my case, but it's obvious that this should be fixed.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/104889
