### ISSUE TITLE
Proper TypeScript debugging fails in Next.js TypeScript example

### ISSUE THREAD

**Issue by michaelschufi** [microsoft/vscode-js-debug#1052]
## Bug Info
Hi

I have problems debugging a simple Next.js typescript example.
I have opened an issue in the Next.js repo (https://github.com/vercel/next.js/issues/26726). 
But since it seems like a platform specific problem, I am here now 🙂.

Below, I repeat what I have already written in the aforementioned issue - I hope that is okay.

### Describe the Bug

After attaching a debugger, as described in the Next.js docs (https://nextjs.org/docs/advanced-features/debugging), the breakpoints set are "unbound":

![image](https://user-images.githubusercontent.com/2805598/123804478-8b3fe000-d8ed-11eb-8106-ed86e7de5d0a.png)

Additionally, using `debugger` statements does not pause the execution at the typescript file but opens the compiled webpack js file instead:

![image](https://user-images.githubusercontent.com/2805598/123804979-fbe6fc80-d8ed-11eb-9004-905e65ced840.png)

### Expected Behavior

I expect the following behavior:

- Breakpoints can be set using VS Code and are "bound", no `debugger` statements are strictly necessary.
- Debugging can occur on the typescript level. Compiled source files are unusable if the code is slightly more complex.

### To Reproduce

1. Use create-next-app to set up the project  
   `npx create-next-app --example custom-server-typescript custom-server-typescript-app --use-npm`
2. Add the `NODE_OPTIONS` env variable to the nodemon exec command line.
   ```json
   // from
   "exec": "ts-node --project tsconfig.server.json server/index.ts",
   // to
   "exec": "NODE_OPTIONS='--inspect' ts-node --project tsconfig.server.json server/index.ts",
   ```
3. Add the following `getStaticProps` function to the `pages/index.tsx` file
   ```
   import { GetStaticProps } from "next";

   export const getStaticProps: GetStaticProps = (_) => {
     const a = 2;
     const x = a + 3;
 
     console.log(x);
     debugger;
 
     return {
       props: {
         x,
       },
     };
   };
   ```
4. Start the server with `npm run dev`
5. Create VS Code launch.json file:
   ```json
   {
     "version": "0.2.0",
     "configurations": [
       {
         "type": "node",
         "request": "attach",
         "name": "Launch Program",
         "skipFiles": ["<node_internals>/**"],
         "port": 9229
       }
     ]
   }
   ```
6. Attach the debugger
7. Set a breakpoint on the `console.log(...)` statement
8. Make a request to the index page.

Observe the above described behaviors.

### Log File

[vscode-debugadapter-03371ab0.json.gz](https://github.com/microsoft/vscode-js-debug/files/6775338/vscode-debugadapter-03371ab0.json.gz)

## Additional context

I experienced this on two different Windows Systems. Both with WSL 2 Ubuntu. I could also reproduce it using only Windows instead of WSL.

### VS Code Version
1.57.1

### Next.js version

11.0.1

### Node.js version

14.17.1

### What browser are you using?

Firefox (but irrelevant)

### What operating system are you using?

Linux Ubuntu (WSL)

### Debug Console warnings
```
Could not read source map for file:///home/michael/dev/custom-server-typescript-app/node_modules/@next/react-refresh-utils/internal/ReactRefreshModule.runtime.js: ENOENT: no such file or directory, open '/home/michael/dev/custom-server-typescript-app/node_modules/@next/react-refresh-utils/internal/ReactRefreshModule.runtime.js.map'
Could not read source map for file:///home/michael/dev/custom-server-typescript-app/node_modules/@next/react-refresh-utils/loader.js: ENOENT: no such file or directory, open '/home/michael/dev/custom-server-typescript-app/node_modules/@next/react-refresh-utils/loader.js.map'
Could not read source map for file:///home/michael/dev/custom-server-typescript-app/node_modules/@next/react-refresh-utils/ReactRefreshWebpackPlugin.js: ENOENT: no such file or directory, open '/home/michael/dev/custom-server-typescript-app/node_modules/@next/react-refresh-utils/ReactRefreshWebpackPlugin.js.map'
Could not read source map for file:///home/michael/dev/custom-server-typescript-app/node_modules/next/dist/compiled/path-to-regexp/index.js: ENOENT: no such file or directory, open '/home/michael/dev/custom-server-typescript-app/node_modules/next/dist/compiled/path-to-regexp/index.js.map'
Could not read source map for file:///home/michael/dev/custom-server-typescript-app/node_modules/typescript/lib/typescript.js: ENOENT: no such file or directory, open '/home/michael/dev/custom-server-typescript-app/node_modules/typescript/lib/typescript.js.map'
Could not read source map for internal/deps/acorn/acorn/dist/acorn.js: Invalid URL: internal/deps/acorn/acorn/dist/acorn.js
```

**Comment by connor4312** [comment]
Thanks for the issue and repro steps. What's happening is that:

1. You use `ts-node` to load server/index.ts
2. Next.js compiles your application with webpack to plain JavaScript files, into the `.next` directory
3. Your application is loaded
4. `ts-node` preprocess JavaScript files as well. But when it does this, it blows away the sourcemap which webpack creates
5. This means that, although the debugger is following the sourcemap, it's following it from ts-node's version of `.next/server/pages.js` to the compiled version of the same file, instead of the real source file.

The ideal fix would be for ts-node/TypeScript to "follow" the source back to its original location--like Webpack does if it recompiles/bundles files--but this is probably not going to be a priority since TS is usually the first step in the compilation process, not the last one.

The easiest fix for this, which will also make your app launch faster, is to configure Nodemon to not re-compile JavaScript files by adding ` --ignore \"\\.js$\" ` to its exec.

**Comment by michaelschufi** [comment]
@connor4312 Interesting!
I'll check the fix in a moment. Just a quick question:
Why is it working for this guy?
https://github.com/vercel/next.js/issues/26726#issuecomment-872993859

**Comment by connor4312** [comment]
I'm not sure why it works for him honestly 😛 Maybe something in his environment is emitting things slightly differently

**Comment by heywoodj** [comment]
Hello, I am also struggling with this issue. I have created a default project with 'create-next-app' with version 13.4.

Could someone elaborate on the fix below. I can't workout where, or how, to configure nodemon with the --ignore flag.

'The easiest fix for this, which will also make your app launch faster, is to configure ts-node to not re-compile JavaScript files by adding --ignore \"\\.js$\" to the nodemon exec.'

**Comment by michaelschufi** [comment]
@heywoodj I commented on what I did here (in `nodemon.json`):
https://github.com/vercel/next.js/issues/26726#issuecomment-875792412

**Comment by michaelschufi** [comment]
It's a config file for a certain project. Here's the official documentation:
https://github.com/remy/nodemon#config-files

**Comment by heywoodj** [comment]
@michaelschufi Thanks for the guidance, doesn't seem to be working for me.

I've tried adding a `nodemon.json` containing the following in my project root directory:
{
     "exec": "NODE_OPTIONS='--inspect' ts-node --project <tsconfig.json location> <tsx location>
}

also tried adding to a `nodemonConfig` section in my `package.json`. If you did anything different let me know, thanks.
