### ISSUE TITLE
CDP proxy server no longer sends CDP events if target navigates away from launch.json url

### ISSUE THREAD

**Issue by bgoddar** [microsoft/vscode-js-debug#1054]
**Describe the bug**
I'm pretty sure this is similar to the behavior we saw when attaching devtools to a paused target: we no longer receive CSS events after navigating to a new page, which causes our styles pane to appear empty:
![image](https://user-images.githubusercontent.com/42152559/125134433-3a35a600-e0bc-11eb-8d49-f75340d255ce.png)

**To Reproduce**
1. Use a "Launch Edge" config to launch a debug session
2. Use the inspect button to attach devtools
3. In the launched browser, navigate to a new page (bing.com, etc)
4. Observe that Devtools updates the DOM, but not styles pane. Likely due to missing CSS stylesheet added events:
![image](https://user-images.githubusercontent.com/42152559/125134550-63563680-e0bc-11eb-8293-f06d70ce6082.png)

**Log File**

Stable/insiders

**Comment by connor4312** [comment]
Hm, I'm having some trouble reproducing this: https://memes.peet.io/img/21-07-ffc09507-891a-42b8-8550-a26468389780.mp4

Are there specific websites this happens on?

**Comment by bgoddar** [comment]
Interesting. I had this happening on a local project. I'll upload it here and see if you can repro

**Comment by bgoddar** [comment]
[Simplesite.zip](https://github.com/microsoft/vscode-js-debug/files/6794175/Simplesite.zip)

**Comment by bgoddar** [comment]
Requires `npm install` and `npm start` before launching the debug target

**Comment by bgoddar** [comment]
Lmk if you can't repro and we can sync next week

**Comment by connor4312** [comment]
I could repro this pretty consistently by navigating to Twitter.com. It seems method calls are still going through, and I was able to get a log of it: https://memes.peet.io/img/vscode-debugadapter-3b33c693.json.gz The thing I see is that CSS.takeComputedStyleUpdates started failing -- the browser didn't respond to one of the calls, and the next one failed with the message that a previous computation is in progress.

**Comment by bgoddar** [comment]
Interesting. I can take a closer look next week. Might be a blink/CDP bug if that's the case. If so I'll file one and report back here

**Comment by bgoddar** [comment]
You are right. I can repro the same behavior in the inbox tools in both Edge and Chrome intermittently. I'll file a bug on chromium

**Comment by connor4312** [comment]
Ok, I will close this one as an upstream issue then. Thanks for looking into it.

**Comment by bgoddar** [comment]
For posterity: filed https://bugs.chromium.org/p/chromium/issues/detail?id=1237926 to track
