### ISSUE TITLE
EACCESS Read-only Workspace Error on NixOS

### ISSUE THREAD

**Issue by dustinlacewell** [microsoft/vscode-js-debug#1057]
**Describe the bug**
On NixOS, all package files are stored in a read-only file-system. Something in `vscode-js-debug` at some point copies a file, from the nix store (which is read-only) into the user's configuration. This works the first time. But since the permissions on the file are read-only, the next time this is attempted, the previous file cannot be overwritten.

Error activating auto attach: Error: EACCES: permission denied, copyfile '/nix/store/s81m8m4p355x54snv6fnc56pw75vlprs-vscode-1.58.0/lib/vscode/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js' -> '/home/ldlework/.config/Code/User/workspaceStorage/ed6365eb04d72d5abb85f7871ffb763d/ms-vscode.js-debug/bootloader.js'

This only happens when workspaces are being used.

Is there a change (here upstream) that could be made? I've discussed the issue https://github.com/NixOS/nixpkgs/issues/130590# but NixOS can't really do anything about an application copying a file out of the store, like making it writable or whatnot.

**To Reproduce**
1. Use NixOS or Nix
2. Install vscode
3. Use auto-attach
3. Start a node process while in a workspace
4. Stop debugging, and repeat 3.

**VS Code Version:** 1.58.2

**Comment by dustinlacewell** [comment]
Would this change be sufficient?

```typescript
    const bootloaderPath = path.join(storagePath, 'bootloader.js');
    try {
      await this.fs.mkdir(storagePath);
    } catch {
      // already exists, most likely
      if (await path.exists(bootloaderPath)) {
        await this.fs.unlink(bootloaderPath);
      }
    }

    await Promise.all([
      this.fs.copyFile(bootloaderDefaultPath, bootloaderPath),
      this.fs.copyFile(watchdogPath, path.join(storagePath, 'watchdog.bundle.js')),
    ]);
```

I've added this block:
```
      if (await path.exists(bootloaderPath)) {
        await this.fs.unlink(bootloaderPath);
      }
 ```

**Comment by connor4312** [comment]
I'm not familiar at all with NixOS. Is the read-onlyness something we can detect via an `lstat` call? If so, can we have our own `copyFile` utility function that stats and then either copies or unlinks and then copies? Or, fall back to the lstat path only if the initial copy fails. That would prevent overhead being added for other OS'.

**Comment by dustinlacewell** [comment]
Basically the only important detail here is that all package files (so vscode files, extension files) they're all going to be read-only. So when we use them to copy, they'll be written as read-only too, unless we change that.

So what you're suggesting is basically "wrap everything in a try/catch and unlink/try again if it fails"? Or something else?

**Comment by connor4312** [comment]
> wrap everything in a try/catch and unlink/try again if it fails

Yep

**Comment by connor4312** [comment]
I pushed a fix for this, please try the [nightly extension](https://github.com/microsoft/vscode-js-debug#nightly-extension) in a few days (note that it requires [VS Code Insiders](https://code.visualstudio.com/insiders/)) and let me know if it's resolved. Thanks!

**Comment by dustinlacewell** [comment]
Hello, I am unable to enable the nightly extension:

![image](https://user-images.githubusercontent.com/53952/128419293-d87725a3-0daa-4fc0-8f0b-bb026153a508.png)

![image](https://user-images.githubusercontent.com/53952/128419376-f8216970-90da-4753-9121-54bbb2483694.png)

**Comment by connor4312** [comment]
The next Insiders that's compatible with the nightly should be out within 24h

**Comment by rzhao271** [comment]
Hi @dustinlacewell, has the issue been fixed for you?
