### ISSUE TITLE
Debugger for Chrome causing issues when restarting with dev tools open.

### ISSUE THREAD

**Issue by DJ4ddi** [microsoft/vscode-js-debug#1058]
**Description**
I am using an Electron configuration with a main process accessed using node launch and a renderer process using chrome attach. When sending a restart command to the Chrome debugger while the dev tools are open in the Electron window, both break with the error below, which seems to cause multiple other components to fail (those issues are not in the provided log, as I didn't touch anything after the restart). When reloading the window using F5 from Electron, everything works fine. The restart command also works fine when the dev tools are not open.

The behavior is working as expected using the legacy debugger.

Error messages (appears over 50 times):
`
[12460:0719/135238.225:ERROR:CONSOLE(67)] "Uncaught TypeError: Cannot read property 'dispatchMessage' of undefined", source: devtools://devtools/bundled/devtools_compatibility.js (67)
`

**Files**
[vscode-debugadapter-devtoolerrors-launcher.gz](https://github.com/microsoft/vscode-js-debug/files/6840463/vscode-debugadapter-devtoolerrors-launcher.gz)
[vscode-debugadapter-devtoolerrors-renderer.gz](https://github.com/microsoft/vscode-js-debug/files/6840465/vscode-debugadapter-devtoolerrors-renderer.gz)
[launch.zip](https://github.com/microsoft/vscode-js-debug/files/6840519/launch.zip) (Launch configurations for both)

**Versions**
VSCode: 1.58.2
Node.js: 14.16.0
Electron: 12.0.9
Debugger for Chrome 4.12.12

**Comment by connor4312** [comment]
I'm not able to reproduce this, but I've put in a fix that may resolve the issue for you. Please try the [next nightly](https://github.com/microsoft/vscode-js-debug#nightly-extension) and let me know whether it's fixed for you.

**Comment by DJ4ddi** [comment]
Issue seems to be resolved on nightly v2021.7.1917.

**Comment by isidorn** [comment]
Adding verified per @DJ4ddi comment. Thanks!
