### ISSUE TITLE
Debug console does not run commands.

### ISSUE THREAD

**Issue by DJ4ddi** [microsoft/vscode-js-debug#1059]
**Description**
I am using an Electron configuration with a main process accessed using node launch and a renderer process using chrome attach. My goal is to run commands from the debug console as I would in the dev tools of the Electron window (where everything is working).

The VSCode debug console does not auto-complete commands, does not execute any commands and also does not display commands that are executed through the Electron console. It does show the other output, captured through `outputCapture: "std"` option. There are no obvious errors in the VSCode console.

Electron console:
![grafik](https://user-images.githubusercontent.com/1696102/126155403-4333e84d-155b-4816-ba59-049057da842d.png)

VSCode console:
![grafik](https://user-images.githubusercontent.com/1696102/126155459-b4b4cd6f-8132-4926-b90c-78a3409912a4.png)

**Files**
[vscode-debugadapter-console-launcher.gz](https://github.com/microsoft/vscode-js-debug/files/6840511/vscode-debugadapter-console-launcher.gz)
[vscode-debugadapter-console-renderer.gz](https://github.com/microsoft/vscode-js-debug/files/6840512/vscode-debugadapter-console-renderer.gz)
[launch.zip](https://github.com/microsoft/vscode-js-debug/files/6840519/launch.zip) (Launch configurations for both)

**Versions**
VSCode: 1.58.2
Node.js: 14.16.0
Electron: 12.0.9
Debugger for Chrome 4.12.12

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/128400
