### ISSUE TITLE
Detect what process is using 9222 when it's taken

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-js-debug#1061]
I was struggling to figure out why VS Code debugging wasn't working, the first issue was that 9222 was taken by an unrelated app. If we fail to connect can we run `Get-Process -Id (Get-NetTCPConnection -LocalPort 9222).OwningProcess` and the linux/mac equivalent for the user?

**Comment by connor4312** [comment]
Not planning on taking this, debugging in the default settings of js-debug always uses pipes or a system-assigned port (port 0) and this is only a problem is really advanced cases, like VS Code
