### ISSUE TITLE
Could not retrieve the username after successful auth code exchange. Due to: connect ETIMEDOUT 101.53.161.118:443

### ISSUE THREAD

**Issue by MaheswarReddy3735** [microsoft/vscode-js-debug#1062]
Could not retrieve the username after successful auth code exchange.
Due to: connect ETIMEDOUT 101.53.161.118:443 i facing this error

**Comment by connor4312** [comment]
This is probably an issue with your code, you're seeing a timeout connecting to whatever that IP address is. The debugger doesn't participate ion this.
