### ISSUE TITLE
Take ownership of the default node, chrome, extensionHost, and msedge types

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#1065]
This month we are (finally) removing the legacy Node debug extensions from being built-in. All old debug extensions will still be accessible in the marketplace, but they (including the Chrome and Edge debuggers) will require the `legacy-` prefix in the launch "type" to use. The `debug.javascript.usePreview` setting is going away.

`js-debug` will take ownership of the default launch types, and will no longer require the `pwa-` prefix. However, we will continue allowing the "pwa-" prefix in launch.json's and the "redirection" logic will ensure launched sessions are prefixed, to avoid breaking extensions that depend on the `type`.

**Comment by bpasero** [comment]
Steps?

**Comment by connor4312** [comment]
1. Create a launch config using each of the listed types
2. Set `trace: true` in the config
3. Verify that the path logged in the Debug Console ends with `.json.gz` (easiest indicator of the new debugger)
4. Do the same with types using a `pwa-` prefix, and verify that it still works

**Comment by weinand** [comment]
I've verifed:
- setting `debug.javascript.usePreview` is no longer known 
- `js-debug` is available via the debug types: node, extensionHost, chrome, msedge and the corresponding `pwa-` prefixed types.
-  installing the deprecated node debug extensions on the Marketplace (node-debug and node-debug2) does not interfere with `js-debug`: the deprecated debug types are only available via the `legacy-` prefix. I could still debug node.js programs for node.js versions < 8.0.

**Comment by liesauer** [comment]
cannot switch back to legacy chrome debugger using `legacy-chrome`.
it says doesn't support `legacy-chrome` type.
![image](https://user-images.githubusercontent.com/8676741/192178213-b4faad3f-a729-46a7-bd0f-75b72648a929.png)

@connor4312
