### ISSUE TITLE
Launching with debugger results in chrome tab crashing Error code: STATUS_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by DzmitryFil** [microsoft/vscode-js-debug#1066]
Launching with debugger results in chrome tab crashing Error code: STATUS_ACCESS_VIOLATION
I can attach debugger if chrome started without debugger, but running standard launch with debugger task result in
"Aw, Snap!" page, with Error code: STATUS_ACCESS_VIOLATION

To Reproduce: click Run with debugger (or press F5)

Log file: 
[vscode-debugadapter-ae661be7.json.gz](https://github.com/microsoft/vscode-js-debug/files/6939778/vscode-debugadapter-ae661be7.json.gz)

I don't i had this problem before last update of vscode (current version is 1.52).
I tried updating debugger extension to nightly with no success.
The same STATUS_ACCESS_VIOLATION when launching Edge

**Comment by connor4312** [comment]
This is an issue in Chromium -- if none of [this existing bugs for STATUS_ACCESS_VIOLATION](https://bugs.chromium.org/p/chromium/issues/list?q=STATUS_ACCESS_VIOLATION&can=2) cover your scenario, please use the "New Issue" button on that page to open a bug. Thanks!
