### ISSUE TITLE
Breakpoints are still active after deletion until you also refresh the debug session

### ISSUE THREAD

**Issue by codepo8** [microsoft/vscode-js-debug#1067]
When you set a breakpoint, it works as you would expect. But if you unset it and interact with the browser, it still breaks where the breakpoint was until you refresh the debug session. Not sure if that is a Mac only issue.

**To Reproduce**
Set a breakpoint
Interact with the page to trigger it
Go through the debug process
Delete breakpoint
Interact with the page again
Breakpoint still triggers

**Log File**
Attached.
[vscode-debugadapter-28927180.json.gz](https://github.com/microsoft/vscode-js-debug/files/6941678/vscode-debugadapter-28927180.json.gz)

**VS Code Version:** Version: 1.58.2 (Universal)

**Additional context**

See attached video

https://user-images.githubusercontent.com/13508/128421073-c1076c07-15bd-470a-bd13-aa450c077184.mp4

**Comment by connor4312** [comment]
Thanks for the log, this appears to be a V8/Chromium issue. I've opened a bug here, if you have any extra info to add please do so there: https://bugs.chromium.org/p/chromium/issues/detail?id=1237217
