### ISSUE TITLE
The debug console is slow when working with pwa-node

### ISSUE THREAD

**Issue by catan271** [microsoft/vscode-js-debug#1068]
**Describe the bug**
I have just found that the new JavaScript debugger is slow when I launch Node.JS app.
The default configuration for Node.js is
```
"configurations": [
        {
            "type": "pwa-node",
            "request": "launch",
            "name": "Launch Program",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}\\src\\index.js"
        }
```

The debug console do logging with long delay, like this video:
[https://drive.google.com/file/d/1w6EEpYfDrv67RhKYm7aghf9Spi6kvBm9/view?usp=sharing](https://drive.google.com/file/d/1w6EEpYfDrv67RhKYm7aghf9Spi6kvBm9/view?usp=sharing)

But when I change the type to node:
`"type": "node"`
the debug console run way faster:
[https://drive.google.com/file/d/1OGeFpXrAPj2KspMwnbvPf6SVufHgRooh/view?usp=sharing](https://drive.google.com/file/d/1OGeFpXrAPj2KspMwnbvPf6SVufHgRooh/view?usp=sharing)

**To reproduce**
1.  Open project folder in VSCode
   (here is my project folder zip <https://drive.google.com/file/d/14jR3RJWnLKFZezmMir6qSSOMUIqGMd6s/view?usp=sharing>)
2.  Run without debug (`ctrl` + `F5`)
3.  Open postman
4.  Make a GET request to `localhost:3000/users/45645132131` or any id string after "users/"
5.  Come back to VSCode and wait for the id to be logged in debug console
6.  In lauch.json, change `"type": "node"` and do the same steps above then see the difference in those to debugger

**VSCode version:** 1.59.0 (user) stable Windows 10 64bit
**NodeJS version:** 14.16.0

**Additional text:**
Unfortunately, Node (legacy) was deprecated and is going to be replaced by this new debugger (pwa-node). Is this a bug and will it be fixed in the future? I'm really sad to know that the simple Node debugger was to deprecate.

**Comment by connor4312** [comment]
Please share a log and/or reproduction using the instructions in the issue template. Thanks!

**Comment by catan271** [comment]
Can you please show me where to get those instructions, and where the issue template is?

**Comment by catan271** [comment]
I have update the report. You can you any other tools besides Postman to make that GET request in step 3 and 4

**Comment by connor4312** [comment]
Thanks for the sample, but I don't repro the issue, it's [instant for me](https://memes.peet.io/img/2ecaf349-37b1-4a01-8b98-34db673b43ab.mp4). Can you please share a log file so I can see more of what's happening on your machine?

**Comment by catan271** [comment]
Is this the log files I should collect? <https://drive.google.com/file/d/1kUVi8TBAq290LFnr9PV6WmtSXbMafJLS/view?usp=sharing>

**Comment by connor4312** [comment]
It's in the issue template:

> If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
> ⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by catan271** [comment]
Thanks for the instructions. Here is the log file
[vscode-debugadapter-6c5037f9.json.gz](https://github.com/microsoft/vscode-js-debug/files/6948385/vscode-debugadapter-6c5037f9.json.gz)

**Comment by connor4312** [comment]
Thanks, this'll be fixed in the next [nightly release](https://github.com/microsoft/vscode-js-debug#nightly-extension) on Monday (note that [VS Code Insiders](https://code.visualstudio.com/insiders/) is required).
