### ISSUE TITLE
[question] how can I get source code when I debug javascript in vscode?

### ISSUE THREAD

**Issue by ShroXd** [microsoft/vscode-js-debug#1070]
## Overview

I'm trying to debug the source code of react in vscode.
Since source map, if I debug the code in Chrome devtools, I can see the source code. But when I try to debug it in vscode by using js-debug, it shows me the compiled code.
How can I get the source code when I debug javascript code in vscode?

### The launch.json & script
```
{
  "name": "Launch via npm",
  "type": "node",
  "request": "launch",
  "cwd": "${workspaceFolder}",
  "runtimeExecutable": "npm",
  "runtimeArgs": ["run-script", "test"],
}

"test": "node ./scripts/jest/jest-cli.js --watch ReactDOMOption",
```

### Screenshot

| VScode | Chrome DevTools |
| :-: | :-: |
|<img width="2602" alt="vscode" src="https://user-images.githubusercontent.com/48713853/128588468-973830fa-d311-483a-904d-af634a5e1da7.png">|<img width="1722" alt="chrome" src="https://user-images.githubusercontent.com/48713853/128588474-e88f078f-df22-44f0-bd10-032e66b19669.png">|

**Comment by connor4312** [comment]
This can be configured with the `resolveSourceMapLocations` options in your launch.json
