### ISSUE TITLE
Documentation of known issue with userDataDir

### ISSUE THREAD

**Issue by AntonOfTheWoods** [microsoft/vscode-js-debug#1072]
**Is your feature request related to a problem? Please describe.**

https://github.com/microsoft/vscode/issues/120872

Mentions that it is a known issue that it is not possible to launch a browser in the default profile if a process is already launched.

https://github.com/microsoft/vscode-js-debug/blob/main/OPTIONS.md#pwa-chrome-launch (section userDataDir) makes no mention of this.

As https://github.com/microsoft/vscode/issues/120872 acknowledges it is a known issue and is closed without suggesting it will be fixed, should this not be documented in the OPTIONS.md to avoid others wasting time?

**Comment by Manish-Giri** [comment]
Hello, may I please take this up?

**Comment by connor4312** [comment]
Sure, the description can be found here: 

https://github.com/microsoft/vscode-js-debug/blob/0e6523778b404d9b183deac3cc83ec4b152a17f6/src/build/strings.ts#L108-L109
