### ISSUE TITLE
Issues with requirejs

### ISSUE THREAD

**Issue by highvoltz** [microsoft/vscode-js-debug#1073]
**Describe the bug**
When using requirejs for importing modules, breakpoints placed in modules other than the executing one will show as unbound, but when they get hit, a new read-only version of the module opened. 

Another issue is when the running the debugger while the read-only module is still open, a 'Save As' dialog is shown.

I have tested using the in-preview debugger shipped with VSCode 1.59 and again with the nightly build; both have same issue.

**To Reproduce**
1. Extract my attached demo source, run 'npm install' in extract folder and open workspace with VSCode
2. Place a breakpoint in main.js at line number 12
3. Place a breakpoint in utils.js at line number 5
4. Run the debugger (F5)
5. When breakpoint hits the one in main.js, switch over to the utils.js and observe that breakpoint is shown as unbound
6. Continue the debugger (F5) and observe a new read-only (generated?) utils.js file open up a break at line number  5
7. Without closing any tabs, remove breakpoints, restart debugger and observe a 'Save As' dialog open

**Log File**
[vscode-debugadapter-db700fc1.json.gz](https://github.com/microsoft/vscode-js-debug/files/6963690/vscode-debugadapter-db700fc1.json.gz)

**Demo Source**
[demo.zip](https://github.com/microsoft/vscode-js-debug/files/6963707/demo.zip)

**VS Code Version:** 1.59

**Comment by connor4312** [comment]
You can fix this by setting `"enableContentValidation": false,` in your launch.json.
