### ISSUE TITLE
Launching from Github Codespaces will not connect successfully to the debugger.

### ISSUE THREAD

**Issue by fungiboletus** [microsoft/vscode-js-debug#1077]
**Describe the bug**
Launching pwa-msedge or pwa-chrome from a Github Codespace will start the browser but the connection to the debugger will fail with a timeout.

I cannot see any port forwarding from the host in the ports tabs. If I use the now deprecated (and a bit broken) extensions for chrome or edge, they do connect to the debugger and I can see a port forward from my host to github codespaces.

**To Reproduce**
1. Create a Github Codespace
2. Set the following launch configuration
```json
{
  "type": "pwa-msedge",
  "request": "launch",
  "name": "Demo bug report",
  "url": "http://perdu.com"
}
```
3. Run and debug

**VS Code Version:** 1.56.0

**Comment by fungiboletus** [comment]
It seems that I have the same problem using WSL2 and VsCode.

**Comment by connor4312** [comment]
You're on a old version of VS Code. Please update to 1.59.0 and let me know if the problem persists.

**Comment by fungiboletus** [comment]
Indeed, sorry about that.

So with version `1.59.0` it looks like the port is forwarded, but it's still not connecting correctly to the browser.

The only error I can see in the trace log is the following:
```json
{
	"tag": "cdp.send",
	"timestamp": 1628791467553,
	"metadata": {
		"connectionId": 7,
		"message": {
			"id": 1001,
			"method": "Target.attachToBrowserTarget",
			"params": {}
		}
	},
	"level": 0
}
{
	"tag": "internal",
	"timestamp": 1628791467554,
	"message": "pipeRead error",
	"metadata": {
		"error": {
			"message": "incorrect header check",
			"stack": "Error: incorrect header check\n\tat Zlib.zlibOnError [as onerror] (zlib.js:181:17)"
		}
	},
	"level": 3
}
```

**Comment by connor4312** [comment]
Oh, yes. This duplicates https://github.com/microsoft/vssaas-planning/issues/2013

**Comment by fungiboletus** [comment]
Alright. microsoft/vssass-planning is a private repository but I guess this will be fixed eventually. Have a nice day.

**Comment by jarrodldavis** [comment]
I'm also running into this issue and would like a publicly available GitHub Issue that I can watch for updates so I know when this issue is resolved.

**Comment by connor4312** [comment]
Github reports that this should now be fixed
