### ISSUE TITLE
Can we add the insights into values of lines you get in the browser breakpoints?

### ISSUE THREAD

**Issue by codepo8** [microsoft/vscode-js-debug#1079]
![image](https://user-images.githubusercontent.com/13508/129612403-d9c074a0-a676-4239-acc2-b22e9b200fef.png)

In the browser developer tools you get evaluations of the value of each line when you do breakpoint debugging (see the brown parts in the screenshot). This is incredibly useful and would be a nice to have in the VS Code debugger, too,.

**Comment by connor4312** [comment]
Check out the `debug.inlineValues` setting 🙂 

We have a heuristic used today to generate evaluated expressions, but that will be improved in the next release with https://github.com/microsoft/TypeScript/issues/43449
