### ISSUE TITLE
Edge Devtools User is requesting different autocomplete behavior in console

### ISSUE THREAD

**Issue by bgoddar** [microsoft/vscode-js-debug#1081]
**Is your feature request related to a problem? Please describe.**
User is requesting both "Enter" and "Tab" keys can be used to accept an autocomplete option, instead of requiring Tab then Enter.

Original Bug contents below:
Hi, this one if form UX department.

Behavior of typeahead/autocomplete behavior if debug console is different from behavior of intellisense in vscode or console typeahead in the browser. It requires user to hit Tab to complete the suggestion and then enter to accept, while everywhere else enter (along with tab) works to accept/complete the suggestion. In the browser second 'Enter' hit causes execution.

Would be great to sync the interactions, because ... muscle memory :)

![image](https://user-images.githubusercontent.com/42152559/130129475-49e62d06-c41a-4ed2-ba9d-4859bcee4b53.png)

**Describe the feature you'd like**

**Comment by bgoddar** [comment]
Original issue: https://github.com/microsoft/vscode-edge-devtools/issues/457

**Comment by connor4312** [comment]
This is intentional; feel free to weigh in on https://github.com/microsoft/vscode/issues/108439#issuecomment-871521843
