### ISSUE TITLE
Unable to debug with "unbundled" build tools (Vite, Snowpack)

### ISSUE THREAD

**Issue by tuner** [microsoft/vscode-js-debug#1086]
# Describe the bug

If I set a breakpoint through VSCode, Chrome pauses on the correct file and line. However, VSCode opens a read-only editor that has the file delivered by the [Vite](https://vitejs.dev/) development server. The breakpoints box displays an odd path that begins with a slash and the hostname:

![image](https://user-images.githubusercontent.com/399972/130334066-2e549b0f-f994-449a-b3ca-c0e51aa9a6a1.png)

# Details

I created a simple vanilla js test project, which includes my `launch.js` file: https://github.com/tuner/vite-project-debugging

I also tried various `pathMapping` configurations but they had no effect.

In principle, Vite dev server just delivers unbundled javascript files, and in my simple example, no compilation/transpilation is performed. It just rewrites the imports of npm dependencies (there are none) and does some tricks to allow for importing css files, etc. I tried debugging when the files are served as purely static files (using Python's http.server) and setting the breakpoint seemed to work perfectly. I don't know what's going on. 

I stumbled upon the same issue with [Snowpack](https://www.snowpack.dev/) some months ago. Unfortunately, StackOverflow offered no help: https://stackoverflow.com/questions/66221405/how-to-setup-pathmapping-in-vscode-to-debug-a-snowpack-application

**VS Code Version:** 

Version: 1.59.1
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:53:52.479Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 19.6.0

**Comment by connor4312** [comment]
[Sourcemaps](https://vitejs.dev/config/#build-sourcemap) are required when working with any bundler or code transformer; it looks like your repo is not set up to generate them.

**Comment by tuner** [comment]
Ok. The `build.sourcemap` option only affects bundling (when preparing a release), not the unbundled development, which supports fast hot module reloads and other cool stuff. It appears that Vite doesn't create source maps for plain JS files: https://github.com/vitejs/vite/issues/80#issuecomment-625328799. It kind of makes sense because plain JS files can be debugged with browser dev tools just fine. However, this appears to be a problem with the VSCode debugger.

I'm not too familiar with source map internals or debugger protocols, but I envision two possible solutions:

1. Vite (and Snowpack) should create source maps during unbundled development. 
2. VSCode debugger could support transformed files where only the imports have been modified. File names, line numbers, symbols, everything else is intact.

I don't know how feasible either of these options is. Still, apparently, it's not currently possible to use VSCode debugger with Vite (or Snowpack). Thoughts?

**Comment by connor4312** [comment]
You can set `enableContentValidation: false` [options](https://github.com/microsoft/vscode-js-debug/blob/main/OPTIONS.md#enablecontentvalidation-1) to avoid opening the readonly editor. But really they should create sourcemaps since that's the only way mapping can be guarenteed -- the fact that content validation fails indicates they _are_ transforming the source in some way which is something that 'should' result in a sourcemap being generated.

**Comment by tuner** [comment]
Thanks, Connor! That seems to do the trick! I didn't notice that option.

Anyway, I'll file a Vite feature request.

**Comment by softboy99** [comment]
@tuner Is there any PR we can track? Are vite team tracking it?

**Comment by tuner** [comment]
@softboy99 No. Connor's solution, albeit suboptimal, has been working so well that I kind of forgot this.

**Comment by Agamennon** [comment]
Got bitten by this, Connor solution works on vscode, but its smells like a hack, imho the defaults should work, we should not have to fiddle with vscode configurations to be able to debug plain js code.

**Comment by connor4312** [comment]
It is a hack:

> the fact that content validation fails indicates they are transforming the source in some way which is something that 'should' result in a sourcemap being generated.
