### ISSUE TITLE
Breakpoints which are set in the UI don't trigger

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/vscode-js-debug#1096]
**Describe the bug**

If we try to debug JavaScript code via the Debug Terminal the breakpoints which are set via the UI are not triggering. If I put the debugger; keyword it works.

**To Reproduce**
1. `mkdir test`
2. `npm init -y`
3. `npm i @playwright/test`
4. `npx playwright install`
5. put the content into the file `foo.spec.ts`
6. `npx playwright test`

```js
// foo.spec.ts
const { test, expect } = require('@playwright/test');

test('basic test', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  const title = page.locator('.navbar__inner .navbar__title');
  await expect(title).toHaveText('Playwright');
});
```

**Log File**

How to get the trace logs with the debug terminal?

**VS Code Version:** 1.59.1

**Additional context**

See here: https://github.com/microsoft/playwright/issues/8625

**Comment by connor4312** [comment]
I cannot reproduce this

<img width="1305" alt="image" src="https://user-images.githubusercontent.com/2230985/131727191-65b32780-2c34-463e-8136-94be6796e81d.png">

You can get trace log with a launch config like:

```json
    {
      "type": "pwa-node",
      "trace": true,
      "name": "Launch Program",
      "runtimeExecutable": "npx",
      "runtimeArgs": ["playwright", "test"],
      "request": "launch",
    }
```

**Comment by mxschmitt** [comment]
Here is the trace:

[vscode-debugadapter-be1ac3eb.json.gz](https://github.com/microsoft/vscode-js-debug/files/7093716/vscode-debugadapter-be1ac3eb.json.gz)

(also made sure that the certain test runs, by adding a process.exit(1) or debugger; inside)

**Comment by connor4312** [comment]
Oh yea. If you look in the debug console we log a warning about that. V8 had a bug for a few versions that prevented breakpoints from being set in any function with destructured arguments.
