### ISSUE TITLE
Canonical list of old-debugger config options that are not used in vscode-js-debug?

### ISSUE THREAD

**Issue by justingrant** [microsoft/vscode-js-debug#1102]
I have a lot of old launch.json configs for the old VSCode Node debugger. The new debugger is great!  But I'm not sure which of the old settings are no longer used in the new debugger. Is there an authoritative list of settings that are removed in the new debugger? 

Specifically:
* `"protocol": "inspector"` - still needed?
* `"disableOptimisticBPs": true` - is this used anymore?
* Any others that have been retired? 

The docs are somewhat helpful in listing the settings that *are* supported (although the [docs for `protocol`](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_launch-configuration-attributes) provide no info about what it does). And just because a setting is omitted in the docs doesn't always mean it's not used; it might just be new, or only used in niche cases not deserving a mention in docs. So I'm loath to remove config settings without knowing that they're really not needed.

**Comment by connor4312** [comment]
Almost all relevant options are still used and should function identically to the old debugger, with two exceptions:

- `"protocol": "inspector"` -- this was used to support Node versions prior to Node 8 that used a different debug protocol. Node 6 reached its end of life in 2018 and we don't support it with the new debugger, so there's no longer a reason to have this.
- `"disableOptimisticBPs": true` -- the new debugger sets breakpoints in a different way, and more reliably overall. This option was an artifact of how the old debugger functioned, which is no longer appliable.

I think these should really be the only two that weren't moved over, and they can safely be deleted from your launch configs. Let me know if you have other questions/find others.

**Comment by Drarig29** [comment]
For the record, here is where it was used before (old JS debugger, archived repo):

Search results: [https://github.com/microsoft/vscode-node-debug2/search?q=disableOptimisticBPs](https://github.com/microsoft/vscode-node-debug2/search?l=TypeScript&q=disableOptimisticBPs)
or permalink: [https://github.com/microsoft/vscode-node-debug2/src/nodeDebugInterfaces.d.ts#L21-L22](https://github.com/microsoft/vscode-node-debug2/blob/a1d8b5495938a3525927f88d0b572b5ce541e5e5/src/nodeDebugInterfaces.d.ts#L21-L22)
