### ISSUE TITLE
debug.javascript.defaultRuntimeExecutable seems not to be used

### ISSUE THREAD

**Issue by nhaug** [microsoft/vscode-js-debug#1108]
Hey there,

i got the following message:

The Node version in "C:\Program Files (x86)\CA\SharedComponents\pec\bin\node.exe" is outdated (version The node identifier for V100SPWTK121558 is re7wc8qbky.), we require at least Node 8.x. Would you like to try debugging anyway?

I configured via json, but it seems not to work ....

    "debug.javascript.defaultRuntimeExecutable": {
        "pwa-node": "W:\\node-v14.15.1-win-x64;"
    } 

i also set, which works for the terminal, but not for the debugger

    "terminal.integrated.env.windows": {
        "PATH": "W:\\node-v14.15.1-win-x64;${env:PATH}"
    },

Regards Nils

**Comment by connor4312** [comment]
We expect `defaultRuntimeExecutable` to contain the path to the binary, not the folder where it resides. For example you may want `W:\\node-v14.15.1-win-x64\\node.exe`

**Comment by nhaug** [comment]
Hey Connor, 

unfortunately the problem still exists. 

I double checked it's W:\node-v14.15.1-win-x64\node.exe

I also set in launch.json

"runtimeExecutable": "W:\\node-v14.15.1-win-x64\\node.exe", 

and for security     

"debug.javascript.defaultRuntimeExecutable": {
        "pwa-node": "W:\\node-v14.15.1-win-x64\\node.exe"
    }

Im not able to set the PATH Variable in my user-settings in Windows.

![image](https://user-images.githubusercontent.com/22777448/134123258-bca83b58-5a83-4f79-b712-e11fee92e8a0.png)

**Comment by connor4312** [comment]
I'll take a look

**Comment by connor4312** [comment]
Oh, this is for auto attach. That's expected: we probe the PATH and are conservative is don't enable it if it looks like it'll result in a broken installation. The runtimeExecutable only affects when the debugger launches the program itself; in the terminal, the user is the one launching Node.

Node 8 has been end of life for several years now, I don't plan on changing this.
