### ISSUE TITLE
Debugger domain CDP messages can be sent before response to Debugger.enable, causing them to fail

### ISSUE THREAD

**Issue by EricCornelson** [microsoft/vscode-js-debug#1109]
There looks to be a race condition where Debugger domain messages can be sent out before the response to Debugger.enable is received. Most of the time they succeeed, but occasionally they will fail with the error: 
```json
{
  "id": 1020,
  "sessionId": "7406777437D020B36526E40889580677",
  "error": {
    "code": -32000,
    "message": "Debugger agent is not enabled"
  }
}
```

See attached log. This is particularly reproducible on this Blazor project (steps in the readme): https://github.com/EricCornelson/cdp-debugger-race-repro

**Log File**
[visualstudio-js-debugger.txt](https://github.com/microsoft/vscode-js-debug/files/7198134/visualstudio-js-debugger.txt)

**VS Code Version:** 
Version: 1.61.0-insider (user setup)
Commit: a0af58197e4a1d3e82fbe3048e0549e622d19f4f
Date: 2021-09-17T05:15:50.405Z
Electron: 13.4.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by connor4312** [comment]
We don't hit this in VS Code, but I pushed a fix, let me know if that resolves it for you

**Comment by TylerLeonhardt** [comment]
@EricCornelson can you confirm if this is fixed?

**Comment by thaystg** [comment]
Yes, it's fixed.
