### ISSUE TITLE
How to open and see the verbose log in vscode?

### ISSUE THREAD

**Issue by pilaoda** [microsoft/vscode-js-debug#1111]
I found `this.logger.verbose` in this repo, but don't know where to see those logs. 
I already checked the `OUTPUT` and `DEBUG CONSOLE` tabs in vscode.

**Comment by pilaoda** [comment]
BTW, I am debugging the V8 source code.
My launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "pwa-node",
            "name": "Attach",
            "request": "attach",
            "port": 8080,
            "skipFiles": [
                "<node_internals>/**"
            ],
        }
    ]
}
```

**Comment by connor4312** [comment]
Instructions and info are in the "bug template" here https://raw.githubusercontent.com/microsoft/vscode-js-debug/main/.github/ISSUE_TEMPLATE/bug_report.md
