### ISSUE TITLE
No access to a global function

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/vscode-js-debug#1123]
**Describe the bug**

When trying to use a global function in the debugger REPL it does not find it and a ReferenceError gets thrown.

**To Reproduce**

```js
async function foo() {
  return "bar"
}

const foo2 = async () => {
  return "bar"
}

console.log("test") // set breakpoint here
```

1. Create a file with the file content above
2. Set the debugger at the console.log statement
3. Run it
4. Try to evaluate "foo" in the debugger

Expected: It does find the variable
Actual: It does not

**VS Code Version:** 1.61.0

**Additional context**

Note: For "foo2" it is working

**Comment by connor4312** [comment]
This is an behavior V8, note that if `foo` is actually used then it will be present:

<img width="599" alt="image" src="https://user-images.githubusercontent.com/2230985/137176024-0b3cc753-4c3a-4f2b-bb8c-12c923ea5804.png">

The similar very common case is if you're in an async callback that doesn't use locals in the parent scope, those are not accessible.
