### ISSUE TITLE
Error activating auto attach, please report 

### ISSUE THREAD

**Issue by dfdumaresq** [microsoft/vscode-js-debug#1131]
Debugger listening on ws://127.0.0.1:50999/41cd8634-4191-4ec1-a9ca-a756413fb395
  For help, see: https://nodejs.org/en/docs/inspector
  read byte 1
  
  Error activating auto attach, please report to https://aka.ms/js-dbg-issue
  Hash: a35a9e620eb3429894cbcc3c77bec38e288692a2
  Version: webpack 4.46.0

**Comment by connor4312** [comment]
Please run the "toggle developer tools" command and let me know if there are any errors there

**Comment by dfdumaresq** [comment]
Here's a screenshot, Conner. 
My troubles seem to be with one workspace not initializing my git repos, which is causing the MSBuild tools to hang on Initializing.... I can't find anything wrong in the workspace, but when I switch to another the git repos are init'd and all is good. 

![image](https://user-images.githubusercontent.com/20051/140417522-cf161b2f-b796-4785-996b-10f1b7d0e19c.png)

**Comment by dfdumaresq** [comment]
Now I'm getting errors after trying to start a JS debugging session in Chrome.

![image](https://user-images.githubusercontent.com/20051/140418921-50f5a1de-95fb-49d6-8dd2-c9950182e764.png)

**Comment by dfdumaresq** [comment]
Restarting my machine -

**Comment by dfdumaresq** [comment]
I'm getting a lot of issues turning up with auto-attach. 
`
Error activating auto attach: Error: We did not find `node` on your PATH, so we cannot enable auto-attach in your environment at new AppInsightsAsyncCorrelatedErrorWrapper (/Users/ddumaresq/.vscode/extensions/qub.qub-xml-vscode-1.2.8/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:172:18) at new E (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1410650) at C.getBootloaderFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1409325) at C.r [as bootloaderFile] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1274014) at C.resolveEnvironment (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1440137) at C.applyInspectorOptions (/Applications/Visual Studio Code.app/Contents/Resources/app/extens...
`

**Comment by dfdumaresq** [comment]
My extension for Chrome said to Upgrade. I then rebooted my machine and restarted vscode. The Omnisharp MSBuild then reported:
`[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/ddumaresq/EducationPlannerBC/Dockerize/EPAS/sources/develop-branch/epbc-ui' on host 769.
It was not possible to find any installed .NET SDKs.
Install a .NET SDK from:
  https://aka.ms/dotnet-download
[fail]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '{projectFilePath}'.
`
So I've now installed .Net 5.

**Comment by connor4312** [comment]
It's possible there were changes in your PATH that were not applied prior to a restart. Let me know if you hit issues here again...

**Comment by dfdumaresq** [comment]
I just hit one. But it recovered correctly and ran my webpack.
`
$ npm run dev
Debugger listening on ws://127.0.0.1:49884/fe02d055-5e43-42a7-86fc-b54851938ae0
For help, see: https://nodejs.org/en/docs/inspector
read byte 1

Error activating auto attach, please report to https://aka.ms/js-dbg-issue

> epas-ui-client@1.0.0 dev /Users/ddumaresq/EducationPlannerBC/Dockerize/EPAS/sources/develop-branch/epbc-ui
> webpack --watch --progress --hot --config webpack.config.js

Debugger listening on ws://127.0.0.1:49886/a80572f7-8615-4eee-9d9e-ab05ce9ed893
For help, see: https://nodejs.org/en/docs/inspector
read byte 1

Error activating auto attach, please report to https://aka.ms/js-dbg-issue
10% [1] building 0/0 modules 0 active
webpack is watching the files…

Hash: da4f1e28e1038f5c80c599de313092cfaf2dcc4c
Version: webpack 4.46.0
`
