### ISSUE TITLE
enableContentValidation should respect pathMapping

### ISSUE THREAD

**Issue by baybal** [microsoft/vscode-js-debug#1133]
**Is your feature request related to a problem? Please describe.**
VSCode checks if debugger output matches local file, `enableContentValidation: false` will disable this behaviour. If the only difference in between mapped, and remote file is import statement like `import { something } from 'https://github.com/someorg/somepkg/raw/libs/somelib'` vs `import { something } from '/libs/somelib'` it will not map the file even if pathMapping is correct.

**Describe the feature you'd like**
`enableContentValidation: true` must check if files for match after using pathMapping to substitute import paths.

**Comment by connor4312** [comment]
enableContentValidation has nothing to do with pathMapping. If you have a file that isn't getting mapped locally, it's most likely an issue with how the debugger is configured to resolve paths. You can open an issue and include the trace log using the instructions in the issue template to diagnose this.

**Comment by baybal** [comment]
@connor4312 I'm pretty sure that it is enableContentValidation. I have a file which maps nicely with `enableContentValidation: false` and shows as "Disk verification failed" in debug diagnostics.

**Comment by connor4312** [comment]
If enableContentValidation is set to false, the content hash is never used, at all, regardless of any other options.

https://github.com/microsoft/vscode-js-debug/blob/1ea758e0b8936b3b6cf5ff55414146574dfae7c7/src/adapter/sources.ts#L867

Without a log and a detail of what problem you're actually facing/repro steps, I don't have enough information to help you.
