### ISSUE TITLE
Error processing attach: Error: Could not connect to debug target at localhost:9229: Could not find any debuggable target

### ISSUE THREAD

**Issue by brandonseager** [microsoft/vscode-js-debug#1135]
So we have been using the debugger for a long time with no problems. Implemented the debugger off this link https://www.bigbinary.com/blog/debug-nodejs-app-running-in-a-docker-container.

Out of the blue we started getting the attached error in our logs and the debugger acts like it starts then dies. Any and all help would be appreciated.

**To Reproduce**
1. Docker-compose up 
2. Try to Attach the debugger

Launch.json

{
        "type": "node",
        "request": "attach",
        "trace": true,
        "address": "local.app.hdsdoorways.com", //alias for localhost
        "name": "Docker: Attach to Node",
        "remoteRoot": "/app",
        "port": 9229,
}

package.json

"start.dev": "nodemon --inspect=0.0.0.0:9229",

docker-compose.debug

doorways:
        build:
          context: .
          dockerfile: Dockerfile.dev
        restart: always
        command: npm run start.dev
        env_file:
            - .env
        ports:
            - "3000:3000" 
            - "9229:9229"
         volumes:
            - ./:/app
            - doorways-node_modules:/app/node_modules

**Log File**

{"tag":"dap.receive","timestamp":1635104222663,"metadata":{"connectionId":14,"message":{"command":"attach","arguments":{"type":"pwa-node","name":"Docker: Attach to Node","request":"attach","trace":{"console":false,"level":"verbose","stdio":true,"logFile":"/Users/seagerb/Library/Application Support/Code/logs/20211024T142536/exthost1/ms-vscode.js-debug/vscode-debugadapter-d90b638b.json.gz","tags":[]},"outputCapture":"console","timeout":10000,"timeouts":{},"showAsyncStacks":true,"skipFiles":[],"smartStep":true,"sourceMaps":true,"sourceMapRenames":true,"pauseForSourceMap":false,"resolveSourceMapLocations":["**","!**/node_modules/**"],"rootPath":"/Users/seagerb/repos/doorways","outFiles":["/Users/seagerb/repos/doorways/**/*.js","!**/node_modules/**"],"sourceMapPathOverrides":{"webpack:///./~/*":"/Users/seagerb/repos/doorways/node_modules/*","webpack:////*":"/*","webpack://?:*/*":"/Users/seagerb/repos/doorways/*","webpack:///([a-z]):/(.+)":"$1:/$2","meteor://💻app/*":"/Users/seagerb/repos/doorways/*"},"enableContentValidation":true,"cascadeTerminateToConfigurations":[],"__workspaceFolder":"/Users/seagerb/repos/doorways","__autoExpandGetters":false,"__breakOnConditionalError":false,"cwd":"/Users/seagerb/repos/doorways","env":{},"envFile":null,"localRoot":"/Users/seagerb/repos/doorways","remoteRoot":"/app","autoAttachChildProcesses":true,"runtimeSourcemapPausePatterns":[],"attachExistingChildren":true,"address":"local.app.hdsdoorways.com","port":9229,"restart":false,"continueOnAttach":false,"__configurationTarget":5,"__workspaceCachePath":"/Users/seagerb/Library/Application Support/Code/User/workspaceStorage/365dbce57a83d026a4e13348794cf6ce/ms-vscode.js-debug","__sessionId":"162f370b-6843-407d-960c-e3e1a869db86"},"type":"request","seq":2}},"level":0}
{"tag":"dap.send","timestamp":1635104222664,"metadata":{"connectionId":14,"message":{"seq":3,"type":"event","event":"output","body":{"category":"telemetry","output":"js-debug/launch","data":{"type":"pwa-node","request":"attach","os":"darwin x64","nodeVersion":"v14.16.0","adapterVersion":"1.60.2","parameters":"{\"type\":\"pwa-node\",\"name\":\"<string>\",\"request\":\"attach\",\"trace\":{\"console\":false,\"level\":\"<string>\",\"stdio\":true,\"logFile\":\"<string>\",\"tags\":[]},\"outputCapture\":\"console\",\"timeout\":10000,\"timeouts\":{},\"showAsyncStacks\":true,\"skipFiles\":[],\"smartStep\":true,\"sourceMaps\":true,\"sourceMapRenames\":true,\"pauseForSourceMap\":false,\"resolveSourceMapLocations\":[\"<string>\",\"<string>\"],\"rootPath\":\"<string>\",\"outFiles\":[\"<string>\",\"<string>\"],\"sourceMapPathOverrides\":{\"webpack:///./~/*\":\"<string>\",\"webpack:////*\":\"<string>\",\"webpack://?:*/*\":\"<string>\",\"webpack:///([a-z]):/(.+)\":\"<string>\",\"meteor://💻app/*\":\"<string>\"},\"enableContentValidation\":true,\"cascadeTerminateToConfigurations\":[],\"__workspaceFolder\":\"<string>\",\"__autoExpandGetters\":false,\"__breakOnConditionalError\":false,\"cwd\":\"<string>\",\"env\":{},\"envFile\":null,\"localRoot\":\"<string>\",\"remoteRoot\":\"<string>\",\"autoAttachChildProcesses\":true,\"runtimeSourcemapPausePatterns\":[],\"attachExistingChildren\":true,\"address\":\"<string>\",\"port\":9229,\"restart\":false,\"continueOnAttach\":false,\"__configurationTarget\":5,\"__workspaceCachePath\":\"<string>\",\"__sessionId\":\"<string>\"}"}}}},"level":0}
{"tag":"dap.send","timestamp":1635104222664,"metadata":{"connectionId":14,"message":{"seq":4,"type":"event","event":"output","body":{"category":"console","output":"Verbose logs are written to:\n/Users/seagerb/Library/Application Support/Code/logs/20211024T142536/exthost1/ms-vscode.js-debug/vscode-debugadapter-d90b638b.json.gz\n"}}},"level":0}
{"tag":"dap.receive","timestamp":1635104222669,"metadata":{"connectionId":14,"message":{"command":"setBreakpoints","arguments":{"source":{"name":"household-accounts.client.service.js","path":"/Users/seagerb/repos/doorways/packages/custom/accounting/public/components/household-accounts/household-accounts.client.service.js"},"lines":[5,16],"breakpoints":[{"line":5},{"line":16}],"sourceModified":false},"type":"request","seq":3}},"level":0}
{"tag":"dap.send","timestamp":1635104222670,"metadata":{"connectionId":14,"message":{"seq":5,"type":"response","request_seq":3,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"id":1,"verified":false,"message":"Unbound breakpoint"},{"id":2,"verified":false,"message":"Unbound breakpoint"}]}}},"level":0}
{"tag":"dap.receive","timestamp":1635104222767,"metadata":{"connectionId":14,"message":{"command":"setExceptionBreakpoints","arguments":{"filters":[],"filterOptions":[{"filterId":"all"},{"filterId":"uncaught"}]},"type":"request","seq":4}},"level":0}
{"tag":"dap.send","timestamp":1635104222767,"metadata":{"connectionId":14,"message":{"seq":6,"type":"response","request_seq":4,"command":"setExceptionBreakpoints","success":true,"body":{}}},"level":0}
{"tag":"dap.receive","timestamp":1635104222773,"metadata":{"connectionId":14,"message":{"command":"configurationDone","type":"request","seq":5}},"level":0}
{"tag":"dap.send","timestamp":1635104222774,"metadata":{"connectionId":14,"message":{"seq":7,"type":"response","request_seq":5,"command":"configurationDone","success":true,"body":{}}},"level":0}
{"tag":"dap.receive","timestamp":1635104222814,"metadata":{"connectionId":14,"message":{"command":"threads","type":"request","seq":6}},"level":0}
{"tag":"dap.send","timestamp":1635104222814,"metadata":{"connectionId":14,"message":{"seq":8,"type":"response","request_seq":6,"command":"threads","success":true,"body":{"threads":[]}}},"level":0}
{"tag":"runtime.launch","timestamp":1635104225800,"message":"Error looking up /json/version","metadata":{"ok":false,"body":"socket hang up","statusCode":503,"error":{"message":"Unexpected 503 response from http://local.app.hdsdoorways.com:9229/json/version: socket hang up","stack":"Error: Unexpected 503 response from http://local.app.hdsdoorways.com:9229/json/version: socket hang up\n\tat b.fetchHttp (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1145624)\n\tat runMicrotasks (<anonymous>)\n\tat processTicksAndRejections (internal/process/task_queues.js:93:5)\n\tat async b.fetchJson (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1144758)\n\tat async Promise.all (index 0)\n\tat async l (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1395717)\n\tat async Object.retryGetNodeEndpoint (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1396519)\n\tat async t (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1419107)\n\tat async C.launch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1436050)\n\tat async t.Binder.captureLaunch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1227855)\n\tat async t.Binder._launch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1227400)\n\tat async Promise.all (index 5)\n\tat async t.Binder._boot (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1226452)\n\tat async t.default._onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1319092)"}},"level":0}
{"tag":"runtime.launch","timestamp":1635104225800,"message":"Error looking up /json/list","metadata":{"ok":false,"body":"socket hang up","statusCode":503,"error":{"message":"Unexpected 503 response from http://local.app.hdsdoorways.com:9229/json/list: socket hang up","stack":"Error: Unexpected 503 response from http://local.app.hdsdoorways.com:9229/json/list: socket hang up\n\tat b.fetchHttp (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1145624)\n\tat runMicrotasks (<anonymous>)\n\tat processTicksAndRejections (internal/process/task_queues.js:93:5)\n\tat async b.fetchJson (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1144758)\n\tat async Promise.all (index 1)\n\tat async l (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1395717)\n\tat async Object.retryGetNodeEndpoint (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1396519)\n\tat async t (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1419107)\n\tat async C.launch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1436050)\n\tat async t.Binder.captureLaunch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1227855)\n\tat async t.Binder._launch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1227400)\n\tat async Promise.all (index 5)\n\tat async t.Binder._boot (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1226452)\n\tat async t.default._onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1319092)"}},"level":0}
{"tag":"dap.send","timestamp":1635104227664,"metadata":{"connectionId":14,"message":{"seq":9,"type":"event","event":"output","body":{"category":"telemetry","output":"js-debug/dap/operation","data":{"VSCode.ABExp.Features":"livesharecontinuousaacf;reusableLinks;RemoveKernelToolbarInInteractiveWindowcf;portForwardingServiceEnabled-development;portForwardingServiceEnabled-staging;portForwardingServiceEnabled-production;mindaroBinariesVersion;mindaroBinariesVersion-1.0.20210702;mindaroBinariesVersion-1.0.20210723;account-aa","abexp.assignmentcontext":"vsliv368cf:30146710;vsreu685:30147344;python383cf:30185419;vspor879:30202332;vspor708:30202333;vspor363:30204092;binariesv615:30325510;bridge0708:30335490;bridge0723:30353136;vsaa593:30376534;","errors":[],"initialize":{"operation":"initialize","totalTime":0.1,"max":0.1,"avg":0.1,"stddev":null,"count":1,"failed":0},"!initialize.errors":[],"setBreakpoints":{"operation":"setBreakpoints","totalTime":1,"max":1,"avg":1,"stddev":null,"count":1,"failed":0},"!setBreakpoints.errors":[],"setExceptionBreakpoints":{"operation":"setExceptionBreakpoints","totalTime":0.2,"max":0.2,"avg":0.2,"stddev":null,"count":1,"failed":0},"!setExceptionBreakpoints.errors":[],"configurationDone":{"operation":"configurationDone","totalTime":0.2,"max":0.2,"avg":0.2,"stddev":null,"count":1,"failed":0},"!configurationDone.errors":[],"threads":{"operation":"threads","totalTime":0.3,"max":0.3,"avg":0.3,"stddev":null,"count":1,"failed":0},"!threads.errors":[]}}}},"level":0}
{"tag":"runtime.launch","timestamp":1635104229155,"message":"Error looking up /json/version","metadata":{"ok":false,"body":"socket hang up","statusCode":503,"error":{"message":"Unexpected 503 response from http://local.app.hdsdoorways.com:9229/json/version: socket hang up","stack":"Error: Unexpected 503 response from http://local.app.hdsdoorways.com:9229/json/version: socket hang up\n\tat b.fetchHttp (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1145624)\n\tat runMicrotasks (<anonymous>)\n\tat processTicksAndRejections (internal/process/task_queues.js:93:5)\n\tat async b.fetchJson (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1144758)\n\tat async Promise.all (index 0)\n\tat async l (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1395717)\n\tat async Object.retryGetNodeEndpoint (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1396519)\n\tat async t (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1419107)\n\tat async C.launch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1436050)\n\tat async t.Binder.captureLaunch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1227855)\n\tat async t.Binder._launch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1227400)\n\tat async Promise.all (index 5)\n\tat async t.Binder._boot (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1226452)\n\tat async t.default._onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1319092)"}},"level":0}
{"tag":"runtime.launch","timestamp":1635104229155,"message":"Error looking up /json/list","metadata":{"ok":false,"body":"socket hang up","statusCode":503,"error":{"message":"Unexpected 503 response from http://local.app.hdsdoorways.com:9229/json/list: socket hang up","stack":"Error: Unexpected 503 response from http://local.app.hdsdoorways.com:9229/json/list: socket hang up\n\tat b.fetchHttp (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1145624)\n\tat runMicrotasks (<anonymous>)\n\tat processTicksAndRejections (internal/process/task_queues.js:93:5)\n\tat async b.fetchJson (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1144758)\n\tat async Promise.all (index 1)\n\tat async l (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1395717)\n\tat async Object.retryGetNodeEndpoint (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1396519)\n\tat async t (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1419107)\n\tat async C.launch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1436050)\n\tat async t.Binder.captureLaunch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1227855)\n\tat async t.Binder._launch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1227400)\n\tat async Promise.all (index 5)\n\tat async t.Binder._boot (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1226452)\n\tat async t.default._onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1319092)"}},"level":0}
{"tag":"runtime.launch","timestamp":1635104232523,"message":"Error looking up /json/version","metadata":{"ok":false,"body":"socket hang up","statusCode":503,"error":{"message":"Unexpected 503 response from http://local.app.hdsdoorways.com:9229/json/version: socket hang up","stack":"Error: Unexpected 503 response from http://local.app.hdsdoorways.com:9229/json/version: socket hang up\n\tat b.fetchHttp (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1145624)\n\tat runMicrotasks (<anonymous>)\n\tat processTicksAndRejections (internal/process/task_queues.js:93:5)\n\tat async b.fetchJson (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1144758)\n\tat async Promise.all (index 0)\n\tat async l (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1395717)\n\tat async Object.retryGetNodeEndpoint (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1396519)\n\tat async t (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1419107)\n\tat async C.launch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1436050)\n\tat async t.Binder.captureLaunch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1227855)\n\tat async t.Binder._launch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1227400)\n\tat async Promise.all (index 5)\n\tat async t.Binder._boot (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1226452)\n\tat async t.default._onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1319092)"}},"level":0}
{"tag":"runtime.launch","timestamp":1635104232523,"message":"Error looking up /json/list","metadata":{"ok":false,"body":"socket hang up","statusCode":503,"error":{"message":"Unexpected 503 response from http://local.app.hdsdoorways.com:9229/json/list: socket hang up","stack":"Error: Unexpected 503 response from http://local.app.hdsdoorways.com:9229/json/list: socket hang up\n\tat b.fetchHttp (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1145624)\n\tat runMicrotasks (<anonymous>)\n\tat processTicksAndRejections (internal/process/task_queues.js:93:5)\n\tat async b.fetchJson (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1144758)\n\tat async Promise.all (index 1)\n\tat async l (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1395717)\n\tat async Object.retryGetNodeEndpoint (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1396519)\n\tat async t (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1419107)\n\tat async C.launch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1436050)\n\tat async t.Binder.captureLaunch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1227855)\n\tat async t.Binder._launch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1227400)\n\tat async Promise.all (index 5)\n\tat async t.Binder._boot (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1226452)\n\tat async t.default._onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1319092)"}},"level":0}
{"tag":"runtime.launch","timestamp":1635104232726,"message":"Error looking up /json/version","metadata":{"ok":false,"body":"Promise was canceled","statusCode":503,"error":{"message":"Unexpected 503 response from http://local.app.hdsdoorways.com:9229/json/version: Promise was canceled","stack":"Error: Unexpected 503 response from http://local.app.hdsdoorways.com:9229/json/version: Promise was canceled\n\tat b.fetchHttp (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1145624)\n\tat runMicrotasks (<anonymous>)\n\tat processTicksAndRejections (internal/process/task_queues.js:93:5)\n\tat runNextTicks (internal/process/task_queues.js:62:3)\n\tat listOnTimeout (internal/timers.js:523:9)\n\tat processTimers (internal/timers.js:497:7)\n\tat async b.fetchJson (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1144758)\n\tat async Promise.all (index 0)\n\tat async l (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1395717)\n\tat async Object.retryGetNodeEndpoint (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1396519)\n\tat async t (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1419107)\n\tat async C.launch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1436050)\n\tat async t.Binder.captureLaunch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1227855)\n\tat async t.Binder._launch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1227400)\n\tat async Promise.all (index 5)\n\tat async t.Binder._boot (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1226452)\n\tat async t.default._onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1319092)"}},"level":0}
{"tag":"runtime.launch","timestamp":1635104232726,"message":"Error looking up /json/list","metadata":{"ok":false,"body":"Promise was canceled","statusCode":503,"error":{"message":"Unexpected 503 response from http://local.app.hdsdoorways.com:9229/json/list: Promise was canceled","stack":"Error: Unexpected 503 response from http://local.app.hdsdoorways.com:9229/json/list: Promise was canceled\n\tat b.fetchHttp (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1145624)\n\tat runMicrotasks (<anonymous>)\n\tat processTicksAndRejections (internal/process/task_queues.js:93:5)\n\tat async b.fetchJson (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1144758)\n\tat async Promise.all (index 1)\n\tat async l (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1395717)\n\tat async Object.retryGetNodeEndpoint (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1396519)\n\tat async t (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1419107)\n\tat async C.launch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1436050)\n\tat async t.Binder.captureLaunch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1227855)\n\tat async t.Binder._launch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1227400)\n\tat async Promise.all (index 5)\n\tat async t.Binder._boot (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1226452)\n\tat async t.default._onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1319092)"}},"level":0}
{"tag":"runtime.launch","timestamp":1635104232726,"message":"Launch returned error","metadata":{"error":{"message":"Could not connect to debug target at http://local.app.hdsdoorways.com:9229: Could not find any debuggable target","stack":"Error: Could not connect to debug target at http://local.app.hdsdoorways.com:9229: Could not find any debuggable target\n\tat Object.retryGetNodeEndpoint (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1396580)\n\tat runMicrotasks (<anonymous>)\n\tat processTicksAndRejections (internal/process/task_queues.js:93:5)\n\tat async t (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1419107)\n\tat async C.launch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1436050)\n\tat async t.Binder.captureLaunch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1227855)\n\tat async t.Binder._launch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1227400)\n\tat async Promise.all (index 5)\n\tat async t.Binder._boot (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1226452)\n\tat async t.default._onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1319092)"},"wasCancelled":true,"name":"C"},"level":2}
{"tag":"dap.send","timestamp":1635104232726,"metadata":{"connectionId":14,"message":{"seq":10,"type":"response","request_seq":2,"command":"attach","success":false,"body":{"error":{"id":9221,"format":"Error processing attach: Error: Could not connect to debug target at http://local.app.hdsdoorways.com:9229: Could not find any debuggable target\n\tat Object.retryGetNodeEndpoint (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1396580)\n\tat runMicrotasks (<anonymous>)\n\tat processTicksAndRejections (internal/process/task_queues.js:93:5)\n\tat async t (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1419107)\n\tat async C.launch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1436050)\n\tat async t.Binder.captureLaunch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1227855)\n\tat async t.Binder._launch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1227400)\n\tat async Promise.all (index 5)\n\tat async t.Binder._boot (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1226452)\n\tat async t.default._onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1319092)","showUser":false,"sendTelemetry":false}}}},"level":0}
{"tag":"dap.receive","timestamp":1635104232733,"metadata":{"connectionId":14,"message":{"command":"disconnect","arguments":{"restart":false},"type":"request","seq":7}},"level":0}
{"tag":"dap.send","timestamp":1635104232734,"metadata":{"connectionId":14,"message":{"seq":11,"type":"response","request_seq":7,"command":"disconnect","success":true,"body":{}}},"level":0}
{"tag":"dap.send","timestamp":1635104237734,"message":"Not sending message because the connection has ended","metadata":{"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"js-debug/dap/operation","data":{"VSCode.ABExp.Features":"livesharecontinuousaacf;reusableLinks;RemoveKernelToolbarInInteractiveWindowcf;portForwardingServiceEnabled-development;portForwardingServiceEnabled-staging;portForwardingServiceEnabled-production;mindaroBinariesVersion;mindaroBinariesVersion-1.0.20210702;mindaroBinariesVersion-1.0.20210723;account-aa","abexp.assignmentcontext":"vsliv368cf:30146710;vsreu685:30147344;python383cf:30185419;vspor879:30202332;vspor708:30202333;vspor363:30204092;binariesv615:30325510;bridge0708:30335490;bridge0723:30353136;vsaa593:30376534;","errors":[],"disconnect":{"operation":"disconnect","totalTime":0.7,"max":0.7,"avg":0.7,"stddev":null,"count":1,"failed":0},"!disconnect.errors":[]}}},"level":2}

**VS Code Version:** Version: 1.62.2

**Comment by connor4312** [comment]
The debugger is receiving a "socket hang up" when it tries to connect to `local.app.hdsdoorways.com:9229`. This is unlikely to be a problem with the debugger itself. Try hitting that address in your browser and seeing why the connection is failing.

Alternately, you can develop directly inside a Docker containing with [remote containers](https://code.visualstudio.com/docs/remote/containers)
