### ISSUE TITLE
Remove dependency on `Debugger.CallFrame.url`

### ISSUE THREAD

**Issue by bmeurer** [microsoft/vscode-js-debug#1136]
We are exploring the idea to deprecate the `url` field in `Debugger.CallFrame`, which is sent as part of `Debugger.paused` events. [crbug/1270316](https://crbug.com/1270316) tracks this work. The motivation is that URLs can be costly (worst case we've seen so far is whole WebAssembly modules being served as Base64-encoded `data:`-URLs), and the information is 

1. redundant, since the `location.scriptId` on the same `CallFrame` let's the debugger front-end lookup the URL from `Debugger.scriptParsed` events, and
2. potentially ambiguous, as the URL is not guaranteed to be unique (example of this is [crbug/1270248](https://crbug.com/1270248)).

Design doc with more context [here](https://docs.google.com/document/d/1X7h8nKLn1PoNvIFjpZvq-00SfXV7YdPMYJtwHMtyU-k/view).

**Comment by connor4312** [comment]
Thanks for the heads up. We do depend on the URL in a couple places right now, but also maintain a script ID mapping so we can use the location. I'll have this as a debt item for clean up in December/Janurary

**Comment by bmeurer** [comment]
Thanks for the quick response.

What I forgot to mention is that we are also exploring the possibility of deprecating `Runtime.CallFrame.url`, which is even more costly to maintain (especially in the context of async stack traces in huge applications). For `Runtime.CallFrame.url` there are plenty of uses outside of debuggers, so it'll probably turn out to be a flag to `Runtime.enable` to disable collecting and sending the `url` fields, but giving the scalability problems, it might be a good opportunity for VScode to also reduce dependencies on it.

**Comment by connor4312** [comment]
Thanks for the heads up, we should be able to drop dependency on both of those fairly easily.

**Comment by bmeurer** [comment]
Heads up, I'm about to land crrev.com/c/3345001 in V8, so starting with Chromium 100, the `url` field of `Debugger.CallFrame` will contain an empty string.

**Comment by connor4312** [comment]
Good timing, I'm taking care of this this week 🙂
