### ISSUE TITLE
Launch config snippets use pwa- types

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#1138]
Open launch.json, trigger snippets, insert "Chrome: Attach". It has type "pwa-chrome". These snippets should just use the non pwa- types

**Comment by roblourens** [comment]
It seems like these are still `pwa-`

**Comment by weinand** [comment]
Now inserted launch configs have correct type:

![CleanShot 2022-03-24 at 17 34 08@2x](https://user-images.githubusercontent.com/1898161/159965532-9c58030a-2d6b-4d10-bbaa-b3b92c159917.png)
