### ISSUE TITLE
When two consecutive methods that eventually fire callback are called, only the callback from first method gets registered while the callback from second one does not.

### ISSUE THREAD

**Issue by iheathers** [microsoft/vscode-js-debug#1139]
**Describe the bug**
I have described the bug on StackOverflow in detail [here](https://stackoverflow.com/questions/70008777/vs-code-debugger-not-working-as-expected-while-debugging-nodejs-app)

```
const deleteProduct = async (req, res, next) => {
  const productID = req.params.productID;

  const product = await Product.fetchProductWithId(productID);

  await Cart.deleteProductFromCart(productID, product.price);
  await Product.deleteProductWithId(productID);

  res.redirect(301, '/products');
};
```

When two consecutive methods that eventually fire callback are called, only the first callback from the first method gets registered while the callback from the second one does not. The program works as expected with `yarn start` but not with the debugger.

This works fine with normal `yarn start` though.

**VS Code Version:**

![image](https://user-images.githubusercontent.com/34258778/142249822-b78a2dfd-1509-4ceb-a5d6-7c9af1d80406.png)

**Comment by connor4312** [comment]
It looks like the repo linked in the issue no longer exists. Do you still have a copy of it so I can investigate this? Thanks!

**Comment by iheathers** [comment]
@connor4312 I have updated the visibility of the repo. Please visit the `vs-code-debugger-experiment` branch. The attached files are under `models` folder.

**Comment by connor4312** [comment]
I'm not able to reproduce the issue on your repo. Please collect a log file using the instructions in the issue template.
