### ISSUE TITLE
Restart frame button is doing “Step Into” instead of restarting the frame

### ISSUE THREAD

**Issue by andrewbranch** [microsoft/vscode-js-debug#1142]
**To Reproduce**
1. Start a debug session
2. Click the "restart frame" button repeatedly

https://user-images.githubusercontent.com/3277153/142687967-0a20f49f-2e6b-4354-bfd4-23394eda1abf.mp4

**VS Code Version:**

Version: 1.63.0-insider
Commit: d450b04c783dfa6f83dc439017767acccd4e9fac
Date: 2021-11-17T07:45:14.150Z (2 days ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0

Node in debug session: 16.13.0

**Comment by connor4312** [comment]
Restart frame is buggy in V8 and was removed a few months ago, and is already gone in the latest versions of Chrome/Edge. Eventually we'll remove it from the debugger as it arrives in Node. Therefore I don't plan to apply fixes here.
