### ISSUE TITLE
Skip calling `evaluateOnCallFrame` in variable assignment for simple expressions

### ISSUE THREAD

**Issue by thaystg** [microsoft/vscode-js-debug#1143]
### Description

Changing a value during a debugger breakpoint does not work in a Blazor WASM project. This was found as part of exploratory testing.

### Reproduction Steps

**Repro Steps**
1. Create a Blazor WASM 6.0 project.
1. Open Pages/Counter.razor, place a breakpoint at method @code{}.
1. Run the project with F5
1. Click Counter>Click me on webpage 
1. After the breakpoint get hit on Counter.razor 
1. Change the value of currentCount to 8

### Expected behavior

Value does not change

### Actual behavior

**Actual Result**

The value of currentCount can be changed

![DebugBlazor](https://user-images.githubusercontent.com/55483444/140882132-422bd9dd-62a0-4ef8-91a6-2b53f81011cf.gif)

### Other information

It works correctly on chrome.

The reason for it is:
We should receive Debugger.setVariableValue and not setVariable as we are receiving.

Looking at the log, we receive it:
```
{"tag":"cdp.send","timestamp":1627073804470,"metadata":{"connectionId":0,"message":{"id":1038,"method":"Debugger.evaluateOnCallFrame","params":{"expression":"11\n//# sourceURL=eval-3b30418f.cdp\n","callFrameId":"dotnet:scope:55"},"sessionId":"7697A4FF00ACB3B73C461F183E1D04B2"}},"level":0}
{"tag":"cdp.receive","timestamp":1627073804487,"metadata":{"connectionId":0,"message":{"id":1038,"sessionId":"7697A4FF00ACB3B73C461F183E1D04B2","error":{"result":{"type":"object","subtype":"error","description":"(7,35): error CS1026: ) expected(7,35): error CS1002: ; expected","className":"CompilationError"}}}},"level":0}
{"tag":"dap.send","timestamp":1627073804488,"metadata":{"connectionId":1,"message":{"seq":97,"type":"response","request_seq":31,"command":"setVariable","success":false,"message":"Invalid expression","body":{"error":{"id":9223,"format":"Invalid expression","showUser":true}}}},"level":0}
{"tag":"dap.receive","timestamp":1627073804488,"metadata":{"connectionId":1,"message":{"type":"request","command":"setVariable","arguments":{"variablesReference":5,"name":"testDaThays","value":"11","timeout":10000},"seq":32}},"level":0}
{"tag":"cdp.send","timestamp":1627073804489,"metadata":{"connectionId":0,"message":{"id":1039,"method":"Debugger.evaluateOnCallFrame","params":{"expression":"11\n//# sourceURL=eval-703605b9.cdp\n","callFrameId":"dotnet:scope:55"},"sessionId":"7697A4FF00ACB3B73C461F183E1D04B2"}},"level":0}
{"tag":"cdp.receive","timestamp":1627073804505,"metadata":{"connectionId":0,"message":{"id":1039,"sessionId":"7697A4FF00ACB3B73C461F183E1D04B2","error":{"result":{"type":"object","subtype":"error","description":"(7,35): error CS1026: ) expected(7,35): error CS1002: ; expected","className":"CompilationError"}}}},"level":0}
{"tag":"dap.send","timestamp":1627073804506,"metadata":{"connectionId":1,"message":{"seq":98,"type":"response","request_seq":32,"command":"setVariable","success":false,"message":"Invalid expression","body":{"error":{"id":9223,"format":"Invalid expression","showUser":true}}}},"level":0}
{"tag":"dap.send","timestamp":1627073809500,"metadata":{"connectionId":1,"message":{"seq":99,"type":"event","event":"output","b
```

**Comment by connor4312** [comment]
Setting a variable happens in two steps. First, `evaluateOnCallFrame` is used to convert the entered expression into a value. Then, once evaluate, `Debugger.setVariableValue` is used to assign the result of the expression to the value. This works in Chrome.

I suggest reopening the issue on the dotnet repo. If Blazor cannot deal with the expression being assigned when setting variables, then it can return an error from `evaluateOnCallFrame` to be displayed in the UI -- it seems like a separate bug that VS does not display that error in your screenshot. However, if it can, then it should and return it like any other call to `evaluateOnCallFrame`.

We could special-case for simple strings and numeric literals to skip `evaluateOnCallFrame`, but it would make better sense to me that Blazor would want to support this flow as browsers do.

**Comment by thaystg** [comment]
I could fix it on my side.
