### ISSUE TITLE
Debug flask web app

### ISSUE THREAD

**Issue by Tony763** [microsoft/vscode-js-debug#1147]
Hello, is there a way to debug flask web app?
With:
```
{
            "name": "Launch Chrome",
            "request": "launch",
            "type": "pwa-chrome",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}/templates"
        },
```
When I want to return a page I get in vs code `localhost꞉8080/show_stats꞉19:9: Source not found.`

**Comment by connor4312** [comment]
Most likely your `webRoot` is not correct. Though without more info such as repro steps I can't be of much help.
