### ISSUE TITLE
Adopt the pre-release extensions support

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-js-debug#1151]
These docs should help https://github.com/microsoft/vscode-docs/blob/vnext/api/working-with-extensions/publishing-extension.md#pre-release-extensions 
Let me know if you have any questions

**Comment by connor4312** [comment]
I don't think prerelease builds will work for js-debug right now. VS Code disallows installing alternative versions of built-in extensions, so users could not opt into js-debug's prerelease

![image](https://user-images.githubusercontent.com/2230985/146581353-1b234591-a983-4137-83a5-c5ef5a147612.png)

**Comment by isidorn** [comment]
Correct. I forget that `js-debug` is built-in, sorry. We do not yet have a solution for this, you are right.
fyi @sandy081
