### ISSUE TITLE
Incoherent behavior on asking for object properties details.

### ISSUE THREAD

**Issue by ilonatommy** [microsoft/vscode-js-debug#1153]
For most of fields in following test class, properties expansion in watch results in execution "getProperties" (fields with Ok in name). however, when a field has a custom accessor ("NotOk" in the name), properties expansion results in  "callFunctionOn" execution. This behavior is not homogenous and makes it difficult to maintain custom debugger based on commands sent by js-debugger.
```
    public class Test
    {
            public static List<int> listFieldOk = new List<int>() { 1, 2 };
            public static string textFieldOk = "text";

            public static List<int> listPropOk { get; set; }
            public static string textPropOk { get; set; }

            public List<int> listCustomNotOk { get { return new List<int>() { 1, 2 }; } }
            public string textCustomNotOk { get { return "text"; }
            
            public TestEvaluatePropertiesNone()
            {
                listPropOk = new List<int>() { 1, 2 };
                textPropOk = "text";
            }
    }
```
**To Reproduce**
1. Create a new Blazor Application with Web Assembly
2. Add the above class to the app, create instance
3. Add to watch
4. Compare behavior on expanding properties of Ok and NotOk properties.

**Expected behavior**
On each properties expansion, OnProperties should be called, regardless of the parent's content.

**Comment by connor4312** [comment]
Using `callFunctionOn` is the same behavior that Chrome/Edge devtools use to retrieve accessor values. I'm not aware of any other way that accessors are evaluated. Do you have any suggestions?

**Comment by connor4312** [comment]
Closing as there's been no movement here for several years
