### ISSUE TITLE
Unbound breakpoint in Angular project & Could not read source map

### ISSUE THREAD

**Issue by AbhiramTS** [microsoft/vscode-js-debug#1155]
Break point set in .ts files are being shown as unbound breaking point. If I were to put a "debugger" instead of break point, it hits the compiled ".js" file instead of the ".ts" file. It was working as intended before the update.

this is my launch.json

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome",
            "url": "http://localhost:4200",
            "webRoot": "${workspaceFolder}",
            "sourceMaps": true,
            "sourceMapPathOverrides": {
                "/./*": "${webRoot}/*",
                "/src/*": "${webRoot}/*",
                "/*": "*",
                "/./~/*": "${webRoot}/node_modules/*"
            }
        }
    ]
}
```
I tried adding 
```
"resolveSourceMapLocations": [
    "${workspaceFolder}/**",
    "!**/node_modules/**"
]
```
Without any success

this error is being shown on the debug console.
![image](https://user-images.githubusercontent.com/18684444/146340750-6c8794d0-02cf-4dbe-8926-b272c6ea43cc.png)

and this is the trace file

[vscode-debugadapter-438f1773.json.gz](https://github.com/microsoft/vscode-js-debug/files/7725832/vscode-debugadapter-438f1773.json.gz)

Thank You in advance

**VS Code Version:** 1.63.1
**OS Version:** Linux Manjaro KDE

**Comment by connor4312** [comment]
I see you have a breakpoint in `client-time-sheet-details.component.ts`, but that component is not loaded in the application. The breakpoint will be shown as unbound until its script is loaded.

**Comment by AbhiramTS** [comment]
Sorry for the delay in replying. The component was loaded in the application.I tried putting "debugger" ,it was hitting in chrome and I could view the .ts file in chrome. Usually when I do that, it will also be shown on VS Code,but now instead its shown in a ".js" file. Please see the screenshots attached.

**Breakpoint and Debugger Set in .ts File**
![image](https://user-images.githubusercontent.com/18684444/146719049-f12c3d3d-299c-4435-82b7-ac81873d6b11.png)

**Debugger Hit in module.js file**
![image](https://user-images.githubusercontent.com/18684444/146719083-e8963128-1c7d-4e9f-9a4a-b2c1ba085b60.png)

**Error in debug console showing 503 responce code**
![image](https://user-images.githubusercontent.com/18684444/146719109-5a0a99fc-a7c7-4220-b030-6796f6b46d43.png)

**Debugger hit in chrome**
![image](https://user-images.githubusercontent.com/18684444/146719216-aa8b1b70-484e-472c-93ed-c76efdb5b479.png)

**Comment by AbhiramTS** [comment]
> I see you have a breakpoint in `client-time-sheet-details.component.ts`, but that component is not loaded in the application. The breakpoint will be shown as unbound until its script is loaded.

Hi, any update on this issue?

**Comment by connor4312** [comment]
Ah, thanks, that's more helpful!

So what is happening is the script loads from `http://localhost:4200/modules-payroll-payroll-module.js` and then says it has a sourcemap at `http://localhost:4200/"modules-payroll-payroll-module.js.map`. And then as you see trying to actually make that request fails. This may be due to some kind of firewall or permission error in the context of where VS Code is running. I recommend investigating that on your machine.

Alternately, you could tweak how sourcemaps are generated. If you can configure the CLI to create an inline sourcemap, that will be given directly to VS Code by Chrome.

**Comment by AbhiramTS** [comment]
> And then as you see trying to actually make that request fails. This may be due to some kind of firewall or permission error in the context of where VS Code is running. I recommend investigating that on your machine.

uh... can you tell me how I would go about that...I am using a Linux machine(Manjaro). Can you tell me what could be the possible reason for that.It used to work fine before the latest update.

Thank You

**Comment by AbhiramTS** [comment]
> I recommend investigating that on your machine.

@connor4312 Can you tell me what I need to check...

**Comment by connor4312** [comment]
I'm not at all familiar with Manjaro. On Ubuntu we've seen some permission weirdness with `snap` installs but not sure whether that applies to your case.

**Comment by AbhiramTS** [comment]
an update...there is no issue when serving with **"--host=127.0.0.1"**  but the issue is still there when I try it with **"localhost"**

**Comment by connor4312** [comment]
In the past I've seen some oddities where `localhost` binds to only the IPv6 or IPv4 loopback, but when other applications resolve `localhost` they get the wrong version. Perhaps that's what's going on here.

**Comment by connor4312** [comment]
In https://github.com/microsoft/vscode-js-debug/commit/bc90de2b23442d68efb6e9304e28fe1a77dcb3fd we now try both localhost and 127.0.0.1 if we see a "connection refused" type of failure which I think should resolve this.
