### ISSUE TITLE
Force references from outside of the lexical scope accessible

### ISSUE THREAD

**Issue by HosseinAlipour** [microsoft/vscode-js-debug#1156]
In debug mode, Is there any way to force the evaluation of the `a` variable in the sub scope, without defining it explicitly in the scope?
```
const a = 'something';

(() => {
    debugger;
// a is not accessible in debug mode unless we define it explicitly in the scope
})()
```

**Comment by connor4312** [comment]
No, this is a V8 behavior. As far as I know there are no flags or methods to change it.
