### ISSUE TITLE
Not hitting breakpoints in typescript code running under node showing main.ts  Skipped by smartstep

### ISSUE THREAD

**Issue by mwoodpatrick** [microsoft/vscode-js-debug#1159]
**Describe the bug**
I'm trying to debug a typescript program running on wsl-2 ubuntu 20.04 but it's not stopping at the breakpoints I'm setting and I'm seeing an editor window showing my program with the title "main.ts Skipped by smartstep" even though my launch.json has:

      "stopOnEntry": true,
      "sourceMaps": true,
      "smartStep": false,
      "trace": true,

Any suggestions on how to debug would be much appreciated

**VS Code Version:** Replace me!

Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by connor4312** [comment]
Please collect a log file using the instructions in the issue template. Thanks!
