### ISSUE TITLE
cannot debug node applications

### ISSUE THREAD

**Issue by LirazRom** [microsoft/vscode-js-debug#1166]
I am running with version 
Version: 1.63.2 (Universal)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

and I cannot debug my node applications
i have tried to enable the auto attach but it never attach

when looking in the setting file
debug.javascript.autoAttachFilter
is marked as unknown configuration setting

{
    "workbench.iconTheme": "vscode-icons",
    "files.autoSave": "afterDelay",
    "explorer.confirmDelete": false,
    "vs-kubernetes": {
        "vscode-kubernetes.kubectl-path.mac": "/Users/liraz/.vs-kubernetes/tools/kubectl/kubectl",
        "vscode-kubernetes.minikube-path.mac": "/Users/liraz/.vs-kubernetes/tools/minikube/darwin-amd64/minikube",
        "vscode-kubernetes.helm-path.mac": "/Users/liraz/.vs-kubernetes/tools/helm/darwin-amd64/helm"
    },
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "redhat.telemetry.enabled": true,
    "go.toolsManagement.autoUpdate": true,
    "security.workspace.trust.untrustedFiles": "open",
    "debug.javascript.autoAttachFilter": "always",
    "docker.showStartPage": false,
    "vsicons.dontShowNewVersionMessage": true,
}

**Comment by connor4312** [comment]
Please search for `@disabled` extensions in the Marketplace tab, perhaps your js-debug extension got disabled at some point.

**Comment by LirazRom** [comment]
thanks
