### ISSUE TITLE
Unbound breakpoint in lerna project

### ISSUE THREAD

**Issue by ZoeLeee** [microsoft/vscode-js-debug#1169]
tsconfig.json
`
{
    "compileOnSave": true,
  
    "compilerOptions": {
      "downlevelIteration": true,
      "rootDirs": ["src"],
      "outDir": "dist",
      "baseUrl": ".",
      "moduleResolution": "node",
      "target": "es5",
      "module": "commonjs",
      "jsx": "react",
      "experimentalDecorators": true,
      "esModuleInterop": true,
      "sourceMap": true,
      "skipLibCheck": true,
      "skipDefaultLibCheck": true,
      "noUnusedLocals": false,
      "declaration": true,
      "declarationMap": true,
      "lib": ["esnext", "dom"],
      "types": ["node"],
    },
    "exclude": ["node_modules", "dist", "test", "webpack", "script", "src/**/*.spec.*"]
  }
`

launch.json
```
{
  // 使用 IntelliSense 了解相关属性。
  // 悬停以查看现有属性的描述。
  // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "pwa-chrome",
      "request": "launch",
      "soureMap": true,
      "name": "Launch Chrome against localhost",
      "url": "http://localhost:9001",
      "webRoot": "${workspaceFolder}"
    }
  ]
}

```
project structure
![image](https://user-images.githubusercontent.com/33168975/148507832-ef504f27-02b3-4566-8cf5-73442a322dc5.png)

**Comment by bpasha7** [comment]
I use vue 3 and after the last update, it stopped working. I just add this https://vuejs.org/v2/cookbook/debugging-in-vscode.html#Displaying-Source-Code-in-the-Browser

**Comment by connor4312** [comment]
Please collect a log file using the instructions in the issue template

**Comment by ZoeLeee** [comment]
> I use vue 3 and after the last update, it stopped working. I just add this https://vuejs.org/v2/cookbook/debugging-in-vscode.html#Displaying-Source-Code-in-the-Browser

Thanks,referring to this configuration, it solved my problem.
