### ISSUE TITLE
How to enabe vue debug extension on  Edge Debug mode ?

### ISSUE THREAD

**Issue by Michaelzhouisnotwhite** [microsoft/vscode-js-debug#1177]
It is Good to launch microsoft edge tools. However I want to debug html with vue extension and I cant open the extension menu on edge.
![image](https://user-images.githubusercontent.com/52443370/149647113-b6276928-a8f3-44da-9126-90ae33487846.png)

**Comment by connor4312** [comment]
Please open this issue on https://github.com/Microsoft/vscode-edge-devtools. Thanks!
