### ISSUE TITLE
Node debugging extremely slow on startup and after first breakpoint

### ISSUE THREAD

**Issue by imnitishng** [microsoft/vscode-js-debug#1179]
**Description**
ExpressJS application becomes unresponsive for a long time whenever VSCode debugger is attached to the application.
The application works as expected and starts up instantly when run normally in a terminal (`node dist/server.js`) or using node default debugger (`node inspect dist/server.js`). Just a note that the Express JS application in context here isn't super resource intensive, just some basic CRUD operations and debugging experience on VSCode on other low specs Linux machines is seamless and has no such issue.
The issue only occurs whenever VSCode's debugger is attached to the application, be it in any form (launch configuration, javascript debug terminal or node process attach). 

Here is the full debugging scenario for more context on the issue
1. If the application is launched using the launch configuration the application won't start instantly (i.e. if I goto `localhost:3000` the browser will stuck loading for 2-3 mins), it eventually starts and the first breakpoint is hit but once I step forward in the debugger nothing happens and I have to wait 1-2 mins to reach the next line, after that the debugger works normally. So the main issue is the unresponsive behaviour on attaching debugger and after step over the first breakpoint.
2. Now if I start the application normally in the terminal, it starts working the browser almost instantly, now once I attach VSCode  debugger to the node process and hit any of the application endpoint it hangs and I'll have to wait for the debugger to hit the first breakpoint, and then again wait after stepping forward from the first breakpoint. After this things work normally without any waiting times.

**To Reproduce**
1. Run an express JS application with the following run configurations
```json
{
    "configurations": [
// for scenario 2 listed above
        {
            "name": "Attach by Process ID",
            "processId": "${command:PickProcess}",
            "request": "attach",
            "skipFiles": [
                "<node_internals>/**",
                "${workspaceFolder}/node_modules/**/*.js",
            ],
            "sourceMaps": true,
            "trace": true,
            "type": "pwa-node"
        },
// for scenario 1 listed above
        {
            "type": "pwa-node",
            "request": "launch",
            "name": "Debug with watch task",
            "skipFiles": [
                "<node_internals>/**",
                "${workspaceFolder}/node_modules/**/*.js"
            ],
            "program": "${workspaceFolder}/dist/server.js",
            "outFiles": [
                "${workspaceFolder}/dist/**/*.js"
            ],
            "sourceMaps": true,
            "trace": true,
            "preLaunchTask": "tsc: watch - tsconfig.json"
        }
    ]
}
``` 

**Log File**
- Log file for scenario 1 listed above [vscode-debugadapter-f1751c97.json.gz](https://github.com/microsoft/vscode-js-debug/files/7876591/vscode-debugadapter-f1751c97.json.gz)
- Log file for scenario 2 listed above [vscode-debugadapter-07d46764.json.gz](https://github.com/microsoft/vscode-js-debug/files/7876592/vscode-debugadapter-07d46764.json.gz)

**VS Code Version:** 
```
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:38:17.605Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.2.0
```

**Additional context**
Machine Specs
<img width="243" alt="Screenshot 2022-01-16 at 2 10 20 PM" src="https://user-images.githubusercontent.com/35267629/149653077-3f9461cf-2ace-4d44-9b2f-061f8562db3a.png">

**Comment by connor4312** [comment]
Does this issue go away if you remove `${workspaceFolder}/node_modules/**/*.js` from your `skipFiles`?

**Comment by imnitishng** [comment]
It did! Thanks!
I wonder why this happened in the first place, do `node_modules` not belong in `skipFiles`? Or is it a mac thing?

**Comment by connor4312** [comment]
It's a bug thing 🙂 I will most likely fix this the first week of Feb.

**Comment by MihaiBojescu** [comment]
Any updates on this one? The issue is still present 😞

**Comment by henryatzeal** [comment]
Reinstalling the x64 version of node/nvm resolved this sort of issue for me.

**Comment by fgirardey** [comment]
I also found out that `skipFiles` is making JS debug very slow, is there a fix in the pipe somewhere?

**Comment by nextlevelbeard** [comment]
@connor4312 Any prospect of fixing this soon?
Skipping `node_modules` is essential for a lot of development and this is really incapacitating the debugger.
Sad to see this issue pushed back for months.

Can you provide more insight on what might cause it, maybe the community can help

**Comment by connor4312** [comment]
The issue is that setting a very large array of blackboxed patterns...

https://github.com/microsoft/vscode-js-debug/blob/812a259f1f09a5c6527f0940f81e5efb6f1eb0da/src/adapter/scriptSkipper/implementation.ts#L157

...causes the runtime to work very slowly.

Unfortunately, the runtime does not have any notion of negations. In the simple case where all node_modules are blackboxed, this could be made more efficient pretty easily. However, if there are later inclusions within the node_modules, this becomes more complicated.

**Comment by garyking** [comment]
This issue didn't exist until maybe a year ago, is that right? I don't recall experiencing it until only relatively recently. Yet the apparently problematic line was last touched 3 years ago?

So the current solution is to essentially keep the total number of paths in `skipFiles` to a minimum, which usually means to *not* include `node_modules` in it?

**Comment by orjinalp** [comment]
it happens again with this problem
