### ISSUE TITLE
Console in Edge not having REPL functionality nor window access

### ISSUE THREAD

**Issue by codepo8** [microsoft/vscode-js-debug#1182]
**Describe the bug**
When launching an Edge instance via the debugger workflow or launch.json you get the Console in the Debug Console, but all you get is log messages. There is no access to the Window object nor any REPL functionality.

This is on Mac.

Additionally, even with trace enabled, there is no log being written.

![image](https://user-images.githubusercontent.com/13508/150095260-ce83f40d-8ecf-47e9-85c8-b69604dd77c0.png)

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/138963
