### ISSUE TITLE
Extensions want to remove these existing changes from the terminal's environment

### ISSUE THREAD

**Issue by denik1981** [microsoft/vscode-js-debug#1185]
Issue Type: <b>Bug</b>

I'm getting a warning sign on my Terminal  coming from the vscode-debug-nightly extension. The Action request is to relaunch the Terminal but the warning sign shows up again.

Extensions want to remove these existing changes from the terminal's environment:

NODE_OPTIONS=--require /home/demian/.config/Code/User/workspaceStorage/2c2e9dd83af10bc1fd96a6edb2a52053/ms-vscode.js-debug-nightly/bootloader.js ${env:NODE_OPTIONS}
VSCODE_INSPECTOR_OPTIONS=${env:VSCODE_INSPECTOR_OPTIONS}:::{"inspectorIpc":"/tmp/node-cdp.1254423-1.sock.deferred","deferredMode":true,"waitForDebugger":"","execPath":"/home/demian/.volta/bin/node","onlyEntrypoint":false,"autoAttachMode":"always"}

Extension version: 2022.1.1417
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.11.0-46-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 x 1000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.70GB (1.27GB free)|
|Process Argv|--unity-launch --crash-reporter-id 33efc46f-e006-4ef9-be0b-4858543fff23|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30424896
pythonvs932:30410667
vscop804:30404766
vscop453:30404998
vsrem710cf:30416617
vsbas813:30426126

```

</details>

**Comment by connor4312** [comment]
Could you capture a gif of what you're seeing? https://gifcap.dev/ is good

**Comment by denik1981** [comment]
![Recording 2022-01-20 at 21 25 58](https://user-images.githubusercontent.com/66160623/150443521-db70cb66-ee72-44cc-a094-75c574540d4c.gif)

Sometimes I might have a lot of terminal instances showing that warning sign. 
Please, note that up to now is just a warning display but it didn't affect on any functionally although I might not be aware of it.
Of course that I have reloaded and relaunched my terminal and vscode entirely.

**Comment by denik1981** [comment]
Ok, I have researched a little bit more and this happens when I toogle the AutoAttach debug feature and start and attach to a debug session within a node.

**Comment by connor4312** [comment]
Yea, it's expected that this warning sign will show up when toggling auto attach. Auto attach works via environment variables, and thus a reload is necessary to apply them. What is unexpected is this:

> The Action request is to relaunch the Terminal but the warning sign shows up again.

From what I understand, you're saying

1. You have the warning sign on a terminal
2. You hit the "relaunch terminal" link on the hover dialog
3. The terminal relaunches, but the ⚠️  is still there

Is this correct / can you clarify?

**Comment by denik1981** [comment]
Yes, mostly that. But not all the time. Need to understand when it clearly happens so I can make a solid case for it.
I know that happens on AutoAttach. 

I "suspect" is regarding a memory leak because I saw that on the console log for vscode-dev-tools, and I suspect the leak is regarding the number of listeners that are opened.  All this is just hypothetical based on the logs. I'm currently not seeing the issue. I will try to post the logs of the console if I see it again.
