### ISSUE TITLE
debug adapter not respecting ValueFormat fields

### ISSUE THREAD

**Issue by EricCornelson** [microsoft/vscode-js-debug#1188]
When the IDE wants to display values in hexadecimal, it sets the `hex` field on the `format` field (in Evaluate request, StackTrace request, Variables request, etc.), but the debug adapter currently ignores this value.

![image](https://user-images.githubusercontent.com/38218905/151417803-207b62c3-d6f3-4f7e-8160-25d15066d370.png)

**Log File**
[visualstudio-js-debugger.txt](https://github.com/microsoft/vscode-js-debug/files/7952828/visualstudio-js-debugger.txt)

**Comment by connor4312** [comment]
I don't think this is something we ever supported, so marking it as a feature.

**Comment by connor4312** [comment]
@EricCornelson can you validate that this works?

**Comment by JacksonKearl** [comment]
Verified by changing https://github.com/microsoft/vscode/blob/188b1a51fe48a225c2a977e2b32c472b46845d36/src/vs/workbench/contrib/debug/browser/debugSession.ts#L591:
```
return this.raw.evaluate({ expression, frameId, context, format: { hex: true } });
```

The right value is shown, though I'd expect a `0x` prefix?

<img width="190" alt="image" src="https://user-images.githubusercontent.com/8586769/160035957-02fceb66-7c03-4fda-99c9-298cd908a892.png">
