### ISSUE TITLE
Debug Blazor using Edge on Ubuntu

### ISSUE THREAD

**Issue by thaystg** [microsoft/vscode-js-debug#1190]
**Describe the bug**
Launch Edge on ubuntu and redirect to the page set in url parameter - using nightly build of vscode-js-debug.

**To Reproduce**
1. Create a new folder called `MyBlazorApp` somewhere
2. Navigate inside the folder and Open in Terminal
3. Type `dotnet new blazorwasm`
4. Type `code .; exit`
5. Allow VS Code to auto-generate `launch.json` and `tasks.json`
6. Inside `launch.json`, add `"browser": "edge"` to the first configuration in the list and set the url to the url defined in your `launchSettings.json`
6. Go to the file `Counter.razor` inside of the `Pages` folder and put a breakpoint where it says `currentCount++;`
7. Press `F5` to debug
8. It launches the browser but doesn't redirect to the url set in `launch.json`

Related to https://github.com/dotnet/aspnetcore/issues/38413

**Comment by connor4312** [comment]
It appears that, in connecting to the Blazor proxy to create a websocket connection, it uses a 302 redirect to a different, `http://` url. As websocket connections do not work over the `http:` protocol, the connection then fails. @thaystg this looks like something to be fixed on the Blazor side of things

![image](https://user-images.githubusercontent.com/2230985/151888732-ee21f11b-009b-4e4a-81f5-15b34ef61e96.png)

This is where the error is caught, you can set a breakpoint here and debug up the stack to see more info 

https://github.com/microsoft/vscode-js-debug/blob/728b43331d3120edd4069c98395110895bafaf4e/src/cdp/webSocketTransport.ts#L44

**Comment by thaystg** [comment]
I don't think it's on BrowserDebugProxy side, once it works correctly on Chrome.

**Comment by connor4312** [comment]
It doesn't work on Chrome nor Edge for me

**Comment by thaystg** [comment]
At least for me when I launch the BlazorApp using browser = edge on chrome, it shows a about:blank page on edge and never redirects to the correct url.

**Comment by thaystg** [comment]
Is your launch.json like this:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch and Debug Standalone Blazor WebAssembly App",
            "type": "blazorwasm",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "browser": "chrome",
            "url": "http://localhost:5133"
        }
    ]
}
```

**Comment by connor4312** [comment]
If I add the `url` to the config, then I get an ECONNREFUSED on both Edge and Chrome. If I omit the URL, I get the error I mentioned before (`The URL's protocol must be one of "ws:", "wss:", or "ws+unix:"`) on both Edge and Chrome.

**Comment by indcoder** [comment]
> I don't think it's on BrowserDebugProxy side, once it works correctly on Chrome.

Appros my comment in the original issue, it does not work on Chrome and Canary too. It worked initially on Chrome(didnt test with Edge then) but it stopped working across all Chromium based browsers.

https://github.com/dotnet/aspnetcore/issues/38413#issuecomment-1024795799

**Comment by thaystg** [comment]
@connor4312 can you try?
1) Install the extension: https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.blazorwasm-companion and also c# extension.
2) get this repo: https://github.com/JansthcirlU/MyBlazorApp
3) use this launch.json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch and Debug Standalone Blazor WebAssembly App",
            "type": "blazorwasm",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "browser": "chrome",
            "url": "http://localhost:5133"
        }
    ]
}

**Comment by connor4312** [comment]
Ok, thanks! I noticed I got a warning that your project targeted NET 5, apparent `latest/edge` of dotnet-sdk is .NET 5, not 6, so I got that upgraded, `dotnet --version` is 6.0.101 and I see 6.0.1 DLL's being used to build. However I run into the same redirection error.

Let me know if there's further information I can help with.

**Comment by thaystg** [comment]
Using the configuration that I described could you make it work on Chrome?

**Comment by connor4312** [comment]
No, I got the issue on both browsers.

**Comment by thaystg** [comment]
There is still something weird in your environment I think. Any information that I can collect in my environment where on Chrome is working to help you to figure out the difference?

**Comment by connor4312** [comment]
Not sure, this is a fairly vanilla Xubuntu setup running in HyperV. The Blazor proxy redirects the websocket to an `http:` address, which is invalid -- perhaps someone with knowledge of the proxy could help figure out in what scenario this could happen? To be clear that's `ws://localhost:5133/_framework/debug/ws-proxy?browser=...` issuing a 302 redirect to `http://127.0.0.1:40509/devtools/browser/...`

**Comment by thaystg** [comment]
I'm on of the ones who knows about the Proxy.

Before that part of redirecting that you described, the Blazor page should be loaded on browser, do you know why the Blazor page is not loaded on browser? We should never see that about:blank page.

**Comment by connor4312** [comment]
When js-debug opens a browser, it intentionally opens it to `about:blank` so that any breakpoints can be transmitted to the browser before a page starts loading. It only gets navigated to the blazor app once js-debug connects.

Also, if I patch in some code to the `ws` library to rewrite the redirect URL to be `ws:` instead of `http:`, then both Edge and Chrome work.

**Comment by thaystg** [comment]
Ohhh, okay, something on vscode-js-debug extension was changed.

If I test NOT using the nightly build it works on chrome and it doesn't work on Edge (it doesn't launch edge because it's not implemented)

If I test using NIGTHLY build both chrome and edge are launched but I get the same error that you are describing.

**Comment by connor4312** [comment]
Hm, let me try stable and get back to you.

**Comment by connor4312** [comment]
Ahh, okay. Yea Edge on Linux support was only added this iteration (https://github.com/microsoft/vscode/issues/138495). I'll poke around and see if I can see what changed that caused the redirect to happen.

**Comment by connor4312** [comment]
I think this might just because I updated a bunch of dependencies, including `ws`, for component governance, and the old version of `ws` might not have included the protocol check. I could downgrade it as a temporary measure, but would it be possible to modify the proxy so that the redirect gets an `ws:` protocol? With that I think everything should work here...

**Comment by connor4312** [comment]
@thaystg gentle ping here 🙂  Our next release is going out tomorrow fyi

**Comment by thaystg** [comment]
We could fix on aspnetcore side.
Thanks, Connor.

**Comment by ChristianWeyer** [comment]
Are you able to elaborate on where and how this was fixed @thaystg ? Thanks!

**Comment by lewing** [comment]
@ChristianWeyer the patch is here https://github.com/dotnet/aspnetcore/pull/39995

**Comment by ChristianWeyer** [comment]
Great, thank you!

**Comment by connor4312** [comment]
Verified in Insiders by the Blazor team

**Comment by indcoder** [comment]
I can confirm too

<img width="909" alt="image" src="https://user-images.githubusercontent.com/2099300/153315526-7413f922-af96-4f22-8d47-302ee658c8a3.png">

But I'm not sure if the new error cropping up in another extension is related to this change 

Error loading "hint" package from "c:\xxxx\TestVSCodeDebug"
Trying to load shared version
Found hint at c:\xxxxxxxx\AppData\Roaming\Code - Insiders\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\index.js
c:\xxxxx\AppData\Roaming\Code - Insiders\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151
                throw new types_1.AnalyzerError(e, error_status_1.AnalyzerErrorStatus.AnalyzeError);

<img width="676" alt="image" src="https://user-images.githubusercontent.com/2099300/153315947-6a1b03c0-60d9-4464-b187-d7cd1841e35b.png">
