### ISSUE TITLE
Logpoint suspends/breaks the execution unexpectedly

### ISSUE THREAD

**Issue by xpomul** [microsoft/vscode-js-debug#1191]
**Describe the bug**
I wanted to put a logpoint in my backend service to see on the console when it is called.
But sadly, when the execution reaches the respective line, execution is suspended. Only after resuming execution, the expected log message is printed.

**To Reproduce**

1. Start VS Code
2. Use "Remote-Containers: Clone Repository in Container Volume...“ and clone the https://github.com/xpomul/theia-boilerplate repository branch `hello-world`
3. After some waiting to get everything installed, open `hello-world-impl.ts` and add a logpoint with the expression `test` in line 7 
4. Go to the Run/Debug view and select the Launch Backend launch configuration and start it
5. Open a browser at `http://127.0.0.1:3000` and run `Edit > Say Hello`

**Log File**
[vscode-debugadapter-79e72f37.json.gz](https://github.com/microsoft/vscode-js-debug/files/7989705/vscode-debugadapter-79e72f37.json.gz)

**VS Code Version:** VS Code 1.63.2 

**Additional context**
I am quite new to JavaScript/TypeScript development in VS Code - sorry if this is a dumb question/issue, but I have had a question on StackOverflow https://stackoverflow.com/questions/70938984/vs-code-logpoint-suspends-breaks-the-execution-unexpectedly that has been unanswered for two days now, so it seems at least not a straight-forward n00b thing...

**Comment by connor4312** [comment]
This is because Their overwrites `console.log` such that it returns truthy (a promise) and triggers the breakpoint

**Comment by xpomul** [comment]
I can confirm that it’s fixed in the latest nightly. Awesome - thank you for the quick fix :-)
