### ISSUE TITLE
Debugger does not attach to Electron 14+ until dev tools are manually opened.

### ISSUE THREAD

**Issue by DJ4ddi** [microsoft/vscode-js-debug#1193]
**Description**
I am using an Electron configuration with a main process accessed using node launch and a renderer process using chrome attach.

After upgrading the Electron version to 14+, the VSCode debugger no longer attaches to the renderer process until the dev tools are opened manually. Until then, no breakpoints are hit, no output is shown, the console does not work and extensions accessing the session fail.

Everything is working as intended using Electron ^13 (13.6.8) or below (also tested with ^12), but breaks when using Electron ^14 (14.2.5) or above (also tested with ^15).

**Files**
[vscode-debugadapter-launcher.json.gz](https://github.com/microsoft/vscode-js-debug/files/8010801/vscode-debugadapter-launcher.json.gz) (successful connection)
[vscode-debugadapter-renderer.json.gz](https://github.com/microsoft/vscode-js-debug/files/8010802/vscode-debugadapter-renderer.json.gz) (successful connection after opening dev tools)
[vscode-debugadapter-renderer-before.json.gz](https://github.com/microsoft/vscode-js-debug/files/8010818/vscode-debugadapter-renderer-before.json.gz) (unsuccessful connection before opening dev tools)
[launch.zip](https://github.com/microsoft/vscode-js-debug/files/6840519/launch.zip) (Launch configurations for both)

**Versions**
VSCode: 1.64.0
Node.js: 16.5.0
Electron: 15.3.6

**Comment by connor4312** [comment]
I see some 'weirdness' in the logs but would need a reproduction in order to munge around and see what needs to be fixed on the debugger side (or whether it's a Chromium issue). I'm not able to hit this using Electron 17 in https://github.com/electron/electron-quick-start. Are you able to provide a reproduction case or modify the quickstart so that the issue happens there?

**Comment by DJ4ddi** [comment]
After fiddling around with this for a while, I found that the issue is my `serverReadyAction` attaching the debugger too early. If I change the patten to a later message, it works as before.

I haven't yet managed to find out why this doesn't happen on earlier Electron versions. I also can't reproduce it in a minimal project. The behavior when I try to provoke this issue by sending a log message that triggers the attach command before initializing anything is exactely what I expect: The launch waits for the window to become available, then attaches correctly. With the broken launch, the debugger only starts after the main process is *closed*.

For my use case, changing the listening pattern of the launch configuration is fine, so I'll close this issue and reopen when I have new findings.

**Comment by connor4312** [comment]
Hm, that does make it sound like a timing-based issued in Chromium/Electron.
