### ISSUE TITLE
JS debug console gives errors on a couple common Array functions

### ISSUE THREAD

**Issue by kruchkamgar** [microsoft/vscode-js-debug#1201]
simple Array functions, executed in the JS debug console, appear to result in errors. (sample shown below)

```
[1,2,3].find(key => key > 2)
Uncaught SyntaxError: Invalid destructuring assignment target
[1,2,3].filter(key => key > 2)
Uncaught SyntaxError: Invalid destructuring assignment target

```
**To Reproduce**
1. run a JS file with a debugger statement
2. when it stops on debugger statement, try to enter an Array function in the JS debug console

**Log File**

**VS Code Version:** 
Version: 1.64.1
Commit: d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03
Date: 2022-02-07T17:26:08.977Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

**Additional context**

**Comment by connor4312** [comment]
I can't repro this. Please collect a log using the instructions in the issue template.

![image](https://user-images.githubusercontent.com/2230985/153347362-29511980-c3da-49fc-bc86-a9a082ba4ed3.png)

**Comment by alexhalme** [comment]
I've had the same issue for months. Extremely annoying. [1, 2, 3].map(x => x) will cause the error, then changing the variable will work temporarily → e.g. [1, 2, 3].map(xx => xx) will work for a while, then need to change var name again.

**Comment by connor4312** [comment]
@alexhalme  Please collect a log file using the instructions in the issue template.

**Comment by kruchkamgar** [comment]
@connor4312, I initially tried to add `"trace": true` to my settings file and launch.json file and neither resulted in any output to debug console.

**Comment by kruchkamgar** [comment]
![Recording 2022-03-02 at 17 54 21](https://user-images.githubusercontent.com/1715504/156475492-f5c2ceea-1697-413f-a305-e7b4127468dd.gif)

looks like it happens with jest only. I tried it without jest and it worked fine.

**Comment by connor4312** [comment]
Ok, what you want to do to get a trace log from there is add this to your user settings:

```
  "debug.javascript.terminalOptions": {
    "trace": true
  },
```

You'll then want to reopen or create a new Debug Terminal, and that should get you the trace log

**Comment by kruchkamgar** [comment]
[vscode-debugadapter-6b752bf8.json.zip](https://github.com/microsoft/vscode-js-debug/files/8203275/vscode-debugadapter-6b752bf8.json.zip)

trace log..
second action taken: 'find((key)...'

**Comment by connor4312** [comment]
Got it, thanks!

**Comment by connor4312** [comment]
The next [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) will have the fix, please let me know whether you run into this again!

**Comment by meganrogge** [comment]
with 

```
let x = 5;
// eslint-disable-next-line no-debugger
debugger;
```
It's not stopping at the debugger line at all for me. Maybe because of eslint or what am I doing wrong?

**Comment by connor4312** [comment]
@meganrogge can you grab a gif? THat sounds unrelated to this issue

**Comment by connor4312** [comment]
Verification instructions:

Create a file **minified.js**

```
const o=42;const c=43;debugger;console.log(o,c);
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIm9yaWdpbmFsLmpzIl0sIm5hbWVzIjpbInJlbmFtZWRWYXIiLCJhbm90aGVyUmVuYW1lZFZhciIsImNvbnNvbGUiLCJsb2ciXSwibWFwcGluZ3MiOiJBQUFBLE1BQU1BLEVBQWEsR0FDbkIsTUFBTUMsRUFBb0IsR0FDMUIsU0FDQUMsUUFBUUMsSUFBSUgsRUFBWUMifQ==
```

and also a file **original.js**

```
const renamedVar = 42;
const anotherRenamedVar = 43;
debugger;
console.log(renamedVar, anotherRenamedVar); 
```

Debug minified.js, with a launch config or in the debug terminal.

Once there, play around the REPL. Verify you can evaluate `renamedVar` and `anotherRenamedVar` as expected.  For this particular issue, use the renamed name as a parameter, for instance `[1, 2, 3].find(renamedVar => renamedVar === 2)`
