### ISSUE TITLE
Add validation for Blazor WebAssembly debugging scenario in VSCode

### ISSUE THREAD

**Issue by mkArtakMSFT** [microsoft/vscode-js-debug#1202]
## Context

The Blazor WebAssembly debugging experience broke in VSCode due to a recent dependency update which the vscode-js-debug took.
This has already been mitigated, however, there is no prevention mechanism in place to avoid issues like this one going forward.

## Ask
This request is about adding a basic Blazor WebAssembly debugging validation scenario for VSCode.

## Validation instructions

The below instructions assume that the user is going to have .NET 6 SDK installed on their machine.
1. Open command prompt
2. Create a new Blazor WebAssembly project using `dotnet new blazorwasm -o TestDebugging`
2. Navigate to the `TestDebuging` folder `cd TestDebugging`
3. Start VSCode in that folder by running `code .`
4. After VSCode opens a popup will show up suggesting to install required assets for building and debugging the project. Click `Yes`:
<img width="398" alt="image" src="https://user-images.githubusercontent.com/34246760/153512988-f037c630-2c6a-4b9e-810c-544f270631fe.png">

5. Open the `Pages\Counter.razor` file and add a breakpoint in the `IncrementCount` method, on the `currentCount++` line (Click F9)
<img width="298" alt="image" src="https://user-images.githubusercontent.com/34246760/153513226-196e2789-5d0e-4189-a1ce-181badabe2b3.png">

6. Start debugging by clicking `F5`. This will open a browser window with the following content:
<img width="712" alt="image" src="https://user-images.githubusercontent.com/34246760/153513686-2c3860e3-e29e-4305-8b0a-41d97c4d20d5.png">

7. Navigate to the `Counter` page on the left navigation menu
<img width="356" alt="image" src="https://user-images.githubusercontent.com/34246760/153513738-b6fa2d92-ce0b-40ba-820b-33f906803377.png">

8. Click the `Click me` button`

### Expected result
The debug session should break on breakpoint set in `step 5` above.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-js-debug/issues/307
