### ISSUE TITLE
wasm DWARF support

### ISSUE THREAD

**Issue by flipkickmedia** [microsoft/vscode-js-debug#1205]
Support C++ wasm with embedded DWARF

Currently it's possible inside Chrome Dev Tools to interactively debug C++ source.
![image](https://user-images.githubusercontent.com/15732784/153981823-49ec2dd9-d40f-4906-b8a6-eab02cbf5c53.png)

When a debugging session starts, this is the same result inside VSCode, unfortunately VSCode cant handle the encoding inside the WASM file.
![images](https://user-images.githubusercontent.com/15732784/153982011-4d2772d4-4db5-4d91-bd9f-c15407ecab76.png)

It would be great to see this happen.

**Comment by devshgraphicsprogramming** [comment]
I'm also interested in this feature, Chrome isn't an IDE and debugging in an IDE is nice.

We're trying to put together an example repo showing how to develop a Native app which can be deployed to the Web using both C++ and Emscripten but also C# and Blazor.

**Comment by connor4312** [comment]
The Chromium team is "actively working on" open sourcing their DWARF wasm debugger, and estimate that happening in the first half of next year. They also reportedly have a prototype VS Code extension. After they get their debugging components open source,I plan to work with them to see if/how that can be integrated into js-debug. I don't know where it would live yet. js-debug does have extensibility mechanisms, so maybe it can plug into those, or we can do some special integration with functionality that lights up when the wasm extension is installed. Lots of options.

**Comment by flipkickmedia** [comment]
> Unfortunately the Chrome extension is closed source, quite limited and buggy. (Sometimes it doesn't even work, most of the time stepping doesn't work, standard library types are not all inspectable etc.)
> 
> Our idea is write a VSCode extension that integrates with the existing browser debugging experience in VSCode and implements this feature request. (I recall that if we switch out the buildtime DWARF generation for sourcemap generation, this already works, except for inspecting values, which makes it quite useless for serious work.)
> 
> What I'm not certain about is where the boundaries of responsibility lie between VSCode itself, vscode-js-debug, the browser being debugged, the existing C++ extension and a theoretical new "Wasm debugger" extension. Is it possible to really implement this in a separate extension? Do the required points of extensibility exist within the browser debugging flow and the debugger itself? (It would be rather less convenient if we had to fork VSCode or parts of it to achieve this.)

I have the same concerns. Since this is C++ the responsibility probably sits inside the c++ extensions, or at least this makes the most sense from a users perspective, you're debugging C++, you'd expect it to be inside a C++ extension along with all the other C++ "stuff".

If the Chromium team is planning a release then it kinda makes sense to wait for that and if they created a new extension then the decision about where this sits may have already been made.

I wonder if I can get a pre release of the extension for testing....

**Comment by fatfatson** [comment]
it's almost half year, how about it?

**Comment by toyobayashi** [comment]
Can't wait to use this in vscode!

**Comment by connor4312** [comment]
Merging into https://github.com/microsoft/vscode-js-debug/issues/1789, somehow I didn't find this issue when I was searching earlier...
