### ISSUE TITLE
Debug output location for <node_internals> broken on Linux

### ISSUE THREAD

**Issue by trond-snekvik** [microsoft/vscode-js-debug#1208]
The debug console's location label appears to have an off-by-one error when rendering <node_internals> locations, and omits the opening `<`, but appends an extra `>` at the end:

![image](https://user-images.githubusercontent.com/7857838/154253944-7672f32e-1863-416f-957f-f1ea02e1e9e7.png)

This breaks the `skipFiles` mechanism for <node_internals> files.

**To Reproduce**

Any Mocha test suite that lists `**/node_modules/**` in `skipFiles` will have this artifact on lines produced by mocha. 
To create the screenshot above: 
1. Generate a VS Code extension with `yo code`
2. Add `**/node_modules/**` to `skipFiles` in the `Extension tests` launch configuration. 
3. Launch and observe.

**VS Code Version:** 1.64.2

Using the public version of the extension (v1.64.3), on Linux.

**Comment by connor4312** [comment]
> This breaks the skipFiles mechanism for <node_internals> files.

This is just a cosmetic bug with the label as far as I know

> Any Mocha test suite that lists **/node_modules/** in skipFiles will have this artifact on lines produced by mocha.

node_internals are separate from node_modules. You'll need to add node_internals to skipFiles as well

Will keep this issue open for the former issue

**Comment by trond-snekvik** [comment]
Sorry, I should have specified. The output above happens when my `skipFiles` includes both node_modules and node_internals:
```json
"skipFiles": [
	"<node_internals>/**",
	"**/node_modules/**"
],
```

I added node_modules in addition to the prefilled `<node_internals>`, but it's not coming through in my issue description.

I'm not sure what the behavior is when all files in the stack trace for the output log is skipped, and that might be what's happening here. If this is the case, I think I would expect the location tag to be hidden, but that's a separate issue, I suppose.

**Comment by connor4312** [comment]
This no longer seems to repro. We also apply skipFiles to the locations of log messages nowadays.
