### ISSUE TITLE
Support hit condition breakpoints

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#121]
https://github.com/microsoft/vscode-pwa/blob/af1be6406940501a424c15a6667631517144b668/src/adapter/debugAdapter.ts#L80

**Comment by connor4312** [comment]
It seems like we already do. I see code for it and tossing in a hit condition breakpoint on `i` in

```
for (let i = 0; i < 20; i++) {
  console.log(i);
}
```

works. Was there some scenario that was wasn't working right for you?

**Comment by roblourens** [comment]
"conditional" breakpoints are different from "hit condition" breakpoints. You can pick "hit count" when editing a breakpoint, and you can enter expressions like `>3` to pause every time after the 4th iteration.

**Comment by connor4312** [comment]
Ah, okay, thanks!

**Comment by connor4312** [comment]
Fixed in https://github.com/microsoft/vscode-js-debug/commit/8ad3517f528c6a001829a8ad75de5aed59ba0cdb
