### ISSUE TITLE
Consider to sort "lazy" variables with regular variables 

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-js-debug#1215]
When trying the new "lazy" variables feature with js-debug I noticed that the "lazy" variables appear after the `__proto` property:

![image](https://user-images.githubusercontent.com/1898161/156217028-a505bb68-a732-4ccf-96d4-23645da3b0bf.gif)

Most likely this is because "lazy" variables are really functions and js-debug puts properties and functions into different groups when sorting.

It would be nice if "lazy" variables and regular variables would be sorted into one group.

**Comment by connor4312** [comment]
This is because getters defined on classes are automatically non-enumerable, which we consider "private". However I think it's reasonable to add a special case where non-enumerable properties that are getters bypass this logic.
