### ISSUE TITLE
Cutting text on Debug experience on Blazor WASM

### ISSUE THREAD

**Issue by safacero** [microsoft/vscode-js-debug#1217]
**Describe the bug**
A customer commented on the Visual Studio Community that when on a debug session on Blazor WASM, if they hover over a json value that will be long enough, the UI will cut the json in half and show just the beginning and the end of the json content with "..." in the middle.

**To Reproduce**
Link to the Developer Community bug: https://developercommunity.visualstudio.com/t/Blazor-Wasm-debug-property-value--Loss/1669311

**Comment by connor4312** [comment]
@EricCornelson I not that familiar with the VS UI. There are different contexts in which variables can be inspected and evaluated in js-debug. Specifically, the `copy` or `clipboard` context have unlimited preview budget. Let me know if there's anything you think needs to be done on the js-debug side.

**Comment by connor4312** [comment]
Haven't heard anything, so I will close this out. Please let me know if any js-debug changes are necessary here.
