### ISSUE TITLE
Breakpoints lost on refresh

### ISSUE THREAD

**Issue by eclarke12** [microsoft/vscode-js-debug#1219]
**Describe the bug**
I am working on client-side code for a node app running in a docker container in WSL. The client code is loaded from a mapped path in my WSL `home` directory.

When I set a breakpoint in vscode it works until I refresh the browser session via the browser or the debugger controls, then the breakpoint becomes unbound.

**To Reproduce**
1. Launch Chrome debug session
2. Set breakpoint
3. Execute action to hit breakpoint
4. Breakpoint activates and pauses execution
5. Unpause debugger
6. Refresh page
7. Observe that breakpoint is now unbound

**Log File**

[vscode-debugadapter-2562bc9f.json.gz](https://github.com/microsoft/vscode-js-debug/files/8225520/vscode-debugadapter-2562bc9f.json.gz)

**VS Code Version:** 1.65.1

**Additional context**
The Firefox debugger works as expected after its wizard creates the pathmapping (which it prompts to do on every refresh).

I've tried different combinations of `pathMapping` for the Chrome debugger but I can't find the right one.

launch.json:

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "firefox",
            "request": "launch",
            "reAttach": true,
            "name": "Launch Firefox",
            "url": "http://localhost:59999/",
            "webRoot": "${workspaceFolder}",
            "pathMappings": [
                {
                    "url": "http://localhost:59999/modules",
                    "path": "vscode-remote://wsl%2Bubuntu/home/eclarke/fvtt-dev-data/Data/modules"
                },
                {
                    "url": "http://localhost:59999/modules",
                    "path": "vscode-remote://wsl%2Bubuntu/home/eclarke/fvtt-dev-data/Data/modules"
                }
            ]
        },
        {
            "type": "pwa-chrome",
            "request": "launch",
            "name": "Launch Chrome",
            "url": "http://localhost:59999",
            "pathMapping": {
                "http:///localhost:59999/modules/combat-utility-belt": "${workspaceFolder}"
            },
            "trace": true
        }
    ]
}
```

**Comment by eclarke12** [comment]
I was able to resolve this with the following launch config:
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "pwa-chrome",
            "request": "launch",
            "name": "Launch Chrome",
            "url": "http://localhost:59999",
            "webRoot": "http://localhost:59999",
            "pathMapping": {
                "/modules/combat-utility-belt/": "${workspaceFolder}"
            }
        }
    ]
}
```

**Comment by RichardTeller** [comment]
@eclarke12 Still working for you? I am having this issue and what you've described here does not help. I tried the `pwa-chrome` type and the `pathMapping` property in a similar fashion, doesn't work.

For me:
1. Launch chrome debug browser
2. I set a break point in source js in vscode, breakpoint is red and can successfully be hit. (So my source mappings must be correct...)
3. Refresh the page on the browser and my breakpoint in vscode turns hollow and doesnt get hit.
4. From here I can repeat the above steps forever, click the breakpoint to remove and again to re-add, its red again and can be hit.
5. Refresh again and the breakpoint is hollow.

Pretty frustrating. I want to be able to hit the breakpoint on page load.

My launch config:

```json
{
    "name": "Chrome",
    "type": "chrome",
    "request": "launch",
    "url": "http://localhost:53567/Home/Dashboard",
    "webRoot": "${workspaceRoot}/my_project_folder/wwwroot"
}
```

Same behavior when using edge.

**Comment by eclarke12** [comment]
> @eclarke12 Still working for you? I am having this issue and what you've described here does not help. I tried the `pwa-chrome` type and the `pathMapping` property in a similar fashion, doesn't work.
> 
> For me:
> 
> 1. Launch chrome debug browser
> 2. I set a break point in source js in vscode, breakpoint is red and can successfully be hit. (So my source mappings must be correct...)
> 3. Refresh the page on the browser and my breakpoint in vscode turns hollow and doesnt get hit.
> 4. From here I can repeat the above steps forever, click the breakpoint to remove and again to re-add, its red again and can be hit.
> 5. Refresh again and the breakpoint is hollow.
> 
> Pretty frustrating. I want to be able to hit the breakpoint on page load.
> 
> My launch config:
> 
> ```json
> {
>     "name": "Chrome",
>     "type": "chrome",
>     "request": "launch",
>     "url": "http://localhost:53567/Home/Dashboard",
>     "webRoot": "${workspaceRoot}/my_project_folder/wwwroot"
> }
> ```
> 
> Same behavior when using edge.

Still working for me. 

I would maybe try using Firefox as I had better luck natively with that.

Sorry I don't have anything else to contribute.

**Comment by crossan007** [comment]
I'm seeing this issue with Firefox 117.0b9 (64-bit) and VSCode 1.74.1

**Comment by connor4312** [comment]
This debugger only works for Chromium-based browsers, you may have meant to file this on https://github.com/firefox-devtools/vscode-firefox-debug...
