### ISSUE TITLE
javascript not running/debugging

### ISSUE THREAD

**Issue by FiliLecci** [microsoft/vscode-js-debug#1222]
I am trying to run and debug a js file, but when I press F5 at first it seems that it is running, however it doesn't show anything neither on the output and the debug terminal.
If I excecute the file from terminal with `node example.js` the code runs with no issues at all.
node version: v16.14.0
JavaScript Debugger (Nightly): v2022.3.717
 I tryied every possible solution (creating a lounch.json, reinstalling vs, node and extenctions and moving my file in different directories) but nothing worked

**Comment by connor4312** [comment]
Please collect a log file using the instructions in the issue template
