### ISSUE TITLE
spawn C:\Program Files\Google\Chrome\Application\chrome.exe ENOENT

### ISSUE THREAD

**Issue by elvince** [microsoft/vscode-js-debug#1224]
**Describe the bug**
No way to launch the browser;
spawn C:\Program Files\Google\Chrome\Application\chrome.exe ENOENT
I tried also with msedge and I have the same behavior.

**To Reproduce**
1. Create an angular with "ng new testproject"
2. Open the project in vscode
3. click on run

**Log File**
[vscode-debugadapter-658d3e69.json.gz](https://github.com/microsoft/vscode-js-debug/files/8323654/vscode-debugadapter-658d3e69.json.gz)

**VS Code Version:** 1.64.2

thanks for your help

**Comment by elvince** [comment]
Just in case, I have the same behavior in 1.65.

**Comment by connor4312** [comment]
Where is Chrome installed on your machine??

**Comment by elvince** [comment]
Any hint? anything to check?

**Comment by elvince** [comment]
@connor4312 
Anything else to look at to find the root cause?

**Comment by elvince** [comment]
I finally found that it is not working when "null" service is not started.
Null service helps to manage memory. I have no clue why it has this side effect, but in case it helps to avoid loosing hours to find the root cause.

**Comment by incutonez** [comment]
> I finally found that it is not working when "null" service is not started. Null service helps to manage memory. I have no clue why it has this side effect, but in case it helps to avoid loosing hours to find the root cause.

Hey @elvince, how exactly did you start "null" service?  I'm not sure where this is.
