### ISSUE TITLE
Debugger auto-attaching to integrated zsh terminal after auto-attach disabled

### ISSUE THREAD

**Issue by djragsdale** [microsoft/vscode-js-debug#1226]
I was attempting to debug yesterday and it was not pausing on breakpoints in untranspiled node.js code. I enabled debug auto-attach, which also was failing to actually pause on breakpoints (although debugger; commands worked). I restarted multiple times to no effect. I disabled the setting this morning and restarted VS Code. It is continuing to auto-attach the debugger. I am running a start command from the integrated terminal using zsh, not a JS Debug Terminal.

It may be unrelated but I've also been seeing problems with the Prettier plugin.

```
Debugger listening on ws://127.0.0.1:55516/c3e00113-1862-4bdb-9dfe-24e3c610c7bc
For help, see: https://nodejs.org/en/docs/inspector
Error: connect ECONNREFUSED /var/folders/5y/0kfbgjn13qj_59r212sg5nkm0000gr/T/node-cdp.6655-1.sock.deferred
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1146:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/var/folders/5y/0kfbgjn13qj_59r212sg5nkm0000gr/T/node-cdp.6655-1.sock.deferred'
}

Error activating auto attach, please report to https://aka.ms/js-dbg-issue
yarn run v1.22.17
$ ultra --filter "+@aptivconnectedservices/spellbook-ui" -r start
Debugger listening on ws://127.0.0.1:55519/8d28547d-2194-49c0-af6f-8f1e34c04684
For help, see: https://nodejs.org/en/docs/inspector
Error: connect ECONNREFUSED /var/folders/5y/0kfbgjn13qj_59r212sg5nkm0000gr/T/node-cdp.6655-1.sock.deferred
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1146:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/var/folders/5y/0kfbgjn13qj_59r212sg5nkm0000gr/T/node-cdp.6655-1.sock.deferred'
}

Error activating auto attach, please report to https://aka.ms/js-dbg-issue
```

Version: 1.65.2 (Universal)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:49.188Z (1 wk ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

**Comment by connor4312** [comment]
There should be a ⚠️ icon in the upper right side of the terminal prompting you to reload it so that the auto attach environment variables can be removed; is that not present?

**Comment by djragsdale** [comment]
> There should be a ⚠️ icon in the upper right side of the terminal prompting you to reload it so that the auto attach environment variables can be removed; is that not present?

Ah, it sets an environment variable! That explains why the issue didn't resolve even after restarting VS code or my machine. That did fix it, although it was not a very noticeable warning. The window still has the debug controls on it but I assume restarting VS code will fix that now that the auto-attach is fixed.
![image](https://user-images.githubusercontent.com/4396766/159773991-566d6042-2b66-4176-9893-7ef48317009f.png)

**Comment by connor4312** [comment]
Indeed. Restarting your machine _should_ have fixed it. Restarting just vscode may not have since now we persist terminals for some time.
