### ISSUE TITLE
Set Value does not work when value is hex displayed

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-js-debug#1231]
ref #1188

![Recording 2022-03-24 at 18 26 51](https://user-images.githubusercontent.com/8586769/160036684-674d5063-584d-42f1-8139-66b47c14ff46.gif)

**Comment by connor4312** [comment]
Thanks for the issue! This is actually 'as designed' 🙂  When you set a value, it's invoking `setExpression`. When you set a value to `bb8`, it's evaluating `bb8` as an expression and therefore looking for a variable of that name. Further, different types of things can be hex encoded, so if a UI just hands me a `setExpression` for `bb8` and somehow can say "this is hex", js-debug wouldn't know if that should be interpreted as a number, string, or something else entirely.

I think it's up to the UI implementers to, if the UI indicates to a user that they're setting a hexadecimal value, to encode that into a way that it can be set in the debug adapter.
