### ISSUE TITLE
Unable to use auto-attach, bootloader fails to run

### ISSUE THREAD

**Issue by alloy** [microsoft/vscode-js-debug#1234]
When I open a JavaScript Debug Terminal, I see the following message:

```
/var/folders/8n/3pw08znd5rldfnjn5rlyq7l80000gn/T/tmp.HPf8DZ4a/oldenv: line 2: /Users/eloy/.vscode-insiders/extensions/ms-vscode.js-debug-1.66.1/src/bootloader.bundle.js: Permission denied
```

If read the various existing issues on this topic, but none solve my issue. It is true that I can disable auto-attach to make the issue go away, but I'd obviously like to make use of the feature.

Perhaps this might be due to my shell of choice, specifically [the Fish shell](https://github.com/fish-shell/fish-shell)? That and/or the combination of usage of nvm?

----

I tried to see how this boot loader is invoked and what `oldenv` is, but this file is cleaned up immediately after invoking and I couldn't find references to it in either this repo or the vscode repo (using GH search). What I did find is that if I add the executable bit to the bootloader file, it appears as if the file is being invoked as it were an executable—this fails of course:

```
chmod +x /Users/eloy/.vscode-insiders/extensions/ms-vscode.js-debug-1.66.1/src/bootloader.bundle.js
```

```
/Users/eloy/.vscode-insiders/extensions/ms-vscode.js-debug-1.66.1/src/bootloader.bundle.js: line 1: /*!: No such file or directory
/Users/eloy/.vscode-insiders/extensions/ms-vscode.js-debug-1.66.1/src/bootloader.bundle.js: line 2: syntax error near unexpected token `)'
/Users/eloy/.vscode-insiders/extensions/ms-vscode.js-debug-1.66.1/src/bootloader.bundle.js: line 2: `()='
```

----

I'd love to debug further, but have alas come to a point where I will need some guidance in doing so. For instance, where can I find the contents of the `oldenv` script?

----

**VS Code Version:** 1.66.0-insider
**vscode-js-debug:** 1.66.1
**macOS Version:** 12.3
**Fish Shell Version:** 3.4.1

**Comment by alloy** [comment]
Unsure why, but in a different project I just opened the error message is slightly different. Namely it points to a different path (with spaces):

```
/var/folders/8n/3pw08znd5rldfnjn5rlyq7l80000gn/T/tmp.iq6rnrcc/oldenv: line 4: /Users/eloy/Library/Application Support/Code - Insiders/User/workspaceStorage/ceeb461a54e3619cd1545f206613371c/ms-vscode.js-debug/bootloader.js: Permission denied
```

**Comment by connor4312** [comment]
Thanks for the issue, and apologies for the delay.

I think _something_ in your shell is trying to execute that bootloader as a binary. Which is rather odd -- the bootloader is put in an environment variable called `NODE_OPTIONS` in the form `NODE_OPTIONS="--require /path/to/bootloader.js"`. So something is deconstructing that variable.

I tried repro'ing this by running an Ubuntu container, installing fish, and [nvm.fish](https://github.com/jorgebucaran/nvm.fish), but things worked as I would expect there.

I'm curious to see the contents of oldenv, running `cat /path/to/oldenv` would be useful.
