### ISSUE TITLE
Debugging Node.js does not work after latest update

### ISSUE THREAD

**Issue by NTTAKR** [microsoft/vscode-js-debug#1235]
Debugging node.js apps worked. 
I closed vscode
vscode shows a small window with updates
I open vscode again
Debugging does not work anymore

Error Message pops up: "Error activating auto attach, please report to https://aka.ms/js-dbg-issue
Right bottom shows "Cannot read properties of undefined (reading 'logger')

What can I do?

**Comment by connor4312** [comment]
Please try toggling Auto Attach to `Disabled` and then back on again and let me know if the problem persists.

**Comment by NTTAKR** [comment]
Already tried that.
If it is on anything that enables debugging, the error message is output and the process does not start. 
If I disable debugging the process is started normally.

**Comment by connor4312** [comment]
Can you share more info about what you're trying to debug and how you're running it? Anything I can use to help reproduce. https://gifcap.dev/ may be useful.

**Comment by NTTAKR** [comment]
Seems I have found a way it works....

There is a small triangle shown on the terminal window and in the output. 
If you mouse over the icon in the list of terminal windows it tells you that the terminal configuration wants to be changed. 
As soon as you agree to that it works again.

**Comment by NTTAKR** [comment]
Seems the problem is not yet resolved :-(

I have debug Javascript Auto Attach Filter set to smart.  
If I start the node.js app with npm start  or node index.js it shows this: 

Debugger listening on ws://127.0.0.1:65516/90e56882-eeed-4389-9779-dc374c42b9c6
For help, see: https://nodejs.org/en/docs/inspector

On the right side an error toast appears with "Cannot read properties of undefined (reading 'logger')"

The program does NOT run. 

If I set Auto Attach Filter to disabled the program works, but I have no debugging. 

Where does this error come from? 
How can I solve this?

**Comment by dinhvan195** [comment]
![images (1)](https://user-images.githubusercontent.com/54309885/176346054-235009e7-acc7-49a2-aa39-6928af57f9a1.jpg)
adas

**Comment by connor4312** [comment]
Sorry, this issue fell through the cracks. Are you still running into it in modern versions?
