### ISSUE TITLE
Debugger getting slow to compile and run after getting the latest MacOS updates

### ISSUE THREAD

**Issue by oscarchuaweiwen-fsd** [microsoft/vscode-js-debug#1236]
**Describe the bug**
When i click run and debug button and start to run debug to my project, it takes longer time to compile and also takes time to stop down the whole debug process whenever i click the stop button.

**Log File**

**VS Code Version:** 
Version: 1.66.1
Commit: 8dfae7a5cd50421d10cd99cb873990460525a898
Date: 2022-04-06T14:49:52.288Z (5 days ago)
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin arm64 21.4.0
MACOS Version: 12.3.1

**Additional context**
Below is my launch.json configuration:

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
      {
        "command": "kill-port 4000 && DEBUG=things-factory:* yarn workspace @things-factory/operato-wms run serve:dev",
        "name": "1. Debug WMS",
        "request": "launch",
        "type": "node-terminal",
        "cwd": "${workspaceFolder}"
      },
      {
        "command": "kill-port 3000 && DEBUG=things-factory:* yarn workspace @things-factory/operato-hub run serve:dev",
        "name": "2. Debug Hub",
        "request": "launch",
        "type": "node-terminal",
        "cwd": "${workspaceFolder}"
      },
      {
        "command": "kill-port 5000 && DEBUG=things-factory:* yarn workspace @things-factory/operato-mms run serve:dev",
        "name": "3. Debug MMS",
        "request": "launch",
        "type": "node-terminal",
        "cwd": "${workspaceFolder}"
      }
    ]
  }

Screenshot image:

![Screenshot 2022-04-12 at 8 36 25 AM](https://user-images.githubusercontent.com/81850353/162855252-cbd90cb4-b459-4499-a908-3e9aa24bec1e.png)

**Comment by connor4312** [comment]
Having the debugger connected will cause JS programs to run more slowly than they otherwise would. If you want to compile your code without running under the debugger, check out the [preLaunchTask](https://code.visualstudio.com/docs/editor/debugging#_launchjson-attributes) and tasks system.
