### ISSUE TITLE
Help appreciated: JS-Debug Warning "Node (Version ) outdated. We require ...

### ISSUE THREAD

**Issue by Bloodiko** [microsoft/vscode-js-debug#1239]
Hello, 

this is explicitly not stated as bug report since it may be system exclusive. 
I'll include most information anyway. 

I'm trying to run an electron based app with the VSCode launch file. 
but every time i do, i get the Warning message:

`The Node version in "{project-path-replaced}/node_modules/.bin/electron" is outdated (version ), we require at least Node 8.x. Would you like to try debugging anyway?`

when i click yes, the application launches fine, debugger as well. 
it does use weird versions. (may be normal , i am not familiar with node js that much yet. ) 
Application output says its using `Node.js 16.13.2, Chromium 100.0.4896.75, and Electron 18.0.4`, which is weird since i have 17.7.1 installed via snap (unless npm install custom installs a specific node version for the project, which i dont know , but i dont think it happens. 

So Installed is v. 17.7.1, Application runs with 16.13.2 - but in either cases there shouldnt be a warning from the extension about an outdated version. 

Interesting part is, i dont even want to debug at all. i just want to run it. 
And in my Launch.json is also only the type Launch stated, not attach (which I  assume is used to launch a debug run. ) 
Auto Attach in the Extension settings is disabled. It shouldnt attach itself. 

VSCode About: 

```
Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:49:24.808Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.4.0-107-generic snap
```

Node is installed via Snap: `node                     17.7.1                      6001   17/stable      iojs✓             classic`

running `node` also brings up the dev console with version 17.7.1 as installed. 
running `npm version` lists npm 8.1.3 and also node version 17.7.1

Oh and i'm adding the Verbose launch log, but i dont know wether it does include useful information, since the "Analyzer" seems to be missing an "upload" button for me. It does not analyze the file at all. But thats a different story. 
[vscode-debugadapter-8e616b74.json.gz](https://github.com/microsoft/vscode-js-debug/files/8513479/vscode-debugadapter-8e616b74.json.gz)

Thanks. 
Bastian

**Comment by connor4312** [comment]
Thanks for the details. Which version of Electron do you have installed, and can you also share your `launch.json`?

**Comment by Bloodiko** [comment]
Sure, 

Electron 18.0.4 (Locally installed in the project directory , not global. ) 

launch.json :

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Main Process",
            "type": "node",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron",
            "windows": {
                "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron.cmd"
            },
            "args": [
                "."
            ],
            "outputCapture": "std",
        }
    ]
}
```

The project is actually nothing special, trying to learn currently, so i'm going through the "Hello World" from electron and  ran into this. 
wanted to get this cleared up before I get into more complex stuff.

**Comment by supernovaw** [comment]
I also have this problem and it's very annoying. `node -v` says v16.14.0, as does `console.log(process.version)`.
In the warning, there is: `outdated (version )`. I assume it's printing out what it thinks the version to be and apparently the string is `version ` with a trailing space which is very weird. I was trying to figure out how to rerun my `index.js` every time I make changes, and the best I found was to press F5 to run. But because of this useless warning it is as tiresome every time to close it as it would be to fire `npm start` in terminal.
