### ISSUE TITLE
Adopt SHA-256 hashes for scriptParsed events

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#1244]
Chrome will [soon](https://chromium-review.googlesource.com/c/v8/v8/+/3229957) move their hashing from "chromehash" to SHA-256. We should use the length of the hash in `scriptParsed` events to determine which hashing algorithm to use.

**Comment by connor4312** [comment]
1. Install Chrome Canary
2. Open a workspace with a `chrome` type launch config, like https://github.com/microsoft/vscode-js-debug/tree/main/demos/web-worker, and set `"runtimeVersion": "canary"`
3. Set a breakpoint or add a `debugger;` statement in a `.js` file without a sourcemap, and keep it open
4. Debug and hit the breakpoint. Verify that the breakpoint is shown in the file you have open (not a temporary/from-memory file, which is what the debugger would open if the content verification fails)

**Comment by alexr00** [comment]
`"runtimeVersion": "canary"` didn't appear to work for me. I also didn't see any breakpoints get hit.

**Comment by connor4312** [comment]
Apologies, it's `runtimeExecutable: "canary"`. That's what I get for writing instructions from memory on a train.

Note that in the web-worker example you'll need to serve the files somehow, e.g. by running `npx server -p 5002`. Then you should hit a debugger statement when changing either of the inputs (or you can set a breakpoint wherever). Verified locally that this should work.
