### ISSUE TITLE
Make All VSCode extensions of JavaScript Debugger compatible with https://vscode.dev/ and https://github.dev/

### ISSUE THREAD

**Issue by codecycleteam** [microsoft/vscode-js-debug#1245]
**Is your feature request related to a problem? Please describe.**
Developers are not able to use these extensions with https://vscode.dev/ and https://github.dev/

**Describe the feature you'd like**
Make All VSCode extensions of JavaScript Debugger compatible with https://vscode.dev/ and https://github.dev/
@connor4312 @pavelfeldman @dgozman @roblourens @digeff @EricCornelson 
Please consider this as DX improvement and give some priority for it.
Thanks

Here is more info
https://aka.ms/vscode-web-extensions-guide
https://code.visualstudio.com/api/extension-guides/web-extensions

Screenshot of extension showing not compatible with web version.
![Screenshot 2022-04-25 11 35 07](https://user-images.githubusercontent.com/84431724/165047161-500df7e4-dc51-4fe3-b8cf-72ea2c579016.png)

![Screenshot 2022-04-25 11 35 27](https://user-images.githubusercontent.com/84431724/165047179-478ab267-e39d-4aca-8226-ea982c75a3b5.png)

**Comment by connor4312** [comment]
This is not possible to do in the forseeable future.

**Comment by codecycleteam** [comment]
@connor4312 we will be grateful to you if you can explain why it is not possible in the near future? Can't we think in this direction that how can we make this possible in the near future? and what duration timing we are defining as near future?
This quarter or next quarter of this year OR year itself? Please think on this once and let's discuss this first how this can be achieved...Awaiting your helpful response because it's not for you or me it's for all the developers who are going to be benefited from this.
Thanks a lot for everything.

**Comment by connor4312** [comment]
Debugging JavaScript with this debugger requires a [CDP connection](https://chromedevtools.github.io/devtools-protocol/). This cannot be acquired in a browser not already being run in debug mode, nor can it be required from code running on any page.

Some custom runtime could be built that would transpile JS code and make it debuggable. That is a _lot_ of work, and it would probably be easier to make a minimal "lite" JavaScript debugger extension than implementing spec-compliant CDP to a sufficient degree that js-debug could plug into it.

Another option is to compile V8 to webassembly and run code inside of that, which would get a CDP connection. This is similar what Stackblitz did in their web containers https://blog.stackblitz.com/posts/introducing-webcontainers/. Having something like web containers would be neat for vscode.dev, but that's not something we've started investigating seriously (and Stackblitz' implementation is not OSS.)

None of these options are currently on [our roadmap](https://github.com/microsoft/vscode/wiki/Roadmap), though if there was community interest in developing something like this I would be happy to help it hook into js-debug.

**Comment by codecycleteam** [comment]
@connor4312 
Thanks a lot for the really positive and supportive response. i got it.

I have already created two issues to support web containers with this extension see below links.
https://github.com/microsoft/vscode-livepreview/issues/215
https://github.com/microsoft/vscode-livepreview/issues/216
I am going to keep those two issues there and for vs code please let me know are there any open issues to support web containers in vs code for both runtime nodejs and deno? If not then should i create it in this repo https://github.com/microsoft/vscode

And also let me know by supporting web containers natively in vscode.dev this js debugger extension can run there or not?

And yes stackblitz has already open sourced their web container things see here.
https://github.com/stackblitz/webcontainer-core

Awaiting your response. Thank You.

**Comment by connor4312** [comment]
Sure, opening an issue on vscode core would be the right place.

> And yes stackblitz has already open sourced their web container things see here.

That repo contains only documentation and issue track, no code. Its FAQ states "Is this open source? Today no..."
