### ISSUE TITLE
Problem attaching to open chrome browser when using wsl2

### ISSUE THREAD

**Issue by ChrisBagge** [microsoft/vscode-js-debug#1249]
I can't attach to an open chrome browser using this debug configuration in newly created react app.
{
      "name": "Attach to Chrome",
      "port": 9222,
      "request": "attach",
      "type": "pwa-chrome",
      "webRoot": "${workspaceFolder}"
}

using the default launch config works fine.

Chrome browser has been started with --remote-debugging-port=9222 

This works fine when doing this under windows.

I had this in a project of mine, but to make sure it wasn't a quirk of the project I was able to reproduce by creating a new app in wsl2 using create-react-app.

The debugger appears to be attached but the debug console is empty and breakpoints are unbound

**VS Code Version:** 1.66.2

[vscode-debugadapter-71492637.json.gz](https://github.com/microsoft/vscode-js-debug/files/8596709/vscode-debugadapter-71492637.json.gz)

**Comment by connor4312** [comment]
Fixed in https://github.com/microsoft/vscode-js-debug-companion/commit/35fc25a533b0afd367d3608562e649ea2963233c. This'll be in the [Insiders build](https://code.visualstudio.com/insiders/) later this week (Wednesday/Thursday)
