### ISSUE TITLE
Browser breakpoints should ideally go the breakpoints view

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-js-debug#125]
We should open up some contributinos such that the PWA extension can contribute breakpoints to the breakpoints view. Having a new view is a waste of space imho.

Until we have this, can you change your view to only be shown when debugUx is 'default' same as the breakpoints view does [here](https://github.com/Microsoft/vscode/blob/c5f9f701fcacc10c61382a3f47e81fd5ad4b0d02/src/vs/workbench/contrib/debug/browser/debug.contribution.ts#L113)
The name of the context is `debugUx` so you need to check if debugUx == 'default'

**Comment by connor4312** [comment]
Being able to contribute something like this should be cool...

![image](https://user-images.githubusercontent.com/2230985/69978831-f5aa5780-14e1-11ea-9db6-45f9091be39d.png)

**Comment by isidorn** [comment]
We will probably not have an inline + Add DOM Breakpoint, since that breaks the pattern which we use in other areas (for example Watch and Function breakpoints).
Idealy it would be a context menu action, or a BREAKPOINTS title area action.

fyi @weinand

**Comment by connor4312** [comment]
Yea, that makes more sense 🙂  A title area "+" that opens the quickpick would work well.
