### ISSUE TITLE
Service Worker stuck on "trying to install"

### ISSUE THREAD

**Issue by Twiggeh** [microsoft/vscode-js-debug#1252]
**Describe the bug**
When running Chrome from VSC (for the wonderful breakpoints) my Service Worker doesn't "work". Under normal Chrome / Firefox (latest) the SW is working as intended. 

Under the VSC-Chrome it doesn't install (?) but is instead stuck on trying to install
![image](https://user-images.githubusercontent.com/23149166/166695123-411e85da-20d7-4d65-9c66-89696fe22b97.png)

It is also visible in the Call Stack
![image](https://user-images.githubusercontent.com/23149166/166695276-a7228c81-cbdd-4738-b939-1d6d105f19fa.png)

Left is the real Chrome instance, on the right is the VSC-Chrome instance (notice under size it says ServiceWorker on the left)

![image](https://user-images.githubusercontent.com/23149166/166694644-5725842c-0e31-4d91-a26e-d8bce00eed6a.png)

**To Reproduce**
1. git clone https://github.com/Twiggeh/jsdebugreport
2. Follow Instructions in readme

**Log File**
[vscode-debugadapter-99ed8456.json.gz](https://github.com/microsoft/vscode-js-debug/files/8621036/vscode-debugadapter-99ed8456.json.gz)

**VS Code Version:** 1.60.1

**Additional context**
So running chrome with --remote-debugging-port=9222 and attaching to it works, but the sw doesn't show up in the call stack! Just launch doesn't work 🤔

**Comment by connor4312** [comment]
You're on a pretty old version of VS Code. I recommend updating, as this has been fixed in more recent versions.

Duplicates https://github.com/microsoft/vscode/issues/138790 (tracked in https://bugs.chromium.org/p/chromium/issues/detail?id=1281013)
