### ISSUE TITLE
Support source map files with sections ('indexed maps')

### ISSUE THREAD

**Issue by ashgti** [microsoft/vscode-js-debug#1260]
**Is your feature request related to a problem? Please describe.**

Using a indexed source map like the kind described in https://github.com/mozilla/source-map/blob/7a263408de1b60e60b6220ca3e36d9b3e4aa047d/lib/source-map-consumer.js#L673-L722 or those produced by the closure-compiler when producing bundled output the JS debugger fails to parse the sourcemap.

https://sourcemaps.info/spec.html#h.535es3xeprgt is the spec for indexed bundles.

When you try to use one of these, this assert will be tripped up: https://github.com/microsoft/vscode-js-debug/blob/main/src/common/sourceMaps/sourceMapFactory.ts#L81 due to the not checking for sections data.

**Describe the feature you'd like**

These types of source maps should be supported.

**Comment by connor4312** [comment]
I'm actually not sure what tools produce indexed sourcemaps. @ashgti are you able to help verify this works or provide a real-world use case we can use for verification?

**Comment by ashgti** [comment]
This is working for me, the [closure-compiler](https://github.com/google/closure-compiler) will generate these kinds of source-maps if you run it in bundle mode (where it just merges files together).
