### ISSUE TITLE
optimization

### ISSUE THREAD

**Issue by HamzaButt98** [microsoft/vscode-js-debug#1262]
Issue Type: <b>Feature Request</b>

how to enable optimiztion development on terminal

Extension version: 2022.5.617
VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:06:02.889Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by connor4312** [comment]
I'm unclear on what you're asking for, can you provide more information?
