### ISSUE TITLE
Unbound Breakpoint Prevents Debugging

### ISSUE THREAD

**Issue by arimourao** [microsoft/vscode-js-debug#1266]
I have already configured in the past and it was quite straight forward to configure the debug for a node app inside a local docker container. But now I can't make it work. I Already researched a lot. The breakpoint always appears as "unbound" and it is not hit.

My launch.json

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "attach",
      "name": "Debug: Node",
      "remoteRoot": "/home/node/app",
      "localRoot": "${workspaceFolder}",
      "port": 9229,
      "restart": true,
      "address": "0.0.0.0",
      "skipFiles": ["<node_internals>/**"],
      "sourceMaps": true,
      "trace": true,
      "resolveSourceMapLocations": [
        "${workspaceFolder}/**",
        "!**/node_modules/**"
      ],
    }
  ]
}

```
My dockerfile

```
FROM node:16.14.2-buster

COPY package*.json ./
COPY tsconfig.build.json ./
COPY tsconfig.json ./

RUN npm install

ENV PATH /home/node/app/node_modules/.bin:$PATH

COPY . /home/node/app
EXPOSE 8080
EXPOSE 9229

CMD ["npm", "run", "debug"]
```

VSCODE Version

Version: 1.67.0
Commit: 57fd6d0195bb9b9d1b49f6da5db789060795de47
Date: 2022-05-04T12:08:42.978Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.13.0-40-generic snap

**Comment by connor4312** [comment]
Please collect logs using the instructions in the template. 

You may also try the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) to see if your issue is already fixed there.

**Comment by arimourao** [comment]
[vscode-debugadapter-fc77a4bf.json.gz](https://github.com/microsoft/vscode-js-debug/files/8665005/vscode-debugadapter-fc77a4bf.json.gz)

**Comment by arimourao** [comment]
I'm also running the container with this command:

`$ docker run -p 8080:8080 -p 9229:9229 -v ~/Documents/projects/pir-node:/home/node/app pir`

Already double-checked the paths, everything seems fine.

It is a nestjs app and in my package.json I have:

`"debug": "nest start --debug 0.0.0.0:9229 --watch && set NODE_ENV=development",`

any help would be hugely appreciated

**Comment by connor4312** [comment]
Your sourcemaps contains paths like `file:///dist/app.controller.js` Your remoteRoot appears to be the root of the filesystem `/`.

**Comment by arimourao** [comment]
any recommendations?!

**Comment by connor4312** [comment]
Setting your `remoteRoot` to `/` in the launch.json would be a good start 🙂

**Comment by arimourao** [comment]
Tried this but to no avail... also tried to set a WORKDIR in my dockerfile with the path that my app is inside the docker but didn't help either. 
Any other idea would be greatly appreciated.

**Comment by arimourao** [comment]
well, forget about that, I just set the workdir and the remoteRoot the way it was and it just worked! Thank you very much sir!
