### ISSUE TITLE
Error when trying to debug an Ionic App on my MacOS

### ISSUE THREAD

**Issue by vnetonline** [microsoft/vscode-js-debug#1267]
OS Version : MacOS 12.3.1 Monterey
VS Code Version: 1.67.1 (Universal)
JavaScript Debugger (Nightly): v2022.5.1017

I am getting the following error when I am trying to debug a Ionic App try and debug and my breakpoints show that they are unbound breakpoints

**launch.json**

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Chrome",
            "request": "launch",
            "type": "chrome",
            "url": "http://localhost:8100",
            "webRoot": "${workspaceFolder}"
        },
    ]
}
``` 

![Screen Shot 2022-05-13 at 12 41 39 pm](https://user-images.githubusercontent.com/15242923/168200877-f43e5773-df4d-4a18-b537-4929f6e6440c.png)

**Comment by vnetonline** [comment]
When I change the url
In launch.json to 127.0.0.1:8100 the source maps resolve

Can someone please explain why this works and doesn't use localhost??

**Comment by timvahlbrock** [comment]
I'm not sure if that is causing the issues, but shouldn't your `webRoot` be set to `${workspaceFolder}/src`?

**Comment by connor4312** [comment]
Can you collect trace logs using the instructions in the issue template?
