### ISSUE TITLE
Could not read source map while debug React Native app

### ISSUE THREAD

**Issue by JiglioNero** [microsoft/vscode-js-debug#1268]
**Describe the bug**
Hello, I am a member of the `React Native Tools` extension development team for VSCode. After updating the `vscode-js-debug` extension to version `1.67`, which is used by our debugging extension, the following error began to appear:
 
![image](https://user-images.githubusercontent.com/43934531/168297895-077ee052-0c24-4d23-a529-3540a82176b8.png)

This error occurs on any change in code during debugging process.

**To Reproduce**

1. Install `React Native Tools` extension in your VSCode
2. Configure your environment for React Native development as shown in [documentation](https://reactnative.dev/docs/environment-setup)
3. Initialize new React Native project via command `react-native init rnProject`
4. Open project folder via VSCode and run "Debug Android" debug config
```json
{
            "name": "Debug Android",
            "cwd": "${workspaceFolder}",
            "type": "reactnative",
            "request": "launch",
            "platform": "android",
}
```
5. After the application starts, switch to debug mode via devMenu
6. After the extension is attached to the application, change any part of the application code

**Log File**

[vscode-debugadapter-ad81bbfe.json.gz](https://github.com/microsoft/vscode-js-debug/files/8688471/vscode-debugadapter-ad81bbfe.json.gz)

**VS Code Version:** 1.67.1

**Comment by JiglioNero** [comment]
No, its reproduce on today's nightly build too

**Comment by cesarak** [comment]
Same here, but I'm facing this issue trying to "Attach Android application" too

Here is my config
`    {
      "name": "Attach Android application",
      "request": "attach",
      "type": "reactnativedirect",
      "cwd": "${workspaceFolder}"
    },`

**Comment by connor4312** [comment]
@JiglioNero hm, interesting. Could you take a trace log from the latest nightly build so I can diagnose further?

**Comment by JiglioNero** [comment]
Yes, sure - [vscode-debugadapter-b2b2c743.json.gz](https://github.com/microsoft/vscode-js-debug/files/8715679/vscode-debugadapter-b2b2c743.json.gz)

**Comment by connor4312** [comment]
It looks like you're still using the stable build. Make sure that you did steps 1 and 2 in the instructions to switch to the nightly build: https://github.com/microsoft/vscode-js-debug#nightly-extension

**Comment by JiglioNero** [comment]
This [logs](https://github.com/microsoft/vscode-js-debug/files/8729007/vscode-debugadapter-adf2e9ee.json.gz) for `vscode-js-debug` nightly version `v2022.5.1817`

**Comment by connor4312** [comment]
Hm, the adapter version in that log is still `1.67.2`.

**Comment by JiglioNero** [comment]
Hi, this was my mistake, sorry. This error not reproducing now with the nightly build

**Comment by connor4312** [comment]
Thanks for confirming. This duplicates https://github.com/microsoft/vscode/issues/148864
