### ISSUE TITLE
Consider a "wizard" for creating the initial chrome launch config

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#1270]
- Have no launch.json
- Click Run and Debug
- Pick "Chrome"
- You get a launch.json with a prefilled chrome launch config

Discussed a bit in the context of https://github.com/microsoft/vscode/issues/146338. It might be a better experience to ask the user some questions to get their server URL and a couple other details that could help us generate a more useful launch config to start with.

**Comment by connor4312** [comment]
Probably would implement this as https://github.com/microsoft/vscode-js-debug/issues/1214

**Comment by connor4312** [comment]
Duplicating into https://github.com/microsoft/vscode-js-debug/issues/1214
