### ISSUE TITLE
Incorrect timeDelta handling for start and end samples

### ISSUE THREAD

**Issue by sereilly** [microsoft/vscode-js-debug#1272]
**Describe the bug**
Given the following samples and timeDeltas, the tree view displays 600ms self time and the flame graph view shows 200ms self time.
```
"samples": [0, 0, 0],
  "timeDeltas": [200000, 400000, 500000],
  "startTime": 1652739599999000,
  "endTime": 1652739601099000,
```

Expected: Both the tree view and flame graph display the combined sample time of 1.1s.

**To Reproduce**
Extract [repro.zip](https://github.com/microsoft/vscode-js-debug/files/8703932/repro.zip) and open 12345.cpuprofile in vscode

**VS Code Version:** 1.67.1

**Additional context**

**Comment by sbatten** [comment]
I'm not sure if this is actually wrong, but I don't see 1.1s, I see 900ms for both.
<img width="482" alt="image" src="https://user-images.githubusercontent.com/6561887/171751309-fa5e9a14-3a90-450a-8eda-ed2f84554fd1.png">
<img width="449" alt="image" src="https://user-images.githubusercontent.com/6561887/171751327-86914c2b-7723-4da2-9791-e51cf0febe9b.png">

**Comment by connor4312** [comment]
That's correct. From what I sent Sean earlier:

> `timeDeltas[0]​` is be the duration before the first sample. Then `timeDeltas[i]`​ is the duration between samples `i`​ and `i - 1​`. So in this case there should be a 200ms gap before the start of the first sample, and then it should be in the `<anonymous>`​ function for a total of 900ms across the two functions.
