### ISSUE TITLE
Error activating auto attach, please report to https://aka.ms/js-dbg-issue

### ISSUE THREAD

**Issue by VashJuan** [microsoft/vscode-js-debug#1273]
**Describe the bug**
Restarted VS Code to get the latest, and got the following log message as soon as the terminal window appeared. My workflow is uninterrupted, but you all asked for it to be reported.

I've tried twice more, so far & get a Debugger Attached message: with & without the trace enabled.

Hmmm. Love these random bugs... 

**Feel free to close this issue!**

**To Reproduce**
start VSCode, look at the terminal window. Enter "npm list".
This didn't happen, to my recollection, yesterday.

**Log File**
PowerShell 7.2.3
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Projects\rangertrak> npm list
Debugger listening on ws://127.0.0.1:63646/fe2be9ee-353e-4d99-a13c-2060fe1c3ce8
For help, see: https://nodejs.org/en/docs/inspector
timeout

Error activating auto attach, please report to https://aka.ms/js-dbg-issue

**VS Code Version:** Latest insider

**Additional context**

**Comment by connor4312** [comment]
Can you run the "Toggle Developer Tools" command and report any issues that appear in your Console tab?
