### ISSUE TITLE
Heads-up: `Debugger#restartFrame` now working again

### ISSUE THREAD

**Issue by szuend** [microsoft/vscode-js-debug#1283]
We recently re-implemented the `Debugger#restartFrame` CDP method that allows restarting of functions while paused ([CL](https://crrev.com/c/3644624)).

This is just a heads-up in case folks are interested in bringing this feature also to JS debugging in VS Code.

The new semantics are a bit different though, in that V8 won't always allow functions to be restarted. We communicate this info in the `Debugger.paused` event where each call frame now has a `canBeRestarted` flag. This info is accurate as long as the user doesn't mess with stack between pausing and requesting a frame restart. Calling the `restartFrame` CDP method also continues execution immediately, but will pause automatically at the beginning of the restarted function.

**Comment by connor4312** [comment]
Thank you for the heads up! This will make @hediet happy. I think we still have it enabled in the debugger, but will need tweaks to adjust when it can be shown based on the new property.

**Comment by hediet** [comment]
Thank you! This is great news!

**Comment by connor4312** [comment]
Calling `Debugger.restartFrame` in Chrome Canary, I get an error:

```
{
  "code": -32000,
  "message": "Restarting frame without 'mode' not supported"
}
```

This happens at any line in the following function:

```
setTimeout(() => {
  let i = 0;
  i++;
  i++;
  i++;
  i++;
  i++;
})
```

I don't see any relevant properties or methods called `mode` in the currently published CDP. I assume this is something the Chromium team is still working on. I do see the new property, however, and will PR in support for it 🙂

**Comment by szuend** [comment]
We added a new `mode` parameter to the `Debugger.restartFrame` to stay back-wards compatible. Otherwise the behavior of the CDP command would have changed from one version to another.

It seems that the documentation hasn't updated yet (I'll look into that), but in the raw PDL file you can see the new `mode` parameter: https://source.chromium.org/chromium/chromium/src/+/main:v8/include/js_protocol.pdl;l=293-297

**Comment by connor4312** [comment]
Hm, thanks. I will hack it in for now and watch the issue that you opened on the devtools-protocol.

**Comment by connor4312** [comment]
Verifier: use Chrome Canary (by installing it, and then set `runtimeExecutable: "canary"` in your launch.json) and check that the "restart frame" action works (a hover action on the call stack view)

**Comment by szuend** [comment]
It's a bit technical: Essentially we can't restart across C++ frames (because destructors need to run when dropping C++ frames), which means restarting across Web APIs or Node APIs is now prohibited.

**Comment by hediet** [comment]
@szuend thanks for clarifying! What do you mean with "across Web/Node APIs" though?
When C++ land calls into JS? What would be an example?

**Comment by szuend** [comment]
Let's say you have a function `foo` and a function `myCallback` in your script and `foo` calls some Web/Node API:

```
function foo() {
  //...
  someNodeAPI(function myCallback() {
    debugger;
  });
```

When stopped in `myCallback` you won't be able to restart `foo`.

As a side note, this is different to e.g. async/generator functions, which can't be restarted for other reasons.
