### ISSUE TITLE
Debugger crashes with "autoAttachChildProcesses": true set when debugging the extension host and a debugged child process exits quickly

### ISSUE THREAD

**Issue by segevfiner** [microsoft/vscode-js-debug#1289]
**Describe the bug**
The debugger crashes with `"autoAttachChildProcesses": true` set when debugging the extension host and a debugged child process exits quickly.

**To Reproduce**
1. Clone https://github.com/segevfiner/vscode-jest-extension-debug-crash.
2. `npm install` in both the repos root directory and jest subdirectory.
3. Open in VS Code.
4. Run the "Run extension" debug configuration
5. Open the jest subdirectory in the extension development host.
6. The extension development host exits/crashes a short time after the jest extension activates.

**Log File**

[vscode-debugadapter-724d8689.json.gz](https://github.com/microsoft/vscode-js-debug/files/8823393/vscode-debugadapter-724d8689.json.gz)

**VS Code Version:** 1.67.2

**Additional context**
See https://github.com/jest-community/vscode-jest/issues/873

**Comment by connor4312** [comment]
Good find, this is actually reproducable when any debugged child process ends, for example adding this to the "hello world" sample will cause a crash too

```js
cp.spawn('node', ['-e', 'setTimeout(() => { console.log(42) }, 1000)']);
```
