### ISSUE TITLE
Attaching is intermittently extremely slow

### ISSUE THREAD

**Issue by andrewbranch** [microsoft/vscode-js-debug#1299]
I apologize that I don’t yet have any useful repro information for this—I’m opening it primarily to see if it’s something you’re already familiar with, and if not, how I can collect diagnostic info next time it happens.

Every so often—say, 1 in 10 debug sessions, which amounts to about once a week for me—the debugger will take minutes instead of seconds to attach. It can be fixed simply by restarting VS Code. This started happening, or at least started happening more frequently, in the last ~2 months. I run VS Code Insiders on macOS, but one teammate told me the same thing just happened to her on Windows and VS Code stable, and another told me he often sees the opposite pattern—attaching will sometimes take 5 minutes in a fresh VS Code session, but will go faster afterwards in that same session.

**Comment by connor4312** [comment]
Interesting, can you share the launch.json you're using, if any?

Do you experience this in all Node.js projects, or have you only observed it in a specific repo?

**Comment by andrewbranch** [comment]
I don’t recall if I’ve seen this happen outside of the TypeScript repo, because that’s the only codebase I debug in a typical week. @weswigham might be able to say more about his experience.  https://github.com/microsoft/TypeScript/blob/2f7ecc699186814c913e0dad577978348de6d590/.vscode/launch.template.json#L21-L51

**Comment by connor4312** [comment]
I think this can be merged into https://github.com/microsoft/vscode-js-debug/issues/1149
