### ISSUE TITLE
Detect available browsers when debugging web apps

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode-js-debug#1304]
**Is your feature request related to a problem? Please describe.**
Testing [vscode#151665](https://github.com/microsoft/vscode/pull/151665) and ran into an issue where Chrome was presented as an option to debug in the browser, but I didn't actually have Chrome installed. I ended up getting an error since I forgot I didn't have Chrome on this computer.

**Describe the feature you'd like**
It would be great to detect browser installations and to filter this quick pick's options accordingly.

## Demo

https://user-images.githubusercontent.com/25163139/173116256-88b3cf54-9b0b-4194-a101-6de1ff6957ad.mp4

cc @roblourens

**Comment by connor4312** [comment]
The debuggers in the selection you see there are provided statically, before activating extensions (all debuggers you have installed can be listed there; this could be very intense.) We don't have an opportunity to do browser detection at that point.
