### ISSUE TITLE
Mapping of breakpoints drops pathname when it's part of the applicationurl

### ISSUE THREAD

**Issue by joj** [microsoft/vscode-js-debug#1308]
**Describe the bug**
When the application root includes a pathname (which is very common for IIS), breakpoint resolution drops the pathname, resulting in the breakpoints not being resolved. For instance, in the attached logs the application root is "https://localhost/webapplication10", and the breakpoint is in "https://localhost/webapplication10/js/functions.js", but when resolving the path gets truncated to "https://localhost/js/functions.js".

**To Reproduce**
This is simplish to reproduce in VS, I'm not sure if it will be so simple to reproduce in vscode. 
VS steps are:

- Create ASP.Net (Model-View-Controller)
- Open wwwroot/js, right click on the folder
- Add New Item (javascript file) named "functions.js"
- Added this code:

```
function display()
{
    alert("message");
}

```

- Set a breakpoint on line 3 (where the alert is)
- Open Views\Home, double click on Index.cshtml
- Add the following script blocks at the end of the file:
- <script src="~/js/functions.js"></script>

```
<script>
display();
</script>

```    

- Run

At this point, the breakpoint is hit. The root is "http://localhost:xxxx/"

- Open the dropdown in the start button
- Click on "WebApplication Debug Properties"
- Click the first button (Create a New Profile)
- In launchsettings.json (Properties), IIS should look like this:

 ```
   "IIS": {
      "commandName": "IIS",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
(...)
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iis": {
      "applicationUrl": "https://localhost/WebApplication10",
      "sslPort": 0
    },

```

- Run

At this point, the breakpoint will not be hit. The root is "https://localhost/appname"

**Log File**
[visualstudio-js-debugger-pathname.txt](https://github.com/microsoft/vscode-js-debug/files/8910267/visualstudio-js-debugger-pathname.txt)

**Additional Context**
This issue was first reported here: https://developercommunity.visualstudio.com/t/After-the-1720-update-Visual-Studio-2/10054778

**Comment by roblourens** [comment]
> Create ASP.Net (Model-View-Controller)

Sorry, what do I need to create?

**Comment by connor4312** [comment]
@joj can you verify whether this was fixed for you with these changes?
