### ISSUE TITLE
Auto-evaluate properties feature in VS works for Blazor WebAssembly debugging

### ISSUE THREAD

**Issue by thaystg** [microsoft/vscode-js-debug#1315]
https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1430485

VS has an option which, when checked, will cause the debugger UI to automatically evaluate locals/callstack fields that are classified as properties. 

![image](https://user-images.githubusercontent.com/4503299/175611393-73313156-3507-46f9-8764-0a6b95ed6bde.png)

This feature currently works for Blazor Server debugging, but not for WebAssembly, since WebAssembly goes through the [vscode-js-debug adapter](https://github.com/microsoft/vscode-js-debug). We have an ask from the Blazor team to light this feature up for Blazor WebAssembly.

![image](https://user-images.githubusercontent.com/4503299/175611412-652d557b-7577-4a79-af49-cdcb78da572e.png)

How it looks for regular C# debugging:
Enabled:
![image](https://user-images.githubusercontent.com/4503299/175611426-4271e79c-11f7-4eba-b2d4-1446786acfe8.png)

Disabled:
![image](https://user-images.githubusercontent.com/4503299/175611444-98eefb1c-d5fc-4897-8549-8551a28c7986.png)

How it currently looks for JS/Blazor WebAssembly:
![image](https://user-images.githubusercontent.com/4503299/175611486-6af914be-1eea-40a9-b83c-0d3804ce44ee.png)

Getting Started / Helpful Info:
The VSCodeDebugAdapterHost (PineZorro) defines a set of custom extensions to the debug adapter protocol, one of which is an extension to both the evaluate, variables, and stackTrace requests, which adds an EvaluationOptions item that includes settings for auto-evaluation.

See the schema for the custom DAP extensions here: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/VSCodeDebugAdapterHost?path=/src/product/VsCodeDebugProtocol/PrivateSchemaExtensions/EvaluationOptions.json&_a=contents&version=GBmain

What I'm planning:

- Adding the supportsEvaluationOptions capability to the capabilities list returned on initialize
- Implementing support in the evaluate, variables, and stackTrace requests to automatically evaluate properties if the setting is enabled in the EvaluationOptions passed in the request

**Comment by connor4312** [comment]
We [added support for lazy variables in DAP](https://github.com/microsoft/debug-adapter-protocol/issues/246) and also in js-debug, and in VS code they can be expanded by default using the `debug.autoExpandLazyVariables` setting. I don't think any changes/non-standard additions to DAP are necessary here.

**Comment by thaystg** [comment]
It doesn't matter if I check or not this check box on VS:
![image](https://user-images.githubusercontent.com/4503299/175614773-917f7aa1-d794-447b-9136-bebc216a868c.png)

Vscode-js-debug always sends the request to dap like this:
`{"tag":"dap.send","timestamp":1656092688436,"metadata":{"connectionId":1,"message":{"seq":118,"type":"response","request_seq":39,"command":"variables","success":true,"body":{"variables":[{"name":"_month","value":"7","evaluateName":"aaa._month","type":"number","variablesReference":0,"presentationHint":{"visibility":"private"}},{"name":"Month","value":"ƒ Month ()","evaluateName":"aaa.Month","type":"function","variablesReference":20,"presentationHint":{"visibility":"private","lazy":true}}]}}},"level":0}`

I think we still need a way to get the information from DAP to set it correctly setting on VS, am I wrong?

**Comment by thaystg** [comment]
In my opinion we need to add in vscod-js-debug capabilites: 
supportsEvaluationOptions

Then we can receive this information from DAP:
`{"tag":"dap.receive","timestamp":1655912058693,"metadata":{"connectionId":1,"message":{"type":"request","command":"variables","arguments":{"variablesReference":3,"format":{"hex":true},"timeout":1000,"evaluationOptions":{"noFuncEval":true,"noToString":true,"forceRealFuncEval":true}},"seq":25}},"level":0}
`
And noFuncEval=true means that we shouldn't auto-evaluate properties. And the default value for noFuncEval=false, so we should auto-evaluate properties.

**Comment by connor4312** [comment]
The `debug.autoExpandLazyVariables` setting controls behavior of the UI, not the debug adapter. When turned on, VS Code automatically sends nested `variables` requests to properties that are presented with `lazy: true`. Can VS do the same thing when that box is checked?

**Comment by thaystg** [comment]
@isadorasophia Can you answer this one?

**Comment by isadorasophia** [comment]
Hi Connor! Are you proposing that VS sends out a "lazy" property for nested variable requests? Would that only be send if that debugger UI option is turned off? I believe that would lead to a slightly different behavior from `noFuncEval` capability that Thays is implementing.

+@andrewcrawley who can also help us out with this 😁

**Comment by thaystg** [comment]
@lewing @ilonatommy @radical

**Comment by connor4312** [comment]
js-debug(/any debug adapter that implements it) will send `presentation: { lazy: true }` on variables that should be evaluated in the same way. This is always sent regardless of any option or setting.

If you want to "auto expand" these, the VS can immediately follow up with a `variables` request on the lazy variable without requiring user interaction.

**Comment by thaystg** [comment]
OK, makes sense to me.

**Comment by andrewcrawley** [comment]
@connor4312 VS Code's idea of a `lazy` virtual variable provides exactly one bit of information: "You may not want to evaluate this by default".  It's a great solution for VS Code's simpler debugging experience, but it's not expressive enough for VS.  For instance, VS needs be to able to express "Evaluate this, but don't make any function calls" and "Evaluate this, but don't do anything that would have side effects" as separate concepts.  Further, VS has no way to tell what might happen when expanding a `lazy` variable, whether a given variable represents a field or a property (as in the case of the specific option in question here), etc, so we have no way to map our evaluation options onto a decision whether or not to expand - only the debug adapter has the necessary knowledge.  The effect would be the same as the current situation: the user sees their settings being ignored.

You can support both VS and VS Code scenarios by looking at the `clientId` passed in the `initialize` request, sending `lazy` variables to VS Code and handling `evaluationOptions` from VS.  I believe there are several places in vscode-js-debug that already do this.

For reference, here's the complete list of flags we support via our `evaluationOptions` extension, which we added back in 2020 to support these scenarios in our C# debugger:
```json
        "treatAsStatement": {
          "type": "boolean",
          "description": "Evaluate the expression as a statement."
        },
        "allowImplicitVars": {
          "type": "boolean",
          "description": "Allow variables to be declared as part of the expression."
        },
        "noSideEffects": {
          "type": "boolean",
          "description": "Evaluate without side effects."
        },
        "noFuncEval": {
          "type": "boolean",
          "description": "Exclude funceval during evaluation."
        },
        "noToString": {
          "type": "boolean",
          "description": "Exclude calling `ToString` during evaluation."
        },
        "forceEvaluationNow": {
          "type": "boolean",
          "description": "Evaluation should take place immediately if possible."
        },
        "forceRealFuncEval": {
          "type": "boolean",
          "description": "Exclude interpretation from evaluation methods."
        },
        "runAllThreads": {
          "type": "boolean",
          "description": "Allow all threads to run during the evaluation."
        },
        "rawStructures": {
          "type": "boolean",
          "description": "The 'raw' view of objects and structions should be shown - visualization improvements should be disabled."
        },
        "filterToFavorites": {
          "type": "boolean",
          "description": "Variables responses containing favorites should be filtered to only those items"
        },
        "simpleDisplayString": {
          "type": "boolean",
          "description": "Auto generated display strings for variables with favorites should not include field names."
        }
```

**Comment by connor4312** [comment]
I see. Via CDP, how would you like such properties to get to the Blazor debugger?

**Comment by connor4312** [comment]
Sure, perhaps `variables` could take some additional custom `jsDebugRuntimeProperties` option. Though right now we actually call `getProperties` twice for two different sets of properties, not sure how you want to integrate it,.

**Comment by connor4312** [comment]
I believe these were addressed in @thaystg's PR
