### ISSUE TITLE
Allow the currently paused location in step in targets

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#1322]
Refs https://github.com/microsoft/vscode/issues/149871#issuecomment-1170250136

**Comment by connor4312** [comment]
This is actually not really possible with V8 right now 😞

**Comment by hediet** [comment]
Oh no... Going to the outer-most function call is a very important use-case for this feature...

**Comment by connor4312** [comment]
Currently the way step in targets works is by setting a breakpoint immediately before the desired function call, hitting it, and stepping in.

However, take a line like `foo(bar())` that has a breakpoint on that line. The debugger is paused at `*foo(bar())` because that's where the breakpoint is. So doing our normal logic, we'd want to set a breakpoint before `foo()`, continue, then wait for it to be hit... except there is a breakpoint there already, so we can't do that, and even removing and re-setting the breakpoint, it's not hit again.

So this isn't really possible with the current implementation of step in targets.
