### ISSUE TITLE
Add argument for specifying host for `debugServerMain.ts`, `vsDebugServer.ts`, `flatSessionLauncher.ts`

### ISSUE THREAD

**Issue by gfszr** [microsoft/vscode-js-debug#1328]
**Is your feature request related to a problem? Please describe.**
All debug adapter frontends do not offer an argument to specify the host to listen on. This causes several confusions, for instance: `vsDebugServer` listens on the root session on external IP, but child sessions listen to `127.0.0.1` hardcoded: https://github.com/microsoft/vscode-js-debug/blob/98af79b65794d81771fb62443dac240b0b03ef37/src/common/findOpenPort.ts#L99-L105

**Describe the feature you'd like**
Add an optional host argument to all debug adapter executables, which specifies a hostname all created TCP servers would listen on.

**Comment by weinand** [comment]
Verified by code inspection
