### ISSUE TITLE
pwa-debug shows no error when trying to debug node.js < 8.0

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-js-debug#134]
testing microsoft/vscode#85984:

- install version of node.js < 8.0 (e.g. by using nvm or nvs)
- make sure that `node --version` shows the correct version number
- create a  simple program hello.js:
  ```js
  console.log("hello world");
  debugger;
  ```
- create and run a launch config with a `"stopOnEntry": true` attribute.

Observe:
program does not stop anywhere and just finishes:

![2019-12-03_14-19-25](https://user-images.githubusercontent.com/1898161/70055236-7304c380-15d9-11ea-86d8-b434cc98fa6d.png)

In node-debug we were falling back to "node-debug (legacy)" for node.js versions < 8.0.

With pwa-debug we should either fall back too or show a error/warning explaining why debugging is failing.

**Comment by roblourens** [comment]
Also see https://github.com/microsoft/vscode-pwa/issues/133
