### ISSUE TITLE
Issue with debugging nodejs with node8 after upgrading to vscode 1.69.x

### ISSUE THREAD

**Issue by lewjc** [microsoft/vscode-js-debug#1340]
**Describe the bug**
When attempting to debug a nodejs application running on node 8.15.0 through pm2, the debugger hangs once attached and a breakpoint is set. When detaching the request continues as normal. This does not occur if no breakpoints are set and we are attached. 

**To Reproduce**
1. Start a pm2 loopback/express nodejs application with node interpreter version 8.15.0 with an inspect port 
```
{
...Other Pm2 Config
"node_args": "inspect=9229"
}
```
2. Attach using the attach launch type like below
```
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to API",
            "port": 9229,
            "trace": true,
            "skipFiles": [
                "node_modules/",
                "<node_internals>/"
            ]
        },
```
3. Set a breakpoint and make a request
4. The breakpoint will never be hit
5. The request will hang until the disconnecting from the debugger.

**Log File**

Below is a sanitised subset of logs that seem to have some relevance on the issue, I will send across the full logs if necessary as they cannot be posted publicly. 

[sanitised-logs-for-debugging-issue.json.gz](https://github.com/microsoft/vscode-js-debug/files/9169063/sanitised-logs-for-debugging-issue.json.gz)

**VS Code Version:**  1.69.2

**Additional context**
I have tried using node 10 and it works fine, but only when switching back to a version of node 8.x it fails again. I appreciate node 8 is EOL and has been for sometime, but unfortunately we are not yet in a position to upgrade to the LTS version due to legacy support constraints.   

The error log I noted in the file above was 

```
{"tag":"runtime.exception","timestamp":1658502452451,"message":"Unhandled error in debug adapter","metadata":{"message":"Cannot read properties of undefined (reading 'endsWith')","stack":"TypeError: Cannot read properties of undefined (reading 'endsWith')\n\tat new y (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:921511)\n\tat Function.fromDebugger (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:921731)\n\tat Function.fromDebugger (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:919218)\n\tat j._createPausedDetails (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:950172)\n\tat j._onPaused (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:946337)\n\tat processTicksAndRejections (node:internal/process/task_queues:96:5)"},"level":3}

```

which seems to relate to https://github.com/microsoft/vscode-js-debug/blob/812a259f1f09a5c6527f0940f81e5efb6f1eb0da/src/adapter/stackTrace.ts#L275
if I read the stack trace right, but I may be wrong I just did a little digging to see if there was anything obvious wrong at first glance.  

Thank you in advance!

**Comment by connor4312** [comment]
THis duplicates https://github.com/microsoft/vscode-js-debug/issues/1327, and is fixed on the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension)

**Comment by lewjc** [comment]
Thanks @connor4312
