### ISSUE TITLE
Extension webview debugging no longer works

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-js-debug#1344]
I cannot get Extension webview debugging to work anymore. I don't know if it is a change in js-debug or my sourcemap generation, but no matter what I've tried to debug GitLens webviews they no longer work.

From inspecting the sourcemaps, it looks like things are right, so I think it is something in js-debug -- it looks like the `absolutePath` it gets for the loaded js file gets the path almost doubled up -- you can see that in the logs and I see that Debug Doctor

![image](https://user-images.githubusercontent.com/641685/180922593-81b57463-fa0a-45a2-8559-2fc62169da04.png)

**To Reproduce**
1. Debug [GitLens](https://github.com/gitkraken/vscode-gitlens)
2. Try to set a breakpoint in `src/webviews/apps/home/home.ts`
3. Open the GitLens Home sidebar
4. See that the breakpoint will not be mapped properly

**Log File**
[vscode-debugadapter-5045641d.json.gz](https://github.com/microsoft/vscode-js-debug/files/9186491/vscode-debugadapter-5045641d.json.gz)

**VS Code Version:** 
Version: 1.70.0-insider (user setup)
Commit: 3cbf3063281410d21951877eb628551809d70c6b
Date: 2022-07-25T05:27:52.229Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22622

**Comment by eamodio** [comment]
@connor4312 👍 I didn't see a new nightly release -- should that be out soon? Dying to get this working 😄

**Comment by connor4312** [comment]
Looks like there was a transient failure in the publishing pipeline, kicking a new one now...

**Comment by eamodio** [comment]
Fixed it -- thanks so much!
