### ISSUE TITLE
extension host debugging stops on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-js-debug#135]
testing https://github.com/microsoft/vscode/issues/85984:

- use Ubuntu 16.04 LTS
- create hello world extension
- in launch config change type "extensionHost" to "pwa-extensionHost"
- F5
- wait a few seconds

Observe: VS Code enters debug mode for a few seconds but then the debug bar disappears, which means that the debug session has ended.

On the Chrome DevTools console the error "Unknown request: breakpointLocations " occurs:

![2019-12-03_15-46-20](https://user-images.githubusercontent.com/1898161/70061173-1bb82080-15e4-11ea-8b0b-bc439950e3eb.png)

When running extension tests no breakpoints are hit either. 

This problem does not occur on Ubuntu 19.04

**Comment by connor4312** [comment]
I'm not able to repro this on a fresh Ubuntu 16.04 install (with Node 12 installed via `nvm`). We do spawn a helper process using the system's Node install--I'm wonderings if that's failing for you perhaps. What version of Node is your 16.04 instance running, if any?

**Comment by weinand** [comment]
@connor4312 I'm using node 12.13.1 (via nvm) on Ubuntu 16.04.
In general we should not use the user installed node for helper processes because we never know what version of node we get. Instead Electron running as node should be used.

**Comment by weinand** [comment]
I just reproduced the problem in the latest Insiders.

If I set  the new setting `debug.showInlineBreakpointCandidates` to false, the "Unknown request: breakpointLocations " error no longer appears in the DevTool's console but the debug adapter still dies.

**Comment by connor4312** [comment]
Could you enable `trace: true` and send over the logs? The `unknown request` should be unrelated (the stubbed parent session is not listening for this which causes those console logs to be displayed, but they're benign.)

**Comment by connor4312** [comment]
Please reopen with logs if this is still an issue 🙂
