### ISSUE TITLE
Debugger doesn't reliably break on breakpoints in Angular projects

### ISSUE THREAD

**Issue by dschuessler** [microsoft/vscode-js-debug#1351]
**Describe the bug**
Since quite a while, the Chrome debugger works very unreliably for our Angular projects.

**To Reproduce**
1. `git clone https://github.com/dschuessler/debugger-bug-angular`
2. `docker-compose up` (Alternatively `cd test` && `npm run start` if you don't have Docker but node.js installed)
3. Start debugger config "Launch Chrome against localhost"
4. Set a breakpoint in `/test/src/app/app.component.ts`, line 12.
5. Reload the page in the Chrome instance launched by the debugger.

Expected behavior: Execution halts at the breakpoint.
Actual behavior: Execution does not halt at the breakpoint although the code is clearly executed, the Debugger is connected and the breakpoint is valid.  

**Log File**

[vscode-debugadapter-30f49726.json.gz](https://github.com/microsoft/vscode-js-debug/files/9242631/vscode-debugadapter-30f49726.json.gz)

**VS Code Version:** 1.69.2

**Additional context**
Sometimes it miraculously works. I haven't figured out yet under which conditions.

**Comment by connor4312** [comment]
I'm not sure why this works at all for you--you should set your `webRoot` to `${workspaceFolder}/test`, since that's where your sources are. With that change this works reliably and upon reload for me.
