### ISSUE TITLE
Breakpoints in Razor class libraries imported in a Blazor WASM project will not bind

### ISSUE THREAD

**Issue by EricCornelson** [microsoft/vscode-js-debug#1363]
**Describe the bug**

In a Blazor WebAssembly project, if a user creates a Razor class library with some javascript interop, they will be unable to hit breakpoints in those javascript files that are not in the main project (hitting breakpoints on javascript in the main Blazor WASM project works fine).

It seems that when the javascript is coming from a path other than the project root, the debug adapter can't map the script URL back to the file on disk, and so it's not finding the scriptId to set with (the setBreakpointByURL request with the file:/// url doesn't work at all in either case).

It's possible we could try to make `BlazorSourcePathResolver` smarter, and only send file URLs for razor/c# files, and the typical URL for javascript (which does work).

**To Reproduce**
1. Create a Blazor WebAssembly project
2. Add a Razor class library project to the solution
3. Add some JavaScript interop to the razor class library
4. try to set a breakpoint in the JavaScript, and launch the Blazor app

(also, See https://github.com/aspnet/AspNetCore-ManualTests/issues/284)

**Log File**

successful (javascript is in the main Blazor WASM project):  [visualstudio-js-debugger.txt](https://github.com/microsoft/vscode-js-debug/files/9285363/visualstudio-js-debugger.txt)

unsuccessful (javascript is in a razor class lib): 
[visualstudio-js-debugger_bad.txt](https://github.com/microsoft/vscode-js-debug/files/9285372/visualstudio-js-debugger_bad.txt)

**Comment by connor4312** [comment]
I repro'd this following the instructions on https://github.com/aspnet/AspNetCore-ManualTests/issues/284.

In that case, a script that happened to be in `libs/RazorLib1/wwwroot/exampleJsInterop.js` was served directly in `http://localhost:5200/_content/RazorLib1/exampleJsInterop.js`. There's nothing for the debugger to go on to locate the source file -- the URL is the same regardless of where the original file is from.

The most natural fix for this would be for the Blazor dev server to add a sourceURL, like `//# sourceURL=file:///original/source/path/libs/RazorLib1/wwwroot/exampleJsInterop.js`. This would let the debugger deterministically and easily map back to the right location without requiring js-debug changes. Thoughts?

**Comment by connor4312** [comment]
Let me know if there's a js-debug change you think would be appropriate here.
