### ISSUE TITLE
Race condition clearing debug breakpoints on startup

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode-js-debug#1371]
**Describe the bug**
Clearing breakpoints on process start can lead to the breakpoints still being bound with no UI to unbind them

**To Reproduce**
1. Set some breakpoints
2. Start debugging Code-OSS
3. As the window is spinning up hit clear all breakpoints
4. 🐛 Your breakpoints will still hit.
5. Reload the window and the breakpoints are still bound

**Comment by connor4312** [comment]
I couldn't hit this, but found a probable cause. Author verification requested 🙂
