### ISSUE TITLE
getVersionText fails because of missing cwd when using volta

### ISSUE THREAD

**Issue by airaolagoitia** [microsoft/vscode-js-debug#1375]
**Is your feature request related to a problem? Please describe.**

[Volta](https://volta.sh/)'s shim relies on the project `package.json` to find the correct node executable so as `getVersionText` is not setting `cwd` when calling `node --version`, the shim responds with an error.

**Describe the feature you'd like**

To fix this problem we would need to pass `cwd` all the way to `getVersionText` so the volta shim can find the `package.json` file.

I put up a branch to show the required change: https://github.com/microsoft/vscode-js-debug/compare/main...airaolagoitia:vscode-js-debug:getversion-cwd

**Comment by connor4312** [comment]
Those changes look OK to me, would you like to submit a PR? 🙂

**Comment by andresiraola** [comment]
@connor4312 I created a PR: https://github.com/microsoft/vscode-js-debug/pull/1385
