### ISSUE TITLE
F5 doesn't execute the code

### ISSUE THREAD

**Issue by mvcas** [microsoft/vscode-js-debug#1377]
Hello, I'm not sure if this is the right place... When I press F5, VSCode does not execute simple JS File. I followed instructions from Getting started with Visual Studio Code Microsoft video.
![VS Code Error](https://user-images.githubusercontent.com/40358718/187043315-ca55f1a4-bf20-45e6-8f34-f33661d36dd8.png)

**Comment by connor4312** [comment]
You must select the debugger you expect to use. Most likely you want to choose Node.js.

**Comment by mvcas** [comment]
No, that won't work. I found that you need to create launch.json file and to add "configuration" with "console" property in it.

**Comment by mvcas** [comment]
> You must select the debugger you expect to use. Most likely you want to choose Node.js.

No, that won't work. I found that you need to create launch.json file and to add "configuration" with "console" property in it.

**Comment by nehemiahlc** [comment]
Hi I am having the same issue, can you please help?
