### ISSUE TITLE
Debugging program with many local variables hangs the debugger

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-js-debug#138]
testing https://github.com/microsoft/vscode/issues/85984:

- debug this program with pwa: [10000locals.js.zip](https://github.com/microsoft/vscode-pwa/files/3917432/10000locals.js.zip)

Observe:
debugger does not stop on `debugger;` statement.

**Comment by connor4312** [comment]
I'm not able to repro this, at least with the set of fixes that came in between your testing and now.
