### ISSUE TITLE
Unable to preview named import for ts with sourcemap

### ISSUE THREAD

**Issue by liuxingbaoyu** [microsoft/vscode-js-debug#1383]
**Describe the bug**
When debugging ts files with source maps, named imported variables are not previewed properly.

**To Reproduce**
1. `git clone https://github.com/liuxingbaoyu/jsdebug-sourcemap-bug`
2. `yarn / npm i`
3. set breakpoint at `src\util\scope.ts` L18
4. start debugging `Launch Program`
5. preview `BIND_SCOPE_LEXICAL`
6. see error

**VS Code Version: 1.71.0 (user setup)

**Additional context**
![image](https://user-images.githubusercontent.com/30521560/188241421-379db8c2-bc6e-4c79-b7db-c219df17f5dc.png)
![image](https://user-images.githubusercontent.com/30521560/188241473-2b6ca158-e76d-4395-a665-292040b1845a.png)

**Comment by connor4312** [comment]
This is a result of how TS emits its `names`, not something the debugger controls.

**Comment by liuxingbaoyu** [comment]
Thanks for the quick reply, I'll look into the source map.

**Comment by liuxingbaoyu** [comment]
I've re-investigated and this seems to be something the debugger can fix.

As a simple test, I modified https://github.com/microsoft/vscode-js-debug/blob/main/src/common/sourceMaps/renameProvider.ts#L21 to `const identifierRe = /[$a -z_][$0-9A-Z_$]*.?[$0-9A-Z_$]*/iy;`, it works fine.

![image](https://user-images.githubusercontent.com/30521560/194187512-c48a0713-ae69-48c3-8073-d07a450832c4.png)

**Comment by connor4312** [comment]
The identifierRe is pretty strict because the sourcemap only gives us where a name _starts_, not the length of it. But I think including `.` in that should be fine.
