### ISSUE TITLE
Question: How to change output directory for performance profiling results?

### ISSUE THREAD

**Issue by dsvitnev** [microsoft/vscode-js-debug#1386]
Maybe i'm not clever enough but i did not find this option as available in debugger. Any help?

**Comment by connor4312** [comment]
This is not possible at the moment. I could take a PR for it.

**Comment by dsvitnev** [comment]
it would  be great, thank you!

**Comment by connor4312** [comment]
So far this hasn't been a popular ask. I'd still take a PR for it, but I'm going to close this issue as I have no plans to personally address it.
