### ISSUE TITLE
Unable to bind breakpoint in package in monorepo

### ISSUE THREAD

**Issue by azzlack** [microsoft/vscode-js-debug#1390]
**Describe the bug**
When using a monorepo, binding breakpoints in a package does not work.
Breakpoints in the main app works as they should.

See [sample repository for reproducable setup](https://github.com/azzlack/vscode-monorepo-debug).

This could of course also just be a misconfiguration, but I cannot find any good documentation on how this should be set up.

**To Reproduce**
1. Start project by running `pnpm dev` in the root folder.
2. Attach VSCode by using the included launch.json config
3. Set a breakpoint in `apps/web/pages/api/hello.ts` on line 9.
4. Set a breakpoint in `packages/lib/src/HelloWorld.ts` on line 2.
5. Open [http://localhost:3000/api/hello](http://localhost:3000/api/hello) in a browser
6. Observe that the breakpoint in `apps/web/pages/api/hello.ts` is hit, while the one in `packages/lib/src/HelloWorld.ts` is not

**Log File**
[vscode-debugadapter-acbac098.json.zip](https://github.com/microsoft/vscode-js-debug/files/9527806/vscode-debugadapter-acbac098.json.zip)

**VS Code Version:** 1.71.0

**Tech Stack in Sample**
* Next.js
* Turbo
* tsup
* TypeScript
* pnpm

**launch.json**
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "attach",
            "name": "Attach: Web",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "cwd": "${workspaceFolder}/apps/web",
            "trace": true,
        }
    ]
}
```

**package.json (web)**
```
{
  "name": "web",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "cross-env NODE_OPTIONS='--inspect' next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "12.2.5",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "lib": "workspace:^1.0.0"
  },
  "devDependencies": {
    "@types/node": "18.7.16",
    "@types/react": "18.0.18",
    "@types/react-dom": "18.0.6",
    "eslint": "8.23.0",
    "eslint-config-next": "12.2.5",
    "tsconfig": "workspace:^1.0.0",
    "typescript": "^4.8.2",
    "cross-env": "^7.0.3"
  }
}
```

**package.json (lib)**
```
{
  "name": "lib",
  "version": "1.0.0",
  "description": "",
  "private": true,
  "main": "./dist/index.js",
  "module": "./dist/index.mjs",
  "types": "./dist/index.d.ts",
  "source": "./index.ts",
  "files": ["dist", "src", "index.ts"],
  "scripts": {
    "build": "tsup --treeshake",
    "dev": "tsup --watch",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "tsconfig": "workspace:^1.0.0",
    "tsup": "^6.2.2"
  },
}
```

**Output from Debug Diagnostics**
![CleanShot 2022-09-08 at 16 43 23](https://user-images.githubusercontent.com/1385084/189152382-9d32a6c6-7e69-4e88-952c-0f87a1ac67c3.png)

**Comment by connor4312** [comment]
This has generally required creating a [custom webpack config](https://nextjs.org/docs/api-reference/next.config.js/custom-webpack-config) with next.js and telling it to use the webpack [source-map-loader](https://webpack.js.org/loaders/source-map-loader/), since at the moment source resolution stops with `index.js`. 

However I have put in a change to support this scenario automatically in https://github.com/microsoft/vscode-js-debug/issues/1390. You will be able to use this in the nightly extension: https://github.com/microsoft/vscode-js-debug#nightly-extension

**Comment by Daydreamer-riri** [comment]
Hi @connor4312 , I think Nightly-EXTENSION has no effect. Breakpoints in 'https://github.com/azzlack/vscode-monorepo-debug' still does not work.
