### ISSUE TITLE
Problema para depurar

### ISSUE THREAD

**Issue by mafiozo1518** [microsoft/vscode-js-debug#1391]
![WhatsApp Image 2022-09-10 at 16 49 10](https://user-images.githubusercontent.com/112278104/189542674-3afb3e55-3ca9-41dc-a735-d3c28c500389.jpeg)

Ola pessoal!

estou com problema para fazer uma depuração no vs code com node.js, quando eu clico em executar e depurar ele começa a carregar mas dai fica desse jeito que esta na imagem, na parte de pontos de parada ele fica com um ponto que parece estilo um erro mas eu não sei como resolver, se alguém poder me ajudar agradeço.

OBS: já atualizei o vs code e o node.js.

obrigado

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/159881, will be fixed in our release later this week
