### ISSUE TITLE
Provide better details for `Debug: Toggle Auto Attach`

### ISSUE THREAD

**Issue by jsoref** [microsoft/vscode-js-debug#1392]
**Is your feature request related to a problem? Please describe.**

macOS 12.6
VSCode Version: 1.71.1 (Universal)
JavaScript Debugger v1.71.0

```sh
jsoref@jsoref-mbp yarn % which node
/Users/jsoref/.nvm/versions/node/v16.13.2/bin/node
```

This _appears_ to be a _node_ and it _appears_ to be in my path.

When I use `cmd`-`shift`-`p` and enter `Debug: Toggle Auto Attach` and toggle to something that isn't `Disabled`, I get this dialog:
<img width="462" alt="image" src="https://user-images.githubusercontent.com/2119212/190292207-1f2da44c-c482-428a-a05e-bb6bc8d650b0.png">

Clicking details takes me to #708

> There are three things you can do to get around this issue:
> 1. Update to a Node version >12
> 2. If the error is not correct (which may happen when using .rc-file based version managers like nvm or nvs), you can still enable auto attach by running the command Debug: Force Enable Auto-Attach from the command palette. If this breaks your setup, you can restore your state by setting auto attach to disabled and then reloading the VS Code window.
> 3. You can use the previous version of auto attach by turning the setting `debug.javascript.usePreviewAutoAttach` off

I tried 3 and that didn't seem to do anything.

**Describe the feature you'd like**

I'd like a sheet or pane or something that actually helps a user figure out how to make things work, or a page that has current information.

**Comment by connor4312** [comment]
Now that Node 12 is EOL and its usage is continuing to decrease in VS Code, I think we can loosen the restriction to allow turning auto attach on with spaces in the path.

**Comment by alexr00** [comment]
@connor4312 what's the best way to verify this?
