### ISSUE TITLE
debug twice transformed js to original TS souce code.

### ISSUE THREAD

**Issue by l1987lll** [microsoft/vscode-js-debug#1393]
**Is your feature request related to a problem? Please describe.**
I have a project A writes in TS which is a npm package, there is a sample project (hello world) use this package, the sample project is in a subfolder of the package. I want VSCode can go to TS files when debugging hello world project, but it seams can only debug into the js files which located in node_modules.

**Describe the feature you'd like**
Is it possible VSCode can directly support this scenario? I found two tools in github to re-generate a combined sourcemap, but I think it would be great if VSCode can directly support this scenario.
[multi-stage-sourcemap](https://github.com/azu/multi-stage-sourcemap)
[sorcery](https://github.com/Rich-Harris/sorcery)

![image](https://user-images.githubusercontent.com/5010054/190852344-105025ae-4980-4093-8bbb-be20bf7bd211.png)

**Comment by connor4312** [comment]
Done in https://github.com/microsoft/vscode-js-debug/pull/1410

**Comment by weinand** [comment]
@l1987lll it would be great if you could verify your feature in the latest VS Code Insider.
