### ISSUE TITLE
Debug typescript line by line

### ISSUE THREAD

**Issue by dn54321** [microsoft/vscode-js-debug#1399]
I have recently tried out the debugger using Create React App + typescript and noticed that when I debug typescript files, when I step in or step over, I may need to step multiple times before going to the next line. Upon further investigation, I found that the debugger actually attaches to the transpiled typescript code (JavaScript code). One typescript line may transpile to multiple JavaScript lines, as such, I would need to step over multiple times before the debugger goes to the next typescript line.

I would really cool to have an option that would allow me to step to the next typescript line instead of the next JavaScript line by changing some configuration in launch.json file.

**Comment by connor4312** [comment]
I don't have any plans for this right now. TypeScript when targeting a reasonably modern target (ES2019+) now very rarely emits extra lines of code outside of certain exotic things like decorations--though of course TypeScript is not the only language that compiles to JavaScript.
