### ISSUE TITLE
Confusing pwa- prefix in documentation

### ISSUE THREAD

**Issue by romankaravia** [microsoft/vscode-js-debug#1404]
In [OPTIONS.md](https://github.com/microsoft/vscode-js-debug/blob/main/OPTIONS.md) all launch config types have a `pwa-` prefix.

But when I try to use it, VS Code tells me this: 
![image](https://user-images.githubusercontent.com/47303530/193264164-353af11c-82d0-4d8b-b6f2-2ca4dbded67c.png)

As someone new to vscode-js-debug I found this very confusing and it even made me doubt if I have this plugin enabled, or if I'm somehow still one the [old one](https://github.com/microsoft/vscode-chrome-debug).

=> Please remove the `pwa-` prefix from the docs.

Related: https://github.com/microsoft/vscode/issues/151910

**Comment by roblourens** [comment]
Use "chrome". The journey to kill `pwa-` continues 😁

**Comment by Lippiece** [comment]
Can anyone tell what does pwa- mean and why should it be avoided?

**Comment by romankaravia** [comment]
It's explained in [a comment in the issue linked above](https://github.com/microsoft/vscode/issues/151910#issuecomment-1153998582):

> We have pwa-node for historical reasons: the current [js-debug](https://github.com/microsoft/vscode-js-debug) used to be called the "pwa debugger" or something like that due to additional features it added to be able to debug [PWA](https://en.wikipedia.org/wiki/Progressive_web_app)s. It then replaced the built-in debugger and took over prefix-free launch types (node, chrome, etc.). However, we can't remove the old configurations without breaking users who have them in their configs.
