### ISSUE TITLE
VSCode skip breakpoint in JS file Ubuntu 20.04, node 12.22.10

### ISSUE THREAD

**Issue by GrandFoin01** [microsoft/vscode-js-debug#1405]
**Describe the bug**
Using impossible to use breakpoints in a JS file:

**To Reproduce**
1. Use launch.json file as describe below for the debug launch
2. Use this helloworld.js file as describe below for the file with breakpoint.
3. Observe that breakpoint is skipped.

launch.json
{
    "version": "0.2.0",

    "configurations": [

        {

            "name": "Launch ATF Tests on all test files.",

            "type": "node",

            "request": "launch",

            "cwd": "${workspaceFolder}",

            "runtimeExecutable": "node",

            "runtimeArgs": ["--preserve-symlinks", "./helloworld.js", "./test"],

            "runtimeVersion": "12",

            "trace": true

        }

    ]

}

helloworld.js
console.log("Helloworld!);

**VS Code Version:** 
1.60.2

**Additional context**
I use a MacOS to ssh into a Ubuntu 20.04 box

**Comment by connor4312** [comment]
Please collect a log file using the instructions in the issue template.

**Comment by GrandFoin01** [comment]
{"timestamp":1664554560414,"tag":"runtime.welcome","level":1,"message":"js-debug v1.60.2 started","metadata":{"os":"linux x64","nodeVersion":"v14.16.0","adapterVersion":"1.60.2"}}
{"tag":"dap.receive","timestamp":1664554560344,"metadata":{"connectionId":39,"message":{"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"pwa-node","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us","supportsProgressReporting":true,"supportsInvalidatedEvent":true,"supportsMemoryReferences":true},"type":"request","seq":1}},"level":0}
{"tag":"dap.send","timestamp":1664554560344,"metadata":{"connectionId":39,"message":{"seq":1,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"supportsConfigurationDoneRequest":true,"supportsFunctionBreakpoints":false,"supportsConditionalBreakpoints":true,"supportsHitConditionalBreakpoints":true,"supportsEvaluateForHovers":true,"exceptionBreakpointFilters":[{"filter":"all","label":"Caught Exceptions","default":false,"supportsCondition":true,"description":"Breaks on all throw errors, even if they're caught later.","conditionDescription":"error.name == \"MyError\""},{"filter":"uncaught","label":"Uncaught Exceptions","default":false,"supportsCondition":true,"description":"Breaks only on errors or promise rejections that are not handled.","conditionDescription":"error.name == \"MyError\""}],"supportsStepBack":false,"supportsSetVariable":true,"supportsRestartFrame":true,"supportsGotoTargetsRequest":false,"supportsStepInTargetsRequest":false,"supportsCompletionsRequest":true,"supportsModulesRequest":false,"additionalModuleColumns":[],"supportedChecksumAlgorithms":[],"supportsRestartRequest":true,"supportsExceptionOptions":false,"supportsValueFormattingOptions":true,"supportsExceptionInfoRequest":true,"supportTerminateDebuggee":false,"supportsDelayedStackTraceLoading":true,"supportsLoadedSourcesRequest":true,"supportsLogPoints":true,"supportsTerminateThreadsRequest":false,"supportsSetExpression":true,"supportsTerminateRequest":false,"completionTriggerCharacters":[".","[","\"","'"],"supportsBreakpointLocationsRequest":true,"supportsClipboardContext":true,"supportsExceptionFilterOptions":true}}},"level":0}
{"tag":"dap.send","timestamp":1664554560345,"metadata":{"connectionId":39,"message":{"seq":2,"type":"event","event":"initialized","body":{}}},"level":0}
{"tag":"dap.receive","timestamp":1664554560409,"metadata":{"connectionId":39,"message":{"command":"launch","arguments":{"type":"pwa-node","name":"Launch ATF Tests on all test files.","request":"launch","trace":{"console":false,"level":"verbose","stdio":true,"logFile":"/home/ll405k/.vscode-server/data/logs/20220930T143651/exthost3/ms-vscode.js-debug/vscode-debugadapter-d813347d.json.gz","tags":[]},"outputCapture":"console","timeout":10000,"timeouts":{},"showAsyncStacks":true,"skipFiles":[],"smartStep":true,"sourceMaps":true,"sourceMapRenames":true,"pauseForSourceMap":false,"rootPath":"/home/ll405k/app_bidderc/atf-tests","outFiles":["/home/ll405k/app_bidderc/atf-tests/**/*.js","!**/node_modules/**"],"sourceMapPathOverrides":{"webpack:///./~/*":"/home/ll405k/app_bidderc/atf-tests/node_modules/*","webpack:////*":"/*","webpack://?:*/*":"/home/ll405k/app_bidderc/atf-tests/*","webpack:///([a-z]):/(.+)":"$1:/$2","meteor://💻app/*":"/home/ll405k/app_bidderc/atf-tests/*"},"enableContentValidation":true,"cascadeTerminateToConfigurations":[],"__workspaceFolder":"/home/ll405k/app_bidderc/atf-tests","__autoExpandGetters":false,"__breakOnConditionalError":false,"cwd":"/home/ll405k/app_bidderc/atf-tests","env":{"PATH":"/home/ll405k/.nvm/versions/node/v12.22.10/bin:/home/ll405k/.vscode-server/bin/7f6ab5485bbc008386c4386d08766667e155244e/bin:/home/ll405k/.vscode-server/bin/7f6ab5485bbc008386c4386d08766667e155244e/bin:/home/ll405k/.nvm/versions/node/v12.22.10/bin:/usr/appnexus/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/puppetlabs/bin:/opt/dell/srvadmin/bin:/home/ll405k/.fzf.install/fzf-0.17.5/bin:/home/ll405k/bin:/home/ll405k/bin"},"envFile":null,"localRoot":null,"remoteRoot":null,"autoAttachChildProcesses":true,"runtimeSourcemapPausePatterns":[],"program":"","stopOnEntry":false,"console":"internalConsole","restart":false,"args":[],"runtimeExecutable":"node","runtimeVersion":"12","runtimeArgs":["--preserve-symlinks","./helloworld.js","./test"],"profileStartup":false,"attachSimplePort":null,"killBehavior":"forceful","__configurationTarget":5,"noDebug":true,"__workspaceCachePath":"/home/ll405k/.vscode-server/data/User/workspaceStorage/62ac748a2c06a543624d8c5f39ce5976/ms-vscode.js-debug","__sessionId":"0d0f20a9-5805-47e4-9144-ce52cd939a76"},"type":"request","seq":2}},"level":0}

**Comment by GrandFoin01** [comment]
{"tag":"dap.send","timestamp":1664554560410,"metadata":{"connectionId":39,"message":{"seq":3,"type":"event","event":"output","body":{"category":"telemetry","output":"js-debug/launch","data":{"type":"pwa-node","request":"launch","os":"linux x64","nodeVersion":"v14.16.0","adapterVersion":"1.60.2","parameters":"{\"type\":\"pwa-node\",\"name\":\"<string>\",\"request\":\"launch\",\"trace\":{\"console\":false,\"level\":\"<string>\",\"stdio\":true,\"logFile\":\"<string>\",\"tags\":[]},\"outputCapture\":\"console\",\"timeout\":10000,\"timeouts\":{},\"showAsyncStacks\":true,\"skipFiles\":[],\"smartStep\":true,\"sourceMaps\":true,\"sourceMapRenames\":true,\"pauseForSourceMap\":false,\"resolveSourceMapLocations\":[\"<string>\",\"<string>\"],\"rootPath\":\"<string>\",\"outFiles\":[\"<string>\",\"<string>\"],\"sourceMapPathOverrides\":{\"webpack:///./~/*\":\"<string>\",\"webpack:////*\":\"<string>\",\"webpack://?:*/*\":\"<string>\",\"webpack:///([a-z]):/(.+)\":\"<string>\",\"meteor://💻app/*\":\"<string>\"},\"enableContentValidation\":true,\"cascadeTerminateToConfigurations\":[],\"__workspaceFolder\":\"<string>\",\"__autoExpandGetters\":false,\"__breakOnConditionalError\":false,\"cwd\":\"<string>\",\"env\":{\"PATH\":\"<string>\"},\"envFile\":null,\"localRoot\":null,\"remoteRoot\":null,\"autoAttachChildProcesses\":true,\"runtimeSourcemapPausePatterns\":[],\"program\":\"\",\"stopOnEntry\":false,\"console\":\"internalConsole\",\"restart\":false,\"args\":[],\"runtimeExecutable\":\"node\",\"runtimeVersion\":\"<string>\",\"runtimeArgs\":[\"<string>\",\"<string>\",\"<string>\"],\"profileStartup\":false,\"attachSimplePort\":null,\"killBehavior\":\"forceful\",\"__configurationTarget\":5,\"noDebug\":true,\"__workspaceCachePath\":\"<string>\",\"__sessionId\":\"<string>\"}"}}}},"level":0}
{"tag":"dap.send","timestamp":1664554560411,"metadata":{"connectionId":39,"message":{"seq":4,"type":"event","event":"output","body":{"category":"console","output":"Verbose logs are written to:\n/home/ll405k/.vscode-server/data/logs/20220930T143651/exthost3/ms-vscode.js-debug/vscode-debugadapter-d813347d.json.gz\n"}}},"level":0}
{"tag":"dap.receive","timestamp":1664554560425,"metadata":{"connectionId":39,"message":{"command":"configurationDone","type":"request","seq":3}},"level":0}
{"tag":"dap.send","timestamp":1664554560425,"metadata":{"connectionId":39,"message":{"seq":5,"type":"response","request_seq":3,"command":"configurationDone","success":true,"body":{}}},"level":0}
{"tag":"runtime.launch","timestamp":1664554560426,"message":"Using binary at","metadata":{"location":"/home/ll405k/.nvm/versions/node/v12.22.10/bin/node","executable":"node"},"level":1}
{"tag":"runtime.launch","timestamp":1664554560435,"message":"Discovered version","metadata":{"version":"v12.22.10"},"level":1}
{"tag":"dap.send","timestamp":1664554560442,"metadata":{"connectionId":39,"message":{"seq":6,"type":"event","event":"output","body":{"category":"console","output":"/home/ll405k/.nvm/versions/node/v12.22.10/bin/node --preserve-symlinks ./helloworld.js ./test"}}},"level":0}
{"tag":"runtime.launch","timestamp":1664554560448,"message":"Launched successfully","metadata":{"name":"x"},"level":1}
{"tag":"dap.send","timestamp":1664554560448,"metadata":{"connectionId":39,"message":{"seq":7,"type":"response","request_seq":2,"command":"launch","success":true,"body":{}}},"level":0}
{"tag":"dap.receive","timestamp":1664554560458,"metadata":{"connectionId":39,"message":{"command":"threads","type":"request","seq":4}},"level":0}
{"tag":"dap.send","timestamp":1664554560458,"metadata":{"connectionId":39,"message":{"seq":8,"type":"response","request_seq":4,"command":"threads","success":true,"body":{"threads":[]}}},"level":0}
{"tag":"dap.receive","timestamp":1664554560481,"metadata":{"connectionId":39,"message":{"command":"loadedSources","type":"request","seq":5}},"level":0}
{"tag":"dap.send","timestamp":1664554560481,"metadata":{"connectionId":39,"message":{"seq":9,"type":"response","request_seq":5,"command":"loadedSources","success":true,"body":{"sources":[]}}},"level":0}
{"tag":"cdp.receive","timestamp":1664554560580,"metadata":{"connectionId":19,"message":{"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"c6788dbe8a87134afac484ce","processId":1981328,"type":"waitingForDebugger","title":"/home/ll405k/app_bidderc/atf-tests/helloworld.js","url":"file:///home/ll405k/app_bidderc/atf-tests/helloworld.js","attached":true,"canAccessOpener":false,"processInspectorPort":53031}}}},"level":0}

**Comment by GrandFoin01** [comment]
{"tag":"cdp.send","timestamp":1664554560581,"metadata":{"connectionId":19,"message":{"id":1001,"method":"Target.attachToTarget","params":{"targetId":"c6788dbe8a87134afac484ce"}}},"level":0}
{"tag":"cdp.receive","timestamp":1664554560588,"metadata":{"connectionId":19,"message":{"id":1001,"result":{"sessionId":"c6788dbe8a87134afac484ce"}}},"level":0}
{"tag":"cdp.send","timestamp":1664554560588,"metadata":{"connectionId":19,"message":{"id":1002,"method":"NodeWorker.enable","params":{"waitForDebuggerOnStart":true}}},"level":0}
{"tag":"cdp.receive","timestamp":1664554560590,"metadata":{"connectionId":19,"message":{"id":1002,"result":{}}},"level":0}
{"tag":"cdp.send","timestamp":1664554560671,"metadata":{"connectionId":19,"message":{"id":1003,"method":"Runtime.enable","params":{}}},"level":0}
{"tag":"runtime.launch","timestamp":1664554560671,"message":"Running with noDebug, so debug domains are disabled","level":1}
{"tag":"cdp.send","timestamp":1664554560671,"metadata":{"connectionId":19,"message":{"id":1004,"method":"Debugger.setAsyncCallStackDepth","params":{"maxDepth":32}}},"level":0}
{"tag":"cdp.receive","timestamp":1664554560673,"message":"Dequeue messages","metadata":{"message":[]},"level":0}
{"tag":"cdp.receive","timestamp":1664554560685,"metadata":{"connectionId":19,"message":{"method":"Runtime.executionContextCreated","params":{"context":{"id":1,"origin":"","name":"/home/ll405k/.nvm/versions/node/v12.22.10/bin/node[1981328]","auxData":{"isDefault":true}}}}},"level":0}
{"tag":"cdp.receive","timestamp":1664554560685,"metadata":{"connectionId":19,"message":{"id":1003,"result":{}}},"level":0}
{"tag":"cdp.receive","timestamp":1664554560685,"metadata":{"connectionId":19,"message":{"id":1004,"result":{}}},"level":0}

**Comment by GrandFoin01** [comment]
[vscode-debugadapter-d813347d.json.gz](https://github.com/microsoft/vscode-js-debug/files/9687154/vscode-debugadapter-d813347d.json.gz)

**Comment by connor4312** [comment]
You're running via "Debug: Start Without Debugging". In this mode, breakpoints (among other features of the debugger) are not enabled. You want to run the "Debug: Start Debugging" task instead.
