### ISSUE TITLE
Sending breakpoint change event after removal

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#1406]
Hey @connor4312, I noticed that https://github.com/microsoft/vscode/issues/157317 regressed, and I'm trying to figure out whether anything changed on js-debug's side, or I just hit a different case from what we verified somehow?

- Debug js
- Add a breakpoint
- Disable the breakpoint
- js-debug sends a bp change event which marks the bp as unbound, and this state is apparently considered "enabled" by vscode

I'd expect that js-debug should not send an event for a breakpoint which has been removed in DAP. But also, vscode should probably not allow DAs to modify breakpoints that are disabled.

[vscode-debugadapter-002e8ca0.json.gz](https://github.com/microsoft/vscode-js-debug/files/9690916/vscode-debugadapter-002e8ca0.json.gz)

**Comment by weinand** [comment]
When disabling a breakpoint in an active js-debug session, VS Code shows an "Unbound breakpoint" hover.
When disabling a breakpoint when no debug session is active, VS Code shows an "Disabled breakpoint" hover.

**Comment by roblourens** [comment]
I don't see that @weinand, could you include a screenshot or code example?

**Comment by weinand** [comment]
![2022-10-27_12-43-17 (1)](https://user-images.githubusercontent.com/1898161/198264487-9c3cfe88-3fe5-44f1-a3a5-1da6bb4a0c9b.gif)

**Comment by rzhao271** [comment]
Reopening the issue based on https://github.com/microsoft/vscode-js-debug/issues/1406#issuecomment-1292158221

**Comment by connor4312** [comment]
@weinand note that I did not make a stable js-debug bump in the last release; please verify this on nightly (or in the November release)
