### ISSUE TITLE
Error activating auto-attach in vscode

### ISSUE THREAD

**Issue by justtonowu** [microsoft/vscode-js-debug#1411]

**Comment by connor4312** [comment]
Please provide more info, such as errors in the debug console

**Comment by justtonowu** [comment]
Debugging error in terminal during npx create-react-app .

**Comment by connor4312** [comment]
Do you see any errors in the console when running Toggle Developer Tools?

**Comment by connor4312** [comment]
Thanks. Once again, do you see any errors in the "Console" when running the Toggle Developer Tools command?

**Comment by justtonowu** [comment]
No
