### ISSUE TITLE
Allows to stop printing the attach message.

### ISSUE THREAD

**Issue by liuxingbaoyu** [microsoft/vscode-js-debug#1420]
**Is your feature request related to a problem? Please describe.**
When debugging a test, the attach message affects the stdout of the child process, which will cause the test to fail.

**Describe the feature you'd like**
Add an option to allow to stop printing attach messages.

**Comment by connor4312** [comment]
This is a behavior of Node.js which is unfortunately not configurable.

**Comment by liuxingbaoyu** [comment]
I get it, thank.
