### ISSUE TITLE
Is it possible to debug a chrome extension?

### ISSUE THREAD

**Issue by jfrancis537** [microsoft/vscode-js-debug#1421]
When trying to attach to a chrome extension, the debugger hangs. It also doesn't appear in the pick list when that option is chosen. Here is the launch JSON that I have been using. Sometime I omit the url and replace it with pick.

    {
      "type": "chrome",
      "request": "attach",
      "name": "Chrome JS Debugger",
      "port": 9224,
      "trace": true,
      "url": "chrome-extension://...",
    }
    
Obviously it's possible to use the built in inspector for this task, but it would be nice to debug the extensions directly from chrome.

**Comment by connor4312** [comment]
I think some people have figured out how to do it, but we don't formally support debugging Chrome extensions.

**Comment by connor4312** [comment]
Duplicating into https://github.com/microsoft/vscode-js-debug/issues/945
