### ISSUE TITLE
DAP Scopes aren't being updated after a variable has changed

### ISSUE THREAD

**Issue by gfszr** [microsoft/vscode-js-debug#1425]
**Describe the bug**
`variables` command on scopes' `variablesReference`is not updated if the values of the variables had changed (For example, watch evaluation or variable set). It does work however on an object's `variablesReference` and the bug is specific to scopes.

**To Reproduce**
Reproducing with `setVariable` is tougher and requires sending DAP packets by hand (When setting a variable, VSCode doesn't fetch the entire variables but uses the returned result from the `setVariable` request), but the easiest way would be the following using VSCode watches:
1. Debug the following code:
```typescript
let a = 1
let b = 2
let c = 3
let d = {"m_1":1, "m_2":2}
console.log("Hello world!\n") // <= Place breakpoint here
```
2. Place a single watch: `eval("a = 8")` - see that it doesn't update the value of `a`.
3. Place another watch: `eval("d.m_1 = 20")` - see that it indeed updates!
4. Behind the scenes: After evaluating a watch, VSCode requests again for the scopes and variables of the current frame, upon which `a` returns with the un-updated value while `d.m_1` is. 

**Log File**

No log file is required, as it is easy to reproduce. 

**VS Code Version:** 1.72.0

**Comment by connor4312** [comment]
Thanks for the issue. Unfortunately (as this has been reported before a long time ago) this is a bug in V8, rather than the debugger: the scope "object" from V8 does not reflect changed variables.

**Comment by gfszr** [comment]
Oh no... thanks for the quick reply! Do you happen to know if this was reported or referenced by V8 maintainers in any way?

**Comment by gfszr** [comment]
@connor4312 Seems to be a wontfix.... https://bugs.chromium.org/p/chromium/issues/detail?id=874865
