### ISSUE TITLE
Debug sessions for webviews in electron do not appear

### ISSUE THREAD

**Issue by a1exwang** [microsoft/vscode-js-debug#1432]
**Describe the bug**
I have an Electron app (started with `--remote-debugging-port=9222`) and there is a webview in this electron app. I want to debug js code running in the webview with VS code. `index.html` (main page of the renderer process) debugging works but debugging code in webview does not work

**To Reproduce**
1. Start electron app
2. Launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to app",
            "type": "chrome",
            "request": "attach",
            "port": 9222,
        },
    ]
}

```
3. F5 to start "Attach to app"
4. Only one debug session exists (index.html). The webview url is not found (should start with https://teams.microsoft.com/...)
. And `console.log` in webview will not show in debug console and breakpoints do not work.
<img width="990" alt="image" src="https://user-images.githubusercontent.com/9698542/196884213-01120ee6-1951-4486-ad54-a169c0c128a3.png">

5. However, if I go to `chrome://inspect` in Chrome browser, two debug session can show up and inspector works. So it appears that the Electron app itself works perfectly.
<img width="719" alt="image" src="https://user-images.githubusercontent.com/9698542/196883642-7767b87f-bae7-431e-a013-2a45dae991e2.png">

6. Go to `http://localhost:9222`, it also shows two debug sessions
![image](https://user-images.githubusercontent.com/9698542/196887212-fa36d2a6-991d-449f-9108-5c4194248290.png)

**Log File**

**VS Code Version:** 
Version: 1.72.2 (user setup)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:15:18.074Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No
**Additional context**

Similar to this issue https://github.com/microsoft/vscode/issues/47302

**Comment by connor4312** [comment]
We don't support Electron webviews (and generally they also [recommend against them](https://www.electronjs.org/docs/latest/api/webview-tag)). js-debug does support iframes, however.

**Comment by Rabbitzzc** [comment]
if you want to debug webview in electron inspect, you should change the extension code... 

Actually,  Webview is same with Page, you can add the code...
![image](https://github.com/microsoft/vscode-js-debug/assets/26913511/45aafedb-4a81-4035-a506-523efd16bc79)
