### ISSUE TITLE
Unable to bind breakpoint on source file, weird error message

### ISSUE THREAD

**Issue by sherpya** [microsoft/vscode-js-debug#1435]
**Describe the bug**

I'm trying to debug odoo addon (javascript), but I'm unable to set breakpoint directly in vscode (setting in the browser does work)
I've tried various mappings, but I got a weird error, vcode says that the breakpoint is initially set to the same path
it suggests.

✅ This breakpoint was initially set in:

/home/sherpya/workspace/odoo/odoo/odoo/custom_addons/website_model_viewer/static/src/js/website_model_viewer_editor.js line 15 column 1

❓ We couldn't find a corresponding source location, but found some other files with the same name:

/home/sherpya/workspace/odoo/odoo/odoo/custom_addons/website_model_viewer/static/src/js/website_model_viewer_editor.js
You may need to adjust the webRoot in your launch.json if you're building from a subfolder, or tweak your sourceMapPathOverrides.

As you can see it is the same path, attached the screenshort because thre strikeout text is weird too:

![Screenshot_20221027_055921](https://user-images.githubusercontent.com/120074/198188078-8ca9f225-f4f9-4ad0-b81d-10fdcdcff3bd.png)

**Log File**
[vscode-debugadapter-fc3616cc.json.gz](https://github.com/microsoft/vscode-js-debug/files/9875663/vscode-debugadapter-fc3616cc.json.gz)

**VS Code Version:** 1.72.2

Launch configuration:
```json
        {
            "name": "Launch Chrome",
            "request": "launch",
            "type": "chrome",
            "url": "http://localhost:8069/?debug=assets",
            "webRoot": "${workspaceFolder}",
            "trace": true,
            "pathMapping": {
                "/": "${workspaceFolder}/addons",
                "/website_model_viewer": "${workspaceFolder}/custom_addons/website_model_viewer",
            },
            "sourceMapPathOverrides": {
                "/website_model_viewer": "${workspaceFolder}/custom_addons/website_model_viewer",
            }
        }
```

**Comment by connor4312** [comment]
The path is not the same: the strikeout shows what's missing from the resolved path.

sourceMapPathOverrides is missing a `/*` at the end of the key and value.

**Comment by sherpya** [comment]
sorry even worse:
```json
            "sourceMapPathOverrides": {
                "/website_model_viewer/*": "${workspaceFolder}/custom_addons/website_model_viewer/*",
            }
```

tried also to add to the `pathMapping`:

![image](https://user-images.githubusercontent.com/120074/202731437-531dfc28-9997-4c39-8b59-80712f86f8a8.png)

**Comment by deeeed** [comment]
Any update on this? I have a similar issue...

**Comment by DKilkenny** [comment]
I'm also running into this issue. Out of nowhere VSCode stopped binding my breakpoints. Worked fine yesterday

**Comment by DKilkenny** [comment]
Mine was due to an issue that a chrome update pushed out. https://github.com/microsoft/vscode-js-debug/issues/1604

**Comment by akaraibrahimov** [comment]
Mine just fixed itself and I don't know how

**Comment by echogeo** [comment]
Please check if your path structure matches the format "c:\project\project". If it does, I would suggest renaming the second 'project' folder to 'test' in order to avoid nested folders with the same name: "c:\project\test"

This was the issue in my case.

**Comment by arjavsethi** [comment]
I am facing the same issue any updates on this?

**Comment by arjavsethi** [comment]
> ```json
> sourceMapPathOverrides
> ```

Mine got solved by adding  "webRoot": "${workspaceFolder}/packages/web", into configuration of launch.json .

**Comment by subins829** [comment]
any updates related to this issue ?

**Comment by Philip-Isaacs** [comment]
Also having the same issue. VS Code can no longer hit any break points inside of my JSX files. It used to work but something must have changed.

**Comment by connor4312** [comment]
Please file separate issues for your problems and collect the information the template asks for.
