### ISSUE TITLE
sourceMapPathOverrides seems not working with vite dev server

### ISSUE THREAD

**Issue by rmajasol** [microsoft/vscode-js-debug#1436]
Hello, im running a flask project with vite and i found i cannot map vite dev server generated js files to my local files, 

e.g. `localhost:5173/js/test.js` -> `/path/to/my/project/js/test.js`

so when i put a breakpoint inside vscode on any line at `test.js` local file, it does not stop there. Not even displaying typical red dot marking a breakpoint in debugger.

<img width="528" alt="Captura de pantalla 2022-10-31 a las 16 26 06" src="https://user-images.githubusercontent.com/822842/199045370-177e9573-3a4a-4989-a21d-1fa484792553.png">

If i add `debugger;` sentence, script stops there in browser as usual but vscode opens `localhost:5173/js/test.js` generated by vite dev server, not being able to edit:

<img width="660" alt="Captura de pantalla 2022-10-31 a las 16 39 06" src="https://user-images.githubusercontent.com/822842/199048396-53abb53b-eac0-4476-bef7-77ca7abc8cef.png">

Here my config added to launch.json:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Browser: Play",
            "request": "launch",
            "type": "chrome",
            "trace": true,
            "url": "http://localhost:5000/play",
            "webRoot": "${workspaceFolder}/src/web_server",
            "sourceMapPathOverrides": {
                "localhost:5173/js/test.js": "${webRoot}/static/js/test.js"
            },
        },
        ...rest of launch.json
```

Also put this lines at corresponding .html `<header>` section, as explained in [vite docs](https://vitejs.dev/guide/backend-integration.html#backend-integration):

```html
<script type="module" src="http://localhost:5173/@vite/client"></script>
<script type="module" src="http://localhost:5173/js/test.js"></script>
```

Tested ok without using vite dev server. Maybe im doing something wrong with `sourceMapPathOverrides` option?

Thanks!

**Comment by connor4312** [comment]
Please include a trace log using the instructions in the issue template.
