### ISSUE TITLE
Is it possible to inspect value from an angular html template ?

### ISSUE THREAD

**Issue by naomeencontro** [microsoft/vscode-js-debug#1437]
Hi,

I'm trying to debug an Angular Application and every time i try to inspect the value of a variable inside the html template, i can't see the value. 

This just happen on template, inside of the component itself, i can watch the values inside the variable.

Is it possible to debug inside html template on Angular with this tool?

**Comment by connor4312** [comment]
You could write an extension that does this via `vscode.languages.registerEvaluatableExpressionProvider`
