### ISSUE TITLE
Container breakpoints occasionally marked invalid (but still hit)

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-js-debug#144]
Using `vscode-remote-try-node` container:

Set breakpoint in the handler for:
```js
const app = express();
app.get('/', (req, res) => {
	console.log("hello");
	res.send('Hello remote world!\n');
});
```

It will (sometimes) get shown as unbound. However, upon navigating to the page it will still be hit. I was not able to repro outside of a container.

**Comment by connor4312** [comment]
I think this is an issue in VS Code core. What I'm seeing is that:

 1. The 'stubbed' parent debug session gets a setBreakpoints request. It returns unverified BP (and never verifies them).
 2. The child debug session gets a setBreakpoints request. It also initially returns the BPs as unverified,
 3. then a few milliseconds later (once we get confirmation from CDP) the child verifies them.

I think the correct behavior is for the BP to show as verified if any debug session verifies them, and this usually works. So I suspect there's some timing issue in vs code itself here.

cc @isidorn -- I'm able to get a fairly easy repro with Jackson's steps. [Here's a gist](https://gist.github.com/connor4312/3b4ba2784bbf9e14de9f1cc7d2800fac) you can plug into [our tool](https://microsoft.github.io/vscode-pwa-analyzer/index.html) if you want to look at the messages.

**Comment by isidorn** [comment]
I have heard similar complains from the Java team. Please check out this comment [here](https://github.com/microsoft/vscode/issues/83743#issuecomment-563894120), Jinbo will create a new issue and I plan to investigate then. If he does not can you create an issue in vscode. Thanks

**Comment by connor4312** [comment]
Tracking in https://github.com/microsoft/vscode/issues/86749
