### ISSUE TITLE
Is debugging Chrome Extension Service Worker supported?

### ISSUE THREAD

**Issue by albertusdev** [microsoft/vscode-js-debug#1445]
Hi! Great work on this Extension!

Is it possible to debug (add a breakpoint, etc) on Chrome Extension Service Worker scripts?
I've successfully managed to get the breakpoint and debugger working for content scripts since those run on each tab and the this vscode-js-debug can attach to each tab Chrome debugger.

But is it possible to debug/attach to each service worker available on the attached Chrome?

**Comment by natan-shaltiel** [comment]
I'm also looking for a way to enable it,
It seems that there was a pull request that enabled expanding the filter currently being used by setting targetTypes (https://github.com/microsoft/vscode-chrome-debug/pull/727) but the config doesn't seem to be working anymore

**Comment by spookyuser** [comment]
Pls 😢

**Comment by horihiro** [comment]
I found that the following steps can achive to inspect Chrome Extension Service Worker.
In this way, 2 Chrome windows are needed.

1. Start debug with <kbd>F5</kbd>, then Chrome launches (`window1`).
2. Press <kbd>Ctrl</kbd> + <kbd>n</kbd> to open new Chrome window (`window2`) and navigate `chrome://extensions` in `window2`
3. Make sure that the service worker of the extension you are developing is **in**active.      
  ![image](https://github.com/microsoft/vscode-js-debug/assets/4566555/0f572cf3-f7e9-46c1-899c-2806352b3b5d)  
  If the service worker is active, you wait until the service worker becomes inactive (up to 30 seconds).
4. Open a popup window of your extension on `window2`, then DevTools for the popup opens automatically.
5. Click `Application` tab of the DevTool and make sure if information of the service worker is displayed.  
  ![image](https://github.com/microsoft/vscode-js-debug/assets/4566555/dd531acf-8d13-401b-875b-8005be38942d)
6. Click `start` link in `status` line and close the DevTool (NOT the popup)
  ![image](https://github.com/microsoft/vscode-js-debug/assets/4566555/bd54d939-681e-4642-a6af-cae567106e1d)

 
Then VSCode attaches to the service worker, breakpoints on VSCode can pause the service worker script.
In `CALL STACK` of VSCode, you can see the service worker as a child of the popup.
![image](https://github.com/microsoft/vscode-js-debug/assets/4566555/2fba3ca3-604a-4843-8229-050aca655a3f)

> **Note**
> During inspection of the service worker, it needs to keep the popup on `window2` open though you can manipulate `window1` for debugging.
> This is the reason why new Chrome window is created at step 2.

**Comment by spookyuser** [comment]
Omg thank youu @horihiro !

**Comment by HppZ** [comment]
`I've successfully managed to get the breakpoint and debugger working for content scripts`

how to get breakpoint in conent script work? @albertusdev
