### ISSUE TITLE
Troubleshoot your launch configuration

### ISSUE THREAD

**Issue by kanha91** [microsoft/vscode-js-debug#1447]
> **Describe the bug**

**To Reproduce**

**Log File**

Unbound breakpoint

 Some of your breakpoints could not be set. If you're having an issue, you can [troubleshoot your launch configuration](vscode-file://vscode-app/c:/Users/Admin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html).

debugger not work on node js in vs code please heip

**VS Code Version:** Replace me!

**Additional context**

![image](https://user-images.githubusercontent.com/54071847/202443956-f2e5111d-83e0-407b-bcaf-a9a30d76e67c.png)

![image](https://user-images.githubusercontent.com/54071847/202444479-a9600c03-3b5f-42e7-9509-47d1e9e1dc71.png)

**Comment by connor4312** [comment]
Please provide more information about the problem you're facing, such as the debug logs requested in the issue template.

**Comment by kanha91** [comment]
Yes
I am facing issue when we start with node js , but debugger not attach.

troubleshoot your launch configuration
<vscode-file://vscode-app/c:/Users/Admin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html>
When available please share some time with me to resolve this issue.

**Comment by kanha91** [comment]
Ok, thanks.

**Comment by connor4312** [comment]
Please provide the debug logs requested in the issue template.
