### ISSUE TITLE
Help with breakpoints/source mapping

### ISSUE THREAD

**Issue by farnasirim** [microsoft/vscode-js-debug#1451]
**Describe the bug**

**To Reproduce**
1. Clone https://github.com/farnasirim/vscode-debug-repro
2. Open the top level workspace.
3. Go to `tsdebug` subproject/folder. `npm i`, and then `npm start`. Note the `start` script in the webpack config.
4. Using the launch config or `Debug: Open link` action open `https://localhost:8080`.
5. Observe that source mapping (e.g. clicking on console log source after clicking on the button) leads to a readonly page with content
```
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
function main() {
    return __awaiter(this, void 0, void 0, function* () {
        const button = document.createElement("button");
        button.onclick = () => {
            console.log("one");
            console.log("two");
            console.log("three");
        };
        button.innerText = "debug";
        document.getElementById("root").appendChild(button);
    });
}
document.onreadystatechange = function () {
    if (document.readyState == "complete") {
        main();
    }
};


//# sourceURL=webpack://tsdebug/./src/index.ts?
```
Instead of the actual source file and that breakpoints do not function.

**Log File**

[vscode-debugadapter-52936667.json.gz](https://github.com/microsoft/vscode-js-debug/files/10053250/vscode-debugadapter-52936667.json.gz)

**VS Code Version:**
```
1.72.2                                    
d045a5eda657f4d7b676dedbfa7aab8207f8a075  
x64                                       
```

**Additional context**

I have tried as many sensible (to me) `webRoot` and `sourceMapPathOverrides` combinations as I could think of, based on docs, other issues, and my intuition and have read through the trace. No progress in any of these cases.

On a related note, does it matter where I put the launch configs? E.g. in the `.code-workspace`, in `.vscode` in project root, or under `tsdebug/.vscode`? (I have tried all of these as well)

**Comment by connor4312** [comment]
You do not have sourcemaps enabled in the TypeScript compiler, so the code Webpack bundles is the compiled code, not your actual source code: https://github.com/farnasirim/vscode-debug-repro/blob/57ab5c4a07b9d5b214529830976b33396dd33ec0/tsdebug/tsconfig.json#L50

**Comment by farnasirim** [comment]
This does not affect what I observe. https://github.com/farnasirim/vscode-debug-repro/blob/main/tsdebug/tsconfig.json#L50 What else can I probe?

**Comment by farnasirim** [comment]
@connor4312 Would you please reopen this to avoid duplication?

**Comment by connor4312** [comment]
You will also want to set your `devtool: "source-map"` by default Webpack uses `eval` maps which map only to generated code.

Please see this page for more information: https://webpack.js.org/configuration/devtool/

**Comment by farnasirim** [comment]
Fantastic, this did it, if I may ask, what lead you to this conclusion?

One more thing: I know I am picking nits here now, but when I set a breakpoint on the already running application I it does not seem to trigger until I force a restart. Is this expected? `Diagnose breakpoint problems` doesn't complain.
