### ISSUE TITLE
debugWithChrome / chrome launch tasks doesn't keep JavaScript breakpoints bound when launching or through page reloads

### ISSUE THREAD

**Issue by barrycburton** [microsoft/vscode-js-debug#1456]
**Describe the bug**

When using the debugWithChrome serverReadyAction on a Java server launch task or when using a chrome launch task to independently debug the webpage, breakpoints set before launch become unbound during launch. Also breakpoints set after launch come unbound when the browser is reloaded. This makes it impossible to debug JavaScript that runs on page load in VSCode. My server does not bundle or minify the JavaScript so no source maps are needed. Setting a breakpoint after the server and chrome debug session are launched works as expected until the browser is reloaded.

**To Reproduce**

1. Set a breakpoint in a plain JavaScript file
2. Either launch a Java server task with a debugWithChrome serverReadyAction or launch a Chrome debug task or refresh the browser in an already running and attached Chrome debug session. In any case plain JavaScript files must be correctly mapped using the `webRoot` property.

Expected: breakpoint remains bound and pauses execution when reached

Actual: breakpoint becomes unbound and by clicking on it I get the following error message:

> Unbound Breakpoint
> 
> Some of your breakpoints could not be set. If you're having an issue, you can \<troubleshoot your launch configuration\>.

If I then click on \<troubleshoot your launch configuration\> I am shown the following more detailed error message which makes it sound like everything is correct-

> - This breakpoint was initially set in:
>     /Users/barry/Workspace/Paging/src/main/resources/paging.js line 20 column 1
> - We couldn't find a corresponding source location, but found some other files with the same name:
>     /Users/barry/Workspace/Paging/src/main/resources/paging.js
> You may need to adjust the webRoot in your launch.json if you're building from a subfolder, or tweak your sourceMapPathOverrides.

**Log File**

[vscode-debugadapter-80e3cade.json.gz](https://github.com/microsoft/vscode-js-debug/files/10094297/vscode-debugadapter-80e3cade.json.gz)

**VS Code Version:** 1.73.1

**Additional context**

I'm fairly certain several other people have reported this exact issue but filing a new bug report because their reports were not detailed and did not include log files.

**Comment by connor4312** [comment]
You have pathMapping like this:

```
{
  "/paging.js": "/Users/barry/Workspace/Paging/src/main/resources/paging.js"
}
```

However, this is not where paging.js is served from, it's served from `/static/paging.js`. The debugger is therefore attempting to set a breakpoint at `localhost꞉8080/paging.js`, which never gets bound.

Your webRoot is already correct, so breakpoints should work if you just remove the pathMapping.

**Comment by barrycburton** [comment]
I tried many permutations of pathMapping including "/static/paging.js" and not having a pathMapping entry at all. The bug reproduces the same in all of the cases. Breakpoints work great as long as they are set after launch and as long as the browser is never reloaded.

Here is a new trace with the pathMapping entry removed, just relying on webRoot. The behavior of breakpoints becoming unbound on launch and on browser reload is the same-

[vscode-debugadapter-f08199b6.json.gz](https://github.com/microsoft/vscode-js-debug/files/10094545/vscode-debugadapter-f08199b6.json.gz)

**Comment by connor4312** [comment]
Ah, sorry. Try setting `pathMapping: { "/static": "${workspaceFolder}/src/main/resources" }`

**Comment by barrycburton** [comment]
That works, thanks so much!
