### ISSUE TITLE
Debugger does not terminate

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode-js-debug#1457]
Code_-_Insiders_nhIB4f0JvB.gif
![Code_-_Insiders_nhIB4f0JvB](https://user-images.githubusercontent.com/2931520/204111274-3e2580de-7870-489b-adcc-762b0d974eb4.gif)

Happens randomly, no clear reproduction steps.
Happens maybe every 20th-40th debug session.

Only reloading VS Code gets me out of this.

This session was started from the JavaScript Debug Terminal.
But it also happens when debugging Code OSS.

**Comment by connor4312** [comment]
Are there any errors/logs in the Console when this happens?

**Comment by hediet** [comment]
I will check the next time, but I don't think so. You never ran into that issue?

**Comment by hediet** [comment]
It could be this:

image.png
![image](https://user-images.githubusercontent.com/2931520/204302626-350abfc4-80a5-481a-a34f-366503dca3b0.png)

Which is super weird, as I have 64GB of memory...

**Comment by connor4312** [comment]
That would do it. If the extension host died, then debugging does get stuck. This is a bug but not one we have spent a lot of time on...

**Comment by connor4312** [comment]
You might be running into https://github.com/github/copilot/issues/2360 which it seems several people have hit recently

**Comment by hediet** [comment]
Would be cool if the crash/freeze of the extension host would be shown somehow.

But I guess this issue most likely has nothing to do with the debug adapter.
