### ISSUE TITLE
Apply glob negations if glob is navigated outside workspace folder

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#1479]
> The glob behavior is something we can improve, automatically applying it if we see a relative pattern navigates outside the workspace folder.

https://github.com/microsoft/vscode/issues/169033?notification_referrer_id=NT_kwDOACIKybI1MDc5ODA3NTU5OjIyMzA5ODU#issuecomment-1352030679

**Comment by andreamah** [comment]
are there some verif steps for this?

**Comment by connor4312** [comment]
Use the steps in https://github.com/microsoft/vscode/issues/169033, **but** before step 5, modify the launch.json by adding the following property to the Attach by Process ID configuration:

```
"outFiles": [
	"${workspaceFolder}/**/*.js",
	"${workspaceFolder:common-external}/**/*.js",
	"!**/node_modules/**"
],
```

Then, you should be able to have breakpoints bind in all the files.
