### ISSUE TITLE
Debugging Angular 15 with the Angular Recipe and Node 18 , nor 19 works

### ISSUE THREAD

**Issue by Bjego** [microsoft/vscode-js-debug#1493]
**Describe the bug**
Dear VS Code JS Debug team, I started working with an angular project and I tried to get the VS Code debugging up and running with your recipes ( and several other sources from the web) - It didn't work.

When I downgraded my nodejs installation to 16.9.0 it just works. 

You can use my angular tutorial code: https://github.com/Bjego/angular-tutorial

I am working on Windows 10.

**To Reproduce**
1. Install current LTS of NodeJs (or the current version)
2. Scaffold an Angular-project
3. Prepare debugging as described here: https://github.com/microsoft/vscode-recipes/tree/main/Angular-CLI
4. Set a breakpoint
5. Try to debug
6. The breakpoints aren't hit and loading the .map files from ng serve errors out with 503 (You can see that in the debug log)

**Log File**
Don't have it but one term was:

unexpected 503 response from http://127.0.0.1:4200/styles.js.map

**VS Code Version:** 1.74.2 (User)

**Additional context**
Thanks & merry christmas!

**Comment by Bjego** [comment]
The current workaround is to install NodeJs 16.9.0

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/167353
