### ISSUE TITLE
TpeError: Cannot read properties of undefined (reading 'toString')

### ISSUE THREAD

**Issue by phortonssf** [microsoft/vscode-js-debug#1502]
**Describe the bug**
When starting the debugger node vsDebugServer.js 
 I get the following error.
```
[dap-js] JS Debugger stderr:
[dap-js] JS Debugger stderr: ~/.local/share/nvim/site/pack/packer/opt/vscode-js-debug/src/vsDebugServer.ts:93
    console.log((result.server.address() as net.AddressInfo).port.toString());
                                                                 ^
TypeError: Cannot read properties of undefined (reading 'toString')
    at VsDebugServer.launchRoot (~/.local/share/nvim/site/pack/packer/opt/vscode-js-debug/src/vsDebugServer.ts:93:66)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

[dap-js] JS Debugger exited with code 1!
```
**To Reproduce**
1. Installed latest and uzzipped the lates build, 1.74.1 
2. ran npm install and npm run compile
3.  tsc --version
Version 4.9.3

node -v
v18.12.1

**Comment by phortonssf** [comment]
I tried **vscode-js-debug-1.72.0** and it worked fine, note i didn't try anything between **1.72.0** and **latest 1.74.1.**

**Comment by revmischa** [comment]
I'm seeing the exact same. 1.72.0 works, latest version gives me the port undefined error

**Comment by Saco93** [comment]
> Fixed in [749f75d](https://github.com/microsoft/vscode-js-debug/commit/749f75d6b26a5bf830c48b447090304c7ca421f5)

I'v updated to the latest commit(cf0888942de535bc9bac4c1f3824d783c21b0f38), still get the same error.
```log
[dap-js] JS Debugger stderr:                                                                                               
[dap-js] JS Debugger stderr: /Users/sacosong/.local/share/nvim/site/pack/packer/opt/vscode-js-debug/src/vsDebugServer.ts:95
                                                                                                                           
    console.log((result.server.address() as net.AddressInfo).port.toString());                                             
                                                                                                          ^                                                         
TypeError: Cannot read properties of undefined (reading 'toString')                                                        
    at VsDebugServer.launchRoot (/Users/sacosong/.local/share/nvim/site/pack/packer/opt/vscode-js-debug/src/vsDebugServer.ts:95:66)                                                                                                                   
    at processTicksAndRejections (node:internal/process/task_queues:95:5)                                                  
[dap-js] JS Debugger exited with code 1! 
```

**Comment by artemave** [comment]
I am seeing the same as @Saco93 (on v1.75.0)

**Comment by connor4312** [comment]
Can you please verify what arguments you're launching the script with?

**Comment by jessevanassen** [comment]
[nvim-dap-vscode-js](https://github.com/mxsdev/nvim-dap-vscode-js), which is where the above reports are coming from, isn't calling the script with any arguments.

[It's starting the script here](https://github.com/mxsdev/nvim-dap-vscode-js/blob/v1.1.0/lua/dap-vscode-js/utils.lua#L90-L102), getting the command and args from [`get_spawn_cmd`](https://github.com/mxsdev/nvim-dap-vscode-js/blob/v1.1.0/lua/dap-vscode-js/utils.lua#L57-L67). The `cmd` is the absolute path to Node, and the only argument is the path to vsDebugServer.js, so no additional arguments are passed.

**Comment by rzhao271** [comment]
What are some verification steps for this issue?

**Comment by connor4312** [comment]
1. Clone js-debug, npm install
2. Run `gulp vsDebugServerBundle`
3. Run `node out/src/vsDebugServer.js`
4. Verify that it prints a number to your console (instead of erroring)
