### ISSUE TITLE
Launch debug throws error when using c8 module

### ISSUE THREAD

**Issue by ullumullu** [microsoft/vscode-js-debug#1507]
When launching in a Typescript/Javascript the debugger the following error crops up:

```
Error in the js-debug bootloader, please report to https://aka.ms/js-dbg-issue: Error [ERR_INSPECTOR_ALREADY_ACTIVATED]: Inspector is already activated. Close it with inspector.close() before activating it again.
    at new NodeError (internal/errors.js:322:7)
    at Object.inspectorOpen (inspector.js:137:11)
    at bootloader.bundle.cdp:2:91827
    at bootloader.bundle.cdp:2:93164
    at Object.7207 (bootloader.bundle.cdp:2:93364)
    at __webpack_require__ (bootloader.bundle.cdp:2:99718)
    at bootloader.bundle.cdp:2:99871
    at Object.<anonymous> (bootloader.bundle.cdp:2:99898)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
```

I was able to confirm that the problem is caused/related to the usage of [c8](https://www.npmjs.com/package/c8). 

launch.json:

```
    {
      "type": "node",
      "request": "launch",
      "name": "Test Current File",
      "cwd": "${workspaceFolder}",
      "skipFiles": ["<node_internals>/**"],
      "runtimeExecutable": "npx",
      "runtimeArgs": ["c8", "--reporter=lcov", "--reporter=text", "mocha", "${file}"],
      "outputCapture": "std",
      "env": {
        "NODE_ENV": "development"
      }
    }
```

**To Reproduce**
1. Setup launch.json in a project using c8 and mocha 
2. Create a simple mocha test
3. Run it from the Debug Launcher

**Log File**

I have taken a trace file - it would be possible to send it via mail if needed.

**VS Code Version:** 

Version: 1.74.1 (Universal)
Commit: 1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a
Date: 2022-12-14T10:33:40.793Z (3 wks ago)
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 22.2.0
Sandboxed: No

**Additional context**

**Comment by connor4312** [comment]
Looks like this is a quirk in Node.js when NODE_V8_COVERAGE is used. I've opened an issue here: https://github.com/nodejs/node/issues/46110

If you run your tests without coverage (i.e. in mocha directly) you will not receive this error. Will wait for the Node.js team to weigh in since the workaround is not super trivial.

**Comment by connor4312** [comment]
Node.js fixed this in https://github.com/nodejs/node/commit/7b4cc58b70a7679a7ce0c244b6d083438b8d6c22. No changes are necessary in js-debug to support this.
