### ISSUE TITLE
Breakpoints not binding in language server protocol extension

### ISSUE THREAD

**Issue by gee4vee** [microsoft/vscode-js-debug#1509]
**Describe the bug**
We are building our LSP extension using the [sample](https://github.com/microsoft/vscode-extension-samples/tree/main/lsp-sample) as a basis. Breakpoints are binding successfully for code in the client folder but not in the server folder. Our launch configs are very similar to the ones in the sample and all our typescript gets compiled into the out folder.

**To Reproduce**
1. Clone the lsp-sample linked above.
2. Add a breakpoint to a line in `server/server.ts`.
3. Run the `Language Server E2E Test` launch config.
4. Breakpoint does not get hit.
5. Check the breakpoint's debug diagnostics. Only a small portion of client files are loaded.

**Log File**

[vscode-debugadapter-a4b1ccf8.json.gz](https://github.com/microsoft/vscode-js-debug/files/10356338/vscode-debugadapter-a4b1ccf8.json.gz)

**VS Code Version:**

Version: 1.74.2 (Universal)
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:26:09.430Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 22.1.0
Sandboxed: No

**Additional context**

**Comment by connor4312** [comment]
You will want to set `"autoAttachChildProcesses": true` in your launch config in order to debug child processes.
