### ISSUE TITLE
Incorrect error reporting of bad `cwd` in DAP launch

### ISSUE THREAD

**Issue by gfszr** [microsoft/vscode-js-debug#1517]
**Describe the bug**
Upon receiving a launch configuration, `vscode-js-debug` tries to check for the target `node`'s version:
https://github.com/microsoft/vscode-js-debug/blob/175d9120d25005db7a66a2a67317c8ce406a6c6f/src/targets/node/nodeBinaryProvider.ts#L300

The problem here is that if the `cwd` of the configuration is a non-existing directory, the returned error looks like this:

![image](https://user-images.githubusercontent.com/99412607/212852844-a0754352-5f6a-4f17-b11e-e3ba11a5ef98.png)

which isn't accurate (the error that should be presented is in the invalid `cwd`). 

This can be solved either by better parsing the error when trying to execute the version, or the easiest solution IMO: just checking that `cwd` is correct and pointing to a valid directory beforehand. The latter actually does happen but in the VSCode extension, not the debug adapter which can be standalone. 

**To Reproduce**
A bit hard as the VSCode extension itself validates `cwd`, so a needed setup for this to work is using a different DAP-compatible editor.

**Comment by connor4312** [comment]
PR's welcome
