### ISSUE TITLE
Toggling auto attach gives an error and a non-spinning status bar item

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-js-debug#1519]
Running the toggle auto attach command gives this:

<img width="128" alt="image" src="https://user-images.githubusercontent.com/2193314/212908391-5cd0d339-550b-4aa8-89a8-932d62e93aa3.png">

<img width="230" alt="image" src="https://user-images.githubusercontent.com/2193314/212908468-0dfbe9d3-5375-4651-93cb-eb3049dbf6bf.png">

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-js-debug/issues/1520
