### ISSUE TITLE
Error: hash.bundle.js process unexpectedly exited

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-js-debug#1520]
First debug session today I saw this:

<img width="437" alt="image" src="https://user-images.githubusercontent.com/2193314/212910577-df17849a-2e90-45f6-a767-995656aec770.png">

Version: 1.75.0-insider (user setup)
Commit: 1379f0375440df946adc62f7afb8375dd45d5adf
Date: 2023-01-17T05:21:07.217Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

JavaScript Debugger (Nightly)
v2023.1.1617

**Comment by Tyriar** [comment]
<img width="521" alt="image" src="https://user-images.githubusercontent.com/2193314/212919095-aeead300-350b-4be5-98cb-f18734baf0b2.png">

**Comment by connor4312** [comment]
Fixed in https://github.com/microsoft/vscode-js-debug/pull/1521
