### ISSUE TITLE
Can't copy `watchdog.js` because it doesn't exist in Nightly version

### ISSUE THREAD

**Issue by yume-chan** [microsoft/vscode-js-debug#1522]
**Describe the bug**
When opening a folder, VSCode show a notification like this:

```
ENOENT: no such file or directory, copyfile 'c:\Users\simon\.vscode-insiders\extensions\ms-vscode.js-debug-nightly-2023.1.1617\src\bootloader.js' -> 'c:\Users\simon\AppData\Roaming\Code - Insiders\User\workspaceStorage\9d4000f75dd35d0e77394ad500a55aef\ms-vscode.js-debug-nightly\bootloader.js'
```

**To Reproduce**
1. Install the Nightly version
2. Open a JavaScript project

**Log File**

**VS Code Version:** 

```
Version: 1.75.0-insider (user setup)
Commit: 1379f0375440df946adc62f7afb8375dd45d5adf
Date: 2023-01-17T05:21:07.217Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.25276
Sandboxed: Yes
```

**Additional context**

Extension version: v2023.1.1617

As https://github.com/microsoft/vscode-js-debug/pull/1515#issuecomment-1385704343 said:

> The bootloader file is still bootloader.bundle.js in the built VSIX... But this PR changed it to bootloader.js, the extension now fails to find it.

There is only `bootloader.bundle.js` in `'c:\Users\simon\.vscode-insiders\extensions\ms-vscode.js-debug-nightly-2023.1.1617\src` folder.

This issue also happens to the `watchdog.bundle.js` vs `watchdog.js` file.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-js-debug/issues/1520
