### ISSUE TITLE
Symbol.isStringTag shows as undefined

### ISSUE THREAD

**Issue by pflannery** [microsoft/vscode-js-debug#1525]
When trying to evaluate `Symbol.toStringTag` in the debug variables section the value is shown as `undefined`
![image](https://user-images.githubusercontent.com/1727302/213753068-5c85bff1-3b75-49f3-8575-9e164d576534.png)

but it's not actually undefined when I run `new TestPropertyType()[Symbol.toStringTag]` in the debug console.

![image](https://user-images.githubusercontent.com/1727302/213752244-ec6e283b-83dc-4b15-824e-a71966c4a307.png)
![image](https://user-images.githubusercontent.com/1727302/213752322-3a916112-c32b-48d4-b3a1-600273ed4893.png)

I think this is happening because vscode (or node?) is treating it as a function because the tooltip in the debug variable section shows the word `function`

Just clarify Mozilla states we can use getters for Symbol.toStringTag
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toStringTag

```js
// contrived class example
class TestPropertyType {
  constructor(args) {  }
  get [Symbol.toStringTag]() {
    return TestPropertyType.name;
  }
}
```

VS Code Version: 1.74.3
Node Version: 18.13.0

**Comment by jrieken** [comment]
There is no clear repro steps here, so I am poking in the dark, but I don't believe this is working. Using the sample above and drilling into the property I still see `undefined`

<img width="1146" alt="Screenshot 2023-02-22 at 11 12 33" src="https://user-images.githubusercontent.com/1794099/220589857-fec81f2b-14ca-42ee-a2ef-ea0b712dc059.png">

**Comment by connor4312** [comment]
Please make sure to use the nightly build of the debugger if you verify before I bump the version in the next Insiders
