### ISSUE TITLE
Variable renamed incorrectly, leading to thrown error 

### ISSUE THREAD

**Issue by jakebailey** [microsoft/vscode-js-debug#1542]
**Describe the bug**

When debugging the TS codebase (which is bundled with esbuild), I periodically hit cases where the variable name I'm using in the debug console doesn't work and ends up throwing.

**To Reproduce**
1. Clone https://github.com/microsoft/TypeScript, npm install, etc
2. Set breakpoint on the line after `const links = ...` in `getTypeOfVariableOrParameterOrProperty` in checker.ts.
3. With `.vscode/launch.template.json` copied to `.vscode/launch.json`, open `2dArrays.ts` and run the test via the "mocha tests" launcher.
4. Once the breakpoint is hit, open the debug console and type `links`.
5. Note the stack trace which mentions `links2`.
6. Disable source mapped stepping; note the variable is called `links`, not `links2`, and now the debug console works.

**Log File**

[vscode-debugadapter-07d5029d.json.gz](https://github.com/microsoft/vscode-js-debug/files/10561633/vscode-debugadapter-07d5029d.json.gz)

**VS Code Version:** 1.74.3 with debugger v2023.1.3017

**Additional context**

Also, the error that's thrown bypasses #1259, somehow; the error is huge.

**Comment by connor4312** [comment]
I think we may try to rename `node` in the parameter, which is not correct. Will check on that

Renames are not AST-aware, we just try to get the closest rename. In general I _really_ want to avoid having to parse source AST's. Maybe it's sufficient to generate a set of fallbacks, like `typeof links2 === 'undefined ? (typeof links1 === 'undefined' ? links : links1) : links2`. Renames that share the underlying source name will usually be a result of shadowing, and thus the non-relevant `links` aliases won't be available in that scope since they wouldn't have been used...

**Comment by jakebailey** [comment]
To be clear, you mean avoiding parsing the AST of the debug console input? I would expect that to always be small so not actually expensive in practice.

> Maybe it's sufficient to generate a set of fallbacks, like `typeof links2 === 'undefined ? (typeof links1 === 'undefined' ? links : links1) : links2`.

That set of fallbacks won't work if the variable happens to be undefined already, though.

I'm a little confused, though; in this case, node is not something that's actually in scope, so why is it getting a renaming at all? This to me sounds like the first part of the issue where it's spuriously using the name `links2`.

**Comment by connor4312** [comment]
We do parse debug console input, but we don't parse sources in the runtime. Sourcemaps just say "the thing at this location is now named something else", so to deal with renames we just pull the closest rename to the current stackframe for each identifier we find in the evaluate input.

> That set of fallbacks won't work if the variable happens to be undefined already, though.

_If_ only one of the aliases is defined, it would still return undefined. Alternatively we could do a big try/catch to access each variable. Which would probably be fine...

> node is not something that's actually in scope

If it's anywhere in the source before the current stackframe, we'll try to rename it.

**Comment by jakebailey** [comment]
Hm, I guess I thought that the info from whatever powers the "variables" panel was in use here, since that seems to have the up-to-date scope information.

**Comment by connor4312** [comment]
Yea, we could be a bit smarter about not renaming things that aren't in `scopes`. But, assuming we don't rename things in a way that generates invalid syntax, renaming things that are contained within the REPL input should be harmless. `const node=42;console.log(node)` turning into `const node2=42;console.log(node2)` for example.

**Comment by jakebailey** [comment]
I suppose that's true, but you'd have to be careful about something like `(node, node2) => node + node2` and similar, and I'm not quite sure how to do that without moving past a simple replacement.

**Comment by connor4312** [comment]
> This also appears to be related; when at the same breakpoint (and anywhere in debugging, really), if I write:
> 
> ```ts
> (node) => node
> ```
> 
> Into the debug console, I get:
> 
> > Uncaught SyntaxError SyntaxError: Malformed arrow function parameter list
> 
> But disabling source mapped stepping makes the problem go away.

For me, doing that generates `(renamedIndentifier) => typeof renamedIdentifier === 'undefined' ? node : renamedIdentifier`. Which, regardless of the merits, is syntactically valid. Could you grab a trace log so I can see how it's getting transformed for you?

**Comment by connor4312** [comment]
I played with actually doing the parsing. As expected, it can be slow for large files. But if I put it in a worker, it should be okay: https://github.com/microsoft/vscode-js-debug/pull/1548

**Comment by jakebailey** [comment]
Here's a trace log of the `(node) => node`:

[vscode-debugadapter-9e1ab71a.json.gz](https://github.com/microsoft/vscode-js-debug/files/10583744/vscode-debugadapter-9e1ab71a.json.gz)

**Comment by jakebailey** [comment]
Wow, very odd, it's transforming it to:

```
(node2.kind => typeof node2.kind !== "undefined" ? node2.kind : node);
```

**Comment by connor4312** [comment]
Ahh, yep, that would do it. We added support for member access renames, but I didn't update the replacer to account for that.

**Comment by jakebailey** [comment]
I'm hitting what I think is still this bug more and more. For example, I was debugging our parser and wanted completions on the scanner but didn't get any. Checking the varible, the debug console instead gave me entirely the wrong thing entirely; compare source mapped versus not.

![image](https://user-images.githubusercontent.com/5341706/217613543-ee163f68-a436-4ccc-98d2-2f40c6a467f5.png)

I think @andrewbranch hit a case just like this with hover yesterday afternoon.

**Comment by andrewbranch** [comment]
Yep, I spent like 20 minutes trying to figure out why something was `undefined` when it turned out to be a hover showing me the value of a completely different variable 😦

**Comment by connor4312** [comment]
I'm on vacation currently and for the duration of next week, so this will not be fixed immediately, but soon.

My current thinking is that I still _really_ dislike parsing the AST of compiled code. Even in a worker, taking a second to do that means an (extra) second of delay before variables are available, for instance. One thing I'm considering is writing a parser that:

1. Parses JavaScript string sytax and
2. Tracks braces and parenthesis to generate rename scopes

(or use a lexer that can do this; currently we use acorn for parsing and manipulation, but it doesn't have a 'parse-only' mode)

**Comment by jakebailey** [comment]
So far the best workaround I've had is to follow the instructions to install nightly, then downgrade the nightly verison to `v2022.12.1317`. This version doesn't appear to have the bug, but does thankfully contain the performance optimizations needed to make debugging responsive in the TypeScript repo.

**Comment by andrewbranch** [comment]
Here’s another interesting one; apparently it’s not just renaming identifiers; I don’t know what it’s doing but it’s mangling the syntax here

<img width="810" alt="image" src="https://user-images.githubusercontent.com/3277153/217935166-ec04a2cb-b804-4bda-baa5-7a33fde21b63.png">

**Comment by jakebailey** [comment]
Yeah, I think that one is somewhat the same as: https://github.com/microsoft/vscode-js-debug/issues/1542#issuecomment-1416537774

**Comment by connor4312** [comment]
Looked at a few solutions. Using swc in webassembly is a bit faster than Acorn's parser, running 2.5 ops/s instead of acorn.parse()'s 0.9 ops/s for TypeScript's `run.js`. But it also is a decently sized wasm file (350KB / 150KB gzipped).

In my search I found https://github.com/guybedford/es-module-lexer, which is a lexer dedicated to the purpose of extracting import/export statements. It's widely used (12M downloads/month), tiny, and incredibly fast, handling run.js at _1,500,00 ops/s_. My plan is to fork and repurpose that module for extracting the relevant information we need for scopes.

**Comment by jakebailey** [comment]
Given a user's going to also have the TypeScript extension running, I wonder if it'd be possible to grab the info from there instead, given it should be already done and unlikely to change (so maybe quick).

**Comment by jakebailey** [comment]
Although I guess these are output files so they wouldn't be immediate. I am curious about our parser's perf, of course.

**Comment by connor4312** [comment]
This is gone in https://github.com/microsoft/vscode-js-debug/pull/1566

**Comment by jakebailey** [comment]
Thanks! Looking forward to the next nightly or stable so I can try it out.
