### ISSUE TITLE
breakpoint on a wrong line

### ISSUE THREAD

**Issue by apanchati** [microsoft/vscode-js-debug#1544]
**Describe the bug**
I installed https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug-nightly extension with below configurations.
After setting a breakpoint I run my application. When I reach the page its hitting the breakpoint but at the wrong line. Please let me know if I am missing some settings.

**launch.json**
{
  "configurations": [
    {
      "name": "Launch Edge",
      "request": "launch",
      "type": "msedge",
      "url": "https://localhost:3000",
      "webRoot": "${workspaceFolder}",
      "sourceMapPathOverrides": {
        "webpack://my-project-name/./src/*": "${webRoot}/src/*", // After updating to webpack 5, my-project-name was added to the path so we need to map it
        "webpack://my-project-name/./*.js": "${webRoot}/*.js"
      }
    },
  {
    "name": "Launch Chrome",
    "request": "launch",
    "type": "chrome",
    "url": "https://localhost:3000",
    "webRoot": "${workspaceFolder}",
    "sourceMapPathOverrides": {
        "webpack://my-project-name/./src/*": "${webRoot}/src/*", // After updating to webpack 5, my-project-name was added to the path so we need to map it
        "webpack://my-project-name/./*.js": "${webRoot}/*.js"
    }
  }
  ]
}

**VS Code Version:** 
Version: 1.74.3 (user setup)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

Regards,

**Comment by connor4312** [comment]
Please collect a log using the instructions in the issue template. Also, any information about your build setup or repo would be helpful. Most likely you have a misconfigured step in your build.

**Comment by apanchati** [comment]
can email the logs? and let me know which build setup you need? i won't be able to share everything because of the privacy and my company will not allow it. 

Thanks!

**Comment by connor4312** [comment]
Yes, you can email. Your webpack.config is a good start.

**Comment by apanchati** [comment]
FYI:
One of my team member have below extension and it's working with below config.
https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome

**launch.json**
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "legacy-chrome",
      "request": "launch",
      "name": "Chrome - CIS5",
      "url": "https://localhost:3000",
      "webRoot": "${workspaceFolder}",
      "userDataDir": "${workspaceFolder}/.chrome-vscode-debug-profile", // This setting retains the Chrome profile so that your Chrome settings are remembered. Otherwise, it will create a new one everytime you launch.
      "sourceMapPathOverrides": {
        "webpack://my-project-name/./src/*": "${webRoot}/src/*", // After updating to webpack 5, my-project-name was added to the path so we need to map it
        "webpack://my-project-name/./*.js": "${webRoot}/*.js"
      }
    },
  ]
}

**Comment by apanchati** [comment]
want to confirm if you got my email sent last Friday, February 3rd. The email contains webpack config and logs.

**Comment by apanchati** [comment]
@connor4312  any update on this? Thanks!

**Comment by connor4312** [comment]
Hi, apologies for the late followup, I was on vacation. I checked my inbox and spambox and I can't seem to find an email for this issue then. Could you resend it? Then I can look at it right away 🙂

**Comment by apanchati** [comment]
No worries. Hope you had a good vacation. I resend it and it's from my work email.

**Comment by connor4312** [comment]
Thanks for the log. It does look like some tool in your toolchain is generating bad sourcemaps, or messing them up in some way. The process the debugger goes through is that:

1. `app.js` gets parsed, and its sourcemaps map the breakpoint in `DoorOpeningsHistoryDialog.ts` to line 304488, column 288
2. Chrome/V8 then applies that breakpoint. In doing so, it binds that location to the nearest position a breakpoint can actually be set. That ends up being 304490 column 6
3. The debugger sees that, and tries to map that location back to where it should be in `DoorOpeningsHistoryDialog.ts` (or any other source)
4. 🐛 the sourcemap doesn't have any ranges that include that location, so the debugger falls back to showing the breakpoint at the compiled app.js

I would check for any loaders in `module.rules`, or plugins you might have, in your webpack config affecting that .ts which might not be sourcemap-aware, or might not be configured for receiving or generating sourcemaps.

**Comment by apanchati** [comment]
The two rules i have are below for TypeScript. We have .ts files and .vue file can contain TypeScript. The .vue files can have HTML, TypeScript, and SCSS.

`{
        test: /\.vue$/,
        use: [
          {
            loader: 'cache-loader',
            options: {
              cacheDirectory: path.resolve(__dirname, '../node_modules/.cache/vue-loader'),
              cacheIdentifier: '4c8f83fd'
            }
          },
          {
            loader: 'vue-loader',
            options: {
              cacheDirectory: path.resolve(__dirname, '../node_modules/.cache/vue-loader'),
              cacheIdentifier: '4c8f83fd',
              // getCustomTransformers: () => ({ before: [Vue] })
            }
          }
        ]
      },
      /* config.module.rule('ts') */
      {
        test: /\.ts$/,
        use: [
          {
            loader: 'cache-loader',
            options: {
              cacheDirectory: path.resolve(__dirname, '../node_modules/.cache/ts-loader'),
              cacheIdentifier: '156370e0'
            }
          },
          {
            loader: 'babel-loader'
          },
          {
            loader: 'ts-loader',
            options: {
              transpileOnly: true,
              appendTsSuffixTo: [
                '\\.vue$'
              ],
              happyPackMode: false,
              // getCustomTransformers: () => ({ before: [tsNameof] })
            }
          }
        ],
        exclude: [
          path.resolve(__dirname, '../node_modules'),
        ],
      },`

Regards,

**Comment by connor4312** [comment]
Using both `babel-loader` and `ts-loader` is suspicious to me. `babel-loader` needs to ensure that it does not create entirely new sourcemaps, but modifies the ones that the ts-loader emits. I don't know whether it does this; just doing a quick test, the Babel CLI does not (i.e. re-compiling a file that already has a sourcemap just references the compiled file rather than the source file).

You're already using `transpileOnly` in the ts-loader, it might make sense to have Babel do the TypeScript transpilation instead of ts-loader.
