### ISSUE TITLE
Activate exception handling after a condition is met

### ISSUE THREAD

**Issue by JeremyFunk** [microsoft/vscode-js-debug#1549]
## Problem: 
Debugging our monorepo requires manual disabling of caught exception handling and waiting for a breakpoint at the entrypoint to be reached. Then we have to turn on caught exception handling and can start debugging the application. Some dependencies throw thousands of caught exceptions during startup, causing a delay of over 60 seconds to reach the first breakpoint when caught exception handling is enabled (compared to the normal 3 seconds). The issue is not caused by slow skipFiles patterns.

## Feature Request:
Allow users to configure an entrypoint for exception handling through a setting such as `debug.javascript.skipExceptionHandlingToFirstBreakpoint: bool` and `debug.javascript.continueOnFirstBreakpoint: bool` to automatically continue execution upon hitting the first breakpoint.

## Alternative
If this solution is not feasible, please assist me in finding a way to enforce this behavior using an external extension. I built an extension to automatically continue the debugger when the first checkpoint is reached, but I can't figure enabling/disabling exception handling out. If I get this to work I can publish the extension as a workaround for the problem. There have been quite a few issues and posts about this problem on various platforms over the last two years, I think developers on projects with a high number of dependencies could benefit from an optional extension.

**Comment by connor4312** [comment]
Have you tried out [conditional exception breakpoints](https://github.com/microsoft/vscode/issues/104453#issuecomment-754267066)?

**Comment by JeremyFunk** [comment]
Conditional exception breakpoint work great but has the same performance penalty as skip files on startup. I assume there is some "slow" code that runs every time the debugger encounters a conditional error (probably still in the single digit millis, we just have an insane number of exceptions).
My idea of how it works is:

Debugger receives exception
Check if conditional breakpoint for the exception is enabled
Run some slow code
Check for skipFiles and conditional breakpoints
If both tests are successful, pause the debugger, else continue

I could easily write up a workaround for this if I could tell the debugger to enable/disable conditional breakpoints, but there don't seem to be any VSCode API commands for this. I can enable/disable non-exception breakpoints without problems. Can you give me a starting point of how I could implement this?

I tried basically all relevant API commands with expected payloads and used a debugAdapterFactory to read all communication and replicated the exact setExceptionBreakpoints requests sent when the conditional breakpoint is changed. I get the expected response back but it simply doesn't change the exception breakpoint. At this point the only option I see is to fork this extension and provide my own command to achieve this, but that is a very bad solution to something that should be easily possible.

### Implementation of conditional exception breakpoints
For anyone wondering how this could be implemented to see if it might be a fit in your case:
In your entrypoint you have to declare a global:
```
declare global {
  var finishedInitialization: boolean
}
```
At the point of the application where you want to start error handling you have to set this boolean to true:
`globalThis.finishedInitialization = true`
Then use `globalThis.finishedInitialization === true` as your conditional exception breakpoint.

**Comment by JeremyFunk** [comment]
Any updates on this?

**Comment by JeremyFunk** [comment]
In case anyone has a similar issue, I built an [extension](https://marketplace.visualstudio.com/items?itemName=JeremyFunk.debug-my-code) for this. It works exactly as expected, but might have unforeseen side-effects, as it intercepts, changes and creates messages between the debug adapter and VSCode UI. I tested it for a few days and I haven't seen any bad side-effects yet.
