### ISSUE TITLE
Breakpoints are greyed out using NestJS debug command

### ISSUE THREAD

**Issue by shubham-novo** [microsoft/vscode-js-debug#1551]
package.json script contains **"start:debug": "nest start --debug --watch"**

Ran yarn start:debug in Javascript Debug Terminal but breakpoints are greyed out.

**Comment by connor4312** [comment]
Please collect logs and provide information using the instructions in the "bug" issue template.

**Comment by shubham-novo** [comment]
My Bad, it is working now. Missed some DI imports.
