### ISSUE TITLE
`enableTurboSourcemaps: false` does not take effect from auto-attach settings 

### ISSUE THREAD

**Issue by artu-ole** [microsoft/vscode-js-debug#1553]
Specifying `enableTurboSourcemaps: false` in `debug.javascript.terminalOptions` in `settings.json` does not have an effect for auto attach debug configurations.
I have an issue with hitting breakpoints with nodejs auto attach 1.75.0 release and expected setting `enableTurboSourcemaps: false` in `debug.javascript.terminalOptions` to revert the source maps discovery mechanism, but unfortunately to no avail. Downgrading to 1.74.3 did the trick, but would be nice to have control over it for auto attach configurations in the new release as well.

**Comment by connor4312** [comment]
Thanks for the issue, but I do not plan to look into this, as the setting will be removed in the next 1-2 iterations anyways. However, please file a bug if you find a scenario where breakpoints don't bind as a result of this. The "bug" issue template has instructions for collecting relevant log files.
