### ISSUE TITLE
Cannot inspect variables correctly on v1.75.0 on debug

### ISSUE THREAD

**Issue by edmsamuel** [microsoft/vscode-js-debug#1555]
Version info with issue:
Versión: 1.75.0 (user setup)
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Fecha: 2023-02-01T15:23:45.584Z
Electrón: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.19044
En espacio aislado: No

[EN]
Hello, good afternoon.
We have this problem with the latest vscode update (version info at the beginning of the issue).

After upgrading we noticed that we couldn't inspect variables correctly (first gif), we thought it was some problem with our code, we modified webpack configuration and other files without success.

I don't know if this is a configuration problem or something, but I also tried `"enableTurboSourcemaps": false` which is indicated on the new version page, we also thought it was some conflict with the extensions so I uninstalled the current debuggers without succeed.

![Code_Oq0E5YqzSK](https://user-images.githubusercontent.com/14112893/217674772-1301cf41-2b64-4480-8524-d15acc9e25ec.gif)

So after several hours, I downgraded to the previous version available at: https://az764295.vo.msecnd.net/stable/97dec172d3256f8ca4bfb2143f3f76b503ca0534/VSCodeUserSetup-x64-1.74.3.exe

Which allows us to debug as we normally have been doing (second gif)

![Code_LKCrKxz8Q8](https://user-images.githubusercontent.com/14112893/217674957-21c278ec-b9de-4e9b-a55b-678f353905d3.gif)

If there's a way to fix this in the latest version, I'd appreciate if there's somewhere I can look up this information.
Thank you very much for the help and for this great development.

----

[ES]
Hola, buenas tardes.
Tenemos este problema con la ultima actualización de vscode (inf de versión al principio del issue). 

Después de actualizar notamos que no podiamos inspeccionar variables correctamente (primer gif), pensabamos que era algun problema con nuestro código, modificamos configuraciónes de webpack y otros archivos sin tener exito.

Desconozco si este sea un problema de configuración o algo, pero intenté también `"enableTurboSourcemaps": false` el cual se indica en la pagina de la nueva versión, también pensamos que era algun conflicto con las extensiones por lo que desinstalé los debuggers actuales sin tener exito.

Por lo que después de varias horas, hice downgrade a la versión anterior disponible en: https://az764295.vo.msecnd.net/stable/97dec172d3256f8ca4bfb2143f3f76b503ca0534/VSCodeUserSetup-x64-1.74.3.exe

La cual nos permite hacer el debug como normalmente lo veniamos haciendo(segundo gif)

Si hay forma de solucionar esto en la última versión, agradecería si hay algun lugar donde consultar esta información.
Muchas gracias por la ayuda y por este grandioso desarrollo.

**Comment by connor4312** [comment]
Thanks for the issue and gif. Can you grab logs using the instructions in the issue template so I can see what's going on?

> If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
> ⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by galdebert** [comment]
I have the same issue in the WATCH window

```
Version: 1.75.0 (user setup)
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Date: 2023-02-01T15:23:45.584Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: Yes
```

when `arr.stuff` is used in the code the the WATCH on arr is replaced by the value of arr.stuff

![image](https://user-images.githubusercontent.com/8616869/217845583-27143653-4310-44b8-a8fc-675db5ea2c60.png)

I tried different versions of `ms-vscode.js-debug-nightly` and it seems the issue appeared in v2022.12.1417:
- v2022.12.1417   bug
- v2022.12.1317   works fine

Hope this can help

**Comment by jakebailey** [comment]
This might be the same as #1542, as going down to `v2022.12.1317` was also the workaround I've gotten.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-js-debug/issues/1561
