### ISSUE TITLE
pwa-chrome: Breakpoint is hit even if it does not exit

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-js-debug#156]
Testing https://github.com/microsoft/vscode/issues/85984

Steps to Repro

- Use Launch VS Code launch in VS Code OSS with `pwa-chrome` to launch
- Keep a break point at line 595 and 596 
https://github.com/microsoft/vscode/blob/0fd472271d9c0cc8f923319418eaf7c559f9bee0/src/vs/workbench/contrib/markers/browser/markersPanel.ts#L595
- Open any file in launched VS Code. It hits first break point which will show column break points on first line.
- Enable the column break point on that line
- Resume debugging by continue (just keep resuming at each break point)
- Remove all break points now
- Come back to launched VS Code
- Open another file
🐛 See that breakpoint is hit again

![image](https://user-images.githubusercontent.com/10746682/70140905-14e9e600-1696-11ea-847e-04854efdba8a.png)

**Comment by connor4312** [comment]
I'm a little confused how you got into this state--the debugger paused even though you didn't have a BP there? Do you have repro steps?

**Comment by sandy081** [comment]
Yes. Updated the description with steps.

**Comment by connor4312** [comment]
Nice find on this and the other bug, these were fun to track down! 🙂

**Comment by connor4312** [comment]
Should be fixed with #162
