### ISSUE TITLE
Build and start DAP compliant server

### ISSUE THREAD

**Issue by xddq** [microsoft/vscode-js-debug#1560]
Hey, thanks for the great work on this debug server!

I am currently using the old/previous [debug server](https://github.com/microsoft/vscode-node-debug2) where I could just:
- clone the repo
- install the packages with `yarn`
- build the project with `gulp build`
- and then start the server with `node ./out/src/nodeDebug.js`

However I want/need to switch to this debug server but sadly am to stupid to figure out how to get it up and running.

I am using a separate client for debugging and simply want to know how to **build and start the server** so that I can connect to it.

**Comment by connor4312** [comment]
This requires adopting `startDebugging`, which I had some free time to start on in December but have not yet finished https://github.com/microsoft/vscode-js-debug/issues/1388

**Comment by navono** [comment]
@xddq Have you tried `js-debugger`? I also want to switch this debug server, but didn't work.
