### ISSUE TITLE
Debugger shows wrong symbols in 1.75.0 and 1.75.1 on TypeScript project 

### ISSUE THREAD

**Issue by tlbdk** [microsoft/vscode-js-debug#1561]
Type: <b>Bug</b>

1. Start debugger on a project with a typescript
2. Hover over symbol and see wrong value

![image](https://user-images.githubusercontent.com/11635/218087742-d34e391b-2491-47c5-a4f3-8db047700107.png)

![image](https://user-images.githubusercontent.com/11635/218087801-b1278419-7538-4ae5-8631-0246c140c866.png)

We use babel for transpilling and generating source maps:
https://github.com/connectedcars/node-setup

Setting sourcemaps: false and running debug on the transpilled javascript version fixes the issue.

launch.json
```
 {
  "name": "parse-server-frames",
  "type": "node",
  "request": "launch",
  "cwd": "${workspaceRoot}",
  "preLaunchTask": "npm: build:js",
  "sourceMaps": true,
  "program": "${workspaceFolder}/bin/parse.ts",
  "outFiles": [
    "${workspaceRoot}/build/dist/**/**.js"
  ],
  "args": [
    "parse-server-frames",
    ""
  ],
  "env": {},
  "internalConsoleOptions": "openOnSessionStart"
},
     
```

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:34:01.965Z)
OS version: Darwin arm64 22.2.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|--crash-reporter-id 21c864d5-16f5-4c52-86a0-bac29ba9cf20|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
vscode-eslint|dba|2.4.0
udev-rules|dpk|1.0.1
EditorConfig|Edi|0.16.4
bitbake|Eug|1.1.2
vscode-jest-runner|fir|0.4.60
vscode-pull-request-github|Git|0.58.0
go|gol|0.37.1
vscode-systemd-support|han|1.0.1
git-graph|mhu|1.30.0
vscode-docker|ms-|1.23.3
remote-containers|ms-|0.275.1
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
cpptools|ms-|1.13.9
hexeditor|ms-|1.9.11
remote-explorer|ms-|0.2.0
vsliveshare|ms-|1.0.5828
rust-analyzer|rus|0.3.1394
rewrap|stk|1.16.3
pdf|tom|1.2.2
change-case|wma|1.0.0
srecord|xia|0.0.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
282f8724:30602487
f6dab269:30613381
pythonsymbol12:30657548

```

</details>

**Comment by roblourens** [comment]
@connor4312 here's a log from 1.74
[vscode-debugadapter-ae1824d6.json.gz](https://github.com/microsoft/vscode-js-debug/files/10734265/vscode-debugadapter-ae1824d6.json.gz)

and from 1.75
[vscode-debugadapter-dd5ae2af.json.gz](https://github.com/microsoft/vscode-js-debug/files/10734271/vscode-debugadapter-dd5ae2af.json.gz)
where js-debug evaluated `response.data` when vscode asked for `response`. Looks like there were some changes to sourcemap variable names in this iterationn.

To work around this, you can either install vscode 1.74, or downgrade js-debug (Search "javascript debugger nightly" in the extensions view, right click, "install another version", pick something from a couple months ago)

**Comment by connor4312** [comment]
This is because Babel is emitting that it renames this

```js
    const response = await axios.get<string>(`${httpServer.listenUrl}`)
    expect(response.data).toEqual('Hello world')
           ^
```

to (in the compiled code)

```js
            response = _context5.sent;
            expect(response.data).toEqual('Hello world');
                   ^ 
```

Source map renames do not indicate ranges. One of their many, many flaws 😛 In the last release, we expanded the matcher to follow property accesses, which is useful for TS that renames `foo` in `import { foo } from 'bar'` to `bar_1.foo` when compiling to commonjs.

However in this case we then end up thinking `response` should actually be accessed as `response.data`, which is not correct. Will fix this when I get back on Monday.

**Comment by connor4312** [comment]
Verification: this project is easiest https://github.com/microsoft/vscode-js-debug/issues/1564#issue-1586101749

**Comment by liuxingbaoyu** [comment]
> Will try to think of a fix for when I get back on Monday, but I'm not sure this can be done without changes to Babel.

FYI, Babel now outputs `names` that will actually have exact ranges, but I can't find a good way to make it compatible with other compilers as well.

By the way, feel free to at me if there is anything Babel related that I can help with!

**Comment by connor4312** [comment]
Thanks! I'll check out the new Babel changes at some point. But unfortunately it'll be a while before I can adopt this since people will take a while to upgrade dependencies (unless I can feature-detect it in some way 🤔 )
