### ISSUE TITLE
vscode 1.75.1 shows wrong values when debugging (watch and hover) with jest tests

### ISSUE THREAD

**Issue by talarari** [microsoft/vscode-js-debug#1564]
you can see that values1 is an array [1,2,3] in locals but when hovering or in watch/debug console it shows as map function (from the next line maybe? )
 ![image](https://user-images.githubusercontent.com/4973087/219079762-b79ea60b-e17b-4c33-a44f-9e3e27cfd901.png)

after loosing my mind i downgraded to 1.74.3 where it works normally 
![image](https://user-images.githubusercontent.com/4973087/219080910-899042b9-76bc-4f44-bd69-558da50b9d4a.png)

i've made a repro repo here: 
https://github.com/talarari/jest-test

running on mac with intel chip

**Comment by connor4312** [comment]
duplicates https://github.com/microsoft/vscode-js-debug/issues/1561
