### ISSUE TITLE
unbound breakpoints only when putting the breakpoints before debugging

### ISSUE THREAD

**Issue by chungpham5599** [microsoft/vscode-js-debug#1567]
**Describe the bug**
Whenever I put the breakpoints at any random line, as long as it's before debugging starts running the breakpoints become unbound. But if I put a breakpoints after I start debugging and my source code is loaded to the loaded scripts, it's working normally.

**To Reproduce**
1. set a breakpoint at any lines before starting the debugger
2. start debugging
3. See error
The web page keeps loading indefinitely
**Log File**
[vscode-debugadapter-6a08325a.json.gz](https://github.com/microsoft/vscode-js-debug/files/10791553/vscode-debugadapter-6a08325a.json.gz)

**VS Code Version:** 1.75.1

**Additional context**

**Comment by connor4312** [comment]
Good catch, thanks. Looks like an upcoming change in Chrome dev (112). Fixed in the next [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension).

**Comment by Dev-Icaro** [comment]
For devs that are facing the same issue, I only could resolve the problem by disabling the builtin Javascript Debugger extension by following the steps:

1. Open the extensions view (ctrl+shift+x) and search for @builtin @id:ms-vscode.js-debug
2. Right click on the JavaScript Debugger extension and Disable it.
4. Search for @id:ms-vscode.js-debug-nightly in the extensions view.
3. Install that extension.

Problemn solved...
