### ISSUE TITLE
Object previews are not devtools spec compliant

### ISSUE THREAD

**Issue by byCedric** [microsoft/vscode-js-debug#1583]
**Describe the bug**
When the debugger is requesting [`Runtime.getProperties`](https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#method-getProperties), it expects certain [`Runtime.PropertyDescriptor`](https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#type-PropertyDescriptor) / [`Runtime.RemoteObject`](https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#type-RemoteObject) to be set, which are considered "optional" in the Chrome DevTools specification. (see the [devtools own types here](https://github.com/ChromeDevTools/devtools-protocol/blob/6aab256dcf4f3fe819ef5f10868cf17df49c66b3/types/protocol.d.ts#L1578-L1619))

This results in certain variables to error in the object preview, when using JS engines like [Hermes](https://reactnative.dev/docs/hermes):

![image](https://user-images.githubusercontent.com/1203991/222474508-31dab703-e1dc-4760-af0c-a73bce825acc.png)

**To Reproduce**

Full repository here: https://github.com/byCedric/vscode-js-debug-issue-1583
Walkthrough here: https://github.com/byCedric/vscode-js-debug-issue-1583/blob/main/walkthrough.mp4

**Log File**

[vscode-debugadapter-9169231d.json.gz](https://github.com/microsoft/vscode-js-debug/files/10872936/vscode-debugadapter-9169231d.json.gz)

**VS Code Version:**

```
Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:34:01.965Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: No
```

**Comment by connor4312** [comment]
Yea, the devtools types are all very lacking. Maybe just because PDL doesn't support object unions, so they're not easily expressible. As far as I know there is no "spec" for what types are present where, so this debugger has its own [more strict types](https://github.com/microsoft/vscode-js-debug/blob/main/src/adapter/objectPreview/betterTypes.ts) made from observation.

**Comment by byCedric** [comment]
@connor4312 Awesome, thanks for quickly fixing that. I'm not sure if `function` types are the only ones expecting descriptions, but I think that was the main issue that I ran into.

**Comment by alexr00** [comment]
What is the best way to verify this?

**Comment by connor4312** [comment]
It's a bit of a pain, you need to set up and debug react native, though Cedric was nice enough to have a repo with instructions https://github.com/byCedric/vscode-js-debug-issue-1583#issue-1583-repro-vscode-js-debug

@byCedric any chance you could see if this works for you on [Insiders](https://code.visualstudio.com/insiders/) or using the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension)?
