### ISSUE TITLE
sourceMapPathOverrides does not work for node_modules

### ISSUE THREAD

**Issue by lokeb** [microsoft/vscode-js-debug#1588]
Hi. I have a local project that is linked to the current project.  Launch.json has the following configuration:

The project is located outside the current project.

```json
"sourceMapPathOverrides": {
   "webpack:///./~/project/src/*": "${workspaceFolder}/../project/src/*",
}
```
Why does it not work?

**Comment by connor4312** [comment]
Please collect logs using the instructions in the issue template.
