### ISSUE TITLE
Latest Chrome (mac) seems to break chrome debugger

### ISSUE THREAD

**Issue by promontis** [microsoft/vscode-js-debug#1600]
**Describe the bug**

Chrome for Mac Version 111.0.5563.64 (Official Build) (arm64) seems to break the Chrome debugger. Overnight, the debugger stopped working with no code changes on my part.

The launch.json configuration is like this:

```
 {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:4200",
            "webRoot": "${workspaceFolder}/apps/designer"
}
```

I've also tried the Edge debugger, which works fine for the same configuration:

```json
{
            "name": "Launch Edge",
            "request": "launch",
            "type": "msedge",
            "url": "http://localhost:4200",
            "webRoot": "${workspaceFolder}/apps/designer/"
},
```
Note, they are the same except for the `type`.

**To Reproduce**
Launch the chrome debugger. When no breakpoints are set, the app loads fine. When breakpoints are set, the app keeps loading and nothing happens. 

**Log File**

[vscode-debugadapter-5bce821e.json.gz](https://github.com/microsoft/vscode-js-debug/files/10926140/vscode-debugadapter-5bce821e.json.gz)

**VS Code Version:** 

1.76.0

**Additional context**

**Comment by connor4312** [comment]
Fixed in the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) already (https://github.com/microsoft/vscode-js-debug/pull/1580). Also, Chrome is rolling this back https://bugs.chromium.org/p/chromium/issues/detail?id=1421661

**Comment by promontis** [comment]
Awesome!

**Comment by chopin2256** [comment]
This should still be an open issue. I have to keep downgrading Chrome (it just autoupdates after a few days on me), and I continue to get this hanging problem. I keep thinking it's an error with my software because I assumed this was fixed.

**Comment by connor4312** [comment]
@chopin2256 we close issues when they are fixed in our sources, not when they are released.

This fix is going into a recovery release of VS Code, which you can track on this issue https://github.com/microsoft/vscode/issues/177119. When that issue is closed, the recovery release is available.

**Comment by pbaker0804** [comment]
> 

I tried downgrading chrome also thinking it was a chrome thing (and messing with the plist to stop automatic updates), but the thing that (temporarily) solved it for me was: 

1) Go into your vscode extensions
2) disable the JavaScript Debugger (bottom in the image)
3) Installing the JavaScript Debugger (Nightly) as suggested above (top in the image).   

![image](https://user-images.githubusercontent.com/40005191/225311348-b1e8c7c5-390e-4482-a63d-7ed934957c9b.png)
