### ISSUE TITLE
Debugger Stuck on Breakpoint

### ISSUE THREAD

**Issue by Wanchai** [microsoft/vscode-js-debug#1601]
**Describe the bug**

When I set a breakpoint in my angular project and press F5, it launches Chrome and get stuck. 
Breakpoints are greyed out and I get "Some of your breakpoints could not be set."

**To Reproduce**
1. ng new my-project
2. open with VS code
3. set breakpoint in .ts file
4. press F5

**Log File**

[vscode-debugadapter-c9a8d7e4.json.gz](https://github.com/microsoft/vscode-js-debug/files/10948881/vscode-debugadapter-c9a8d7e4.json.gz)

I guess the most interesting part is this:
```
[error] TypeError: Cannot read properties of undefined (reading 'location')
	at j._onPaused (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:2:948470)
```
**VS Code Version:**
Version: 1.76.1 (system setup)
Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b
Date: 2023-03-08T16:32:00.131Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

***My Project***
Angular CLI: 15.2.2
Node: 16.19.0
Package Manager: npm 8.19.3
OS: win32 x64

**Additional context**

It works on my personal PC (windows 10), not on my pro one (windows 11).

I tried to replicate the exact same config (node version, angular version etc ...), re installed VS code to a clean state (removed all config and extensions) but nothing works ...

Thanks for your help!

**Comment by connor4312** [comment]
Please see https://github.com/microsoft/vscode-js-debug/issues/1600#issuecomment-1461073532
