### ISSUE TITLE
The breakpoint function is not working properly and displays a message that the breakpoint is unbound breakpoint.

### ISSUE THREAD

**Issue by IWSR** [microsoft/vscode-js-debug#1602]
**Describe the bug**

Hi，I’m trying to debug a React project on VS Code, but whenever I set a breakpoint to debug, it always prompts me that the breakpoint is an unbound breakpoint and has never been hit.

![image](https://user-images.githubusercontent.com/18499412/224526112-517d2f6a-7a1d-4fc1-833f-aa65407d7872.png)

But what's strange is setting in the browser does work. When I set breakpoints in the browser, the corresponding code in vscode is also executed.

![image](https://user-images.githubusercontent.com/18499412/224526020-d5ed1812-3a38-456b-b982-9f02ef656fb8.png)

My debugging environment is on WSL2 in Windows 11, and the code is stored inside WSL2. The same code can be debugged normally in macOS environment.

**Log File**

[vscode-debugadapter-0d45d307.json.gz](https://github.com/microsoft/vscode-js-debug/files/10950023/vscode-debugadapter-0d45d307.json.gz)

**VS Code Version:** 

version 1.76

**Launch configuration**

```JSON
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "pwa-chrome",
      "request": "launch",
      "name": "Launch Chrome against localhost",
      "url": "http://localhost:3000",
      "webRoot": "${workspaceFolder}",
      "sourceMaps": true
    }
  ]
}
```

**Additional context**

My [repository address](https://github.com/IWSR/react-code-debug) is here.

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode-js-debug/issues/1604
