### ISSUE TITLE
Cannot start Angular page using VSCode debug

### ISSUE THREAD

**Issue by zozo8** [microsoft/vscode-js-debug#1605]
**Describe the bug**
Once starting my page - and it doesn't matter if the page is running from webpack in VSCode console (using npm start) or is deployed on host (not local) - the chrome session opened by my config can't run any further than index.html (in Angular) - so it shows me constantly loading page. It is kind of frozen during that - I cannot open dev tools, nor refresh. Resizing doesn't take effect as well:
![image](https://user-images.githubusercontent.com/50959052/224736958-5401f51a-1f95-40d5-9f5b-555a8a9ded55.png)
![image](https://user-images.githubusercontent.com/50959052/224737022-4d620830-15b0-41be-875f-296299e70be9.png)
![image](https://user-images.githubusercontent.com/50959052/224737065-bfbe2d76-d022-4c29-840a-578fd23ab2ad.png)

Correctly loaded page from regular Chrome (censored):
![image](https://user-images.githubusercontent.com/50959052/224737790-1e22a843-5826-48a2-886b-0a2b515807b6.png)

**To Reproduce**
1. Make sure `launch.json` contains entry:
```
{
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome against localhost",
      "url": "https://localhost:5002",
      "webRoot": "${workspaceFolder}",
      "trace": true
}
```
2. Type `npm start` in console
3. Hit F5
4. On the other hand, open regular Chrome (not via VSCode) and paste localhost address.

**Log File sent to connor@xbox.com**

**VS Code Version:** 1.76.1

**Additional context**
It is happening on multiple project, all of them are angular.

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode-js-debug/issues/1604
