### ISSUE TITLE
Breakpoints Not Binding to JS scripts

### ISSUE THREAD

**Issue by DKilkenny** [microsoft/vscode-js-debug#1607]
**Describe the bug**
I have a project (containing Vue, JS, TS, and HTML files) that I have been developing on and all of a sudden it stopped binding breakpoints when I launched the debugger in Chrome. 
If I don't attach a breakpoint at all, it runs fine with no issues. If I attach a breakpoint to a Vue file, it runs until it hits a breakpoint. However, if I attach to a JS file, it no longer binds like it did a couple days ago. If I use `debugger` (but not a red breakpoint) in my JS files it will attach.

Unfortunately, I can't share the project repo but happy to share as much as I can.

**To Reproduce**
I've detailed what it takes for me to reproduce above but I wanted to add what the Debug Doctor showed. 
```
✅ This breakpoint was initially set in:

/Users/name/Desktop/company/admin_vue/src/api/Broadcast.js line 67 column 1

❓ We couldn't find a corresponding source location, but found some other files with the same name:

/Users/name/Desktop/company/admin_vue/src/aputils/broadcast.js
You may need to adjust the webRoot in your launch.json if you're building from a subfolder, or tweak your sourceMapPathOverrides.
```
I did try and set `sourceMapPathOverrides` but nothing seemed to fix the issue.

**Log File**
I will send this to you with the title of the ticket and ticket number as the subject.

**VS Code Version:** 
```
Version: 1.76.1 (Universal)
Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b
Date: 2023-03-08T16:32:09.831Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.3.0
Sandboxed: No
```

**Additional context**

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode-js-debug/issues/1604

**Comment by DKilkenny** [comment]
Ah, thank you!!
