### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by jburgoyne** [microsoft/vscode-js-debug#1609]
Very simple app to test the debugger

Index.html

\<html>
    \<head>
        \<script src="index.js"></script>
    \</head>
    \<body>
        \<p>Hello World\</p>
\</body>
\</html>

Index.js

alert("Hello");

launch.json

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Open file",
            "file": "C:\\inetpub\\wwwroot\\Basic\\index.html"
        },
        {
            "type": "chrome",
            "request": "launch",
            "name": "Open from web",  
            "webRoot": "${workspaceFolder}",            
            "url": "https://localhost/Basic/index.html"
    
        },
        {
            "type": "legacy-chrome",
            "request": "launch",
            "name": "Open from web legacy",
            "webRoot": "${workspaceFolder}",            
            "url": "https://localhost/Basic/index.html"
        }
    ]
}

Open File - Can hit break point in Index.js
Open from Web - Cannot hit break point Index.js
Open from web legacy - Can hit break point Index.js

What am I doing wrong?

**Comment by connor4312** [comment]
I'm not able to reproduce this. Please collect a log file using the instructions in the issue template:

> If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
> ⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by jburgoyne** [comment]
Many Thanks

**Comment by connor4312** [comment]
You'll want to add `"pathMapping": { "/Basic/": "${workspaceFolder}" }`

**Comment by jburgoyne** [comment]
Thanks, I'll check it out.

Why doesn't it work the same as the legacy debugger?
