### ISSUE TITLE
Console logs occasionally skipped before shutdown

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-js-debug#161]
```ts
const delay = () => new Promise(resolve => setTimeout(resolve, 14));

(async () => {
  console.log('1')
  await delay()
  console.log('2')
  await delay()
  console.log('3')
  await delay()
  console.log('4')
  await delay()
  console.log('5')
  await delay()
  console.log('6')
  await delay()
  console.log('7')
  await delay()
  console.log('8')
  await delay()
})()

```

Try running this a few times, if you see no output increase delay if you see full output decrese it. At around 11-14ms I see anywhere between no output and full output, with the output sometimes reordered.

**Comment by connor4312** [comment]
We need a change in the DAP to solve this properly: https://github.com/microsoft/debug-adapter-protocol/issues/85

**Comment by connor4312** [comment]
Update on this since there have been a few duplicates: we now use the behavior of the previous debug adapter where we stringify simple messages directly, so those should not be missed. However, if a message includes complex data that we need to send as variables, we can still hit the scenario I described in the linked issue.

**Comment by connor4312** [comment]
Some improvements made here https://github.com/microsoft/vscode-js-debug/commit/02f9147456d23bdda8f81c55679060af995b2b1f but the scenario with variable references is still present

**Comment by connor4312** [comment]
@weinand there've been a trickle of reports about this over time.

Something I could do in js-debug, now that we learned how to delay shutdown while console output is purged, is add an additional delay expecting variables requests for all console lines. But this is not very ideal. Any other suggestions?
