### ISSUE TITLE
Breakpoint maps to the wrong location in inner functions in run time

### ISSUE THREAD

**Issue by shashankvidiyalaC3** [microsoft/vscode-js-debug#1623]
**Describe the bug**
I have a use case where I return an object with functions and the function has a few internal functions which are not being used, I add breakpoints to the unused internal function which are moved to a different location.

**To Reproduce**
1)use the following code
```
k = (function scope(){
    function add(b,c){
        return b+c;
    }
    
    function skip(b,c){
        return b*c;
    }
    return {
        _add: (a,b) => add(a,b),
    }
})()
k._add(1,2);
```
2) add breakpoints after functions add and skip
3) run the debugger the breakpoint of the function skip moves to the block before the return statement

https://user-images.githubusercontent.com/105740053/228678159-c507025e-dad3-4750-98ba-1e53a2464f71.mp4

**Log File**

[vscode-debugadapter-7c3240dd.json.gz](https://github.com/microsoft/vscode-js-debug/files/11105881/vscode-debugadapter-7c3240dd.json.gz)

**VS Code Version:** 1.76.2

**Additional context**

**Comment by connor4312** [comment]
This is a behavior of V8. `skip` is unused so it gets optimized away, and therefore a breakpoint on the `skip` function resolves to the next viable location, which is the `return` statement. The same behavior can be observed in Chrome devtools.

I don't think it would be a high priority for them, but you can open an issue on their tracker if it's important for your use case: https://bugs.chromium.org/p/chromium/issues/list

**Comment by shashankvidiyalaC3** [comment]
Thanks for the quick response
