### ISSUE TITLE
Javascript debug terminal don't work with zsh

### ISSUE THREAD

**Issue by mario-mui** [microsoft/vscode-js-debug#1626]
**Describe the bug**
I have a simple index.js fille as follows with a breakpoint on line one.
<img width="331" alt="image" src="https://user-images.githubusercontent.com/7720722/229135377-34e3edfa-b9b1-4e7e-aa50-544a42ad039b.png">

And then I ran the command `node index.js` in Javascript debug terminal
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/7720722/229136027-eea9a8af-346c-4df0-8f9c-7fdd65097c6c.png">
It seems that debug model does not work

--------------------------------------------------------------------------------------
When I switched to bash, I ran the same command, it works
<img width="997" alt="image" src="https://user-images.githubusercontent.com/7720722/229136714-6ed11997-38e1-47bb-a7e2-eb9a1ea5ef99.png">

**To Reproduce**

**Log File**

**VS Code Version:** Replace me!

**Additional context**

**Comment by connor4312** [comment]
Please ensure you are not overwriting `NODE_OPTIONS` in your zshrc. You can check its value by running `echo $NODE_OPTIONS`

**Comment by mario-mui** [comment]
<img width="356" alt="image" src="https://user-images.githubusercontent.com/7720722/229294056-08b1e5b2-bc8c-4041-9517-530ea07aaf13.png">
I had set `NODE_OPTIONS`. So I must remove the `NODE_OPTIONS` in my zshrc? Is there any other solution?

**Comment by connor4312** [comment]
I recommend appending to NODE_OPTIONS, not overwriting it. E.g. `export NODE_OPTIONS="$NODE_OPTIONS --max_old_space_size=122222`

**Comment by mario-mui** [comment]
thanks
