### ISSUE TITLE
Can't debug web (eg ReactJS project) by Microsoft Edge or Chrome

### ISSUE THREAD

**Issue by viethung9at1** [microsoft/vscode-js-debug#1628]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.77.0
- OS Version: WSL2 (on both Ubuntu 18.04 and Ubuntu 20.04)- Windows 11 build 22624.1470
Steps to Reproduce:

1.  Create a new ReactJS app (no code modified)
2.  Press F5 and choose Web(Edge) debug
3.  Error: Unable to lanuch brower: (void 0) is not a constructor

**Comment by connor4312** [comment]
This will be fixed in the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) available shortly after 5PM PST today. I will also propose it for a recovery release next week.

**Comment by TKraus27** [comment]
I tried the nightly build, however I am getting 'unable to attach to browser'

**Comment by connor4312** [comment]
@TKraus27 the nightly build only just came out

---

This is now fixed in the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension). I will also propose it for a recovery release next week.

**Comment by TKraus27** [comment]
I just tried it again. Still 'unable to attach to browser' error. Not sure what the issue is as it is a very general error

**Comment by adviner** [comment]
Tried the nightly build and now getting the following error

Unable to launch browser: Unable to find an installation of the browser on your system.  Try installing it, or providing an absolute path to the browser in the runtimeExecutable in your launch.json

**Comment by TKraus27** [comment]
I initially had the same error as @adviner has stated above. my error has since changed after doing various troubleshooting.

**Comment by adviner** [comment]
TKraus27 what did you change to get over the issue I'm facing?

**Comment by TKraus27** [comment]
@adviner not sure entirely. one thing I did do was try installing chrome via the terminal using their debian package. it didn't really seem to give a full success on install. and alas I am still faced with 'unable to attach to browser'. other than that, I think all I did was reinstall the 'Javascript Debugger (nightly)" extension and relaunch vscode a few times.

**Comment by liangsqrt** [comment]
i also meet this problem, it seems like there is no launcher in my system, but is do really have installed and it works fine yesterday

> Tried the nightly build and now getting the following error
> 
> Unable to launch browser: Unable to find an installation of the browser on your system. Try installing it, or providing an absolute path to the browser in the runtimeExecutable in your launch.json

**Comment by Ashesh3** [comment]
@connor4312 
Nightly build does not fix this issue:

```
[Window Title]
Visual Studio Code

[Content]
Unable to launch browser: "Unable to find an installation of the browser on your system. Try installing it, or providing an absolute path to the browser in the "runtimeExecutable" in your launch.json."

[Open 'launch.json'] [Cancel]
```

**Comment by adviner** [comment]
I had to finally revert back to 2.7.6 and turned off automatic updates until this issue is fixed.

**Comment by louis-lau** [comment]
Same as above for me

**Comment by connor4312** [comment]
Ah, sorry, one more change is needed for now: add `"browserLaunchLocation": "ui"` to your launch config. I will put a fix in and make a special nightly release today for that.

**Comment by TKraus27** [comment]
@connor4312 adding the `"browserLaunchLocation": "ui"` to my launch.json worked for me. I'm using the nightly build of the Javascript Debugger extension

**Comment by TKraus27** [comment]
I have a new issue which is arising. Launching my next.js project through a launch configuration is causing issues. I can't get it to fully launch unless I run the `npm run dev` command in terminal manually. 

here is what shows up in terminal when I run the config:
`/usr/bin/env 'NODE_OPTIONS=--require /home/tkraus/.vscode-server/extensions/ms-vscode.js-debug-nightly-2023.3.3117/src/bootloader.js --inspect-publish-uid=http' 'VSCODE_INSPECTOR_OPTIONS={"inspectorIpc":"/tmp/node-cdp.80-87dac7be-48.sock","deferredMode":false,"waitForDebugger":"","execPath":"/usr/bin/node","onlyEntrypoint":false,"autoAttachMode":"always","fileCallback":"/tmp/node-debug-callback-095161b19d0c47a3"}' /usr/bin/npm run-script dev`

here is what my launch config looks like:
`"name": "Next.js: Launch",
      "type": "node",
      "request": "launch",
      "runtimeExecutable": "npm",
      "runtimeArgs": [ "run-script", "dev"],
      "console": "integratedTerminal",
      "skipFiles": [
        "<node_internals>/**"
      ]`

**Comment by connor4312** [comment]
Please open a new issue for that. A screencap using gifcap.dev would be useful as well.

**Comment by jimrandell** [comment]
same issue: died right after update

- Version: 1.77.0 (user setup)
- Commit: 7f329fe6c66b0f86ae1574c2911b681ad5a45d63
- Date: 2023-03-29T10:02:16.981Z
- Electron: 19.1.11
- Chromium: 102.0.5005.196
- Node.js: 16.14.2
- V8: 10.2.154.26-electron.0
- OS: Windows_NT x64 10.0.19045
- Sandboxed: No

**Comment by Ashesh3** [comment]
> > @TKraus27 the nightly build only just came out
> > This is now fixed in the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension). Note that you will need to install that _in the remote workspace_. I will also propose it for a recovery release next week.
> 
> Can you elaborate? I have no options on where to install, but it shows "Extension is Enabled on WSL:Ubuntu" but still getting 'unable to attach to browser'. I'm not running insiders build of VS Code just the standard. Thank you

Search for `@id:ms-vscode.js-debug-nightly` in the extensions view

**Comment by Ashesh3** [comment]
> > > > @TKraus27 the nightly build only just came out
> > > > This is now fixed in the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension). Note that you will need to install that _in the remote workspace_. I will also propose it for a recovery release next week.
> > > 
> > > 
> > > Can you elaborate? I have no options on where to install, but it shows "Extension is Enabled on WSL:Ubuntu" but still getting 'unable to attach to browser'. I'm not running insiders build of VS Code just the standard. Thank you
> > 
> > 
> > Search for `@id:ms-vscode.js-debug-nightly` in the extensions view
> 
> Yes, I do have that enabled, and the standard one disabled. I was questioning this part:
> 
> > Note that you will need to install that in the remote workspace.

It automatically gets enabled on the remote, even I get the "Extension is enabled on *remote name*" message on the extension page. Using vscode standard. Can you share your launch.json file? Here's mine that works:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "msedge",
            "request": "launch",
            "name": "Launch Edge against localhost",
            "url": "http://localhost:4000",
            "webRoot": "${workspaceFolder}",
        }
    ]
}
```

**Comment by TKraus27** [comment]
@Ashesh3 you need to add `"browserLaunchLocation": "ui"` to your launch.json configuration as connor4312 had stated in an earlier post

**Comment by Ashesh3** [comment]
> @Ashesh3 you need to add `"browserLaunchLocation": "ui"` to your launch.json configuration as connor4312 had stated in an earlier post

He said that adding `"browserLaunchLocation": "ui"` to the configuration was a temporary workaround until he fixed it in the next nighty build, I think we do not need it anyone, can you try without that?

**Comment by TKraus27** [comment]
@Ashesh3 I tried without it and it does seem to work for me. I thought that may have been a possible fix but it seems like it has already been updated in the nightly build.

**Comment by connor4312** [comment]
Yes, there is already a build out that removes the need for manually specifying `browserLaunchLocation`

**Comment by flyfishMT** [comment]
> > > > > @TKraus27 the nightly build only just came out
> > > > > This is now fixed in the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension). Note that you will need to install that _in the remote workspace_. I will also propose it for a recovery release next week.
> > > > 
> > > > 
> > > > Can you elaborate? I have no options on where to install, but it shows "Extension is Enabled on WSL:Ubuntu" but still getting 'unable to attach to browser'. I'm not running insiders build of VS Code just the standard. Thank you
> > > 
> > > 
> > > Search for `@id:ms-vscode.js-debug-nightly` in the extensions view
> > 
> > 
> > Yes, I do have that enabled, and the standard one disabled. I was questioning this part:
> > > Note that you will need to install that in the remote workspace.
> 
> It automatically gets enabled on the remote, even I get the "Extension is enabled on _remote name_" message on the extension page. Using vscode standard. Can you share your launch.json file? Here's mine that works:
> 
> ```
> {
>     // Use IntelliSense to learn about possible attributes.
>     // Hover to view descriptions of existing attributes.
>     // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
>     "version": "0.2.0",
>     "configurations": [
>         {
>             "type": "msedge",
>             "request": "launch",
>             "name": "Launch Edge against localhost",
>             "url": "http://localhost:4000",
>             "webRoot": "${workspaceFolder}",
>         }
>     ]
> }
> ```

Yours works for me thank you. The same exact config with "type": "pwa-chrome" does not.

**Comment by Ashesh3** [comment]
> 

Try `"type": "chrome"` once.

**Comment by Ashesh3** [comment]
> > > > > > @TKraus27 the nightly build only just came out
> > > > > > This is now fixed in the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension). Note that you will need to install that _in the remote workspace_. I will also propose it for a recovery release next week.
> > > > > 
> > > > > 
> > > > > Can you elaborate? I have no options on where to install, but it shows "Extension is Enabled on WSL:Ubuntu" but still getting 'unable to attach to browser'. I'm not running insiders build of VS Code just the standard. Thank you
> > > > 
> > > > 
> > > > Search for `@id:ms-vscode.js-debug-nightly` in the extensions view
> > > 
> > > 
> > > Yes, I do have that enabled, and the standard one disabled. I was questioning this part:
> > > > Note that you will need to install that in the remote workspace.
> > 
> > 
> > It automatically gets enabled on the remote, even I get the "Extension is enabled on _remote name_" message on the extension page. Using vscode standard. Can you share your launch.json file? Here's mine that works:
> > ```
> > {
> >     // Use IntelliSense to learn about possible attributes.
> >     // Hover to view descriptions of existing attributes.
> >     // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
> >     "version": "0.2.0",
> >     "configurations": [
> >         {
> >             "type": "msedge",
> >             "request": "launch",
> >             "name": "Launch Edge against localhost",
> >             "url": "http://localhost:4000",
> >             "webRoot": "${workspaceFolder}",
> >         }
> >     ]
> > }
> > ```
> 
> Yours works for me thank you. The same exact config with "type": "pwa-chrome" does not.

Try "type": "chrome" once.

**Comment by flyfishMT** [comment]
> > > > > > > @TKraus27 the nightly build only just came out
> > > > > > > This is now fixed in the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension). Note that you will need to install that _in the remote workspace_. I will also propose it for a recovery release next week.
> > > > > > 
> > > > > > 
> > > > > > Can you elaborate? I have no options on where to install, but it shows "Extension is Enabled on WSL:Ubuntu" but still getting 'unable to attach to browser'. I'm not running insiders build of VS Code just the standard. Thank you
> > > > > 
> > > > > 
> > > > > Search for `@id:ms-vscode.js-debug-nightly` in the extensions view
> > > > 
> > > > 
> > > > Yes, I do have that enabled, and the standard one disabled. I was questioning this part:
> > > > > Note that you will need to install that in the remote workspace.
> > > 
> > > 
> > > It automatically gets enabled on the remote, even I get the "Extension is enabled on _remote name_" message on the extension page. Using vscode standard. Can you share your launch.json file? Here's mine that works:
> > > ```
> > > {
> > >     // Use IntelliSense to learn about possible attributes.
> > >     // Hover to view descriptions of existing attributes.
> > >     // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
> > >     "version": "0.2.0",
> > >     "configurations": [
> > >         {
> > >             "type": "msedge",
> > >             "request": "launch",
> > >             "name": "Launch Edge against localhost",
> > >             "url": "http://localhost:4000",
> > >             "webRoot": "${workspaceFolder}",
> > >         }
> > >     ]
> > > }
> > > ```
> > 
> > 
> > Yours works for me thank you. The same exact config with "type": "pwa-chrome" does not.
> 
> Try `"type": "chrome"` once.

Still "Unable to attach browser" for "type": "chrome"

**Comment by codycodes** [comment]
Fixed for me without any configuration changes after update → v1.77.2

**Comment by mofojed** [comment]
I was still having problems in v1.77.3, turns out I had VSCode installed through `snap`. I tried installing with the `.deb` package and that seems to have fixed the issue: https://code.visualstudio.com/docs/setup/linux
