### ISSUE TITLE
Command "chrome.exe --headless --user-data-dir=${USER_DATA_DIR}" does NOT work if USER_DATA_DIR comes as or with any parent as directory junction

### ISSUE THREAD

**Issue by NotAndOr** [microsoft/vscode-js-debug#1633]
**Describe the bug**
Command "chrome.exe --headless --user-data-dir=${USER_DATA_DIR}" does NOT work if USER_DATA_DIR comes as or with any parent as [directory junction](https://learn.microsoft.com/en-us/windows/win32/fileio/hard-links-and-junctions), which may fail Microsoft Edge DevTools.

**To Reproduce**
1. [Enable portable mode of VS Code](https://code.visualstudio.com/docs/editor/portable) by create folder "data" as directory junction rather than real folder.
2. Open a folder with html file inside, for example a local copy of folder "demo-to-do" from [Microsoft Edge Demos](https://github.com/MicrosoftEdge/Demos/).
3. Try to [start Edge DevTools by right-clicking an HTML file](https://learn.microsoft.com/en-us/microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension/get-started-right-click-html), for example file index.html in folder "demo-to-do".
![Snipaste_2023-04-01_16-08-43](https://user-images.githubusercontent.com/2784615/229274202-9772331e-4b23-45dc-9e17-bec1bf9a0ce2.png)
4. See what pop up are NOT Edge DevTools tab and Edge DevTools: Browser tab,
![Edge DevTools tab and Edge DevTools: Browser tab](https://learn.microsoft.com/en-us/microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension/get-started-images/devtools-extension-v211.png)
BUT error dialog box.
![Snipaste_2023-04-01_16-09-26](https://user-images.githubusercontent.com/2784615/229274897-f4ce8548-a7b5-4bda-a90c-b9bc32dee722.png)

**Log File**
Not available.

**VS Code Version:**  1.76.2

**Additional context**
1. [Generating launch.json](https://learn.microsoft.com/en-us/microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension/open-devtools-and-embedded-browser#click-the-generate-launchjson-button) and invoking "Launch Edge Headless and attach DevTools" results in same error.
1. Invoking "Launching Edge and attach DevTools" workarounds this error.
1. It is reasonable to conclude that argument --headless do matters.
1. Switching to "pwa-chrome" in launch.json results in same as "pwa-msedge".
1. USER_DATA_DIR with directory junction fails command "chrome.exe --headless  --user-data-dir=${USER_DATA_DIR}".
1. USER_DATA_DIR with directory junction does NOT fail command "chrome.exe --user-data-dir=${USER_DATA_DIR}".
1. USER_DATA_DIR with directory junction does NOT fail command "chrome.exe --headless  --no-sandbox --user-data-dir=${USER_DATA_DIR}".
1. It is reasonable to speculate that there is some conflict among feature Headless and feature Sandbox and option USER_DATA_DIR with directory junction in Chromium and derived Edge and Chrome.
1. I have tried to [use fs.realpathSync() to purify resolvedDataDir in launchBrowser() in src/targets/browser/browserLauncher.ts](https://github.com/NotAndOr/microsoft.vscode-js-debug/commit/b763ec63a20b793b457e160ab592189861e8ed7a), and prevented Edge DevTools from reproducing that unexpected behavior on OS Windows.
1. Let me know if there is some introduced impact not taken into my account, for example some unanticipated side effect on OS other than Windows.

**Comment by connor4312** [comment]
Fixed in https://github.com/microsoft/vscode-js-debug/pull/1656
