### ISSUE TITLE
pathMapping not working when working remote and browserLaunchLocation is "ui"

### ISSUE THREAD

**Issue by sbormann** [microsoft/vscode-js-debug#1640]
**Describe the bug**
Working remote on a VM-Box debian system.

My workspace is:
``/opt/iobroker/ioBroker.iqontrol``

I edit my webfiles here:
``/opt/iobroker/ioBroker.iqontrol/www``

When i save them they are deployed to
``/opt/iobroker/iobroker-data/files/iqontrol`` 
(so that is laying outside the workspace-folder)

I have the following launch.json:
````json
{
            "name": "www debug",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:8082/iqontrol/index.html",
            "webRoot": "/opt/iobroker/iobroker-data/files",
            "pathMapping": {
                "/iobroker": "${workspaceFolder}/www"
            },
            "browserLaunchLocation": "ui"
}
````

When i run this, it openes (since i have the nightly build) chrome local.
I can see the messages in the debug console in vscode.
But the breakpoints do not hit.
When i click on a message in the debug console to open index.js, it openes a new file
``/opt/iobroker/iobroker-data/files/iqontrol/index.js``
So the pathMapping seems to be ignored - or am i doing something wrong? I tried all imaginable combinations, none of them worked.

**Log File**
[vscode-debugadapter-1cf73dd0.json.gz](https://github.com/microsoft/vscode-js-debug/files/11148376/vscode-debugadapter-1cf73dd0.json.gz)

**VS Code Version:** 1.77.0

**Comment by connor4312** [comment]
It looks like your script is served from `http://localhost:8082/iqontrol/index.js`, so you want a pathMapping for `/iqontrol`, not `/iobroker`. There are no scripts served from `/iobroker/*` in the log file you sent.

**Comment by connor4312** [comment]
Do you have the "legacy chrome debugger" extension installed? If so, please uninstall it, I think that is also messing with things.

**Comment by sbormann** [comment]
No, i have no additional debugger installed.
For testing i installed edge tools - with edge my configuration in launch.json works.
