### ISSUE TITLE
when use cross-env in npm script, unable to run

### ISSUE THREAD

**Issue by wuhaohuang** [microsoft/vscode-js-debug#1645]
**Describe the bug**

when use cross-env in npm script with nestjs, unable to run. script like:
```
"start:debug": "cross-env NODE_OPTIONS=--max-old-space-size=12288 BUILD_ENV=development NODE_ENV=development node ../../node_modules/.bin/nest start --debug --watch",
``` 

launch.json like:
```json
  {
  "version": "0.2.0",
  "configurations": [

    {
      "name": "Launch via NPM",
      "request": "launch",
      "runtimeArgs": [
        "run-script",
        "start:debug"
      ],
      "runtimeExecutable": "npm",
      "runtimeVersion": "16.16.0",
      "internalConsoleOptions": "neverOpen",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "sourceMaps": true,
      "type": "node"
    }
  ]
}
  ```

when on click launch, the call stack like: 
<img width="348" alt="iShot_2023-04-06_20 11 39" src="https://user-images.githubusercontent.com/19322584/230375261-ff22f244-7604-4ad0-b32d-83cfc57cd21c.png">

**Log File**
[vscode-debugadapter-472d6b89.json.gz](https://github.com/microsoft/vscode-js-debug/files/11170505/vscode-debugadapter-472d6b89.json.gz)

**VS Code Version:** 1.77.0 (Universal)

**Additional context**
Unbound breakpoint like:
<img width="904" alt="iShot_2023-04-06_20 17 20" src="https://user-images.githubusercontent.com/19322584/230376462-5316b3ba-3422-42ae-9e8f-222dde657047.png">

Mask: is mac os.

My current solution is not to use Cross-Env, the injected variable is declared in launch.json. It can run up.

Don't understand why this is like this.

**Comment by connor4312** [comment]
NODE_OPTIONS is used for setting up debugging; overwriting it will break debugging. You will want to append to it instead of replacing it.

**Comment by lin1987www** [comment]
append to it will be this
  
` "start:debug": "cross-env \"NODE_OPTIONS=${NODE_OPTIONS} --max-old-space-size=12288\" BUILD_ENV=development NODE_ENV=development node ../../node_modules/.bin/nest start --debug --watch",`
