### ISSUE TITLE
Can't hit breakpoints in worker thread that starts before debugger attaches

### ISSUE THREAD

**Issue by debonte** [microsoft/vscode-js-debug#1646]
**Describe the bug**
I'm unable to hit breakpoints in worker threads that were started before the debugger attached. Multiple people on the Pylance team are experiencing this. It seems to have started recently. I believe I first hit this issue on March 27 in VS Code Insiders.

**To Reproduce**
1. git clone https://github.com/debonte/WorkerThread -- This contains a simple app with a main thread and worker thread that send messages back and forth.
2. Open the cloned folder in VS Code
3. Add breakpoints on the `worker.postMessage` call in `main.js` (line 19) and the `parentPort.postMessage` call in `worker.js` (line 8).
4. From command-line, run `node --inspect=9229 main.js`. You should start seeing console output like "Message received from main thread..."
5. In VS Code, select the "Attach" debug configuration and press F5.

**Expected:** You should be able to hit both breakpoints. When you hit one, press F5 and shortly after that you should hit the other one (in the other thread).

**Actual:** Only the breakpoint in `main.js` is hit. The breakpoint in `worker.js` never binds.

If you start the program with `--inspect-brk` instead of `--inspect`, both breakpoints will work. I assume this is because the debugger is attached before the worker thread is started.

**Log File**
[vscode-debugadapter-2c0f67cb.json.gz](https://github.com/microsoft/vscode-js-debug/files/11174220/vscode-debugadapter-2c0f67cb.json.gz)

**VS Code Version:**
Version: 1.78.0-insider (user setup)
Commit: 3e0b354932b8ddeb099c68ed3b7dfac25350dde2
Date: 2023-04-06T05:20:25.265Z
Electron: 22.4.3
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.25314
Sandboxed: Yes

**Comment by rchiodo** [comment]
This is making it difficult to debug our language server at the moment. We believe this is a regression because we used to be able to debug the language server.

**Comment by debonte** [comment]
Thanks @connor4312!
