### ISSUE TITLE
Breakpoitn gets disabled as soon i start in debug mode in chrome

### ISSUE THREAD

**Issue by kavithaJrd** [microsoft/vscode-js-debug#1649]
**Describe the bug**h I
I have added configuration of launch chrome in launch.json. Default one provided by visual studio. Added breakpoints in method. Start application and then started debugging i.e 'start debugging' under run. Application launched in debug mode but breakpoint automatically got disabled in code. I have enabled debug everywhere under user and workspace both.

**To Reproduce**

**Log File**

**VS Code Version:** March 2023 (version 1.77)

**Additional context**

**Comment by connor4312** [comment]
Please collect a trace log using the instructions in the issue template. Thanks!
