### ISSUE TITLE
Debug adapter still sending events after sending the response to "disconnect"

### ISSUE THREAD

**Issue by EricCornelson** [microsoft/vscode-js-debug#165]
We've noticed the adapter sending the following events after responding to the "disconnect" request:

- loadedSource
- thread
- process
- output
- terminated

(after which, VS expects the session to be completed). These events are unexpected on the VS side, and cause assertion errors:

![image](https://user-images.githubusercontent.com/38218905/70556306-7cd87a80-1b35-11ea-954b-9954e755ddb2.png)
![processEventAssert](https://user-images.githubusercontent.com/38218905/70556319-8366f200-1b35-11ea-8001-5a2f13965ce8.png)
![image](https://user-images.githubusercontent.com/38218905/70556363-9d083980-1b35-11ea-98e9-5fc08e06008d.png)

logs attached
[vscode-debugadapter(1).log](https://github.com/microsoft/vscode-js-debug/files/3946518/vscode-debugadapter.1.log)
[vscode-debugadapter.log](https://github.com/microsoft/vscode-js-debug/files/3946522/vscode-debugadapter.log)

**Comment by connor4312** [comment]
One of the bits of difficulty for this, at least for Node, is that we send a terminated event immediately when we see the child process exits. This is not done in lockstep with any events that may be inbound or processing in the CDP. It's possible that we'll need some higher level refactor work to serialize these events.

**Comment by connor4312** [comment]
Please let me know if you continue hitting issues after https://github.com/microsoft/vscode-js-debug/pull/255

**Comment by EricCornelson** [comment]
Will do, thanks Connor!
