### ISSUE TITLE
[zh-Hans] Suggest not to translate "promise rejection"

### ISSUE THREAD

**Issue by Krysl** [microsoft/vscode-js-debug#1658]
<img width="280" alt="Snipaste_2023-04-08_23-45-08" src="https://user-images.githubusercontent.com/5905801/230730465-8efac0b4-76a4-4aa9-a8ff-449fb107ab45.png">
When I first saw this translation, my mind went blank and I couldn't understand what it meant.  

https://github.com/microsoft/vscode-loc/blob/44f29a528527b811bf0fe605d0c312f16cd6cca5/i18n/vscode-language-pack-zh-hans/translations/extensions/ms-vscode.js-debug.i18n.json#L315

https://github.com/microsoft/vscode-loc/blob/44f29a528527b811bf0fe605d0c312f16cd6cca5/i18n/vscode-language-pack-zh-hans/translations/extensions/ms-vscode.js-debug.i18n.json#L231

I have hardly ever seen these two words translated into Chinese on Chinese websites. 
It seems to be a convention to use the English version.

**Comment by TylerLeonhardt** [comment]
@connor4312 can you add a comment to these strings like `'{Locked="promise"}'` for these so they don't get translated?
