### ISSUE TITLE
Debugger starts in non JavaScript Debug Terminal and crashes

### ISSUE THREAD

**Issue by lazpavel** [microsoft/vscode-js-debug#1660]
![image](https://user-images.githubusercontent.com/85319655/232122673-4ec48ccb-dfee-4c49-88fd-eca31ef10d41.png)

**Comment by connor4312** [comment]
Can you please share the result of the following two commands?

- `echo $NODE_OPTIONS`
- `echo $VSCODE_INSPECTOR_OPTIONS`

**Comment by roblourens** [comment]
@lazpavel is this working for you in the latest Insiders build?

**Comment by connor4312** [comment]
I hypothesize that the tmpdir location rotated and that the socket path that was initially set was no longer valid. I don't know whether a change to the tmpdir can be forced. I suggest waiting for author verification or add some dummy code in OSS to 'corrupt' the `ipcAddress` in debug-auto-launch when read from storage and making sure it gets re-set afterwards.

https://github.com/microsoft/vscode/blob/68dc2206ef350dba57f50bcdb2a6c8a3719cfc96/extensions/debug-auto-launch/src/extension.ts#L375

**Comment by roblourens** [comment]
I'm not really sure what to do with that, but I think the code change looks straightforward. I'll mark it as verified, if you think I should try running the scenario then maybe you can share your code change to OSS

**Comment by lazpavel** [comment]
I don't think this issue is completely resolved, it still happens if I have more than one instance of vscode running
