### ISSUE TITLE
debugger in WSL2 is not working, but work fine in windows

### ISSUE THREAD

**Issue by eveforest** [microsoft/vscode-js-debug#1661]
**Describe the bug**
using js debugger work fine in window, but in wsl2 project the reference named '/mnt/c/...'  seems disconnected with 'localhost:xx'.
The src dir below them is also dispear and any breakpoint is not working.
![2023-04-16_124759](https://user-images.githubusercontent.com/32702981/232268349-7a37bd44-2ac3-469d-b05d-f827dd2c9682.png)

And work fine in window like below:
![2023-04-16_130421](https://user-images.githubusercontent.com/32702981/232272025-d3df4379-1d7c-45c9-88ee-3227e33d1471.png)

my configuration json:
{
    "type": "chrome",
    "request": "launch",
    "name": "wsl chrome",
    "url": "http://localhost:9000",
    "webRoot": "${workspaceFolder}"
}

**VS Code Version:**
Version: 1.77.3 (user setup)
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:02.548Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

using lasted JavaScript Debugger (Nightly)

**Comment by connor4312** [comment]
Please collect logs using the the instructions in the issue template.

**Comment by connor4312** [comment]
Please share that file by dragging and dropping it into the comment box on Github. The website you linked is just a local viewer and doesn't share anything with us.

**Comment by connor4312** [comment]
It doesn't look like you had any breakpoints set in that session. Can you try setting some so I can see where the issue is?

**Comment by connor4312** [comment]
You mentioned 

> any breakpoint is not working

Is this no longer the case?

**Comment by eveforest** [comment]
hi @connor4312, thx for your patience, the more detail situation is:
1. first make a breakpoint , and then launch debugger and npm run pro, it will cause every steps stop, even though i just only make one breakpoint. this situation log is:
 [vscode-debugadapter-ee5c9865.json.gz](https://github.com/microsoft/vscode-js-debug/files/11253007/vscode-debugadapter-ee5c9865.json.gz).
3. if i launch debugger and npm run pro first, then make a breakpoint, there is nothing happen. Any breakpoint is not working in vscode, whenever i make breakpoints from vscode or the chrome debug mode sources(F12). This situation log is:
 [vscode-debugadapter-b3bcae0c.json.gz](https://github.com/microsoft/vscode-js-debug/files/11252896/vscode-debugadapter-b3bcae0c.json.gz)
