### ISSUE TITLE
Error in the js-debug bootloader

### ISSUE THREAD

**Issue by kudlav** [microsoft/vscode-js-debug#1667]
```
Starting inspector on 127.0.0.1:53527 failed: address already in use
Error in the js-debug bootloader, please report to https://aka.ms/js-dbg-issue: Error [ERR_INSPECTOR_NOT_ACTIVE]: Inspector is not active
    at new NodeError (node:internal/errors:400:5)
    at Object.inspectorWaitForDebugger (node:inspector:194:11)
    at Ta (bootloader.bundle.cdp:8:7880)
    at bootloader.bundle.cdp:8:6506
    at bootloader.bundle.cdp:8:6708
    at Object.<anonymous> (bootloader.bundle.cdp:8:8838)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
```

Version: 1.77.3 (system setup)
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:02.548Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

<html>
<body>

CPUs | 12th Gen Intel(R) Core(TM) i7-1260P (16 x 2496)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok skia_renderer: enabled_on video_decode: enabled video_encode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled webgpu: disabled_off
Load (avg) |  
Memory (System) | 31.70GB (15.97GB free)
Process Argv | --crash-reporter-id 7392af27-71b2-4526-8259-b5641ce529bf
Screen Reader | no
VM | 0%

</body>
</html>

<html>
<body>

Extension | Author (truncated) | Version
-- | -- | --
Handlebars | and | 0.4.1
better-cpp-syntax | jef | 1.17.2
latte | Kas | 0.18.0
Kotlin | mat | 1.7.1
dotenv | mik | 1.0.1
remote-containers | ms- | 0.288.1
remote-ssh | ms- | 0.100.0
remote-ssh-edit | ms- | 0.84.0
remote-wsl | ms- | 0.77.0
remote-explorer | ms- | 0.4.0
Handlebars | and | 0.4.1
vscode-intelephense-client | bme | 1.9.5
doxdocgen | csc | 1.4.0
vscode-eslint | dba | 2.4.0
prettier-vscode | esb | 9.10.4
todo-tree | Gru | 0.0.226
better-cpp-syntax | jef | 1.17.2
php-cs-fixer | jun | 0.3.9
latte | Kas | 0.18.0
Kotlin | mat | 1.7.1
git-graph | mhu | 1.30.0
dotenv | mik | 1.0.1
vscode-docker | ms- | 1.25.0
jupyter-renderers | ms- | 1.0.15
vscode-jupyter-cell-tags | ms- | 0.1.8
vscode-jupyter-slideshow | ms- | 0.1.5
cmake-tools | ms- | 1.13.45
cpptools-extension-pack | ms- | 1.3.0
hexeditor | ms- | 1.9.11
makefile-tools | ms- | 0.6.0
color-highlight | nau | 2.5.0
java | red | 1.17.0
trailing-spaces | sha | 0.4.1
code-spell-checker | str | 2.20.4
code-spell-checker-czech | str | 1.0.4
selectline-statusbar | tom | 0.0.2
non-breaking-space-highlighter | vik | 0.0.3
intellicode-api-usage-examples | Vis | 0.2.7
vscodeintellicode | Vis | 1.2.30
vscode-maven | vsc | 0.41.0

<span style="color: rgb(204, 204, 204); font-family: &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(60, 60, 60); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">(4 theme extensions excluded)</span>
</body>
</html>

No current experiments.

---

Computer reboot was required, Only `wsl --shutdown` doesn't solve the problem.

**Comment by connor4312** [comment]
This is an issue in Node.js, please open an issue with reproduction steps there: https://github.com/nodejs/node/issues

`inspector.open()` is called if `inspector.url()` is defined. It appears in this case `inspector.url()` returned something, but the inspector was not actually active.
