### ISSUE TITLE
Cannot set breakpoint, Vue 2, Typescript, Webpack, since VS Code 1.75

### ISSUE THREAD

**Issue by SaschaAusUlm** [microsoft/vscode-js-debug#1670]
**Describe the bug**

That worked nicely in 1.74.3
I set a breakpoint in one of my TS files.
I see the breakpoint in the breakpoints panel as "AlarmsHistoryDialog.ts line 135" (just an example)

But when the application starts in my browser, the breakpoint changes to "app.js line 279014"

The debugger stops there ,,,, yes ... but does not help debugging.

I see an attention icon, that leads me to:

✅ This breakpoint was initially set in:

C:\src\hau-bus-ui\src\components\alarms\history\AlarmsHistoryDialog.ts line 135 column 1

✅ In the runtime, the breakpoint was set in:

http://localhost:8080/app.js line 279012 column 283

✅ The runtime acknowledged and adjusted the breakpoint, and it mapped back to the following locations:

line 279014 column 7

If this is not right, your compiled code might be out of date with your sources. If you don't think this is the case and something else is wrong, please [open an issue](https://github.com/microsoft/vscode-js-debug/issues/new/choose)!

Which I am doing now. Worked fine in 1.74.3.

**Log File**

Version 1.77.3 now

[vscode-debugadapter-5e5dd168.json.gz](https://github.com/microsoft/vscode-js-debug/files/11294972/vscode-debugadapter-5e5dd168.json.gz)

**Comment by connor4312** [comment]
This looks like an error in your build tooling. As the trace log shows, the breakpoint mapped to a different compiled location. And then when the browser paused there, that location didn't have an associated mapping back to your source file.

If you have an example repro case I can look more, but from what you've described and the logs it seems like things are working as intended. I would make sure all your build tooling is up to date to get any fixes they might have put in.

**Comment by SaschaAusUlm** [comment]
Hey Connor.

What trace log? Can you point me to the line?

In VS Code 1.74.3:

```
[15:38:13.333 UTC] SourceMap: mapping webpack:///./src/components/alarms/history/AlarmsHistoryDialog.ts => C:\src\hau-bus-ui\src\components\alarms\history\AlarmsHistoryDialog.ts, via sourceMapPathOverrides entry - "webpack:///./*": "C:\src\hau-bus-ui/*"

[15:38:13.532 UTC] SourceMap: mapping webpack:///./src/components/alarms/history/AlarmsHistoryDialog.ts?b57d => C:\src\hau-bus-ui\src\components\alarms\history\AlarmsHistoryDialog.ts?b57d, via sourceMapPathOverrides entry - "webpack:///./*": "C:\src\hau-bus-ui/*"
```


That looks correct to me.

In VS Code 1.77.3:

```
{"tag":"runtime.sourcemap","timestamp":1680523195315,"message":"SourceMap: mapping webpack:///./src/components/alarms/history/AlarmsHistoryDialog.ts => C:\\src\\hau-bus-ui/./src/components/alarms/history/AlarmsHistoryDialog.ts, via sourceMapPathOverrides entry - /^webpack:\\/\\/.*?\\/(.*?)$/i","level":0}

{"tag":"runtime.sourcecreate","timestamp":1680523195315,"message":"Creating source from source map","metadata":{"inputUrl":"webpack:///./src/components/alarms/history/AlarmsHistoryDialog.ts","sourceMapId":446,"absolutePath":"c:\\src\\hau-bus-ui\\src\\components\\alarms\\history\\AlarmsHistoryDialog.ts","resolvedUrl":"file:///C:/src/hau-bus-ui/src/components/alarms/history/AlarmsHistoryDialog.ts"},"level":0}

{"tag":"runtime.sourcemap","timestamp":1680523195907,"message":"SourceMap: mapping webpack:///./src/components/alarms/history/AlarmsHistoryDialog.ts => C:\\src\\hau-bus-ui/./src/components/alarms/history/AlarmsHistoryDialog.ts, via sourceMapPathOverrides entry - /^webpack:\\/\\/.*?\\/(.*?)$/i","level":0}

{"tag":"dap.send","timestamp":1680523196223,"metadata":{"connectionId":9,"message":{"seq":55,"type":"event","event":"loadedSource","body":{"reason":"new","source":{"name":"src/components/alarms/history/AlarmsHistoryDialog.ts","path":"c:\\src\\hau-bus-ui\\src\\components\\alarms\\history\\AlarmsHistoryDialog.ts","sourceReference":0}}}},"level":0}
```

Path for Windows looks strange:

C:\\src\\hau-bus-ui/./src/components/alarms/history/AlarmsHistoryDialog.ts

I guess it depends on how the path is then used.

Build tool (webpack) we're not demanding or specifying explicitly. It comes with the Vue build tools chain.
So I would say nothing has really changed. The files are on disk and should be in the source map.

Uploading the source map of 1.74.3 as well.





[vscode-edge-debug.txt](https://github.com/microsoft/vscode-js-debug/files/11304205/vscode-edge-debug.txt)
