### ISSUE TITLE
GWT Debugger

### ISSUE THREAD

**Issue by rhuanhianc** [microsoft/vscode-js-debug#1671]
Hello, I've tried in every possible way to debug gwt in vscode, in intellij it works with js debug, in eclipse too, but in vs code I can't, at the moment I use the devtools itself to debug. this is my launch.json:

{
    "version": "0.2.0",
    "configurations": [
      {
        "name": "Launch Chrome against WildFly",
        "type": "chrome",
        "request": "launch",
        "url": "http://localhost:8180/ServerExec/proce/",
        "webRoot": "${workspaceFolder:VisalClient}",
        "sourceMaps": true,
        "trace": true,
        "sourceMapPathOverrides": {
          "http://localhost:53967/sourcemaps/visaclient/*": "${workspaceFolder:VisalClient}/*"
        }
      }
    ]
  }

**Comment by connor4312** [comment]
Please collect logs using the instructions in the issue template

**Comment by rhuanhianc** [comment]
[vscode-debugadapter-d3c08ffb.json.gz](https://github.com/microsoft/vscode-js-debug/files/11297747/vscode-debugadapter-d3c08ffb.json.gz)

**Comment by connor4312** [comment]
It looks like you just need to change `localhost:53967` in your sourceMapPathOverrides to `127.0.0.1:53967` to match what your tooling is emitting.

**Comment by rhuanhianc** [comment]
After changing to 127.0.0.1 and changing the path to src, it worked correctly, thank you for your help with the configuration!
