### ISSUE TITLE
debugger stops at Exceptions in devtools://

### ISSUE THREAD

**Issue by Megabyteceer** [microsoft/vscode-js-debug#1674]
**Describe the bug**
When i open chrome devtools with vscode debugger connected, i always get debugger stopped at exception:
```
Exception has occurred: Error: Readers took over 1500ms. Possible deadlock?
  at devtools://devtools/bundled/ui/components/render_coordinator/render_coordinator.js:1:2451
```
it is happens in different versions of chrome.
as example now i use chrome 112.0.5615.87

**To Reproduce**
Start debugging in chrome.
Open devtools in chrome with vscode debugger connected.

![image](https://user-images.githubusercontent.com/5096541/234011541-3fd09270-1c3c-4260-8086-1f6cd9b4e520.png)

Maybe debugger should ignore devtools process?
I tried set "autoAttachChildProcesses": false but debugger connects to devtools process anyway. If "Uncaught exception" checkbox is disabled, exception does not stop.

**VS Code Version:** 1.77.3

**Comment by Megabyteceer** [comment]
Sorry, I have tried nightly build, and it is still attaches to the devtools:// process and stops at exception after devtools open.
Here is my project: https://lm.pixel-cave.com/uploads/file/8a8eb0ff07cc9/ts-vite-electron.zip
there is trace file dbug.log in .zip 
to reproduce bug: `npm i`   open in vscode as folder allow startup task (vite.js dev serve) and start default debug configuration.
Here is electron project, but i had the same error in chrome too.

**Comment by connor4312** [comment]
Thanks for the log, I'm not able to decompress it however 🤔

**Comment by Megabyteceer** [comment]
Unpacked log https://lm.pixel-cave.com/uploads/file/3f96107829460/dbug.txt

Also i have tried to debug vscode extension via steps in oficial vscode extensions repo. Got the same error in devtools. I hope it is not my local system error. I tried many versions of electron and chrome.

**Comment by connor4312** [comment]
It looks like in your case when devtools are opened, the page initially has an empty URL before getting a later `targetInfoChanged` event, so the generic logic I added doesn't filter it. I would recommend just using a `urlFilter` in your launch config to avoid attaching to devtools, e.g `"urlFilter": "http://127.0.0.1:5173/*`
