### ISSUE TITLE
Unbound breakpoint    Some of your breakpoints could not be set. If you have a problem, you can troubleshoot your launch configuration.

### ISSUE THREAD

**Issue by TrakyRichard** [microsoft/vscode-js-debug#1679]
✅ This breakpoint was initially set in:

/Users/richard/Desktop/project/apps-webs/apps/apps/api/src/App/modules/donations/donations-users.controller.ts line 24 column 1

❓ We couldn't find a corresponding source location, but found some other files with the same name:

/Users/richard/Desktop/project/apps-webs/apps/apps/api/src/App/modules/donations/donations-users.controller.ts
If this is the same file, you may need to adjust your build tool to correct the paths.

I'm trying to attach a debugger with a Nestjs application on Nx workspace but i'm getting this errors.
Does anyone know where it come from ?

**Comment by connor4312** [comment]
Please collect logs using the instructions in the "bug" issue template
