### ISSUE TITLE
Private class field values aren't shown when they are hovered

### ISSUE THREAD

**Issue by surenenfiajyan** [microsoft/vscode-js-debug#1686]
**Bug description**
When I'm hovering private class fields/methods their values aren't shown, although they are correctly shown in watch expressions
[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2023.04.30-01_28_36.webm](https://user-images.githubusercontent.com/13224708/235325031-7bb0a11e-017d-416f-92ea-272198c9d144.webm)
.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/18058
