### ISSUE TITLE
pwa debug types no longer works

### ISSUE THREAD

**Issue by veredcon** [microsoft/vscode-js-debug#1687]
Hi @connor4312 

We have a VSCode based IDE product and our users have debug configurations with type "pwa-node" that has always been working fine.
However after VSCode upgrade, now we are using 1.76.2 and JavaScript Debugger 1.76.1, these configurations do not longer work for our customers. I read some threads that pwa prefix should be avoided and is deprecated but I could not find the exact announcement or PR in this point in time (between VSCode version 1.75.0 and 1.76.2) where it happened. 
Do you know maybe when it had happened and can send me details?

The generated configuration looks like this and it doesn't work anymore:
` {
      "name": "Run bookshop-1",
      "request": "launch",
      "type": "pwa-node",
      "cwd": "${workspaceFolder}",
      "runtimeExecutable": "npx",
      "args": [
        "cds",
        "run",
        "--in-memory?"
      ],
      "console": "internalConsole",
      "internalConsoleOptions": "openOnSessionStart",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "envFile": "${workspaceFolder}/.env1",
      "env": {
        "NODE_ENV": "development",
        "run.config": "..."
      }
    }`

If we remove the pwa prefix so the type is just "node" it works fine.

**Comment by connor4312** [comment]
The PWA prefix is still present and should work fine. Please collect logs using these instructions:

> If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
> ⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by veredcon** [comment]
Hi @connor4312 
Thank you for your suggestion! seems like the issue we have is in "node-terminal" type so the debug session starts but breakpoints are unbound.
I tried to add trace=true to the configuration but the output is json.gz binary so I guess it is not compatible for the pwa analyzer
I sent you the file in the mail

![image](https://user-images.githubusercontent.com/9718939/235425178-60273f66-d4ca-465d-9b1c-cd7b12ac2784.png)

**Comment by veredcon** [comment]
Thank you so much for the support.
We have found the issue in our side.
Thanks!
Vered
