### ISSUE TITLE
The generated `gz` file from `trace: true` has "unexpected end of data" error when decompressing

### ISSUE THREAD

**Issue by cinderblock** [microsoft/vscode-js-debug#1688]
The generated `gz` file from `trace: true` has "unexpected end of data" error when decompressing

### To Reproduce
1. Add `"trace": true` to `launch.json`
2. Try running the debugger
3. Get path to `.../vscode-debugadapter-*.json.gz`
4. Try uploading to https://microsoft.github.io/vscode-pwa-analyzer/index.html

### Log File

[vscode-debugadapter-eba022ac.json.gz](https://github.com/microsoft/vscode-js-debug/files/11364018/vscode-debugadapter-eba022ac.json.gz)

### Versions

 - **OS**: Windows 11
 - **VS Code**: 1.77.3
 - **js-debug**: v1.77.2

### Additional context

I'm trying to attach to an instance of `node` running on a remote machine over my own port forward. Something is not working. In trying to debug that, the generated trace files keep having issues and I can't upload to the analyzer website.

PS: There is no error on the analyzer website. Just sits there waiting.
Extracting with 7-zip shows an error, but gets a valid `.json` text file. Recompressing that into a new good `.json.gz` file lets me upload to the analyzer successfully.

PPS: My instance of node is printing: `Debugger listening on ws://127.0.0.1:9229/dc1a71f0-d008-46b1-aafc-707b26c2b4fc` but trying to attach VS Code's debugger to that port, via a tcp port forward, generates these logs with `"connect ECONNREFUSED 127.0.0.1:9229"` errors... ~I'm not sure why. I don't see where/how the UUID gets passed along, or if it needs to be.~ My port forwarding was broken.

**Comment by connor4312** [comment]
To make sure the log gets written out, you can end the debug session. We do `Z_SYNC_FLUSH` after writing each log entry, but for some reason it seems this is not always sufficient. I looked into this a while ago but didn't see a great way to deal with it. Suggestions welcome.

**Comment by cinderblock** [comment]
I cannot end the debug session - it never even started (I had a broken port forward that just never responded)

**Comment by connor4312** [comment]
I don't think there's much I want to do here. The only real solution would be using some kind of alternative compression algorithm, but I don't want to bloat the extension by doing so. Files with "unexpected end of data" can, as found, generally still be extracted with tools like 7zip or just the unix `gunzip`.
