### ISSUE TITLE
a question about this code base

### ISSUE THREAD

**Issue by kerimcharfi** [microsoft/vscode-js-debug#1689]
I tried to add some WASM debug functionality and had a hard time getting into this code base. My main issue is / was the way Scripts and Sources and their locations are all mixed up. 
My question is: Apart from pretty printing, are there any situations were a chaining of SourceMaps actually happen? Is there a real world situation where a Sourcemap points to another Sourcemap? 
I feel like this was a major reason that lead to the design choice of mixing the role of scripts and sources?, e.g. calling a location inside a script and inside a source both UiLocation.
While trying to add my wasm functionality I started rewriting it so that a SourceMap points from a script to a source directly. Is there a reason why its not done this way?

**Comment by connor4312** [comment]
Yes, these are encountered in the real world. For https://github.com/microsoft/vscode-js-debug/pull/1410 for example:

**Comment by connor4312** [comment]
Let me know if you have other questions.
