### ISSUE TITLE
A breakpoint update event can sometimes be sent before the response to the breakpoint request that created it

### ISSUE THREAD

**Issue by EricCornelson** [microsoft/vscode-js-debug#169]
It looks like there is a race condition where a breakpoint update event can be sent out before the response to the "setBreakpointsRequest" that creates it. This causes an error in VS, as there is no breakpoint existing with the referenced id.

![image](https://user-images.githubusercontent.com/38218905/70671984-bc38c100-1c32-11ea-8201-ff772fc19752.png)

Logs (see line 212):
[vscode-debugadapter.log](https://github.com/microsoft/vscode-js-debug/files/3953228/vscode-debugadapter.log)

**Comment by connor4312** [comment]
Thanks, Dmitry actually mentioned the possibility of this on the associated PR yesterday. I'll have a fix in tomorrow morning.
