### ISSUE TITLE
Step over in Jasmine test does not pause on next line

### ISSUE THREAD

**Issue by c3danielxu** [microsoft/vscode-js-debug#1700]
**Describe the bug**
I am trying to use https://www.npmjs.com/package/jasmine to execute a test. At the end of a `it` block, step over does not pause on the next line (that is not excluded by skipFiles). But if I set a breakpoint or use `debugger;` then the debugger will pause on the line. I am using default debugger configurations except for `"**/node_modules/**",` in `skipFiles`. See recording below.

**To Reproduce**
1. Open this workspace: [jasminetest.zip](https://github.com/microsoft/vscode-js-debug/files/11410066/jasminetest.zip)
2. Run `npm install`
3. Run and Debug --> Launch program
4. Observe that debugger pauses on line 3 due to debugger statement. Repeated step over does not pause on line 6 and instead pauses on the next breakpoint or `debugger;` line, on line 9.

**Log File**
[vscode-debugadapter-e8723dd9.json.gz](https://github.com/microsoft/vscode-js-debug/files/11410092/vscode-debugadapter-e8723dd9.json.gz)

**VS Code Version:** `1.77.3` and nightly debugger `v2023.5.317`

**Additional context**

https://user-images.githubusercontent.com/111001237/236569170-79b907e9-2101-4adb-8f3b-6aa34ed3e9ae.mp4

If the folder above could not be downloaded, here are my individual files:
`.vscode/launch.json`:
```json
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "skipFiles": [
        "<node_internals>/**",
        "**/node_modules/**",
      ],
      "program": "${workspaceFolder}/index.js",
      "trace": true,
    }
  ]
}
```
`index.js`:
```js
const Jasmine = require('jasmine');
const jasmine = new Jasmine();
// run it blocks sequentially
jasmine.env.configure({ random: false });
debugger;
jasmine.execute(['test.js']);
```
`test.js`:
```js
describe('test', function() {
  it('a', function () {
    debugger;
  });
  it('b', function () {
    console.log('hello world')
  })
  it('c', function () {
    debugger;
  })
});
```
`package.json`:
```json
{
  "name": "stepover",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "jasmine": "^4.6.0"
  }
}
```

**Comment by connor4312** [comment]
This is because we reach the maximum of 16 steps before the debugger starts backing out. Maybe this limit should be raised , e.g. 128 seems to work

https://github.com/microsoft/vscode-js-debug/blob/52b31fcd59a204bb9f276b877cfb7eb42c09ca33/src/adapter/smartStepping.ts#L44

**Comment by c3danielxu** [comment]
Hi @connor4312 thanks for the response! You're right I can reproduce this behavior without Jasmine too:
```js
function recursive(x) {
  if (x === 0) return;
  recursive(x-1);
}

recursive(10000); // put breakpoint here and step over
console.log('hello world') // code does not pause on this line
```
I actually have another case where I'm using a library that makes a lot of JavaScript calls with a deep call stack but using the Jasmine example was the simplest way I could reproduce it until now. Is there some way for the debugger to handle an arbitrary number of steps other than by increasing the limit?

**Comment by connor4312** [comment]
The limit is mostly there in the event that there's no un-skipped code to run (at least not for a while) and slowing the program to a crawl as a result. For example, if you stepped over the last test and there was still a lot of work to do, like writing a test coverage file. However raising the limit to something in the hundreds should be fine, since each pause/resume generally only takes a few milliseconds (<5)

**Comment by c3danielxu** [comment]
I see, does this mean that as long as I have almost all the JavaScript calls under `skipFiles` and we raise the limit to something in the hundreds, I should be able to step over a "heavy" function call provided by any library? The two cases I have are pretty similar, I step over something, have most of the executing code under `skipFiles`, and at the end I want to pause on the next line that isn't covered by `skipFiles`.

**Comment by c3danielxu** [comment]
Hi @connor4312 just wanted to follow up on this, if raising `smartStepBackoutThreshold` is a working solution, when would this change be made? Thank you!
