### ISSUE TITLE
While debugging, double-escaped apostrophe displays differently in hover of variable and console

### ISSUE THREAD

**Issue by slashinpdx** [microsoft/vscode-js-debug#1708]
To reproduce:

const x = \`\\\\'`; // either quotation mark or tick used to enclose
debugger;

(run code)
While debugging, hover over x to see: '\\\\''
In console, type x and press enter to see: '\\''

**Comment by connor4312** [comment]
Merging into https://github.com/microsoft/vscode/issues/182835
