### ISSUE TITLE
"Debugger for Chrome (Nightly)" not properly deprecated in VSCode Marketplace

### ISSUE THREAD

**Issue by darkvertex** [microsoft/vscode-js-debug#1710]
I thought it was weird that you guys deprecated the main old extension page:
https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome
but appear to have forgotten the "nightly" page for the same extension:
https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome-nightly

Inside VSCode:
![image](https://github.com/microsoft/vscode-js-debug/assets/941331/01c7f6c8-b4ba-4547-a542-f70a63a54ca6)

---
ps: I'm reporting it here as per the README from https://github.com/Microsoft/vscode-chrome-debug saying to report new issues in this repo.

**Comment by connor4312** [comment]
Thanks, I've now made this change (make take a few hours to propagate due to caching)
