### ISSUE TITLE
Can't find Node.Js 

### ISSUE THREAD

**Issue by Nup3** [microsoft/vscode-js-debug#1711]
Hello,

I am trying to Run and Debug using Node.js. When I attempt to do it I get the following error message every time. Kindly note that I am on the 2019 Mac Book Pro

Can't find Node.js binary "node": path does not exist. Make sure Node.js is installed and in your PATH, or set the "runtimeExecutable" in your launch.json

**Comment by connor4312** [comment]
Where is Node installed? It is on the PATH and set such that the path is accessible to VS Code?
