### ISSUE TITLE
[Bug/Question] Breakpoint auto-relocate to other file in V1.78.0

### ISSUE THREAD

**Issue by EzioLi01** [microsoft/vscode-js-debug#1715]
Hey @connor4312 , I'm the maintainer of microsoft/react-native-tools repo. Currently I noticed a behavior from `V1.78.0 built-in`(nightly version is from `v2023.4.2709`), when I debug react-native project using `react-native-tools`(depend on js-debug) extension, put a breakpoint in App.tsx then it auto changes to require.js file. 

I'm not sure it's the issue or design by some updates, could you please help to look into this and give me the guidance? Thank!

https://github.com/microsoft/vscode-js-debug/assets/19662219/e91c1a9d-d2db-4dd2-b9d3-af95d54dacbb

If you need other info, please let me know.

**Comment by EzioLi01** [comment]
Seems it caused by PR https://github.com/microsoft/vscode-js-debug/pull/1669, but not sure it's the expected behavior.

**Comment by connor4312** [comment]
Could you grab a trace log using the instructions in the issue template?

**Comment by EzioLi01** [comment]
> Could you grab a trace log using the instructions in the issue template?

Please check if it's readable. Anything else please let me know.
[vscode-debugadapter-c38e1e8c.json.gz](https://github.com/microsoft/vscode-js-debug/files/11711413/vscode-debugadapter-c38e1e8c.json.gz)

**Comment by EzioLi01** [comment]
Hey @connor4312, just kindly reminder that do we have any plan on this?
