### ISSUE TITLE
Breakpoints not binding / Auto Attach npm run serve

### ISSUE THREAD

**Issue by theauthorer** [microsoft/vscode-js-debug#1717]
Hello together,

When running npm run serve with auto attach I see the debugger being attached to each of the 4 processes that are being spawned.
However, I can't set any Breakpoints because they are not binding.

I have sourceMap set to true in my tsconfig.json
I tried all sorts of different configurations without actually knowing what I'm trying there. For example I crated a launch Task which simply ran `npm run serve` where I also configured `sourceMap = true` and also tried other stuff people mentioned in other conversations like setting sourceMapPathOverrides. 

Is there a way to actually see what is going wrong during Breakpoint binding? The most debug information I was able to get was adding trace = true to my launch config. 

Any help appreciated

**Comment by connor4312** [comment]
Please share the trace log produced by that setting. You can run npm with a launch config like:

```
{
    "name": "Run npm serve",
    "request": "launch",
    "runtimeArgs": ["run", "serve"],
    "runtimeExecutable": "npm",
    "type": "node",
},

```

**Comment by theauthorer** [comment]
@connor4312 Sent you the log file via email

**Comment by connor4312** [comment]
It looks like your breakpoint maps to a location in `dist/js/app.js`, but that's never loaded in your debug session. Just based on the script events, it seems like you're using npm to run a webpack process. Are you expecting `dist/js/app.js` to be loaded in a browser? If so, you may want to check out [Browser debugging in VS Code](https://code.visualstudio.com/docs/nodejs/browser-debugging).

**Comment by theauthorer** [comment]
Hello @connor4312 that actually pointed me into the right direction. The final solution was to actually get rid of any source map modifying settings and just adding a clean Browser launch config with a pre launch task

launch.json
```json
{
	"type": "chrome",
	"request": "launch",
	"name": "vuejs: chrome",
	"url": "http:/localhost:8080",
	"preLaunchTask": "vuejs: start"
},
```

tasks.json
```json
{
	"type": "chrome",
	"request": "launch",
	"name": "vuejs: chrome",
	"url": "http:/localhost:8080",
	"preLaunchTask": "vuejs: start"
},
```

Thank you very much for the input!
