### ISSUE TITLE
Worker breakpoints don't bind

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-js-debug#1718]
**Describe the bug**
Given a simple worker built using webpack, setting a breakpoint in the worker.ts file doesn't ever bind. I can only bind breakpoints in the js file.
[WorkerDebug.zip](https://github.com/microsoft/vscode-js-debug/files/11691610/WorkerDebug.zip)

**To Reproduce**
1. Unzip the attached folder
2. Open folder in VS code
3. Run `npm install`
4. Run `npm run build`
5. Run `npm run webpack:worker`
6. Set a breakpoint in the 'src\worker.ts' file
7. Launch the debugger
8. Breakpoint will not be hit.

**Log File**
[vscode-debugadapter-dea172cb.json.gz](https://github.com/microsoft/vscode-js-debug/files/11691607/vscode-debugadapter-dea172cb.json.gz)

**VS Code Version:** 1.78.2

**Additional context**
Also tried just building the worker using tsc instead of webpack, same result.

**Comment by connor4312** [comment]
You must enable `"sourceMap": true` in your tsconfig.json

**Comment by rchiodo** [comment]
That didn't fix it for me? Dev tool was already source map in the webpack.worker.config.js, but also adding it to the tsconfig.json had no effect.

**Comment by connor4312** [comment]
Yep

**Comment by rchiodo** [comment]
Yeah that has no effect. Breakpoint still isn't hit. Perhaps something else is interfering?

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode-js-debug/assets/2230985/800e29ff-993f-49b9-b3c8-dbf8333d75b0

This is what I'm trying

**Comment by rchiodo** [comment]
Oh you're using insiders. Let me try that.

**Comment by connor4312** [comment]
And [js-debug-nightly](https://github.com/microsoft/vscode-js-debug#nightly-extension). If it doesn't work, please get a new trace log once sourcemaps are enabled.
