### ISSUE TITLE
Breakpoints for worker bind after the worker has already started

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-js-debug#1719]
**Describe the bug**
If your worker map file is too large, breakpoints won't bind until after the worker is already running

**To Reproduce**
The only steps I have to reproduce is to use our real product. I'm running a worker thread that contains our entire language server and the breakpoints for the worker thread bind on a time delay after the worker has actually started.

Meaning I can't debug startup of the worker thread.

The breakpoints do bind later, and I can debug messages sent to the server (as I can stick a breakpoint in the client).

**Log File**

[vscode-debugadapter-d1089d59.json.gz](https://github.com/microsoft/vscode-js-debug/files/11692734/vscode-debugadapter-d1089d59.json.gz)

**VS Code Version:** 1.79.0-insiders

**Additional context**

**Comment by roblourens** [comment]
Hey @rchiodo, is this working for you now?

**Comment by rchiodo** [comment]
Yep, working good. I used it everyday now.
