### ISSUE TITLE
Debugger not working with tsx

### ISSUE THREAD

**Issue by TheChilliPL** [microsoft/vscode-js-debug#1727]
**Describe the bug**
Trying to run the debugger with globstar running tests via tsx seems to crash the debugger:
```
PS C:\Users\drago\WebstormProjects\juan> npm test
Debugger attached.

> juan@0.1.0 test
> globstar -- node --no-warnings --loader tsx --test "src/tests/**/*.ts"

Debugger attached.
Error in the js-debug bootloader, please report to https://aka.ms/js-dbg-issue: undefined
Debugger attached.
```

**To Reproduce**
[unknown]

**Log File**

I don't use `launch.json`, it doesn't seem to be recognized by VS Code at all for me. I just use JavaScript Debug console, so I don't know how to do that.

**VS Code Version:**
> Version: 1.80.0-insider (user setup)
> Commit: db6bcdf309cc1565c502a54b73c33a63bdabfbd8
> Date: 2023-06-09T05:21:13.157Z
> Electron: 22.5.5
> Chromium: 108.0.5359.215
> Node.js: 16.17.1
> V8: 10.8.168.25-electron.0
> OS: Windows_NT x64 10.0.25375

**Additional context**
N/A

**Comment by connor4312** [comment]
Thanks for the issue. I added better logging in the latest [nightly version](https://github.com/microsoft/vscode-js-debug#nightly-extension) of the extension. Please try that and, if you still get this error, share the output.

**Comment by connor4312** [comment]
Thanks, this appears to be a Node.js bug. I've reported it on https://github.com/nodejs/node/issues/48467
