### ISSUE TITLE
New settings for this extension not recognized

### ISSUE THREAD

**Issue by jtsom** [microsoft/vscode-js-debug#173]
The new settings that are in the instruction, that need to be added to the settings.json file, are shown as "unknown settings" in vscode:

<img width="301" alt="image" src="https://user-images.githubusercontent.com/13488/70808009-c969c300-1d8c-11ea-81a6-203e9b6dbc60.png">

```
Version: 1.42.0-insider
Commit: cbeff45f80213db0ddda2183170281ed97ed3b12
Date: 2019-12-13T07:05:12.353Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0
```

**Comment by connor4312** [comment]
The setting still works, but we should make this visible now that the extension has been announced in preview.

**Comment by roblourens** [comment]
Yeah, I can do that. Will add one for EH debugging too.

**Comment by jtsom** [comment]
Still showing as unavailable with the latest release.

**Comment by roblourens** [comment]
It will be in the next insiders on Monday

**Comment by jtsom** [comment]
After updating to the latest Insiders, "debug.node.useV3", along with one for "extensionHost" are now showing as available, but the debug.chrome.V3 is still not enabled:

<img width="339" alt="image" src="https://user-images.githubusercontent.com/13488/70911321-ad119480-1fdf-11ea-813a-8082d566307c.png">

**Comment by roblourens** [comment]
I haven't republished the extension yet.

**Comment by jtsom** [comment]
Several versions of the extension have been put out, and the debug.chrome.useV3 still shows as an unknown setting. 
Name: JavaScript Debugger (Nightly)
Id: ms-vscode.js-debug-nightly
Description: An extension for debugging Node.js programs and Chrome.
Version: 2020.1.5284
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug-nightly

**Comment by jtsom** [comment]
This setting is still showing as unavailable, as of the latest Insiders version and latest version of the extension:
Name: JavaScript Debugger (Nightly)
Id: ms-vscode.js-debug-nightly
Description: An extension for debugging Node.js programs and Chrome.
Version: 2020.1.31743
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug-nightly

Version: 1.42.0-insider
Commit: c4d53a19df8799f5d49a4f49a6900c499e6fa27c
Date: 2020-01-23T05:38:55.065Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.2.0

<img width="240" alt="image" src="https://user-images.githubusercontent.com/13488/72986750-e72c3e00-3db6-11ea-9803-99f67db84be1.png">
