### ISSUE TITLE
disconnecting a "chrome attach" session terminates the browser 

### ISSUE THREAD

**Issue by ago1024** [microsoft/vscode-js-debug#1733]
**Describe the bug**

Attaching to chrome and disconnecting will terminate the browser starting with ac95032802f2d9f5a5ed88a9cc5a64232b488cba

**To Reproduce**
1. Start `chrome --remote-debugging-port=9222`
2. Start 'Attach to Chrome' debug target
~~~
		{
			"name": "Attach to Chrome",
			"port": 9222,
			"request": "attach",
			"type": "chrome",
		},
~~~
3. Disconnect the debug target
4. Chrome will terminate

**Log File**
[vscode-debugadapter-7c10c29d.json.gz](https://github.com/microsoft/vscode-js-debug/files/11768795/vscode-debugadapter-7c10c29d.json.gz)

**VS Code Version:** 1.79, ms-vscode.js-debug  ac95032802f2d9f5a5ed88a9cc5a64232b488cba

**Comment by ago1024** [comment]
Setting the `supportTerminateDebugee` capability to `true` solved the issue for me

~~~
diff --git a/src/adapter/debugAdapter.ts b/src/adapter/debugAdapter.ts
index 9ed2eb04..25b46337 100644
--- a/src/adapter/debugAdapter.ts
+++ b/src/adapter/debugAdapter.ts
@@ -247,7 +247,7 @@ export class DebugAdapter implements IDisposable {
       supportsExceptionOptions: false,
       supportsValueFormattingOptions: true,
       supportsExceptionInfoRequest: true,
-      supportTerminateDebuggee: false,
+      supportTerminateDebuggee: true,
       supportsDelayedStackTraceLoading: true,
       supportsLoadedSourcesRequest: true,
       supportsLogPoints: true,
~~~

**Comment by mubaidr** [comment]
any update on this issue?
