### ISSUE TITLE
Electron app doesn't launch when debugging in dev container

### ISSUE THREAD

**Issue by oloftus** [microsoft/vscode-js-debug#1736]
**Describe the bug**
When I launch an electron app for debugging via a VS Code launch configuration of type `node` with request `launch`, the electron main script is never run, i.e. no breakpoint is hit, and no electron window opens. The same happens when I run the same command as in the debug configuration (`npx electron .`) in a JS debug terminal. This behaviour only happens when the workspace is running inside a dev container ; on my local machine the same launch configuration works fine.

**Additional context**
I noticed that when I run the command in the JS debug console, node reports three times that the debugger is listening, but only twice that a debugger was attached (see log below). When I manually (via a new launch configuration) attach a debugger using the port from the third "Debugger listening on" statement, the breakpoint is hit and the main window opens.

```
Debugger listening on ws://127.0.0.1:53959/1b1c7b1d-6dd1-417c-b388-91d63cf1300e
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Debugger listening on ws://127.0.0.1:53363/e81d2e65-430d-4f56-b526-5700c62b4e61
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
[2415:0624/183843.696014:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Debugger listening on ws://127.0.0.1:53351/66ec19c8-3795-4e29-b365-6bcc667a2be2
For help, see: https://nodejs.org/en/docs/inspector
```

_Workaround_
Adding `"attachSimplePort": 0` to the launch configuration makes it work inside the dev container. This isn't ideal, however, as some tools like pnpm doesn't recognise the `--inspect-brk` and just exit.

**To Reproduce**
I forked the official [electron/electron-quick-start](https://github.com/electron/electron-quick-start) repo, and added a dev container configuration and a launch configuration to demonstrate the problem.

_Pre-requisites_
- Have Docker Desktop installed locally
- Have the VS Code [Dev Containers extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) installed
- Have an X11 server, e.g. XQuartz running locally. The X service must allow and be listening for network connections.

_Steps_
1. Clone the [forked repo](https://github.com/oloftus/vscode-js-debug-repro)
2. Comment out the following lines in _.devcontainer.json_ otherwise you won't have the necessary privileges once inside the container to do an `npm install`
```
  "securityOpt": [
    "seccomp=chrome_seccomp.json"
  ],
```
4. Run "Dev Containers: Reopen in Container" from the command pallette
5. Run `npm install` from inside the dev container
6. Run "Dev Containers: Reopen Folder Locally" from the command pallette
7. Put back the lines commented in step 2. The seccomp configuration is needed for Chromium to run.
8. Run "Dev Containers: Rebuild and Reopen in Container" from the command pallette
9. Set a breakpoint somewhere in _main.js_
10. Run the "Launch Electron Main" launch configuration and observe that the breakpoint from step 9 isn't hit and no electron window opens
11. Uncomment the line `"attachSimplePort": 0` in _.vscode/launch.json_
12. Run the "Launch Electron Main" launch configuration and observe that the breakpoint from step 9 is hit and the electron window opens when you let the debugger continue from the breakpoint

**Log File**
I wasn't able to get hold of the log file because the seccomp configuration restricts my access to the dev container file system.

**VS Code Version:**
Version: 1.79.2 (Universal)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:58:52.392Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

**Comment by connor4312** [comment]
I have trouble getting this to work, as the Vs Code server fails to run in the container on step (8) with seccomp policies installed.

```
[4463 ms] /vscode/vscode-server-insiders/bin/linux-x64/31f183271b0d1f24a2052f6eccbb76bdef45d60b-insider/node[122]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0xb02960 node::Abort() [/vscode/vscode-server-insiders/bin/linux-x64/31f183271b0d1f24a2052f6eccbb76bdef45d60b-insider/node]
 2: 0xb029de  [/vscode/vscode-server-insiders/bin/linux-x64/31f183271b0d1f24a2052f6eccbb76bdef45d60b-insider/node]
 3: 0xb6fb7e  [/vscode/vscode-server-insiders/bin/linux-x64/31f183271b0d1f24a2052f6eccbb76bdef45d60b-insider/node]
 4: 0xb6fc46 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/vscode/vscode-server-insiders/bin/linux-x64/31f183271b0d1f24a2052f6eccbb76bdef45d60b-insider/node]
 5: 0xac7d64 node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags, node::ProcessFlags::Flags) [/vscode/vscode-server-insiders/bin/linux-x64/31f183271b0d1f24a2052f6eccbb76bdef45d60b-insider/node]
 6: 0xac8949 node::Start(int, char**) [/vscode/vscode-server-insiders/bin/linux-x64/31f183271b0d1f24a2052f6eccbb76bdef45d60b-insider/node]
 7: 0x7faae1cd718a  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7faae1cd7245 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0xa3d03c  [/vscode/vscode-server-insiders/bin/linux-x64/31f183271b0d1f24a2052f6eccbb76bdef45d60b-insider/node]
Aborted (core dumped)
```

I'm just _guessing_ that one of the seccomp policies prohibits the Electron main process from accessing the unix socket that's used to connect subprocess to this debugger. The location of this socket is in the `VSCODE_INSPECTOR_OPTIONS` environment variable if you want to check on it. If that's the case, then I would say that using simpleAttachPort is the workaround (or adjusting whatever security policy that's blocking that connection)

**Comment by connor4312** [comment]
Closing as we've not heard from the OP

**Comment by oloftus** [comment]
Sorry for the delay. @connor4312 you were right, without the seccomp policies the debugger works fine.
Thanks for your response.
