### ISSUE TITLE
Requests stuck at pending when debugging Electron app using attach to chrome.

### ISSUE THREAD

**Issue by cnSchwarzer** [microsoft/vscode-js-debug#1741]
**Describe the bug**
I launch electron app with `--remote-debugging-port=9229` and use `attach-chrome` to debug the renderer processes. (Yes, I will open multiple windows/tabs)

If I attach to the chromium before create windows, the window's request will mostly stuck at pending.

![image](https://github.com/microsoft/vscode-js-debug/assets/29846655/b85397d5-e6ae-4468-933a-ff25c84a15e2)

**To Reproduce**
1. Go to https://github.com/cnSchwarzer/js-debug-issue-1
2. Clone, `npm i --save-dev`, F5 `Debug App` to launch the debug process. Check the opened DevTool UI's Network tab, you'll see requests are stuck at `Pending`. If the page loads normally, try repeat launch the debug session.
3. Stop debugging, and F5 `Debug Main Process`, after window opened, start `Debug Renderer Process`, you'll see the pages loads normally even you refresh the page.

![image](https://github.com/microsoft/vscode-js-debug/assets/29846655/bda195c7-f647-4620-b991-468135c887d1)

**Log File**
[vscode-debugadapter-18f95990.json.gz](https://github.com/microsoft/vscode-js-debug/files/11884856/vscode-debugadapter-18f95990.json.gz)

**VS Code Version:** 
1.18.0-insider

**Additional context**
js-debug `v2023.6.2117`

**Comment by connor4312** [comment]
This appears to be a bug in Electron -- it never responds to the debugger calling `Runtime.runIfWaitingForDebugger` and proceeding with startup. Unfortunately I don't reproduce the issue locally, but I recommend opening an issue [on Electron](https://github.com/electron/electron) and they may be able to provide instructions to get more diagnostic data.

**Comment by cnSchwarzer** [comment]
Thank you for the information!
