### ISSUE TITLE
Child process not terminated

### ISSUE THREAD

**Issue by thenbe** [microsoft/vscode-js-debug#1747]
**Describe the bug**
The top process is killed, but it's immediate *child* is not killed - it's just re-parented.

## `htop` output

Before stopping:

![2023-07-07-15-32-51](https://github.com/microsoft/vscode-js-debug/assets/33713262/6f2da84e-261a-4821-bcfe-8612877435c9)

```bash
│  │  └─ /nix/store/l43bdmxxlkrzwic3q24ik366qyqg3s1g-nodejs-18.16.1/bin/node /nix/store/m82k0dfkwp7m8zyshvrg2pdca67szlgw-pnpm-8.6.5/bin/.pnpm-wrapped vavite-loader vite dev
│  │     └─ node ./node_modules/.bin/../@vavite/node-loader/cli.js vite dev
│  │        └─ node ./node_modules/.bin/../vite/bin/vite.js dev
```

---

After stopping:

![2023-07-07-15-36-06](https://github.com/microsoft/vscode-js-debug/assets/33713262/305e6081-10dc-4aa7-a698-8f724959566b)

```bash
│  │     └─ node ./node_modules/.bin/../@vavite/node-loader/cli.js vite dev
│  │        └─ node ./node_modules/.bin/../vite/bin/vite.js dev
```

---

**To Reproduce**
1. Clone [repro](https://github.com/thenbe/repro-dirty-stop)
1. `pnpm install`
1. In vscode, click the green play button to run the [`launch.json`](https://github.com/thenbe/repro-dirty-stop/blob/master/.vscode/launch.json) config.
1. Click on the stop button.
1. Click the green play button again.
1. Observe error in console `Error: Port 3000 is already in use`

**Log File**

[vscode-debugadapter-a10b2212.json.gz](https://github.com/microsoft/vscode-js-debug/files/11982409/vscode-debugadapter-a10b2212.json.gz)

**VS Code Version:** 1.79.2
**Extension:** ms-vscode.js-debug-nightly v2023.6.2117

**Additional context**

If setting `"killBehavior": "polite"`, the top *two* processes are killed. But the third (`node ./node_modules/.bin/../vite/bin/vite.js dev` seen in output above) is left running.

```
❯ nix-shell -p nix-info --run "nix-info -m"                                                                        04:09:18 
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.36, NixOS, 23.11 (Tapir), 23.11pre501260.78419edadf0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"nixos, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by connor4312** [comment]
I'm not able to reproduce this.

[Killing the process tree uses `pgrep`](https://github.com/microsoft/vscode-js-debug/blob/main/src/targets/node/terminateProcess.sh) to list child processes of a PID. If that's not available on your system or is returning unexpected data, that could lead to the behavior you're experiencing.

**Comment by thenbe** [comment]
Yup, that was it. It runs fine after removing the hardcoded path (some Linux distros, like `nixOS`, do not place these binaries under `/usr/bin`)

```diff
-	for cpid in $(/usr/bin/pgrep -P $1); do
+	for cpid in $(pgrep -P $1); do
```
