### ISSUE TITLE
Unable to launch browser: "Timed out waiting for browser connection"

### ISSUE THREAD

**Issue by rnenjoy** [microsoft/vscode-js-debug#1756]
**Describe the bug**
I installed VSCODE tunnel on my linux server and is running VSCODE 5.1.3 on Windows 11 on my client machine.
VSCODE is connected to my tunnel and i can see all the files. I'm running debug with this configuration:

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "name": "my dev linux server",
      "request": "launch",
      "url": "http://10.0.1.8:3000",
      "webRoot": "${workspaceFolder}",
      "browserLaunchLocation": "ui"
    }
  ]
}
```

Chrome or msedge (both) opens up e blank window (about:blank). And after some seconds VSCODE throws an alert: Unable to launch browser: "Timed out waiting for browser connection".

Am i missing something?

**To Reproduce**
I'm not sure how to replicate this.

**Log File**

**VS Code Version:** 5.1.3

**Additional context**

**Comment by connor4312** [comment]
Can you grab a screen recording of what you see so I can get more context around what's happening? http://gifcap.dev/ is useful

**Comment by rnenjoy** [comment]
![Recording 2023-07-12 at 19 50 41](https://github.com/microsoft/vscode-js-debug/assets/6672175/7cbe166f-25d7-49cc-8c3e-31ac6885a22b)

**Comment by rnenjoy** [comment]
![Recording 2023-07-12 at 19 53 28](https://github.com/microsoft/vscode-js-debug/assets/6672175/cfc25d5c-2db2-47ca-a4ff-e6b960c62b99)

**Comment by rnenjoy** [comment]
Sometimes i get Invalid URL also. Dont very random.

**Comment by rnenjoy** [comment]
Seems to be related to my Remote-Tunnels tunnel to my linux machine. When i use file access instead of the tunnel, it launches correctly the window. But is it possible to launch msedge beta instead of normal msedge?

**Comment by connor4312** [comment]
Yes, by setting `"runtimeExecutable": "beta"

**Comment by rnenjoy** [comment]
> Yes, by setting `"runtimeExecutable": "beta"

Thank you. That worked! Just trying to get attach to work now.

**Comment by connor4312** [comment]
This seems to potentially be some issue in Chrome. We launch with `--remote-debugging-port`, and that error happens because we expect something to be listening on that port, but nothing is within the few second deadline we give it. You could try running `chrome.exe --remote-debugging-port=12345 --user-data-dir=some-temp-dir` manually from a terminal and seeing (a) if anything actually is accessible on http://localhost:12345 and (b) whether any errors are shown when you do.

**Comment by connor4312** [comment]
Please let me know if you're able to investigate that.
