### ISSUE TITLE
New breakpoints are mapped to incorrect lines / sourcemap after Vite HMR in existing attached debugger

### ISSUE THREAD

**Issue by qm965** [microsoft/vscode-js-debug#1761]
**Describe the bug**

**To Reproduce**
https://github.com/microsoft/vscode-js-debug/assets/70834319/a64ebdba-ca5d-492f-9195-61eb5dd233e5

run `pnpm create vite` and select react,typescript template

Version: 1.80.0 (Universal)
Commit: 660393deaaa6d1996740ff4880f1bad43768c814
Date: 2023-07-04T13:39:33.766Z (2 wks ago)
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 21.5.0

refers to: https://github.com/vitejs/vite-plugin-vue/issues/33

**Comment by qm965** [comment]
<img width="915" alt="image" src="https://github.com/microsoft/vscode-js-debug/assets/70834319/e6f300ee-123e-4db9-a472-b5720b668e1f">

**Comment by fnicastri** [comment]
Experiencing something similar with Vite + Typescript + Svelte.
Breakpoints are mapped on localhost:5173/.../file.svelte transpiled file and to the wrong line and not on the source.

**Comment by connor4312** [comment]
@fnicastri that is unrelated, this bug is specifically for HMR.

This may duplicate https://github.com/microsoft/vscode/issues/155331

**Comment by michaellimair** [comment]
Hi @connor4312, was digging around the interwebs and looks like a fix similar to [this one for Webpack HMR](https://github.com/microsoft/vscode-js-debug/pull/1357) will fix the issue. Seems like there needs to be some special handling for Vite HMR URLs (e.g. `?t=123123123123`).

Looks related to this issue in `@vitejs/plugin-react` [https://github.com/vitejs/vite-plugin-react/issues/23]

**Comment by qm965** [comment]
hi, @connor4312 , I have tested this bugfix by visx, which was built by running npm run package in my own native environment.
the breakpoints had not breaked in app.tsx/t=***** file ,but its position will change.

like this:  https://github.com/microsoft/vscode-js-debug/assets/70834319/b00307b9-707c-426b-a2f8-1ea07d2325cf

**Comment by qm965** [comment]
@connor4312 Is this because the breakpoint locations did not change along with the changes in the source code?

**Comment by connor4312** [comment]
Desync like that is kind of expected as the events between the file being saved, vite building an HMR and loading it, and vscode telling the debugger about new breakpoints are not synchronized. But yes unsetting the breakpoint and resetting it in vscode once your changes are HMR'd in should be a very reliable way to have things work.

You don't need to build your own vsix to test it, you can use the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension)
