### ISSUE TITLE
Extensible customDescriptionGenerator by default

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode-js-debug#1773]
I just discovered `customDescriptionGenerator` - I love it! I just wished it would be easier to configure.

At the moment, I have to stop and start a new debug session every time I change this property. It would be very nice if I could just change that property and it would update immediately!

Also, that property is not very well suited for more complex description generators. To work around this, I set a custom description generator that just delegates to `globalThis.$$customDescription` and then used my debug visualizer extension to inject a custom script into the debugger that sets this property.

Generally, I think it would make sense to have a default `customDescriptionGenerator` that can be overriden by setting a globalThis property - then extensions override this property at runtime without having to instruct the user to adjust the launch configuration.

---

This is how it looks currently:
![Code_-_Insiders_1E5wQ7CtFK](https://github.com/microsoft/vscode-js-debug/assets/2931520/d2013664-c1a1-4619-aad7-be903920eaa9)

This is what I managed to get with a `customDescriptionGenerator`:
![UxPw3qXQbM](https://github.com/microsoft/vscode-js-debug/assets/2931520/8b6be9bf-2e49-4f75-8c7f-a11512277306)

(maybe it makes sense to investigate if we can get this behavior by default, can we support custom description generators for property values in objects?)

I used this code:

```js
globalThis.customDescription = (obj, def) => {
    if (Object.getPrototypeOf(obj) !== Object.getPrototypeOf({})) {
        return def;
    }

    const body = Object.entries(obj).map(([key, val]) => {
        return `${key}: ${val}`
    }).join(", ");
    return `{${body}}`;
}
```

And this custom description generator:
```json
"customDescriptionGenerator": "function (def) { return globalThis.customDescription ? globalThis.customDescription(this, def) : def }"
```

**Comment by connor4312** [comment]
We discussed something like this in https://github.com/microsoft/vscode/issues/102181. Going to merge into that PR -- and just do it.
