### ISSUE TITLE
Unbound breakpoint In NextJs 13 With chrome

### ISSUE THREAD

**Issue by DevYemi** [microsoft/vscode-js-debug#1784]
**Describe the bug**
I been unable to bind breakpoints when i launch the debugger, i can add breakpoints before i launch it but immediately i launch it it kinda greys out.

**To Reproduce**
1. Create new next project with "npx create-next-app@latest"
2. Cd into your project And Add Breakpoints
3. Launch the Debugger and you should see the problem

**Log File**

[vscode-debugadapter-0fe75395.json.gz](https://github.com/microsoft/vscode-js-debug/files/12373375/vscode-debugadapter-0fe75395.json.gz)

-->

**Comment by connor4312** [comment]
It looks like you never load the page on which you set breakpoints in the browser. Alternatively, if it a purely a SSR page, then it's expected that there are no scripts for it in the browser and you would need to use a Node debug type instead.

**Comment by DevYemi** [comment]
Thank you, you are actually correct The page where this issue is occurrring is purely SSR. There is actually info on how to set it up in NextJs docs, for anyone else check [https://nextjs.org/docs/pages/building-your-application/configuring/debugging](here) for the config.

I will close the issue now.
