### ISSUE TITLE
[Question] Attach to process starts debug session

### ISSUE THREAD

**Issue by mikicho** [microsoft/vscode-js-debug#1785]
I found a nice surprise: running `node server.js` without `--inspect` and then starting a debug session via [`Debug: Attach to Node process`](https://github.com/microsoft/vscode-js-debug/blob/main/src/ui/processPicker.ts#L31) causes `js-debug` (or `vs code`) to initiate a new debug session on a random port instead of the standard 9229.
I am interested in detecting if the debugger is attached via `inspector.url` to change the test timeout to Infinity during debugging. Otherwise, the test fails after 5 seconds.

I couldn't find the documentation about this behavior so I'm wondering if this is a bug/accident. can I rely on this behavior?

Steps to reproduce:

1. Create a simple server:
```
const http = require('http');

const hostname = '127.0.0.1';
const port = 3000;

const server = http.createServer((req, res) => {
  res.statusCode = 200;
  res.setHeader('Content-Type', 'text/plain');
  res.end('Hello World');
});

server.listen(port, hostname, () => {
  console.log(`Server running at http://${hostname}:${port}/`);
});
```
2. run `node server.js` (again, no `--inspect`)
3. Attach the debugger by the process picker
```
➜  server git:(master) ✗ node server.js
Server running at http://127.0.0.1:3000/
Debugger listening on ws://127.0.0.1:9229/b25db8c5-fe7b-4f23-89c3-f873d0f6b466
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
``` 
Note how the `debugger listening` is after the `Server running`

**Comment by connor4312** [comment]
Yes, inspector.url() will always be set if a debugger is attached (or if the process is waiting for a debugger) https://nodejs.org/api/inspector.html#inspectorurl

**Comment by mikicho** [comment]
@connor4312 Thanks! 

> or if the process is waiting for a debugger

This is my problem! I want to increase the test's timeout only when the debugger is attached. When I'm debugging, the timeout should be Infinity, and when the process is only *waiting* for the debugger, I want the timeout to be normal because I'm not actually debugging.

The unique thing about `js-debug` is that it starts the debugger in the process without requiring the `--inspect` flag, and closes the debug session afterward, giving me the desired behavior.

My question is, how this magic happens? :D Proxy?

**Comment by connor4312** [comment]
Ah, I see. There's not really any API, either from Node or CDP, to do this. You could be clever and observe some subtle side-effects of what js-debug does when it attaches, but these are not API and not easy to detect.

The best way I think is not to use an --inspect flag but instead define a [launch config](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_launch-configuration) that starts your tests and passes some command-line flag to turn off timeouts.

**Comment by mikicho** [comment]
@connor4312 Thanks!

> The best way I think is not to use an...

But the problem is that I working with watch mode (e.g. jest) and can start debug session and stop it within the same process (think about TDD working flow)

**Comment by connor4312** [comment]
Hm. Another 'clever' way would be to have some simple http server listening from your watch task and then use the `preDebugTask` and `postDebugTask` hooks in the launch config to run `curl` and hit a couple endpoints that would toggle the config.

I agree that in your case having some kind of introspection API would be a lot simpler, but I'm not greatly enthused about putting that responsibility in the debugger directly...

**Comment by mikicho** [comment]
> Hm. Another 'clever' way would...

Great idea! I wasn't familiar with these hooks. 
Anyway, I'm surprised that a Node process can't answer if there is a debugger attached to the session.

Just for a reference, we can also set a proxy server to the debugger which expose such the relevant API. 

Thanks again!
