### ISSUE TITLE
WASM debugging support

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#1789]
js-debug should be able to debug WebAssembly.

There's two parts of this. The base devtools experience allows users to step into and around WebAssembly, displayed as WAT. Supporting this can be done pretty easily.

The next step is giving source-level support for debugging. The Chromium team recently made their DWARF debugger [open source](https://source.chromium.org/chromium/chromium/src/+/main:third_party/devtools-frontend/src/extensions/cxx_debugging/). While this very sadly doesn't work out of the box for Rust [yet](https://github.com/rustwasm/wasm-bindgen/issues/2389), it should eventually (we can hope), and it does support any other language that outputs DWARF symbols.

While the extension is built for integration in Chrome devtools, it looks like it's architected in a way that pretty much all the work happens in the `DevToolsPluginWorker`. I think that we could package this up into an node module that the extension could consume and run in a Node worker_thread.

The downside is the the DWARF SymbolBackend includes(?) chunks from LLVM and even compressed is pretty hefty at 11MB, so we may not want to have it included in vscode by default like js-debug is. My thought is that we can have an extension that exports a known API for js-debug to consume, alongside an npm package that ships only the _types_ in the package (or maybe I just copy the types directly into js-debug). We can try to both 
`require('vscode').extensions.getExtension('ms-vscode.js-debug-dwarf')` as well as `require('@vscode/dwarf-debugging')` to enable pure DAP consumers to get this too. And of course we can prompt the user to install this extension when they first step into WASM code.

1. [x] Enable basic debugging with WAT
2. [x] Create a module bundling the devtools c/++ worker debugger
3. [x] Integrate the module into js-debug
4. [x] Externalize the module into an extension with suggestions

**Comment by connor4312** [comment]
This is largely done now in PRs #1803 through #1808. Tomorrow I will do some final cleanup and try to get some tests going, and then it will ship in the nightly.

**Comment by fleabitten232** [comment]
Does this currently support the "path substitution" feature from the Chrome plugin? I compile in a container, which means that the source file paths are incorrect for the machine I want to debug on. 

Appreciate all the work that's been done on this and I'm eager to try it out!

**Comment by connor4312** [comment]
The path goes through the usual path mapping logic in js-debug, so for your case you'd want to set the localRoot/remoteRoot in your launch.json as described in https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_remote-debugging
