### ISSUE TITLE
js-debug does not step into line

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#179]
@eamodio reported that stepping into [here](https://github.com/eamodio/vscode-gitlens/blob/62043b1eb72cf8451f2a81ecc103f6ad75d6c373/src/git/gitService.ts#L2857) does not work. Can be reproduced by opening the file history view in Gitlens, then clicking any commit.

**Comment by connor4312** [comment]
This is upstream. What happens is this (showing the steps with zero-indexed
columns, though there is internally conversion at various steps):

1. A user sets a breakpoint at column 0 in 

```js
      const [renamedRef, renamedFile] = GitLogParser.parseSimpleRenamed(data, fileName);
^
```

2. We correctly map it back through the sourcemap and unambiguously resolve it to column 12
   in the compiled sources, the start of `const`. And we tell V8 that we
   want a breakpoint there.

```js
            const [renamedRef, renamedFile] = _git__WEBPACK_IMPORTED_MODULE_11__["GitLogParser"].parseSimpleRenamed(data, fileName);
            ^
```

<details>
<summary>Log</summary>

```json
{
  "tag": "cdp.send",
  "timestamp": 1576608158938,
  "metadata": {
    "message": {
      "id": 12,
      "method": "Debugger.setBreakpointByUrl",
      "params": {
        "urlRegex": "file:\\/\\/\\/Users\\/copeet\\/Github\\/vscode-gitlens\\/dist\\/extension\\.js|\\/Users\\/copeet\\/Github\\/vscode-gitlens\\/dist\\/extension\\.js",
        "lineNumber": 54375,
        "columnNumber": 12
      }
    }
  },
  "level": 0
}
```
</details>

3. V8 tells us it _actually_ resolved this at column 19, where renamedRef is
declared.

```js
            const [renamedRef, renamedFile] = _git__WEBPACK_IMPORTED_MODULE_11__["GitLogParser"].parseSimpleRenamed(data, fileName);
                   ^
```
<details>
<summary>Log</summary>

```json
{
  "tag": "cdp.receive",
  "timestamp": 1576608158960,
  "metadata": {
    "message": {
      "id": 12,
      "result": {
        "breakpointId": "2:54375:12:file:\\/\\/\\/Users\\/copeet\\/Github\\/vscode-gitlens\\/dist\\/extension\\.js|\\/Users\\/copeet\\/Github\\/vscode-gitlens\\/dist\\/extension\\.js",
        "locations": [
          {
            "scriptId": "267",
            "lineNumber": 54375,
            "columnNumber": 19
          }
        ]
      }
    }
  },
  "level": 0
}
```
</details>

4. This location doesn't get hit until after `parseSimpleRenamed` is invoked. So trying to step in when you hit this line does not work. However, you can set a breakpoint above the line and step down to it, then in, as a workaround.

I can actually reproduce this in Chrome as well. I'll open a bug on them.

![image](https://user-images.githubusercontent.com/2230985/71026588-6777c900-20be-11ea-8176-53a851428b92.png)

**Comment by roblourens** [comment]
Is this the same as https://bugs.chromium.org/p/chromium/issues/detail?id=782461&can=4&q=breakpoint&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified ?

**Comment by connor4312** [comment]
yep looks like it

**Comment by connor4312** [comment]
Closing as it's upstream. No changes needed on our end if/when this is solved in Chromium.
