### ISSUE TITLE
WSL: Blank screen on Chrome when attaching to debugger

### ISSUE THREAD

**Issue by MrBrN197** [microsoft/vscode-js-debug#1793]
I'm attempting to debug from WSL. on Windows "attaching to chrome" opened with remote debugging works correctly.
tyring to attach to the same debugging port through WSL doesn't work. 
explicitly setting the port and setting the address to the wsl address doesn't seem to help.

I set a timeout value and when the timeout expires I get this error message:
"Timed out waiting for browser connection."
With the same settings in Windows it attaches correctly.

this is my configuration.
```
{
	"name": "ChromeDebug",
	"type": "chrome",
	"request": "attach",
	"port": 8100,
	"timeout": 1500,
	// "address": "127.0.0.1",
	"url": "http://localhost:5500",
	"webRoot": "${workspaceFolder}",
}
```

**Comment by connor4312** [comment]
Can you collect logs using the instructions in the "bug" issue template?

**Comment by MrBrN197** [comment]
@connor4312 hi I'll check it and do that.
