### ISSUE TITLE
Skipfiles not working for extension

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#180]
@eamodio debugging gitlens:

> I also have "skipFiles": ["<node_internals>/**", "**/node_modules/**", "**/resources/app/out/vs/**"], set but I still hit stuff in async_hooks.js

May be fixed in https://github.com/microsoft/vscode-js-debug/pull/94

**Comment by roblourens** [comment]
Closing in favor of https://github.com/microsoft/vscode-js-debug/issues/64
