### ISSUE TITLE
Cannot set breakpoints in Vite within Docker image

### ISSUE THREAD

**Issue by KrisDavie** [microsoft/vscode-js-debug#1800]
**Describe the bug**
After trying anything I can find suggestions of, I am unable to get breakpoints within VSCode to work - they always remain as "Unbound breakpoint" - I'm relatively new to this, so maybe I've missed something obvious bit I've been struggling with this for days now and it seems like it should just be working. In chrome, I am able to use the sources page and set breakpoints in DevTools - these work as expected, they just never work in VSCode

**To Reproduce**
1. Install vite-redux template `npx degit reduxjs/redux-templates/packages/vite-template-redux && npm i`
2. Configure `tsconfig.json`,  `vite.config.js`, `launch.json`, `tasks.json` and `Dockerfile` (contents below)
3. Run & Debug with F5

The Docker image is built, and the app is launched. In the debug terminal, I can see the output from node and I am able to `Right Click -> Open in Browser -> 5173` the container in VSCode to open the webpage, but breakpoints never work within VSCode. 

**Log File** [vscode-debugadapter-8e54c9db.json.gz](https://github.com/microsoft/vscode-js-debug/files/12590226/vscode-debugadapter-8e54c9db.json.gz)

**VS Code Version:** 1.82.0

**Additional context**
I have the same issue in VSCode-insiders
Possible duplicate of https://github.com/microsoft/vscode-js-debug/issues/1799, however they aren't using Docker

Any help would be greatly appreciated!

`tsconfig.json`
```
{
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "allowJs": false,
    "skipLibCheck": true,
    "esModuleInterop": false,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "module": "ESNext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "types": ["testing-library__jest-dom"],
    "sourceMap": true
  },
  "include": ["src"],
  "references": [{ "path": "./tsconfig.node.json" }]
}
```

`vite.config.ts`
```
import { defineConfig } from "vitest/config"
import react from "@vitejs/plugin-react"

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  server: {
    open: false,
    host: true,
    watch: {
      usePolling: true,
    },
  },
  build: {
    outDir: "build",
    sourcemap: true,
  },
  test: {
    globals: true,
    environment: "jsdom",
    setupFiles: "src/setupTests",
    mockReset: true,
  },
})
```
`Dockerfile`
```
FROM node:lts-alpine

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5174
EXPOSE 9229
```

`launch.json`
```
{
  "configurations": [
    {
      "name": "Docker Node.js Launch",
      "type": "docker",
      "request": "launch",
      "preLaunchTask": "docker-run: debug",
      "platform": "node",
      "trace": true
    }
  ]
}
```

`tasks.json`
```
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "docker-build",
      "label": "docker-build",
      "platform": "node",
      "dockerBuild": {
        "dockerfile": "${workspaceFolder}/Dockerfile",
        "context": "${workspaceFolder}",
        "pull": true
      }
    },
    {
      "type": "docker-run",
      "label": "docker-run: debug", 
      "dependsOn": ["docker-build"],
      "dockerRun": {
        "env": {
          "DEBUG": "*",
          "NODE_ENV": "development"
        },

        "command": "node --inspect=0.0.0.0:9229 node_modules/vite/bin/vite.js",
        "remove": true
      },
      "node": {
        "enableDebugging": true
      }
    }
  ]
}

```

**Comment by connor4312** [comment]
It looks like you've captured the log for the node.js Vite process, not the browser. Please capture the trace log for the browser. To do this you'll need a launch config: https://code.visualstudio.com/docs/nodejs/browser-debugging#_launching-browsers

**Comment by KrisDavie** [comment]
So, I added the config to `launch.json` to launch a browser session rather than using the `attach` request to connect directly to the node debugger, and now breakpoints are working. 

I'm not entirely sure why this is the case and why it wasn't working with the attach version, but seems like this is probably a me issue and not on your end! Thanks for your time and sorry for the noise!

**Comment by connor4312** [comment]
No worries. It seems like you tried to debug the Node.js process of the Vite dev server. This would be useful if you're a developer working on Vite itself, but for your application you need to debug the browser.
