### ISSUE TITLE
Using source maps with eval and inner functions are not hitting breakpoints

### ISSUE THREAD

**Issue by shashankvidiyalaC3** [microsoft/vscode-js-debug#1835]
**Describe the bug**

The breakpoints are not being recognized if we use eval which has inner functions and source maps.

**To Reproduce**

1. Create two files addNum.js and evalAddNum.js with the following content
### addNum.js
```
({
  addNum: function addNum(a, b, c) {
    return a + b + c;
  }
});
```
### evalAddNum.js
```
k = eval(`({
  addNum: function addNum(a, b, c) {
    return a + b + c;
  }
});

//# sourceURL=/Users/shashank/Documents/debug-test/newsrcmapbug/addNum.js
//# sourceMappingURL=/Users/shashank/Documents/debug-test/newsrcmapbug/script-compiled.js.map
`);

try{
k.addNum(1,2,3);
} catch{};
```

2) generate the source map for evalAddNum.js and add breakpoints in evalAddNum.js
3) The breakpoints don't seem to hit.

It was working with the previous version of the debugger not sure when it was broken

**Log File**
[vscode-debugadapter-7e13d83c.json.gz](https://github.com/microsoft/vscode-js-debug/files/12835657/vscode-debugadapter-7e13d83c.json.gz)

**VS Code Version:** 1.82.2

**Additional context**
I am using the nightly extension. This is a working correctly on 1.80.0 recently upgraded and saw this issue
Video 

files [newsrcmapbug.zip](https://github.com/microsoft/vscode-js-debug/files/12835672/newsrcmapbug.zip)

https://github.com/microsoft/vscode-js-debug/assets/105740053/31fb3130-9af0-4675-ab82-bbca77e861dc

**Comment by connor4312** [comment]
This should be fixed by https://github.com/microsoft/vscode-js-debug/pull/1833, please try the [nightly extension](https://github.com/microsoft/vscode-js-debug#nightly-extension).

I appreciate the really nice issue and repro you've made 🙂

**Comment by shashankvidiyalaC3** [comment]
Thanks, Connor looks like its fixed in the latest nightly extension.
