### ISSUE TITLE
content.lastIndexOf is not a function

### ISSUE THREAD

**Issue by Rabbitzzc** [microsoft/vscode-js-debug#1839]
https://github.com/microsoft/vscode-js-debug/blob/eb545faf20e798ca6abcd9a11cc89af4422b4467/src/common/sourceUtils.ts#L228C11-L228C18

Should be 
```ts
pos = `${content}`.lastIndexOf(name, pos);
```

**Comment by connor4312** [comment]
Why should it be that way? Content should always be a string.
