### ISSUE TITLE
BreakPoints are not getting hit

### ISSUE THREAD

**Issue by sumeet2714** [microsoft/vscode-js-debug#1840]
**Describe the bug**
 My project uses monorepo's with lerna bootstrap. After updating to - September 2023 (version 1.83), now breakpoints are not getting bound

**To Reproduce**

**Log File**

**VS Code Version:** Replace me!

**Additional context**

**Comment by connor4312** [comment]
Probably duplicates https://github.com/microsoft/vscode-js-debug/pull/1833, please try the [nightly extension](https://github.com/microsoft/vscode-js-debug#nightly-extension). Fix will be released to stable in a few days.
