### ISSUE TITLE
Unable to bind breakpoint while debugging React 18 app in chrome

### ISSUE THREAD

**Issue by edishu** [microsoft/vscode-js-debug#1842]
**Describe the bug**
When I try to add breakpoints in my react 18 code I get this warning:
`Some of your breakpoints could not be set.`

![image](https://github.com/microsoft/vscode-js-debug/assets/37514088/1daa66a1-474f-4790-a0b3-a62ea043ef93)

On clicking the troubleshoot link I get:
```
❓ We sent the breakpoint, but it didn't bind to any locations. If this is unexpected:
Make sure that your program is loading or running this script. You can add a debugger; statement to check this: your program will pause when it hits it.
If your breakpoint is set in certain places, such as on the last empty line of a file, the runtime might not be able to find anywhere to place it.
If necessary, make sure your compiled files are up-to-date with your source files.
```

And navigating app to hit the breakpoint does not break it.

**To Reproduce**
launch.json configuration:
```
{
  [
    {
      "name": "Demo - 3000",
      "request": "launch",
      "type": "chrome",
      "url": "http://demo.com:3000",
      "webRoot": "${workspaceFolder}"
    }
  ]
}
```
*My local app is server at `http://demo.com:3000`

React version: 18.2.0
Webpack version: 5.88.2
@babel/core version: 7.23.0
Typescript version: 4.9.5

**VS Code Version:** 1.83.0

**Comment by connor4312** [comment]
Does this work using the [nightly extension](https://github.com/microsoft/vscode-js-debug#nightly-extension)?

**Comment by edishu** [comment]
> Does this work using the [nightly extension](https://github.com/microsoft/vscode-js-debug#nightly-extension)?

I've not tried this but updated my vscode to version: `1.83.1` yesterday and it is working now 🎉
