### ISSUE TITLE
Breakpoints didn't bind to any locations after upgrading to 1.83.0 (Universal) for Mac

### ISSUE THREAD

**Issue by tanyak1601** [microsoft/vscode-js-debug#1844]
**All breakpoints not binding in VSCode after upgrading to 1.83.0 on `MacOS`**

I use the following config:
{
      "name": "Launch Chrome",
        "request": "launch",
        "type": "chrome",
        "url": "http://localhost:3000",
        "webRoot": "${workspaceFolder}",
}

Breakpoints in Chome itself work fine
In the previous version 1.82.3 everything worked fine

On debug diagnostic page I see the folloing:
![image](https://github.com/microsoft/vscode-js-debug/assets/50367908/8400571b-b5c6-415e-acec-4e4a1db5ac64)

**VS Code Version:** 1.83.0

**Comment by connor4312** [comment]
This is fixed already on the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension)
