### ISSUE TITLE
RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-js-debug#185]
![image](https://user-images.githubusercontent.com/641685/70965126-9a897080-205c-11ea-87f5-2fcfd8efeb1a.png)

I was modifying code while debugging and then hit restart.
[vscode-debugadapter.zip](https://github.com/microsoft/vscode-js-debug/files/3971461/vscode-debugadapter.zip)

**Comment by eamodio** [comment]
This was caused by un-runnable code (I didn't notice the compile error at first)

**Comment by connor4312** [comment]
This looks like it's upstream in [source-map](https://github.com/mozilla/source-map). If you encounter this again, can you grab the source map file(s) and open an issue there?

**Comment by eamodio** [comment]
Opened: https://github.com/mozilla/source-map/issues/412

**Comment by connor4312** [comment]
Remains an issue upstream but I'm closing this here for housekeeping.
