### ISSUE TITLE
debugger: continueOnAttach 

### ISSUE THREAD

**Issue by nojvek** [microsoft/vscode-js-debug#187]
When attaching to a whole bunch of different kinds of apps via a debug adapter, the debugger always starts a break point state where users needs to continue so it hits the user defined breakpoint. Would be great to have "continueOnAttach" in debugger config.

```json
        {
            "name": "Nodejs Attach",
            "type": "node",
            "request": "attach",
            "port": 9229,
            "smartStep": true,
            "continueOnAttach": true
        },
```

this would mean when I start node in --inspect-brk mode like `node --inspect-brk node_modules/webpack/bin/webpack.js`. I can simply hit `F5` to start debugging and land on the breakpoint. Because 99.9% of the time when the debugger connects I just want it to continue.

**Comment by connor4312** [comment]
Added in https://github.com/microsoft/vscode-js-debug/commit/09bffbb12174fbd85d95ab9f30eeef49e2457f9b
