### ISSUE TITLE
Sourcemaps for node_modules packages when running from "debug test"

### ISSUE THREAD

**Issue by NickBolles** [microsoft/vscode-js-debug#1872]
I'm working with a package `QE` lets call it that wraps playwright with some utilities, which is used within our app. I'm trying to enable source maps such that we can run playwright tests from our app and step into the `QE` package to debug. Ultimately I'd like to get this working with `yalc` so that we can debug and develop changes side by side. 

This works fantastically when we run from the Javascript Debug Terminal, but I would like to utilize the VSCode built in Test runner to debug test. When I run with that the sourcemaps aren't picked up. I've tried playing with `debug.javascript.terminalOptions` and `debug.javascript.pickAndAttachOptions` `resolveSourceMapLocations` settings (I believe `debug.javascript.terminalOptions`=>`resolveSourceMapLocations`=null is what makes the javascript debug terminal source maps work). 

So my primary question is, is there a `resolveSourceMapLocations` setting for the "Debug Test" functionality in VS Code?

**Comment by connor4312** [comment]
VS Code doesn't have a built-in test runner; you will want to look up whatever extension you're using to run tests to see if/how it allows passing options to js-debug.

**Comment by NickBolles** [comment]
@connor4312 I guess the extension is playwright then. I'll make an issue there. I just thought that js-debug had global configuration. Thank you.

**Comment by connor4312** [comment]
Not currently
