### ISSUE TITLE
Disconnect is slow

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#188]
- Debug something
- Stop debugging
- It takes the debug widget noticeably longer to disappear with this adapter than with the previous one.

Should figure out whether the DA is doing something more slowly or whether this has something to do with multi-session debugging in vscode

**Comment by connor4312** [comment]
May be related 206

**Comment by connor4312** [comment]
Seemed in my testing that the 206 fix resolved a couple slow disconnects that I saw. Please reopen this if you still run into this.
