### ISSUE TITLE
when running 'yarn:package', appear  `yarn list --prod --json` error

### ISSUE THREAD

**Issue by Rabbitzzc** [microsoft/vscode-js-debug#1882]
it should add the code in gulp:
```js
gulp.task('compile:lock', async () => {
  fs.copyFileSync('package-lock.json', `${buildDir}/package-lock.json`);
  fs.copyFileSync('yarn.lock', `${buildDir}/yarn.lock`);
});

```
and:
```js
gulp.task(
  'package:prepare',
  gulp.series(
    'clean',
    'compile:static',
    'compile:build-scripts',
    'compile:dynamic',
    'compile:extension',
    **'compile:lock',**
    'package:createVSIX',
  ),
);
```

**Comment by connor4312** [comment]
I don't understand the issue you're facing. 

Also, this repo uses npm, not yarn.

**Comment by Rabbitzzc** [comment]
I'm currently cloning this repository and attempting to build a new vs extension locally. However, I ran into the above error when executing the mentioned command - `yarn list --prod --json`. The result is the same whether I use Yarn or NPM.

**Comment by connor4312** [comment]
Please share the complete console output including the command you're running and the output you're seeing.

**Comment by Rabbitzzc** [comment]
![image](https://github.com/microsoft/vscode-js-debug/assets/26913511/96add5a5-347c-47ea-8bd1-eea08361fad0)

**Comment by connor4312** [comment]
Please provide the command starting from when you clone the repo to get to the state you're in.

**Comment by Rabbitzzc** [comment]
sure.... just
1. `yarn clone`
2. `yarn watch`
3. `yarn package`

**Comment by connor4312** [comment]
As I mentioned, this project doesn't use yarn. Yarn may or may not work, I have not tested it, and we do not support it.
