### ISSUE TITLE
JS debug terminal is too slow to startup on the wsl2 mirrored network mode.

### ISSUE THREAD

**Issue by ZedG2** [microsoft/vscode-js-debug#1886]
First of all, sorry for my poor English.
---

I have been using the wsl2 mirrored network mode for a while, and I encountered this problem at the beginning. So I reported the problem to the vscode repository. But I couldn’t prove that was a vscode issue, not something else. A few days later, the problem was suddenly solved by itself, so I closed the issue. Recently, I started writing a typescript project and found that the problem appeared again.

This is run JS debug terminal on wsl2 bridged network mode, it's fast to startup. (~5s). 

https://github.com/microsoft/vscode-js-debug/assets/7886856/135b928a-8132-49ae-8de2-dbc528ea79e7

This run on wsl2 mirrored network mode, it's too slow to startup. (~6m)
The video has been speed up by 5x.

https://github.com/microsoft/vscode-js-debug/assets/7886856/84b5d550-c26a-4970-990d-1fb350506b92

The example project: [my-app.zip](https://github.com/microsoft/vscode-js-debug/files/13388147/my-app.zip)

Could you help me to solve this problem?

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/198429
