### ISSUE TITLE
Unintentional character class range?

### ISSUE THREAD

**Issue by RedCMD** [microsoft/vscode-js-debug#1888]
the regex `[+-/]` is a character class range consisting of `+`, `,`, `-`, `.` and `/`
I assume this was unintentional and matching agasint comma's `,` shouldn't be allowed

https://github.com/microsoft/vscode-js-debug/blob/14755d4dfdddc28b582217d3750c5553494e49f3/src/ui/basic-wat.tmLanguage.json#L11
https://github.com/microsoft/vscode-js-debug/blob/14755d4dfdddc28b582217d3750c5553494e49f3/src/ui/basic-wat.tmLanguage.json#L15
![image](https://github.com/microsoft/vscode-js-debug/assets/33529441/22c037c2-00df-4fb6-b3c5-7600cb33014c)

simply escaping the `-` dash will fix it
![image](https://github.com/microsoft/vscode-js-debug/assets/33529441/df06f481-b97c-4637-9970-78de9f617125)

**Comment by connor4312** [comment]
indeed - PR welcome :)
