### ISSUE TITLE
pauseForSourceMap with true causes stepOver an eval function hang forevever

### ISSUE THREAD

**Issue by shashankvidiyalaC3** [microsoft/vscode-js-debug#1892]
**Describe the bug**
When pauseForSourceMap is set to true and I try to step over an eval function the debugger hangs forever

**To Reproduce**
1. Try to Debug the following code add breakpoint in line 1 and use options with the following values `pauseForSourceMap: true` , 
 `enableContentValidation: false`
```
k = eval(`({
  addNum: function addNum(a, b, c) {
    return a + b + c;
  }
});

//# sourceURL=/Users/shashank/Documents/debug-test/newsrcmapbug/addNum.js
//# sourceMappingURL=/Users/shashank/Documents/debug-test/newsrcmapbug/script-compiled.js.map
`);
try{
k.addNum(1,2,3);
} catch{};

```

2) Try to step over line 1, the debugger hangs for ever

**Log File**
[vscode-debugadapter-f8edd5e9.json.gz](https://github.com/microsoft/vscode-js-debug/files/13494118/vscode-debugadapter-f8edd5e9.json.gz)

**VS Code Version:** 1.84.2
Using the nightly version

**Additional context**
Source map and source URL files

### script-compiled.js.map
`{"version":3,"file":"script-compiled.js","names":["addNum","a","b","c"],"sources":["addNum.js"],"sourcesContent":["({\n  addNum: function addNum(a, b, c) {\n    return a + b + c;\n  }\n});\n"],"mappings":"AAAA,CAAC;EACCA,MAAM,EAAE,SAASA,MAAM,CAACC,CAAC,EAAEC,CAAC,EAAEC,CAAC,EAAE;IAC/B,OAAOF,CAAC,GAAGC,CAAC,GAAGC,CAAC;EAClB;AACF,CAAC"}`

### addNum.js
```
({
  addNum: function addNum(a, b, c) {
    return a + b + c;
  }
});
```

Was working with older versions 1.83 or older

**Comment by connor4312** [comment]
For verifiers, this bug only appears on Node >=20
