### ISSUE TITLE
Breakpoints either hitting in Libraries or in App folder using NX (Monorepo)

### ISSUE THREAD

**Issue by C-monC** [microsoft/vscode-js-debug#1894]
Hi,

I am struggling to understand the effect of webRoot and sourceMapOverrides. VSCode is silently skipping breakpoints in my setup.
```
    {
      "name": "Debug Frontend",
      "type": "chrome",
      "request": "launch",
      "url": "https://localhost.com",
      "webRoot": "${workspaceFolder}/frontend",
      "trace": true
    },
```
Folder Structure
```
Project/
├─ frontend/
│  ├─ apps/
│  ├─ libs/
│  ├─ tsconfig.base.json
```
After many hours of playing with webRoot and sourceMapOverrides I can only ever get break points to hit in apps/ or in libs/ but never both.
I have produced a log file for what I am calling the default (I guess its not really default because I include "webRoot": "${workspaceFolder}/frontend". In this run breakpoints hit only in the libs/ directory and not in apps/ but VScode does not indicate that the breakpoints are broken - they just get skipped. 
I suspect it could be because of my tsconfig paths?

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "esnext",
    "lib": ["es2020", "dom"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "baseUrl": ".",
    "paths": {
      "@frontend/docwize-models-services": [
        "libs/docwize-models-services/src/index.ts"
      ],
      "@frontend/docwize-ql": ["libs/docwize-ql/src/index.ts"],
      "@frontend/ui": ["libs/ui/src/index.ts"]
    }
  },
  "exclude": ["node_modules", "tmp"]
}

```
[vscode-debugadapter-27210f3d.json.gz](https://github.com/microsoft/vscode-js-debug/files/13496561/vscode-debugadapter-27210f3d.json.gz)

**Comment by connor4312** [comment]
You probably want to use a pathMapping something along the lines of

```
"pathMapping": {
	// your tooling makes the "libs" on /@fs/ followed by the absolute path
	"/@fs/": "/",
	// the stuff in your frontend sources are just on /
	"/": "/apps/docwize/"
}
```

`sourceMapOverrides` won't be applicable because of the way your tooling forms source map URLs
