### ISSUE TITLE
Debugger not binding breakpoints in linked package

### ISSUE THREAD

**Issue by Seredeep** [microsoft/vscode-js-debug#1895]
**Describe the bug**
The VSCode debugger is not binding breakpoints made to a symbolically linked local package (with 'npm link command')

**To Reproduce**
1. Have a local npm package.
2. Link the package with 'npm link'
3. In the consuming application importing the package link it with 'npm link [package name]'
4. Try to set a breakpoint in the linked package
5. Run the consuming application with debugger.
6. Breakpoint doesn't bind. Debug diagnostics shows "sourcemap children: None (does not have a sourcemap)" when it literally has a .map file next to it.

**Log File**
[vscode-debugadapter-31fc4b21.json.gz](https://github.com/microsoft/vscode-js-debug/files/13503197/vscode-debugadapter-31fc4b21.json.gz)

**VS Code Version:** 1.84.2

**Additional context**
WSL being used. Paths are like this:
/base/package
/base/consuming_app
Workspace is open in /base/consuming_app

**Comment by connor4312** [comment]
You will want to configure your `outFiles` as described here: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_source-map-discovery

**Comment by Seredeep** [comment]
May I suggest in that case adding some description of this to debug diagnostics? It suggested I should remove outfiles, which seems literally the opposite of I'm supposed to do

Thank you for your help!

**Comment by Seredeep** [comment]
Still no change. Also tried using resolveSourceMapLocations to no avail @connor4312

**Comment by connor4312** [comment]
Please grab a log file using the updating settings. Thanks!
