### ISSUE TITLE
Can't set breakpoints in node_internal files?

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#1898]
[vscode-debugadapter-240d386b.json.gz](https://github.com/microsoft/vscode-js-debug/files/13540466/vscode-debugadapter-240d386b.json.gz)

Step into `setTimeout` or `console.log`. Set a breakpoint, it is unbound, I thought this was possible, is it not? Was thinking about https://github.com/microsoft/vscode/pull/199898

The visualization of the regex looks off too

<img width="587" alt="image" src="https://github.com/microsoft/vscode-js-debug/assets/323878/a4ac8c27-9d37-4bee-8f32-194b5d3a42dc">

**Comment by connor4312** [comment]
This is a Node.js bug: https://github.com/nodejs/node/issues/51067
