### ISSUE TITLE
Browser auto close error

### ISSUE THREAD

**Issue by Yux77Yux** [microsoft/vscode-js-debug#1900]
**Describe the bug**
After the code debugging starts, the browser automatically closes after about 4 seconds.

**To Reproduce**
1.Open an HTML file through VSCode
2.  Conduct debugging(F5) or non debugging(Ctrl+F5) runs
3. Wait for 4 seconds

**JavaScript Debugger (Nightly) Version:** v2023.12.717

```[tasklist]
### Tasks
```

**Comment by Yux77Yux** [comment]
I am using the Simplified Chinese VSCode. If I uninstall the Simplified Chinese expansion pack, the browser will not automatically close. However, reinstalling the expansion pack will reproduce the error.

The expansion pack for Chinese is Chinese (Simplified) Language

**Comment by connor4312** [comment]
Sorry, this was some debug code that slipped into the last nightly. A new nightly build will be out soon.
