### ISSUE TITLE
Not getting output when logging a lot

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#1904]
Debug this code

```js
setInterval(() => {
    for (let index = 0; index < 10; index++) {
        console.log({ hello: Math.random(), string: 'hello' });
    }
}, 100);
```

It logs a lot of objects but not _that_ many. I see some output, then the output stops while the file's node process takes 100% of CPU. Trace shows that the DA stopped sending updates. Any idea?

[vscode-debugadapter-0b28e4a8.json.gz](https://github.com/microsoft/vscode-js-debug/files/13654526/vscode-debugadapter-0b28e4a8.json.gz)

Increasing the setInterval to slow it down even further, I still had a problem seeing the output

**Comment by roblourens** [comment]
Logging a string- no problem

Debugging this code with Chrome devtools- no problem

**Comment by connor4312** [comment]
This is pausing and resuming a bunch of times similar to https://github.com/microsoft/vscode/issues/195062#issuecomment-1848854354, though I'm not sure why it eventually stalls. I will make a change to avoid this.

**Comment by roblourens** [comment]
Oh yeah, unchecking "caught exceptions" fixes it, but what is throwing in that code?

**Comment by connor4312** [comment]
It throws internally when trying to evaluate `this[Symbol.for('debug.description')]()` seeing if there's a prettier way to show the object. I added a check so that we see if that exists before trying to call it.
