### ISSUE TITLE
Crash with large source maps

### ISSUE THREAD

**Issue by segevfiner** [microsoft/vscode-js-debug#1911]
**Describe the bug**
On trying to debug using the "JavaScript Debug Terminal", a project that has quite a bunch of very large source maps, the debugger, debug adapter & extension host crash with: "Debug adapter process has terminated unexpectedly (Extension host shut down)".

**To Reproduce**
1. Debug a project with very large source maps using the "JavaScript Debug Terminal".

My project is proprietary, so I can't provide it directly as a repro, but I will see if I can mock something similar that exhibits the same behavior if you can't figure out what's going on from logs alone.

**Log File**

[vscode-debugadapter-28a26b60.json.gz](https://github.com/microsoft/vscode-js-debug/files/13773182/vscode-debugadapter-28a26b60.json.gz)

It also sometimes produces a cpuprofile in the "Window" log of VS Code:
<img width="1139" alt="image" src="https://github.com/microsoft/vscode-js-debug/assets/24731903/974122a3-96d3-4209-9826-2515f8a3f22d">
[exthost-d35bd5.cpuprofile](https://github.com/microsoft/vscode-js-debug/files/13773172/exthost-d35bd5.cpuprofile)

**VS Code Version:** 1.85.1

**Additional context**
Wasn't able to figure out exactly why it crashes. As in, if it hangs the extension host, and gets terminated by something, OOM, or something else... Any ideas how to figure this out?

**Comment by connor4312** [comment]
That appears to be in this function https://github.com/TooTallNate/proxy-agents/blob/b133295fd16f6475578b6b15bd9b4e33ecb0d0b7/packages/data-uri-to-buffer/src/index.ts#L8-L39

While that's not super fast (the base64 decoder I wrote for vscode itself is 3x faster) I don't see it being _that_ slow. Parsing 100MB of data through that takes about 3.5 seconds, which is not fast, but it's not a crash and that would be "very big" as far as sourcemaps go...

How big are your sourcemaps?

**Comment by segevfiner** [comment]
There are many, a lot of them are small, but there are also a few big ones, with the largest being around 50MiB, though it's not really used in the source of the script I was trying to debug.

**Comment by connor4312** [comment]
Once my linked PR goes in, decoding should be much faster (25x or so).

You may also see improvement in the latest nightly with https://github.com/microsoft/vscode-js-debug/pull/1916, which fixes some cases where sourcemap memory was leaked (the previous implementation was wasm-based and required manual deallocation of memory, which didn't always happen.)

**Comment by connor4312** [comment]
Please let me know if you see this again on the nightly build or VS Code >1.86. Thanks!

**Comment by gilles-yvetot** [comment]
I am still seeing this in 1.102.0
