### ISSUE TITLE
How exactly is a shell selected for running node launch configurations?

### ISSUE THREAD

**Issue by starball5** [microsoft/vscode-js-debug#1917]
When I create a basic `node` launch config that runs a script that does `console.log(`SHELL env var: ${process.env["SHELL"]}`);`, it always prints `/bin/bash` (which is my system's default shell). It does this even when I put `"terminal.integrated.automationProfile.linux": { "path": "/bin/dash" },` in my user settings.json, and/or when I start the instance of VS Code from a Dash shell. This happens both when using the default `"console": "internalConsole"`, or when using `"console": "integratedTerminal"`.

Why does it always seem to run Node from the context of an instance of my system shell? Is there a way to select a different shell, such as by using the `terminal.integrated.automationProfile.<platform>` settings?

I am running on VS Code 1.85.1 installed as a Snap on Ubuntu 23.10, with version v1.85.0 of this extension.

**Comment by connor4312** [comment]
VS Code does a probe and loads the default shell environment for the user when the application is started. This is quite useful if the program is started from a desktop environment which may not have variables from a shell profile loaded. This can be disabled by turning off the `terminal.integrated.inheritEnv` setting.

**Comment by starball5** [comment]
@connor4312 That didn't really answer the question. You're talking about an environment. I'm asking about shells. But I realized I was just misled. VS Code does honour the `terminal.integrated.automationProfile.<platform>`. It's just that Dash doesn't seem to set the `SHELL` environment variable.
