### ISSUE TITLE
VSCode Extension Debug: Breakpoints in Sourcemaps not set when --profile-temp is used.

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode-js-debug#1922]
**Describe the bug**
Launch config:
```json
    {
      "name": "Launch Extension",
      "type": "extensionHost",
      "request": "launch",
      "runtimeExecutable": "${execPath}",
      "args": [
        "--extensionDevelopmentPath=${workspaceFolder}",
      ],
    },
```

This works fine, however simply adding `--profile-temp` will cause breakpoints to remain unbound. Named Profiles also work

![image](https://github.com/microsoft/vscode-js-debug/assets/15258962/2200a191-9dca-4aa6-a1c7-f9c0eb283d31)

Note the `outFiles` part. I have no outfiles config so maybe something about profile-temp is manipulating this.

**To Reproduce**
1. Start a vscode extension with sourcemaps such as the hello world TS sample
2. Use a normal launch config and add --profile-temp to it
3. Note breakpoints are unbound.
4. Remove --profile-temp and note that breakpoints work again.
5. Use --profile=somenewprofile and it should work as well.

I made sure I didn't have any JS debug settings in my current user profile

**Log File**

Normal Profile (working): 
[vscode-debugadapter-622a8ffd.json.gz](https://github.com/microsoft/vscode-js-debug/files/13981302/vscode-debugadapter-622a8ffd.json.gz)

Temp Profile (breakpoints unbound): 
[vscode-debugadapter-8319429f.json.gz](https://github.com/microsoft/vscode-js-debug/files/13981340/vscode-debugadapter-8319429f.json.gz)

**VS Code Version:** 1.85.2

**Additional context**

**Comment by connor4312** [comment]
I'm not able to repro this.

![image](https://github.com/microsoft/vscode-js-debug/assets/2230985/05734d4f-372d-4672-9fe0-8498b2bf748e)


Unfortunately it looks like the log files didn't get recorded correctly. Can you use `"trace": { "logFile": "${workspaceFolder}/log.txt" }` so that logs are saved as a plain .txt file, and share those here?

**Comment by JustinGrote** [comment]
@connor4312 thanks for taking a look, I'll give it another shot. Are you sure you're using sourcemaps here? I don't see a sourcemap file in your repo.

**Comment by connor4312** [comment]
Yea, it works with sourcemaps as well for me (using the [helloworld-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/helloworld-sample)).

**Comment by JustinGrote** [comment]
So I'm still getting it with a fresh "host" profile and debug configs for profile and profile-temp. Wondering if it's something about my computer specifically (Windows), let me try it in a codespace.

**Comment by connor4312** [comment]
Can you use "trace": { "logFile": "${workspaceFolder}/log.txt" } so that logs are saved as a plain .txt file, and share those here? That may provide a hint.

**Comment by JustinGrote** [comment]
OK so I can't reproduce in a fresh codespaces with helloworld-sample, but one thing interesting I noticed is that the breakpoint doesn't bind until the extension activates. Is this normal or expected? I could see this being super confusing.

Video:

https://github.com/microsoft/vscode-js-debug/assets/15258962/1f6c541d-527a-439d-8c7f-0414243ed257



Here's the log:
[log.zip](https://github.com/microsoft/vscode-js-debug/files/14117819/log.zip)

**Comment by JustinGrote** [comment]
That being said, I'm not reproducing this in sample-helloworld so I'll see if I can reproduce where I was seeing it and produce a simpler repro. Thanks! I'll open breakpoint as a separate issue.
