### ISSUE TITLE
UI: Breakpoints not binding for VS Code Extensions until activation

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode-js-debug#1936]
**Describe the bug**

Continuation of https://github.com/microsoft/vscode-js-debug/issues/1922#issuecomment-1920058779

Breakpoints in an extension show unbound until the extension is activated, not sure if this is desired behavior or not but it is definitely confusing UI for someone who isn't sure if their breakpoints bound correctly or not during extension development.

Additional items tested:
1. Putting a breakpoint in a code path that isn't run on extension activation will activate the breakpoint once it is loaded

**To Reproduce**
Using `helloworld-sample`

https://github.com/microsoft/vscode-js-debug/assets/15258962/613d7b47-758d-405a-866e-6cf893651a75

**Log File**

[log.zip](https://github.com/microsoft/vscode-js-debug/files/14117819/log.zip)

**VS Code Version:** `1.85.2`

**Comment by connor4312** [comment]
This is by design: until the runtime loads the file and acknowledges the breakpoint, it remains unverified to show it has not yet been bound.
