### ISSUE TITLE
"node version is outdated"

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#194]
I see this the first time I start debugging, and it works the second time

![image](https://user-images.githubusercontent.com/323878/71204102-2ca79980-2254-11ea-953e-5902633d9f7f.png)

Probably related to my nvm setup, but I wasn't seeing it before

**Comment by connor4312** [comment]
Thought I fixed this, maybe I left it on a forgotten branch somewhere...

**Comment by giovanni-bertoncelli** [comment]
@connor4312 @roblourens 
Hi, I'm receiving this error too.. But with the node version 6.9.0... Am I missing something? Is VSCode no more compatible with this version of nodejs?

**Comment by connor4312** [comment]
No, it's no longer compatible. You can set `debugger.javascript.usePreview: false` to use the previous version of debugger until you have time to upgrade (however this options will eventually go away.)

**Comment by giovanni-bertoncelli** [comment]
Ok thanks... Is there anything about this somewhere? Maybe some changelog?

**Comment by connor4312** [comment]
Just in issues -- and that warning

**Comment by cwilby** [comment]
I have this problem, but I'm using 14.16.1 installed with nvm.
