### ISSUE TITLE
Some of your breakpoints could not be set. If you're having an issue, you can troubleshoot your launch configuration.

### ISSUE THREAD

**Issue by edip6606** [microsoft/vscode-js-debug#1942]
how can i solution this problem

**Comment by connor4312** [comment]
> If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
> ⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by LO-Arctic** [comment]
Hello. I am having the same problem. My symptoms:

1. When I click to add a breakpoint, I get some weird behaviors. After the first click the breakpoint shows in the list, but I don't get the red circle on the margin of the source code. Click again and this time the breakpoint show up (unbounded) and I get a second breakpoint (bound) on what I presume is the transpiled js module.
3. The breakpoint does hit in the js file and I can see almost-but-not-quite my code. This editor is read-only.

My launch.json 
{
    "configurations": [
        {
            "type": "chrome",
            "name": "Local RAP",
            "request": "launch",
            "url": "https://localhost:4200",
            "trace": true
        }
    ]
}

Why my breakpoints don't bind says

✅ This breakpoint was initially set in:

C:\Users\LuisOrtega\repos\rap\rap-web-ui\src\app\content\model-management\risk-model-factor\risk-model-factor.component.ts line 165 column 1

✅ In the runtime, the breakpoint was set in:

https://localhost:4200/src_app_content_super-admin_setup-admin_module_ts.js line 2185 column 5


✅ The runtime acknowledged and adjusted the breakpoint, and it mapped back to the following locations:

line 2185 column 5

I uploaded the trace file to the page as instructed, but nothing happened. I'm emailing the trace to you.

Thanks 
Luis.

**Comment by connor4312** [comment]
Closing as we've not heard from the original reporter.

@LO-Arctic I would look into your webpack config and make sure that each step is generating and processing sourcemaps as you would expect, since it seems like locations in the sourcemaps are off.

**Comment by LO-Arctic** [comment]
Hi Connor, are there any other pointers you can give me. I don't know what's its expected. Just want to debug my code.

**Comment by connor4312** [comment]
If you're able to share the contents of "https://localhost:4200/main.js.map" and "https://localhost:4200/main.js.map" I can look a bit more and see if there's any issue on our side. We did switch out sourcemap libraries in VS Code 1.86, but we haven't heard of any other issues so I'm not sure whether that would be related.

**Comment by LO-Arctic** [comment]
Thanks Connor.

Here's the file (isn't that the same one twice?)

[main.js.zip](https://github.com/microsoft/vscode-js-debug/files/14365833/main.js.zip)

**Comment by connor4312** [comment]
Oops, sorry, I mean [https://localhost:4200/main.js](https://localhost:4200/main.js) as well

**Comment by LO-Arctic** [comment]
emailed

**Comment by 0xvNFT** [comment]
im having similar issue like this, any solution?

**Comment by LO-Arctic** [comment]
Hi 0xvNFT. 

This problem sort of solved itself for me. I never got a response from Connor, but a few weeks later, VS Code popped up a dialog asking me something about sourcemaps (don't remember exactly what) responded yes and that solved my issue.

Are you in the latest version?

**Comment by 0xvNFT** [comment]
> Hi 0xvNFT.
> 
> This problem sort of solved itself for me. I never got a response from Connor, but a few weeks later, when loading my project, VS Code popped up a dialog asking me something about sourcemaps (don't remember exactly what) responded yes and that solved my issue.
> 
> Are you in the latest version?

yes as of now im in:
Version: 1.88.1 (system setup)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:41:02.734Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.19045

still can't use debug tool on tsx files :/

**Comment by LO-Arctic** [comment]
Yeah, that's the same I have. Sorry I can't be more help.

**Comment by 0xvNFT** [comment]
> Yeah, that's the same I have. Sorry I can't be more help.

are you using next js?

**Comment by LO-Arctic** [comment]
No
