### ISSUE TITLE
debugger not stopping in breakpoints in vscode when we are making external request in node js

### ISSUE THREAD

**Issue by avinashvishu** [microsoft/vscode-js-debug#1945]
**Describe the bug**

**To Reproduce**

**Log File**

**VS Code Version:** Replace me!

**Additional context**

**Comment by connor4312** [comment]
Please fill in the info in the template

**Comment by Pritam-sd-dev** [comment]
@connor4312 
hi, i am new to open source world. I very much curious to contribute to this project. i doesnot found any reference or context that how this project is structured and design of the project. i am requesting you to please help me to get started with this project.
your small effort can be very helpful for me.
thanks
