### ISSUE TITLE
How does auto attach knows where to look for the sourcemap files?

### ISSUE THREAD

**Issue by Gorthog** [microsoft/vscode-js-debug#1960]
I'm using nx with nest and when I run the serve command, the debugger is auto attached, but all breakpoint are unbound.
I see sourcemaps are generated.

I think maybe "auto attach" doesn't know where to look for the source map files. How can I troubleshoot this further?

here is a repo with a repro:
https://github.com/Gorthog/nx-debugging

I run the following command:
```
nx run app:serve:development
```

I get the following behavior

![image](https://github.com/microsoft/vscode-js-debug/assets/15230040/a19d48d4-642b-47bc-988f-f00edf5b2629)

**Comment by Gorthog** [comment]
i'm running a Nest app - only server side. 

How can I check if auto attach is not attaching to the correct process? Is there a way for me to pinpoint which process should be attached and configure auto attach to attach to it?

**Comment by Gorthog** [comment]
And also, if you please, how can I verify that auto attach searches the correct folder for the js files and map files?

**Comment by connor4312** [comment]
ah, sorry.

You can diagnose breakpoints using the `Debug: Diagnose Breakpoint Problems` command.

Your apps are built using Webpack, which creates path like`webpack:///./src/app/app.controller.ts` that the debugger needs to map back to disk. By default that'll look for `src/app/app.controller.ts` in your workspace folder that doesn't exist.

To fix this I recommend creating a launch.json configuration to run your command and adjust the `sourceMapPathOverrides` option inside of it https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_launch-configuration such as

```
{
  "type": "node",
  "request": "launch",
  "name": "Launch Program",
  "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/nx",
  "runtimeArgs": ["run", "app:serve:development"],
  "console": "integratedTerminal",
  "sourceMapPathOverrides": {
    "webpack://?:*/*": "${workspaceFolder}/apps/app/*"
  }
}
```

**Comment by Gorthog** [comment]
thank you for your answer.

If I use this launch.json file:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach to setlist service",
      "request": "attach",
      "cwd": "${workspaceFolder}/apps/app",
      "type": "node",
      "port": 9229
    }
  ]
}
 
```

everything works great - which to me seems to suggest there is no need to override the source maps. please correct me if i'm wrong. 

The reason I open this issue and what I'm trying to do is to use auto attach to debug my project.

Seems to me either auto attach doesn't attach to the correct process or it doesn't "know" where to look for the sourcemap files.
Can you share some info how can I further troubleshoot? Specifically I would like to know:

1. How can I check if auto attach is not attaching to the correct process? Is there a way for me to pinpoint which process should be attached and configure auto attach to attach to it?
2. How can I verify that auto attach searches the correct folder for the js files and map files?

Using the command `Debug: Diagnose Breakpoint Problems` doesn't seem to answer either of these questions.

**Comment by connor4312** [comment]
Yea, setting the `cwd` works too because that'll automatically adjust the `sourceMapPathOverrides`

> How can I check if auto attach is not attaching to the correct process? Is there a way for me to pinpoint which process should be attached and configure auto attach to attach to it?

If you look in the Call Stack view, you can see the process ID that it's attached to in square brackets. You can also look in the Loaded Sources view and see what sources you expect to be loaded perpprocess.

> How can I verify that auto attach searches the correct folder for the js files and map files?

By default, all folders in your workspace expect for node_modules will be searched for sourcemaps. This is configurable in your settings via `debug.javascript.terminalOptions` (which applies to auto attach), or by manually creating a launch.json

**Comment by Gorthog** [comment]
You've provided me a tremendous help - Thank you!

For anyone else facing this problem, I fixed it by changing webpack.config.js to the following:
```javascript
const { NxWebpackPlugin } = require('@nx/webpack');
const path = require('path');

const outDir = path.join(__dirname, '../../dist/apps/app');

module.exports = {
  output: {
      devtoolModuleFilenameTemplate(info) {
        const { absoluteResourcePath, namespace, resourcePath } = info;

        if (path.isAbsolute(absoluteResourcePath)) {
          return path.relative(outDir, absoluteResourcePath);
        }

        // Mimic Webpack's default behavior:
        return `webpack://${namespace}/${resourcePath}`;
      },
      path: outDir,
    },
  plugins: [
    new NxWebpackPlugin({
      target: 'node',
      compiler: 'tsc',
      main: './src/main.ts',
      tsConfig: './tsconfig.app.json',
      assets: ['./src/assets'],
      optimization: false,
      outputHashing: 'none',
      sourceMap: true
    }),
  ],
};


```
