### ISSUE TITLE
Breakpoints not set properly when running with vitest

### ISSUE THREAD

**Issue by louislatreille-cb** [microsoft/vscode-js-debug#1970]
**Describe the bug**

I have a TypeScript monorepo, containing a few packages. Two are causing me issues. First one is an API server, using the second one, a common package.

Breakpoints used to work, but something changed recently (unsure what exactly), and now they aren't bound properly when using vitest. If I have some set before starting my tests in debug mode, most breakpoints don't bind at all, and the few that do bind to wrong places, usually in totally different files than expected.

I have another launch configuration which starts my API server in debug mode with TSX, and things work perfectly there. This leads me to believe that my source maps are correct, but I might be wrong.

**Log File**

I've sent the log file to connor@xbox.com . Happy to send more files if needed.

**VS Code Version:** 1.87.2

**Additional context**
Here are the two launch configs. First one is the one causing issues, second one works as expected.

```
   {
      "type": "node",
      "request": "launch",
      "name": "Debug API Test File",
      "autoAttachChildProcesses": true,
      "program": "${workspaceRoot}/node_modules/vitest/vitest.mjs",
      "env": {
        "NODE_ENV": "development"
      },
      "envFile": "${workspaceRoot}/packages/api/.env",
      "args": [
        "--config",
        "vitest-debug.config.mts",
        "run",
        "${workspaceRoot}/packages/api/test/computeFlowsheet.test.ts"
      ],
      "smartStep": true,
      "console": "integratedTerminal",
      "internalConsoleOptions": "openOnFirstSessionStart",
      "trace": true
    },
    {
      "type": "node",
      "request": "launch",
      "name": "Debug API Service",
      "autoAttachChildProcesses": true,
      "program": "${workspaceRoot}/node_modules/tsx/dist/cli.js",
      "args": [
        "-r",
        "${workspaceRoot}/packages/api/node_modules/dotenv/config",
        "${workspaceRoot}/packages/api/src/listen.ts"
      ],
      "smartStep": true,
      "console": "integratedTerminal",
      "env": {
        "NODE_ENV": "development"
      },
      "envFile": "${workspaceRoot}/packages/api/.env",
      "trace": true
    },
```

**Comment by louislatreille-cb** [comment]
Update:

I've noticed the following:
- Breakpoints in the log file being executed are bound properly and immediately.
- Breakpoints in the API packages are eventually bound, when the debugger is fully started
- Breakpoints in the common package are never bound, and even after the debugger is fully started, it's impossible to set any in the common package
- Stepping into code from the common package shows incorrect lines/files

Sent another log file when going through the steps that lead to the above conclusions.

**Comment by connor4312** [comment]
This is a common issue in monorepos, you're building your "common" code, but then your tooling is not "following" the sourcemaps in the compiled code. When it's bundling the code, it's creating sourcemaps that reference the already compiled bundle rather than your actual source code, e.g.

```js
{
	"version": 3,
	"sources": [
		"chunk-ZZYPPKAZ.js"
	],
```

I think that you might not be building with sourcemaps in your common code, as both vitest/esbuild and js-debug have logic that may handle this case if that were so.

**Comment by louislatreille-cb** [comment]
@connor4312 Thanks for the reply.

Actually, we do generate source maps for our common package. In fact, everything was working fine not too long ago. I tried going as far as 3 months back into our commit history, but still have the same issues with the debugger, which leads me to believe that we're either doing something wrong with our launch configs, or something changed with the debugger.

Based on your comment, I tried disabling code splitting in our bundler. This eliminates all the chunk files. Still getting the exact same issue though. Sent another log file to your email with that.

Here's another look into my issues:
![image](https://github.com/microsoft/vscode-js-debug/assets/120123693/16d70869-3a17-4a13-81ec-204fb975f36e)
![image](https://github.com/microsoft/vscode-js-debug/assets/120123693/f1c1079c-f903-4e31-9233-680f40ccf855)
![image](https://github.com/microsoft/vscode-js-debug/assets/120123693/e0350a09-fec5-4d5d-bf79-b48b57c8d773)

This is the result after clicking twice on line 308 in `calculateUtilities.ts`. As you can see, the breakpoints make no sense.
