### ISSUE TITLE
Easier way to jump to function definitions in debug log.

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode-js-debug#1979]
Currently, it requires 3 expansions to get to `[[FunctionLocation]]`:

![AxJsz6UUvT](https://github.com/microsoft/vscode-js-debug/assets/2931520/747fbb0a-7301-4f71-9657-01e2838bc9ad)

Would be nice if that was one click on `f`.

I think identifying a function with its source location is very natural .

**Comment by connor4312** [comment]
We now have this with DAP location references
