### ISSUE TITLE
VS Code built-in extension breakpoints could not be set.

### ISSUE THREAD

**Issue by BABA983** [microsoft/vscode-js-debug#1980]
Tried to debug a built-in extension named `configuration-editing` in vscode.
I tried the following step from [the wiki](https://github.com/microsoft/vscode/wiki/How-to-Contribute#debugging). Just don't work on extension debugging. How can I debug the built-in extension?
<img width="1920" alt="image" src="https://github.com/microsoft/vscode-js-debug/assets/38986298/54e44440-4f25-40df-9e7e-6c9fd3912b6d">
<img width="1920" alt="image" src="https://github.com/microsoft/vscode-js-debug/assets/38986298/f2158137-9f53-4980-b58a-f52e58b672ae">

**Comment by connor4312** [comment]
Breakpoints are only bound once an extension activates. Based on the troubleshooter, it does not appear that the configuration editing extension was activated.

**Comment by BABA983** [comment]
> Breakpoints are only bound once an extension activates. Based on the troubleshooter, it does not appear that the configuration editing extension was activated.

It seems the configuration editing extension works when I type some keywords and I get the source map. Not sure which step I got wrong.
<img width="1920" alt="image" src="https://github.com/microsoft/vscode-js-debug/assets/38986298/95156303-e6ff-4dee-8542-739445d8ab08">
<img width="1920" alt="image" src="https://github.com/microsoft/vscode-js-debug/assets/38986298/cbb54976-52e8-4e68-b274-a9158a04e0e5">

**Comment by connor4312** [comment]
Yea, it doesn't activate until you start editing configuration (in most cases.) This seems to be working as designed.
