### ISSUE TITLE
Electron render Typescript debugging breakpoints work in vscode natively, but not inside a dev container

### ISSUE THREAD

**Issue by rhbroberg** [microsoft/vscode-js-debug#1986]
Describe the bug
For some reason typescript debugging for the renderer side of Electron does not find sourcemaps when run in a dev container.

Debugging both main and renderer parts of Electron using vscode.  When source is javascript in both parts, debugging works properly in terms of being able to set breakpoints.  When source is typescript for both parts, if vscode is run on a workstation (tested on linux and macOS), the sourcemaps work properly and breakpoints can be set in either the main or the renderer process.

However when the project is opened in a typescript+nodejs container inside of vscode, if the source is typescript for main and renderer, only the breakpoints in main are found; the ones in the renderer side are not.  vscode complains that it can't find the associated file.  If the project uses straight javascript (not typescript) and is run in the dev container, debugging works just fine.

The sourcemaps are being created, the tsconfig.json file and the launch.json file both contain the clauses to activate/use them.  
"sourceMap": true is in tsconfig..json, and       "sourceMaps": true -- is in launch.json.

To Reproduce
Steps to reproduce the behavior.  First, verify that the project is configured to work not in a dev container:
(on a machine which has nodejs installed)

1. Checkout [https://github.com/abartho/electron-typescript-vscode.git](https://github.com/abartho/electron-typescript-vscode.git) and open it in vscode
2. run npm i
3. run npm run start (to verify it runs)
4. add a breakpoint to both the main.ts (line 5) and renderer.ts (line 2)
5. run 'Electron: All' launch configuration to start debugging
6. observe the breakpoint stop in main.js, and also in the renderer  when you press the 'turn page red' button 

7.  Now 'reopen in container' to see it break.  choose 'nodejs typescript' container,  choose all defaults for the rest
8.  in Terminal window, 'rm -rf node_modules build' to clean out previous architecture artifacts
9. run npm i 
10. run 'sudo apt update && sudo apt install -y libnss3-dev libgdk-pixbuf2.0-dev libgtk-3-dev libxss-dev libasound2' in your dev container so it has required dependencies to run Electron in X; 
11. run 'npm run start' (to verify it runs in dev container)
12. run 'Electron: All' launch configuration to start debugging
13. observe that the breakpoint stops in main.js, but does NOT stop in the renderer when you press the 'turn page red' button

Log File

[vscode-debugadapter-b67df2b6.json.gz](https://github.com/microsoft/vscode-js-debug/files/14890504/vscode-debugadapter-b67df2b6.json.gz)
[vscode-debugadapter-fb782d67.json.gz](https://github.com/microsoft/vscode-js-debug/files/14890505/vscode-debugadapter-fb782d67.json.gz)

VS Code Version:
Version: 1.88.0
Commit: 5c3e652f63e798a5ac2f31ffd0d863669328dc4c
Date: 2024-04-03T13:28:09.495Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.3.0

Additional context

**Comment by connor4312** [comment]
Unfortunately I'm not able to reproduce this. Based on the logs this is because Electron does not respond to the `Target.attachToBrowserTarget` request. I suggest trying their latest beta release and, if the issue reproduces there, open an issue on the Electron repo: https://github.com/electron/electron/

**Comment by connor4312** [comment]
Oh, please also try setting

```
			"browserAttachLocation": "workspace"
```

so that the debugger attaches in the dev container instead of going to your host. It's possible there's some network configuration going on that was different between our machines. And that's the right thing to do in this case. (By default it attaches on the local side since it assumes the developer is running a local browser to debug an app hosted in a dev container)

**Comment by rhbroberg** [comment]
YES!!  That fixed it!

Setting the  `"browserAttachLocation": "workspace"` in the renderer portion of launch.json made it work for me!  

Thank you so much!
