### ISSUE TITLE
Some of your breakpoints could not be set (greyed out)

### ISSUE THREAD

**Issue by 0xvNFT** [microsoft/vscode-js-debug#1993]
**Describe the bug**
**Some of your breakpoints could not be set. If you're having an issue, you can [troubleshoot your launch configuration**

**To Reproduce**
1. CTRL + SHIFT + D
2. Launch Chrome Against Localhost

Launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "trace": true,
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:3000/",
            "sourceMaps": true,
            "webRoot": "${workspaceFolder}",
            "resolveSourceMapLocations": [
                "${workspaceFolder}/",
                "!/node_modules/**"
            ],
        }
    ]
}
```

**Log File**
[vscode-debugadapter-0b667bdc.json.gz](https://github.com/microsoft/vscode-js-debug/files/14982632/vscode-debugadapter-0b667bdc.json.gz)

**VS Code Version:
Version: 1.88.1 (system setup)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:41:02.734Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.19045

**Additional context**
![image](https://github.com/microsoft/vscode-js-debug/assets/135686766/fc34b26f-d4d3-4c47-96b6-2743256c0c3b)

Im using: Typescript, next js, react.

ts config:
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**.*.js", "**/*.tsx", ".next/types/**/*.ts", "../referenceCodebase/login/forgotPassword.ts", "src/lib/constants/index.js"],
  "exclude": ["node_modules"]
}
```

**Comment by connor4312** [comment]
In your tsconfig.json, you need to specify `sourceMaps: true` in order for the compiler to generate sourcemaps.

**Comment by 0xvNFT** [comment]
i did what you said and tested it i still get:

_Unbound breakpoint

 Some of your breakpoints could not be set. If you're having an issue, you can..._
 
 **tsconfig:**
```
 {
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "sourceMap": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**.*.js", "**/*.tsx", ".next/types/**/*.ts", "../referenceCodebase/login/forgotPassword.ts", "src/lib/constants/index.js"],
  "exclude": ["node_modules"]
}

```

> In your tsconfig.json, you need to specify `sourceMaps: true` in order for the compiler to generate sourcemaps.

**Comment by connor4312** [comment]
Based on your log file, sourcemaps are not generated from your build system. I would recommend looking there and ensure it is properly configured to create sourcemaps.

**Comment by connor4312** [comment]
If you push your code to a repo I could see if anything sticks out.
