### ISSUE TITLE
Unbound breakpoint

### ISSUE THREAD

**Issue by 0xvNFT** [microsoft/vscode-js-debug#1995]
**Describe the bug**

###  Some of your breakpoints could not be set. If you're having an issue, you can...

**Launch.json:**
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome against localhost",
      "url": "http://localhost:3000",
      "webRoot": "${workspaceFolder}/xxx/xxx-web",
      "sourceMaps": true,
      "trace": true,
      //   "sourceMapPathOverrides": {
      //     "webpack:///src/*": "${webRoot}/src/*",
      //     "webpack:///./~/*": "${webRoot}/node_modules/*"
      //   },
      // "sourceMapPathOverrides": {
      //     "webpack:///./*": "${webRoot}/*",
      //     "webpack:///src/*": "${webRoot}/*",
      //     "webpack:///*": "*",
      //     "webpack:///./~/*": "${webRoot}/node_modules/*",
      //     "meteor://💻app/*": "${webRoot}/*",
      //     "webpack://_N_E/*": "${webRoot}/*"
      // },
      "sourceMapPathOverrides": {
        "webpack:///_N_E/./*": "${workspaceFolder}/./*",
        "webpack:///_N_E/*": "${workspaceFolder}/*",
        "webpack:///_N_E/./src/*": "${workspaceFolder}/src/*"
      }
      //   "resolveSourceMapLocations": [
      //     "${workspaceFolder}/xxx/xxx-web/**",
      //     "!**/node_modules/**"
      //   ]
    }
  ]
}
```

**tsconfig.json:**
```
{
  "compilerOptions": {
    "target": "es5",
    "sourceMap": true,
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**.*.js", "**/*.tsx", ".next/types/**/*.ts", "../referenceCodebase/login/forgotPassword.ts", "src/lib/constants/index.js"],
  "exclude": ["node_modules"]
}
```
**Debug diagnostics:**
![image](https://github.com/microsoft/vscode-js-debug/assets/135686766/e729b8ab-b956-4995-83a3-172d270501e3)
![image](https://github.com/microsoft/vscode-js-debug/assets/135686766/15bf0904-2217-4283-af8c-f29a06783afa)
and so on...

**Log File**
[vscode-debugadapter-d1f6b972.json](https://github.com/microsoft/vscode-js-debug/files/14997223/vscode-debugadapter-d1f6b972.json)

**VS Code Version:** 
Version: 1.88.1 (system setup)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:41:02.734Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.19045

**Additional context**
been trying different methods i couldn't make debugger work. Im using next, ts, and react

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-js-debug/issues/1993, your build is not producing sourcemaps. Sourcemaps are required for breakpoints to work when code is compiled or transformed.
