### ISSUE TITLE
The split2 module is very slow when handling large amounts of CDP data

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#2001]
I noticed in a profile that the split2 module took a ridiculous amount of time when requesting a large source from a debugee:

<img width="439" alt="image" src="https://github.com/microsoft/vscode-js-debug/assets/2230985/5b0369ae-c04e-491c-af85-257cda8ff17c">

Let's replace it with the optimized splitter I wrote for VS Code

**Comment by andreamah** [comment]
Are there verification steps for this?

**Comment by connor4312** [comment]
No good steps really, but folks have been using js-debug-nightly for copilot-chat where this was an issue and it seems to have worked, so I'll mark verified.
