### ISSUE TITLE
NODE_OPTIONS set in extension host process

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-js-debug#2010]
I see NODE_OPTIONS set to `' --require "/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/bootloader.js"'` in the extension host process when debugging an extension. This results in a `Node.js environment variables are disabled because this process is invoked by other apps.` error when spawning new Node processes using Electron. Similar to https://github.com/microsoft/vscode/issues/204005.

**Comment by connor4312** [comment]
This is intended, because setting this option allows debugging child processes spawned by the extension host.

**Comment by chrmarti** [comment]
Ack, turns out it's only a warning anyway. Closing, thanks.
