### ISSUE TITLE
No obvious way to launch Edge as debug browser for terminal link handling in WSL

### ISSUE THREAD

**Issue by amweiss** [microsoft/vscode-js-debug#2012]
**Describe the bug**
When using the Debug Terminal with VSCode in WSL remote mode, there was no obvious way to switch the browser option to Edge. I was able to make it work by using the following config:

```json
    "debug.javascript.defaultRuntimeExecutable": {
        "pwa-chrome": "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe",
    },
```

**To Reproduce**
1. In Windows, set Edge as your default browser
2. Run VSCode in WSL mode
3. Start a webserver
4. Ctrl+click the advertised hostname
5. See Chrome launches

**VS Code Version:** `v2024.5.217`

**Comment by connor4312** [comment]
Can you please let me know the value of [this](https://github.com/sindresorhus/default-browser/blob/08ed0560dfb7ed71e6536902ae312e03920a6929/windows.js#L25) registry key?

We will use Edge automatically if it's set as the platform default browser, but it seems like the detection is not working in your case.

**Comment by amweiss** [comment]
Here's the output of that command:
```sh
reg QUERY HKEY_CURRENT_USER\Software\Microsoft\Windows\Shell\Associations\UrlAssociations\http\UserChoice /v ProgId

HKEY_CURRENT_USER\Software\Microsoft\Windows\Shell\Associations\UrlAssociations\http\UserChoice
    ProgId    REG_SZ    MSEdgeHTM
```

**Comment by amweiss** [comment]
@connor4312 sorry for the tag, but I didn't want to start a new issue just to ask so I wanted to make sure it was seen on a closed issue.

Any chance of getting a release of `vscode-js-debug-companion` to make this work? I didn't see a nightly like the `vscode-js-debug` extension so I can't verify this or benefit from it yet.

**Comment by alexr00** [comment]
I have Edge Dev set as my default browser, and this works fine from non-js-debug terminal, but not from a js-debug terminal.

**Comment by connor4312** [comment]
@alexr00 can you share more details about the platform you're on? We don't detect Edge Dev in general on Windows. I think that's a separate issue if so.

**Comment by alexr00** [comment]
My mistake, I thought this was for just using the default browser. I'm on Windows using WSL.

**Comment by connor4312** [comment]
We don't naively launch the default browser because it might not be debuggable; we identify if it's Edge or (by default) Chrome and then launch that using our usual discovery.

Closing for some reverification
