### ISSUE TITLE
Correctly display shadowed variables in hovers

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#2022]
With [recent additions](https://github.com/microsoft/debug-adapter-protocol/pull/481) to DAP, evaluation requests can now come with a source and location. We should try to un-shadow variables in these evaluations so that the hovered variable is more consistent and reliable.

**Comment by amunger** [comment]
is the idea that something like this has accurate hover values?

```
const var1 = 1;

{
	const var1 = { str: 'value' };
	console.log(var1.str);
}

console.log(var1)
```

The only bit of inconsistency I notice is that when stopped on the second `console.log`, hovering the `var1` within the scope has a value of 1, whereas hovering the first `var1` while it's shadowed will display the type.
