### ISSUE TITLE
autoattach not working: cannot run without debugger if using launch.json

### ISSUE THREAD

**Issue by conradoGen** [microsoft/vscode-js-debug#2025]
**Describe the bug**

**To Reproduce**
vscode launch
      {
        "type": "node",
        "request": "launch",
        "name": "Update Examples",
        "program": "${workspaceFolder}/dist/util/runUpdateEgWithDB.js",
        "console": "integratedTerminal",
        "env": {
          "WRITE_RESPONSE_TO_FILE": "true",
          "NODE_OPTIONS": "",
          "VSCODE_INSPECTOR_OPTIONS": ""
        },
        "restart": false,
        "autoAttachChildProcesses": false,
        "sourceMaps": false
      },

it always starts the terminal as

cd /home/xzz/zzzz/privacy-relay ; /usr/bin/env WRITE_RESPONSE_TO_FILE=true 'NODE_OPTIONS= --require /home/xzz/.vscode-server/bin/5437499feb04f7a586f677b155b039bc2b3669eb/extensions/ms-vscode.js-debug/src/bootloader.js  --inspect-publish-uid=http' 'VSCODE_INSPECTOR_OPTIONS=:::{"inspectorIpc":"/tmp/node-cdp.582085-fb8a4243-16.sock","deferredMode":false,"waitForDebugger":"","execPath":"/usr/local/bin/node","onlyEntrypoint":true,"autoAttachMode":"always","mandatePortTracking":true,"fileCallback":"/tmp/node-debug-callback-9d192041cb9a41ec"}' /usr/local/bin/node ./dist/util/myFile.js

also, makes no difference running with ctrl + f5 vs f5

**Comment by connor4312** [comment]
> it always starts the terminal as

This is intended since VS Code sets environment variables for the process?

What's the bug?

**Comment by conradoGen** [comment]
How should we run without attaching the debugger?
________________________________

**Comment by connor4312** [comment]
See https://github.com/microsoft/vscode/issues/102057#issuecomment-656440073
