### ISSUE TITLE
Lack of information about sourceMapPathOverrides

### ISSUE THREAD

**Issue by DamienCassou** [microsoft/vscode-js-debug#2027]
**Describe the bug**

`dapDebugServer.js` produces events such as:

```
{
  "seq": 1484,
  "type": "event",
  "event": "loadedSource",
  "body": {
    "reason": "new",
    "source": {
      "name": "/(rsc)/src/app/page.jsx",
      "path": "/(rsc)/src/app/page.jsx",
      "sourceReference": 1615416030
    }
  }
}

{
  "seq": 1503,
  "type": "event",
  "event": "loadedSource",
  "body": {
    "reason": "new",
    "source": {
      "name": "/home/cassou/myproject/src/app/webpack:/@me/country/src/app/page.jsx",
      "path": "/home/cassou/myproject/src/app/webpack:/@me/country/src/app/page.jsx",
      "sourceReference": 734626073
    }
  }
}
```
 
Both events refer to the same file but with different paths, none of them matching anything on my filesystem.

I've tried to use [sourceMapPathOverrides](https://github.com/microsoft/vscode-js-debug/blob/main/OPTIONS.md) to override these paths but nothing I do works. It seems https://github.com/microsoft/vscode-js-debug/issues/1597 is about a similar issue.

It would be nice to have this option better documented.

**To Reproduce**
1. Create a new application with `npx create-next-app@latest --use-yarn --javascript --app --src-dir`
2. Try to [debug the server-side code](https://nextjs.org/docs/pages/building-your-application/configuring/debugging#server-side-code) with `dapDebugServer.js`

**Comment by connor4312** [comment]
Not sure what launch config you're using, but I added some docs in the linked commit

**Comment by DamienCassou** [comment]
thank you @connor4312
