### ISSUE TITLE
Debugger hangs when setting a breakpoint in a file with japanese characters with Node.js ESM loader active

### ISSUE THREAD

**Issue by dgozman** [microsoft/vscode-js-debug#2043]
**Describe the bug**

The following conditions trigger the debugger/program hang:
- registering a [ESM loader](https://nodejs.org/api/module.html#moduleregisterspecifier-parenturl-options)
- requiring a file with japanese characters in the name, e.g. `テスト_example.spec.js`
- setting a breakpoint in the above file

**To Reproduce**
1. Clone https://github.com/dgozman/repro-debug
2. Open VSCode
3. Open JavaScript Debugger Terminal
4. Run `node main.js` in the debugger terminal
5. Observe everything works and outputs "1"
6. Place a breakpoint at `テスト_example.spec.js:3`
7. Run `node main.js` in the debugger terminal
8. Program and debugger hang

**Log File**

[vscode-debugadapter-65f7bcb8.json.gz](https://github.com/user-attachments/files/16329026/vscode-debugadapter-65f7bcb8.json.gz)

**VS Code Version:**

Version: 1.91.1
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:07:46.768Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 22.6.0

**Additional context**

Note this requires Node.js v20+. Definitely reproduces with Node.js v20.11.1.

**Comment by connor4312** [comment]
This is https://github.com/nodejs/node/issues/50516
