### ISSUE TITLE
Error activating auto attach (Nextjs 14)

### ISSUE THREAD

**Issue by BilalurRehman-27** [microsoft/vscode-js-debug#2052]
Debugger listening on ws://127.0.0.1:60908/dd69f551-055f-405a-b506-b92c0e4c4b59
For help, see: https://nodejs.org/en/docs/inspector
timeout

Error activating auto attach, please report to https://aka.ms/js-dbg-issue
Debugger listening on ws://127.0.0.1:60917/f18a4479-bb4b-4e06-bed6-04540507d541
For help, see: https://nodejs.org/en/docs/inspector
timeout

**Comment by connor4312** [comment]
Thanks,

1. if you run the "toggle developer tools" command in the vscode window, do you see any errors:
2. do you see any warning ⚠️ on your terminal tab/title when you're in this state?
