### ISSUE TITLE
process hanging: renames calculated in 67078ms

### ISSUE THREAD

**Issue by xtutu** [microsoft/vscode-js-debug#2061]
**Describe the bug**
VSCode can successfully hit my breakpoints, but when I hover over a variable,  The process keeps hanging.
Is it a bug ?

[vscode-debugadapter-f346b509.json](https://github.com/user-attachments/files/16809252/vscode-debugadapter-f346b509.json)

**VS Code Version:** 1.92.2

**Additional context**

- launch.json
```json
{
            "name": "Attach to Remote",
            "address": "127.0.0.1",
            "port": 10330,
            "localRoot": "${workspaceFolder}",
            "remoteRoot": "${workspaceFolder}",
            "outFiles": [
                "${workspaceFolder}\\..\\client\\Assets\\Doc\\js_project\\game\\*.mjs"
            ],
            "request": "attach",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "trace": true,
            "type": "node"
        }
```

- init.mjs    size: 9551 KB
- init.mjs.map    size: 30950 KB

But when I use "chrome://inspect/#devices" to debug, it react quickly!

How can I solve this problem ?

**Comment by connor4312** [comment]
You can set `sourceMapRenames: false` to get around this.

Not sure there's much we can do for this case. The source map renames we calculate are pretty fast but with giant sources and source maps the work we need to go can be slow.

**Comment by xtutu** [comment]
thanks! it works
