### ISSUE TITLE
Sometimes the debug toolbar disappears while debugging

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-js-debug#208]
I don't have any reproducible case, but quite a few times I've seen the debug toolbar either not show up when starting a debug session or it just goes missing.

**Comment by connor4312** [comment]
If you see this again, can you grab a trace log? 🙂

**Comment by eamodio** [comment]
Will do -- though this is quite infrequent.

**Comment by connor4312** [comment]
No worries. I'll put it on a backlog for now then, we can promote it once we can get some visibility--or if it becomes more frequent.

**Comment by connor4312** [comment]
This may have been https://github.com/microsoft/vscode/issues/83771. Please reopen if you still run into this issue. Thanks!
