### ISSUE TITLE
Debugger is pausing on an uncaught exception but with no stack trace or logs, seemingly impossible to debug

### ISSUE THREAD

**Issue by twilson90** [microsoft/vscode-js-debug#2086]
**Describe the bug**
The debugger is occasionally pausing on an uncaught exception in one of my scripts, according to the Call Stack panel it is paused on a promise rejection, but that's as much as it tells me.
The call stack is 1 level deep (task queues->processTicksAndRejections) and no logs are produced, so I have no idea where the rejection is coming from.
Recently converted my project from CJS to ESM, never had this issue when it was CJS.

![Code_fQoghfg2Oe](https://github.com/user-attachments/assets/f584a80d-f29b-4dc4-b5b7-b27419bc3930)

If I toggle off pausing on uncaught exceptions, it would appear there are no errors as I don't see anything still in the debug console.

**Log File**

[E-Ticket Booking Ref OBLZPZ Folder No. 3276436.pdf](https://github.com/user-attachments/files/17090680/E-Ticket.Booking.Ref.OBLZPZ.Folder.No.3276436.pdf)

**VS Code Version:**

Version: 1.93.1 (user setup)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by connor4312** [comment]
Please collect a log file using the instructions in the issue template. Thanks!

**Comment by connor4312** [comment]
This is an existing bug in Node.js
