### ISSUE TITLE
sourceURL containing space does not work

### ISSUE THREAD

**Issue by sapphi-red** [microsoft/vscode-js-debug#2089]
**Describe the bug**
When `// #sourceURL=` has an URL containing space, the transformed file is shown instead of the original file.

**To Reproduce**

1. Clone https://github.com/ondrejrohon/sveltekit-debug-vscode in a path containing a whitespace (e.g. `C:\Users\green\foo bar\sveltekit-debug-vscode`)
2. Click this button
![image](https://github.com/user-attachments/assets/12206fbd-567b-48c6-811d-d6d8ee983f1d)
3. Open `http://localhost:5173`
4. See the transformed file (IIFE named `anonymous`) is shown instead of the original file (ESM exporting `load` function).
![image](https://github.com/user-attachments/assets/62e42963-c07f-4337-9b41-8085364466f6)

**Log File**
[vscode-debugadapter-e6485847.json.gz](https://github.com/user-attachments/files/17127385/vscode-debugadapter-e6485847.json.gz)

**VS Code Version:** 1.93.1

**Additional context**
It did not work even if I escaped the space with `%20`.

Original issue: https://github.com/vitejs/vite/issues/17977, https://github.com/sveltejs/kit/issues/12625

**Comment by connor4312** [comment]
The string you put in there is not a valid URL. File URLs should generally begin with `file:///`. Encoding it as a URL properly will allow for escaping of spaces.

**Comment by sapphi-red** [comment]
Thanks for the response!
