### ISSUE TITLE
Cannot set breakpoints in c++ code transpiled to wasm using emscripten

### ISSUE THREAD

**Issue by matusthemostlygreat** [microsoft/vscode-js-debug#2099]
I have a c++ project built into wasm using emscripten, and I have the extension installed and built using -g. I can set breakpoints in javascript, and it does break on javascript exceptions. However, it does not break on c++ breakpoints, so I am unable to step through my code.
 
Been following this page:
[https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_debugging-webassembly](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcode.visualstudio.com%2Fdocs%2Fnodejs%2Fnodejs-debugging%23_debugging-webassembly&data=05%7C02%7Cmatusl%40microsoft.com%7C909f50b58bc94fb59ff208dce6fd8d11%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638639223932797360%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=qwLUIIOitwasTfnCDE4%2FBjE6znGFKCj7XWHEeFJwubE%3D&reserved=0)

Can you point me in the right direction please?  What do I need to look at to investigate why it's not working?
![debuggerbug](https://github.com/user-attachments/assets/ee1ef198-5781-4106-80d0-dfbac5bfbf0e)

This is my launch json

{
    "configurations": [
        {
            "type": "chrome",
            "name": "visualizer",
            "request": "launch",
            "url": "http://localhost:3001/visualizer.html"
        }
    ]
}

**Comment by connor4312** [comment]
Please collect a log file:

>If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by matusthemostlygreat** [comment]
[vscode-debugadapter-1ab06081.json.gz](https://github.com/user-attachments/files/17283884/vscode-debugadapter-1ab06081.json.gz)

**Comment by connor4312** [comment]
In that log, it looks like you don't have any breakpoints set up. But I see the sources get parsed correctly, and in your screenshot above it looks like they got bound successfully 

![Image](https://github.com/user-attachments/assets/e0b79800-d5eb-42ee-8225-699764a2d598)

**Comment by matusthemostlygreat** [comment]
i disabled them cause i didn't think the log was being generated correctly. here is a fresh run with a single breakpoint set and matching log file.

![image](https://github.com/user-attachments/assets/b3987df1-ddc5-472d-89f5-a38cb52dd71a)
[vscode-debugadapter-cab056d0.json.gz](https://github.com/user-attachments/files/17284967/vscode-debugadapter-cab056d0.json.gz)

**Comment by matusthemostlygreat** [comment]
as you can see in the debug output spew, execution was not stopped at the breakpoint. the red text was output as a result of a failure inside app.Run()

**Comment by connor4312** [comment]
Did you refresh the page to try to hit the breakpoint?

> Breakpoints in WebAssembly code are resolved asynchronously, so breakpoints hit early on in a program's lifecycle may be missed. There are plans to fix this in the future. If you're debugging in a browser, you can refresh the page for your breakpoint to be hit. If you're in Node.js, you can add an artificial delay, or set another breakpoint, after your WebAssembly module is loaded but before your desired breakpoint is hit.

**Comment by matusthemostlygreat** [comment]
thanks, that was it! if i set a breakpoint in the main generated .js file at function run() where it calls preRun(), after hitting that js breakpoint i can then hit my c++ breakpoint in main().

**Comment by connor4312** [comment]
Yea, that's how to do it. Unfortunately in V8 we can't set an 'entrypoint' breakpoint when WASM modules are parsed like we can for normal scripts (which we use to set breakpoints when a script is sourcemapped.) There's an upstream bug for it, and it should 'just work' once that's fixed.

**Comment by connor4312** [comment]
Ended up making a workaround in https://github.com/microsoft/vscode-js-debug/pull/2102, will arrive on [nightly](https://github.com/microsoft/vscode-js-debug/?tab=readme-ov-file#nightly-extension) this evening.
