### ISSUE TITLE
'paused on debugger statement' when debugging vscode extension

### ISSUE THREAD

**Issue by adrianstephens** [microsoft/vscode-js-debug#2105]
**Describe the bug**
When I debug a vscode extension with the nightly debugger, it stops two times with 'paused on debugger statement' before it gets to my extension.

**To Reproduce**

1. Create a vscode extension (or use any of the sample ones)
2. Hit F5
3. Note the debugger stopping with 'Paused on Debugger Statement'
4. Hit F5
5. Note the debugger stopping with 'Paused on Debugger Statement' again
6. Hit F5
7. Debugging continues as usual

**Log File**
[vscode-debugadapter-4c089f80.json.gz](https://github.com/user-attachments/files/17347561/vscode-debugadapter-4c089f80.json.gz)

**VS Code Version:1.94.0

**Additional context**

This is the stack on the 1st stop:

<anonymous> (Unknown Source:3)
Promise.then (Unknown Source:0)
WebAssembly.<computed> (Unknown Source:3)
<anonymous> (<node_internals>/internal/deps/cjs-module-lexer/dist/lexer:1)
await (Unknown Source:0)
init (<node_internals>/internal/deps/cjs-module-lexer/dist/lexer:1)
initCJSParse (<node_internals>/internal/modules/esm/translators:89)
commonjsStrategy (<node_internals>/internal/modules/esm/translators:343)
callTranslator (<node_internals>/internal/modules/esm/loader:272)
moduleProvider (<node_internals>/internal/modules/esm/loader:278)
await (Unknown Source:0)
ModuleJob (<node_internals>/internal/modules/esm/module_job:67)
#createModuleJob (<node_internals>/internal/modules/esm/loader:290)
getJobFromResolveResult (<node_internals>/internal/modules/esm/loader:247)
getModuleJob (<node_internals>/internal/modules/esm/loader:228)
await (Unknown Source:0)
<anonymous> (<node_internals>/internal/modules/esm/module_job:87)
link (<node_internals>/internal/modules/esm/module_job:86)
await (Unknown Source:0)
ModuleJob (<node_internals>/internal/modules/esm/module_job:99)

this is the 2nd call stack:

<anonymous> (Unknown Source:3)
Promise.then (Unknown Source:0)
WebAssembly.<computed> (Unknown Source:3)
lazyllhttp (<node_internals>/internal/deps/undici/undici:5560)
await (Unknown Source:0)
lib/dispatcher/client-h1.js (<node_internals>/internal/deps/undici/undici:5604)
__require (<node_internals>/internal/deps/undici/undici:6)
lib/dispatcher/client.js (<node_internals>/internal/deps/undici/undici:7289)
__require (<node_internals>/internal/deps/undici/undici:6)
lib/dispatcher/pool.js (<node_internals>/internal/deps/undici/undici:7750)
__require (<node_internals>/internal/deps/undici/undici:6)
lib/dispatcher/agent.js (<node_internals>/internal/deps/undici/undici:7833)
__require (<node_internals>/internal/deps/undici/undici:6)
lib/global.js (<node_internals>/internal/deps/undici/undici:7933)
__require (<node_internals>/internal/deps/undici/undici:6)
<anonymous> (<node_internals>/internal/deps/undici/undici:13172)
compileForInternalLoader (<node_internals>/internal/bootstrap/realm:398)
requireBuiltin (<node_internals>/internal/bootstrap/realm:429)
fetch (<node_internals>/internal/bootstrap/web/exposed-window-or-worker:69)
DH.globalThis.fetch (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:158)

**Comment by connor4312** [comment]
Should be fixed in tonight's nightly with https://github.com/microsoft/vscode-js-debug/pull/2103

**Comment by adrianstephens** [comment]
Thank you so much for such a speedy fix!

**Comment by ronaldmiranda** [comment]
Oh god, is there another way to disable it? It's so annoying.

**Comment by connor4312** [comment]
Update your version of js-debug.
