### ISSUE TITLE
module.register() will hang when debugging

### ISSUE THREAD

**Issue by millionkn** [microsoft/vscode-js-debug#2118]
My English is not very good, so I’m using ChatGPT for translation. I apologize for any formatting errors or other issues.

**Describe the bug**
Debugging a JavaScript file which leverages [module.register](https://nodejs.org/api/module.html#moduleregisterspecifier-parenturl-options) does end up in a infinite hang.
This issue is the same as[issue2009](https://github.com/microsoft/vscode-js-debug/issues/2009), which was closed due to lack of a reproduction method. I have found a stable way to reproduce the issue.

**To Reproduce**
```js
//入口.js
import { register } from 'module'

console.log('print something');
register('anything') // hang up if has break point in this file
console.log('set break point here');
```
1. In VS Code, set a breakpoint on line 6 of`入口.js`
2. In the VS Code terminal (I'm using cmd), run `node --inspect ./入口.js`

**Log File**
N/A

**VS Code Version:** 1.94.2

**Additional context**

The key to reproducing this issue is **having Chinese characters in the file path of the file containing the breakpoint**,However, it seems that the length of the Chinese characters matters. For example,if `入口.js` is replaced with`入.js`or`口.js`, it outputs nothing and simply exits.

If the filename is in another language, such as `テスト.js` (Japanese), it also outputs nothing.

I tested this on two versions of Node (`v22.11.0` and `v18.20.4`), and the issue exists on both.

**Comment by connor4312** [comment]
This is a result of https://github.com/nodejs/node/issues/50516
