### ISSUE TITLE
Cannot debug (react) project on chrome without changing launch config

### ISSUE THREAD

**Issue by kitfit-dave** [microsoft/vscode-js-debug#212]
Trying to debug gives this error message:
```
Unable to launch browser: "Unable to find Chrome version stable. You can set the "runtimeExecutable" in your launch.json to the path to Chrome
```
The relevant contents of the (working with the default debugger) launch.json file:
```
		{
			"type": "chrome",
			"request": "launch",
			"runtimeArgs": [
				"--auto-open-devtools-for-tabs"
			],
			"userDataDir": "${workspaceFolder}/.vscode/user-data-dir",
			"name": "Launch Chrome at local.test",
			"url": "http://local.test:8080",
			"webRoot": "${workspaceFolder}"
		}
```
Adding `runtimeExecutable` does resolve the issue, e.g.:
```
			"runtimeExecutable": "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
```
however, it would be nicer if it was able to use the chrome instance in the path.

**Comment by connor4312** [comment]
Thanks for the issue. Can you post the output of running the following command?

```
/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -dump | grep -i 'google chrome\( canary\)\?.app$'
```

**Comment by kitfit-dave** [comment]
There is no output from that command. I don't have canary installed - is the nightly debugger expecting a dev build of chrome to exist then? It does seem to work just fine with regular chrome as long as you tell it where the executable is.

**Comment by zaiste** [comment]
It seems that the register function doesn't check for the [Chrome Dev](https://www.google.com/chrome/dev/) flavour that sits at `/Applications/Google Chrome Dev.app` on MacOS. Chrome Dev is the natural choice for developers. It'd be great to extend the register search to include this Chrome flavour as well.
