### ISSUE TITLE
No longer able to debug Karma Test in Visual Studio Code after latest update

### ISSUE THREAD

**Issue by clegeard** [microsoft/vscode-js-debug#2121]
**Describe the bug**
No longer able to debug Karma Test in Visual Studio Code after latest update (1.95.1)

**To Reproduce**
Since yesterday I'm no longer able to debug my tests 
My launch file was is set as:
{
            "type": "chrome",
            "request": "launch",
            "name": "Debug Karma Tests",
            "url": "http://localhost:9876/debug.html",
            "webRoot": "${workspaceFolder}"
        }

This was working perfectly fine until today.

**Log File**

No logs available, Karma Debugger Runner opens on port 9876 (http://localhost:9876/debug.html) but it simply does nothing

**VS Code Version:** 1.95.1

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode/issues/232651#issuecomment-2450365808
