### ISSUE TITLE
Breakpoints assigned to incorrect line when using register/import transpiler

### ISSUE THREAD

**Issue by bdentino** [microsoft/vscode-js-debug#2122]
**Describe the bug**
I apologize in advance if this is behaving as expected and I've just misconfigured my project. If that's the case I would appreciate any advice on fixing said configuration to achieve the behavior described below.

I have a nodejs typescript project that I run locally in docker. I am using swc register to transpile code as it's loaded instead of running from a build directory. I can connect to debug the project and set breakpoints in the remote files from my local sources, but these breakpoints are generally not inserted into the expected position on the remote code. I believe this is related to the fact that the 'loaded' script is actually transpiled with an inline sourcemap, and vscode seems to be ignoring that sourcemap when it assigns the breakpoint to the mapped source file. 

For instance, trying to set a breakpoint locally on line 20 of my untranspiled file results in VSCode requesting a breakpoint at line 20 of the transpiled source, which doesn't exist.

Am I doing something wrong here? Is there some way to explicitly tell vscode where to find sourcemaps for local files so that it knows which line to request the breakpoint at?

**To Reproduce**
I created a very simple repro here:
https://github.com/bdentino/vscsm-repro

1. Checkout repo
2. `npm install` locally
3. `docker compose up api`
4. In VSCode, attach debugger and set a breakpoint at line 22.
5. Observe that breakpoint cannot be bound

![Image](https://github.com/user-attachments/assets/945d0074-c2ce-4862-9bd9-bb014406a2f4)

**Log File**

[vscode-debugadapter-ae11dbf9.json.gz](https://github.com/user-attachments/files/17608427/vscode-debugadapter-ae11dbf9.json.gz)

**VS Code Version:** 
![Image](https://github.com/user-attachments/assets/67752d97-be0e-49d5-a60a-dab0eb640f17)

**Comment by eleanorjboyd** [comment]
Hi @bdentino! Are you able to verify if this issue is fixed? You can use the pre-release of the vscode-js-debug to try it. Appreciate if you are able to do so- thanks!

**Comment by bdentino** [comment]
Hi! Thanks for taking the time to work on this @connor4312 @eleanorjboyd. Unfortunately, I still have the same problem with the pre-release debugger. I did push some local changes just now to my [reproduction repo](https://github.com/bdentino/vscsm-repro) that never made it to origin (whoops). Maybe you can try that on your end to confirm that it's not just me?

**Comment by connor4312** [comment]
Can you grab a new log file?

**Comment by bdentino** [comment]
Sure thing

[vscode-debugadapter-ce176483.json.gz](https://github.com/user-attachments/files/18591559/vscode-debugadapter-ce176483.json.gz)

**Comment by connor4312** [comment]
It looks like you're still on the stable debugger release, here are instructions for using the nightly build: https://github.com/microsoft/vscode-js-debug?tab=readme-ov-file#nightly-extension
