### ISSUE TITLE
Regression: Debugger gets stuck if breakpoint is set before launch

### ISSUE THREAD

**Issue by CobusKruger** [microsoft/vscode-js-debug#2127]
**Describe the bug**
This appears to be a regression of [Issue 1604](https://github.com/microsoft/vscode-js-debug/issues/1604), which relates to Chrome 111 and VS Code 1.76.

When you set a breakpoint before launching, and the browser version is either Edge or Chrome 130, the app never starts. The browser opens, but spins endlessly without loading the page.

**To Reproduce**
I prepared a simple test in the repo linked below. All this is, is a new Angular app with a `launch.json` file, as generated by the Angular tools. If this is related to the previous issue, the specifics of the project should make no difference. To run the project, use the `ng serve` launch profile[vscode-debugadapter-71246763.json.gz](https://github.com/user-attachments/files/17703205/vscode-debugadapter-71246763.json.gz)
. https://github.com/CobusKruger/VscodeChromeBreakpointsIssue.

If you launch the project without any breakpoints set, you will see that it loads as expected. As soon as you set a breakpoint (I placed one at `app.component.ts`, line 12), the page will no longer open.

**Log File**

[vscode-debugadapter-71246763.json.gz](https://github.com/user-attachments/files/17703349/vscode-debugadapter-71246763.json.gz)

**VS Code Version:** 1.95.2

**Additional context**

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode-js-debug/?tab=readme-ov-file#nightly-extension

**Comment by CobusKruger** [comment]
Holy smokes, that was quick. Thank you @connor4312!
