### ISSUE TITLE
Fully qualified name of sources doesn't have drive on windows

### ISSUE THREAD

**Issue by digeff** [microsoft/vscode-js-debug#213]
This seems like a bug:
![image](https://user-images.githubusercontent.com/14098140/71931855-97613c00-3153-11ea-93c7-c7e8c5a43f71.png)

I reproduced this while debugging the standard React template in VS

**Comment by connor4312** [comment]
Does this cause any issues for your setup? I don't think this is something we've touched since the handover, and looking at the code it's only used

 1. For the `prettyName` of the source, used for display
 2. As the path for the source iff it doesn't exist on disk.

**Comment by digeff** [comment]
I'm not sure if this is causing any issues or not, but it seemed wrong...

**Comment by connor4312** [comment]
I agree. The fqname handling seems weird to me. I think we can probably reduce its usage or be smarter about it. Tagging this as debt and backlog as it doesn't seem to be causing any issues at the moment.
