### ISSUE TITLE
Failing to debug JavaScript in VS code flask application with blueprints

### ISSUE THREAD

**Issue by zuberek** [microsoft/vscode-js-debug#2130]
**Describe the bug**
I have a flask web app that is using flask blueprints.
I'm trying to debug the front end JS with breakpoints from within VS code.
However, when launching the debugging session, the breakpoints are becoming unbounded.

**To Reproduce**
My project structure is such that I have JS files in several places, and when launching the app, Chrome DevTools have them mapped to these:

`WebApp/src/app_static/js/globals.js` : `http://127.0.0.1:5000/app_static/js/globals.js`  
`WebApp/src/blueprints/blueprintA/app_static/js/blueprintAFunction.js` : `http://127.0.0.1:5000/static/blueprintA/js/blueprintAFunction.js`

The launching script is here `WebApp/run.py`  
I am running this on Windows but within WSL's VS code.  
Similar question was asked [here](https://stackoverflow.com/q/66342725/8953414) but it doesn't work for me.

**Log File** 
[vscode-debugadapter-f8f0c184.json.gz](https://github.com/user-attachments/files/17746285/vscode-debugadapter-f8f0c184.json.gz)

**VS Code Version:** 1.95.2

**Additional context**
I tried manually setting the sourceMap within the debugger like explained in the [README](https://github.com/microsoft/vscode-chrome-debug/blob/master/README.md#sourcemaps). My launch.json config looks like this

```json
          {
              "name": "Launch Chrome",
              "request": "launch",
              "type": "chrome",
              "url": "http://localhost:5000",
              "webRoot": "/mnt/c/Users/userA/code/WebApp/src",
              "sourceMapPathOverrides": {
                  "/static/*": "${webRoot}/blueprints/*/app_static/*",
                  "/app_static/*": "${webRoot}/app_static/*",
              }
          },
```

I can debug from within Chrome DevTools and when the app hits a breakpoint from there, it even stops in VS code, showing me the environment and everything. This works even if I launch with silly `webRoot` and `sourceMapPathOverrides` values, but of course is not what I want.

Having this more general version from [this](https://medium.com/front-end-weekly/solve-breakpoint-ignored-with-visual-studio-code-vscode-1-19-chrome-debugger-6d484c88b829) Medium article also doesn't work

```json
"sourceMapPathOverrides": {
        "*": "${webRoot}/*"
      }
```

I have asked this question on [stackoverflow](https://stackoverflow.com/q/79185088/8953414) also

**Comment by connor4312** [comment]
You want a webroot of `${workspaceFolder}/Annotator/annotator`

You aren't using sourcemaps, so `sourceMapPathOverrides` aren't relevant for you
