### ISSUE TITLE
Unbound breakpoint in VS Code with electronJs

### ISSUE THREAD

**Issue by cristhianprog** [microsoft/vscode-js-debug#2134]
I'm having a problem when trying to run Debuggingmode in vs using electronJs. When I try to run Debugging mode, the breakpoints I place are only marked as Unbound. I'm already setting it to "sourceMap": true and the error still persists.

My .vscode/launch.json:

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug Main Process",
      "type": "node",
      "request": "launch",
      "cwd": "${workspaceFolder}",
      "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron",
      "windows": {
        "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron.cmd"
      },
      "args" : ["."],
      "outputCapture": "std"
    }
  ]
}
```

My angular.js:

    "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
    "version": 1,
    "newProjectRoot": "projects",
    "projects": {
        "torus-pdv": {
            "root": "",
            "sourceRoot": "src",
            "projectType": "application",
            "architect": {
                "build": {
                    "builder": "@angular-devkit/build-angular:browser",
                    "options": {
                        "outputPath": "dist",
                        "index": "src/index.html",
                        "main": "src/main.ts",
                        "tsConfig": "src/tsconfig.app.json",
                        "polyfills": "src/polyfills.ts",
                        "assets": [
                            "src/assets",
                            "src/favicon.ico",
                            "src/favicon.png",
                            "src/favicon.icns",
                            "src/favicon.256x256.png",
                            "src/favicon.512x512.png"
                        ],
                        "styles": ["src/styles.scss"],
                        "scripts": [],
                        "allowedCommonJsDependencies": ["qrcode", "rxjs"],
                        "vendorChunk": true,
                        "extractLicenses": false,
                        "buildOptimizer": false,
                        "sourceMap": true,
                        "optimization": false,
                        "namedChunks": true
                    },
                    "configurations": {
                        "dev": {
                            "budgets": [
                                {
                                    "type": "anyComponentStyle",
                                    "maximumWarning": "6kb"
                                }
                            ],
                            "buildOptimizer": false,
                            "optimization": false,
                            "sourceMap": true,
                            "outputHashing": "all",
                            "namedChunks": false,
                            "aot": false,
                            "extractLicenses": true,
                            "vendorChunk": true,
                            "fileReplacements": [
                                {
                                    "replace": "src/environments/environment.ts",
                                    "with": "src/environments/environment.dev.ts"
                                }
                            ]
                        },
                        "production": {
                            "budgets": [
                                {
                                    "type": "anyComponentStyle",
                                    "maximumWarning": "6kb"
                                }
                            ],
                            "optimization": true,
                            "outputHashing": "all",
                            "sourceMap": true,
                            "namedChunks": false,
                            "extractLicenses": true,
                            "vendorChunk": false,
                            "buildOptimizer": true,
                            "fileReplacements": [
                                {
                                    "replace": "src/environments/environment.ts",
                                    "with": "src/environments/environment.prod.ts"
                                }
                            ]
                        }

                    },
                    "defaultConfiguration": ""
                },
                "serve": {
                    "builder": "@angular-devkit/build-angular:dev-server",
                    "options": {
                        "browserTarget": "torus-pdv:build"
                    },
                    "configurations": {
                        "dev": {
                            "browserTarget": "torus-pdv:build:dev"
                        },
                        "production": {
                            "browserTarget": "torus-pdv:build:production"
                        }
                    }
                },
                "extract-i18n": {
                    "builder": "@angular-devkit/build-angular:extract-i18n",
                    "options": {
                        "browserTarget": "torus-pdv:build"
                    }
                },
                "test": {
                    "builder": "@angular-devkit/build-angular:karma",
                    "options": {
                        "main": "src/test.ts",
                        "polyfills": "src/polyfills-test.ts",
                        "tsConfig": "src/tsconfig.spec.json",
                        "karmaConfig": "src/karma.conf.js",
                        "scripts": [],
                        "styles": ["src/styles.scss"],
                        "assets": [
                            "src/assets",
                            "src/favicon.ico",
                            "src/favicon.png",
                            "src/favicon.icns",
                            "src/favicon.256x256.png",
                            "src/favicon.512x512.png"
                        ]
                    }
                },
                "lint": {
                    "builder": "@angular-eslint/builder:lint",
                    "options": {
                        "lintFilePatterns": ["src/**/*.ts", "src/**/*.html"]
                    }
                }
            }
        },
        "torus-pdv-e2e": {
            "root": "e2e",
            "projectType": "application",
            "architect": {}
        }
    },
    "defaultProject": "torus-pdv",
    "schematics": {
        "@schematics/angular:component": {
            "prefix": "pdv",
            "style": "scss",
            "skipTests": true
        },
        "@schematics/angular:directive": {
            "prefix": "pdv",
            "skipTests": true
        },
        "@schematics/angular:service": {
            "skipTests": true
        }
    },
    "cli": {
        "analytics": false,
        "defaultCollection": "@angular-eslint/schematics"
    }

**VS Code Version:** 1.88.1
**Node Js Version:** v18.19.0
**Angular Version:** 13
**electron**: "^13.1.2",
**electron-builder**: "^22.11.7",
**electron-reload**: "^1.5.0",

**Comment by connor4312** [comment]
you want to debug the renderer, not main process, if you expect Angular breakpoints to bind.

**Comment by cristhianprog** [comment]
Sorry, I'm not sure I understand your answer.

**Comment by cristhianprog** [comment]
Sorry @connor4312 , I'm not sure I understand your answer.

**Comment by connor4312** [comment]
https://www.electronjs.org/docs/latest/tutorial/process-model

**Comment by cristhianprog** [comment]
Got it @connor4312. But is there any debug configuration that can solve this? Or is there any other way to debug?
