### ISSUE TITLE
Debugger always fails to attach to VS Code extension host (`"type" : "extensionHost"`)

### ISSUE THREAD

**Issue by minestarks** [microsoft/vscode-js-debug#2135]
**Describe the bug**

Recently, VS Code extension debugging using a `launch.json` configuration stopped working completely. This is with repos and `launch.json` configurations that used to work just fine (a few months ago?).

- I am not able to set breakpoints in .ts files
- I am not able to set breakpoints in the compiled .js files 
- I don't see my extension code under "loaded scripts"

**To Reproduce**

EDIT: Ignore this repro, it's user error. Instead, please see my comment below for a valid repro with our product repo https://github.com/microsoft/vscode-js-debug/issues/2135#issuecomment-2515838556

~~1. Clone the official "hello world" VS Code extension sample at https://github.com/microsoft/vscode-extension-samples/tree/main/helloworld-sample
2. Open the folder in VS Code
3. `npm install` 
4. Hit F5 in VS Code to launch the extension
5. Set a breakpoint in `extension.ts`
6. Set a breakpoint in `out/extension.js`~~

~~Observe that the breakpoints aren't getting bound.~~

**Log File**

~~[vscode-debugadapter-3a2882f3.json.gz](https://github.com/user-attachments/files/17941409/vscode-debugadapter-3a2882f3.json.gz)~~

**VS Code Version:** 

Version: 1.95.3 (user setup)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22621

**Additional context**

Originally encountered in when working in the Q# extension at https://github.com/microsoft/qsharp - but I did repro in every other VS Code extension I tried.

**Comment by minestarks** [comment]
@connor4312  Is the attached log corrupt? I can't unzip it on my end. I tried a few times, but I'm unable to get VS Code generate a valid file. Sorry :/

**Comment by connor4312** [comment]
Looks like it. Can you use `"trace": {"logFile": "${workspaceFolder}/log.txt"},` to make it write uncompressed?

**Comment by minestarks** [comment]
@connor4312 good morning, thanks for the suggestion, it worked: [helloword_sample_log.txt](https://github.com/user-attachments/files/17981852/helloword_sample_log.txt)  . Same repro steps as above. 

Not that I can make much sense of these logs, but I think I'd expect a `loadedSource` event for `C:\\src\\vscode-extension-samples\\helloworld-sample\\out\\extension.js` yet that isn't happening in the logs. It's like the debugger isn't even attached to the extension host process.

**Comment by connor4312** [comment]
To confirm, this happens even though you run the "Hello World" command in the debugged window?

**Comment by minestarks** [comment]
@connor4312  Oh, I'm so sorry! I did forget to run "Hello World" to activate the extension. When I do, breakpoints bind, debugging works as expected. Stupid mistake on my part, sorry to waste your time on that.

So my attempted Hello World repro is invalid, but I _am_ positively reproing with our Q# web extension. Here it is!!


This time I tried on some older VS Code versions as well, making sure to run the same exact scenario and that the extension is activating (language service and other features are working)

- **1.93.1 is last known good**
- **1.94.2 is first known bad**


Repo: https://github.com/microsoft/qsharp
launch.json (Using `"Run VS Code Web Extension"` config for this repro):

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Run VS Code extension",
            "type": "extensionHost",
            "debugWebWorkerHost": true,
            "request": "launch",
            "trace": {"logFile": "${workspaceFolder}/log.txt"},
            "runtimeExecutable": "${execPath}",
            "outFiles": [
                "${workspaceFolder}/vscode/out/**/*.js",
                "${workspaceFolder}/vscode/out/*.js"
            ],
            "args": [
                "--disable-extensions",
                "--extensionDevelopmentPath=${workspaceFolder}/vscode",
                "${workspaceFolder}/samples/"
            ]
        },
        {
            "name": "Run VS Code Web Extension",
            "type": "pwa-extensionHost",
            "debugWebWorkerHost": true,
            "request": "launch",
            "trace": {"logFile": "${workspaceFolder}/log.txt"},
            "outFiles": [
                "${workspaceFolder}/vscode/out/**/*.js",
                "${workspaceFolder}/vscode/out/*.js"
            ],
            "args": [
                "--extensionDevelopmentPath=${workspaceFolder}/vscode",
                "--extensionDevelopmentKind=web",
                "${workspaceFolder}/samples/"
            ]
        }
    ]
}
```

[qsharp_debug_1.93.1_good.txt](https://github.com/user-attachments/files/18000733/qsharp_debug_1.93.1_good.txt)
[qsharp_debug_1.94.2_bad.txt](https://github.com/user-attachments/files/18000732/qsharp_debug_1.94.2_bad.txt)
[qsharp_debug_1.95.3_bad.txt](https://github.com/user-attachments/files/18000734/qsharp_debug_1.95.3_bad.txt)

**Comment by minestarks** [comment]
Thank you! I patched my install locally and validated that this fixes the issue. Looking forward to the release
