### ISSUE TITLE
RFC: deno support for JavaScript Debug Terminal launch

### ISSUE THREAD

**Issue by cdaringe** [microsoft/vscode-js-debug#2141]
**Is your feature request related to a problem? Please describe.**

https://github.com/denoland/deno/issues/19328 is about supporting the JavaScript Debug Terminal for `deno`. `deno`'s debug instrumentation  is similar to node's, but doesn't have a `NODE_OPTIONS` equivalent, so presumably the same instrumentation strategy may not be used.

**Describe the feature you'd like**

A prescription, guide, and/or ideation for how to get `deno` workin'! FWIW, i'm no 💯 this is the correct repo for this discussion. Feel free to close at will. Thanks!

**Comment by connor4312** [comment]
You're in luck, this past iteration I added some API for this in response to an issue from the Bun folks: https://github.com/microsoft/vscode-js-debug/blob/main/EXTENSION_AUTHORS.md#extension-api (only on [nightly](https://github.com/microsoft/vscode-js-debug?tab=readme-ov-file#nightly-extension) until later this week). Let me know if that works for you.

**Comment by cdaringe** [comment]
Super interesting. Thanks!

**Comment by connor4312** [comment]
Merging into https://github.com/microsoft/vscode-js-debug/issues/2104
