### ISSUE TITLE
Debugger not resolving exported variables

### ISSUE THREAD

**Issue by adrianstephens** [microsoft/vscode-js-debug#2146]
**Describe the bug**

If I define an exported variable in a typescript file, the debugger will not see it from within that file.

(I hesitate to call this a bug - or at least *your* bug, but thought I'd let you know!)

**To Reproduce**

In a typescript file define an exported variable:
`export let xyz = 42;`

Stop the debugger somewhere in that file and put xyz in a watch window.
You will see:
`Uncaught ReferenceError: xyz is not defined`

Looking at the transpiled javascript I can see that xyz actually is undefined because it became:
`exports.xyz = 42;`

**VS Code Version:** 1.96.0

**Additional context**
I've recently switched to a new version of the typescript transpiler, so this might be a new thing.

**Comment by connor4312** [comment]
This is a limitation of renames in sourcemaps. The next version of the sourcemap specification, once adopted, should allow us to resolve these better.
