### ISSUE TITLE
Breakpoint hit but is shown in the transpiled file

### ISSUE THREAD

**Issue by KermanX** [microsoft/vscode-js-debug#2149]
**Describe the bug**

Possibly the exact same as #2101. However, I am still experiencing this in the latest `v1.96.0`.

**To Reproduce**

1. Clone https://github.com/KermanX/vsc-breakpoint-repro
2. Run `pnpm i`
3. Add a breakpoint in `main.ts`
4. Open a JavaScript debug terminal in VSCode, and run `node ./run.js` (or press `F5`)
5. The breakpoint will hit, but in the transpiled one. But the file path is the same.

![Image](https://github.com/user-attachments/assets/fe035bbc-f573-4d4f-8746-4d5a28c7222a)

**Log File**

[vscode-debugadapter-04947872.json.gz](https://github.com/user-attachments/files/18141082/vscode-debugadapter-04947872.json.gz)

**VS Code Version:** 1.96.0

**Comment by connor4312** [comment]
Your tooling is not generating a sourcemap for main.ts. I see a sourceMappingURL comment in your screenshot, but I don't get one locally and V8 doesn't parse one in your log file:

```json
{
  "method": "Debugger.scriptParsed",
  "params": {
    "scriptId": "181",
    "url": "file:///C:/Users/kerma/Desktop/vsc-breakpoint-repro/main.ts",
    "startLine": 0,
    "startColumn": 0,
    "endLine": 4,
    "endColumn": 3,
    "executionContextId": 1,
    "hash": "151db19419709e2eeeb1aa95c98c1da91dd080a2dfe990e1ebba985089a37ae0",
    "executionContextAuxData": {
      "isDefault": true
    },
    "isLiveEdit": false,
    "sourceMapURL": "", // <-
    "hasSourceURL": false,
```

For me setting the option `sourceMaps: true` or `process.env.JITI_SOURCE_MAPS = '1'` doesn't result in one either... so I would probably open an issue on your library.

[`tsx`](https://github.com/privatenumber/tsx) is also a good transpiler that works well out of the box.

**Comment by connor4312** [comment]
Oh, for me I had to explicitly turn off the cache for the change in options to take effect. So for me it works when I turn on sourcemaps and turn off cache:

<img width="644" alt="Image" src="https://github.com/user-attachments/assets/95c2d3c9-f079-4206-8b67-5f900835ad99" />

**Comment by KermanX** [comment]
> Oh, for me I had to explicitly turn off the cache for the change in options to take effect. So for me it works when I turn on sourcemaps and turn off cache:
> 
> <img alt="Image" width="644" src="https://private-user-images.githubusercontent.com/2230985/396167697-95c2d3c9-f079-4206-8b67-5f900835ad99.png">
> I would try setting these options for your run.

That works! Thank you so much~
