### ISSUE TITLE
Node.js run and debug ("Launch program") fail to debug

### ISSUE THREAD

**Issue by leduyquang753** [microsoft/vscode-js-debug#2150]
**Describe the bug**

When using run and debug with a Node.js program, the program is launched, but the editor does not successfully establish a debug connection and fails to set breakpoints.

![Image](https://github.com/user-attachments/assets/5a86be39-c320-4c5b-95c0-fbcbe6841a6e)

**Reproduction**

1. Create a script `test.js` with the following code:

```js
console.log("Started.");

await new Promise(resolve => {
	setInterval(() => {
		console.log("Tick.");
	}, 1000);
});

```

2. Set one or a few breakpoints anywhere within the code.
3. Create `launch.json` with a _Node.js: Launch program_ configuration:

```json
{
	"version": "0.2.0",
	"configurations": [{
		"name": "Launch program",
		"type": "node",
		"request": "launch",
		"skipFiles": ["<node_internals>/**"],
		"program": "${workspaceFolder}/test.js",
		"trace": true
	}]
}
```

4. Issue _Start debugging_ command.
5. Observe the debug console and the debugging panel, particularly the _Breakpoints_ section.

**Log file**

[vscode-debugadapter-92487e48.json.gz](https://github.com/user-attachments/files/18146359/vscode-debugadapter-92487e48.json.gz)

**Visual studio code version**

Version: 1.96.0
Commit: 138f619c86f1199955d53b4166bef66ef252935c
Date: 2h29:09,626; 11 Dec 2024 (UTC)
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.26100

**Additional context**

Tested with Node.js version 23.4.0 and a new empty Visual studio code data folder.

**Comment by connor4312** [comment]
This is a Node.js regression fixed in their next release https://github.com/nodejs/node/issues/56002
