### ISSUE TITLE
logPoints don't work correctly with } in the expression part

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#226]
After https://github.com/microsoft/vscode-js-debug/issues/113, logpoints will have a defect that also existed in v1. Our parsing of expressions out of logpoints is naive and won't work correctly when the expression contains a }.

One idea would be to look for the first {, then parse all text after that with TS. The first statement should be a block type. The end of the block would be the end of the embedded expression?

**Comment by connor4312** [comment]
Yea, I think that should work fine. TS will emit errors on the program but it should be able to parse the block and create the Program, and you can then strip out that area.

**Comment by roblourens** [comment]
It also doesn't handle having multiple statements

**Comment by alexr00** [comment]
Very cool. I did notice that I had to reload after changing my log point for the new log to get used the next time the point was hit. Expected?

**Comment by connor4312** [comment]
Not expected, I'll get a fix for that, thanks for mentioning it
