### ISSUE TITLE
BP goes to wrong line 

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#231]
- Debug the test repo from https://github.com/microsoft/vscode/issues/88532
- Set a breakpoint on line 3, `console.log('hello!')`
- It goes to line 5

**Comment by connor4312** [comment]
This is another issue with Babel's generated source maps. We try to set a BP here:

```
  console.log('hello');
^
```

That range maps to the following locations:

```
  console.log('hello');
^ ^           ^       ^
```

...and we pick the last one.

This isn't the first time we've had this problem with Babel. We could implement some special logic where if we bump the breakpoint over to the first statement of the line if we have a line BP set in whitespace. That would be more file i/o for disk and or require us to load content from CDP, though.

**Comment by roblourens** [comment]
Why do we pick the last one when there is an exact match?

**Comment by connor4312** [comment]
They're all exact matches 🙁 The whitespace before the console.log maps exactly to all four of those locations.

(Also, I misread one thing, we do instruct the source map to bump over to the next defined range which is the statement; it's that the console statement maps to four locations):

![](https://memes.peet.io/img/20-01-2efad446-0a51-4988-bfc1-0652be5773b8.png)

**Comment by connor4312** [comment]
It _might_ be safe to prefer to closest-to-0 column for line breakpoints. Or maybe get the breakpoint closest to the originally set column?

We don't get the first location, since we ran into an issue where a breakpoint on the first line of a function would get resolved outside the function in that scenario.

**Comment by connor4312** [comment]
Fix for one other behavior I noticed. It was racey but happened consistently on my windows machine: https://github.com/microsoft/vscode-js-debug/pull/236

**Comment by PSeitz** [comment]
Any idea why it works fine with these settings?

```json
{
      "type": "node",
      "request": "launch",
      "name": "Launch Program 2",
      "runtimeArgs": ["--nolazy", "-r", "${workspaceRoot}/babel-register.js"],
      "args": ["test.ts"]
    }
```

```javascript
const register = require('@babel/register').default;

register({ presets: [
    ["@babel/preset-env", {
      targets: { node: "current" }
    }]
  ],
  plugins: [
    "@babel/plugin-transform-typescript",
  ],
  extensions: [".ts", ".js"],
  cache: true
});
```

**Comment by connor4312** [comment]
We've since redone some of how this works. I should all work happily with Babel now.

**Comment by PSeitz** [comment]
The original, where babel is not loaded via "-r" still has issues with the breakpoints

**Comment by connor4312** [comment]
@PSeitz this may duplicate / be fixed with the changes in https://github.com/microsoft/vscode-js-debug/issues/407
