### ISSUE TITLE
Support the Edge browser

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#235]
Need to bring code for launching Edge from https://github.com/microsoft/vscode-edge-debug2/ to this repo.

**Comment by dhanvikapila** [comment]
@roblourens - We will be bringing the code to launch the new Edge browser and not Legacy Edge.

**Comment by connor4312** [comment]
Edge support work is complete at this time. Further improvements may be tracked in their own issues.

Testers: this is a meta-issue and does not need verification.
