### ISSUE TITLE
Issues debugging VueJS applications

### ISSUE THREAD

**Issue by jtsom** [microsoft/vscode-js-debug#239]
Trying to debug a Vue application, but I'm seeing lots of these errors in the console. Not sure if it is the cause of my failure to actual hit breakpoints:
```
[2020-01-15 14:25:54.915] [renderer1] [warning] UNRESPONSIVE extension host, 'ms-vscode.js-debug-nightly' took 96% of 461.196ms, saved PROFILE here: '/var/folders/w9/y7wbvtz13mv22f2hq9y752t00000gp/T/exthost-3000be.cpuprofile' [{"id":"gc","total":489,"percentage":0},{"id":"ms-vscode.js-debug-nightly","total":443948,"percentage":96},{"id":"octref.vetur","total":405,"percentage":0},{"id":"program","total":231,"percentage":0},{"id":"self","total":15935,"percentage":3}]
[2020-01-15 14:30:12.505] [renderer1] [warning] UNRESPONSIVE extension host, 'ms-vscode.js-debug-nightly' took 98% of 129.526ms, saved PROFILE here: '/var/folders/w9/y7wbvtz13mv22f2hq9y752t00000gp/T/exthost-b909a9.cpuprofile' [{"id":"cssho.vscode-svgviewer","total":127,"percentage":0},{"id":"ms-vscode.js-debug-nightly","total":126498,"percentage":98},{"id":"program","total":124,"percentage":0},{"id":"self","total":1933,"percentage":1},{"id":"vscode.git","total":132,"percentage":0},{"id":"vscode.json-language-features","total":419,"percentage":0},{"id":"vscode.typescript-language-features","total":133,"percentage":0}]
[2020-01-15 14:33:27.654] [renderer1] [warning] UNRESPONSIVE extension host, 'ms-vscode.js-debug-nightly' took 97% of 94.578ms, saved PROFILE here: '/var/folders/w9/y7wbvtz13mv22f2hq9y752t00000gp/T/exthost-c5ede5.cpuprofile' [{"id":"ms-vscode.js-debug-nightly","total":91462,"percentage":97},{"id":"octref.vetur","total":413,"percentage":0},{"id":"program","total":813,"percentage":1},{"id":"self","total":1756,"percentage":2}]
```

**Comment by jtsom** [comment]
It does seem to cause an issue. 

With this enabled, my breakpoints appear as "unbound breakpoint", and they are ignored. If I disable the extension (by removing the settings options), my breakpoints show normally and will be hit.

**Comment by connor4312** [comment]
The console errors aren't directly related to being able hit breakpoints, or not. Please enable `trace: true` in your launch.json and share the logs 🙂 

 > **⚠️Warning:** The logs will include information from your workspace, such as file paths. If you have any concerns about posting this publicly on Github, you can alternatively email them to me at connor@xbox.com. On our side, we only use these logs to investigate issues like this.

**Comment by jtsom** [comment]
I added a trace: "verbose" to the launch.json - where do these log messages show?

**Comment by jtsom** [comment]
I found the log file (the output window was cleared before I could see the path to the file.) I am sending it via email.

**Comment by connor4312** [comment]
@jtsom thanks for the logs! Can you try updating the `type` in your launch.json to `pwa-chrome` instead of `chrome`?

The `chrome` type with the setting goes through a special pathway in the existing debug adapters to start a session, it looks like there might be a bug in that code.

**Comment by jtsom** [comment]
Ah, didn't know there was a different type. I will give it a try tomorrow. (I had to futz with the launch.json and the babel.json file to be able to actually even click and set a breakpoint on the correct line...)

**Comment by jtsom** [comment]
Hm. I changed to use that, but I'm still seeing "Unbound Breakpoint".

FWIW, here's my launch.json:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "pwa-chrome",
            "request": "launch",
            "name": "Vue: Chrome",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}/src",
            "sourceMapPathOverrides": {
                // "webpack:///./src/*": "${webRoot}/*",
                "webpack:///src/*": "${webRoot}/*",
                // "webpack:///*": "*",
                // "webpack:///./~/*": "${webRoot}/node_modules/*"
            },
            "windows": {
                "runtimeExecutable": "C:\\Program Files (x86)\\Google\\Chrome Dev\\Application\\chrome.exe",
                "runtimeArgs": [
                    "--new-window",
                    "--remote-debugging-port=9222"
                ]
            }
            // "preLaunchTask": "npm: serve"
        }
    ]
}
```

**Comment by jtsom** [comment]
I wonder if it has to do with the fact that this is a Vue application, where the Javascript code is embedded in a .vue file (there are sections in the file - <template></template>, <script></script>, and <style></style>)
Setting a breakpoint in a plain .js file in the project sets the breakpoint just fine. Trying to set a breakpoint in a <script> block in a Vue file does not work.
Disabling this extension, I can set the breakpoints in the .vue file.

**Comment by jtsom** [comment]
Trying to set breakpoints in the .js file, however, I'm seeing strange things - I can't set on some lines, but can on others:

<img width="558" alt="image" src="https://user-images.githubusercontent.com/13488/72529429-52b45f80-383b-11ea-8e76-a2d2575b7a9a.png">

**Comment by jtsom** [comment]
(Sorry for all the comments)
I removed the settings I added in my babel.json file yesterday to get being able to select breakpoints working:
```
   env: {
     development: {
      sourceMaps: true,
       retainLines: true,
     },
   },
```
and now I can set breakpoints in my .vue files! And it looks like I can set breakpoints in my .js files fine too!

(an aside - should I disable the "old" Debugger For Chrome extension? Or can the two co-exist without conflict?)

**Comment by connor4312** [comment]
Nice I'm glad you got it working! And thanks for your patience with troubleshooting this 🙂 

It's interesting that those settings cause it to fail. I'll do a bit of research into what exactly they affect, and we might need to provide guidance in the future that they can cause issues. I'll close out this issue once my investigation is complete.

**Comment by jtsom** [comment]
I was also unaware of the "pwa-chrome" setting. The instructions say that there's no changed necessary to the launch.json. I wonder if a temporary line about "pwa-chrome" in addition to the settings changes would be useful?

Thanks!

**Comment by connor4312** [comment]
Yea, you shouldn't need pwa-chrome. The ${webRoot} variable isn't a standard VS Code thing--we [replace that](https://github.com/microsoft/vscode-js-debug/blob/604878d35d4d50092d2b1e4f6856ebd224006329/src/baseConfigurationProvider.ts#L104-L112) in the config resolution step, but going through the old debug type bypasses that step. This the debugger to think that your source files were literally at `./${webRoot}/src/foo.vue` instead of `/Users/whatever/code/src/foo.vue` and not resolve correctly. Tracking that in https://github.com/microsoft/vscode-js-debug/issues/240.

**Comment by jtsom** [comment]
So again, does that mean I can disable the existing Debugger for Chrome extension, and just use "chrome" vs "pwa-chrome"? Can the two co-exist?

**Comment by connor4312** [comment]
Yep, the two can coexist. You can disable the existing Debugger for Chrome extension if you'd like, it shouldn't have an effect one way or the other given you use `pwa-chrome` as your debug type.

**Comment by jtsom** [comment]
I may have spoken too soon.. I just tried to set a breakpoint again, and it's back to "unbound breakpoint"...

**Comment by connor4312** [comment]
I went through the Vue starter and found an issue, which may affect you (esp if it worked once for you but usually doesn't) in https://github.com/microsoft/vscode-js-debug/pull/242. Let me know if that works for you--either after tonight's nightly build, or by [running out of sources](https://github.com/microsoft/vscode-js-debug#installation) if you have lots of free time 🙂

**Comment by jtsom** [comment]
I'm game to try running from sources - is there a specific branch the change is on?

**Comment by connor4312** [comment]
It's on master now

**Comment by jtsom** [comment]
I think that's got it. Built from master and installed it (looks like the (nightly) name isn't in the name anymore, so I was confused, and the version number was different). But so far it's working. I'll continue to test.

Thanks!

**Comment by connor4312** [comment]
Okay, thanks for the confirmation! Can you share the Babel configuration you're running for the JS files?

**Comment by jtsom** [comment]
The babel config is pretty much stock:

module.exports = {
  presets: ['@vue/app'],
};

**Comment by jtsom** [comment]
Hm. I thought it was working with the latest nightly, but I am not able to consistently set a breakpoint:

<img width="202" alt="image" src="https://user-images.githubusercontent.com/13488/72635139-19a6e880-392a-11ea-941e-b33e184564e0.png">

**Comment by connor4312** [comment]
Thanks for the followup reports. I looked into it a bit more and, at least in my setup, the heuristic we use around the shortest URL doesn't _always_ work. It depends how sourcemaps are set up, I opened an issue for it here https://github.com/vuejs/vue/issues/11023

If you can forward me another log file, I can confirm whether you're facing the same issue or if it's something else.

**Comment by jtsom** [comment]
Thanks for your help with this. I'll try to get another log for you. It's sort of hit-and-miss as to whether a breakpoint will be hit. Today, I set a couple, but they were just ignored. Then they started working. Hopefully it'll get figured out, it's super helpful to not have to use the browser debugger directly.

**Comment by jtsom** [comment]
Log file on the way via email

**Comment by connor4312** [comment]
Thanks for the log! It looks like you're still on version 2020.1.20223 of this module which was from before our ${webRoot} and other fixes. Can you try updating and see if it works?

**Comment by jtsom** [comment]
Hm. I wonder if I grabbed an old log file? This is what I have installed:

<img width="422" alt="image" src="https://user-images.githubusercontent.com/13488/72829705-4a9a5c80-3c4d-11ea-8092-daf265e16fde.png">

**Comment by jtsom** [comment]
Ok, I'll grab something more recent. I have to track down the log file, as the message that shows where the logs are gets cleared before I can copy it
<img width="558" alt="image" src="https://user-images.githubusercontent.com/13488/72829897-9cdb7d80-3c4d-11ea-89a5-352968c1e301.png">

**Comment by jtsom** [comment]
On the way

**Comment by connor4312** [comment]
Yep, thanks again for your logs, and patience. It seems to be the same issue. I opened an issue on Vue for them to generate paths better here. They seem receptive to fixing it, hopefully we'll be able to get a PR in there this week. For the moment, you'll just need to use the Chrome devtools. I'll follow up here when there's a fix for you to try.

**Comment by jtsom** [comment]
Trying to set a breakpoint, and I'm now seeing a message "It's taking a while to configure your breakpoints. You can speed this up by updating the 'outFiles' in your launch.json." Is this new? I have no idea what to set for the outFiles? Should I mirror the "sourceMapPathOverrides"?

**Comment by connor4312** [comment]
Before we enter a debug session we scan the workspace for sourcemaps to do a first pass on where we need to set breakpoints. By default we recursively look in all folders except for node_modules, but you can configure this by setting outFiles to, for example, `["${workspaceFolder}/dist/**/*.js"]`, if that's where your build files are. If you aren't seeing this consistently, it may have just been one launch that ran slow for whatever reason.

**Comment by jtsom** [comment]
Given it's a Vue app, when it's running in debug mode, there really aren't any built files on disk (at least that I've found). The "sourceMapPathOverrides" is set to (an array of) "webpack://" type paths. There are (were) several listed:
```
            "sourceMapPathOverrides": {
                "webpack:///./src/*": "${webRoot}/*",
                "webpack:///src/*": "${webRoot}/*",
                "webpack:///*": "*",
                "webpack:///./~/*": "${webRoot}/node_modules/*"
            },
```
as I found that those helped with the setting a breakpoint problem, but I changed it to just be the second one in that list, and the last time I launched under debug, I did not get the error (and was able to set a breakpoint, were I couldn't before.

I'm chalking all of this up to the weirdness of trying to debug Vue... One more tick in the "Cons" column of Vue development :)

**Comment by jtsom** [comment]
Well, I think I'm just going to not even try to debug through VS Code a Vue application. It just doesn't work. I was having similar issues even with the original Chrome debugger extension. VueJS just does too many things to play nice with VSCode. Oh well, it was nice when it worked.

**Comment by seb0stian** [comment]
Hello I hope this belongs here.
When I want to set a breakpoint in my .vue file in my electron app in the methods section it sets a breakpoint two lines under the top of the file where the template element sits.
When I do the same with the old debugger everything works as expected.

**Comment by connor4312** [comment]
Added a bunch of special handling that makes Vue-cli applications work well out of the box -- tested hello worlds on Vue 3 and 4, and used Postwoman as a real-world Vue app.

Verifier -- easy way is to:

 1. `https://github.com/liyasthomas/postwoman.git && cd postwoman && npm i`
 2. `npm run dev`
 3. Add a pwa-chrome launch config for localhost :8080
 4. Set a breakpoint in some random callback. Verify that it gets hit.

Note: if you set a breakpoint at a top level (e.g. on an `export`) statement you can get into weird places. This is because the sourcemaps Vue produces are missing a range for that; this is a bug and confuses Chrome as well, I don't intend to fix it.

**Comment by roblourens** [comment]
Nice
