### ISSUE TITLE
vscode starts with extensions disabled

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#243]
- Start "Launch VS Code" config with js-debug
- Get this dialog: 
![image](https://user-images.githubusercontent.com/323878/72639258-0429c280-391a-11ea-897f-f28a2241464a.png)

not getting this with v1, weird

**Comment by roblourens** [comment]
Would be helpful if it would log the exact command run to start

**Comment by roblourens** [comment]
Weird, we have this:

https://github.com/microsoft/vscode-js-debug/blob/f3affb61da7e5fdb27f83d2f43914c16b0e48d7d/src/targets/browser/launcher.ts#L36

but I don't think this was happening before, do you know if something changed?

Also we should figure out how to handle this for the "chrome type launching things that are not chrome" case. Which could be a new debug type.

**Comment by connor4312** [comment]
Not sure. Git blame says that's been there for 7 months. Diego's change touched areas around this recently but I don't see anything suspicous.

**Comment by connor4312** [comment]
I think just removing that arg would be sufficient.

- The existing debug adapter doesn't provide a way to turn off built-in arguments, so doesn't seem necessary to implement globally.
- Chrome extensions can be very value in debugging. For example, the Redux devtools extension provides an additional experience that the debug adapter won't ever have built-in. Chrome launches are put into their own user data dir by default, so users will need to explicitly install extensions if they want them; we should respect those.
