### ISSUE TITLE
"restart" on attach config not working

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#245]
- Debug vscode
- Run "Attach to Extension Host"
- Reload the window
- The EH config should be disconnected, but then reattach when the EH is reloaded, but it never reattaches

**Comment by connor4312** [comment]
I don't think we implement reattachment if the target goes away, we consider it a graceful exit and end the session.

**Comment by roblourens** [comment]
There is a launch config flag "restart" that tells it to restart the session though, we should respect that.

**Comment by connor4312** [comment]
To verify:

 1. Run any long-running program via `node --inspect foo.js`
 2. Pick "attach to node.js process (preview)" in the command palette, and attach there
 3. Kill the process and restart it
 4. The debugger should automatically reconnect
