### ISSUE TITLE
js-debug insiders plan

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#248]
At this point, we'd like to get a larger audience on the new debug adapter. The first step we would like to take is including `js-debug-nightly` as a built-in extension inside of VS Code Insiders.

There will be a setting which, when enabled, seamlessly swaps to the new debug adapter.

```json
{
  "debug.javascript.usePreview": true
}
```

This is like the existing `useV3` settings, but it's one setting for both Chrome and Node.

js-debug today contributes default launch configurations. When `usePreview` is **off**, they will be published with a ` (preview)` suffix, so the quickpick might look like:

```
- Node
- Node (preview) <-- js-debug
- Chrome
- Chrome (preview) <-- js-debug
```

When the usePreview settings turned **on**, the existing debug adapters should not publish default configurations, and js-debug will drop the suffix:

```
- Node <-- js-debug
- Chrome <-- js-debug
```

cc @kieferrm @roblourens

**Comment by connor4312** [comment]
Hm, unfortunately it looks like the renaming is difficult here; the names in the launch configurations come from the names of the debuggers which cannot be changed conditionally. We may just have the `(preview)` flags always on and redirect...

**Comment by kieferrm** [comment]
Even with the 'preview' label that makes sense to me.
