### ISSUE TITLE
Set next statement (goto request)

### ISSUE THREAD

**Issue by huguesv** [microsoft/vscode-js-debug#249]
https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Goto

I'm debugging a vscode extension written in typescript. I really miss the ability to control execution via "set next statement" which I use regularly in Visual Studio with C#.

**Comment by connor4312** [comment]
Thanks for the suggestion!

Unfortunately, this doesn't appear to be possible within the Chrome debug protocol. There was [a related request](https://bugs.chromium.org/p/chromium/issues/detail?can=6&id=382904) on Chromium which is currently closed as a wontfix.

If that changes and the Chromium team implements something in the debug protocol for us to implement that, then we can definitely revisit this 🙂

**Comment by EricCornelson** [comment]
@connor4312, would it be possible to revisit this, if just for Blazor WASM? They've implemented a custom CDP request for this: https://github.com/dotnet/runtime/pull/64114

**Comment by connor4312** [comment]
It's not likely to be proritized for me in the near future but I would accept a PR for it
