### ISSUE TITLE
Wrong resolution for source path starting with /

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#254]
I have a simple app that I can't set breakpoints in, I think this worked earlier?

Sourcemap looks like
`"sources":["client with space/test1a.ts",...],"sourceRoot":"/"`

I can't set breakpoints in that ts file, if I break on a debugger statement, the path is 

`http://localhost꞉8081/out/client%20with%20space/client%20with%20space/test1a.ts`

But the absolute path starting with `/` should be resolved relative to webroot, not the sourcemap location like a relative path would be

**Comment by roblourens** [comment]
Also it might not be respecting the `webRoot` in my launch config? I have `"webRoot": "${workspaceFolder}/wwwroot"`

**Comment by connor4312** [comment]
Probably we're bailing out here because we see a path starting with a slash is a valid POSIX absolute path

https://github.com/microsoft/vscode-js-debug/blob/f1ae99ae308fc8912c97aceb2f9fa2568703b811/src/targets/browser/browserPathResolver.ts#L50
