### ISSUE TITLE
Conditional breakpoints not working?

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#259]
Was just trying to use a conditional bp and it seems like the condition is ignored.

**Comment by connor4312** [comment]
Seems to work for me, setting a BP with the simple conditional `false` causes it not to hit, and `true` does. Send logs?

**Comment by roblourens** [comment]
There is something weird going on but of course I didn't get a log earlier

**Comment by connor4312** [comment]
This was probably https://github.com/microsoft/vscode-js-debug/issues/282
