### ISSUE TITLE
Provide a diagnostic tool

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#260]
The v1 adapter has the `.scripts` command which dumps info about which scripts are loaded, the sourcemap info, and how the paths are finally resolved after applying overrides. It would be useful to have the same in this adapter. Would be awesome to have this in GUI form, a custom treeview, or opening an editor with a nicely formatted markdown grid, or something more user friendly than what v1 does.

**Comment by jasonwilliams** [comment]
Yes please, this would make debugging these issues much easier

**Comment by connor4312** [comment]
Could even pop open the browser and/or write an HTML file with details. We have a lot of data and being able to display it in a richer form than the debug console may make life easier. The analyzer could be built into it as well. That alone would make my debug loop a little faster.

**Comment by roblourens** [comment]
Sort of related, I have imagined a workflow where you can click a source that looks like `webpack://mycode.ts` and pick the file on disk that it corresponds to, and we would generate the launch config parameters to produce that correct mapping.

**Comment by connor4312** [comment]
Added a new command `Create Diagnostic Information` which generates a nice .html report. Example:  https://memes.peet.io/img/js-debug-diagnostics2.html

- shows current sources and shows you sourcemap children/parents
- has a 'breakpoint fixer' that checks for a few common cases
  - a breakpoint set in a file that was missing. Will show if there are any files of the same name in the runtime.
    - For .ts/x files it suggests adding sourceMap: true to the tsconfig.json if no files are found
    - For web launches it suggests changing the webRoot
    - If it sees the user specific outFiles, it suggests removing the glob (since we default to the workspace)
  - Breakpoints where they match a file, but are unbound by the runtime (almost always outdated sources or bad locations)

**Comment by bartocc** [comment]
I get the following error when running this new `Create Diagnostic Information for Current Session` command:

````
Command 'Debug: Create Diagnostic Information for Current Session' resulted in an error (Error processing createDiagnostics: Error: ENOENT: no such file or directory, open '/Users/julien/.vscode/extensions/ms-vscode.js-debug-nightly-2020.10.1317/src/index.bundle.js')
```

Is this a bug or am I missing something?

**Comment by connor4312** [comment]
Thanks for pointing that out; fixed in the next nightly

**Comment by bartocc** [comment]
I can confirm it works in `v2020.10.2217` 👍

**Comment by bartocc** [comment]
Here's the content of my "

**Comment by sippeangelo** [comment]
Where is this now? I've been following a trail of issues from the original .scripts command to this issue, but I can't find any `Create Diagnostic Information` command any more. Was it removed? What's the replacement?

**Comment by sippeangelo** [comment]
I guess it's been renamed?
https://github.com/microsoft/vscode-js-debug/blob/ff3de043dbaf918bbcf26186c08e94381fc1f5ae/src/build/strings.ts#L310
but I can't find any command like that either in VSCode 1.57.0
![image](https://user-images.githubusercontent.com/262378/122402305-a588ce00-cf7d-11eb-8a15-c63bfc7a9e9a.png)

**Comment by connor4312** [comment]
In the next release I added a simple rewrite so `.scripts` will also open the new tool
