### ISSUE TITLE
Support Edge: Add `browserVersion` property to support well-known browser versions (e.g. canary, dev, beta, stable)

### ISSUE THREAD

**Issue by johnemau** [microsoft/vscode-js-debug#268]
#### Background
This is part of the effort to achieve backwards compatibly with [vscode-edge-debug2] and [fully support debugging Microsoft Edge (Chromium)][1].

Currently Chrome and [soon to be Edge (Chromium)][1] support setting well-known version names as the `runTimeExecutable` (e.g. canary, beta, stable).

This will get awkward for as we increase the number of supported browsers and it would be better to have a separate property.

#### What needs to happen
*  Add a new `browserVersion` property that uses `findBrowser.ts` to set the `runTimeExecutable` value. For some more details [see this comment][2].
* For drop-in [vscode-edge-debug2] compatibility the `browserVersion` property should have an alias for `version` or we should use the name `version`.

Related: #235

[vscode-edge-debug2]: https://github.com/microsoft/vscode-edge-debug2
[1]: https://github.com/microsoft/vscode-js-debug/issues/235
[2]: https://github.com/microsoft/vscode-js-debug/pull/264#issuecomment-578868423

**Comment by connor4312** [comment]
Kai pointed our in our 1:1 that this the need for this is exclusive with #266; if we have separate configurations for edge, the ambiguity is removed when providing qualities in `runtimeExecutable`. And since the quality is itself exclusive with the runtime executable, I'm going to go that direction instead.
