### ISSUE TITLE
Second pwa-node launch doesn't connect debugger

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-js-debug#269]
Found testing https://github.com/microsoft/vscode/issues/89393 on Windows

- Add the pwa prefix to the Launch VS Code (Main Process) configuration in the vscode project
- Run the Launch VS Code (Main Process) launch config.
- Wait until debugging is ready
- Close the OSS window that has opened
- Debugging ends
- Run the Launch VS Code (Main Process) again.
Expected: The OSS window opens and debugging starts.
Actual: The OSS window opens, but debugging never starts (no orange status bar + debug toolbar). When I close the OSS window, I get an error notification "no debug adapter found".

**Comment by connor4312** [comment]
Does this still happen on recent insiders? Wonder if it's that session creation race; that was the cause of quite a few similar bugs.

**Comment by alexr00** [comment]
Looks like it's fixed now.

**Comment by connor4312** [comment]
Cool, thanks for confirming!
