### ISSUE TITLE
Restarting a broken in pwa-node attach doesn't work

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-js-debug#270]
Testing https://github.com/microsoft/vscode/issues/89393 on Windows

- Run the existing, not pwa, Launch VS Code launch config in the vscode project.
- Modify the Attach to Extension Host config to be pwa-node and run it
- It attaches nicely and you can debug. Set a break point and hit the break point in the extension host.
- Hit the Restart button in the debug toolbar
Expected: The extension host will be re-attached to and I'll be at my same hit breakpoint.
Actual: I'm not sure what happens. I think that it never re-attaches, and I don't see that execution is still paused on my breakpoint.

**Comment by connor4312** [comment]
> Expected: The extension host will be re-attached to and I'll be at my same hit breakpoint.
Actual: I'm not sure what happens. I think that it never re-attaches, and I don't see that execution is still paused on my breakpoint.

When the debugger detaches, Node/V8 will automatically continue execution, so when reattaching it won't be at the same breakpoint. I see the same behavior with the existing debugger, which I tested by seeing the `counter` increment in

```
let counter = 0;
setInterval(() => {
  console.log(counter++); // <- breakpoint here
}, 1000);
```

**Comment by alexr00** [comment]
In that case, this isn't an issue. I must have just triggered the same breakpoint twice when trying the same scenario with the old debugger.

**Comment by connor4312** [comment]
Okay, thanks for the confirmation! 🙂
