### ISSUE TITLE
Break points in extension activation are not hit when using pwa-extensionHost

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-js-debug#273]
Testing https://github.com/microsoft/vscode/issues/89393 on Windows

- Debug an extension and put breakpoints in the extension activation code.

The breakpoints are never hit, even if I reload. Breakpoints in other places are hit though.

**Comment by chrmarti** [comment]
Might be the same, sourcemaps are off (compare stacktrace with source location and see breakpoint location):
![image](https://user-images.githubusercontent.com/9205389/73274924-b00ac200-41e6-11ea-8e07-484300e91aa7.png)

**Comment by connor4312** [comment]
Thanks for the issue. I haven't seen this dogfooding js-debug before, but it may be https://github.com/microsoft/vscode-js-debug/issues/262 which is a timing issue I never seem to hit on my main OSX machine.

@alexr00 which extension did you try testing with?

**Comment by alexr00** [comment]
The tree provider sample extension https://github.com/microsoft/vscode-extension-samples/tree/master/tree-view-sample

**Comment by connor4312** [comment]
Please let me know if this fix works for you Alex
