### ISSUE TITLE
Extension host debugging:  Breakpoints don't rebind after restart

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-js-debug#274]
Testing microsoft/vscode#89393 on Mac.

Extension host debugging:

Breakpoints don't rebind after restart:
![image](https://user-images.githubusercontent.com/9205389/73275954-34aa1000-41e8-11ea-9d7d-4c4b00b94bc4.png)

Note that I opened extension.js from the Loaded Scripts section. Then added a breakpoint, that was shown as bound. Then restarted and the breakpoint did not bind again.

**Comment by connor4312** [comment]
Pushing this to (early) Feb since the fix is a little more intricate than thought + may not get in today
