### ISSUE TITLE
Forked hashing process breaks debugging the adapter process using v1

### ISSUE THREAD

**Issue by EricCornelson** [microsoft/vscode-js-debug#275]
It seems that in some scenarios we will never get `breakpoint` update events, or even `paused` events from the adapter.

So far I've only been able to reproduce this in VS. For some reason VS further upstream is sending a double `setBreakpoints` request (one right after the other, same parameters), which may be the trigger?

This was the issue I bisected back to 951c8f68c0affe3f6c53e4cf4a77fc77ce327455. It's not totally clear to me how the hashing might be related, but it works before that commit and breaks afterwards 😄 

Logs:
[vscode-debugadapter_breakpoint-bug.log](https://github.com/microsoft/vscode-js-debug/files/4125475/vscode-debugadapter_breakpoint-bug.log)

**Comment by EricCornelson** [comment]
Found the root cause here. It's actually an instance of https://stackoverflow.com/questions/50885128/how-can-i-debug-a-child-process-fork-process-from-visual-studio-code

I've been typically launching the debugger in flatsession/server mode from vscode so I can set breakpoints if I need to. Since hashing moved to a separate process, the `fork` call tries to inherit the --inspect-brk flag and blows up.

**Comment by connor4312** [comment]
hmm, well, if you use js-debug to spawn the flat server, this won't be a problem since we don't use --inspect-brk to attach 😉
