### ISSUE TITLE
Empty target name

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#278]
Saw this while debugging the "Launch VS Code" launch config together

[vscode-debugadapter.json.txt](https://github.com/microsoft/vscode-js-debug/files/4131372/vscode-debugadapter.json.txt)

**Comment by connor4312** [comment]
Apparently [I added](https://github.com/microsoft/vscode-js-debug/commit/42dcd6dc15dcef21a2d2ed53ca1d381ec4b5d847) that warning because of an intermittent test failure. We apparently haven't seen that much/at all since enabling CI, so I'm just going to drop that log.

**Comment by connor4312** [comment]
Actually, found+fixed it with https://github.com/microsoft/vscode/issues/90149
