### ISSUE TITLE
Thread events coming in before the response to initialize crashes the debug session in Visual Studio

### ISSUE THREAD

**Issue by EricCornelson** [microsoft/vscode-js-debug#281]
Thread events are send out immediately when a new session attaches, which often means they go out before the IDE host has sent the initialize request. This can often crash the debug session in VS, as the thread's created event comes in before the session is actually started in VS which means it gets missed, then later when the adapter sends the thread exit event VS crashes because it can't find the exiting thread.

Logs:
[vscode-debugadapter-early-thread-events.log](https://github.com/microsoft/vscode-js-debug/files/4131983/vscode-debugadapter-early-thread-events.log)

**Comment by roblourens** [comment]
I'm confused about the flow in the log. Why are the very first lines `cdp.send` before we have even attached to a browser?

**Comment by EricCornelson** [comment]
`setup()` isn't being called on the logger until the launch/attach request in `Binder`, so right now we're missing a bunch of stuff at the start (also that call is async and not being awaited).

**Comment by roblourens** [comment]
I don't understand why that's different from the normal vscode scenario where we get all the logs, I assume it has something to do with what the flat session launcher is doing.

**Comment by EricCornelson** [comment]
Could be. It looks like there's a queue for messages that come in before the setup, but for some reason it's not working completely.

I see the same issue launching in debug server mode from vscode as well.

**Comment by roblourens** [comment]
In the debug server case, it always works the first time, but fails on subsequent launches because the logger is not reset between runs. 

In your case, reading the OP more carefully, are you attaching to a service worker or something after the first connection has already been established?

**Comment by roblourens** [comment]
I guess the log thing seems to happen a lot https://github.com/microsoft/vscode-js-debug/issues/299
