### ISSUE TITLE
Changes to logpoints aren't reflected until restart

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#282]
https://github.com/microsoft/vscode-js-debug/issues/226#issuecomment-580314559

**Comment by joaomoreno** [comment]
ping @connor4312

**Comment by alexr00** [comment]
I found this, I know how to verify :)

**Comment by alexr00** [comment]
I'm still seeing this. I'm debugging the helloworld-sample extension sample. Steps:
- Set log point on the `showInformationMessage` call:
```
{
    let x = 2+2;
    if (x>3) {
        return x;
    } else {
        return 10;
    }
}
```
- F5
- Run Hello World command and check the console. You should see 4 logged.
- Change log point:
```
{
    let x = 2;
    if (x>3) {
        return x;
    } else {
        return 10;
    }
}
```
- Do not reload, just go back to where the hello world extension is running and run the hello world command again.
I expect to see 10 logged, but it is still 4.

**Comment by alexr00** [comment]
This is with version 2020.1.41823. I don't see any tags to I'm not sure if it has the fix.

**Comment by connor4312** [comment]
Thanks for verification! Yep the latest version is `2020.1.43263`, the fix isn't present in .41.

And yes the version numbers are kind of confusing, I copied the logic from another of our nightly extensions. I'll probably modify it to just be `YYYY.MM.DDHH` tomorrow so that 2020.2's versions are more parsable.

**Comment by alexr00** [comment]
👍 I wasn't getting the update for some reason. I uninstalled and re-installed it. ( @sandy081 not sure if I should have received the update already).

**Comment by connor4312** [comment]
For the nightly I bump it manually since having the version at `latest` made VS Code download the extension again on every boot and also do other weird things. I just have a small shell script for it that I've [been running](https://github.com/microsoft/vscode/commits/master/build). We probably won't be bumping it every day once we get past insiders into a more stable state, so I didn't bother trying to refactor things to make latest work correctly.
