### ISSUE TITLE
Debug code lens in package.json leaves out `npm`

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-js-debug#287]
From: https://github.com/microsoft/vscode-js-debug/issues/214#issuecomment-580398421

 1. `npx create-react-app my-app --template typescript `
 2. Hit the debug code lens in the package.json and run tests

In the debugger terminal I see that `react-scripts test` is run, not `npm react-scripts test`, so it fails to run.

**Comment by connor4312** [comment]
Ahh. I always have ./node_modules/.bin in my PATH so I never noticed, good catch
