### ISSUE TITLE
"debug.node.useV3" not recognised as an option on MacOS

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode-js-debug#290]
On windows the option works fine, but on MacOS it doesn't seem to be recognised. Is this a known issue?

v2020.1.43263
![useV3](https://user-images.githubusercontent.com/936006/73676707-c0221600-46ac-11ea-948e-0f6f33283005.gif)

**Comment by connor4312** [comment]
This is actually provided by the older debug extension, is your `ms-vscode.node-debug` extension outdated?

**Comment by jasonwilliams** [comment]
I don't think ive ever had that plugin installed, was this baked into VSCode itself?

**Comment by connor4312** [comment]
Yes, it's built-in. If you search for `ms-vscode.node-debug` in the extension view it should come up.

**Comment by jasonwilliams** [comment]
oh i see it, its v1.41.1

**Comment by roblourens** [comment]
Is this VS Code Insiders? It will only work in Insiders right now

**Comment by jasonwilliams** [comment]
ah no, this is Stable

**Comment by connor4312** [comment]
Thanks for the info. The useV3 option will be in stable in 1.42 which should be released later this week. Working as intended for the moment 🙂
