### ISSUE TITLE
Can't set "program" to source file

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#291]
- Create a node launch config where the "program" attribute points at a .ts file
- It tries to run the .ts file with node

The v1 DA tries to resolve the .ts file when `outFiles` is given, and otherwise will refuse to launch. We don't necessarily need the behavior to guess whether a file is a .js file because it can't be 100% accurate (https://github.com/microsoft/vscode/issues/89882) but we should at least resolve .ts files with the sourcemaps we found, for backcompat.

**Comment by connor4312** [comment]
I'm not totally sure I agree with this. For instance someone could use `ts-node` as their runtime executable and be to set `program` to a `.ts` file.

**Comment by roblourens** [comment]
In that case (ideally) there would be no sourcemaps present so we would pass the .ts file through.

This might be disabled in v1 if `runtimeExecutable` is set?

**Comment by roblourens** [comment]
That's not the case. People use `args` with ts-node in v1 to work around the "program" restriction.

**Comment by connor4312** [comment]
I feel like people using TypeScript would generally know that they can't generally run uncompiled code directly in Node. Not sure that auto-fixing the couple of cases where they don't is worth the need for a workaround + complexity in the debug adapter. Maybe one alternative would be providing an extra helpful message if we see a syntax error in the program's stdout combined with a non-`.js` extension?

**Comment by roblourens** [comment]
Even though this has always been a little too "magical" for my taste, I think we should support it just to be compatible with old launch configs.

**Comment by connor4312** [comment]
Mm. Maybe try to do this but just go ahead and run the program if we don't see a sourcemap, to drop the need for a workaround?
