### ISSUE TITLE
sourceReference set on extension.js in js-only extensions

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#295]
- Clone https://github.com/octref/polacode
- Set a breakpoint at https://github.com/octref/polacode/blob/master/src/extension.js#L124
- Debug the extension, hit the breakpoint
- The source in the stack has a sourceReference

[vscode-debugadapter.json.txt](https://github.com/microsoft/vscode-js-debug/files/4151079/vscode-debugadapter.json.txt)

**Comment by connor4312** [comment]
Accidentally committed a test change that removed the double-hashing added previously. Undoing that and adding a test case so it doesn't happen again 😶
