### ISSUE TITLE
Tests: Add integration test for WebView launch scenario

### ISSUE THREAD

**Issue by johnemau** [microsoft/vscode-js-debug#303]
### Steps
1. Create a simple WebView2 application and include it in the project.
2. Have the application launch and hit a break-point as an integration test, similar to the int-chrome tests.

### Platforms
Windows 10 is currently the only supported platform for WebView2. 

### Background
WebView2 debugging support landed in #264, and #285.

**Comment by johnemau** [comment]
@connor4312, because the WebView2 application will need to be a Win32 executable what is the preferred way for me to add it as a test dependency?

I would like to avoid committing a binary file to the project and avoid adding build tooling for WebView2, so maybe a package?

**Comment by connor4312** [comment]
I'm fine with a binary file. We did that for [one test case](https://github.com/microsoft/vscode-js-debug/tree/master/testWorkspace/nodePathProvider/up-to-date) already.
