### ISSUE TITLE
VSCode: breakpoint not hit in electron-main on startup

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-js-debug#308]
Steps:
* use code-insiders
* use the launch config Debug VS Code Main, Renderer & Extension Host
* add breakpoint into https://github.com/microsoft/vscode/blob/eec46fcfc435967db4cb56bc8a825b221938f184/src/vs/code/electron-main/window.ts#L107
* start

=> the breakpoint is not hit it seems

**Comment by connor4312** [comment]
Does this work for you with the existing debuggers? I think this code may be run early on in the main process, which we only attach to after it's running, so there's a good chance we attach after the code has already run. If this is the case, it's just an artifact of how the process gets launched and would be something to evaluate in the VS Code core side of things.

If I put a `debugger;` statement in there to force the main process to pause, I can set and hit breakpoints later on in the file.

**Comment by roblourens** [comment]
I think the config `Launch VS Code (Main Process)` should work for this. The one you used does an "attach" for the main process so it's a race like connor says.

**Comment by connor4312** [comment]
I am able to hit the breakpoint with js-debug via `Launch VS Code (Main Process)`

**Comment by roblourens** [comment]
I did file a bug for that launch config though: https://github.com/microsoft/vscode-js-debug/issues/310 but basically this scenario is covered so I'll close
