### ISSUE TITLE
Session terminates while starting "Launch VS Code (Main Process)"

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#310]
```
Note: Using the "nightly" debug extension
/Users/roblou/code/vscode/scripts/code.sh --no-cached-data
Debugger listening on ws://127.0.0.1:58080/dceda7b5-b989-4bfe-aa16-11bea29d2adc
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Code - OSS
execution.js:83
Debugger attached.
Debugger attached.
Waiting for the debugger to disconnect...
Debugger listening on ws://127.0.0.1:58084/024b383c-f27d-4893-8b10-3b477d35179d
For help, see: https://nodejs.org/en/docs/inspector
Debugger listening on ws://127.0.0.1:58088/d5afc97f-184b-44b5-9c39-4b8f743d3a48
For help, see: https://nodejs.org/en/docs/inspector
Waiting for the debugger to disconnect...
error Command failed with signal "SIGTERM".
Waiting for the debugger to disconnect...
/Users/roblou/code/vscode/scripts/code.sh: line 15: 90232 Terminated: 15          yarn electron
Process exited with code 143
```

It attaches to all the node processes that are started from code.sh and there is something that it doesn't like about that. I can debug fine if I comment out all the lines in that script that start other node processes.

Works for Connor so maybe a race.

**Comment by connor4312** [comment]
Does this still happen on recent insiders? Wonder if it's that session creation race; that was the cause of quite a few similar bugs...

**Comment by roblourens** [comment]
Yeah still reproes

**Comment by connor4312** [comment]
Wanted to check on this again. If so let me know and we can look into this together.

**Comment by roblourens** [comment]
Yeah still reproes

**Comment by roblourens** [comment]
[vscode-debugadapter-0.txt](https://github.com/microsoft/vscode-js-debug/files/4647205/vscode-debugadapter-0.txt)

**Comment by connor4312** [comment]
Sorry, I didn't realize I hadn't bumped js-debug on insiders for a while, so the potential fix I wanted to feel out wasn't there. Please try one more time on the next insiders / with the latest js-debug and let me know.
