### ISSUE TITLE
Adapter occasionally writes lots of nulls (several mb worth) to the logs

### ISSUE THREAD

**Issue by EricCornelson** [microsoft/vscode-js-debug#311]
Repro steps: Unknown. Not able to consistently repro

See attached log

[nulls-vscode-debugadapter.log](https://github.com/microsoft/vscode-js-debug/files/4167429/nulls-vscode-debugadapter.log)

**Comment by connor4312** [comment]
Will be fixed with the refactors relating to https://github.com/microsoft/vscode-js-debug/issues/299

**Comment by connor4312** [comment]
Please let us know if you see this again. Otherwise (@ endgame testers) feel free to mark this verified as-is.
