### ISSUE TITLE
Node scripts don't run first time with integratedTerminal

### ISSUE THREAD

**Issue by dancrumb** [microsoft/vscode-js-debug#318]
Following this issue: https://github.com/microsoft/vscode/issues/90251, I installed the new debugger.

It solved the problem in the original issue, but brought along its own.

I have the following configuration:
```
{
      "type": "node",
      "request": "launch",
      "name": "API Server",
      "args": ["${workspaceFolder}/src/server.ts"],
      "console": "integratedTerminal",
      "runtimeArgs": ["-r", "ts-node/register", "-r", "tsconfig-paths/register"],
      "runtimeVersion": "12.15.0",
      "env": {
        "RAVEN_ENVIRONMENT": "local",
        "NODE_ENV": "local",
        "AWS_REGION": "us-west-2",
        "LOG_LEVEL": "debug"
      }
    },
```

When I start it from the "Run and Debug" panel, it opens a terminal and I get the following output:

```
/Users/danrumney/.nvm/versions/node/v12.15.0/bin/node -r ts-node/register -r tsconfig-paths/register /Users/danrumney/WebstormProjects/ohana/src/server.ts 
Debugger listening on ws://127.0.0.1:60446/8ed0beb3-2330-4a06-bae0-b56ec66d7d27
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Waiting for the debugger to disconnect...
direnv: loading .envrc                                                                                                                           
➜  ohana git:(develop) ✗ /Users/danrumney/.nvm/versions/node/v12.15.0/bin/node -r ts-node/register -r tsconfig-paths/register /Users/danrumney/WebstormProjects/ohana/src/server.ts 
Debugger listening on ws://127.0.0.1:60454/3f945706-0d0c-48de-af1e-adeb2e36c52e
For help, see: https://nodejs.org/en/docs/inspector
[1]    55758 terminated  /Users/danrumney/.nvm/versions/node/v12.15.0/bin/node -r ts-node/register -r 
```

I ran `echo $?` and got an rc of `143`

If I then try to run it again, everything works as I would expect it to...

**Comment by dancrumb** [comment]
For the record, I followed the instructions thus:

> 1. Installing the js-debug-nightly extension,
> 2. Adding "debug.node.useV3": true and "debug.chrome.useV3": true to your user settings,
> 3. Then you should be able to run and debug your programs without changing your launch config. If you can't, then please file an issue.

**Comment by connor4312** [comment]
This is because you use nvm, which runs an npm command to get configuration when the terminal opens. The debugger right now doesn't know that npm is not what we actually want to debug--so it treats it as the main target, and then after it disconnects (i.e. the session is over) just kills everything else.

Had an issue on vscode core for this but it looks like I forgot to transfer it over--thanks for the report!

**Comment by dancrumb** [comment]
You bet. Is there any information I can provide to help or is this pretty easy for you to recreate?

**Comment by connor4312** [comment]
It's easy to recreate, thank you though :)

**Comment by connor4312** [comment]
Fixed with https://github.com/microsoft/vscode/commit/6a04aa0477a0cf6d32e4c5c8db92d23ebdebea14, should be good to go in the next Insiders build.
