### ISSUE TITLE
Strings with newlines in them don't display well in the hover

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-js-debug#319]
![image](https://user-images.githubusercontent.com/641685/74182643-6fad3a00-4c11-11ea-8103-e41b415ac9e5.png)

**Comment by roblourens** [comment]
@isidorn

**Comment by connor4312** [comment]
I'm guessing this is 😉  https://github.com/microsoft/vscode/issues/73845#issuecomment-582458652

**Comment by roblourens** [comment]
Oh, right

**Comment by isidorn** [comment]
Ok, so per that issue, this should be handled by the debug adapter. Thus assigning you two.
VSCode can also try to be smart for the debug hover, but I would prefer not to do that.
