### ISSUE TITLE
Add ability to reference a return value, e.g. $returnValue

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-js-debug#323]
I like the new `Return value` item in the _Variables_ view, but I wish there was a way to reference that value outside of that view. For example in the _Debug Console_ or _Watch_. In both of those cases, the use-case would be to inspect/watch a specific property or call a method on the return value.

FYI, VS supports this as `$ReturnValue` at least in C#.

Refs: https://github.com/microsoft/vscode/issues/88678

**Comment by connor4312** [comment]
💪 for this month, more likely next month  (so backlog for now...)

**Comment by connor4312** [comment]
That was... surprisingly easy. Mildly hacky, but it works. Will take a little more to get it production ready (in completions and everything). Should have it monday morning

![](https://memes.peet.io/img/20-03-061ae14e-5528-4c8e-b8b8-27a322bee446.png)
