### ISSUE TITLE
Node hashbang breaks file hash verification

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#324]
From https://github.com/microsoft/vscode-js-debug/issues/286

- Debug a script that has `#!/usr/bin/env node` as the first line
- The script content reported by the runtime (and I assume that the hash is calculated on) excludes this line

**Comment by connor4312** [comment]
Sounds like a simple replacement fix here https://github.com/microsoft/vscode-js-debug/blob/master/src/common/hash/hash.ts#L48

**Comment by roblourens** [comment]
Doing some testing, seems like anything after a `#!` up to the newline is removed. Only valid as the first line.
