### ISSUE TITLE
js-debug: loaded scripts inconsistencies

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-js-debug#329]
VS Code stable

- debug express "hello world" app by setting a breakpoint in app.js:31

js-debug shows these loaded scripts:
![2020-02-12_16-09-26](https://user-images.githubusercontent.com/1898161/74348890-b175e600-4db3-11ea-8914-4cba07e797ff.png)

whereas node2 shows these loaded scripts:
![2020-02-12_16-16-10](https://user-images.githubusercontent.com/1898161/74348852-a15e0680-4db3-11ea-95e7-a3da70e1e9f1.png)

(the latter is correct)

The main problem is that js-debug does not prefix internal modules (e.g. _http_agent.js, http.js, tty.js) in a way that groups them together under one node in the Loaded Scripts view). As a result they appear intertwined with the user's project files (app.js. bin/www).

Node2 uses the artificial prefixes `<node_internals>` and `<eval>`.

I suggest that js-debug (at least for now) does the same as node2.

The other problem is the bogus debug session "Launch Program" that appears without ever having any scripts under its node. We can address this as part of https://github.com/microsoft/vscode/issues/90518.

**Comment by connor4312** [comment]
Should be better now 
![image](https://user-images.githubusercontent.com/2230985/74369873-fb96a180-4d8a-11ea-9ed2-2dd11d9d5ed6.png)
