### ISSUE TITLE
Increase js-debug adoption in Insiders

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#333]
js-debug is thus far trending well in parity and approaching quality with existing debuggers. Now that we're on insiders (#248) and have seen a gradual increase in users, we would like to expand its audience further.

For this, I propose adding behavior to `vscode-node-debug` and `vscode-chrome-debug` that, on Insiders only:

 1. Stores the number of activations in the last 7-day window as a JSON file in the extension `globalStoragePath`.
 2. On activation, if a) the special `js-debug-prompted` file does not exist in the `globalStoragePath`, b) the setting `debug.javascript.usePreview` is false (default), and c) they have at least 5 debug sessions over the last week, then create the `js-debug-prompted` file and show a notification to the user asking if they would like to try out our new debugger.
 3. If the user answers affirmatively, toggle the `debug.javascript.usePreview` in their user settings, and display a confirmation which setting to turn off (and to file an issue!) if they run into problems.

Q: Maybe something else we could do would be showing a notification when we see `usePreview` gets toggled off (if the js-debug extension is active) thanking them for trying the preview and asking them to file issues they ran into--assuming users will only toggle it off if they ran into problems.

cc @roblourens @kieferrm

**Comment by roblourens** [comment]
In vscode itself we have the ExperimentService which is built to handle this sort of thing - you can define some conditions, and when they are met, trigger an action. 

On the other hand, what you suggest is fairly simple and I'm not sure what benefits using the ExperimentService would give vs just having the extension do it itself.

**Comment by connor4312** [comment]
Ah, that's neat. Do you have an idea of how we would define this experiment in the ExperimentService? From skimming the code there's the [`IRawExperiment`](https://github.com/microsoft/vscode/blob/1fbacccbc900bb59ba8a8f26a4128d48a1c97842/src/vs/workbench/contrib/experiments/common/experimentService.ts#L84-L108) but I don't see an (existing) way to express the condition we want.

**Comment by roblourens** [comment]
Yeah I think we would have to implement a new type of condition.

**Comment by connor4312** [comment]
The experiment changes in place and we'll be ramping this up after our Feb endgame.

**Comment by connor4312** [comment]
![image](https://user-images.githubusercontent.com/2230985/75830760-7dfcfa80-5d66-11ea-9e38-5d2b3d21bd0e.png)

![image](https://user-images.githubusercontent.com/2230985/75830782-8b19e980-5d66-11ea-9848-a8f332ad1e1b.png)

**Comment by connor4312** [comment]
There were a couple more changes needed in the vscode experiments service but, thanks to the new schema version, we don't need to wait because of that 🙂 I have things ready and will do some final validation in the morning.

**Comment by roblourens** [comment]
In https://github.com/microsoft/vscode/commit/25ef9b4765076f0a10564734a0eb08228f810e29 what does "triggering experiments on the fly" basically mean?

Also what will this experiment to on old versions of Insiders?

**Comment by connor4312** [comment]
@roblourens previously the conditions for experiments were only evaluated on boot. The change adjusts it so that we re-check the experiments in the "evaluating" state when we get their events, which causes the notification to show when the user starts the nth debug session (instead of the next time they launch VS Code).

**Comment by roblourens** [comment]
Yeah but something will happen with versions of insiders before you added the schema checking, they are out there. I assume they will all get a notification without the conditions being checked properly. That's ok but we should make sure it doesn't do something bad.

**Comment by connor4312** [comment]
Ah, yea. They will all get the prompt. I can rename it so future versions don't see the prompt. Since I had to make another change today anyway, we may as well do that.

**Comment by connor4312** [comment]
The experiment is released in the most recent insiders. We'll monitor  👀
