### ISSUE TITLE
Contribute to the initial debug view

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#346]
https://github.com/microsoft/vscode/issues/85548

**Comment by isidorn** [comment]
Let me know if you need help with this.
I would be interested in your feedback before I start talking to other debug extension authors about their adoption.

**Comment by connor4312** [comment]
I'll start looking at this today/tomorrow 🙂

**Comment by connor4312** [comment]
Observations while implementing:

 - It would be nice to be able to contribute to the "run and debug" quickpick more explicitly. For instance, I could put auto-discovered npm scripts there, instead of needing a separate button for it.
 - Noticed that launching the debug terminal through Run and Debug felt weird. I cleared out its "languages" array so that it's never suggested that way.
 - Not having programmatic control over the welcome view may make things difficult for some implementors. For instance--while I'm fine having npm scripts behind the Run and Debug button--if I did want a top-level button for that, I could not control the visibility of it based on e.g. whether a package.json is present. I think this might become more of a concern with the change to show the welcome view whenever there isn't a debug session (will discuss more on that PR)
 - It'd be nice to be able to control the presence of buttons based on languages present in the workspace, rather than the last opened file. If I mix languages on a project, it may be a little confusing to figure out when different buttons are visible/hidden.

**Comment by isidorn** [comment]
1) I believe this issue captures what you want https://github.com/microsoft/vscode/issues/88230
2) Makes sense. Debug termianl should not be part of the Run and Debug
3) You should be able to control the visibile via context keys. We could introduce a context keys based on if a package.json is present. I do not think an extension can contribute context keys
4) vscode has no notion of a languages present in a project. This seems like a general vs code request

Great, button looks sexy! I would just remove the word `any` from the sentence, I think the flow of the sentence would be nicer without it.

fyi @weinand

**Comment by weinand** [comment]
Why is this terminal called the "Debug Terminal" and the "JavaScript Debug Terminal"? 
This makes it appear very generic (which is misleading).

The way it works restricts it to Node.js and the description seems to confirm this: "...to instantly debug any Node.js scripts you run".

I suggest to call it "Node.js terminal".

**Comment by isidorn** [comment]
Agree, Debug is too specific. Users might be confused as to why that button disapears when I want to use the terminal to debug my python scripts.

**Comment by connor4312** [comment]
Thanks for the feedback, good point about other languages. I'll update it for today's insiders 🙂
