### ISSUE TITLE
Add prompt to install companion extension as needed

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#349]
Removing this as an `extensionDependency` as it caused failures when running in environments that didn't have UIs, like web. Instead we should show a prompt to install the companion if we see they don't have it, or a let them know that they can't debug browsers directly from web, as appropriate,

**Comment by roblourens** [comment]
I think the companion extension should be builtin. We shouldn't have to have internet access to download a new component to enable functionality that should work out of the box. We can talk about this more if you want when you look at this again.

From Slack

> All the default extensions do already get installed on the remote, I think that as long as the type is set it will still work even if it ends up in both places.   We could optimize the download size by being smarter about which extensions are included in the remote package

**Comment by connor4312** [comment]
Added it as built-in, and added this message that's displayed in web:

![](https://memes.peet.io/img/20-03-bf350319-db6a-4c34-864b-e0c863f2709e.png)
