### ISSUE TITLE
Package.json Codelens gets confused with nested scripts attribute

### ISSUE THREAD

**Issue by SantoJambit** [microsoft/vscode-js-debug#350]
If you have a package.json which contains another "scripts" attribute, nested in another section, it will take precedence over the actual  scripts part.
```json
{
  "name": "demo",
  "version": "0.0.1",
  "files": [],
  "scripts": {
    "test": "echo test"
  },
  "sub": {
    |> Debug
    "scripts": {}
  }
}
```

**Comment by connor4312** [comment]
Thanks for the report! We're in our Feb endgame for VS Code so this will likely not get fixed until next week. If you'd like to put in a PR, however, here's a code pointer :)

https://github.com/microsoft/vscode-js-debug/blob/3185cb8f516f7217880670699e1a5ee697e93d16/src/ui/npmScriptLens.ts#L109

**Comment by SantoJambit** [comment]
Thanks for the pointer. That was easy enough :)
