### ISSUE TITLE
Debugger shows extra node in call stack

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-js-debug#352]
Testing: https://github.com/microsoft/vscode/issues/91326

I know that node has support for multiple workers now but I still think that the majority of applications has only one thread and that showing that additional node is (a) confusing and (b) wastes screen real estate.

<img width="352" alt="capture" src="https://user-images.githubusercontent.com/1931590/75341844-92885100-5895-11ea-8762-d95e732f7c6e.png">

**Comment by connor4312** [comment]
Thanks for the ping, further discussion on this issue: https://github.com/microsoft/vscode/issues/90518
