### ISSUE TITLE
Better indicate lack of variables in async call stacks

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-js-debug#353]
https://github.com/microsoft/vscode/issues/91326

When clicking through the call stack I noticed that for quite some frame no variables are shown. It is unclear to me whether this is a bug (I do think so since there are always variables in the frame) or whether the variables are not available anymore (in which case the debugger should tell me)

<img width="1216" alt="capture" src="https://user-images.githubusercontent.com/1931590/75346940-0596c500-58a0-11ea-89ca-0351d3cd1e27.png">

**Comment by connor4312** [comment]
It looks like you're in an async call stack--unfortunately Chrome only provides us variables for the current (synchronous) call stack. I will look into whether we can add any text to the variables view to indicate that state.

**Comment by connor4312** [comment]
Right now we don't have a good way to display errors/text in this case, see the linked issue. Once resolved I have a change ready to go that will show an appropriate message there.

**Comment by connor4312** [comment]
Added the error in js-debug, pending changes in vscode for it to actually be surfaced.

**Comment by rebornix** [comment]
@connor4312 what's the right js app to verify this issue? Or I can test this in any js app?

**Comment by connor4312** [comment]
Jackson verified this in https://github.com/microsoft/vscode/issues/92102#issuecomment-607508459
