### ISSUE TITLE
Strange thread name when debugging Edge app

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-js-debug#354]
https://github.com/microsoft/vscode/issues/91326

Created a react app and debuged it in VSCode. The thread name is `blank` which sounds very strange.

<img width="360" alt="capture" src="https://user-images.githubusercontent.com/1931590/75347993-4263bb80-58a2-11ea-8ad2-cf99779faa51.png">

**Comment by connor4312** [comment]
We try to display the page title there. However, initially it's blank and it looks like we don't get events when it changes--opened a Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1058108
