### ISSUE TITLE
Restarting React-App debuging in edge didn't work

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-js-debug#355]
Testing https://github.com/microsoft/vscode/issues/91326

Browser didn't finish reload.

<img width="883" alt="capture" src="https://user-images.githubusercontent.com/1931590/75348213-a9817000-58a2-11ea-9e2e-d45ffd0d7437.png">

**Comment by connor4312** [comment]
I've seen this happen a handful of times. Are you able to reproduce this consistently/do you have steps you can share? Wonder whether this is related to #271--if so it should be fixed now.

**Comment by dbaeumer** [comment]
Yes, did reproduce for me consistently. I created a react app using the steps from [here](https://reactjs.org/docs/create-a-new-react-app.html).

- start debugger
- press reload.

**Comment by connor4312** [comment]
I believe this may be a result of the previous attachment race. Closing unless we get more reports of this issue.
