### ISSUE TITLE
Restart doesn't work at all when started from the Debug Terminal

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-js-debug#363]
Refs: microsoft/vscode#91326

I started a simple node project from the debug terminal and the Restart button just has no effect.

**Comment by connor4312** [comment]
This is not solvable, unfortunately. There's no way for the debug adapter to reliably know how to restart a given process in your shell.

**Comment by eamodio** [comment]
Can we just hide the restart button in that case? Seems broken when its there, but does nothing or something unexpected.

**Comment by connor4312** [comment]
DAP has a `supportsRestartRequest` but that just determines whether the UI delegates to the debug adapter to handle the `restart()` request. Setting that to false still shows the button, but will cause it to call `terminate()` and then `launch()` a new session manually--which we also can't handle.

cc @weinand @isidorn
