### ISSUE TITLE
Restart button just ends debugging when attached

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-js-debug#364]
Refs: microsoft/vscode#91326

I started a simple node project from the terminal and attached to it, and the Restart button act the same as stop.

**Comment by eamodio** [comment]
Thinking about this more -- shouldn't the UI in this case have a attach/detach icon rather than the restart one?

**Comment by connor4312** [comment]
In this case restart will/should detach and reattach to the debug target. I agree that it's kind of confusing and might be better to just not exist--can't think of a time where I wanted to detach and reattach to a running debug target.

Related: https://github.com/microsoft/vscode-js-debug/issues/363

**Comment by connor4312** [comment]
Seems like the inconsistency here is VS Code-related, but not totally its fault (sometimes works for me, sometimes doesn't). Usually the child target/attacher will get the restart request, but sometimes the top-level parent session does. When that happens it sends a terminated event which causes the session to end.

**Comment by csafu** [comment]
Error: There is already a debug configuration "Launch Program" running.

**Comment by csafu** [comment]
My vscode cannot start debugging , retry start after the message " Error: There is already a debug configuration "Launch Program" running." is popup
