### ISSUE TITLE
JS Debug: check for deprecated Buffer() usage

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-js-debug#365]
This debug extension seems to be the reason for the following deprecation warnings printed:

`Activating extension 'ms-vscode.js-debug-nightly' failed: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead..`

(I got this running with `export NODE_OPTIONS=--throw-deprecation`)

**Comment by connor4312** [comment]
Looks to be in the `ip` library. I would put in a PR to fix it but it seems to have been abandoned the last four years 😕

**Comment by connor4312** [comment]
To verify:

 1. Close all vscode windows
 2. Set `NODE_OPTIONS=--throw-deprecation`
 3. Open a workspace from the terminal
 4. Verify you can launch js-debug (e.g. "open debug terminal") from that window
