### ISSUE TITLE
Can only debug vscode once

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#372]
- Run "Launch VS Code"
- Quit code-oss
- Run the same launch config again
- The oss window never opens
- Enable dumpio, see this error

```
[main 2020-03-03T01:31:56.736Z] Could not delete obsolete instance handle Error: ENOENT: no such file or directory, unlink '/Users/roblou/Library/Application Support/Code - Insiders/User/workspaceStorage/b90aa18a8f490560d075e46d65ce31ac/ms-vscode.js-debug-nightly/.profile/1.44.0-main.sock'
    at Object.unlinkSync (original-fs.js:976:3)
    at CodeMain.doStartup (/Users/roblou/code/vscode/out/vs/code/electron-main/main.js:176:28)
    at processTicksAndRejections (internal/process/task_queues.js:85:5) {
  errno: -2,
  syscall: 'unlink',
  code: 'ENOENT',
  path: '/Users/roblou/Library/Application Support/Code - Insiders/User/workspaceStorage/b90aa18a8f490560d075e46d65ce31ac/ms-vscode.js-debug-nightly/.profile/1.44.0-main.sock'
}
[main 2020-03-03T01:31:56.739Z] Error: ENOENT: no such file or directory, unlink '/Users/roblou/Library/Application Support/Code - Insiders/User/workspaceStorage/b90aa18a8f490560d075e46d65ce31ac/ms-vscode.js-debug-nightly/.profile/1.44.0-main.sock'
    at Object.unlinkSync (original-fs.js:976:3)
    at CodeMain.doStartup (/Users/roblou/code/vscode/out/vs/code/electron-main/main.js:176:28)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

a couple times it has started working again after I quit all vscode processes but that doesn't fix it every time. The old debug adapter still works in this state.

**Comment by connor4312** [comment]
May be something in the way we tear it down (via killtree). I was inbox tracker for an issue where someone got into this state in their normal install. I think this is worth fixing in VS Code, if we can manage to do that via killTree then users can, and have, get into that state as well.

**Comment by roblourens** [comment]
The weird thing is, with v1, it successfully launches even while js-debug cannot launch it.

**Comment by roblourens** [comment]
I'll try to investigate more to see what the difference is, since I'm pretty sure we shoudl just be spawning the same thing with the same args

**Comment by connor4312** [comment]
Is it a different user-data-dir? In the linked issue they mentioned that using a different directory fixed it.

**Comment by roblourens** [comment]
Yeah `"userDataDir": false` fixes it. I guess it's the same as those other issues, good memory. Except I never see those files created with truncated names.

**Comment by roblourens** [comment]
Actually I think it's at `/Users/roblou/Library/Application Support/Code - Insiders/User/workspaceStorage/b90aa18a8f490560d075e46`

**Comment by roblourens** [comment]
We can close this in favor of the vscode issue. But I wonder whether setting a new user-data-dir when debugging your electron app is unexpected? I think v1 doesn't add any default args when runtimeExecutable is set. But it's more like if we had an `electron` debug type then it would not add that arg.

**Comment by connor4312** [comment]
Normally electron processes are debugged by launching the main process and then attaching to the renderer process like any other browser. It's just slightly weird the way vscode launches where we use the "chrome" debug config to launch a shell script that halfway acts like a browser to set up the debug session. This isn't a scenario most people would run into.
