### ISSUE TITLE
Automatically forward debugged `url` if it's not already

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#373]
This tripped both @kieferrm and I up for a moment today. Right now when you debug remotely we'll happily forward the CDP connection and launch the browser, but the app isn't forwarded automatically, so you're presented with a nice "connection refused" page. We should automatically set up forwarding for the requested `url`, provided it's on localhost, if we see there's isn't already a tunnel for it.

**Comment by rebornix** [comment]
@connor4312 can you provide detailed steps about how to verify this issue?

**Comment by connor4312** [comment]
1. In a remote workspace, start a server running some web app
2. Either set up a Chrome launch config for it, or ctrl+click on a link to it in the debugger terminal
3. Verify that the browser opens and loads the site locally (without manually forwarding the port)
