### ISSUE TITLE
Expose dumpio option

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#375]
Debugging https://github.com/microsoft/vscode-js-debug/issues/372 would have been easier for a real user if we could get the stdout/err output without modifying the adapter code.

We could buffer the output and write it out if we fail to attach or we could add an explicit option for it.

**Comment by connor4312** [comment]
Browser stdout/err will now be logged if `trace: true`, and can be controlled granularly by setting `trace.stdio: true/false`
