### ISSUE TITLE
Attaches incompletely to vscode

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#376]
- Debug vscode
- Sometimes, we appear to be attached, but we don't bind any breakpoints or load sourcemaps or get scriptParsed events

This keeps happening while debugging the extension but I haven't looked deeply yet. I see that we didn't send the expected `.enable` requests.

[vscode-debugadapter-82.json.txt](https://github.com/microsoft/vscode-js-debug/files/4283037/vscode-debugadapter-82.json.txt)

**Comment by roblourens** [comment]
Oh I think we are attaching to the shared process because the `urlFilter` is not respected? But still not sure why we don't enable the Runtime and Debugger.

`{"tag":"cdp.receive","timestamp":1583261593144,"metadata":{"connectionId":2,"message":{"method":"Target.targetInfoChanged","params":{"targetInfo":{"targetId":"9CBDC5F83C3F43B99834AA74F56C9968","type":"page","title":"sharedProcess.html?config=%7B\"appRoot\"%3A\"%2FUsers%2Froblou%2Fcode%2Fvscode\"%2C\"machineId\"%3A\"e9fce95266c953d717196bce4bd4c1c6e7b058fe0a40ec6728c6654f9fe8ceba\"%2C\"userEnv\"%3A%7B\"VSCODE_IPC_HOOK\"%3A\"%2Fvar%2Ffolders%2Ftx%2Fp0ycbfpj37786p760wwdg6y80000gn%2FT%2Fvscode-bcb530b7-1.44.0-main.sock\"%2C\"VSCODE_NLS_CONFIG\"%3A\"%7B%5C\"locale%5C\"%3A%5C\"en-us%5C\"%2C%5C\"availableLanguages%5C\"%3A%7B%7D%2C%5C\"_languagePackSupport%5C\"%3Atrue%7D\"%2C\"VSCODE_LOGS\"%3A\"%2FUsers%2Froblou%2FLibrary%2FApplication Support%2Fcode-oss-dev%2Flogs%2F20200303T105309\"%7D%2C\"windowId\"%3A2%7D","url":"file:///Users/roblou/code/vscode/out/vs/code/electron-browser/sharedProcess/sharedProcess.html?config=%7B%22appRoot%22%3A%22%2FUsers%2Froblou%2Fcode%2Fvscode%22%2C%22machineId%22%3A%22e9fce95266c953d717196bce4bd4c1c6e7b058fe0a40ec6728c6654f9fe8ceba%22%2C%22userEnv%22%3A%7B%22VSCODE_IPC_HOOK%22%3A%22%2Fvar%2Ffolders%2Ftx%2Fp0ycbfpj37786p760wwdg6y80000gn%2FT%2Fvscode-bcb530b7-1.44.0-main.sock%22%2C%22VSCODE_NLS_CONFIG%22%3A%22%7B%5C%22locale%5C%22%3A%5C%22en-us%5C%22%2C%5C%22availableLanguages%5C%22%3A%7B%7D%2C%5C%22_languagePackSupport%5C%22%3Atrue%7D%22%2C%22VSCODE_LOGS%22%3A%22%2FUsers%2Froblou%2FLibrary%2FApplication%20Support%2Fcode-oss-dev%2Flogs%2F20200303T105309%22%7D%2C%22windowId%22%3A2%7D","attached":false,"browserContextId":"26760F2E8A3CE4F2BE71D37C695475EE"}},"sessionId":"4C2204C6A6302D7BCD7AC77A8A55087D"}},"level":0}`

**Comment by connor4312** [comment]
From the logs this looks like https://github.com/microsoft/vscode-js-debug/issues/271. Chrome tells us we're `attachedToTarget` but the child debug session is never spawned.
