### ISSUE TITLE
Node Debug - Break on SyntaxError or other errors thrown in conditional breakpoint

### ISSUE THREAD

**Issue by AnthonyWeston** [microsoft/vscode-js-debug#378]
When using the Debugger for Java, execution breaks at a conditional breakpoint if it contains a syntax error, a compilation error, or throws an exception. Using Node Debug (admittedly the slightly outdated 1.39.0 version as this is the latest version that consistently works with my project for some reason), any syntax errors or other errors thrown when evaluating a JavaScript expression fail silently, and the debugger ignores the breakpoint. It would be great if the debugger would stop at these errors as well.

**Comment by AnthonyWeston** [comment]
If not everyone would want this behavior, would making it a configurable setting be an option?

**Comment by connor4312** [comment]
I think syntax errors should alert to the user. We do this for error in logpoint messages today, it would make sense to do the same thing for code in breakpoints.

**Comment by connor4312** [comment]
This was easy enough and I like having fewer issues, so done in this milestone.
