### ISSUE TITLE
Node Debug not working via Docker Container

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode-js-debug#383]
## Desc 
When using `pwa-node` locally it works fine, however using `pwa-node` via docker it fails to bound a breakpoint.

## Steps (Docker)
- Clone https://github.com/jasonwilliams/nextjs9-typescript-server-vscode-example
- npm install
- docker-compose up
- in VSCode "launch server (Docker)" debugger
- add a breakpoint in server/index.ts (line 12 const expressApp = express())
- it should say unbound breakpoint

## Steps local
- Clone https://github.com/jasonwilliams/nextjs9-typescript-server-vscode-example
- npm install
- docker-compose up
- in VSCode "launch server" debugger
- add a breakpoint in server/index.ts (line 12 const expressApp = express())
- it will work.

## Trace
https://gist.github.com/jasonwilliams/a185ee98ce15d9773a47dd688a867dc4
The mapping seems correct.

**Comment by connor4312** [comment]
Thanks for the great repro steps and example! Fix applied, should be in tonight...

**Comment by connor4312** [comment]
Verified by submitted on the linked PR
