### ISSUE TITLE
Same breakpoint hits twice in different columns

### ISSUE THREAD

**Issue by digeff** [microsoft/vscode-js-debug#385]
I set a breakpoint on a particular column before the file is launched, and then I end up hitting the same breakpoint twice in different columns

This is very problematic for VS because we set all breakpoints in specific columns

[NodejsConsoleApp23.zip](https://github.com/microsoft/vscode-js-debug/files/4308754/NodejsConsoleApp23.zip)
[vscode-debugadapter-3.txt](https://github.com/microsoft/vscode-js-debug/files/4308759/vscode-debugadapter-3.txt)

**Comment by connor4312** [comment]
This was a result of divergence in behavior between the sourcemap predictor and the runtime sourcemap implementation.
