### ISSUE TITLE
lodash not available in Debug Console

### ISSUE THREAD

**Issue by htammen** [microsoft/vscode-js-debug#393]
Issue Type: <b>Bug</b>

I'm using the lodash library in my node.js application. When debugging I can't use it in the Debug Console.
I get the following error message:
```
srv/src/index.ts:146
_.find(['entityName', 'Subclaim Payment  Item'])(allEntities)
Uncaught ReferenceError: _ is not defined
```
When I debug the app with Chrome Debugger this works.

Extension version: 2020.3.1117
VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 4.19.76-linuxkit
Remote OS version: Linux x64 4.19.76-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Node.js 12 & TypeScript|
|OS|Linux x64 4.19.76-linuxkit|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (4 x 2492)|
|Memory (System)|1.94GB (0.25GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: xxxxx: annotation|
|OS|Linux x64 4.19.76-linuxkit|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (4 x 2492)|
|Memory (System)|1.94GB (0.25GB free)|
|VM|0%|
</details>

**Comment by connor4312** [comment]
What does your compiled code look like? This is usually either one of two issues:

1. You aren't using lodash in your current scope, so V8 doesn't include it as an optimization
2. TS renames the import of `_` to something like `lodash_1` behind the scenes (sourcemaps don't give us the ability to automatically fix that name mapping)

**Comment by htammen** [comment]
Everything is working fine inside my code. I'm using lodash there and it gets computed.
But I cannot use it in the Debug Console of the debugger

**Comment by connor4312** [comment]
Are you able to share the compiled code you were trying to debug and the line you were on so we can investigate more? 🙂 

You can also send it by email to connor@xbox.com if you're not comfortable posting it publicly.

**Comment by htammen** [comment]
Unfortunately this is not possible. It appeared in a closed customer project. 
If you are not able to reproduce the error just close the ticket.

**Comment by connor4312** [comment]
Okay. If you're able to create an standalone repro of this, that would work as well. Please reopen the issue if you can!

**Comment by pscanlon1** [comment]
this is super simple to repro

file.ts

import * as _ from 'lodash'

async function xyz() {
const a = [1,2,3,4.[1,2,3];
}

put a debugger on const a =..., and goto the vscode debug console.

try _.flatMap(a)
This has been a problem for multiple years I cant believe that this is the first time it has come up.

**Comment by connor4312** [comment]
@pscanlon1 that is the first case I mentioned:

> You aren't using lodash in your current scope, so V8 doesn't include it as an optimization

**Comment by jakedetels** [comment]
@connor4312 , I experience this issue for all imported items, even when the debugger is paused in the same scope.  Here's a 2 line example to reproduce:
```js
import _ from 'lodash';
debugger; 
```
When paused at the `debugger` line and referencing `_` from the Debug Console, I get the error `ReferenceError: _ is not defined`.  This seems to consistently happen for all imported items, regardless of whether the debugger pauses in the same scope or not.

**Comment by connor4312** [comment]
This is the most likely the second issue I mentioned:

> TS renames the import of _ to something like lodash_1 behind the scenes

**Comment by radziksh** [comment]
as @connor4312 said, for me `_` was renamed to `lodash_1` during compilation. I found it in `VSCODE` at `LOADED SCRIPTS` section:
![Screenshot_49](https://user-images.githubusercontent.com/1275228/131765174-e54ced9f-da68-40a1-9fb9-2f6cf58aed7a.png)

also I found it at: `VARIABLES` -> `closure` sub section.

**Comment by sujansaresta** [comment]
using
import * as _ from 'lodash';
instead of 
import _ from 'lodash';

fixed the problem on Debug Console as well for me.
