### ISSUE TITLE
Breakpoints are off when debugging a webpacked extension

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-js-debug#394]
Version: 1.44.0-insider
Commit: efd7548df65de8e775015b67863190e6bd4934fc

(sry for the long steps)

- git clone https://github.com/microsoft/vscode-remote-containers.git
- open the terminal and run `yarn watch` to compile & webpack the extension
- open the file `repository.ts`
- and set breakpoints at lines: 202, 207, 209
- F5 to start debugging
- from the remote command palette opened from the remote indicator in the status bar select: 'Remote Containers: Open Repository in Container'
- Enter 'microsoft/vscode-npm-scripts' as the repository name
- Create a volume for the repository use the default name
- Use default folder 
- This starts the dev container configuration process and the break point is hit
![image](https://user-images.githubusercontent.com/172399/76607453-45061800-6514-11ea-849b-698637f1b42a.png)
➡️ Notice that the breakpoints at line 207 and line 209 get mapped/validated into a breakpoint at line 211
- Single step through the code
➡️The step locations are not correct and are off by some lines. The line numbers in the call stack are also not correct this indicates some source map issues
![image](https://user-images.githubusercontent.com/172399/76608063-4be15a80-6515-11ea-9fb5-7665d81474a7.png)

**Comment by egamma** [comment]
Date: 2020-03-23T08:11:36.196Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

I did some extensive debugging today with the above version and I did not experience this problem.

**Comment by connor4312** [comment]
Thanks for the update, I was going to try to repro this morning 🙂  It may have been that there was an old sourcemap lying around that got picked up or cached.
