### ISSUE TITLE
Using the js-nightly-debug extension, I can no longer debug Microsoft Edge

### ISSUE THREAD

**Issue by zoherghadyali** [microsoft/vscode-js-debug#399]
This launch.json config:
```json
{
    "configurations": [
        {
            "type": "edge",
            "request": "launch",
            "name": "Launch Microsoft Edge",
            "url": "http://localhost:4200",
            "webRoot": "${workspaceFolder}/js"
        },
```
produces a yellow underline in the file and has this message when I hover over it:

Type of configuration.
The debug type is not recognized. Make sure that you have a corresponding debug extension installed and that it is enabled.(1)

But looking here: https://code.visualstudio.com/updates/v1_43#_new-javascript-debugger, I expected the debugger to support `"type": "edge"`

**Comment by connor4312** [comment]
Thanks for trying out the new debugger!

You still need to have the 'old' debugger types installed to use, for example for `type: chrome` you'd need to Debugger for Chrome--the extensions just look at the `usePreview` flag to redirect the launch to this debugger. However, it looks like the Edge debugger doesn't actually support the usePreview flag; I've opened an issue for them and linked it above.

To get this working in the interim, you can set your launch type to `pwa-msedge`, which will go directly to js-debug. Let us know if you run into any other issues!
