### ISSUE TITLE
Breakpoints not catching

### ISSUE THREAD

**Issue by s4m0r4m4** [microsoft/vscode-js-debug#401]
Hello, it was requested that I submit a bug report from the discussion on this ticket: https://github.com/microsoft/vscode-chrome-debug-core/issues/553#event-3143409749

Long story short, I did the following steps:
1. Verified breakpoints worked with the old debugger
2. Installed the new debugger extension and set `"debug.javascript.usePreview": true` in settings.json (note: these instructions, from [here](https://code.visualstudio.com/updates/v1_43#_new-javascript-debugger), seem a little different from the ones in the README of this github project)
3. Breakpoints no longer hit/catch

Other info:
Version: 1.43.1 (user setup)
Commit: fe22a9645b44368865c0ba92e2fb881ff1afce94
Date: 2020-03-18T07:01:20.184Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.14393

As requested, I've attached the trace log.
[vscode-debugadapter-1.zip](https://github.com/microsoft/vscode-js-debug/files/4359776/vscode-debugadapter-1.zip)

**Comment by connor4312** [comment]
Thanks for the report! In the interim I think you should be able to get this to work by clearing out your custom `sourceMapOverrides` and using the defaults.

<details><summary>Root cause</summary> 

The user has their sourceMapOverrides set at

```json
{
  "webpack:/*": "${webRoot}/*",
  "/./*": "${webRoot}/*",
  "/src/*": "${webRoot}/*",
  "/*": "*",
  "/./~/*": "${webRoot}/node_modules/*"
}
```

and sets a breakpoint in `sal-user-interface\src\app\app.component.ts`. The mapping gets mangled:

```
"SourceMap: mapping webpack:///src/app/app.component.ts => C:\\AIMDev\\Projects\\StreamlinedActiveLearning\\Web\\Applications\\sal-user-interface///src/app/app.component.ts, via sourceMapPathOverrides entry - /^webpack:\\/(.*?)$/i"
```

</details>

**Comment by s4m0r4m4** [comment]
Hi Connor, thanks for the reply. I've confirmed that if I remove the sourceMapOverrides the breakpoints will catch. Thanks for your assistance!

**Comment by rebornix** [comment]
@connor4312 what should we test here?

**Comment by connor4312** [comment]
1. Use some webpacked web app on windows (most of them should work, like create-react-app)
2. Set up a pwa-chrome launch config for it. In your sourceMapPathOverrides, have `"webpack:/*": "${webRoot}/*",`
3. Verify you can launch and hit breakpoints
