### ISSUE TITLE
continueOnAttach is not an allowed property on debug configuration

### ISSUE THREAD

**Issue by nojvek** [microsoft/vscode-js-debug#406]
![image](https://user-images.githubusercontent.com/1018196/77833141-46306b00-70f8-11ea-9ac0-b803b2767dfc.png)

It was an option recently added by @connor4312, but I believe it may have not made it to the schema.

Just an FYI, it doesn't work with `"type": "node"` attach either.

May be it hasn't made it to latest vscode version?

I am using

```
Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:34:57.037Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

**Comment by connor4312** [comment]
This is only a property of the new js-debug, and it won't be recognized by the legacy `type: "node"`. You can swap over to `"type": "pwa-node"` to get rid of the warning.

**Comment by nojvek** [comment]
@connor4312, It doesn't recognize `pwa-node` as a debug type. Is there a special extension I need to download. And what is js-debug, how is it different from chrome debug adapter or node debug adapter?

**Comment by connor4312** [comment]
js-debug is a separate extension which we're working on to replace the existing Node and Chrome debuggers. If it doesn't recognize `pwa-node`, that means it's not installed--you can [get it from the marketplace](https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug-nightly). Feel free to ping us if you run into any issues 🙂
