### ISSUE TITLE
Add ability to configure max restarts / restart delay

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#41]
Feature request on the old node debug adapter, would make sense to do.

**Comment by connor4312** [comment]
Additionally, we might have some smartness where if we see there's a command like `npm run test` or a `command` that points into a known test runner we don't automatically restart--test runners will generally exit with an errorful code on a test failure and getting into a reboot loop is not desirable.

**Comment by connor4312** [comment]
To verify, create a node file that contains `console.log('crashing...'); process.exit(1);` and debug it. Observe that there's a longer delay between restarts, and after 10 tries it stops.

**Comment by JacksonKearl** [comment]
For verification, how do we actually configure the number of resters and the restart delay? Don't see any entries in Settings.

**Comment by connor4312** [comment]
You can provide any of [these](https://github.com/microsoft/vscode-js-debug/blob/master/src/targets/node/restartPolicy.ts#L7-L10) options to the `restart` property in the launch config. For example

```
restart: { static: { delay: 5000, maxAttempts: 2 } }
```
