### ISSUE TITLE
`env` in launch.json isn't incorporated into the environment

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-js-debug#411]
This works fine with the old debugger.

**Comment by connor4312** [comment]
I'm not able to reproduce this

![](https://memes.peet.io/img/20-04-8ae77015-a112-44c8-a8cc-a1bd0c1e2ef6.png)

**Comment by eamodio** [comment]
Maybe only with `extensionHost`?

**Comment by connor4312** [comment]
That was it!

**Comment by connor4312** [comment]
To verify this, make sure to manually install the latest js-debug-nightly extension
