### ISSUE TITLE
Map paths for console.error(...)

### ISSUE THREAD

**Issue by s4m0r4m4** [microsoft/vscode-js-debug#412]
Original discussion in the 'vscode-chrome-debug-core' repo here: https://github.com/microsoft/vscode-chrome-debug-core/issues/553

Long story short, I would like to request a feature in which console.error() messages are also processed to map paths back to source files. This would be helpful for angular developers where the main typescript file that bootstraps the app is setup to catch any errors and use console.erorr() to display them in the console. Please let me know if you need more info!

**Comment by connor4312** [comment]
Good idea, should be fairly easy

**Comment by connor4312** [comment]
This might slip to June. The stacks of logged errors isn't easy to pluck out--we need to actually do some string parsing. This introduces some complexity, and at the moment the console message handling we do is very simple and imperative. I'd like to clean up and extract some of this logic rather than tacking it onto what we have today.

**Comment by s4m0r4m4** [comment]
Thanks for the update! I appreciate it.

**Comment by connor4312** [comment]
![](https://memes.peet.io/img/20-08-53696da9-7e6f-4881-8e23-7ac21e69ee8d.png)

**Comment by roblourens** [comment]
I think this isn't working for me. Just added `console.error(new Error('fail'))` to some TS.

[vscode-debugadapter-4.json.gz](https://github.com/microsoft/vscode-js-debug/files/5164004/vscode-debugadapter-4.json.gz)

**Comment by roblourens** [comment]
![image](https://user-images.githubusercontent.com/323878/92020051-6a7a1e80-ed0c-11ea-8f4f-eea1e4b3a618.png)

**Comment by connor4312** [comment]
It looks like the first line of the stack isn't in parens, so our regex doesn't match it.

It should match the 3rd line, but that looks like it's in a TS header that won't have a source map location.

**Comment by bpasero** [comment]
Unclear how to verify.

**Comment by weinand** [comment]
*.js files are mapped back to *.ts (if possible):

<img width="775" alt="2020-09-03_17-40-31" src="https://user-images.githubusercontent.com/1898161/92136756-b1e7d400-ee0c-11ea-9d6f-4f62a5fe3899.png">
