### ISSUE TITLE
Improve cwd detect in process picker

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#413]
https://github.com/microsoft/vscode/issues/94300

Seems like it's _possible_ to find process cwd's on Windows through some win32 APIs, maybe make a native addon for that as well https://stackoverflow.com/questions/20576834/windows-batch-command-to-determine-working-directory-of-a-process

**Comment by connor4312** [comment]
getting another process' cwd on Windows involves some very gnarly C to read other process' memory. I don't trust myself to write that code, nor antiviruses not to detect it as malicious. There's a Windows SDK utility `tlist.exe` which implements this functionality, but it isn't open source.

@borekb expect this in tomorrow's nightly

**Comment by connor4312** [comment]
To verify on OSX/Linux only:

 - Have a simple TS project as a subdirectory of a workspace folder.
 - Run it with `--inspect` on the command line 
 - Using `Attach to Node.js Process (preview)` command, verify that you can attach and hit breakpoints

**Comment by borekb** [comment]
@connor4312 Is it me who should verify, or is the label for one of your teammates? (I don't have a setup, currently, where I could easily try, but maybe in a few days I could.)

**Comment by connor4312** [comment]
If you had an easy setup, you could verify, otherwise someone from the VS Code team will do so 🙂

**Comment by aeschli** [comment]
Verified the steps above on Linux
