### ISSUE TITLE
Debug lens not showing up in `package.json`

### ISSUE THREAD

**Issue by borekb** [microsoft/vscode-js-debug#414]
_Opening an issue from https://github.com/zeit/next.js/pull/10807#issuecomment-608522767 as suggested by @connor4312._

The debug lens is not showing up in my `package.json` (please let me know if you also need the list of dependencies; it's relatively long so I shortened it):

```json
{
  "name": "@example/ourpackage",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "cross-env FORCE_COLOR=true next | pino-pretty -t -c -s \"level > '30'\"",
    "build": "next build",
    "start": "next start",
    "tsc": "tsc --noEmit",
    "test": "jest",
    "test:debug": "node --inspect-brk ../node_modules/jest/bin/jest --runInBand",
    "generate": "yarn generate:gql && yarn generate:schema.graphql.ts",
    "generate:gql": "gql-gen",
    "generate:schema.graphql.ts": "bash graphql-api/generate-schema-graphql-ts.sh",
    "now-build": "next build",
    "loc:init": "bash ./ttag-scripts.sh init",
    "loc:update": "bash ./ttag-scripts.sh update",
    "loc:check": "bash ./ttag-scripts.sh check"
  },
  "engines": {
    "node": "12.x"
  },
  "dependencies": {
    "@apollo/react-hooks": "4.0.0-beta.1",
    "ttag": "^1.7.22"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "webpack": "4.42.0"
  }
}
```

The file lives in a subfolder, like `<workspaceroot>/subfolder/package.json`.

---

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:34:57.037Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|-psn_0_49164|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (58)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.50
emojisense|bie|0.6.1
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
markdown-yaml-preamble|bie|0.0.4
vscode-styled-jsx|bla|1.5.0
bracket-pair-colorizer-2|Coe|0.0.29
vscode-markdownlint|Dav|0.34.0
vscode-jq-playground|dav|2.1.1
vscode-eslint|dba|2.1.2
phptools-vscode|DEV|1.0.4394
ghlink|dt|1.2.0
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.4
vscode-powertools|ego|0.58.0
LogFileHighlighter|emi|2.7.1
prettier-vscode|esb|4.0.0
vscode-open-in-application|fab|1.0.5
markdown-table-formatter|fcr|2.0.3
vscode-sql-template-literal|for|0.1.0
auto-rename-tag|for|0.1.1
psalm-vscode-plugin|get|1.1.0
vscode-pull-request-github|Git|0.15.0
todo-tree|Gru|0.0.171
vscode-nginx-conf-hint|han|0.1.0
vscode-test-explorer|hbe|2.17.0
rest-client|hum|0.23.2
RelativePath|jak|1.4.0
search-node-modules|jas|1.3.0
vscode-styled-components|jpo|0.0.29
vscode-sshfs|Kel|1.17.0
graphql-for-vscode|kum|1.15.3
git-tree-compare|let|1.9.1
terraform|mau|1.4.0
git-graph|mhu|1.22.0
dotenv|mik|1.0.1
language-gettext|mro|0.1.1
vscode-docker|ms-|1.0.0
js-debug-companion|ms-|0.0.4
js-debug-nightly|ms-|2020.3.3117
debugger-for-chrome|msj|4.12.6
vscode-project-name-in-statusbar|muj|1.0.0
vscode-phpunit|rec|2.0.72
vscode-yaml|red|0.7.2
partial-diff|ryu|1.4.1
code-settings-sync|Sha|3.4.3
vscode-scss-formatter|Sib|1.0.2
mdx|sil|0.1.0
shellcheck|tim|0.9.0
vscode-terminal-here|Tyr|0.2.4
es-quotes|vil|0.2.6
vscodeintellicode|Vis|1.2.6
vscode-apielements|vnc|0.6.7
zoombar-vscode|wra|1.2.1
local-history|xyz|1.8.1
markdown-all-in-one|yzh|2.7.0

(1 theme extensions excluded)

</details>

**Comment by connor4312** [comment]
Thanks for the issue--I'm not able to repro with what you posted here. Can you send the unabridged package.json over? Thanks!

**Comment by wpalombini** [comment]
I am having the same issue.

Version: 1.43.2 (system setup)
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by connor4312** [comment]
@wpalombini can you please share your package.json?

**Comment by wpalombini** [comment]
```
{
  "name": "rescued",
  "version": "0.1.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "9.1.0",
    "@angular/cdk": "9.2.0",
    "@angular/common": "9.1.0",
    "@angular/compiler": "9.1.0",
    "@angular/core": "9.1.0",
    "@angular/forms": "9.1.0",
    "@angular/material": "9.2.0",
    "@angular/platform-browser": "9.1.0",
    "@angular/platform-browser-dynamic": "9.1.0",
    "@angular/router": "9.1.0",
    "rxjs": "6.5.5",
    "tslib": "1.11.1",
    "zone.js": "0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.901.0",
    "@angular/cli": "9.1.0",
    "@angular/compiler-cli": "9.1.0",
    "@angular/language-service": "9.1.0",
    "@types/node": "13.11.0",
    "@types/jasmine": "3.5.10",
    "@types/jasminewd2": "2.0.8",
    "codelyzer": "5.2.2",
    "jasmine-core": "3.5.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "4.4.1",
    "karma-chrome-launcher": "3.1.0",
    "karma-coverage-istanbul-reporter": "2.1.1",
    "karma-jasmine": "3.1.1",
    "karma-jasmine-html-reporter": "1.5.3",
    "protractor": "6.0.0",
    "ts-node": "8.8.2",
    "tslint": "6.1.1",
    "typescript": "3.8.3"
  }
}
```

**Comment by borekb** [comment]
Here's my `package.json`:

<details><summary>Click to expand</summary>

```json
{
  "name": "@example/ourpackage",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "cross-env FORCE_COLOR=true next | pino-pretty -t -c -s \"level > '30'\"",
    "build": "next build",
    "start": "next start",
    "tsc": "tsc --noEmit",
    "test": "jest",
    "test:debug": "node --inspect-brk ../node_modules/jest/bin/jest --runInBand",
    "generate": "yarn generate:gql && yarn generate:schema.graphql.ts",
    "generate:gql": "gql-gen",
    "generate:schema.graphql.ts": "bash graphql-api/generate-schema-graphql-ts.sh",
    "now-build": "next build",
    "loc:init": "bash ./ttag-scripts.sh init",
    "loc:update": "bash ./ttag-scripts.sh update",
    "loc:check": "bash ./ttag-scripts.sh check"
  },
  "engines": {
    "node": "12.x"
  },
  "dependencies": {
    "@apollo/react-hooks": "4.0.0-beta.1",
    "@apollo/react-ssr": "4.0.0-beta.1",
    "@reach/tabs": "0.1.6",
    "@example/library": "*",
    "apollo-cache-inmemory": "^1.6.5",
    "apollo-client": "^2.6.8",
    "apollo-datasource-rest": "^0.8.0",
    "apollo-link": "^1.2.13",
    "apollo-link-http": "^1.5.16",
    "apollo-server-caching": "^0.5.1",
    "apollo-server-core": "^2.11.0",
    "apollo-server-micro": "^2.11.0",
    "apollo-utilities": "^1.3.3",
    "chalk": "^3.0.0",
    "classnames": "^2.2.6",
    "cookie": "^0.4.0",
    "dataloader": "^2.0.0",
    "dotenv": "^8.2.0",
    "formstate": "1.3.0",
    "graphql": "^14.6.0",
    "graphql-tag": "^2.10.3",
    "ioredis": "^4.16.0",
    "isomorphic-unfetch": "^3.0.0",
    "jsonwebtoken": "^8.5.1",
    "lodash": "^4.17.15",
    "lodash.snakecase": "^4.1.1",
    "mobx": "^5.15.4",
    "mobx-react": "6.1.8",
    "nanoid": "^2.1.11",
    "next": "^9.3.4",
    "next-compose-plugins": "^2.2.0",
    "next-transpile-modules": "^3.0.2",
    "nextjs-redirect": "^1.1.2",
    "nock": "^12.0.2",
    "node-mocks-http": "^1.8.1",
    "nprogress": "0.2.0",
    "pino": "^5.17.0",
    "react": "^16.13.1",
    "react-compound-slider": "2.2.0",
    "react-dom": "^16.13.1",
    "react-swipeable": "5.4.0",
    "striptags": "^3.1.1",
    "ttag": "^1.7.22"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@babel/plugin-proposal-decorators": "^7.8.3",
    "@babel/preset-env": "^7.8.6",
    "@graphql-codegen/add": "^1.12.2",
    "@graphql-codegen/cli": "^1.12.2",
    "@graphql-codegen/fragment-matcher": "^1.12.2",
    "@graphql-codegen/typescript": "^1.12.2",
    "@graphql-codegen/typescript-operations": "^1.12.2",
    "@graphql-codegen/typescript-resolvers": "^1.12.2",
    "@svgr/webpack": "5.2.0",
    "@types/classnames": "^2.2.9",
    "@types/cookie": "^0.3.3",
    "@types/graphql": "^14.5.0",
    "@types/ioredis": "^4.14.8",
    "@types/jest": "^25.1.3",
    "@types/jsonwebtoken": "^8.3.8",
    "@types/lodash": "^4.14.149",
    "@types/lodash.snakecase": "^4.1.6",
    "@types/nanoid": "^2.1.0",
    "@types/nprogress": "^0.2.0",
    "@types/pino": "^5.15.5",
    "@types/reach__tabs": "^0.1.0",
    "@types/react": "^16.9.25",
    "@types/react-dom": "^16.9.5",
    "@types/react-test-renderer": "^16.9.2",
    "@types/react-tooltip": "^3.11.0",
    "babel-jest": "^25.1.0",
    "babel-plugin-ttag": "^1.7.24",
    "cross-env": "^7.0.2",
    "jest": "^25.1.0",
    "pino-pretty": "^3.6.1",
    "prettier": "^1.19.1",
    "prop-types": "15.7.2",
    "quicktype": "^15.0.214",
    "react-test-renderer": "^16.9.0",
    "ts-node": "^8.6.2",
    "ttag-cli": "^1.7.28",
    "typescript": "^3.8.3",
    "webpack": "4.42.0"
  }
}
```

</details>

**Comment by connor4312** [comment]
Thanks, this only happened on stable so I didn't run into it personally. Fixed in today's nightly.
