### ISSUE TITLE
Source map issue in Node attach scenario

### ISSUE THREAD

**Issue by RedMickey** [microsoft/vscode-js-debug#424]
Hi guys, this is [React Native Tools](https://github.com/microsoft/vscode-react-native) team. While adapting [React Native Hermes](https://github.com/facebook/hermes) debugging to `js-debug` we decided to try Node debugger for it because for now Hermes doesn't work with flat session API. During investigation we faced a few issues with unexpected source map paths resolving in `Node attach` scenario.

## `<node_internals>/` issue

A Hermes app provides the code bundle and the source map for it via HTTP links, for example: 
```
http://localhost:8081/index.map?platform=android&dev=true&minify=false
```
So, as we found out, `js-debug` considers it as not absolute path and prepends with ["<node_internals>/"](https://github.com/microsoft/vscode-js-debug/blob/master/src/targets/node/nodeSourcePathResolver.ts#L32-L34), and we get such a link:
```
<node_internals>/http://localhost:8081/index.bundle?platform=android&dev=true&minify=false
```
It looks quite strange, but `js-debug` continues to work and successfully downloads source map content. See an example of downloaded `index.map` file in **Attachments**.
Then js-debug [creates](https://github.com/microsoft/vscode-js-debug/blob/master/src/common/sourceMaps/sourceMapFactory.ts#L77-L81) `SourceMap` object. This is how it looks:
![image](https://user-images.githubusercontent.com/33267199/78759734-bfe21780-7988-11ea-86b3-61183908803a.png)
And `sources` property:
![image](https://user-images.githubusercontent.com/33267199/78759805-e1db9a00-7988-11ea-8fe5-39ef6a3ec290.png)

## `file:///` issue

Previously, in `vscode-chrome-debug-core` it was [transformed](https://github.com/microsoft/vscode-chrome-debug-core/blob/master/src/sourceMaps/sourceMap.ts#L126-L132) the following way and it worked for us:
![image](https://user-images.githubusercontent.com/33267199/78760270-92e23480-7989-11ea-82db-f7d8bf1d795c.png)

Then [here](https://github.com/microsoft/vscode-js-debug/blob/master/src/adapter/sources.ts#L798-L801) the extension starts to compute absolute paths and the first `url` value is `__prelude__` (according to `index.map`). Further this `url` is processed [here](https://github.com/microsoft/vscode-js-debug/blob/master/src/targets/node/nodeSourcePathResolver.ts#L63-L74) and the extension throws an error: 
```
TypeError [ERR_INVALID_URL]: Invalid URL: <node_internals>/http://localhost:8081/index.bundle?platform=android&dev=true&minify=false
``` 
But after this error the extension successfully handles other paths which are the absolute ones.
## Debugger.getPossibleBreakpoints issue
We tried to set a breakpoint and got the error:
```
TypeError: r.locations is not iterable
	at g:\work\vscode-js-debug\vscode-js-debug\out\src\adapter\breakpoints.js:166:42
	at async Promise.all (index 0)
	at async BreakpointManager.getBreakpointLocations (g:\work\vscode-js-debug\vscode-js-debug\out\src\adapter\breakpoints.js:180:17)
	at async g:\work\vscode-js-debug\vscode-js-debug\out\src\adapter\debugAdapter.js:69:26
	at async Connection._onMessage (g:\work\vscode-js-debug\vscode-js-debug\out\src\dap\connection.js:138:36)
```
The error is thrown [here](https://github.com/microsoft/vscode-js-debug/blob/master/src/adapter/breakpoints.ts#L240). This means that an application returns empty locations. However, as seen from CDP proxy logs (see in **Attachments**), an app returns some locations.

One thing we noticed when we were comparing `js-debug` and `vscode-chrome-debug-core` is that `js-debug` sends the following request:
```
{
  "id": 15,
  "method": "Debugger.setBreakpointByUrl",
  "params": {
    "urlRegex": "[fF][iI][lL][eE]:\\/\\/\\/[gG]:\\/[wW][oO][rR][kK]\\/[tT][eE][sS][tT]_[rR][eE][aA][cC][tT]_[nN][aA][tT][iI][vV][eE]\\/[aA][wW][eE][sS][oO][mM][eE][pP][rR][oO][jJ][eE][cC][tT]062[hH]\\/[aA][pP][pP][tT][eE][sS][tT][bB][uU][tT][tT][oO][nN]\\.[jJ][sS]|[gG]:\\\\[wW][oO][rR][kK]\\\\[tT][eE][sS][tT]_[rR][eE][aA][cC][tT]_[nN][aA][tT][iI][vV][eE]\\\\[aA][wW][eE][sS][oO][mM][eE][pP][rR][oO][jJ][eE][cC][tT]062[hH]\\\\[aA][pP][pP][tT][eE][sS][tT][bB][uU][tT][tT][oO][nN]\\.[jJ][sS]",
    "lineNumber": 9,
    "columnNumber": 0
  }
}
```
and `vscode-chrome-debug-core` this one:
```
{
  "id": 15,
  "method": "Debugger.setBreakpointByUrl",
  "params": {
    "urlRegex": "http:\/\/localhost:8081\/index\.bundle\?platform=android&dev=true&minify=false",
    "lineNumber": 105685,
    "columnNumber": 0
  }
}
```

So, we have several questions:
- Is that expected that `<node_internals>/` concatenates with HTTP url for source map paths?
- Is this correct that `file:///` isn't prepended to paths in `SourceMap.sources`?
- Does the extension handle `locations` in CDP queries correctly in our case?

### Attachments
- [`js-debug` extension's debug session verbose logs](https://github.com/microsoft/vscode-js-debug/files/4450836/vscode-debugadapter-0.zip)
- [CDP proxy logs](https://github.com/microsoft/vscode-js-debug/files/4450837/log8.txt)
- [index.map file](https://github.com/microsoft/vscode-js-debug/files/4450838/indexMap.txt)

**Comment by connor4312** [comment]
> Is that expected that <node_internals>/ concatenates with HTTP url for source map paths?

This behavior is a result of us assuming all non-absolute paths we see in Node targets are from internals (since we'll get sources like `url: "cluster"` for `require("cluster")`). But doing that for URLs is a 🐛; I haven't tried debugging local Node files that have remote sourcemaps and never noticed that. I'll fix that today and add a test for it.

> Is this correct that `file:///` isn't prepended to paths in SourceMap.sources?

Yes. In chrome-debug-core, we processed the sourcemap when received it to disk paths, while, js-debug preserves the original paths in the sourcemap and does the path mapping later.

Generally the philosophy in the previous debuggers was that a source has example one sourcemap, and a source is present in at most one sourcemap. However, this assumption isn't always true (and in complex web apps that use code splitting, is usually false) so in js-debug we tend to preserve the original data and do path mapping gradually as it's required/

> Does the extension handle locations in CDP queries correctly in our case?

In the [cdp spec](https://chromedevtools.github.io/devtools-protocol/tot/Debugger/#method-getPossibleBreakpoints) locations is not listed as optional. I may not be reading the logs correctly but it looks like we're getting an empty object back from Hermes. For instance the last pair of requests/responses in that log is:

```
debugger -> target rep -> {
  "id": 19,
  "method": "Debugger.getPossibleBreakpoints",
  "params": {
    "restrictToFunction": false,
    "start": {
      "scriptId": "2",
      "lineNumber": 105685,
      "columnNumber": 0
    },
    "end": {
      "scriptId": "2",
      "lineNumber": 105686,
      "columnNumber": 0
    }
  }
}
target -> debugger rep -> {
  "result": {}, // <- this should probably be `{ locations: [] }`?
  "id": 19
}
```

--

Also, if you have a repo or test setup you're working on, feel free to share that with me. I'm happy to help debug more directly in your code, and being able to confirm that fixes work myself reduces back and forth :)

**Comment by connor4312** [comment]
The `node_internals` bug is fixed in the linked commit. By default we'll assume that the pathname is relative to the current working directory, but this can be configured via the `sourceMapPathOverrides`, for example in our tests we add:

```
sourceMapPathOverrides: { 'http://localhost:8001/*': `${testWorkspace}/web/*` },
```

**Comment by RedMickey** [comment]
Hi @connor, thanks for your response.
We tested your bugfix and now the extension doesn't throw an error caused by `<node_internals>/` prefix. The extension fetches such file name as `index.bundle` from the link `http://localhost:8081/index.bundle?platform=android&dev=true&minify=false`, but unfortunately we couldn't find this file in project directory and its subfolders. We debug an application remotely, and it seems that `index.bundle` file is located on the application side. 
For example we get such sourcemap path:
![Аннотация 2020-04-10 111538](https://user-images.githubusercontent.com/33267199/78991687-30806400-7b42-11ea-9209-17403d654bff.png)

But, despite this problem extension continues to work well.

We also investigated deeper how `vscode-chrome-debug-core` handles breakpoints in case of Hermes app debugging and found out the following:
As seen from [chrome-debug-core's code](https://github.com/microsoft/vscode-chrome-debug-core/blob/master/src/chrome/breakpoints.ts#L191-L268), the tool tries to get breakpoints locations using `Debugger.setBreakpointByUrl` method if `Debugger.getPossibleBreakpoints` doesn't work. A Hermes app can return locations on `Debugger.setBreakpointByUrl` method call.
Request:
```
{
  "id": 15,
  "method": "Debugger.setBreakpointByUrl",
  "params": {
    "urlRegex": "[fF][iI][lL][eE]:\\/\\/\\/[gG]:\\/[wW][oO][rR][kK]\\/[tT][eE][sS][tT]_[rR][eE][aA][cC][tT]_[nN][aA][tT][iI][vV][eE]\\/[aA][wW][eE][sS][oO][mM][eE][pP][rR][oO][jJ][eE][cC][tT]0622[hH]_2\\/[aA][pP][pP][tT][eE][sS][tT][bB][uU][tT][tT][oO][nN]\\.[jJ][sS]|[gG]:\\\\[wW][oO][rR][kK]\\\\[tT][eE][sS][tT]_[rR][eE][aA][cC][tT]_[nN][aA][tT][iI][vV][eE]\\\\[aA][wW][eE][sS][oO][mM][eE][pP][rR][oO][jJ][eE][cC][tT]0622[hH]_2\\\\[aA][pP][pP][tT][eE][sS][tT][bB][uU][tT][tT][oO][nN]\\.[jJ][sS]",
    "lineNumber": 9,
    "columnNumber": 0
  }
}
```
Response:
```
{
  "result": {
    "locations": [
      {
        "columnNumber": 14,
        "lineNumber": 9,
        "scriptId": "2"
      }
    ],
    "breakpointId": "3"
  },
  "id": 15
}
```

I saw that [here](https://github.com/microsoft/vscode-js-debug/blob/master/src/adapter/breakpoints/breakpointBase.ts#L446-L459) `js-debug` calls `Debugger.setBreakpointByUrl` method.  But the error occurs [here](https://github.com/microsoft/vscode-js-debug/blob/master/src/adapter/breakpoints.ts#L222-L240). So, it seems that the extension can't get locations using `Debugger.setBreakpointByUrl` method.

We'd like to know if there is a way to make `js-debug` get locations from `Debugger.setBreakpointByUrl` method's response as `chrome-debug-core` does?
<br/>
You can try to debug a React Native Hermes app after the following preparations:
- Prepare the development environment and create React Native project according to [Setting up the development environment guide](https://reactnative.dev/docs/environment-setup)
- Enable Hermes engine for Android, use this [guide](https://reactnative.dev/docs/hermes)
- Launch a Hermes app using the command `npx react-native run-android` from the project root
- In VS Code add pwa-node attach scenario
    ```
    {
        "type": "pwa-node",
        "request": "attach",
        "trace": true,
        "name": "[Node] Attach to program",
        "port": 8081 // packager port
    }
    ```
- Start debugging and try to add a breakpoint

**Comment by connor4312** [comment]
> But, despite this problem extension continues to work well.

The behavior you described is expected. The `NodeSourcePathResolver` does not validate that the paths it returns exists or are correct, it 'postulates' as to where the source can be located. Determining whether the file exists at the path is done during the [content hash verification](https://github.com/microsoft/vscode-js-debug/blob/520b9c2423657ac96d29edefc4e563c61b214176/src/adapter/sources.ts#L143-L148) step.

**Comment by connor4312** [comment]
- > But, despite this problem extension continues to work well.

    The behavior you described is expected. The `NodeSourcePathResolver` does not validate that the paths it returns exists or are correct, it 'postulates' as to where the source can be located. Determining whether the file exists at the path is done during the [content hash verification](https://github.com/microsoft/vscode-js-debug/blob/520b9c2423657ac96d29edefc4e563c61b214176/src/adapter/sources.ts#L143-L148) step. I figured returning URLs as `${cwd}/${pathname}` is a decent default if there's no manually-applied sourceMapOverride, but I'm happy to change that if there's a better default or if that feels inappropriate.

- > We'd like to know if there is a way to make js-debug get locations from Debugger.setBreakpointByUrl method's response as chrome-debug-core does?

    I'm still not totally clear on what problem you're running into. The code that calls `getPossibleBreakpoints` in js-debug is only used to reply to a DAP `breakpointLocations` request. A failure there will cause additional possible breakpoint locations within a line to not appear in VS Code, but it is not involved in the process of setting breakpoints.

- > You can try to debug a React Native Hermes app after the following preparations

    With those instructions, it seems like we can't find a debug target on that port. `http://localhost:8081/json/version` / `http://localhost:8081/json/list` don't have any debugger URLs. Is a step missing?

**Comment by RedMickey** [comment]
Thanks @connor4312, now I see the purpose of [`getBreakpointLocations`](https://github.com/microsoft/vscode-js-debug/blob/master/src/adapter/breakpoints.ts#L164) function. 
So, we've investigated [`_setAny`](https://github.com/microsoft/vscode-js-debug/blob/master/src/adapter/breakpoints/breakpointBase.ts#L446) function deeper and it seems that it could work incorrectly:
`js-debug` tries to get breakpoints data using `setBreakpoint` and `setBreakpointByUrl` methods. For example, we set a breakpoint in `AppTestButton.js` file on line 11. In `_setAny` function we get the following `urlRegex`:
```
[fF][iI][lL][eE]:\/\/\/[gG]:\/[wW][oO][rR][kK]\/[tT][eE][sS][tT]_[rR][eE][aA][cC][tT]_[nN][aA][tT][iI][vV][eE]\/[aA][wW][eE][sS][oO][mM][eE][pP][rR][oO][jJ][eE][cC][tT]0622[hH]_2\/[aA][pP][pP][tT][eE][sS][tT][bB][uU][tT][tT][oO][nN]\.[jJ][sS]|[gG]:\\[wW][oO][rR][kK]\\[tT][eE][sS][tT]_[rR][eE][aA][cC][tT]_[nN][aA][tT][iI][vV][eE]\\[aA][wW][eE][sS][oO][mM][eE][pP][rR][oO][jJ][eE][cC][tT]0622[hH]_2\\[aA][pP][pP][tT][eE][sS][tT][bB][uU][tT][tT][oO][nN]\.[jJ][sS]
```
This is the same as:
```
file:///G:/work/test_react_native/AwesomeProject0622H_2/AppTestButton.js
```
So we get such a request:
```
{
  "id": 22,
  "method": "Debugger.setBreakpointByUrl",
  "params": {
    "urlRegex": "[fF][iI][lL][eE]:\\/\\/\\/[gG]:\\/[wW][oO][rR][kK]\\/[tT][eE][sS][tT]_[rR][eE][aA][cC][tT]_[nN][aA][tT][iI][vV][eE]\\/[aA][wW][eE][sS][oO][mM][eE][pP][rR][oO][jJ][eE][cC][tT]0622[hH]_2\\/[aA][pP][pP][tT][eE][sS][tT][bB][uU][tT][tT][oO][nN]\\.[jJ][sS]|[gG]:\\\\[wW][oO][rR][kK]\\\\[tT][eE][sS][tT]_[rR][eE][aA][cC][tT]_[nN][aA][tT][iI][vV][eE]\\\\[aA][wW][eE][sS][oO][mM][eE][pP][rR][oO][jJ][eE][cC][tT]0622[hH]_2\\\\[aA][pP][pP][tT][eE][sS][tT][bB][uU][tT][tT][oO][nN]\\.[jJ][sS]",
    "lineNumber": 10,
    "columnNumber": 0
  }
}
```

When we was trying to debug `_setAny` function, we faced the problem that sometimes we cannot reach breakpoint at this [block of code](https://github.com/microsoft/vscode-js-debug/blob/master/src/adapter/breakpoints/breakpointBase.ts#L457-L480). Only after several rebuilding of the extension (there were not build errors) and some changes we could debug this part of the code. We found out that sometimes `setBreakpointByUrl` can freeze or responce can be empty. But at the most cases a Hermes app returns something like this:
```
{
  "result": {
    "locations": [
      {
        "columnNumber": 13,
        "lineNumber": 10,
        "scriptId": "2"
      }
    ],
    "breakpointId": "5"
  },
  "id": 22
}
```
So we have breakpoints locations.
Further, we revealed the following sequence of calls:
1. [updateUiLocations](https://github.com/microsoft/vscode-js-debug/blob/master/src/adapter/breakpoints/breakpointBase.ts#L176)
2. [rawLocationToUiLocation](https://github.com/microsoft/vscode-js-debug/blob/master/src/adapter/threads.ts#L705)
    So we get the following uilocations:   
    ![image](https://user-images.githubusercontent.com/33267199/79125230-7dfd0b00-7da6-11ea-9d22-86570b5cf456.png)
    And the following [source object](https://github.com/microsoft/vscode-js-debug/blob/master/src/adapter/breakpoints/breakpointBase.ts#L191):
    ![image](https://user-images.githubusercontent.com/33267199/79125518-02e82480-7da7-11ea-8e88-7d6def5a8f30.png)

    As seen, source in uilocations differs from source object.
3. [currentSiblingUiLocations](https://github.com/microsoft/vscode-js-debug/blob/master/src/adapter/sources.ts#L550)
    Due to the difference between `source objects` here we get an ampty array of matched locations:
![image](https://user-images.githubusercontent.com/33267199/79126558-dd5c1a80-7da8-11ea-8f49-fe37acc488ff.png)
![image](https://user-images.githubusercontent.com/33267199/79126630-fe247000-7da8-11ea-8d3e-1fc4589659e1.png)
![image](https://user-images.githubusercontent.com/33267199/79126718-26ac6a00-7da9-11ea-9111-3a085450fdcd.png)

Thus, it seems that a breakpoint wasn't handled correctly.

`vscode-chrome-debug-core` sends the following request:
```
{
  "id": 15,
  "method": "Debugger.setBreakpointByUrl",
  "params": {
    "urlRegex": "http:\/\/localhost:8081\/index\.bundle\?platform=android&dev=true&minify=false",
    "lineNumber": 105685,
    "columnNumber": 0
  }
}
```

As I understand it tries to get breakpoint location from remote `index.bundle` and a Hermes app returns location within the `bundle`. So breakpoints are handled correctly.

We think that it can be that the extension sends incorrect request (urlRegex) to a Hermes application. It tries to match locations with local files, but they should be matched with remote `index.bundle`. This is our assumptions about incorrect sourcemaps handling.

> With those instructions, it seems like we can't find a debug target on that port. http://localhost:8081/json/version / http://localhost:8081/json/list don't have any debugger URLs. Is a step missing?

It seems that Hermes engine isn't activated. Have you done all the steps from this [guide](https://reactnative.dev/docs/hermes)?
If  Hermes engine is enabled, an application should look something like this:
![image](https://user-images.githubusercontent.com/33267199/79128754-b869a680-7dac-11ea-84fd-4cb052884522.png)

I created a [demo project](https://github.com/RedMickey/rn_demo_button). You can set a breakpoint in [the click handler](https://github.com/RedMickey/rn_demo_button/blob/master/AppTestButton.js#L10-L11) of `AppTestButton` to check how the extension processes breakpoints.

**Comment by connor4312** [comment]
Thanks for the demo app, I'm able to run it locally.

For all breakpoints, we try to set them by their disk path--just in case. If we're wrong, no big deal. The interesting message here is actually the set via script ID:

```json
{
  "id": 16,
  "method": "Debugger.setBreakpoint",
  "params": {
    "location": {
      "scriptId": "2",
      "lineNumber": 105706,
      "columnNumber": 0
    }
  }
}
```

For me, this looks like the right location. That's the script ID of the bundle file and the right line:

![](https://memes.peet.io/img/20-04-ab92da30-ccbd-41f4-baa4-bf2eaac428eb.png)

However, it looks like maybe Hermes does not support setting breakpoints via script ID, or maybe there's a bug? This is the response:

```json
{
  "result": {
    "actualLocation": {
      "lineNumber": 0,
      "scriptId": ""
    },
    "breakpointId": "8"
  },
  "id": 16
}
```

If that request works, I believe the breakpoint should be set.

**Comment by connor4312** [comment]
Going to close this out since it seems like there's no further action for js-debug. Thanks for opening the issue & all your help with debugging it 🙂
