### ISSUE TITLE
Large string output is missing from debug console?

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-js-debug#426]
I'm printing a large JSON stringified blob to console, in the old adapter and the non-preview adapter it works fine, in the preview adapter I get:

```
Note: Using the "preview" debug extension
/Users/jkearl/.nvm/versions/node/v10.18.1/bin/node /Users/jkearl/Developer/tmp/langdetect/detect.js
Debugger listening on ws://127.0.0.1:64291/f05c45b0-46c4-4e48-bf5f-f527458f7988
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
…
Waiting for the debugger to disconnect...
Process exited with code null
```

**Comment by connor4312** [comment]
Fixed. Right now we truncate the string to the first and last 10,000 characters. The Chrome devtools expose "Copy" / "Show All" buttons, but I don't think we can display those in the debug console at the moment. Following up with Isi and will open an issue to track.

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode/issues/94937
