### ISSUE TITLE
Make terminal link handling independently togglable

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#427]
Togglable for debug terminals, not just on/off. Just changing the filtering logic here

https://github.com/microsoft/vscode-js-debug/blob/5ccae881699e86c6da5529a5b28c64d93375b1d9/src/ui/terminalLinkHandler.ts#L35-L37

**Comment by connor4312** [comment]
js-debug has functionality that allows debugging links by ctrl+clicking on them from the terminal. With the setting `debug.javascript.debugByLinkOptions`:

 - *on* (default behavior) should only debug links clicked through the debug terminal ("Create JavaScript Debug Terminal" command)
 - *always* should debug links clicked in all terminals
 - *off* should never debug links

**Comment by JacksonKearl** [comment]
This isn't being properly rendered in the settings editor... when I click to edit it in json it inserts `null`. Do you maybe have it as a nullable enum? Settings editor doesn't know how to render those, and I think just a normal enum (defualted to whatever `null` does now) would work.
![image](https://user-images.githubusercontent.com/8586769/80636966-19cb7f80-8a13-11ea-9844-1f7baba74024.png)

**Comment by JacksonKearl** [comment]
Is this related? When I set debug by link to "always" and I clicked a link I got this scary pop up.
![image](https://user-images.githubusercontent.com/8586769/80637162-60b97500-8a13-11ea-94fc-7ed255c2e6a1.png)

**Comment by JacksonKearl** [comment]
Functionality seems to work in that the strange behaviour of the links opening in chrome is enabled in Debug terminal iff debugByLinkOptions!=='off' and enable din normal terminals iff debugByLinkOptions==='always'. But from the description its not clear to me why exactly its doing this or how I should be using these links. i.e. what does it mean to "debug a link" ?

**Comment by connor4312** [comment]
> This isn't being properly rendered in the settings editor... when I click to edit it in json it inserts null. Do you maybe have it as a nullable enum? Settings editor doesn't know how to render those, and I think just a normal enum (defualted to whatever null does now) would work.

Currently it can be the string state, or options to apply default launch configuration to links (e.g. if the user wants to set custom sourcemap handling). Could make those two different settings.

> I hit "don't allow" and clicking links now opens chrome (not my default browser) to the link, whereas with this setting disabled it opened the file in code.

When it launches Chrome, it should do so in debug mode. We only support Chrome and Edge for debugging; we'll open Edge if we see that's your default browser, otherwise we'll open and debug Chrome. For instance if you run a `webpack-dev-server` and ctrl+click the `http://localhost:1234` link, then localhost:1234 will be debugged as if you had a Chrome launch config for it. File links won't be handled.

From googling online, it seems that prompt can be triggered by running AppleScript--which I think is utilized when we try to determine your default browser on OSX.

If handling the link takes more than 3 seconds -- which that dialog will block -- VS Code will open the link in your default browser. Though you mentioned it opens the file in code -- we shouldn't be trying to debug files.

**Comment by JacksonKearl** [comment]
> we'll open Edge if we see that's your default browser, otherwise we'll open and debug Chrome.

My default browser is Edge and Chrome was still opened.. but that may be because I denied the permissions. I wonder if there's any way to get that back?

> File links won't be handled.

I'm seeing file links being opened in Chrome when I set `debugByLinkOptions: 'always'`? Is that expected?

**Comment by connor4312** [comment]
Huh, interesting. That's a bug. I have logic for prefixing but when testing it out I never had a file linkified. I'll remove the auto-prefixing and not debug URLs that aren't explicitly http(s).

https://github.com/microsoft/vscode-js-debug/blob/ea8cc4b8a521e9881a1a383080dee70011118293/src/ui/terminalLinkHandler.ts#L67-L80

This can be verified in tomorrow's insiders.
