### ISSUE TITLE
Slow starting/refreshing of debug session in Chrome

### ISSUE THREAD

**Issue by mikij** [microsoft/vscode-js-debug#431]
When I am using debug.chrome.useV3: true then debug session took several minutes to just start Angular based application. Any update of code means reload of application which means another wait session. So I am forced to not use V3 for debugging even to try it. I noticed that break points also is not bound so for now this new debugger seems completely usefulness for browser debugging. If you have any suggestions I could try. Official version of debugger works normally for me.

**Comment by connor4312** [comment]
Please add `trace: true` to your launch config and share the logs here. Thanks!

**Comment by mikij** [comment]
I will try because I am working in Amazon Workspaces environment that I don't have possibility to take out anything. But I think they will let me send those logs here.

**Comment by mikij** [comment]
You want logs from moment I start debug session until login screen shows up, right?

**Comment by mikij** [comment]
Well this is what I got in Debug Console output

![image](https://user-images.githubusercontent.com/4502100/79552891-f52ee980-809b-11ea-94c2-524c574c0e8d.png)

Also there is a json file in /tmp folder that is about 648 MB big. Is that log file you need?

**Comment by connor4312** [comment]
Yep. That's pretty large, you can compress it before you send it--it should compact down fairly well.

**Comment by mikij** [comment]
Okay I asked for approval. Once it would approved or disapproved I will let you know.

**Comment by FishOrBear** [comment]
[vscode-debugadapter-0.zip](https://github.com/microsoft/vscode-js-debug/files/4501039/vscode-debugadapter-0.zip)
I have the same problem, check out my

**Comment by connor4312** [comment]
Thanks for the log. I think I know what's happening here. @FishOrBear can you set/add `devtool: "source-map"` to your webpack configuration and let me know if that fixes it for you?

**Comment by FishOrBear** [comment]
debug console
```
Note: Using the "preview" debug extension
Verbose logs are written to:
C:\Users\admin\AppData\Local\Temp\vscode-debugadapter-1.json
[18184:18140:0421/084532.990:ERROR:browser_switcher_service.cc(238)] XXX Init()
[18184:18140:0421/084538.564:ERROR:device_event_log_impl.cc(162)] [08:45:38.563] Bluetooth: bluetooth_adapter_winrt.cc:1055 Getting Default Adapter failed.
[HMR] Waiting for update signal from WDS...
```

[vscode-debugadapter-1 t.zip](https://github.com/microsoft/vscode-js-debug/files/4507017/vscode-debugadapter-1.t.zip)

**Comment by mikij** [comment]
> Thanks for the log. I think I know what's happening here. @FishOrBear can you set/add `devtool: "source-map"` to your webpack configuration and let me know if that fixes it for you?

Isn't that set by Angular for webpack automatically if we just set sourceMap to true in angular.json?

**Comment by FishOrBear** [comment]
My project is not Angular.
Is Webpack + Typescript + React.

The original first log used devtool: "eval-source-map"
The following logs use "source-map"

**Comment by connor4312** [comment]
Thanks for the report. I've submitted a PR with a fix that seems to work well in my testing. Here's a build of the extension with the fix if you'd like to take it for a spin before it gets merged

https://memes.peet.io/img/js-debug-eval-module-fix.vsix

You can install it using `Install from VSIX` command in vs code

**Comment by FishOrBear** [comment]
Looks good, i have used it

**Comment by FishOrBear** [comment]
@connor4312 
![bug](https://user-images.githubusercontent.com/19372111/81146086-2ec38800-8faa-11ea-9eda-e3f66f02a070.gif)

HMR will have problems

**Comment by mikij** [comment]
For my case this is even worse. Now my app won't start at all or at least it needs much more time to start than before. Actually when I turned on Chrome's dev tools I saw it is still loading but process is too much slower now. Sorry for brought up bad news.

**Comment by FishOrBear** [comment]
@mikij I can't use it now.  Temporarily use Debugger for Chrome4.11.7

**Comment by mikij** [comment]
I am using the old Debugger for Chrome all the time while I am waiting for any proper fix for new one to give it a try.

**Comment by connor4312** [comment]
Thanks for letting me know. I'm guessing that something in your setup is different and not triggering the detection that I added to take the fast path for these kinds of bundles.

It may be easier to get approval to send part of the file. In the logs, you should see a very large number of lines containing the string "Debugger.paused". If you can send a sample of these events to me, that should provide enough information to fix up the logic.

**Comment by FishOrBear** [comment]
[typescript-webpack.zip](https://github.com/microsoft/vscode-js-debug/files/4607140/typescript-webpack.zip)

```
npm i
npm run dev
```
in vscode f5

add breakpoint in /src/TestCmdd.ts

change /src/TestCmd.ts

@connor4312

**Comment by mikij** [comment]
Any news @connor4312 ?

**Comment by FishOrBear** [comment]
@mikij @connor4312 
need to create a new ISSUE to track ？
