### ISSUE TITLE
Open profiles in untitled editors on complete

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#432]
For use with the profile visualizer.

Currently blocked on https://github.com/microsoft/vscode/issues/93441 -- until then profiles will be opened up as an unfriendly wall of JSON.

**Comment by connor4312** [comment]
Untitled editors can't be opened for custom webviews. Instead we now save the profile in the workspace and open it as a normal file.

**Comment by aeschli** [comment]
![image](https://user-images.githubusercontent.com/6461412/80602456-72107a80-8a2f-11ea-9fbe-956d82ed857c.png)

Taking a snapshor was not so easy, but found an context menu item on the call stack :-)
