### ISSUE TITLE
Support for capturing heap and tracing-API-based profiles

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#435]
Right now we can capture CPU profiles. We should also support heap profiles for all targets, and can consider supporting tracing API-based profiling for browsers.

**Comment by jasonwilliams** [comment]
This is exciting.
I suppose there needs to be an option to `start` and `stop` right?
So we can pick and choose which bits we want to capture

**Comment by connor4312** [comment]
This issue is a good one for Grace Hopper / Hacktoberfest! 

Collecting a heap profile here should be possible with plug-ins to our existing functionality. [CDP docs](https://chromedevtools.github.io/devtools-protocol/v8/HeapProfiler) -- you'll probably want to look at the sampling heap profile initially.

You want to create a new [IProfiler class here](https://github.com/microsoft/vscode-js-debug/blob/48de86f3cc8ec2d629add5e5915be84b1702090e/src/adapter/profiling/index.ts#L86). The interfaces should guide you through what's needed. You'll probably want to abstract and reuse some of the location-massaging code from the CpuProfiler.

Once it's there, the "Start Profiling" command (available when running a Node.js program) will open a picker asking you what kind of profile you want to take.

Additional extra things you could do once you have that working:

- Currently, profiling is duration based, but users could also want to take point-in-time snapshots of their heap. You can add support for this, which will involve some changes in the [ui side of things](https://github.com/microsoft/vscode-js-debug/blob/909e4f1d33860f305bc9ad4fd96c072bf366672c/src/ui/profiling/uiProfileManager.ts#L135-L143) since there's no 'termination condition'
- You can add support for viewing the resulting heap profile files to the visualizer: https://github.com/microsoft/vscode-js-profile-visualizer

General contributing/setup: https://github.com/microsoft/vscode-js-debug/blob/master/CONTRIBUTING.md#development

**Comment by timjensen-kr** [comment]
Any idea when this might get added? We would love to use this functionality

**Comment by connor4312** [comment]
We had a contribution to add heap profiling. Currently no plans to add a tracing profiler to VS Code.
