### ISSUE TITLE
Terminated events coming in before initialize response

### ISSUE THREAD

**Issue by EricCornelson** [microsoft/vscode-js-debug#436]
Hey guys, found another one of these.

My repro scenario for this one is: have a webpage with a web worker, hit refresh in the browser multiple times quickly. The webworker debug session can send the terminated event before it responds to initialize, which causes VS to get into a bad state because it still thinks that session is active (we don't get the terminate because it comes in before init). In VS we see duplicate webworker processes shown in the process window, and an error message the next time we pause.

![image](https://user-images.githubusercontent.com/38218905/79398078-9438d180-7f34-11ea-8fea-9ad686483190.png)

![image](https://user-images.githubusercontent.com/38218905/79398111-a61a7480-7f34-11ea-8749-49943132083b.png)

Logs attached:
[vscode-chrome-debug.txt](https://github.com/microsoft/vscode-js-debug/files/4484113/vscode-chrome-debug.txt)

**Comment by connor4312** [comment]
The work you did in your recent PR made this easy to fix 🙂 let me know if you see future occurrences of this issue
