### ISSUE TITLE
Unable to use "request": "attach" with "type": "pwa-msedge"

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode-js-debug#441]
I have no problem to attach to riunning MS Edge instance (Version 84.0.488.1 (Official build) dev (64-bit)) using `msedge` and `pwa-chrome` configurations, however if I try `pwa-msedge` UI changes to debug state (buttons, status bar) but nothing happens.

Target in Edge shortcut: `"C:\Program Files (x86)\Microsoft\Edge Dev\Application\msedge.exe" --profile-directory=Default --remote-debugging-port=5555`

Tried debugger configurations:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to pwa-msedge",
            "port": 5555,
            "request": "attach",
            "type": "pwa-msedge",
            "webRoot": "${workspaceFolder}"
        },
        {
            "name": "Attach to pwa-chrome",
            "port": 5555,
            "request": "attach",
            "type": "pwa-chrome",
            "webRoot": "${workspaceFolder}"
        },
        {
            "name": "Attach to Edge",
            "port": 5555,
            "request": "attach",
            "type": "msedge",
            "webRoot": "${workspaceFolder}",
        }
    ]
}
```

In console I see next errors:
```
[Extension Host] Unknown request: enableCustomBreakpoints (at a._onMessage (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.js-debug-nightly\src\extension.js:15:2438600))
[Extension Host] Writing to a closed connection (at t.StreamDapTransport.send (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.js-debug-nightly\src\extension.js:94:12665))
```

When I try `"request": "launch"` with `"type": "pwa-msedge"` - it opens new window and breakpoints work as expected.

---

Version: 1.45.0-insider (user setup)
Commit: b83339a3a7bd8e3ec8a8b79deda9c37e0d91f094
Date: 2020-04-21T05:41:11.873Z
OS: Windows_NT x64 10.0.18363

**Comment by connor4312** [comment]
Thanks for the report!
