### ISSUE TITLE
Couldn't find a debug adapter descriptor for debug type 'pwa-chrome' (extension might have failed to activate

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode-js-debug#450]
Has the name of the launch profile changed recently?
I had the same happen with `pwa-node` i needed to change it to just `node`

**Comment by connor4312** [comment]
Thanks for the report--triggered a new nightly build with the fix.

**Comment by JacksonKearl** [comment]
steps?

**Comment by connor4312** [comment]
Try to debug anything with the latest version of js-debug on stable. (Used a new API in activation which prevented the extension from activating.)
