### ISSUE TITLE
Not detaching from some vscode processes when code-oss goes down

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#453]
- Run "VS Code" compound launch config
- Quit Code-OSS
- The shared process config appears to be still attached
- But evaluating something doesn't return any result, so I think the process is dead

![image](https://user-images.githubusercontent.com/323878/80631721-cad61800-8a1b-11ea-920d-f0765405d352.png)

**Comment by connor4312** [comment]
See https://github.com/microsoft/vscode/issues/95964
