### ISSUE TITLE
Replace TS with acorn for code parsing

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#457]
Right now our introspection logic uses TS. This is nice but TS is fairly huge, constituting over 2/3rds of our extension size. See whether it's possible to swap it out for Acorn.

**Comment by FishOrBear** [comment]
https://github.com/cherow/cherow
It seems that performance will be better.

**Comment by connor4312** [comment]
I'm not sure the performance difference is worth using a less widely-used parser. But using either acorn or esprima will mean dealing with estree nodes, so once that happens we can in theory swap out the parser with any compliant implementation.

**Comment by connor4312** [comment]
Doesn't look like this will work well with completions; we need to be able to roughly parse incomplete/invalid expressions, which parsers generally do not handle. The exceptions are TypeScript, flow, and traceur which are all similarly large and bulky.
