### ISSUE TITLE
Add an option to start the profiling before the program launches

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#467]
Refs: https://github.com/microsoft/vscode-js-debug/issues/388

**Comment by connor4312** [comment]
You can now set an option in your launch config, `profileStartup: true`, for this. Works in Node.js and Chrome, cc @jasonwilliams

**Comment by jasonwilliams** [comment]
That’s great news, thanks!
I haven’t tried it yet but what does it do by default (if you don’t set a break point) does it run for a limited duration?

Im guessing if you set a breakpoint it runs up to that.

Semi related to https://github.com/microsoft/vscode-js-debug/issues/471

**Comment by connor4312** [comment]
At the moment it will start profiling and continue doing so until you stop it. Chrome's version of this ("reload and start profiling" in the performance tab) seems to have some auto-detection figuring out when loading finishes. We can probably do something similar using a debounced function that's fired after we stop seeing scriptParsed events.

I don't want to choose an arbitrary time after which to stop profiling, and enabling breakpoints affects performance.

**Comment by jasonwilliams** [comment]
Hey @connor4312 does this still work? I have  `"profileStartup": true` set and when a very short js file finishes running on the debugger nothing is output. 

> launch.json
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}\\test.js",
            "profileStartup": true,
        }
    ]
}
```

**Comment by connor4312** [comment]
> I've also noticed breakpoints fail to work when "profileStartup": true, is enabled too. I don't know if this is a bug or something expected.

when profiling is running, the Debugger domain is disabled. This follows what Chrome devtools _used_ to do, though last week I've noticed they now only disable async call stacks, so we can probably do the same.

>  I have "profileStartup": true set and when a very short js file finishes running on the debugger nothing is output.

Unfortunately collecting the profile requires interaction with the program, so when the program ends we lose our opportunity to get the profile. You might be able to set some arbitrary timeout and manually stop the profile when the code you're interested in finishes executing.

Though I was recently made aware of a new set of console APIs, [profile/profileEnd](https://developer.mozilla.org/en-US/docs/Web/API/console/profile). I haven't tried these yet, I'm guessing we need to add js-debug hooks for them, but they may work better. I assume profileEnd just taps the debugger and we still need to round-trip to the runtime to grab the profile data which would result in some race conditions with fast-ending programs...
