### ISSUE TITLE
Can't reload window when debugging vscode

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#469]
- Run the "Launch VS Code" launch config with js-debug
- Reload the window
- Debugging stops and code-oss closes

In the log it looks like it thinks the target shut down. But reloading works fine when the debug adapter didn't start the process.

Started a week ago I think. I'm not sure whether something changed in js-debug or in electron.

[vscode-debugadapter-0.txt](https://github.com/microsoft/vscode-js-debug/files/4629857/vscode-debugadapter-0.txt)

**Comment by connor4312** [comment]
I saw @sbatten report this as well. It looks like you're on an older js-debug build, and I can't repro this on the latest build on windows or osx. I updated the builtin version of js-debug, please let me know if you continue to hit this.
