### ISSUE TITLE
Add optional fields to this readme 

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode-js-debug#471]
Can we add the fields you set to the read me of this repo?
I often have to go searching elsewhere for them.

If this does become the official debugger replacing the older chrome one it would be good to see the options here. Also for context of what these options do and how they work, showing the default is very useful too.

Maybe start by copying over https://github.com/microsoft/vscode-chrome-debug#other-optional-launch-config-fields

Btw great work on this extension, it’s really coming together now.

**Comment by connor4312** [comment]
Added generated documentation in the linked commit. Reading it, though, I realize that some options need further clarification. I will follow up with that at a later point.
