### ISSUE TITLE
Breakpoint doesn't hit on react redux application

### ISSUE THREAD

**Issue by digeff** [microsoft/vscode-js-debug#472]
The breakpoint hits on v1 but doesn't hit on js-debug.

Repro steps:
Create Asp.Net Core React&Redux project
Set breakpoint at "ClientApp\src\App.tsx"
Debug Project

[v1 works vscode-chrome-debug.txt](https://github.com/microsoft/vscode-js-debug/files/4637325/v1.works.vscode-chrome-debug.txt)

needs to reinstall node_modules to use the .zip project
[ASPNetCoreReactRedux.zip](https://github.com/microsoft/vscode-js-debug/files/4637328/ASPNetCoreReactRedux.zip)

[v3 does not work vscode-debugadapter-7.zip](https://github.com/microsoft/vscode-js-debug/files/4637330/v3.does.not.work.vscode-debugadapter-7.zip)

**Comment by connor4312** [comment]
This works for me

![](https://memes.peet.io/img/20-05-040942bc-2ee0-4f1e-8350-d47970aad8f9.png)

**Comment by digeff** [comment]
Just to recap the information sent by chat, the breakpoint on line 11 works fine, the issue is when the breakpoint it set on line 10.

**Comment by connor4312** [comment]
This looks like a bug in react-scripts, it generates a source mapping position at the end of the export statement. If I upgrade the project to the latest react-scripts @ 3.4.1, it works

![](https://memes.peet.io/img/20-06-4586fd48-995d-43a5-a927-cf429cec480d.png)
