### ISSUE TITLE
Add setting to remove "using the preview version" in console

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode-js-debug#474]
```
Note: Using the "preview" debug extension
```

Would like to remove it.

**Comment by roblourens** [comment]
Some day soon we will remove it and add "Using the legacy debug extension" in the old one 😁

**Comment by connor4312** [comment]
There's now a stable build of js-debug, in which this message does not show: https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug
