### ISSUE TITLE
Unbound breakpoints after VS Code update

### ISSUE THREAD

**Issue by Jaffsterz** [microsoft/vscode-js-debug#475]
VS Code has automatically updated to 1.45.1 and now none of the breakpoints in our Vue JS files work - they all show as "unbound breakpoint". This applies to all developers in our team who have had the update applied, and not to those that haven't. nothing else has changed in the project code/config.

I've enabled trace:true in launch.json and the only error message I see is:

`[23732:26588:0516/112644.945:ERROR:browser_switcher_service.cc(238)] XXX Init()` 

Chrome version is 81.0.4044.138.

Launch configuration is:

`"configurations": [
    {
      "type": "chrome",
      "request": "launch",
      "name": "vuejs: chrome",
      "url": "http://localhost:8081",
      "webRoot": "${workspaceFolder}/src",
      "breakOnLoad": true,
      "sourceMapPathOverrides": {
        "webpack:///src/*": "${webRoot}/*"
      },
    }`

User settings.json has:
`    "debug.node.useV3": true,
    "debug.chrome.useV3": true,`

One oddity... when we start debug it always breaks at this point in bootstrap.js, despite there not being a breakpoint there (this did not happen before the update):

![image](https://user-images.githubusercontent.com/50236257/82117771-6da3cb80-976a-11ea-9ece-496c855c50f6.png)

Thanks for any help/advice.

**Comment by Jaffsterz** [comment]
In case anyone has the same problem, to fix it I had to change this entry in launch.json:
`"sourceMapPathOverrides": { "webpack:///src/*": "${webRoot}/*" }`
to this:
`      "sourceMapPathOverrides": {
        "webpack:///./src/*": "${webRoot}/*",
      },`
No idea why.

**Comment by connor4312** [comment]
Thanks for the report. I had removed a Vue hack/workaround on the assumption that it wasn't sufficient to debug vue (following #239). But it appears that assumption is not correct, good to know it works for you. Restored in the linked commit and should be in the next nightly.
