### ISSUE TITLE
Debug command not available

### ISSUE THREAD

**Issue by Leigh-M** [microsoft/vscode-js-debug#477]
Debug: Toggle Auto Attach     in either VSCode terminal or Command Palette does not work for me 

Ubuntu Linux 18.04.3 LTS  x64
VSCode 1.45.1
NodeJs  12.8.1

In bash terminal:     bash: Debug:: command not found

**Comment by connor4312** [comment]
Can you please provide more details around how you get that "command now found"? Toggling auto attach does not write anything to the terminal so I'm not clear how you end up with "command not found"

**Comment by connor4312** [comment]
Please follow up if you're able to provide more information on this
