### ISSUE TITLE
bit confused with the node.js preview option

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode-js-debug#482]
Lately there's another option in my debugger menu.
`node.js preview`

I already have some Node launch profiles set up, do i need this option? 
Im not sure what it's for or what it gives me over what i've created myself.

Screenshot
![image](https://user-images.githubusercontent.com/936006/82548655-8db10180-9b53-11ea-868e-c0fd3b55a575.png)

**Comment by connor4312** [comment]
These are the new dynamic launch configurations (https://github.com/microsoft/vscode/issues/95835). The goal of having these--which provide automatic configuration for things like running npm scripts, running the current file, or opening the debugger terminal--is to make it easier for people to start debugging with zero configuration; we see that a relatively small fraction of VS Code users use the editor for debugging, and we want to expand the funnel.

If you already have configurations that you added manually, you probably don't care about using the dynamic configurations 🙂

**Comment by jasonwilliams** [comment]
@connor4312 do we have a better name than `node.js preview`?
I didn't think this extension was preview anymore now its the default debugger. Plus the title doesn't really describe what that option does.

I know it's a bikeshed, but are there better names to use?

**Comment by connor4312** [comment]
Good callout -- this month we're planning to do some name-swapping and remove the "preview" wording from the new debugger, and instead add "legacy" to the old debuggers.

**Comment by jasonwilliams** [comment]
Hey @connor4312 I have a couple of questions.

> this month we're planning to do some name-swapping and remove the "preview" wording from the new debugger, and instead add "legacy" to the old debuggers.

Is this still happening?

>     "debug.javascript.usePreview": true,

Do i still need to set this? 
Im really confused whether this debugger is preview or not. The top of the readme says this still needs to be set but i assumed this debugger is now used by default? If its not the default is that planned to happen?

Whats the difference between `pwa-node` and just `node` if I have usePreview on? Aren't they the same thing?
Do we still need `pwa-node`? I assumed that was just there to not conflict with the old debugger.

Sometimes when I create a new launch config I have 3 node options (I usually pick pwa but i don't know what the other 2 are):
- `node`
- `node2`
- `pwa-node`

Sorry for all the Qs I just find setting up new config not as smooth as it could be, but I'm sure this is for good reason.

**Comment by jasonwilliams** [comment]
I think you may have answered some of those questions in this thread https://github.com/microsoft/vscode-js-debug/issues/548#issue-649402062

**Comment by connor4312** [comment]
Some preview wording has been removed. Didn't quite fit it into september, and last month was our housekeeping month. More likely this "month" (release in early Jan); we're looking to officially deprecate the old debuggers early next year so swapping wording and setting names will come before that.
