### ISSUE TITLE
Error running browser: Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by hholst80** [microsoft/vscode-js-debug#484]
Run with debug (Chrome preview) results in the following error:

    Error running browser: Cannot call write after a stream was destroyed

I have installed the companion (or it was done for me) outside the remote container and in the remote container I have installed the workspace plugin vscode-js-nightly.

![image](https://user-images.githubusercontent.com/6200749/82810690-6463de80-9e8f-11ea-8177-01e33e29afb0.png)

```
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:22.494Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-31-generic
```

**Comment by hholst80** [comment]
Same problem with vscode nightly without any extensions installed.

```
Version: 1.46.0-insider
Commit: 2591ede95a52400d5d22989b16706f9b8b4831da
Date: 2020-05-22T21:12:53.428Z
Electron: 8.3.0
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Linux x64 5.4.0-31-generic
```

**Comment by hholst80** [comment]
google chrome @ host

```
Version 83.0.4103.61 (Official Build) (64-bit)
```

**Comment by connor4312** [comment]
I'm having trouble reproducing this. Can you please do the following:

 1. Verify that you have the extension `id:ms-vscode.js-debug-nightly` installed on your _local_ machine
 2. Enable `trace: true` in your launch config, and share the logs if you're able

**Comment by hholst80** [comment]
I might have done something wrong in the `launch.json` configuration. I did not have the old config available and I tried making up one new from scratch on a another system. I came up with this,
```
        {
"type":"pwa-chrome",
"request": "attach",
"name": "chrome @ localhost:9222",
"address": "localhost",
"port": 9222
        },
```

This works just fine.

**Comment by connor4312** [comment]
Okay, thanks for letting us know!

**Comment by 80sax** [comment]
I think the error is present using "request": "launch"
https://github.com/microsoft/vscode-js-debug/issues/659
