### ISSUE TITLE
Error: Unknown session id: <session-id> while processing: Inspector.targetReloadedAfterCrash

### ISSUE THREAD

**Issue by digeff** [microsoft/vscode-js-debug#486]
We got telemetry that the debug adapter is seeing a lot of this error:
```
Error: Unknown session id: <session-id> while processing: Inspector.targetReloadedAfterCrash
    at t.default._onMessage (connection.js:47:19)
    at call (connection.js:19:61)
    at t.EventEmitter.fire (events.js:36:27)
    at T.call (webSocketTransport.js:21:33)
    at T.r (event-target.js:120:16)
    at T.emit (events.js:210:5)
    at e.exports.R (websocket.js:801:20)
    at e.exports.emit (events.js:210:5)
    at e.exports.dataMessage (receiver.js:436:14)
    at e.exports.getData (receiver.js:366:17)
```

This also happens while processing these other events, and some request responses too:

- Debugger.scriptParsed
- Mono.runtimeReady
- Runtime.consoleAPICalled
- Inspector.targetCrashed
- Inspector.detached

Can this be causing a detrimental experience to the users?

**Comment by digeff** [comment]
A lot of our users are hitting this issue. Raising to vs-p1

**Comment by connor4312** [comment]
Found one big case I was hitting locally -- if the user manually detached from a target, we didn't tell Chrome about that, so were still getting messages from a tab that we didn't care about.

**Comment by digeff** [comment]
Awesome! :)

**Comment by connor4312** [comment]
@digeff / @EricCornelson do you still see this coming up in your telemetry since my initial fix above?

**Comment by connor4312** [comment]
Closing and marking verified -- please let me know if this is not appropriate.

**Comment by digeff** [comment]
@connor4312 Sorry for the delay. At the moment all the stack traces in telemetry are blank, so we don't know what's happening yet. We are looking into this.
