### ISSUE TITLE
debugger traces back to wrong line while digging in react source code

### ISSUE THREAD

**Issue by TomYang1993** [microsoft/vscode-js-debug#487]
- VS Code Version: 1.44.2
- Log file (set `"trace": true` in launch config):

Steps to reproduce:

1. set up any basic react app
2. set break point at line 'return' in render function
3. trace the call stack of 'return' in reactJS source code
4. you will find it's tracing back to wrong line number.
 or maybe the line number is right just the file is formatted differently

As shown below, in debugger it traces back to wrong line. in chrome developer tool, it traces back to correct line in source.

![Screen Shot 2020-04-28 at 11 42 23 PM](https://user-images.githubusercontent.com/20257736/80559048-6890ff00-89aa-11ea-9efd-7d587724b9c1.png)
![Screen Shot 2020-04-28 at 11 42 36 PM](https://user-images.githubusercontent.com/20257736/80559069-76468480-89aa-11ea-9d52-d5ec8de7a7cf.png)
![Screen Shot 2020-04-28 at 11 43 03 PM](https://user-images.githubusercontent.com/20257736/80559088-8199b000-89aa-11ea-9b4b-0253f6348ae3.png)
![Screen Shot 2020-04-28 at 11 43 15 PM](https://user-images.githubusercontent.com/20257736/80559097-8494a080-89aa-11ea-9aa9-457232021699.png)

**Comment by connor4312** [comment]
I tried to reproduce this with js-debug. I didn't hit the exact same stack trace as what Tom had in the screenshots, but checked _a_ react rendering stacktrace and everything lined up in both vs code and the devtools. Let us know if you can reproduce and get a trace log with the new debugger.

**Comment by TomYang1993** [comment]
@jasonwilliams yes, I meant that the same behavior still happened when I used the new debugger, thank you for bring that up

**following** is the App.js example I used, others come from standard react-create-app

```import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';

class App extends Component {

  constructor(){
    super();
    this.clickTitle = "something"
  }
  
  testClick(clickTitle) {
    console.log("clicked")
  }

  testDefineFunction = () => {

  }

  render() {
    return (
      <div className="App">
        <div>
          <label>Location</label>
          <input />
          <button onClick={() => this.testClick(this.clickTitle)}>Submit</button>
        </div>
      </div>
    );
  }
}

export default App; 
```

**following** is the screenshot of the new debugger
![Screen Shot 2020-05-28 at 8 58 15 PM](https://user-images.githubusercontent.com/20257736/83209549-a65a8200-a126-11ea-83fc-f5d66dfcad5e.png)

**following** is the screenshot of the chrome devtools(which is working fine)
![Screen Shot 2020-05-28 at 8 58 44 PM](https://user-images.githubusercontent.com/20257736/83209641-cee27c00-a126-11ea-9717-63a1154b7565.png)

**following** is the screenshot of launch.json
![Screen Shot 2020-05-28 at 9 05 42 PM](https://user-images.githubusercontent.com/20257736/83209740-02bda180-a127-11ea-987c-478c17f531dd.png)

not sure if the trace configuration is correct, but yeah the same behavior remains

vscode on 1.45.1
vscode-js-debug on 2020.5.2717

**Comment by jasonwilliams** [comment]
@TomYang1993 In your debug console at the bottom (first image).

It should say something about outputting a log or trace file, are you able to upload the contents of that? Maybe in a gist or something

**Comment by TomYang1993** [comment]
Library/Application Support/Code/logs/20200529T110520/exthost1/ms-vscode.js-debug-nightly/vscode-debugadapter-0.json

like this one? seems too huge, maybe truncated

[vs-js-debugger json file link](https://gist.github.com/TomYang1993/08ffaf8d324a6bb8d128f79f55c66fb4)

**Comment by connor4312** [comment]
Thanks for the details. This appears to be an issue with the setup in react-scripts; they have a sourcemap for `node_modules/react-dom/cjs/react-dom.development.js`, but the contents of the source in the sourcemap are different from the _actual_ source on disk. Chrome is okay with this because it reads from the sourcemap as its point of truth, but in VS Code we need to correlate files with those on the disk.

I saw the repo on your github, which is on a very old react-scripts build. They've fixed this in the most recent version.

**Comment by TomYang1993** [comment]
@connor4312 great! thank you! a npm install should work then
