### ISSUE TITLE
Error processing evaluate: TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#490]
This happens when I set a breakpoint on line 55 of richTransform.ts and change the renderer of a notebook cell. I can help you repro it if the log isn't enough.

![image](https://user-images.githubusercontent.com/323878/83205511-5a9edd00-a114-11ea-8aa2-3892b25a6789.png)

[debug.json.txt](https://github.com/microsoft/vscode-js-debug/files/4698823/debug.json.txt)

**Comment by connor4312** [comment]
Thanks, somehow we managed to not hit that code path in any of our unit tests

**Comment by connor4312** [comment]
Easiest verification: run `new Map([['foo', function() {}']])` in the repl and verify that it works and shows the value instead of an error
