### ISSUE TITLE
Call stack VS Code view hangs up after a large number of steps over in React Web App

### ISSUE THREAD

**Issue by SounD120** [microsoft/vscode-js-debug#495]
JS debug version: 2020.6.117
VS Code: 1.45.1
OS: Windows 10

Hi guys. I found up that if we do a lot of steps over in React App (just press on F10 button for 5-10 seconds) call stack window is just freezes, shows spinner and stops updating stack frames.
![breakpoint](https://user-images.githubusercontent.com/32372875/83525018-15502600-a4ed-11ea-9af8-b601f19f7c6a.gif)
Reproduce steps:
1. Create new React app: 
```bash
npx create-react-app my-app
cd my-app
npm start
```
2. Open VS Code and use the following debug scenario:
```json
        {
            "type": "pwa-chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceFolder}/build"
        }
```
3. Stop on any breakpoint inside of `App.js` file and hold the F10(Step Over) button for some time(it takes up to 5-10 seconds to reproduce) and the call stack view will hang up as shown on the picture above.

Log file: 
[vscode-debugadapter-0.txt](https://github.com/microsoft/vscode-js-debug/files/4721630/vscode-debugadapter-0.txt)

**Comment by EricCornelson** [comment]
@SounD120 could you attach a log file of when this issue occurs?

**Comment by SounD120** [comment]
@EricCornelson Added! 
I also made some observation and found out that it is more likely the data transfer problem, since if we debug the code with the less deep call stacks than in React it works without problems. So the deep stack traces and the data transfer speed are more likely cause this problem.
