### ISSUE TITLE
Blazor WASM debugging in VSC unable to open browser

### ISSUE THREAD

**Issue by mkArtakMSFT** [microsoft/vscode-js-debug#504]
---
**Issue moved from dotnet/aspnetcore#22527**
- Please respond to @guardrex.

---

_From @guardrex on Thursday, June 4, 2020 12:48:25 AM_

### Describe the bug

Edge doesn't open for WASM debugging in VSC.

### To Reproduce

Stock WASM app created from the 3.2 template and configured for Edge ...

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch and Debug Standalone Blazor WebAssembly App",
            "type": "blazorwasm",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "browser": "edge"
        }
    ]
}
```

### Exception

![image](https://user-images.githubusercontent.com/1622880/83702141-68030e00-a5d1-11ea-83e5-93aba8b9ef09.png)

### Additional note

The error dialog suggests setting the runtime executable for Edge (`runtimeExecutable`), but I don't think that's possible (not without hacks perhaps). Edge docs don't reveal much info about how Edge is launched, and they certainly they don't speak to an executable that does it. Research seemed to indicate that Edge doesn't launch via an executable.

### Further technical details

.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  3.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

### VS Code

Version: 1.45.1 (system setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

### JavaScript Debugger (Nightly)

Version: 2020.6.317

### Microsoft Edge

Version: 44.18362.449.0

cc: @captainsafia

**Comment by mkArtakMSFT** [comment]
---
**Issue moved from dotnet/aspnetcore#22527**
- Please respond to @captainsafia.

---

_From @captainsafia on Thursday, June 4, 2020 4:20:49 PM_

> The error dialog suggests setting the runtime executable for Edge (runtimeExecutable), but I don't think that's possible (not without hacks perhaps). 

The error dialog is coming up from VS Code's JS debugger.

I just gave this a go on a Windows VM and I was able to get the Edge browser to launch so this isn't a generic issue.

I suspect that the JS debugger is looking for Edge in a certain location and unable to find it there based on the particular installation on your machine.

Where is Edge installed on your machine?

**Comment by mkArtakMSFT** [comment]
---
**Issue moved from dotnet/aspnetcore#22527**
- Please respond to @guardrex.

---

_From @guardrex on Thursday, June 4, 2020 4:29:22 PM_

:smile: I'm glad u asked ...

> C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe

... **_and I found my EXE!_** :tada:

<img width="346" alt="Capture" src="https://user-images.githubusercontent.com/1622880/83785219-9bd44700-a656-11ea-9269-11413ab020a2.PNG">


That might permit me to enhance the Blazor security troubleshooting steps.

**Comment by mkArtakMSFT** [comment]
---
**Issue moved from dotnet/aspnetcore#22527**
- Please respond to @captainsafia.

---

_From @captainsafia on Thursday, June 4, 2020 4:33:36 PM_

Yep! That would be it. The JS debugger looks for an edge installation on Windows in the local program data directory and under program files on Windows.

On macOS, it looks under the `/Applications` and `/Contents/Mac OS` directories for the executable.

**Comment by mkArtakMSFT** [comment]
---
**Issue moved from dotnet/aspnetcore#22527**
- Please respond to @guardrex.

---

_From @guardrex on Thursday, June 4, 2020 4:37:01 PM_

Are you saying that is or is not the right spot for the latest version of Windows 10?

Should I be taking steps to reinstall it ... or move it? 😨 ... *which is a little scary.*

**Comment by mkArtakMSFT** [comment]
---
**Issue moved from dotnet/aspnetcore#22527**
- Please respond to @captainsafia.

---

_From @captainsafia on Thursday, June 4, 2020 4:50:36 PM_

@guardrex Actually, it looks like you can set an environment variable to set it to the correct path.

```
EDGE_PATH = "blah"
or
CHROME_PATH = "blah"
```
So what we should let users know that the debugger will look in the default installation directories and that EDGE_PATH and CHROME_PATH can be used indicate where the install is.

Can you try setting this environment variable to the location of your executable and see if that works?

**Comment by mkArtakMSFT** [comment]
---
**Issue moved from dotnet/aspnetcore#22527**
- Please respond to @guardrex.

---

_From @guardrex on Thursday, June 4, 2020 4:55:22 PM_

Done ...

*Hummmmm* 🤔 ... I didn't know that I wasn't on a stable release ...

<img width="422" alt="Capture" src="https://user-images.githubusercontent.com/1622880/83787931-24a0b200-a65a-11ea-83fa-f06595e23bff.PNG">

I guess I can try setting the path explicitly in *launch.json* and see what happens.

**Comment by mkArtakMSFT** [comment]
---
**Issue moved from dotnet/aspnetcore#22527**
- Please respond to @guardrex.

---

_From @guardrex on Thursday, June 4, 2020 4:59:43 PM_

It doesn't like the syntax in the file, and it doesn't work ...

<img width="777" alt="Capture" src="https://user-images.githubusercontent.com/1622880/83788481-de981e00-a65a-11ea-833a-6d21000568dd.PNG">

**Comment by mkArtakMSFT** [comment]
---
**Issue moved from dotnet/aspnetcore#22527**
- Please respond to @guardrex.

---

_From @guardrex on Thursday, June 4, 2020 5:01:09 PM_

... and I don't see anything in Edge that indicates that I'm not using a stable release.

**Comment by connor4312** [comment]
@guardrex being in SystemApps that looks like the "old" Edge browser, which we don't support; js-debug only works with the [fancy new Edge](https://www.microsoft.com/en-us/edge) browser. Download that and I should work for you!

**Comment by guardrex** [comment]
Thanks @connor4312 ... do I need to uninstall the current one first?

**Comment by connor4312** [comment]
no

**Comment by guardrex** [comment]
ok, thx. I'll do that right now and post back the result.

**Comment by guardrex** [comment]
Thanks @connor4312 ... it ✨ **_Just Works!_**:tm: ✨ now.

@captainsafia, seems like we should have a line (a bullet point) in the doc's *Troubleshoot* node to cover this error scenario. Do you concur?

**Comment by connor4312** [comment]
Thanks for confirming, close the issue on this repo then.

**Comment by guardrex** [comment]
Rubber :duck: says that you'll say *yearp!* to that.

Thanks again @connor4312 ... we'll steer others in the right direction with the topic.
