### ISSUE TITLE
Debug bar still show debug actions if tab it was attached to was closed

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode-js-debug#506]
Config
```json
{
    "type": "pwa-msedge",
    "request": "attach",
    "port": 9222,
    "name": "Attach Edge",
    "targetSelection": "pick",
    "urlFilter": "example.com*",
    "webRoot": "${workspaceFolder}"
}
```

1. Open https://example.com/target and https://example.com/other in browser
1. Start debug with config above and pick https://example.com/target from list
1. Close tab with https://example.com/target
1. Call Stack section is empty but debug bar still has actions Pause, Step Over etc.

In this case of `"targetSelection": "pick"` session should be stopped - even if I open another tab with same URL it wont be attached to it (as expected).

In case of `"targetSelection": "automatic"` I would expect same behavior - close all tabs to stop debug session, but I see how some might want to leave session - new tabs would be picked up.

**Comment by connor4312** [comment]
Thanks for the issue and good steps. Fixed this for both "pick" and "automatic".

**Comment by aeschli** [comment]
Trying to reproduce this on Windows 10 2004 with Edge.
On step 2. I don't get a picker, but a dialog
`Could not connect to debug target at http://localhost:9222: Could not find any debuggable target`
Is there anything else I need to configure so that Edge knows about that port?

**Comment by aeschli** [comment]
Ok, got it: `"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --remote-debugging-port=9222`
