### ISSUE TITLE
Inconsistent behavior when targetSelection is "pick"

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode-js-debug#508]
There is inconsistencies in behavior in case when I have 1 or more tabs that match `urlFilter` while `"targetSelection": "pick"`.

Config
```json
{
    "type": "pwa-msedge",
    "request": "attach",
    "port": 9222,
    "name": "Attach Edge",
    "targetSelection": "pick",
    "urlFilter": "example.com*",
    "webRoot": "${workspaceFolder}"
}
```

1. Open https://example.com/target and https://example.com/other in browser
1. Start debug with config above and pick https://example.com/target from list
1. Duplicate any of example.com tabs or open new e.g. https://example.com/newtab
1. Debugger has only one "tab session" it is attached to which is _expected behavior_

Now repeat same steps, but make sure that there is only one tab that matches `urlFilter`
1. Make sure that only https://example.com/target is open
1. Start debug with config above - debugger attached to Example domain without prompt _as expected_
1. Duplicate any of example.com tabs or open new e.g. https://example.com/newtab
1. Each new tab is now in Call Stack session in debugger - _not expected_

When `"targetSelection": "pick"` and there is only one tab opened I would expect same behavior as when I manually pick tab to attach to.

**Comment by connor4312** [comment]
Thanks, related: https://github.com/microsoft/vscode-js-debug/issues/505
