### ISSUE TITLE
Unexpected pause on instrumentation breakpoint

### ISSUE THREAD

**Issue by EricCornelson** [microsoft/vscode-js-debug#514]
Repro project & steps: see: https://github.com/EricCornelson/repro_two_ts_files_extra_pause

Basically we see an extra pause on a line we never set a breakpoint on (and break on entry is not set) due to an instrumentation breakpoint set on the bundle.js, and because the instrumentation bp is actually on line 3, it doesn't get auto-skipped.

![image](https://user-images.githubusercontent.com/38218905/84061646-2aa4d480-a973-11ea-977f-771d02e1e761.png)

![image](https://user-images.githubusercontent.com/38218905/84061659-30021f00-a973-11ea-80aa-23d8873c55f4.png)

**Comment by connor4312** [comment]
Can you send a trace log for this?

**Comment by EricCornelson** [comment]
Logs:
[pause_bug.txt](https://github.com/microsoft/vscode-js-debug/files/4748411/pause_bug.txt)

**Comment by connor4312** [comment]
Thanks for the repro--reflecting my naivety when I first started working on js-debug, we were being too aggressive about determining whether we should pause at an instrumentation point
