### ISSUE TITLE
Can't set breakpoint in vscode, but can in chrome devtools

### ISSUE THREAD

**Issue by qiulang** [microsoft/vscode-js-debug#516]
- VS Code Version: Version: 1.45.0
- Log file 
[vscode-chrome-debug.txt](https://github.com/microsoft/vscode-chrome-debug/files/4602758/vscode-chrome-debug.txt)

This is a vue project (setup using vue-cli 3.0), I can set breakpoints in some vue files but not others and I could not figure out why. 

But I then found that for those files I can't set breakpoint, if I set breakpoint in chrome devtools (webpack://src), debugger will stop at the breakpoint inside vscode. So I suspect it is vscode's problem.

Attached 2 screenshot to demonstrate the issue,

<img width="1386" alt="呼叫中心坐席系统_和_New_Issue_·_microsoft_vscode-chrome-debug" src="https://user-images.githubusercontent.com/516243/81465464-eb148c80-91fc-11ea-8736-a6011f20f3f7.png">

But if I set breakpoint in vscode directly it won't work, debugger won't stop.

<img width="1245" alt="截屏2020-05-09下午1 49 10" src="https://user-images.githubusercontent.com/516243/81465502-1b5c2b00-91fd-11ea-9d5c-5a5ef55abe18.png">

**Comment by connor4312** [comment]
Vue behavior should be improved in https://github.com/microsoft/vscode-js-debug/commit/2f3c93a08df0ceb09eda86251d0309d34bfb26ef

**Comment by qiulang** [comment]
@roblourens @connor4312 I just found my issue was closed but what did this mean exactly ?
Did you mean this was a vue bug so you can't fix it ?

**Comment by connor4312** [comment]
Vue produces odd sourcemaps that have long been a problem in both the old and new debug adapters. I pushed a fix that should improve behavior. You can [try out the nightly extension](https://github.com/microsoft/vscode-js-debug#nightly-extension) and see if you still have this issue.

**Comment by J-Rojas** [comment]
I've tried the new preview debugger and it does not work for my Vue files, only my JS files.
