### ISSUE TITLE
Preview the location of breakpoints while picking them in termination conditions

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#518]
https://github.com/microsoft/vscode/issues/96473#issuecomment-638510505

>A "go to symbol in file"-like experience for this seems fitting. Where moving through the list moves through the editor as well and the quick pick could be filterable by line contents.
![image](https://user-images.githubusercontent.com/8586769/83698264-db972200-a5b5-11ea-809e-66d1838e38d2.png)
>
>
>![image](https://user-images.githubusercontent.com/8586769/83698048-4f84fa80-a5b5-11ea-9e79-eadfea9ae08b.png)

**Comment by roblourens** [comment]
The quick pick is not actually filterable by the line contents. I think you can set `matchOnDescription` to do that.

**Comment by connor4312** [comment]
cool, added!
