### ISSUE TITLE
Refresh restartPolicy after succesful launch

### ISSUE THREAD

**Issue by trubit** [microsoft/vscode-js-debug#522]
After successful restart, we should recreate restartPolicy, so it starts to count from zero again.

For example:
```javascript
{
   "timeout": 0,
   "restart": {
      "static": {
          "maxAttempts": 5,
          "delay": 500
      }
   },
}
```

Will successfully reconnect to debug target 5 times, but after that stops and disconnect.
The config is `maxAttempts` (for restart), not `maxRestarts`.

With current behavior, I can't keep reconnecting to apps, built with angular cli (ng/nx serve).

To fix this, we should create new restart policy after successfull atempt.
So instead of passing existing (maybe already "exhausted" restartpolicy) we should pass new
https://github.com/microsoft/vscode-js-debug/blob/1acdf74e0502933a2602c393457725a4667d6ff5/src/targets/node/nodeAttacher.ts#L83

Should be:
```javascript
const newRestartPolicy = this.restarters.create(runData.params.restart);
program.stopped.then(r => restart(newRestartPolicy, program, r));
```

I tested this issue with node target, but this may affect other targets too.

**Comment by trubit** [comment]
On second thought this could be solved generally by adding `reset` method to `IRestartPolicy` and calling it after successful launch.

**Comment by connor4312** [comment]
Thanks, fixed in https://github.com/microsoft/vscode-js-debug/commit/2f2b1d4c58c85fea0aa53fc191730e9aab17511f

**Comment by roblourens** [comment]
Am I doing this right? Attach to a node process with this config, then kill the process. It doesn't seem to respect the configuration

![image](https://user-images.githubusercontent.com/323878/86399418-17c4ad80-bc5c-11ea-8760-df5a0a3d257d.png)

**Comment by connor4312** [comment]
The restart options are simpler now -- don't nested the object, just have `restart: { maxAttempts: 1, delay: 500 }`
