### ISSUE TITLE
support the `noDebug` flag

### ISSUE THREAD

**Issue by captainsafia** [microsoft/vscode-js-debug#523]
This issue occurs when debugging a Blazor WASM application using vscode-js-debug.

When executing `Start without Debugging`, the `noDebug` property is set in the launching configuration for the debug session.

![Screen Shot 2020-06-12 at 5 21 56 PM](https://user-images.githubusercontent.com/1857993/84555348-3aa11900-acd1-11ea-9268-992aacdde45b.png)

However, the browser launches with debugging enabled (e.g. you can set breakpoints and it makes requests to our DebugProxy.)

Note: This happens with Chrome. I'll see if Edge has the same issue.

**Comment by connor4312** [comment]
It does; js-debug does not actually respect the noDebug flag yet

**Comment by captainsafia** [comment]
Got it -- thanks for the quick response.

**Comment by isidorn** [comment]
@connor4312 I see there is already an issue for `noDebug` support so I will not create an additional one.

**Comment by connor4312** [comment]
I'm not sure if there's a "specification" for how noDebug is supposed to work. In the commit I have just skipped enabling the debugger, runtime, and network domains on the target. This means users will still see the sessions tree on the left hand side, but won't hit breakpoints or be able to use the REPL.

**Comment by weinand** [comment]
@connor4312 the DAP spec is not very precise on `noDebug`:
> If noDebug is true the launch request should launch the program without enabling debugging.

So what you are doing for js-debug makes perfect sense.
