### ISSUE TITLE
`workspaceFolder` causes error in multi-root workspace configuration

### ISSUE THREAD

**Issue by FicoPrieto** [microsoft/vscode-js-debug#525]
When attempting to run a debug task that makes use of the `workspaceFolder` variable, I receive the following error message:

![Code_2020-06-13_07-49-20](https://user-images.githubusercontent.com/22942079/84568074-f8b4b900-ad4a-11ea-8ec2-697cca548d25.png)

This error should not be thrown, because I am already using a scoped `workspaceFolder` variable, as shown in the `configurations.Debug.cwd` parameter of my configuration below.
&nbsp;  

-----

&nbsp;  
With `{"debug.javascript.usePreview": true}`, my `Chrome` task works, but my `Debug` task throws the error shown above.

With `{"debug.javascript.usePreview": false}`, my `Debug` task works, but my `Chrome` task exhibits the issues described in #516.
&nbsp;  

-----

&nbsp;  
### Workspace Configuration
```json
"launch": {
  "version": "0.2.0",
  "configurations": [

    {
      "name":"Debug", "type":"node", "request":"launch",

      "cwd":                    "${workspaceFolder:Root}",
      "outputCapture":          "std",
      "internalConsoleOptions": "openOnSessionStart",

      "runtimeArgs": [
        "--nolazy",
        "--inspect",
        "--require", "ts-node/register",
      ],
      "args": [
        "./__Source__/__Debug__.ts",
      ],
      "skipFiles": [
        "<node_internals>/**/*.js",
        "**/node_modules/**/*",
      ],
    },
    
    {
      "name":"Chrome", "type":"chrome", "request":"launch",

      "url":                    "http://localhost:8080",
      "internalConsoleOptions": "openOnSessionStart",
    },

  ],
},
```

**Comment by connor4312** [comment]
Thanks for the good issue!

**Comment by FicoPrieto** [comment]
@connor4312 

Is the fix live? Just tried on version 2020.8.517 and am still experiencing the issue.

**Comment by connor4312** [comment]
Please set your `type` to `pwa-node`

**Comment by FicoPrieto** [comment]
@connor4312 

That worked, thanks!
