### ISSUE TITLE
pwa-node truncates the repl result for strings

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode-js-debug#526]
My [debug visualizer extension](https://github.com/hediet/vscode-debug-visualizer/blob/master/extension/README.md) does not work anymore with `pwa-node`, since long strings are truncated (and thus cannot be parsed anymore).

Is there a way to disable truncation of long strings?

![image](https://user-images.githubusercontent.com/2931520/84699758-63841100-af52-11ea-87fd-4a28b45aecc1.png)

**Comment by hediet** [comment]
Nevermind, the `copy` context does what I want.
I was under the assumption that there was only `repl` and `watch`.

**Comment by connor4312** [comment]
We also now bumped it to 100k characters (in case anyone else lands on this issue). But yes it sounds like the `clipboard` context will do what you want.
