### ISSUE TITLE
Automatically remove query strings from resolved absolute paths

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#529]
@jasonwilliams reported Next.js has (started?) adding these. `?` is an illegal character path on windows so I do not thing that removing the query string would break anything.

**Comment by jasonwilliams** [comment]
I was doing some digging, it looks like it's coming from Webpack itself and not next.
I found this comment from 2015 which describes the same thing:
https://github.com/webpack/webpack/issues/740#issuecomment-141182259

And next is using eval-source-map:
https://github.com/vercel/next.js/blob/90638c70010310ba19aa0f28847b6226fdd20339/packages/next/build/webpack/config/blocks/base.ts#L32
