### ISSUE TITLE
Nightly finishs immediately

### ISSUE THREAD

**Issue by jeffrson** [microsoft/vscode-js-debug#535]
I have a project, where the nightly from insider immediately finishs. Is there any log file I can check?

Here's the output (which looks slightly broken, btw - everytime a bit different):

```
Debugger listening on ws://127.0.0.1:52658/f807c49e-39fc-4d45-8724-c8e174d122da
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Waiting for the debugger to disconnect...
Debugger listeningDebugger listening on ws://127.0.0.1:52662/536971a2-6600-4fa5-b93b-554935922b90
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

> package@version debug project_workspace_folder
> node --nolazy --inspect-brk=15112 server/startup

DebuggeDebugger listening on ws://127.0.0.1:15112/6094a050-e58a-4ca0-8dc0-b553a290304c
For help, see: https://nodejs.org/en/docs/inspector
```

VSCode: 1.47.0-insider
Debugger: v2020.6.1817
No extension, but the builtin.

The "old" debugger ("debug.javascript.usePreview": false) works.

**Comment by connor4312** [comment]
Can you share your launch configuration?

**Comment by jeffrson** [comment]
Sure. Here it is:

```
  {
            "console": "integratedTerminal",
            "disableOptimisticBPs": true,
            "envFile": "${workspaceFolder}/.vscode/.env",
            "name": "Debug",
            "port": 15112,
            "protocol": "inspector",
            "request": "launch",
            "runtimeArgs": ["run-script", "debug"],
            "runtimeExecutable": "npm",
            "skipFiles": ["<node_internals>/**/*.js"],
            "smartStep": true,
            "sourceMaps": true,
            "type": "node"
}
```

**Comment by connor4312** [comment]
Unfortunately this scenario will not work, see https://github.com/microsoft/vscode/issues/99526#issuecomment-640771550

You can instead adjust your launch configuration to:

```
{
  "console": "integratedTerminal",
  "disableOptimisticBPs": true,
  "envFile": "${workspaceFolder}/.vscode/.env",
  "name": "Debug",
  "request": "launch",
  "stopOnEntry": true,
  "program": "${workspaceFolder}/server/startup",
  "skipFiles": ["<node_internals>/**/*.js"],
  "type": "node"
}
```

**Comment by connor4312** [comment]
Hi, following up on this issue after feedback from you and other users. There are two things to know:

1. If you don't need to debug on the first line of your program, it's actually safe to just remove `--inspect-brk` from your npm scripts with the new debugger. Previously, it was useful to prevent your program from running before VS Code could attach to it, but this is no longer necessary.

1. We've added some change to gracefully fall back (with a warning) when running a program with --inspect-brk in the config. This flag prevents us from being able to attach to children and unlock some additional new functionality, but it should work. This change will be available in the recovery release coming next week, and is available on our [nightly extension](https://github.com/microsoft/vscode-js-debug/#nightly-extension).

Happy Coding!
