### ISSUE TITLE
Reconcile breakpoint locations for files modified locally

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#538]
Options:

 - Unverify/disable breakpoints when a file is edited
 - Some kind of reconciliation logic to shift breakpoints to their correct locations
 - Other?

**Comment by connor4312** [comment]
I was working on a Go project the other day and noticed that their approach to this is to show a notification when you edit a file with breakpoint set. This gets the message across but I don't like how intrusive it is.

@roblourens have you done any thinking on this in the past?

**Comment by roblourens** [comment]
I think it's hard to improve when you consider things like host module reloading, you don't really know the relationship between the state of the file in vscode and the loaded code.
