### ISSUE TITLE
[ms-vscode.js-debug-nightly]: Cannot register multiple views with same id `jsBrowserBreakpoints`

### ISSUE THREAD

**Issue by jerryasher** [microsoft/vscode-js-debug#544]
I have `JavaScript Debugger (Nightly)` installed into `WSL:Ubuntu` and I regularly see an error popup in the lower left corner

> [ms-vscode.js-debug-nightly]: Cannot register multiple views with same id `jsBrowserBreakpoints`

This is distressing for several reasons, not the least of which I don't know how severe this message is. Ignore? Uninstall? What do I do with this message?

```
Version: 1.46.1 (user setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
```

**Comment by connor4312** [comment]
Please follow steps 1 and 2 here to fix this: https://github.com/microsoft/vscode-js-debug#nightly-extension

Thanks for filing an issue!
