### ISSUE TITLE
Web-page hits a breakpoint but VS Code doesn't show it

### ISSUE THREAD

**Issue by digeff** [microsoft/vscode-js-debug#546]
On the VS react and redux default template set a breakpoint on:
App.tsx: Line 10
Counter.tsx: Lines 12 and 14

           "webRoot": "${workspaceFolder}/ClientApp",

Load webpage, click to go to counter page, and the web-page is stuck and VS Code doesn't show the breakpoint pause.

In the logs I see a Debugger.paused message from chrome but no Debugger.resume, and no message to the client telling it about the pause

![image](https://user-images.githubusercontent.com/14098140/86057354-e5c10a80-ba13-11ea-94c9-2f80f3c5c32e.png)

[vscode-debugadapter-0 - Copy.zip](https://github.com/microsoft/vscode-js-debug/files/4848099/vscode-debugadapter-0.-.Copy.zip)

When that happens if I open chrome dev tools I see:
![image](https://user-images.githubusercontent.com/14098140/86057489-1e60e400-ba14-11ea-9f58-4d9112b0bb23.png)

**Comment by connor4312** [comment]
I don't hit this locally. The log says you're still on v1.46.1, can you try in a recent build? If it still reproduces, are you able to debug through to see where it stops?

Code pointer: https://github.com/microsoft/vscode-js-debug/blob/5fb58315f04352b4482f9bc828666ac76d8daa3a/src/adapter/threads.ts#L590

**Comment by connor4312** [comment]
Reading through code the thing I'm suspicious of is the smart stepper. Can you set `smartStep: false` to see if that fixes it?

**Comment by connor4312** [comment]
followup in chat: this should be fixed by https://github.com/microsoft/vscode-js-debug/pull/547

**Comment by digeff** [comment]
This only seems to happen while launching the debug adapter with the debugServer configuration in VS Code. I'm not sure if we want to fix it or not.
