### ISSUE TITLE
js-debug release plan

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#548]
In the May Insiders:

- js debug is default via the `debug.javascript.usePreview` flag on **Insiders**
- it can be opted out of by setting `debug.javascript.usePreview: false`

In the June release:

- js debug is default via the `debug.javascript.usePreview` flag on **all qualities**
- it can be opted out of by setting `debug.javascript.usePreview: false`

In the July release: (tentative)

- js-debug will take ownership of the node/chrome/extensionHost debug types, and the previous debug adapters will be removed.

**Comment by Bnaya** [comment]
I'm not sure if that's the place, but i'm getting very not optimal DX with the new debugger

Few examples:
When I open new terminal tab, it get stuck on :
![Screen Shot 2020-07-19 at 11 29 18](https://user-images.githubusercontent.com/1304862/87870741-9d15c500-c9b3-11ea-93f9-ab528871aba4.png)

I need to click CTRL + C to cancel it.

And then, when i run **any** thing with node in the terminal (for example yarn install)
it tries to debug it, recursively. slowing down and make stuff stuck.

My auto attach is off
I've tried to opt-out using "debug.javascript.usePreview", in both user and project level, with no avail
```
  "debug.javascript.usePreview": false
```

Restarting vscode didn't help

Related env vars:
```
NODE_OPTIONS=--require "/Users/bnaya/Library/Application Support/Code/User/workspaceStorage/52775f5c00279668c3aa87c7a6beab15/ms-vscode.js-debug/bootloader.js" 
VSCODE_INSPECTOR_OPTIONS=:::{"inspectorIpc":"/var/folders/q3/nzk7qrhs623_pqfkz7ms054c0000gn/T/node-cdp.94555-1.sock.deferred","deferredMode":true,"waitForDebugger":"","execPath":"/Users/bnaya/.nvm/versions/node/v12.18.2/bin/node","onlyEntrypoint":false}
```

My system info:
```
Version: 1.47.2
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:18:50.054Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
```

**Comment by connor4312** [comment]
This is fixed as of https://github.com/microsoft/vscode/issues/102057#issuecomment-657728467 -- you can correct it by setting auto attach to 'disabled', and then back on

**Comment by koxu1996** [comment]
Is it released?

**Comment by connor4312** [comment]
This is released but the old extensions will be removed later (we will probably announce deprecation and removal early next year)
