### ISSUE TITLE
Stopping debug doesn't kill Code-OSS

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#554]
- Start the "Launch VS Code" config
- Click stop button
- The OSS window is closed but the app is still running

![image](https://user-images.githubusercontent.com/323878/86396023-12646480-bc56-11ea-8b32-b778e76ef0ff.png)

**Comment by connor4312** [comment]
Fixed the setting but also changed the default following some user reports https://github.com/microsoft/vscode-js-debug/issues/555
