### ISSUE TITLE
Disconnect needs two clicks 

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-js-debug#557]
Version: 1.47.0-insider (user setup)
Commit: 04545fa88043fd10d1f3edefd26be1b8245b516f
Date: 2020-07-02T05:48:37.715Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Have the following launch config:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "pwa-msedge",
            "request": "attach",
            "port": 9222,
            "name": "Attach Edge",
            "targetSelection": "pick",
            "trace": true,
            "urlFilter": "*",
            "webRoot": "${workspaceFolder}"
        }
    ]
}
```
- Run Edge with `"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --remote-debugging-port=9222`
- open `www.spiegel.de`
- run the launch config, pick the page, see that the Call Stack view gets pupullated
- nagvigate on the page, see that the Call Stack has nodes added
- click on the disconnect button on  the `Attach Edge` node in the call stack view
- the`Attach Edge` node is still there

Also tried with ms-vscode.js-debug-nightly v2020.7.117.

![recording (4)](https://user-images.githubusercontent.com/6461412/86374021-6128f300-bc84-11ea-9ae1-1682d8e60951.gif)

**Comment by connor4312** [comment]
Man, that's an ugly call stack!

Thanks for the issue. This is an artifact of compact sessions, I think I was just not able to reproduce it at the time since there were a couple in-flight changes in compaction, but I can do so easily for now.
