### ISSUE TITLE
Debugger statement not pausing/breaking when vscode-js-debug is enabled

### ISSUE THREAD

**Issue by rajsinghUSA** [microsoft/vscode-js-debug#560]
I'm trying to use [vscode-js-debug](https://github.com/microsoft/vscode-js-debug) but when I enable it, like this:
![image](https://user-images.githubusercontent.com/17286177/86835830-ad9c7600-c06a-11ea-9c46-3c32670f2660.png)

 then there's no pause/break at my `debugger;` statement anymore, regardless of whether I run the server with `npm start` or `npm run debug`:
```js
    "start": "node ./server.js",
    "debug": "DEBUG='knex:*' nodemon --inspect ./server.js",
```

If I turn off the **vscode-js-debug** preview, then `npm run debug` works as expected, by pausing/breaking at `debugger;` statements in my code.

What might I be doing wrong?

**Comment by connor4312** [comment]
Can you please collect a trace log using these instructions?

> If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by rajsinghUSA** [comment]
After restarting VSCode, it is now pausing/breaking at the `debugger;` statements again, as expected. However, adding `"trace": true` to my `launch.json` did not log/print any file location to the Terminal or Debug Console.

However, `await subscription.$relatedQuery("discounts")` is returning `Promise {<pending>}`, which I thought the **vscode-js-debug** feature is supposed to resolve so I can get the actual awaited output?

**Comment by connor4312** [comment]
If you use await while paused at a breakpoint, we cannot resolve the promise because the event loop is paused.

If you run into the debugger issue again, please share your launch configuration. Perhaps you put the trace property in the wrong place.

**Comment by rajsinghUSA** [comment]
this is my `launch.json`:
```js
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "attach",
      "name": "Node: Nodemon",
      "processId": "${command:PickProcess}",
      "restart": true,
      "protocol": "inspector",
      "address": "localhost",
      // "port": 9229,
      // "sourceMaps": true,
      "localRoot": "${workspaceFolder}",
      "remoteRoot": "${workspaceFolder}",
      "trace": true
    }
  ]
}
```

In terms of resolving the promise, is there any way around this? Otherwise how do people usually tinker with `async` methods at the debugger console?

**Comment by connor4312** [comment]
> In terms of resolving the promise, is there any way around this? Also, what's the point of awaiting at a paused breakpoint if the promise can't be resolved because event loop is paused?

There's no way around this. V8 can't advance the event loop while also being paused on a line of code, as convenient as that would be.

> Otherwise how do people usually tinker with async methods at the debugger console? 

If paused at a location, I usually use the old fashioned `.then` and `catches` on a promise. You can use console.logs or `debugger;` statements within those blocks to look at its output.
