### ISSUE TITLE
Debugging fails on Windows with utf-8 characters in file path

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#563]
As reported:

```
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'c:/Users/Jo�o Silva/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js'
```

**Comment by vvFiCKvv** [comment]
`internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '"/snap/code/36/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js"'`

it seems it isn't a utf-8 problem.
the fie bootloader.bundle.js exists in the given location...

**Comment by connor4312** [comment]
@vvFiCKvv you're hitting a version of https://github.com/microsoft/vscode/issues/102035#issuecomment-656801666. The resolution steps in the comment will work for you (just ignore the electron part of it)

**Comment by connor4312** [comment]
This is an issue in Node.js, see https://github.com/nodejs/node/issues/34399.

For now, you can get around this by passing `--inspect-brk` manually in the `runtimeArgs` property and using `attachSimplePort`. You miss out on some functionality, but it will unblock you.

Example launch.json:

```
{
  "type": "pwa-node",
  "request": "launch",
  "name": "Launch program",
  "runtimeArgs": ["--inspect"],
  "attachSimplePort": 9229,
  "program": "${workspaceFolder}/main.js",
},
```

**Comment by NikitaBelevich** [comment]
> This is an issue in Node.js, see [nodejs/node#34399](https://github.com/nodejs/node/issues/34399).
> 
> For now, you can get around this by using `attachSimplePort` **with the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension)**. You miss out on some functionality, but it will unblock you.
> 
> Example launch.json:
> 
> ```
> {
>   "type": "pwa-node",
>   "request": "launch",
>   "name": "Launch program",
>   "attachSimplePort": 0,
>   "program": "${workspaceFolder}/main.js",
> },
> ```

I had the same issue, this option of the launch.json helped out me. Thank you very much :)

![image](https://user-images.githubusercontent.com/62552973/111065284-f3e38800-84c9-11eb-965c-eaca73f2dfc2.png)
