### ISSUE TITLE
npm run debug not working with option --inspect-brk=9229

### ISSUE THREAD

**Issue by zhmq0124v** [microsoft/vscode-js-debug#564]
Hello,

VSC upgraded itself automatically today, after the upgrade one of my debugging configurations does not work.
In package.json, debug is defined as `"debug": "node --nolazy **--inspect-brk=9229** index.js"`
In launch.json
`"runtimeExecutable": "npm",
    "runtimeArgs": [
        "run-script", "debug"
    ],
    "port": 9229`

**Describe the bug**
VSC could not start index.js at all. If I replace **--inspect-brk=9229** with **--inspect**, it works.

**VS Code Version:**
Version: 1.47.0 (user setup)
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:02:06.629Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by connor4312** [comment]
Thanks for filing an issue! Please check out this issue: https://github.com/microsoft/vscode/issues/99526#issuecomment-640771550

**Comment by connor4312** [comment]
Hi, following up on this issue after feedback from you and other users. There are two things to know:

1. If you don't need to debug on the first line of your program, it's actually safe to just remove `--inspect-brk` from your npm scripts with the new debugger. Previously, it was useful to prevent your program from running before VS Code could attach to it, but this is no longer necessary.

1. We've added some change to gracefully fall back (with a warning) when running a program with --inspect-brk in the config. This flag prevents us from being able to attach to children and unlock some additional new functionality, but it should work. This change will be available in the recovery release coming next week, and is available on our [nightly extension](https://github.com/microsoft/vscode-js-debug/#nightly-extension).

Happy Coding!
