### ISSUE TITLE
SkipFiles does not work in Chrome attach mode

### ISSUE THREAD

**Issue by egorshulga** [microsoft/vscode-js-debug#565]
**Describe the bug**
The same skipFiles configuration, which works in launch mode, does not work in attach mode.

**To Reproduce**
1. Create following configurations:
```
    {
      "name": "Chrome",
      "type": "pwa-chrome",
      "request": "launch",
      "url": "http://localhost:1234",
      "skipFiles": [
        "${workspaceRoot}/node_modules/**/*.js",
      ],
      "trace": true
    },
    {
      "type": "pwa-chrome",
      "request": "attach",
      "name": "Attach to Chrome",
      "port": 9222,
      "skipFiles": [
        "${workspaceRoot}/node_modules/**/*.js",
      ],
      "trace": true
    },
```
2. Run Attach to Chrome configuration.

Actual result: node_modules are not skipped
![image](https://user-images.githubusercontent.com/6253488/87130758-10288880-c29c-11ea-9c50-9aa2b8fbda58.png)

Expected result (as in launch Chrome configuration above)
![image](https://user-images.githubusercontent.com/6253488/87130954-5d0c5f00-c29c-11ea-8f09-18dae138b56d.png)

**Log File**

From Attach to Chrome: https://drive.google.com/file/d/1x42XTf8bXffw8Mo_JzTQYrEAVWLHBEh1/view?usp=sharing

From launch Chrome: https://drive.google.com/file/d/1B3DawKmbpmzaypoOOx4PpavaO1TOcXUG/view?usp=sharing

**VS Code Version:** Version: 1.47.0 (system setup)
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:02:06.629Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by connor4312** [comment]
Good issue, thanks! Will look into this next week.

**Comment by jasonwilliams** [comment]
@egorshulga have you tried with `${workspaceFolder}` instead of `${workspaceRoot}` ?

**Comment by egorshulga** [comment]
<details>
<summary>With ${workspaceFolder}</summary>

Run Chrome (does not work)
![image](https://user-images.githubusercontent.com/6253488/87558970-5e85bf00-c6c2-11ea-994f-798581de15ba.png)

Attach to Chrome (does not work either)
![image](https://user-images.githubusercontent.com/6253488/87559059-7b21f700-c6c2-11ea-9839-7119aa4472b0.png)
</details>

<details>
<summary>With `**/node_modules/**/*.js`</summary>

Run Chrome (does not work)
![image](https://user-images.githubusercontent.com/6253488/87559274-c0debf80-c6c2-11ea-8dbe-06df105dce0c.png)

Attach to Chrome (does not work either)
![image](https://user-images.githubusercontent.com/6253488/87559350-da800700-c6c2-11ea-8868-9e8601d37110.png)
</details>

Would it be helpful if I paste extension logs as well?

**Comment by connor4312** [comment]
I'll be looking at this today -- it looks like I'll be able to reproduce this locally easily enough, but I'll let you know if I need more info.

**Comment by connor4312** [comment]
@egorshulga does this happen in the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension)? I'm wondering if you're hitting the same issue that Mike hit in https://github.com/microsoft/vscode/issues/102412#issuecomment-658301904

**Comment by egorshulga** [comment]
@connor4312 Yes, it works! That's so cool there is nothing to fix, as it has been already fixed :grin:
When we can expect for this fix to be released as stable?

**Comment by connor4312** [comment]
Good to hear!

Because that was a less common and relatively minor issue (+ also involving a refactoring which carries some danger) I do not intend to ship that in a June recovery release. So this won't go out to VS Code stable users until the July release, in early August. It will be on [Insiders](https://code.visualstudio.com/insiders/) earlier, probably starting tomorrow.

**Comment by quantuminformation** [comment]
Any way to add this to all chrome instances? Normally I just open chrome debugger via open windows.
