### ISSUE TITLE
Support auto attach only if --inspect is given

### ISSUE THREAD

**Issue by Juarrow** [microsoft/vscode-js-debug#566]
I did just update VSCode to 1.47.
What i later found out from the Release Notes was, that there now is this new JS debugger (which links here - that's why i post this here. If it belongs into the VSCode main repo, i'll glady post it there) ).

I found this out, because after the update i ran a simple command line tool within the VSCode terminal which (because it is run with node.js - namely the ionic cli) made the debugger attach to it without me changing any settings.

I got confused and it took me some time to figure, that there is an "auto attach"-setting which seems to be turned on by default with this update.

How about disabling this by default!?

**Comment by lechip** [comment]
I agree with this. Had an issue where I just ran a git command on the terminal (the git command activates a precommit script) and the debugger got attached to the precommit script. This is definitely not something I want.

**Comment by mledom** [comment]
Yes, every command I run in the terminal is attaching to the debugger. None of the commands are inspecting the node process. Is there an option to disable that but still allow Auto Attach to work with processes that we are inspecting with --inspect?

**Comment by connor4312** [comment]
Thanks for the issue, please see: https://github.com/microsoft/vscode/issues/102057

Currently we don't have an "auto attach only with --inspect", but that's a good idea.

**Comment by connor4312** [comment]
Added in the [latest nightly](https://github.com/microsoft/vscode-js-debug#nightly-extension)

![](https://memes.peet.io/img/20-07-18e19815-6696-4ac8-bcf9-19c49a814000.png)
