### ISSUE TITLE
js-debug doesn't activate breakpoints set before attaching [Cordova]

### ISSUE THREAD

**Issue by RedMickey** [microsoft/vscode-js-debug#568]
Hello, this is [Cordova Tools](https://github.com/microsoft/vscode-cordova) team. While adapting debugging of pure Cordova apps to `js-debug` we faced the problem that if we set a breakpoint before attaching, it won't be activated after an attachment, but if we set a breakpoint after an attachment, it will be activated correctly. We tried to debug the `js-debug` extension and noticed that sometimes `js-debug` could activate a breakpoint set before attaching properly. It happened in such cases when we set a lot of breakpoints in all the logic of handling of `Debugger.scriptParsed` events and adding a new source (e.g. functions: [`_onScriptParsed`](https://github.com/microsoft/vscode-js-debug/blob/f52fbc2fbca6486cb5ac6b3b17e5838a2323b2f8/src/adapter/threads.ts#L1182-L1261), [`_addSource`](https://github.com/microsoft/vscode-js-debug/blob/46bc6a6654390d75529ee0ffce4b7a051e7cc82c/src/adapter/sources.ts#L743-L864), [`addSource`](https://github.com/microsoft/vscode-js-debug/blob/46bc6a6654390d75529ee0ffce4b7a051e7cc82c/src/adapter/sources.ts#L710-L741), [`urlToAbsolutePath`](https://github.com/microsoft/vscode-js-debug/blob/2f3c93a08df0ceb09eda86251d0309d34bfb26ef/src/targets/browser/browserPathResolver.ts#L69-L78), [`simpleUrlToAbsolute`](https://github.com/microsoft/vscode-js-debug/blob/2f3c93a08df0ceb09eda86251d0309d34bfb26ef/src/targets/browser/browserPathResolver.ts#L80-L127) and some other inner functions). So, when we stop on breakpoints, we give the debugger enough time to handle all `Debugger.scriptParsed` events before sending `Debugger.setBreakpointByUrl` events to the target.
- Cordova source paths features
A Cordova app's sources are located on the device side and they have such URLs: 
```
file:///android_asset/www/cordova.js
file:///android_asset/www/js/index.js
```
However, by default `js-debug` tries to get sources form the local machine file system.
- Our view of the problem's reason
During the debugging we found out that at first `js-debug` sends `Debugger.setBreakpointByUrl` requests with local machine file system paths:
```
{
  "id": 18,
  "method": "Debugger.setBreakpointByUrl",
  "params": {
    "urlRegex": "[fF][iI][lL][eE]:\\/\\/\\/[gG]:\\/[wW][oO][rR][kK]\\/[cC][oO][rR][dD][oO][vV][aA]\\/[cC][oO][rR][dD][oO][vV][aA]_[aA][pP][pP]\\/[wW][wW][wW]\\/[jJ][sS]\\/[iI][nN][dD][eE][xX]\\.[jJ][sS]|[gG]:\\\\[wW][oO][rR][kK]\\\\[cC][oO][rR][dD][oO][vV][aA]\\\\[cC][oO][rR][dD][oO][vV][aA]_[aA][pP][pP]\\\\[wW][wW][wW]\\\\[jJ][sS]\\\\[iI][nN][dD][eE][xX]\\.[jJ][sS]",
    "lineNumber": 0,
    "columnNumber": 0
  },
  "sessionId": "D339334918E93465E788A8656B796976"
}
```
This is the wrong urlRegex.
But, when we set a breakpoint after an attachment, we get the correct urlRegex.
```
{
  "id": 23,
  "method": "Debugger.setBreakpointByUrl",
  "params": {
    "urlRegex": "[fF][iI][lL][eE]:\\/\\/\\/[aA][nN][dD][rR][oO][iI][dD]_[aA][sS][sS][eE][tT]\\/[wW][wW][wW]\\/[jJ][sS]\\/[iI][nN][dD][eE][xX]\\.[jJ][sS]|\\/[aA][nN][dD][rR][oO][iI][dD]_[aA][sS][sS][eE][tT]\\/[wW][wW][wW]\\/[jJ][sS]\\/[iI][nN][dD][eE][xX]\\.[jJ][sS]",
    "lineNumber": 34,
    "columnNumber": 0
  },
  "sessionId": "D339334918E93465E788A8656B796976"
}
```

It seems that `js-debug` doesn't have enough time to process all the `Debugger.scriptParsed` events, which contain correct URLs:
```
{
  "method": "Debugger.scriptParsed",
  "params": {
    "scriptId": "16",
    "url": "file:///android_asset/www/js/index.js",
    "startLine": 0,
    "startColumn": 0,
    "endLine": 54,
    "endColumn": 17,
    "executionContextId": 1,
    "hash": "263fbd6608d6874a29e0fd8a7500e40e78c37cce",
    "executionContextAuxData": {
      "isDefault": true,
      "frameId": "043591E6E80BA3B6B4B3A4FD8E433A7E"
    },
    "isLiveEdit": false,
    "sourceMapURL": "",
    "hasSourceURL": false,
    "isModule": false,
    "length": 1926
  },
  "sessionId": "D339334918E93465E788A8656B796976"
}
```
We think that on attaching `js-debug` sends `Debugger.setBreakpointByUrl` requests without waiting for the processing of all `Debugger.scriptParsed` events. So it sends only default generated machine file system paths.

We'll tell you the way to reproduce this problem if needed.

I attach log files:
 - [CDP logs for a breakpoint set before attaching](https://github.com/microsoft/vscode-js-debug/files/4902959/logCor7816.txt)
 - [CDP logs for a breakpoint set after attaching](https://github.com/microsoft/vscode-js-debug/files/4902968/logCor8386.txt)
 - [js-debug logs](https://github.com/microsoft/vscode-js-debug/files/4902975/vscode-debugadapter-0.json.gz)

VS code version: 1.47.0
js-debug version: the latest commit 94f88a35328819f7c3d07d7e417c7a4db33e4c35

cc @EricCornelson

**Comment by RedMickey** [comment]
We tested how it works on macOS and didn't face such problem with breakpoints activation. So, the problem with breakpoints activation exists only on Windows. 
We adapted `js-debug` to debugging Cordova and Ionic apps in the PR https://github.com/microsoft/vscode-cordova/pull/634.

**Comment by connor4312** [comment]
Sorry for the delay, I had thought this was a dupe of https://github.com/microsoft/vscode-js-debug/issues/647 so didn't initially look at it.

This is because of some behavior I coincidentally just looked at in https://github.com/microsoft/vscode-js-debug/commit/e4c5f681f367751f80954eced92af1be319fa46c, which will actually break your scenario more. The change I made adjusts our behavior to always use the statically generated paths rather than the URLs of any resolved sources, since doing so is more correct and there _should_ be no difference between them.

I think the fix for you, simulating your setup the best I can, is to make the following two changes:

1. Set the `url` in attachment to `file:///`. This is just needed to activate some extra mapping behavior
1. Add `pathMapping: { '/android_asset/www': 'G:\\work\\cordova\\cordova_app\\www', }`. This will resolve assets in that subpath to the directory, and vise versa

Let me know how this works for you

**Comment by RedMickey** [comment]
Hi @connor4312, I tried to change our debug configuration the following way:
```
        {
            "name": "Attach to Chrome",
            "port": 8999,
            "request": "attach",
            "type": "pwa-chrome",
            "webRoot": "${workspaceFolder}/www",
            "pathMapping": {
                "/android_asset/www": "D:\\cordova\\cordova_app\\www", 
            },
            "sourceMapPathOverrides": {
                "webpack:///./~/*": "${cwd}/node_modules/*",
                "webpack:///./*": "${cwd}/*",
                "webpack:///*": "*",
                "webpack:///src/*": "${cwd}/*",
                "./*": "${cwd}/*"
            },
            "url": "file:///"
        }
```

In this case attachment freezes and we cannot attach to the app. According to the CDP logs, it seems that the debugger doesn't get all the targets as compared with the CDP logs without the `"url": "file:///"` parameter. If I remove the `url` parameter, I'll be able to debug the app, but the original issue with breakpoints remains.

I attach log files:
- [CDP logs](https://github.com/microsoft/vscode-js-debug/files/5156367/logCor6679.txt)
- [js-debug logs](https://github.com/microsoft/vscode-js-debug/files/5156361/vscode-debugadapter-0.json.gz)

**Comment by connor4312** [comment]
Try setting an additional option `"urlFilter": "*"`

**Comment by RedMickey** [comment]
Hi @connor4312, thank you for your help. The proposed solution works fine for us.
