### ISSUE TITLE
Debugger shows errors to debug console when fails to find sourcemaps for files

### ISSUE THREAD

**Issue by SounD120** [microsoft/vscode-js-debug#571]
**Describe the bug**
It looks like the debugger `scriptParsed` event throws an error each time when it cannot find sourcemaps for JS files from `node_modules`

**To Reproduce**
1. `git clone https://github.com/microsoft/vscode-react-native`
2. `cd vscode-react-native && npm install`
2. `code .`
3. Open debug tab and run `Launch All Smoke Tests` debug scenario
4. When debugger will attach (it may take some time) - you'll see a lot of failures connected to absence of source maps files for pure JS code
![image](https://user-images.githubusercontent.com/32372875/87169150-3a983700-c2d8-11ea-9939-f74fcf136ffa.png)

These errors seem to come from [here](https://github.com/microsoft/vscode-js-debug/blob/94f88a35328819f7c3d07d7e417c7a4db33e4c35/src/adapter/threads.ts#L1219).

**Log File**
[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode-js-debug/files/4903917/vscode-debugadapter-0.json.gz)

**VS Code Version:** 1.47.0

**Comment by connor4312** [comment]
This sounds like https://github.com/microsoft/vscode/issues/102042
