### ISSUE TITLE
Getting errors for packages without map file

### ISSUE THREAD

**Issue by ardymalihi** [microsoft/vscode-js-debug#572]
**Describe the bug**
Debugger listening on ws://127.0.0.1:49829/64048437-d258-42da-8303-cc959b970c65
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Could not read source map for file:///.../node_modules/@grpc/proto-loader/build/src/index.js: ENOENT: no such file or directory, open '/.../node_modules/@grpc/proto-loader/build/src/index.js.map'

Some third party packages have `//# sourceMappingURL=index.js.map` but cannot be found so as a result you will see lots of errors in the console.

The error makes sense because the map file should exist if sourceMappingURL is added at the end of js file but it hard to convince all the thirds party packages to include the map files to their projects :)

**To Reproduce**
1. install any packages without map ie: @grpc/proto-loader
2. import in your project file
3. run debug
4. See the error above ^^^^

**Log File**

Debugger listening on ws://127.0.0.1:49829/64048437-d258-42da-8303-cc959b970c65
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Could not read source map for file:///.../node_modules/@grpc/proto-loader/build/src/index.js: ENOENT: no such file or ...

**Comment by connor4312** [comment]
Thanks for the issue and good steps. This duplicates https://github.com/microsoft/vscode/issues/102042
