### ISSUE TITLE
Huge number of "Could not read source map for" from node_modules folder

### ISSUE THREAD

**Issue by samdoeswork** [microsoft/vscode-js-debug#574]
**Describe the bug**
With the new debugger I see a flood of notifications about npm modules without source maps

**To Reproduce**
Run a node/express app with the following configuration:
        {
            "type": "node",
            "request": "launch",
            "name": "Server",
            "cwd": "${workspaceFolder}",
            "program": "${workspaceFolder}/bin/www",
            "env": {"NODE_ENV": "development"},
            "port": 9229,
        },

**Log File**
Here's a sample:

Could not read source map for file:///c:/apps/jaf/node_modules/@google-cloud/firestore/build/src/validate.js: ENOENT: no such file or directory, open 'c:\apps\jaf\node_modules\@google-cloud\firestore\build\src\validate.js.map'
Could not read source map for file:///c:/apps/jaf/node_modules/@google-cloud/firestore/build/src/util.js: ENOENT: no such file or directory, open 'c:\apps\jaf\node_modules\@google-cloud\firestore\build\src\util.js.map'

**VS Code Version:** 1.47

**Comment by connor4312** [comment]
Thanks for the issue! This duplicates https://github.com/microsoft/vscode/issues/102042 -- see there for the solution.

**Comment by samdoeswork** [comment]
This resolution worked for me also, thanks!

[cid:image001.png@01D656E9.9E09CF20]<http://www.instant.marketing/>
Launching 2 new channels LIVE: Join the webinar - "Eloqua on TEN Channels" – 21st July
Sign up and more info<https://bit.ly/3edUl4j>

Please note: Just Add Features is now Instant Marketing ⚡
www.instant.marketing<http://www.instant.marketing/>
