### ISSUE TITLE
1.47 Breaks Node Launch config.

### ISSUE THREAD

**Issue by codyolsen** [microsoft/vscode-js-debug#575]
**Describe the bug**
1.47 VSCode update breaks existing launch.json file. Revert to 1.46.1 fixes behavior.

**To Reproduce**
- Upgrade to 1.47.
- Run debugger.
- Debugger errors, and does not run test suite.
- Stop debugger.
- Debug console outputs more errors.

**Launch File**
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Unit Tests",
      "runtimeExecutable": "yarn",
      "runtimeArgs": [
        "test:debug",
        "${file}"
      ],
      "port": 9229
    }
  ]
}
```
`yarn test:debug` = `node --inspect-brk node_modules/.bin/vue-cli-service test:unit --no-cache --watch --runInBand`

**Log File**
Unable to share

## 1.46.1 Debug Console Output:
```
/usr/local/bin/yarn test:debug /project/tests/unit/Common/util.spec.js 
Debugger listening on ws://127.0.0.1:9229/d7489cc6-1380-4e6d-83f0-234c4a179bea
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
PASS tests/unit/Common/util.spec.js

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        3.081s
Ran all test suites matching /projects\/tests\/unit\/Common\/util.spec.js/i.
```

## 1.47 Debug Console Output:

On Debugger Start:
```
/usr/local/bin/yarn test:debug /project/tests/unit/Common/util.spec.js 
Debugger listening on ws://127.0.0.1:50871/5c670668-a3fd-415e-8916-464c5ec09591
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Could not read source map for file:///usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js: ENOENT: no such file or directory, open '/usr/local/Cellar/yarn/1.22.4/libexec/lib/toSubscriber.js.map'
```
On Debugger Close: 
```
/usr/local/bin/yarn test:debug /project/tests/unit/Common/util.spec.js 
Debugger listening on ws://127.0.0.1:50871/5c670668-a3fd-415e-8916-464c5ec09591
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Could not read source map for file:///usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js: ENOENT: no such file or directory, open '/usr/local/Cellar/yarn/1.22.4/libexec/lib/toSubscriber.js.map'
Debugger listening on ws://127.0.0.1:9229/c2c93888-c78d-48e2-a094-01a55770152d
For help, see: https://nodejs.org/en/docs/inspector
Debugger listening on ws://127.0.0.1:50871/5c670668-a3fd-415e-8916-464c5ec09591
For help, see: https://nodejs.org/en/docs/inspector
Process exited with code null
```

^ It appears there is an outside wrap of another node inspector instance at port 50871.

**VS Code Version:** v1.47
**vscode-js-debug version:** v1.47.3

**Comment by connor4312** [comment]
Thanks for the issue! This is the same as https://github.com/microsoft/vscode/issues/99526#issuecomment-640771550.

Short version is that --inspect-brk when running inside node scripts is not impactible with our new debugger. Instead, you could add `stopOnEntry: true` in your launch config

**Comment by connor4312** [comment]
Hi, following up on this issue after feedback from you and other users. There are two things to know:

1. If you don't need to debug on the first line of your program, it's actually safe to just remove `--inspect-brk` from your npm scripts with the new debugger. Previously, it was useful to prevent your program from running before VS Code could attach to it, but this is no longer necessary.

1. We've added some change to gracefully fall back (with a warning) when running a program with --inspect-brk in the config. This flag prevents us from being able to attach to children and unlock some additional new functionality, but it should work. This change will be available in the recovery release coming next week, and is available on our [nightly extension](https://github.com/microsoft/vscode-js-debug/#nightly-extension).

Happy Coding!

**Comment by codyolsen** [comment]
Thanks @connor4312,
That seemed to do the trick.

**Comment by codyolsen** [comment]
I was mistaken. The new fallback mode doesn't seem to be working. We're unable to use the debugger with stopOnEntry or --inspect-brk with the nightly build. Only solution so far is to stay on 1.46

**Comment by connor4312** [comment]
Thanks for the followup. Are you running into the same problem as you were before? If so, can you share your current launch config and script entry if it changed?

**Comment by codyolsen** [comment]
Okay I think I worked it out. For some reason yarn was still failing. For now we are just using npm to run the scripts in the context of the vscode debugger. We also had to add "outputCapture" : "std". 

Anyone googling for help on vue-test-utils and vscode debugger here's the launch.json for now:

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Unit Tests",
      "runtimeExecutable": "npm",
      "outputCapture" : "std",
      "runtimeArgs": [
        "run-script",
        "test:debug",
        "${file}"
      ],
      "port": 9229
    }
  ]
}
```

package.json script entry:
`"test:debug": "node node_modules/.bin/vue-cli-service test:unit --no-cache --watch --runInBand"`
