### ISSUE TITLE
Can't run Extension of launch.json anymore

### ISSUE THREAD

**Issue by nfmelendez** [microsoft/vscode-js-debug#576]
**Describe the bug**
Can't run Extension of launch.json anymore, says  "Configured debug type 'pwa-extensionHost' is not supported." i guess is because VS code updated to 1.47.0.

**Comment by connor4312** [comment]
At some point did you disable the js-debug extension? (You can find it by searching `ms-vscode.js-debug` in the extensions view).

**Comment by nfmelendez** [comment]
Yes, that was the problem. did the opposite of:

1.- Open the extensions view (ctrl+shift+x) and search for @builtin @id:ms-vscode.js-debug
2.- Right click on the JavaScript Debugger extension and Disable it.

and worked perfectly! :) thanks

**Comment by nfmelendez** [comment]
Sorry didn't worked. i didn't see the error before.  i had to rollback to 1.46.  what happen to me is that in 1.47 with @Builtin @id:ms-vscode.js-debug enabled it does run "Extension" launch.json config for this vscode-js-debug extension but it conflicts the extension in development and the extension installed which are the same.

**Comment by connor4312** [comment]
If you also have js-debug-nightly, you will want exactly one of `js-debug` or `js-debug-nightly` enabled at a time.

**Comment by nfmelendez** [comment]
my error was to enabled it globally, so what works for me is:

1) js-debug-nightly -> disable
2) js-debug -> enable only in my workbench
3) then i run Extension of launch.json and will open another vscode [extension developer host] -> this one has js-debug disabled, that is why is important not to enable globally to make it work in my case
4) enjoy

**Comment by swrdfish** [comment]
I was trying to debug the `js-debug` extension, but in the extension developer host, it is picking up the builtin extension.
If I enable `js-debug` only in the workbench, then it is disabled in the extension host and nothing else is available.
Ideally there should be a different version of `js-debug` extension available in the extension development host. 

@connor4312 any ideas?

**Comment by swrdfish** [comment]
@connor4312 I tried doing that already, the thing is that I cannot set breakpoints, and the stack traces look like this
```
Error: Error parsing mappings (code 1): the mappings contained a negative line, column, source index, or name index
	at l._parseMappings (/Users/binayak/.vscode/extensions/ms-vscode.js-debug-nightly-2020.9.2817/src/extension.js:36:21296)
	at l._getMappingsPtr (/Users/binayak/.vscode/extensions/ms-vscode.js-debug-nightly-2020.9.2817/src/extension.js:36:20590)
	at /Users/binayak/.vscode/extensions/ms-vscode.js-debug-nightly-2020.9.2817/src/extension.js:36:24379
	at Object.withMappingCallback (/Users/binayak/.vscode/extensions/ms-vscode.js-debug-nightly-2020.9.2817/src/extension.js:36:30500)
	at l.generatedPositionFor (/Users/binayak/.vscode/extensions/ms-vscode.js-debug-nightly-2020.9.2817/src/extension.js:36:24300)
	at a.generatedPositionFor (/Users/binayak/.vscode/extensions/ms-vscode.js-debug-nightly-2020.9.2817/src/extension.js:15:2633614)
	at Object.getOptimalCompiledPosition (/Users/binayak/.vscode/extensions/ms-vscode.js-debug-nightly-2020.9.2817/src/extension.js:1:54161)
	at b.predictBreakpoints (/Users/binayak/.vscode/extensions/ms-vscode.js-debug-nightly-2020.9.2817/src/extension.js:15:2555663)
```
When I am debugging `js-debug`, I expect the stack trace to point to the location where the source code is present, even if sourcemaps are not resolved. This works fine for other extensions.

Btw, I installed the nightly extension using the following:
`@id:ms-vscode.js-debug-nightly`

P.S. Thanks for the quick response ! 😊
