### ISSUE TITLE
Can't hit Node.js Breakpoints

### ISSUE THREAD

**Issue by zakariaagha** [microsoft/vscode-js-debug#579]
**Describe the bug**
I have a Node.js application that I've been debugging using VSCode. Since I updated to 1.47, as soon as I launch my application in debug mode, my breakpoints turn grey and hollow and they don't get hit. If I hover them, it says "Unbound Breakpoint". The issue goes away when I revert to 1.46

I am also debugging a Flutter application but the issue does not happen there.

I have tried removing and recloning the repository. I have tried autogenerating the launch.json file and then subsequently, I have tried deleting the entire .vscode folder.

I have a Mac that's running Catalina 10.15.1

**To Reproduce**
1. Place breakpoint in Node.js application
2. Press Fn + F5 to start in debug, select Node.js in dropdown
3. Breakpoint will turn grey and hollow and will not be hit if code is executed

VSCode 1.47

**Comment by connor4312** [comment]
Thanks for the issue, are you able to collect a log file using these instructions?

> If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
> ⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by zakariaagha** [comment]
[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode-js-debug/files/4907322/vscode-debugadapter-0.json.gz)

Here's my log file

**Comment by connor4312** [comment]
Thank you for the information! Which version of Node.js are you running?

**Comment by zakariaagha** [comment]
v8.12.0

**Comment by connor4312** [comment]
Thank you! This is https://github.com/microsoft/vscode/issues/102166. You can either:

1. Update to Node 10 or higher (Noe 8 is EOL at this point, so it's advisable in general)
1. Set `debug.javascript.usePreview: false` to temporarily use the old debugger
1. Wait for the next [nightly build](https://github.com/microsoft/vscode-js-debug/#nightly-extension) of the extension coming in a few hours and update to that, or wait for the next vscode release early/mid next week

**Comment by zakariaagha** [comment]
Thanks!

**Comment by connor4312** [comment]
A fix for this issue has now been released in VS Code 1.47.2. If you previously had to opt-out of the new debugger, you should be safe to turn it back on. Thanks again for the report!
