### ISSUE TITLE
VS Code 1.47.0 No Longer Able to Attach Node.js Debugger

### ISSUE THREAD

**Issue by HAMPLENI** [microsoft/vscode-js-debug#580]
**Describe the bug**
After upgrading to VS Code 1.47.0, I am no longer able to attach my Node.js debugger in VS Code.  The following error is displayed:

```
Error processing attach: Error: Could not connect to debug target at http://[Redacted]:5859: Could not find any debuggable target\n\tat e (c:\\Users\\[Redacted]\\.vscode\\extensions\\ms-vscode.js-debug-nightly-2020.7.1017\\src\\extension.js:15:2438843)\n\tat processTicksAndRejections (internal/process/task_queues.js:85:5)
```

I also tried the `ms-vscode-js-debug` nightly build but the error occurred for both.

**To Reproduce**
1. Windows 10
2. Upgrade VS Code to 1.47.0
3. Press F5 in VS Code

**Log File**

```
{"tag":"runtime.launch","timestamp":1594449604718,"message":"Launch returned error","metadata":{"error":{"message":"Could not connect to debug target at http://[Redacted]:5859: Could not find any debuggable target","stack":"Error: Could not connect to debug target at http://[Redacted]:5859: Could not find any debuggable target\n\tat e (c:\\Users\\[Redacted]\\.vscode\\extensions\\ms-vscode.js-debug-nightly-2020.7.1017\\src\\extension.js:15:2438843)\n\tat processTicksAndRejections (internal/process/task_queues.js:85:5)"},"wasCancelled":true,"name":"y"},"level":2}
{"tag":"dap.send","timestamp":1594449604718,"metadata":{"connectionId":1,"message":{"seq":30,"type":"response","request_seq":2,"command":"attach","success":false,"body":{"error":{"id":9221,"format":"Error processing attach: Error: Could not connect to debug target at http://[Redacted]:5859: Could not find any debuggable target\n\tat e (c:\\Users\\[Redacted]\\.vscode\\extensions\\ms-vscode.js-debug-nightly-2020.7.1017\\src\\extension.js:15:2438843)\n\tat processTicksAndRejections (internal/process/task_queues.js:85:5)","showUser":false,"sendTelemetry":false}}}},"level":0}
{"tag":"dap.receive","timestamp":1594449604723,"metadata":{"connectionId":1,"message":{"command":"disconnect","arguments":{"restart":false},"type":"request","seq":26}},"level":0}
{"tag":"dap.send","timestamp":1594449604724,"metadata":{"connectionId":1,"message":{"seq":31,"type":"response","request_seq":26,"command":"disconnect","success":true,"body":{}}},"level":0}
{"tag":"dap.send","timestamp":1594449609724,"metadata":{"connectionId":1,"message":{"seq":32,"type":"event","event":"output","body":{"category":"telemetry","output":"js-debug/dap/operation","data":{"errors":[],"disconnect":{"operation":"disconnect","totalTime":0.8,"max":0.8,"avg":0.8,"stddev":null,"count":1,"failed":0},"!disconnect.errors":[]}}}},"level":0}
```

**VS Code Version:** 1.47.0

**Additional context**

Here is the `launch.json` configuration that is used:

```
{
            "type": "node",
            "request": "attach",
            "name": "Worker",
            "address": "[Redacted]",
            "port": 5859,
            "restart": true,
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "[Redacted]",
            "protocol": "inspector",
            "skipFiles": [
                "<node_internals>/**/*.js"
            ]
}
```

I am able to attach the debugger after setting `debug.javascript.usePreview` to `false` in `settings.json`.

**Comment by massimeddu** [comment]
I've the same issue.

**Comment by connor4312** [comment]
How are you launching the program you're trying to attach to?

**Comment by massimeddu** [comment]
> How are you launching the program you're trying to attach to?

I'm using the following command to lunch the program:

`node_modules/.bin/nest start --debug 0.0.0.0:9229 --watch`

**Comment by connor4312** [comment]
Okay, thanks for the info. That means we failed to look up the list of targets on the process, for some reason.

What happens if you run `curl http://[Redacted]:9229/json/list` on the machine from which you're trying to connect?

**Comment by connor4312** [comment]
Nevermind, I found the issue. Updating shortly.

**Comment by connor4312** [comment]
This should be fixed in the new [nightly release](https://github.com/microsoft/vscode-js-debug#nightly-extension) which I've manually triggered.

**Comment by massimeddu** [comment]
> This should be fixed in the new [nightly release](https://github.com/microsoft/vscode-js-debug#nightly-extension) which I've manually triggered.

I can confirm that the nightly extension fixes the issue. Thank you for the quick fix!

**Comment by connor4312** [comment]
Excellent, thanks for the confirmation!

**Comment by HAMPLENI** [comment]
The debugger now attaches when using the nightly build and setting `debug.javascript.usePreview` to `true` in `settings.json`.  Thanks for fixing this!

**Comment by AnkitaPadma** [comment]
Hi, I m unable to add the debugger..
![image](https://user-images.githubusercontent.com/23658195/91084156-2aaa9b80-e669-11ea-972a-393f9d6fd48c.png)
I get this image
and my launch.json looks like this
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Docker: Attach to Node",
            "type": "node",
            "request": "attach",
            "port": 9229,
            "address": "localhost",
            "localRoot": "${workspaceFolder}",
            "remoteRoot": "/usr/src/app",
            "protocol": "inspector"
        }
    ]
}

Additional info - I m using node:11-alpine
and running the docker from docker compose using
 ports:
      - "3030:3030"
      - "9229:9229"
    command:
      - node
      - "--inspect-brk=0.0.0.0"
      - "."

none of the breakpoints are hit.
please suggest

**Comment by connor4312** [comment]
Please open a new issue using the issue template.
