### ISSUE TITLE
node.js breakpoints become "unbound breakpoint"

### ISSUE THREAD

**Issue by sphui** [microsoft/vscode-js-debug#581]
**Describe the bug**
node.js breakpoints become "unbound breakpoint".

**To Reproduce**
After upgrade to 1.47, just open my node.js project, and start debugging, all breakpoints said to be "unbound breakpoints"

**Log File**

**VS Code Version:** 1.47

**Additional context**
I revert to 1.46, all breakpoints works well

**Comment by connor4312** [comment]
Can you please share the log file using these instructions?

> If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
> ⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by connor4312** [comment]
If you are using Node 8, this may be https://github.com/microsoft/vscode/issues/102166. You can either:

1. Update to Node 10 or higher (Noe 8 is EOL at this point, so it's advisable in general)
1. Set `debug.javascript.usePreview: false` to temporarily use the old debugger
1. Wait for the next [nightly build](https://github.com/microsoft/vscode-js-debug/#nightly-extension) of the extension coming in a few hours and update to that, or wait for the next vscode release early/mid next week

**Comment by sphui** [comment]
Yes, my node version is 8.16. thanks a lot

**Comment by connor4312** [comment]
A fix for this issue has now been released in VS Code 1.47.2. If you previously had to opt-out of the new debugger, you should be safe to turn it back on. Thanks again for the report!

**Comment by watcher00090** [comment]
Hey @connor4312, I'm also getting unbound breakpoints while trying to attach to a nodeJS process. Would you be willing to take a look at my logs? I've been trying to attach the debugger to a nodeJS process which gets started by an Elixir web endpoint, but unfortunately all my breakpoints are greyed out, and I'm not sure what's going wrong. I did get a warning like "it's taking a long time to set up breakpoints", but I'm not sure what's generating this.  
[vscode-debugadapter-18.json.gz](https://github.com/microsoft/vscode-js-debug/files/5363658/vscode-debugadapter-18.json.gz)
Thank you, 
James

**Comment by connor4312** [comment]
@watcher00090 it looks like you're trying to debug your build process rather than the running application. E.g. none of the files in `/Users/jamespedersen/workspace/orcasite-staging/assets/src/components` are loaded by the process you're debugging.

**Comment by watcher00090** [comment]
Hey Connor, thanks for getting back to me about this! Haha, that was a silly thing to do. The thing is, that's the only NodeJS process that's running on my machine, so I'm not sure what else to attach it to. Is this the right way to debug frontend code that gets served from a non-nodeJS web endpoint? 

Also, I tried using the 'Launch Chrome' configuration after the Elixir web endpoint is started elsewhere, but I'm still getting unbound breakpoints in my frontend code. Log is attached, maybe you'd be willing to take a look at it and point me in the right direction? 

[vscode-debugadapter-25.json.gz](https://github.com/microsoft/vscode-js-debug/files/5379820/vscode-debugadapter-25.json.gz)

**Comment by offero** [comment]
I'm having the same issue now. VSCode Insiders 1.60.0-insider
Node 8.15 application
I used to be able to set breakpoints okay. I seemingly cannot switch back to the old debugger; the config option is no longer available.

**Comment by SorJEF** [comment]
After upgrade to 1.60.0 Node 8.11 application debugging does not work.

Fixed with "legacy-node" type. @offero check this out. It's mentioned here https://code.visualstudio.com/updates/v1_60#_javascript-debugging

**Comment by connor4312** [comment]
We strongly recommend upgrading off Node 8. The version of V8 included in Node 8 has bugs with debugging, and Node 8 itself reached end of life in 2019 and has not received security patches since then.

**Comment by connor4312** [comment]
Generally you can just install the newer Node version without any code changes. The exception is if you have modules that have native dependencies that might be outdated and only work with old Node versions, but these will generally fail either on installation or right when they're `require`'d during app startup.

Here's the documentation on general node debugging: https://code.visualstudio.com/docs/nodejs/nodejs-debugging
