### ISSUE TITLE
Use "attach" mode when running npm scripts with --inspect-brk

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#584]
Lots of people ran into an issue where they have --inspect-brk in their npm scripts, which blocks the bootloader from being able to call back and attach: https://github.com/microsoft/vscode/issues/99526

A workaround we can apply is detecting if the user is trying to debug a script with that flag, and then instead use the legacy/standard port-attach mode rather than the bootloader.

**Comment by connor4312** [comment]
Rob verified

**Comment by connor4312** [comment]
This now should work and print a warning message to the console, like so: 

![](https://memes.peet.io/img/20-07-66ab2120-e7c9-4606-86f7-787be3425c0f.png)

**Comment by connor4312** [comment]
To verify:

1. Have some non-empty `foo.js`
1. Have `"start": "node --inspect-brk foo.js"` as a package.json `scripts`
1. Have this launch config

    ```
    {
      "name": "Start",
      "type": "pwa-node",
      "request": "launch",
      "runtimeExecutable": "npm",
      "runtimeArgs": ["start"],
    },
    ```
1. Verify you can debug that (should be stopped on the 1st line)
1. Remove `--inspect-brk`. Verify that you can debug that.
1. Change `"start"` to `"run", "not-found"`. You should enter debug mode briefly for npm, then it will error and exit.

**Comment by roblourens** [comment]
Seems like this doesn't work with `"console": "integratedTerminal"`. It attaches then detaches, and the program keeps running in the console. But otherwise works fine.

**Comment by connor4312** [comment]
You may be experiencing interference with auto attach. Try/make sure it's `disabled` to clear variables.
