### ISSUE TITLE
Config port number ignored when usePreview: true

### ISSUE THREAD

**Issue by oeed** [microsoft/vscode-js-debug#586]
**Describe the bug**
I run my app in a Docker container and have a launch config which launches the container and a fixed port to link the debugger. For some reason (on nightly 2020.7.1117) this doesn't work when `debug.javascript.usePreview` is true, but it does work when false.

**To Reproduce**
Launch config (notice port: 5850):
```json
{
  "type": "node",
  "request": "launch",
  "name": "Launch web",
  "preLaunchTask": "docker-debug-web",
  "protocol": "auto",  
  "postDebugTask": "docker-debug-down-web",
  "port": 5850,
  "timeout": 30000,
  "localRoot": "${workspaceFolder}/dist-web",
  "remoteRoot": "/usr/src/app/dist-web",
  "outFiles": [
    "${workspaceFolder}/dist-web/**/*.js"
  ],
  "console": "internalConsole",
  "internalConsoleOptions": "openOnSessionStart",
  "stopOnEntry": true,
  "smartStep": true,
  "runtimeVersion": "12.13.1"
}
```

With usePreview: true the output in the console is the following and nothing happens (not even a timeout strangely):
```
Note: Using the "preview" debug extension
/Users/olivercooper/.nvm/versions/node/v12.13.1/bin/node
Debugger listening on ws://127.0.0.1:56561/9fcb2263-0bd5-46b3-a131-2be58708d1fd
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
```

The Docker container logs say:
```
> node --inspect=0.0.0.0:5850 -r ./tsconfig-paths-bootstrap-web.js dist-web/server/src/web.js

Debugger listening on ws://0.0.0.0:5850/a9214ff6-9db5-411a-818f-066116980de8
For help, see: https://nodejs.org/en/docs/inspector
↻ Starting server...
... (and normal app logs from here)
```

With usePreview: false the debugger connects just fine and the program starts as expected.

I used to use --inspect-brk but I saw #584 and #583 so tried removing it although I didn't help. I have stopOnEntry: true in the config but I'm not sure if there's a better way to do this in my situation where Node isn't launched directly by VSCode (would love to know if there is!).

**Log File**
https://drive.google.com/file/d/1vue-ClcK2p0PTn_Feyih0jlTn8HjwHhm/view?usp=sharing

**VS Code Version:** 1.47.0

**Comment by KBroichhausen** [comment]
Thanks for your solution. I'm facing the exact same issue with my app in a docker container. It was working before the last update.

Version: 1.47.0 (user setup)
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:02:06.629Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by connor4312** [comment]
For the moment you can set `debug.javascript.usePreview: false` to use the old debugger

**Comment by connor4312** [comment]
I've added 'official' support for this in js-debug now. See https://github.com/microsoft/vscode-js-debug/commit/540fbcace9eda0c43fa0b73797d3cba95a2f443b for details and reasoning, the tl;dr is that (if you'd like to continue using the new debugger, which I'd encourage 🙂 ) you need to do two things:

1. Grab the [nightly js-debug](https://github.com/microsoft/vscode-js-debug/#nightly-extension) extension
1. Change the `port` property in your launch.json to `attachSimplePort`. Note that VS Code will complain this property is invalid unless you set the debug `type` to `pwa-node`. (I will PR to the deno docs to update this).

Then it should work. This change will land in the next VS Code stable release, at which point you will no longer need to be on the nightly extension build.

**Comment by KBroichhausen** [comment]
>
>     2. Change the `port` property in your launch.json to `attachSimplePort`. Note that VS Code will complain this property is invalid unless you set the debug `type` to `pwa-node`. (I will PR to the deno docs to update this).
> 
> 
> Then it should work. This change will land in the next VS Code stable release, at which point you will no longer need to be on the nightly extension build.

Well, my use case is a little bit different. I'm not launching docker via vscode, it is simply running all the time in the background. So, i just attach to it.
I tried the nightly build and what makes things a little weird for me: I can attach to the process with the new nightly build **without** using the new `attachSimplePort` option. It is working fine with the old `port` option. Maybe my problem is somewhere else but with `debug.javascript.usePreview: true` it is working fine on the nightly build and not working with the current stable build.
Anyway, my problem is solved with the current nightly build and so it will be in the future stable release.

**Comment by oeed** [comment]
Awesome, that works perfectly, thanks! Although can I maybe suggest keeping the option name as 'port'? You might have a large number of rather confused people with older configs that suddenly break otherwise.

**Comment by connor4312** [comment]
I explained that a bit in the commit messsage:

> The parameter is renamed `attachSimplePort` from simply `port`, because
> the have lots of existing users with `port` in their options for whom
> the bootloader will work perfectly and unlock additional functionality.

Thought process:

- *Lots* of users have `port` in their debug configuration, but only a very very small minority of people now need it.
- Attaching via a port prevents us from being able to debug the process tree / child processes, which is a useful new feature.
- The people who do need `port` will probably be advanced users with complex configurations debugging things like Docker or esoteric serverless things (like the first linked issue), who can discover this issue or who will file issues which I can quickly direct here.
