### ISSUE TITLE
Unbound breakpoint after start debugging on MacOS

### ISSUE THREAD

**Issue by captainchain** [microsoft/vscode-js-debug#587]
**Describe the bug**
After the VSCode upgraded to the ver 1.47.0, all my nodejs projects could not be debugged.So I try to write a smallest code to find out the problem. Only two files:
1.test.js
setInterval(() => {
    console.log('test');
}, 1000);

2.launch.json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "outputCapture": "std",
            "request": "launch",
            "name": "startup",
            "program": "${workspaceFolder}/test.js"
        }
    ]
}

**To Reproduce**
1.  Set a breakpoint at the second line of test.js
2.  Press F5
3.  the breakpoint changed from solid to hollow, and show a tip of "unbound breakpoint" when mouse hover

**Log File** 
{"timestamp":1594615171983,"tag":"runtime.welcome","level":1,"message":"js-debug v1.47.3 started","metadata":{"os":"darwin x64","nodeVersion":"v12.8.1","adapterVersion":"1.47.3"}}
{"tag":"dap.receive","timestamp":1594615171966,"metadata":{"connectionId":10,"message":{"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"pwa-node","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"zh-cn","supportsProgressReporting":true},"type":"request","seq":1}},"level":0}
{"tag":"dap.send","timestamp":1594615171966,"metadata":{"connectionId":10,"message":{"seq":1,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"supportsConfigurationDoneRequest":true,"supportsFunctionBreakpoints":false,"supportsConditionalBreakpoints":true,"supportsHitConditionalBreakpoints":true,"supportsEvaluateForHovers":true,"exceptionBreakpointFilters":[{"filter":"caught","label":"Caught Exceptions","default":false},{"filter":"uncaught","label":"Uncaught Exceptions","default":false}],"supportsStepBack":false,"supportsSetVariable":true,"supportsRestartFrame":true,"supportsGotoTargetsRequest":false,"supportsStepInTargetsRequest":false,"supportsCompletionsRequest":true,"supportsModulesRequest":false,"additionalModuleColumns":[],"supportedChecksumAlgorithms":[],"supportsRestartRequest":true,"supportsExceptionOptions":false,"supportsValueFormattingOptions":true,"supportsExceptionInfoRequest":true,"supportTerminateDebuggee":false,"supportsDelayedStackTraceLoading":true,"supportsLoadedSourcesRequest":true,"supportsLogPoints":true,"supportsTerminateThreadsRequest":false,"supportsSetExpression":false,"supportsTerminateRequest":false,"completionTriggerCharacters":[".","[","\"","'"],"supportsBreakpointLocationsRequest":true,"supportsClipboardContext":true}}},"level":0}
{"tag":"dap.send","timestamp":1594615171966,"metadata":{"connectionId":10,"message":{"seq":2,"type":"event","event":"initialized","body":{}}},"level":0}
{"tag":"dap.receive","timestamp":1594615171977,"metadata":{"connectionId":10,"message":{"command":"launch","arguments":{"type":"pwa-node","outputCapture":"std","request":"launch","name":"startup","program":"/Users/captain/test/test.js","trace":true,"cwd":"/Users/captain/test","logFilePath":"/Users/captain/Library/Application Support/Code/logs/20200713T120128/exthost4/ms-vscode.node-debug/debugadapter-legacy.txt","__debuggablePatterns":["*.js","*.es6","*.jsx","*.mjs"],"__workspaceFolder":"/Users/captain/test","__sessionId":"75acb6c8-1706-44f4-80ef-db59426d960e"},"type":"request","seq":2}},"level":0}
{"tag":"dap.send","timestamp":1594615171978,"metadata":{"connectionId":10,"message":{"seq":3,"type":"event","event":"output","body":{"category":"telemetry","output":"js-debug/launch","data":{"type":"pwa-node","request":"launch","os":"darwin x64","nodeVersion":"v12.8.1","adapterVersion":"1.47.3","parameters":"{\"type\":\"pwa-node\",\"name\":\"<string>\",\"request\":\"launch\",\"trace\":true,\"outputCapture\":\"<string>\",\"timeout\":10000,\"showAsyncStacks\":true,\"skipFiles\":[],\"smartStep\":true,\"sourceMaps\":true,\"pauseForSourceMap\":false,\"resolveSourceMapLocations\":null,\"rootPath\":\"<string>\",\"outFiles\":[\"<string>\",\"<string>\"],\"sourceMapPathOverrides\":{\"webpack://?:*/*\":\"<string>\",\"webpack:///./~/*\":\"<string>\",\"meteor://💻app/*\":\"<string>\"},\"__workspaceFolder\":\"<string>\",\"__autoExpandGetters\":false,\"cwd\":\"<string>\",\"env\":{},\"envFile\":null,\"localRoot\":null,\"remoteRoot\":null,\"autoAttachChildProcesses\":true,\"runtimeSourcemapPausePatterns\":[],\"program\":\"<string>\",\"stopOnEntry\":false,\"console\":\"internalConsole\",\"restart\":false,\"args\":[],\"runtimeExecutable\":\"node\",\"runtimeVersion\":\"default\",\"runtimeArgs\":[],\"profileStartup\":false,\"logFilePath\":\"<string>\",\"__debuggablePatterns\":[\"<string>\",\"<string>\",\"<string>\",\"<string>\"],\"__sessionId\":\"<string>\"}"}}}},"level":0}
{"tag":"dap.send","timestamp":1594615171979,"metadata":{"connectionId":10,"message":{"seq":4,"type":"event","event":"output","body":{"category":"console","output":"Verbose logs are written to:\n/var/folders/t8/x_8xz4ys2cd773g803h9wydc0000gn/T/vscode-debugadapter-0.json.gz\n"}}},"level":0}
{"tag":"dap.receive","timestamp":1594615171997,"metadata":{"connectionId":10,"message":{"command":"setBreakpoints","arguments":{"source":{"name":"test.js","path":"/Users/captain/test/test.js"},"lines":[2],"breakpoints":[{"line":2}],"sourceModified":false},"type":"request","seq":3}},"level":0}
{"tag":"dap.send","timestamp":1594615171997,"metadata":{"connectionId":10,"message":{"seq":5,"type":"response","request_seq":3,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"id":1,"verified":false,"message":"Unbound breakpoint"}]}}},"level":0}
{"tag":"dap.receive","timestamp":1594615172003,"metadata":{"connectionId":10,"message":{"command":"setExceptionBreakpoints","arguments":{"filters":[]},"type":"request","seq":4}},"level":0}
{"tag":"dap.send","timestamp":1594615172003,"metadata":{"connectionId":10,"message":{"seq":6,"type":"response","request_seq":4,"command":"setExceptionBreakpoints","success":true,"body":{}}},"level":0}
{"tag":"dap.send","timestamp":1594615172015,"metadata":{"connectionId":10,"message":{"seq":7,"type":"event","event":"output","body":{"category":"console","output":"/usr/local/bin/node /Users/captain/test/test.js"}}},"level":0}
{"tag":"runtime.launch","timestamp":1594615172018,"message":"Launched successfully","metadata":{"name":"v"},"level":1}
{"tag":"dap.send","timestamp":1594615172019,"metadata":{"connectionId":10,"message":{"seq":8,"type":"response","request_seq":2,"command":"launch","success":true,"body":{}}},"level":0}
{"tag":"dap.receive","timestamp":1594615172021,"metadata":{"connectionId":10,"message":{"command":"configurationDone","type":"request","seq":5}},"level":0}
{"tag":"dap.send","timestamp":1594615172021,"metadata":{"connectionId":10,"message":{"seq":9,"type":"response","request_seq":5,"command":"configurationDone","success":true,"body":{}}},"level":0}
{"tag":"dap.receive","timestamp":1594615172063,"metadata":{"connectionId":10,"message":{"command":"loadedSources","type":"request","seq":6}},"level":0}
{"tag":"dap.receive","timestamp":1594615172063,"metadata":{"connectionId":10,"message":{"command":"threads","type":"request","seq":7}},"level":0}
{"tag":"dap.send","timestamp":1594615172063,"metadata":{"connectionId":10,"message":{"seq":10,"type":"response","request_seq":6,"command":"loadedSources","success":true,"body":{"sources":[]}}},"level":0}
{"tag":"dap.send","timestamp":1594615172063,"metadata":{"connectionId":10,"message":{"seq":11,"type":"response","request_seq":7,"command":"threads","success":true,"body":{"threads":[]}}},"level":0}
{"tag":"dap.send","timestamp":1594615172378,"metadata":{"connectionId":10,"message":{"seq":12,"type":"event","event":"output","body":{"category":"stderr","output":"Debugger listening on ws://127.0.0.1:50710/94130238-617f-4883-ae3b-4b44b42b0dab\nFor help see https://nodejs.org/en/docs/inspector\n"}}},"level":0}
{"tag":"cdp.receive","timestamp":1594615172729,"metadata":{"connectionId":10,"message":{"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"1563","type":"waitingForDebugger","title":"/Users/captain/test/test.js","url":"file:///Users/captain/test/test.js","openerId":"","attached":true}}}},"level":0}
{"tag":"cdp.send","timestamp":1594615172729,"metadata":{"connectionId":10,"message":{"id":1,"method":"Target.attachToTarget","params":{"targetId":"1563"}}},"level":0}
{"tag":"dap.send","timestamp":1594615172738,"metadata":{"connectionId":10,"message":{"seq":13,"type":"event","event":"output","body":{"category":"stderr","output":"Debugger attached.\n"}}},"level":0}
{"tag":"dap.send","timestamp":1594615173391,"metadata":{"connectionId":10,"message":{"seq":14,"type":"event","event":"output","body":{"category":"stdout","output":"test\n"}}},"level":0}
{"tag":"dap.send","timestamp":1594615174394,"metadata":{"connectionId":10,"message":{"seq":15,"type":"event","event":"output","body":{"category":"stdout","output":"test\n"}}},"level":0}
{"tag":"dap.send","timestamp":1594615175395,"metadata":{"connectionId":10,"message":{"seq":16,"type":"event","event":"output","body":{"category":"stdout","output":"test\n"}}},"level":0}
{"tag":"dap.receive","timestamp":1594615176369,"metadata":{"connectionId":10,"message":{"command":"disconnect","arguments":{"restart":false},"type":"request","seq":8}},"level":0}
{"tag":"dap.send","timestamp":1594615176411,"metadata":{"connectionId":10,"message":{"seq":17,"type":"event","event":"output","body":{"category":"stdout","output":"test\n"}}},"level":0}
{"tag":"runtime.launch","timestamp":1594615176413,"message":"Failed to attach to target","metadata":{"targetId":"1563"},"level":1}
{"tag":"dap.send","timestamp":1594615176413,"metadata":{"connectionId":10,"message":{"seq":18,"type":"event","event":"output","body":{"category":"stderr","output":"Process exited with code null\r\n"}}},"level":0}
{"tag":"dap.send","timestamp":1594615176413,"metadata":{"connectionId":10,"message":{"seq":19,"type":"event","event":"terminated","body":{}}},"level":0}
{"tag":"dap.send","timestamp":1594615176413,"metadata":{"connectionId":10,"message":{"seq":20,"type":"response","request_seq":8,"command":"disconnect","success":true,"body":{}}},"level":0}
**VS Code Version:** 1.47.0

**Additional context**
MacOs Version: 10.15.5

**Comment by connor4312** [comment]
@captainchain what version of Node.js are you running?

**Comment by captainchain** [comment]
v8.4.0

**Comment by connor4312** [comment]
Please see this for the fix: https://github.com/microsoft/vscode/issues/102166#issuecomment-657138385

**Comment by connor4312** [comment]
A fix for this issue has now been released in VS Code 1.47.2. If you previously had to opt-out of the new debugger, you should be safe to turn it back on. Thanks again for the report!
