### ISSUE TITLE
file.js and file.js?v=2 open as separate files.

### ISSUE THREAD

**Issue by Megabyteceer** [microsoft/vscode-js-debug#588]
**Describe the bug**
On html page i import same js module file with ?v=2 parameter, to prevent modules caching. Vscode treat such a file as separate not editable file. Breakpoints placed on "file.js" tab stop working when module reloaded by "file.js?v=2" name.
In  In previous version all was fine.

**VS Code Version:** 1.47

**Comment by Megabyteceer** [comment]
Loaded scripts list lose '?' character, maybe that why files mapping works wrong.
![image](https://user-images.githubusercontent.com/5096541/87401915-79253e80-c5c3-11ea-8585-e4a7a9523fec.png)

**Comment by YuryKuvetski** [comment]
Same issue

**Comment by pmichel-J2S** [comment]
That, and it seems modifications done to the file are not visible on the "?v=2" file that appears while debugging in VS Code.

Restarting Chrome and VS Code separately, clearing Chrome's cache does not fix the problem. Is there some sort of inner cache for the JS debugger ? (if so can it be cleaned manually).

**Comment by Megabyteceer** [comment]
Changes in file is visible everywhere. Problem is, new debugger does not open real '/file.js' script for '/file/js?v=2' url (old debugger does). Instead vs code creates temporary tab with not editable file '/file/jsv=2'.

**Comment by pmichel-J2S** [comment]
What I meant was :
* I launch a first debug session, do some work, then end it.
* I change something in, say, file.js, something trivial like `console.log("something");`
* I launch another debug session, the temporary/non-editable file.js?v=2 does not contain the change I've made, even after cleaning the cache, restarting VSCode and Chrome.

**Comment by jasonwilliams** [comment]
possibly related to https://github.com/microsoft/vscode-js-debug/issues/529

**Comment by connor4312** [comment]
Thank you for the issue. I'm having a little trouble trying to get it to reproduce -- just loading the scripts with query strings in `<script>` tags seems to work

![](https://memes.peet.io/img/20-07-ac190182-5965-4e35-a366-ecf1002e7382.png)

Can you (@Megabyteceer, @YuryKuvetski, @pmichel-J2S) share your trace log using these instructions so I can get to the root cause? 

>If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

Until this is fixed, you can use the old debugger by setting `debug.javascript.usePreview: false` in your user settings. However, this setting will eventually go away, so I would greatly appreciate your help in fixing this problem 🙂

**Comment by Megabyteceer** [comment]
I realize that "readonly ?v=1" tab appears if loaded content of file is not fully matches with content of file on a disk. I add "?v=1" parameter to all import urls inside js file on server side. So debugger think it is different file because of its slightly different content. But really previous version of debugger ignores content and just open existing file. Maybe add something like option to disable content checking?

**Comment by connor4312** [comment]
That's the trick, in [today's nightly](https://github.com/microsoft/vscode-js-debug/#nightly-extension) there is an option for your launch.json:

```diff
{
  "type": "pwa-chrome", // VS Code will complain the option is invalid if left at "chrome", but it will still work
  "request": "launch",
  "name": "Launch my Site",
  "url": "http://localhost:5002",
+ "enableContentValidation": false
},
```

This remains `true` by default as it's useful in many scenarios and required in some (namely ts-node and @babel/register) but it can now be disabled for scenarios like this.

**Comment by pmichel-J2S** [comment]
Thanks a bunch ! 👍

**Comment by Megabyteceer** [comment]
Just tried enableContentValidation it and its fixes problem. Thanks! : )
