### ISSUE TITLE
Unable to launch browser: "Unable to launch the executable" OSX

### ISSUE THREAD

**Issue by markmcdowell** [microsoft/vscode-js-debug#589]
**Describe the bug**
Trying to debug via chrome, previously it was timing out to start, now it throws an error no matter what the timeout is.

May be related to #570, but slightly different error message. I've tried restarting machine but no difference.

**To Reproduce**
1. Setup the below config
2. Start debugging...
3. Errors with: `Unable to launch browser: "Unable to launch the executable"`

[vscode-debugadapter-1.json.gz](https://github.com/microsoft/vscode-js-debug/files/4911148/vscode-debugadapter-1.json.gz)

**VS Code Version:** 1.47.0

**Additional context**
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Ticker",
            "sourceMaps": true,
            "timeout": 30000,
            "trace": true,
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}"
        }
    ]
}
```

Downgrading debugger for chrome to 4.12.8 fixes.

**Comment by connor4312** [comment]
1. Where is your browser installed?
2. Does using the [latest nightly](https://github.com/microsoft/vscode-js-debug#nightly-extension) fix it for you?

**Comment by markmcdowell** [comment]
Yes confirm the latest nightly fixes it. thanks!

**Comment by connor4312** [comment]
Okay, thanks, sounds like the changes in https://github.com/microsoft/vscode-js-debug/issues/570 also fixed this scenario then.

**Comment by pavel-a-leonov** [comment]
Hi. I got the same error on VS code 1.48.0 and 4.12.10 debugger for chrome at Win 8.1. Downgrading debugger for chrome to 4.12.8 was fixed the bug.

**Comment by connor4312** [comment]
Where do you have Chrome installed?

**Comment by pavel-a-leonov** [comment]
So. I have another problem at 1.48.0: breakpoints does not work at all. I returned to the 1.45 VS code version.

Chrome was installed by official installer to the "C:\Program Files (x86)\Google\Chrome\Application" path.

**Comment by connor4312** [comment]
Please file a new issue using the template in this repo
