### ISSUE TITLE
Multiple webRoot and/or sourceMapOverrides that support multiple roots

### ISSUE THREAD

**Issue by EricCornelson** [microsoft/vscode-js-debug#59]
Adding this to track the issue of having multiple source roots that we want to search to resolve source maps.

**Comment by connor4312** [comment]
In https://github.com/microsoft/vscode-js-debug/pull/261 we implement pathMapping, where for example you could have:

```json
{
  "pathMapping": {
    "/": "${workspaceFolder}",
    "/page1": "${workspaceFolder}/src/first-page",
    "/page2": "${workspaceFolder}/src/second-page",
}
```

Does that do what you're after?

**Comment by connor4312** [comment]
Please let me know / reopen if there's more you're after here 🙂
