### ISSUE TITLE
debug remote nodejs doesn't find any target.

### ISSUE THREAD

**Issue by baptoutiego** [microsoft/vscode-js-debug#590]
**Describe the bug**
Since last update of june the run remote debug doesn't work anymore.
Here is my launch.json file
{
            "type": "node",
            "request": "attach",
            "name": "Launch meaurement",
            "port":9229,
            "address": "node_process_address",
            "localRoot": "/path/to/project",
            "remoteRoot": "/var/www/"
        }
The port 9229 is open on the remote adress and the env NODE_OPTIONS=--inspect=0.0.0.0:9229 is set to accept debug.
Each time VScode try to connect remotely, it gets 

"Could not find any target at e"

**To Reproduce**
1. Go to launch.json file
2. set an attach request to remote nodejs process
3. save and start debug

**Log File**

**VS Code Version:** 1.47
https://microsoft.github.io/vscode-pwa-analyzer/index.html :  

"root":{5 items
"tag":"runtime.launch"
"timestamp":1594633198926
"message":"Launch returned error"
"metadata":{3 items
"error":{2 items
"message":"Could not connect to debug target at http://node_process_address:9229: Could not find any debuggable target"
"stack":"Error: Could not connect to debug target at http://node_process_address:9229: Could not find any debuggable target at e (/home/ubuntu/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/ms-vscode.js-debug/src/extension.js:15:2438843) at processTicksAndRejections (internal/process/task_queues.js:89:5)"
}
"wasCancelled":true
"name":"y"
}
"level":2
}

**Comment by Yoshii974** [comment]
+1, same issue here !

**Comment by andreiropotica** [comment]
+1

I cannot lunch a new debug session on a nodejs file.

`        {
            "type": "node",
            "request": "launch",
            "name": "file.js",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}/file.js"
        }`

**Comment by connor4312** [comment]
This is https://github.com/microsoft/vscode-js-debug/issues/580. To fix this you can:

1. Use the latest [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension)
1. Wait until early next week when these changes are released in the recovery
1. Use `debug.javascript.usePreview: false` to temporarily use the old debugger, at least until (3) happens
