### ISSUE TITLE
Cannot find Module vscode-js-debug-bootloader.js

### ISSUE THREAD

**Issue by francoisvouters** [microsoft/vscode-js-debug#593]
**Describe the bug**

**To Reproduce**

**Log File**

**VS Code Version:** Replace me!

**Additional context**

**Comment by connor4312** [comment]
It seems that you didn't fill out the issue, but you're probably hitting a version of https://github.com/microsoft/vscode/issues/102035#issuecomment-656801666. The resolution steps in the comment should work for you (just ignore the electron part of it).

Please add more info if that's not the case.

**Comment by connor4312** [comment]
A fix for this issue has now been released in VS Code 1.47.2. If you previously had to opt-out of the new debugger, you should be safe to turn it back on. Thanks again for the report!
