### ISSUE TITLE
ver 1.47. Debugging htm with javascript as file in chrome, it throws an error 

### ISSUE THREAD

**Issue by luisloz00** [microsoft/vscode-js-debug#594]
After update to 1.47, my launch.json
{
	// Use IntelliSense para saber los atributos posibles.
	// Mantenga el puntero para ver las descripciones de los existentes atributos 
	// Para más información, visite: https://go.microsoft.com/fwlink/?linkid=830387
	"version": "0.2.0",
	"configurations": [

		{	"type": "chrome", "request": "launch",
			"name": "chrome: file", "file": "${file}",
		},
		{
			"type": "chrome",
			"request": "launch",
			"name": "chrome: localhost",
			"url": "http://localhost:8080",
			"webRoot": "${workspaceFolder}"
		}
	]
}
running as file, returns:
![image](https://user-images.githubusercontent.com/68242209/87330403-d1632e80-c538-11ea-83ec-a1058755de34.png)

**Comment by connor4312** [comment]
Can you collect a trace log using these instructions?

>If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by carlosrovira** [comment]
We're getting the same problem as reported here: https://github.com/BowlerHatLLC/vscode-as3mxml/issues/491

I'm trying with latest nightly (.5) and can't get things to work. Maybe using local files is not supported now? we need to use a local server? that seems not good to me.

**Comment by connor4312** [comment]
Thanks. Can you collect a log file using the instructions above?

To unblock yourself in the meantime you can use `debug.javascript.usePreview: false` to use the old debugger.

**Comment by connor4312** [comment]
Fixed this in https://github.com/microsoft/vscode/issues/102529
