### ISSUE TITLE
Call stack no longer shows the name from the configuration that launched the process.

### ISSUE THREAD

**Issue by strigona-worksight** [microsoft/vscode-js-debug#596]
**Describe the bug**
The "Call Stack" panel just lists `index.ts` (the entry point to my services) instead of the configuration name of from `launch.json`. At launch, the configuration name displays briefly but then is soon replaced with "index.ts". I'm taking a bit of a guess that it's related to the call stack "compaction" that was noted in the latest release.

I often debug several services that all have the same package structure - main file is "index.ts" and so it's now hard to identify them.

![Screenshot from 2020-07-13 13-52-00](https://user-images.githubusercontent.com/13368604/87352955-c5fc0d00-c510-11ea-89a3-be64f62d66d9.png)

Selecting the process does display the correct name in the "Debug Console" drop down menu as well as the "Debug Toolbar".

**To Reproduce**
Configuration entry from `launch.json`:
```
    {
      "name": "GraphQL",
      "type": "node",
      "request": "launch",
      "args": ["./src/index.ts"],
      "outputCapture": "std",
      "smartStep": false,
      "runtimeArgs": ["-r", "ts-node/register"],
      "cwd": "${workspaceFolder}/packages/graphql",
      "skipFiles": [
        "${workspaceFolder}/node_modules/**/*.js",
        "<node_internals>/**"
      ]
    }
```

**VS Code Version:** 1.47

**Comment by connor4312** [comment]
Thanks for the issue, fixed in the [next nightly](https://github.com/microsoft/vscode-js-debug#nightly-extension)
