### ISSUE TITLE
Option to opt out from new auto attach

### ISSUE THREAD

**Issue by artu-ole** [microsoft/vscode-js-debug#599]
New auto attach behaviour is way too slow for scenarios with multi staged project launch such as running eslint, then [copyfiles](https://github.com/calvinmetcalf/copyfiles) for some assets, then [concurrently](https://github.com/kimmobrunfeldt/concurrently) with typescript watch and nodemon. 

Option to opt out from new auto attach back to old behaviour when it would only attach to processes flagged by `--inspect` would be handy. 
I don't mind it taking a [tad longer](https://github.com/microsoft/vscode-js-debug/issues/598), but when that happens for 6 sub processes that I don't care about - it becomes frustrating.

**Comment by connor4312** [comment]
This should answer your questions :) https://github.com/microsoft/vscode/issues/102057#issuecomment-657728467
