### ISSUE TITLE
Writing too much to the Debug Console without waiting hangs NodeJS application

### ISSUE THREAD

**Issue by northstarsh** [microsoft/vscode-js-debug#601]
I have a NodeJS application that writes logs to the Debug Console using the console.log function. After 1.47 update the application would work as normal but after a short period it would hang. After some research I think this is related to some type of limit in the Debug Console, or the amount you write to it in a short amount of time.

The code below can show the issue. The first group of console writes (300 at a time) do not have any issues. But the final 1200 console writes stop at around line 329.

`let total = 0;

testLog = function () {
    for (let count = 0; count < 300; count++) {
        total++;
        console.log(total.toString() + ':' + count.toString() + ' abcdefghijklmnopqrstuvwxyz');
    }
};

testLog();
setTimeout(testLog, 1000);
setTimeout(testLog, 2000);
setTimeout(testLog, 3000);
setTimeout(testLog, 4000);
setTimeout(testLog, 5000);
setTimeout(testLog, 6000);

setTimeout(function () {
    for (let count = 0; count < 1200; count++) {
        console.log(count.toString() + ' abcdefghijklmnopqrstuvwxyz');
    }

    console.log('done');
},8000);`

**VS Code Version:** 1.47.0, NodeJS Version: 12.8.1

**Comment by connor4312** [comment]
Thanks for the issue, this duplicates https://github.com/microsoft/vscode/issues/102254
