### ISSUE TITLE
.scripts no longer works

### ISSUE THREAD

**Issue by Rock2000** [microsoft/vscode-js-debug#602]
**Describe the bug**
I try to run .scripts from the debug console and it doesn't do anything. Or sometimes it will print:

.scripts
Uncaught SyntaxError: Unexpected token '.'
 

**To Reproduce**
Start debugging a typescript Node.js app and then type ".scripts" into the debug console.

**VS Code Version:** 1.47.0

**Additional context**

**Comment by connor4312** [comment]
Thanks for the issue, see: https://github.com/microsoft/vscode-js-debug/issues/260

**Comment by Rock2000** [comment]
I'm not sure I understand. So .scripts is not supported in this debugger? But there is a GUI version of it now? If so, where is it? Might have been helpful to print a little message when the user runs .scripts to tell them where this lives now, if that is the case.

**Comment by connor4312** [comment]
There's not yet any equivalent in the new debugger, but I plan to have some kind of GUI. I agree having some hint `.scripts` is useful.

**Comment by Rock2000** [comment]
Is it possible for me to flip it back to the old debugger in order to troubleshoot script issues as needed?

**Comment by connor4312** [comment]
Yes, you can set `debug.javascript.usePreview: false`.

With the new debugger, you can also set trace:true and open the logs in https://microsoft.github.io/vscode-pwa-analyzer/index.html, but this is less user friendly than .scripts

**Comment by Rock2000** [comment]
Great, that's perfect! Thanks for the time.

**Comment by bartocc** [comment]
@connor4312 I don't know how `vscode-chrome-debug` and `vscode-js-debug` are tied one to the other, but would't it be important to update the `.scripts` command doc here https://github.com/microsoft/vscode-chrome-debug#the-scripts-command?

**Comment by bartocc** [comment]
@connor4312 maybe I am doing something wrong, but even after setting `debug.javascript.usePreview: false`, I still get the `Uncaught SyntaxError: Unexpected token '.'` error when typing `.scripts` in the debug console
