### ISSUE TITLE
Step Over debbuger command going into node internal files even setting skipFiles in launch.json

### ISSUE THREAD

**Issue by daniel-oliv** [microsoft/vscode-js-debug#603]
**Describe the bug**
Even setting to skip node internal files, if I do a "Step Over" command, I end up into node files like async_hooks.js. I have the following .vscode\launch.json:
```
{
  "version": "0.2.0",
  "configurations": [

    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "skipFiles": [
        "${workspaceFolder}/node_modules/**/*.js",
        "${workspaceFolder}/lib/**/*.js",
        "<node_internals>/**",
        "<node_internals>/**/*.js"
      ],
      "preLaunchTask": {
        "type": "npm",
        "script": "clear-build",
        "group": "build",
        "problemMatcher": [],
        "label": "npm: clear-build",
        /*"detail": "npm run clear && npm run build-npx" */
      },
      "program": "${workspaceFolder}\\bin\\main.ts",
      "outFiles": ["${workspaceFolder}/dist/**/*.js"]
    }
  ]
}

```
Before updating to version 1.47, the debbuger was working properly.

**To Reproduce**
1. USING VS CODE 1.47, download the repository "https://github.com/daniel-oliv/test-debugger".
2. Run npm install
3. Run debbuger (Hit F5 I think)
4. Put a breakpoint in 15th of the main.ts file with the content: console.log("Put a breakpoint here and press F10 or click in 'Step Over' sequecially until open a internal node file")
5. Hit F10 or click in "Step Over" repeatedly until you end up into node internal files.

**Comment by connor4312** [comment]
Thanks for the good issue -- we actually had a test for this, but the test was broken 😱

**Comment by daniel-oliv** [comment]
Thanks! 👏 😃

**Comment by alisalemmi** [comment]
I have same problem. 

my vscode version:
![image](https://user-images.githubusercontent.com/45937252/121347932-fc1e5880-c93c-11eb-9f1a-26addb2d9504.png)

lunch.json:
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "debug",
      "type": "node",
      "request": "attach",
      "restart": true,
      "skipFiles": ["<node_internals>/**", "**/node_modules/**"]
    }
  ]
}
```

**Comment by connor4312** [comment]
please open a new issue with the instructions in the issue template
