### ISSUE TITLE
Breakpoints unable to bind in new debugger

### ISSUE THREAD

**Issue by Rock2000** [microsoft/vscode-js-debug#604]
**Describe the bug**
Set a breakpoint in typescript code that is imported from a locally built module. When debugging with the nightly debugger, the breakpoints show as "Unbound breakpoint". If I use the previous debugger with no other changes, the breakpoints are successfully bound.

**To Reproduce**
1. Use a sourceroot in the tsconfig of the locally built module. In my case I have: "sourceRoot": "measure-tools/src/"
2. Set a sourceMapPathOverrides in the app being debugged to map the given module's sourceMaps. For our case it is a Chrome target, or an electron Render target. The launch.json has:
     "webRoot": "${workspaceFolder}/test-app",
     "sourceMapPathOverrides": {
        "${webRoot}/measure-tools/src/*": "${workspaceFolder}/measure-tools/src/*",
      },
3. Start the debugger and try to set a breakpoint in one of the module's ts files.

**Log File**

I can supply the full log if needed, but the seemingly relevant lines are shown here for one source file.

{"tag":"dap.receive","timestamp":1594749552082,"metadata":{"connectionId":5,"message":{"command":"setBreakpoints","arguments":{"source":{"name":"Measurement.ts","path":"h:\\cv-measure\\measure-tools\\measure-tools\\src\\api\\Measurement.ts"},"lines":[361],"breakpoints":[{"line":361}],"sourceModified":false},"type":"request","seq":3}},"level":0}
.
{"tag":"dap.receive","timestamp":1594749563546,"metadata":{"connectionId":9,"message":{"command":"setBreakpoints","arguments":{"source":{"name":"Measurement.ts","path":"h:\\cv-measure\\measure-tools\\measure-tools\\src\\api\\Measurement.ts"},"lines":[361],"breakpoints":[{"line":361}],"sourceModified":false},"type":"request","seq":3}},"level":0}
.
{"tag":"dap.send","timestamp":1594749568139,"metadata":{"connectionId":9,"message":{"seq":3558,"type":"event","event":"loadedSource","body":{"reason":"new","source":{"name":"measure-tools/src/api/Measurement.ts","path":"h:\\cv-measure\\measure-tools\\test-app\\measure-tools\\src\\api\\Measurement.ts","sourceReference":1732143500}}}},"level":0}

The correct local path is in the second entry. The third entry has the 'logical' path (with "test-app") but not the local path.

**VS Code Version:** 1.47.1

**Additional context**

**Comment by connor4312** [comment]
Can you go ahead and send the full log over? The lines you have are relevant but not quite enough for me to divine what the root cause is. Thanks!

**Comment by Rock2000** [comment]
Actually I missed one line from the log that I meant to get. I guess that's why the whole log is better. :)  I emailed it. Thanks

**Comment by connor4312** [comment]
Thanks for those logs. Can you give this .vsix a try and see if it fixes the issue for you? (Download and install it using the "Install from VSIX" command) https://memes.peet.io/img/js-debug-nightly-fix-604.vsix

**Comment by Rock2000** [comment]
Hmmmm, it still doesn’t seem to work. In the extensions view it shows Nightly as “Update to 2020.7.141” so I assume I installed the vsix correctly. But still my breakpoints are not bound, and the local paths seem to still be using non-overriden path that includes the “test-app” folder (which it shouldn’t). Here is the newest log.

Thanks

**Comment by connor4312** [comment]
@Rock2000 thanks for the emailed log, in it I see the js-debug version is still reported at the same `1.47.3`. Make sure you've disabled the built-in version (which may require reloading VS Code) if you install the nightly, otherwise they'll steal each others' commands and requests. [Instructions in the readme](https://github.com/microsoft/vscode-js-debug#nightly-extension)

**Comment by Rock2000** [comment]
You're right, the email seemed to be missing the second part of the instructions. This seems to have fixed it, thanks!

**Comment by connor4312** [comment]
Awesome thanks for confirming!
