### ISSUE TITLE
Debug Console no longer shows output.  Debugger no longer stops at break points.

### ISSUE THREAD

**Issue by 333one** [microsoft/vscode-js-debug#605]
**Describe the bug**
Environment: Windows
Language: node.js

The Debug Console no longer shows output.  The Debugger no longer stops at breakpoints.  Both worked before 1.47.0.  If something isn't broken it has definitely changed and I can't find any new instructions.

**To Reproduce**

Add a breakpoint in the simple app.js server below.
Click the Launch Program button with green arrow in the upper left corner.  

**app.js file contents:**
const express = require('express');
const app = express();
app.listen('8080', function(){
    console.log('app.js listening on port 8080');
});

**launch.json contents:**
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}\\app.js"
        }
    ]
}

**Debug Console output:**
"C:\Program Files\nodejs\node.exe" "c:\myapplication\app.js"
Debugger listening on ws://127.0.0.1:55255/d00d13f2-7e6f-42f2-8e60-246b0e3d07f2
For help see https://nodejs.org/en/docs/inspector

Debug Console output no longer includes console.log _app.js listening on port 8080_,  On program launch breakpoints change from red dots to hollow grey circles and are no longer stopped at.

**Log File**

**VS Code Version:** 1.47.1

**Comment by connor4312** [comment]
Are you using Node 8? This sounds like https://github.com/microsoft/vscode/issues/102166

/needsMoreInfo

**Comment by 333one** [comment]
Thank you so much!  I didn't realize that I had been using an old version of Node.  I updated to V12 and the Debugger works perfect.  Thanks again!

**Comment by connor4312** [comment]
A fix for this issue has now been released in VS Code 1.47.2 🙂
