### ISSUE TITLE
New debugger in version 1.47.1 is not breaking on break points or debugger statements.

### ISSUE THREAD

**Issue by Nosherwan** [microsoft/vscode-js-debug#608]
**Describe the bug**
I am running node.js with ts-node in docker. Remote debugging has been working fine previously with both breakpoints and debugger statements. After updating to version 1.47.1 debugging is broken. None of the breakpoints or debugger statements are being hit.

**To Reproduce**
1. I am using ts-node to run node and my npm run command in package.json is as follows:
```js
"scripts": {
                "start": "npm run build:live",
		"build:live": "nodemon --exec 'TS_NODE_PROJECT=./tsconfig.json node --inspect=0.0.0.0:9229 -r dotenv/config -r ts-node/register ./src/index.ts dotenv_config_path=./.env' --verbose -e ts",
	},
```
2. tsconfig.json declares the out directory where all the source maps are copied.
```js
{
	"include": [
		"src/**/*"
	],
	"compilerOptions": {
		"target": "ES2017",
		"module": "commonjs", 
		"lib": ["es2015"],
		"declaration": true,
		"sourceMap": true,
		"outDir": "./dist",
		"strict": true,
		"moduleResolution": "node",
		"sourceRoot": "./dist",
		"mapRoot": "./dist"
}
```
3. My docker file is as follows that describes the node version:
(I am overriding the npm start to npm run build:live in docker-compose)
```js
FROM node:10.15.3-alpine
RUN apk add --no-cache tzdata
ENV TZ Australia/Sydney
# Create app directory
WORKDIR /app

COPY package*.json /app/
# Installs everything from package.json
RUN npm install
# Will copy all files except node_modules
COPY . .
# even though port is being exposed it will
# be overridden by docker-compose port
EXPOSE 4000 

CMD [ "npm", "start" ]
```

**VS Code Version:** 1.47.1

**Comment by connor4312** [comment]
Thanks for the issue, I think https://github.com/microsoft/vscode-js-debug/issues/586 covers your scenario. I plan to address that tomorrow. (temporary mitigation in https://github.com/microsoft/vscode-js-debug/issues/586#issuecomment-657563889)
