### ISSUE TITLE
Net core project debugging in chrome

### ISSUE THREAD

**Issue by ashifur-malia** [microsoft/vscode-js-debug#609]
**Describe the bug**
Im working on a net core angular project. 
the ui project (typescript) has its launch.json file along with setting.josn and tasks.json
up till now everything was fine while debugging. but after update 1.47.1 when launching application chrome starts to flickering when the browser console is open (more like its try to restart the page over and over. ) after few minutes eventually it lands on the the page. 
I have attached the launch.json, setting.json and tasks.json file in txt format. 
Note: its not only mine vs code being effected but all devs in my team having the same issue. 
I'm not sure if i have provided enough  explanation/documentation. feel free to contact me on "ashifur_rahman@yahoo.com" for any further help. 
[launch.txt](https://github.com/microsoft/vscode-js-debug/files/4922502/launch.txt)
[settings.txt](https://github.com/microsoft/vscode-js-debug/files/4922503/settings.txt)
[tasks.txt](https://github.com/microsoft/vscode-js-debug/files/4922504/tasks.txt)

**To Reproduce**

**Log File**

**VS Code Version:** 1.47.1

**Additional context**

**Comment by connor4312** [comment]
This is the same as https://github.com/microsoft/vscode-js-debug/issues/597. If it's causing significant problems for you you can use the old debugger by setting `debug.javascript.usePreview: false` until it's resolved.
