### ISSUE TITLE
debugger

### ISSUE THREAD

**Issue by chengqilong** [microsoft/vscode-js-debug#610]
debugger can  not be used;   

Version: 1.47.1 (user setup)
Commit: 485c41f9460bdb830c4da12c102daff275415b53
Date: 2020-07-13T22:42:53.386Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by connor4312** [comment]
Can you please provide some details? Around the problem you're facing?

Common issues are Node 8 incompatibility https://github.com/microsoft/vscode/issues/102166 and older electron versions https://github.com/microsoft/vscode/issues/102035, are you hitting one of these?

**Comment by connor4312** [comment]
A fix for the Node 8 has now been released in VS Code 1.47.2.

**Comment by Doubl3** [comment]
- Node 10.6.0
- VSCode 1.47.2

Doesn't work for me.
-> See [Issue 631](https://github.com/microsoft/vscode-js-debug/issues/631#issuecomment-660026205)

**Comment by connor4312** [comment]
Closing due to lack of info. Let us know if you still hit this problem on 1.47.2, and if so provide details. Thanks!
