### ISSUE TITLE
Node.js debugger auto attaching when not required

### ISSUE THREAD

**Issue by sunilubale** [microsoft/vscode-js-debug#611]
After new updates Node.js debugger auto attaching when not required, may be there is any option to toggle it off but I could not easily find it there is not a clear documentation around it.

**To Reproduce**
Run any Gulp command from VS Code terminal

for example when I run gulp clean from VS Code terminal it attaches debugger when not required.

> PS C:\AppPath> gulp clean
> Debugger listening on ws://127.0.0.1:54350/14dd4a26-07e3-4b79-b65c-306a855b2d98
> For help, see: https://nodejs.org/en/docs/inspector
> Debugger attached.
> Build target: DEBUG
> [17:19:25] Using gulpfile ~\dev\test\gulpfile.js
> [17:19:25] Starting gulp
> [17:19:25] Starting 'clean'...
> [17:19:25] Starting subtask 'clean'...
> [17:19:25] Finished subtask 'clean' after 180 ms
> [17:19:25] Finished 'clean' after 183 ms
> [17:19:26] ==================[ Finished ]==================
> [17:19:26] Project test version:0.0.1
> [17:19:26] Build tools version:3.12.1
> [17:19:26] Node version:v10.16.0
> [17:19:26] Total duration:7.38 s
> Waiting for the debugger to disconnect...

**Comment by sunilubale** [comment]
able to disable default javascript debugger

**Comment by connor4312** [comment]
Thanks for the issue, check out https://github.com/microsoft/vscode/issues/102057#issuecomment-657728467
