### ISSUE TITLE
Question: How to detect that debugger is attached?

### ISSUE THREAD

**Issue by yrtimiD** [microsoft/vscode-js-debug#612]
Before new debugger I used to detect "debug mode" by checking process.execArgv for presence of "--inspect" argument.
New debugger doesn't uses it anymore.
Do you have any other way to tell the process that it has debugger attached?

**Comment by connor4312** [comment]
The best way would actually be to see if `inspector.url() !== undefined` https://nodejs.org/api/inspector.html#inspector_inspector_url
