### ISSUE TITLE
Auto-attach does not pick up "node --inspect-brk" (but works with "node --inspect")

### ISSUE THREAD

**Issue by RomainMuller** [microsoft/vscode-js-debug#615]
**Describe the bug**
With auto-attach enabled, executing `node --inspect-brk` does not trigger automatic attachment.
Then upon using the *Debug: Attach to Node Process* command, the debugger attaches, but does not actually do anything until I click the "restart" button of the debug control bar, at which point I am at the state I'd expect to get in..

**To Reproduce**
1. Open VS Code, and ensure *Auto Attach* is enabled
2. In the VS Code built-in terminal, `node --inspect-brk whatever.js`
3. Notice the output of the command:
   ```
   Debugger listening on ws://127.0.0.1:9229/05b9c1a6-cb4c-4627-ba43-de4c793e3e04
   For help, see: https://nodejs.org/en/docs/inspector
   ```
4. Wait for a moment and notice VS Code does not auto-attach
5. Use the *Debug: Attach to Node Process* command
6. The debug controls show up, but the debugger does not "break" at the entry (nothing seems to be happening)
7. Click the "restart" button of the debug controls
8. Debug away

**Log File**

I'm not certain how to get a log trace of this command. If you provide instructions, I'll happily follow those instructions and report back.

**VS Code Version:** 
```
Version : 1.47.1
Commit : 485c41f9460bdb830c4da12c102daff275415b53
Date : 2020-07-13T22:43:02.577Z (Il y a 1 jours)
Electron : 7.3.2
Chrome : 78.0.3904.130
Node.js : 12.8.1
V8 : 7.8.279.23-electron.0
OS : Darwin x64 19.5.0
```

**Additional context**
N/A

**Comment by connor4312** [comment]
Thanks for the issue. This is an artifact with how debugging works with the new debugger -- but we're going to revert this behavior (https://github.com/microsoft/vscode/issues/102057#issuecomment-657728467) as there have been a number of edge cases and complexities coming up. The revert will be released on Thursday the 16th.
