### ISSUE TITLE
Cannot run npm scripts due to debugger interference

### ISSUE THREAD

**Issue by frobinsonj12** [microsoft/vscode-js-debug#619]
Attempt to execute npm scripts using the terminal screen results in screen becoming locked.
**To Reproduce**
1. Start a new terminal
2.Type in npm run build:client on command line
3. "Debugger listening on ws://127.0.0.1:57667/8213f402-f1bd-446b-8dd9-98b368344214
For help, see: https://nodejs.org/en/docs/inspector" and nothing else happens, no entries in call stack, NOTHING.

**Comment by connor4312** [comment]
Please see https://github.com/microsoft/vscode/issues/102057#issuecomment-657728467
