### ISSUE TITLE
UseWebview:"Advanced" -> URLFilter not attaching as expected.

### ISSUE THREAD

**Issue by DavidShoe** [microsoft/vscode-js-debug#624]
When using "useWebView": "advanced" with a URLFilter the filter is not attaching to webviews that it should.

 "urlFilter": "*index.html?i=2",

Reproduce:
Configure useWebView to "advanced"
set URLFilter = "*?i=2",
Navigate to any page and add ?1=2 to the end of the url.

This should trigger the urlfilter code to attach to the webview.

But it is not.

VSCode version 1.47.1

NOTE: this filter does work when using the old debug adapter.  It appears the handling of the * wildcard is not working as expected.

**Comment by connor4312** [comment]
David verified this
