### ISSUE TITLE
could not support nodejs v0.10.33 debug after insall vscode v1.47.1

### ISSUE THREAD

**Issue by spalby** [microsoft/vscode-js-debug#627]
Previous support

**Comment by spalby** [comment]
![bug](https://user-images.githubusercontent.com/54531504/87621594-b8829500-c753-11ea-8638-e8a7115fde98.png)

**Comment by connor4312** [comment]
This is the same as https://github.com/microsoft/vscode/issues/102626

Node 0.10 was end-of-life in 2016. I would seriously consider upgrading at this point for more features, better performance, and security fixes.
