### ISSUE TITLE
Node debugger disregards skipFiles when attaching to running process

### ISSUE THREAD

**Issue by Livshitz** [microsoft/vscode-js-debug#633]
When setting in vscode launch.json `attach` section with `skipFiles` (including node_internals), the new debugger will simply ignore and will step into internal node modules (async_hook.js for example).

**To Reproduce**
In `launch.json` add:
```
{
    "name": "Node Attach",
    "type": "node",
    "request": "attach",
    "port": 9229,
    "smartStep": true,
    "skipFiles": [
        "${workspaceFolder}/node_modules/**/*.js",
        "${workspaceFolder}/lib/**/*.js",
        "<node_internals>/**/*.js"
    ]
}
```

Run a node app, and attach to it. When in debug, step in into async function. You'll be stepping in an internal module instead your underlying code.
Disabling new debugger and using the old one by changing `debug.javascript.usePreview` to `false` in settings and re-running will behave as expected.
P.S, I was debugging TS, didn't test on JS.

**Log File**
Trace: [vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode-js-debug/files/4933013/vscode-debugadapter-0.json.gz)

**VS Code Version:** 1.47.1

**Comment by connor4312** [comment]
Thanks for the issue, this sounds like fixes referenced in https://github.com/microsoft/vscode/issues/102412#issuecomment-658301904. Can you try the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) and see if that fixes your issue?

**Comment by Livshitz** [comment]
@connor4312 yes, the issue is resolved in the nightly build. Thanks for the quick response.
Closing.
