### ISSUE TITLE
configuration name missing in call stack view

### ISSUE THREAD

**Issue by cjones1313** [microsoft/vscode-js-debug#635]
After recent update the call stack view displays javascript file names instead of launch configuration names. This makes it difficult to tell which program is which. 

**To Reproduce**
1. Create a configuration file with several node programs
2. Start each program so more than one are running
3. Notice call stack displays index.js for all programs
![Screen Shot 2020-07-17 at 8 45 31 AM](https://user-images.githubusercontent.com/54443993/87787629-f641f500-c809-11ea-9d30-f24edbe68d7a.png)

Version: 1.47.0

**Additional context**

**Comment by connor4312** [comment]
Thanks for the issue, this is the same as https://github.com/microsoft/vscode-js-debug/issues/596#issuecomment-659562240
