### ISSUE TITLE
Debugger run is incomplete unless extension is disabled

### ISSUE THREAD

**Issue by sfsaccone** [microsoft/vscode-js-debug#637]
**Describe the bug**

When running a simple "launch" script the debugger stops at random parts of the program.

**To Reproduce**

* Set `debug.javascript.usePreview = true`
* Add this to `.vscode/launch.json`:

``` json
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Current File",
            "program": "${file}"
        }
```

Create a program:

``` js
console.log(1);
console.log(2);
console.log(3);
console.log(4);
console.log(5);
```
 
* Run/Start Debugging: output is random. Either nothing, just 1, just 1 and 2, etc. Example:

``` text
Debugger listening on ws://127.0.0.1:45371/607f76d3-6bc9-4212-9d48-ef5860f007c4
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
1
Waiting for the debugger to disconnect...
Process exited with code 0
2
```

* Run/Run Without Debugging: only prints "1".  It also says "Debugger listening" which is unexpected. 

``` text
Debugger listening on ws://127.0.0.1:35101/9eb22cd6-a1ae-4aad-b9e0-bba9af9a53a2
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Waiting for the debugger to disconnect...
Process exited with code 0
1
```

**Workaround**

Set `debug.javascript.usePreview = false`. Then everything works normally.

**Nightly Build**

The results were the same.

**Insiders 1.48**

Everything appears to work normally even when `debug.javascript.usePreview = true`. So these issues will probably just go away in the next version.

**Log File**

Attached.

[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode-js-debug/files/4941018/vscode-debugadapter-0.json.gz)

**VS Code Version:** 1.47.2

**Additional context**

The Node.js programs are on a remote machine.

* Local OS: Windows 10
* Remote OS: Ubuntu Server 20.04
* Remote Node.js: 14.5.0

**Comment by connor4312** [comment]
This was fixed in https://github.com/microsoft/vscode-js-debug/commit/02f9147456d23bdda8f81c55679060af995b2b1f (from a comment on the issue linked therein). I didn't bring that into the June recovery build as it was a relatively minor bug that involved changes to the lifecycle that had the potential to cause issue.

Thank you for filing the issue and including great repro steps and logs ❤️
