### ISSUE TITLE
Debug restart fails intermittently with Gatsby

### ISSUE THREAD

**Issue by aaronadamsCA** [microsoft/vscode-js-debug#639]
**Describe the bug**
Sometimes I "Debug: Restart" and Gatsby restarts, but other times it complains Gatsby is already running and dies. It's intermittent and I haven't identified the pattern.

**To Reproduce**
`launch.json` config:

```json
    {
      "name": "Gatsby Develop",
      "type": "node",
      "request": "launch",
      "protocol": "inspector",
      "cwd": "${workspaceFolder}/packages/web",
      "program": "${workspaceFolder}/packages/web/node_modules/.bin/gatsby",
      "autoAttachChildProcesses": true,
      "args": ["develop", "--inspect-brk"],
      "stopOnEntry": false,
      "runtimeArgs": ["--nolazy"],
      "sourceMaps": false
    },
```

Steps:

1. Start Gatsby
2. Restart Gatsby occasionally, until failure

**Log File**
```txt
Killed
node@b068659a24b1:/workspace/packages/web$  cd /workspace/packages/web ; env 'NODE_OPTIONS=--require "/home/node/.vscode-server/bin/17299e413d5590b14ab0340ea477cdd86ff13daf/extensions/ms-vscode.js-debug/src/bootloader.bundle.js" ' 'VSCODE_INSPECTOR_OPTIONS={"inspectorIpc":"/tmp/node-cdp.129-78.sock","deferredMode":false,"waitForDebugger":"","execPath":"/usr/local/bin/node","onlyEntrypoint":false,"fileCallback":"/tmp/node-debug-callback-610ebce78231d810"}' /usr/local/bin/node --nolazy ./node_modules/.bin/gatsby develop --inspect-brk 
Debugger listening on ws://127.0.0.1:33469/f543f57a-583b-42c1-b6a5-ad50524899cd
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

 ERROR 

Looks like develop for this site is already running. Try visiting http://localhost:8000/ maybe?

Debugger listening on ws://127.0.0.1:33469/f543f57a-583b-42c1-b6a5-ad50524899cd
For help, see: https://nodejs.org/en/docs/inspector
```

**VS Code Version:** 1.47.2

**Comment by aaronadamsCA** [comment]
I've got a trace; I'm not sure it's going to be much help here, but let me know and I can send it in.

**Comment by connor4312** [comment]
Thanks @aaronadamsCA. I was unable to reproduce what you were seeing locally, but have a strong suspicion around what was going on and added a fix in the linked commit. If you are able to, please try the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) (after 5 PM PST today) and let me know if you hit this again.

**Comment by connor4312** [comment]
@aaronadamsCA did this end up fixing the problem for you?

**Comment by aaronadamsCA** [comment]
@connor4312 I don't actually know yet; Gatsby debugging is now broken completely for me, due to an apparent bug in Gatsby:

https://github.com/gatsbyjs/gatsby/issues/26708

They closed it even though the problem still exists. I'm having great luck with debugging, ha. I still have this issue saved to revisit once the other issue is solved and I can test again. Thanks!

**Comment by connor4312** [comment]
Thanks, I will comment on the issue. I'll mark this as verified for the moment, we can reopen it later if needed.

**Comment by aaronadamsCA** [comment]
@connor4312 Add this issue to the list of things that turned out to be Gatsby bugs!

https://github.com/gatsbyjs/gatsby/issues/26214

That said, even when this does happen it now seems to recover a lot quicker; I can debug again within a few seconds, where I don't believe I could previously.

Thank you for this, and for your assistance in the other thread! I am up and running with the new debugger and it's working great.

**Comment by connor4312** [comment]
Ahh, okay, interesting. I would have assumed they started up and threw that error when trying an in-use port. Oh well, this led to better code for our debugger, so I'll call it a win 😄
