### ISSUE TITLE
Remaining skipFiles work

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#64]
To track work remaining for skipFiles. Started with https://github.com/microsoft/vscode-pwa/pull/48

https://github.com/microsoft/vscode-pwa/pull/48#discussion_r340360799

- [ ] Passing unit tests
- [ ] Passing integration tests
- [ ] Error handling (don't show user stacktrace when error occurs)
- [ ] Browser launch support
- [ ] Browser attach support
- [ ] Dynamic toggling of skipFiles during debug session

**Comment by Shenniey** [comment]
- [ ] Passing unit tests
- [ ] Passing integration tests
- [ ] Error handling (don't show user stacktrace when error occurs)
- [ ] Browser launch support
- [ ] Browser attach support
- [ ] Dynamic toggling of skipFiles during debug session

**Comment by connor4312** [comment]
Did we end up finishing some/all of these?

**Comment by roblourens** [comment]
Yes it's done
