### ISSUE TITLE
debugger keeps running in an infinite loop

### ISSUE THREAD

**Issue by uttamraj-pando** [microsoft/vscode-js-debug#642]
**Describe the bug**
when I click on debugging a nodejs App,the debugger runs into an infinite loop

**To Reproduce**
1.start a nodejs app using the below command
`npx nodemon --inspect-brk=9229 <nodejs_filename>`
2.attach the debugger to the nodejs process using the below debug config:
`{
                "type": "node",
                "request": "attach",
                "name": "process_A",
                "port": 9229,
                "skipFiles": [
                    "<node_internals>/**"
                ],
                "restart": true
            }`
3.upon attaching the debugger,the debugger runs into an infinite loop
**Log File**
sometimes also getting the below error
`Exception has occurred: ReferenceError: process is not defined
  at <anonymous>:1:15
    at process.EventEmitter (events.js:26:22)
    at setupProcessObject (internal/bootstrap/node.js:335:18)
    at startup (internal/bootstrap/node.js:31:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
`

**VS Code Version:** 
Version: 1.47.2
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:18:50.054Z (4 days ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

**Additional context**
this bug was not intermittent and is occuring only after the recent version update

**Comment by connor4312** [comment]
> upon attaching the debugger,the debugger runs into an infinite loop

What do you mean by this?

> Exception has occurred: ReferenceError: process is not defined at 

Thanks for the info -- I didn't think that would ever show up in the console. It should not affect debugging, but is ugly and I will hide it.

**Comment by uttamraj-pando** [comment]
> What do you mean by this?
The debugger doesnot stop,debugger loops through some files called called VM...<some_number>
> I didn't think that would ever show up in the console. It should not affect debugging, but is ugly and I will hide it.
sometimes instead of looping it stops at some internal file and shows the above error

**Comment by connor4312** [comment]
I'm still not sure I understand what you mean. Can you take a screen recording of what you're seeing? (https://gifcap.dev/ is helpful)

**Comment by connor4312** [comment]
You can drag it into the comment text area on Github

**Comment by uttamraj-pando** [comment]
![Screen Recording 2020-07-20 at 11 34 24 PM](https://user-images.githubusercontent.com/63234471/87971111-74401d80-cae2-11ea-8077-0a909e5ce99f.gif)

**Comment by connor4312** [comment]
Okay, thanks. You can get around that for now by unchecking `Uncaught Exceptions` in the breakpoints view. I'll put a fix for that in soon.

**Comment by uttamraj-pando** [comment]
thank you @connor4312

**Comment by uttamraj-pando** [comment]
Hi @connor4312 
I disabled both caught and uncaught exception in the vscode debugger as can be seen below and it works perfectly now.Feel free to close the issue as it worked correctly after setting the correct debug config.sorry for the inconvenience caused.

<img width="435" alt="Screenshot 2020-07-21 at 12 19 35 AM" src="https://user-images.githubusercontent.com/63234471/87974685-13b3df00-cae8-11ea-833c-d3a26d17442c.png">

**Comment by connor4312** [comment]
No worries, it shouldn't have been a problem in the first place 🙂 fixed in the next nightly
