### ISSUE TITLE
"Open & Attach to URL" command

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-js-debug#646]
I sometimes have server scripts that I didn't run in the Debug terminal or don't output the server URL in a parseable format. In these cases I can attach to the server by opening a debug terminal and typing the URl then clicking on it, but it would be nice if there were a command to do that.

**Comment by connor4312** [comment]
Forgot there was an issue for this, added it in https://github.com/microsoft/vscode-js-debug/issues/657
