### ISSUE TITLE
Add backward compatibility for Console Domain and support of the Debugger.setBreakpointsActive method

### ISSUE THREAD

**Issue by RedMickey** [microsoft/vscode-js-debug#647]
Hello, this is [Cordova Tools](https://github.com/microsoft/vscode-cordova) team. We are adapting debugging of Ionic and Cordova apps on iOS to `js-debug` approach. We use [ios-webkit-debug-proxy](https://github.com/google/ios-webkit-debug-proxy) tool to be able to debug iOS apps via Chrome Debug Protocol. IWDP uses quite old version of Chrome Dev Tools and requires deprecated [`Console Domain`](https://chromedevtools.github.io/devtools-protocol/tot/Console/) to process console messages. But `js-debug` doesn't support this domain. It would be awesome if it had backward compatibility for old `Console Domain`.
We also found out that IWDP requires the debugger to send the [`Debugger.setBreakpointsActive`](https://chromedevtools.github.io/devtools-protocol/tot/Debugger/#method-setBreakpointsActive) message in order to activate breakpoints, but `js-debug` doesn't use it.
According to these unsupported methods we could try to implement them on our [vscode-cdp-proxy](https://github.com/microsoft/vscode-cdp-proxy) side, but since the debugger counts messages ids, we can break the ids order when we inject additional messages to the original sequence. We think that adding of additional messages from our side is fairly unreliable.
We'd like to discuss how it is possible to implement the support of the `Console Domain` (at least [`Console.enable`](https://chromedevtools.github.io/devtools-protocol/tot/Console/#method-enable) method at the beginning of debugging) and `Debugger.setBreakpointsActive` method.
At the current version of the Cordova Tools extension we use `vscode-chrome-debug-core` and it debugs iOS apps without problems. I attach logs of CDP messages for `vscode-chrome-debug-core` and `js-debug` to make it easier to find difference between these approaches:
- [vscode-chrome-debug-core logs](https://github.com/microsoft/vscode-js-debug/files/4953379/logCor.txt)
- [js-debug logs](https://github.com/microsoft/vscode-js-debug/files/4953381/logCor3042.txt)

**Comment by connor4312** [comment]
Implemented in the proxy https://github.com/microsoft/vscode-js-debug/pull/693#issuecomment-682491122
