### ISSUE TITLE
Cannot run Chrome debug on MacOs 

### ISSUE THREAD

**Issue by ericklind** [microsoft/vscode-js-debug#648]
**Describe the bug**
Cannot run Chrome debug on MacOs (10.15.6) on VS Code version 1.47.2 
Throws: Unable to launch browser: "spawn ENOTDIR"

**To Reproduce**
Using the following config settings:
```
{
"version": "0.2.0",
    "configurations": [
        {
            "name": "Chrome (Mac)",
            "type": "chrome",
            "request": "launch",
            "runtimeExecutable": "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceRoot}/src/index.js"
        }
    ]
}
```

1. Choose Debug profile 
2. Hit F5
3. Error is thrown.

**Log File**
[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode-js-debug/files/4956053/vscode-debugadapter-0.json.gz)

**VS Code Version:** 10.47.2

**Additional context**

**Comment by connor4312** [comment]
This is because your `webRoot` is a file. It should be a directory.

**Comment by ericklind** [comment]
Ah. Didn't know that. Now it's working as expected. Thanks for tip.
