### ISSUE TITLE
js-debug doesn't support custom types of variable scopes in the "VARIABLES" tab

### ISSUE THREAD

**Issue by RedMickey** [microsoft/vscode-js-debug#651]
Hello, this is [Cordova Tools](https://github.com/microsoft/vscode-cordova) team. While debugging an Ionic app on an iOS device we found out that `js-debug` cannot display the `globalLexicalEnvironment` scope name. It just displays an empty string. We tried to debug the same app using `vscode-chrome-debug-core` and it displayed the name of the scope correctly.

This table illustrates the difference between `js-debug` and `vscode-chrome-debug-core`
|js-debug|vscode-chrome-debug-core|
|---|---|
|![Screen Shot 2020-07-22 at 16 44 32](https://user-images.githubusercontent.com/33267199/88183905-be3c1700-cc3a-11ea-95b7-504ef1f42e1e.png)|![Screen Shot 2020-07-22 at 16 43 22](https://user-images.githubusercontent.com/33267199/88183866-aebcce00-cc3a-11ea-8308-ad4b1964bd44.png)|

We also found out that `vscode-chrome-debug-core` [uses pure scope types from a CDP message](https://github.com/microsoft/vscode-chrome-debug-core/blob/master/src/chrome/stackFrames.ts#L138-L142) whereas `js-debug` [supports the limited list of scope types](https://github.com/microsoft/vscode-js-debug/blob/master/src/adapter/stackTrace.ts#L193-L237).
We believe that it would be great if `js-debug` supports custom types of variable scopes.

**VS Code Version:** 1.47.2

**Comment by connor4312** [comment]
Fixed in the next nightly build

**Comment by isidorn** [comment]
A bit hard to verify, since the steps are tricky.
@RedMickey can you please try this with latest vscode insiders and let us know if all is good? Thanks!
https://code.visualstudio.com/insiders/

**Comment by RedMickey** [comment]
@isidorn, I tried a new version of `js-debug`, now it works properly, thank you.

**Comment by isidorn** [comment]
Great, thanks for letting us know. Adding verified label
