### ISSUE TITLE
you broke source maps

### ISSUE THREAD

**Issue by 4r7d3c0** [microsoft/vscode-js-debug#653]
can you make source maps working again before the update to vs code it was fine now it's broken 

```
import { arch } from 'os'

console.log(arch())
``` 

it shows generated file instead which I can't edit 

```
const { arch } = require('os');

console.log(arch())
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImpzLmpzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFBLE1BQU0sQ0FBQyxDQUFDLENBQUMsSUFBSSxDQUFDLENBQUMsQ0FBQyxJQUFJLENBQUMsQ0FBQyxFQUFFOztBQUV4QixPQUFPLENBQUMsR0FBRyxDQUFDLElBQUksQ0FBQyxDQUFDIiwic291cmNlUm9vdCI6Ii9Vc2Vycy9hbnRvbi9hcnRkZWNvL3R5cGFsL3QiLCJzb3VyY2VzQ29udGVudCI6WyJpbXBvcnQgeyBhcmNoIH0gZnJvbSAnb3MnXG5cbmNvbnNvbGUubG9nKGFyY2goKSkiXX0=
```

Version: 1.47.1

![image](https://user-images.githubusercontent.com/60678477/88308111-53abd980-cd15-11ea-8f32-c1f78a11b3e1.png)

this wasn't the case before this debugger was introduced into vs code
https://sokra.github.io/source-map-visualization/#base64,Y29uc3QgeyBhcmNoIH0gPSByZXF1aXJlKCdvcycpOwoKY29uc29sZS5sb2coYXJjaCgpKQovKiBiYXNlNjQgc291cmNlIG1hcCByZW1vdmVkICov,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImpzLmpzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFBLE1BQU0sQ0FBQyxDQUFDLENBQUMsSUFBSSxDQUFDLENBQUMsQ0FBQyxJQUFJLENBQUMsQ0FBQyxFQUFFOztBQUV4QixPQUFPLENBQUMsR0FBRyxDQUFDLElBQUksQ0FBQyxDQUFDIiwic291cmNlUm9vdCI6Ii9Vc2Vycy9hbnRvbi9hcnRkZWNvL3R5cGFsL3QiLCJzb3VyY2VzQ29udGVudCI6WyJpbXBvcnQgeyBhcmNoIH0gZnJvbSAnb3MnXG5cbmNvbnNvbGUubG9nKGFyY2goKSkiXSwiZmlsZSI6ImV4YW1wbGUuanMifQ==,aW1wb3J0IHsgYXJjaCB9IGZyb20gJ29zJwoKY29uc29sZS5sb2coYXJjaCgpKQ==

**Comment by connor4312** [comment]
thanks for the issue, can you capture a trace log using the instructions from the issue template?

>If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by connor4312** [comment]
Actually, nevermind, I can see what I need from the data in the URL you linked. This was fixed yesterday in https://github.com/microsoft/vscode-js-debug/commit/79fe0a95a5d65a6253ad2cc885489fd57cd83801, you can use the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) of the extension which has a fix for this scenario.

**Comment by 4r7d3c0** [comment]
OK thanks sorry for not following the template
