### ISSUE TITLE
After update working node js process no longer hits any breakpoints

### ISSUE THREAD

**Issue by makingglitches** [microsoft/vscode-js-debug#655]
**Describe the bug**
The program is short and runs fine in both terminal and vs code. Problem. I would like the debugger to hit breakpoints.
After the update this resulted basically not being able to stop the code at any editor indicated breakpoints so as to fire up ye olde object inspector.

**To Reproduce**

**Create a happy launch.json file like this one:**

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program ",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}\\parseuszips.js"
        }
    ]
}
```

**Then create a simple all ordinary node file like this one:**

```
const fs = require('fs')

var json = fs.readFileSync("us-zip-code-latitude-and-longitude.json")

var collection = JSON.parse(json)

console.log('//datasource retrieved from \
//https://public.opendatasoft.com/explore/dataset/us-zip-code-latitude-and-longitude/api/\
class USZips\
{\
')

for (i in collection[0])
{
    console.log(i)
}
```

Then click start in any old place but you can specifically select the configuration under the debug section vscode next to the nice green arrow to the left of the title "launch program"

What happens is the code runs. yay.

**Log File**

C:\Program Files\nodejs\node.exe c:\Users\Rescue\Documents\QrCode\parseuszips.js
Debugger listening on ws://127.0.0.1:56803/2e5c244e-7426-45b2-939e-f58f533b8bf5
For help, see: https://nodejs.org/en/docs/inspector
datasetid
parseuszips.js:10
recordid
parseuszips.js:10
fields
parseuszips.js:10
geometry
parseuszips.js:10
record_timestamp
parseuszips.js:10
(node:19536) ExperimentalWarning: The fs.promises API is experimental
<node_internals>/internal/process/warning.js:18
(node:19536) ExperimentalWarning: The fs.promises API is experimental

However i wish I could attach pictures to show that I try to pause the code multiple places and it just bypasses them this is a recent development, as in as of the latest patch to 1.47.

**VS Code Version:**1.47

**Comment by makingglitches** [comment]
This seems like a race condition.
The one of the breakpoints suddenly decided to start working but further down past the load of a fricking 15mb file and subsequent parsing. Seems to suggest that the debugger attaching is happening after this point, as if some kind of a delay is happening. Anyway that's my thoughts and an update.

**Comment by connor4312** [comment]
Thanks for the issue! Can you collect a trace log using these instructions?

>If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by Mewster** [comment]
> Thanks for the issue! Can you collect a trace log using these instructions?
> 
> > If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
> > ⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to [connor@xbox.com](mailto:connor@xbox.com)

I'm having the same issue. I'll try to send you the required logs to your mail

**Comment by connor4312** [comment]
Thanks for the emailed log, Mewster. In your email you mentioned that setting a breakpoint in one place worked, but setting it in another didn't. From what I see it looks like we found a location for the breakpoint in the sourcemap, but when setting it in Node it indicated that the location was invalid.

If you're able, could you also send the compiled contents of `Index.js` alongside the `Index.map.js` so I can check on what's happening here?

**Comment by Mewster** [comment]
I'm sending the files to your mail

**Comment by connor4312** [comment]
Thanks. @Mewster try setting `inlineSourceMap: true` in your tsconfig. If that doesn't work, please send over a log. Thanks! 🙂

**Comment by Mewster** [comment]
> @Mewster try setting `inlineSourceMap: true` in your tsconfig. If that doesn't work, please send over a log. Thanks!

Sent new logs

**Comment by connor4312** [comment]
Hm. Everything in there looks like it should like up. How are you launching the program -- just through `node myprogram.js` or are you using something like ts-node or babel to run it?

**Comment by Mewster** [comment]
> Hm. Everything in there looks like it should like up. How are you launching the program -- just through `node myprogram.js` or are you using something like ts-node or babel to run it?

I'm launching it in a docker container through a simple node command, and I can successfully attach to it and debug until vscode 1.46.1 

After I sent you the last log I also found that I could set a breakpoint inside one of the lambdas, but not on the code outside of it.

**Comment by Mewster** [comment]
If needed, I'm available to do more specific tests or debugging.

**Comment by connor4312** [comment]
Spent some time debugging with Mewster over email. The issue he's hitting seems like it may be a bug in V8 itself, we're following up.

Closing this issue as there's been no followup from the author.
