### ISSUE TITLE
VS Code debugger output and Node.js outputs differ with local npm modules

### ISSUE THREAD

**Issue by omgMath** [microsoft/vscode-js-debug#656]
**Describe the bug**

We use local node_modules (i.e. node_modules installed with e.g. `npm i ..\core`). We had mixed imports (e.g. we used `import {s} from "core/build/Singleton";` in the `project` directory, but still `import {s} from "../../core/build/Singleton";` in the `plugin` directory.

In that case, when run with the VS Code debugger (see `launch.json`), the output of the `plugin`'s `Main` is ` [] `. When run with pure `node` (`cd plugin & node ./build/Main.js`) the output is ` [ 1 ] `.
I would expect the output to be the same.

**To Reproduce**
Reproduction here: [https://github.com/omgMath/VSCode_Debugger_vs_Node_mismatch](https://github.com/omgMath/VSCode_Debugger_vs_Node_mismatch).

**VS Code Version:** 1.47.2

**Additional context**
Windows
node: v12.13.1
tsc: Version 3.7.5

**Comment by connor4312** [comment]
Thanks for the issue and repro! You get the fix by either:

1. Using `console: integratedTerminal` in your launch.json where the correct behavior is already present
1. Use the next [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) available after 5PM PST today
