### ISSUE TITLE
Add "open url" functionality to easily debug urls

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#657]

**Comment by connor4312** [comment]
There's a new `Debug: Open URL` command:

- If you have a url selected in your active text editor (either full https://... or a string in the form <hostname>:<port>) the command will open that automatically
- Otherwise, it opens a quick input. If you have a URL like that ^ in your clipboard, it will be auto-filled. Otherwise the last URL you opened will be prefilled.

**Comment by alexr00** [comment]
Tried to verify with these steps:

1. Open a typescript file.
2. Paste this in: `const this_is_a_url: string = 'https://github.com'`
3. Select the "https://github.com" pasted above.
4. Run command Developer: Open Url

Expected: selected URL is opened
Actual: Quick input asking for a URL is opened.

**Comment by connor4312** [comment]
@alexr00 the command is `Debug: Open URL`. `Developer: Open URL` is an existing command registered by VS Code 🙂
