### ISSUE TITLE
Error running browser on Remote Debugging in Docker container (New JavaScript Debugger)

### ISSUE THREAD

**Issue by 80sax** [microsoft/vscode-js-debug#659]
Hello, 
My remote debugger stopped working since update to VSC 1.47.2 . Reading the release notes I learnt that the new JavaScript Debugger is now the default so I set "debug.javascript.usePreview": false and it works again, so I guess the issue is in the New JavaScript Debugger.

**Steps to reproduce the behavior:**
- My setup is very simple, it launches Chrome to debug an Angular application running in a remote container.
- My [launch.json](https://github.com/microsoft/vscode-js-debug/files/4974787/launch.json.txt) and [tasks.json](https://github.com/microsoft/vscode-js-debug/files/4974789/tasks.json.txt) files are based at https://github.com/microsoft/vscode-recipes/tree/master/Angular-CLI . 
- When the debugger tries to launch chrome a notification appears:
Error running browser: Cannot call write after a stream was destroyed
Source: JavaScript Debugger Companion Extension (Extension)
![image](https://user-images.githubusercontent.com/24919849/88446244-00f22080-cdee-11ea-96af-c3a58f857525.png)
- The debug session remains active but useless and it does not launch chrome

**Log File**
[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode-js-debug/files/4974778/vscode-debugadapter-0.json.gz)

**VS Code Version:** 
Version: 1.47.2
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:22:15.161Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-42-generic snap

**Local environment**
Ubuntu: 18.04.2 LTS
Kernel: 5.4.0-42-generic
Chrome: 84.0.4147.89 (Official Build) (64-bit)
Docker: 19.03.12

**Remote environment**
Alpine Linux: 3.11
Node: 12.18.2

Thanks!

**Comment by connor4312** [comment]
Thanks for the issue! I'm guessing this is a result of the pipe to Chrome failing for some reason locally. Two things to try:

1. Can you try specifying the `runtimeExecutable` in your launch config as the path to your local Chrome binary? (You should be able to launch chrome from the command line by running that binary)
1. If that doesn't work, can you try specifying some new/empty folder as the `userDataDir` option in your launch config?

**Comment by connor4312** [comment]
Closing due to lack of info. @80sax if you're able to try that out ^ let me know.

**Comment by 80sax** [comment]
@connor4312 
Thanks for your answer, I have tried with your suggestions and they do not work for me, I also have tried with attach mode without success.

Funny thing is that with the setting ["debug.javascript.usePreview": false] both modes (launch and attach) work fine.

Did the new js-debug extension change the pipe to chrome? Because the problem could be that when I run Chrome from the terminal it runs fine but a couple of weird ERROR messages are displayed:

`~$google-chrome
[27358:27358:0817/152902.119126:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[27361:27380:0817/152903.238804:ERROR:nss_util.cc(283)] After loading Root Certs, loaded==false: NSS error code: -8018`

After close Chrome
`~$[0817/152904.972081:ERROR:nacl_helper_linux.cc(308)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly`

**Comment by connor4312** [comment]
> Did the new js-debug extension change the pipe to chrome?

Yea, we use --remote-debugging-pipe by default now for security. The extraneous error messages should not matter, but maybe something on your machine is interfering with this.

Previously / on stable, we didn't support attaching or using a port, but as of last week this is now supported. If you'd like to try this out, you can do the following:

1. Use the latest [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) on your _remote_ workspace
1. Update the extension `js-debug-companion` to 1.0.4 on your _local_ workspace

**Comment by 80sax** [comment]
Hi @connor4312 
I have updated `js-debug-companion` and switched to the js-debugger nightly build and the only difference is that in attach mode the debugger is able to attach but still is not able to hit the breakpoints (they appear in grey).

I think is not related with find the right chrome executable because when I specify a wrong path (e.g. /tmp/google-chrome) with `runtimeExecutable` the error message is:
`Error running browser: spawn /tmp/google-chrome ENOENT`

Anyway the problem may be on my machine because if I run chrome from terminal with the following arguments (I have extracted from the vscode-debugadapter.json file generated by trace):
`google-chrome  --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-default-apps --disable-dev-shm-usage --disable-renderer-backgrounding --disable-sync --metrics-recording-only --no-first-run --no-default-browser-check "about:blank" --remote-debugging-pipe`
My CPU load goes to 100% and get a stream of messages with the following error:
`[6210:6295:0818/193442.937835:ERROR:devtools_pipe_handler.cc(229)] Could not write into pipe`
Actually I get the error just with the `--remote-debugging-pipe` argument.

What is the difference between `"type": "chrome",` and `"type": "pwa-chrome"` in launch.jason? Because although with pwa-chrome I'm still not able to launch, I'm able to attach and hit the breakpoints.

**Comment by 80sax** [comment]
I just noticed that I cannot use `"trace":"verbose"` with `"type": "pwa-chrome"`

**Comment by 80sax** [comment]
> This probably means your configuration needs a tweak. If you send over a new trace log I can provide pointers.
Here is a new trace log
[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode-js-debug/files/5192176/vscode-debugadapter-0.json.gz)

I have update the js-debug-companion to 1.0.7 and still using the nightly build.
I confirm that the attach mode works fine (I had a mistake in my configuration and that is why the breakpoint wasn't hit) but the launch mode still doesn't work

If I need to provide more info please let me know

**Comment by connor4312** [comment]
Hm, okay, thanks. So it looks like the pipe is not getting set up.

Do you have Code and/or Chrome installed from Snap, by any chance? I know we've seen problems in the past with snap interfering with stdio.

**Comment by 80sax** [comment]
Not sure
Well my distro is Zorin, it is based on Ubuntu 18.04 
I download the .deb file from https://www.google.com/chrome/ and when I run the file it opens a kind of software store program https://zorinos.com/help/install-apps/

So I do not know if this "software store" runs snap under the hood.

**Comment by 80sax** [comment]
Anyway, the attach mode is working fine, and I get used to it.
As you say it must be something in my environment, so we can close the issue and if I find the cause of my problem I will let you know.
