### ISSUE TITLE
Debugger does not correctly handle inline UTF-8 source maps

### ISSUE THREAD

**Issue by mrjogo** [microsoft/vscode-js-debug#662]
**Describe the bug**
Recently, attaching the debugger to Node programs output with esm (`node --inspect-brk -r esm index.js`) stopped working correctly. This seems to coincide with Node Debug (https://github.com/Microsoft/vscode-node-debug2) starting to forward to this extension by default.

I attach to the process with this `launch.json` config:

```json
{
  "type": "node",
  "request": "attach",
  "name": "Attach to Program",
  "skipFiles": [
    "<node_internals>/**"
  ]
}
```

In the debug console, I get the message `Could not read source map for file:///usr/src/sourcemap-test/index.js: Unexpected token % in JSON at position 0` for every source file. When I place a breakpoint, that breakpoint gets hit in the transpiled file, not the original, which includes the inline sourcemap:

```javascript
debugger;console.log("Hello");
console.log("Goodbye");
//# sourceMappingURL=data:application/json;charset=utf-8,%7B%22version%22:3,%22sources%22:%5B%22file:///usr/src/sourcemap-test/index.js%22%5D,%22names%22:%5B%5D,%22mappings%22:%22AAAA;AACA;AACA%22%7D
```

My guess is that this is not handling URI encoded inline source maps correctly, and choking on the first `%` (for a previous, very similar issue, see https://github.com/microsoft/vscode-chrome-debug-core/issues/343). The issue goes away when debugging with `"debug.javascript.usePreview": false`

I created an example project to demonstrate the issue: [sourcemap-test.zip](https://github.com/microsoft/vscode-js-debug/files/4978237/sourcemap-test.zip)

**To Reproduce**
1. Download the project, unzip, and run `npm i` to install `esm`
1. Make sure your settings have `"debug.javascript.usePreview": true`
1. Start the project with `npm run debug`
1. With the `launch.json` config above, start the debugger
1. See  `Could not read source map...` in the Debug Console, and that the file the debugger breaks at is the transpiled one

**Log File**

[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode-js-debug/files/4978244/vscode-debugadapter-0.json.gz)

**VS Code Version:** 1.47.2

**Additional context**
Also occurs on nightly build of extension.

**Comment by connor4312** [comment]
Thanks for the issue, will be fixed in the next [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension)
