### ISSUE TITLE
typo for node versionHint.description

### ISSUE THREAD

**Issue by andyboyne** [microsoft/vscode-js-debug#663]
https://github.com/microsoft/vscode-js-debug/blob/3ca8e3b59102fc948538b04530d561512b62cbdb/src/build/strings.ts#L215

Whilst trying to get 1.47.2 working when debugging electron 5 I noticed launch.json shows nodeVersionHint as being an invalid property. There is a typo as referenced above.

**Comment by connor4312** [comment]
The `strings` is not where this comes from.

Maybe the problem you were running into was because your debug `type` is `node` and not the newer `pwa-node`?

**Comment by andyboyne** [comment]
I was unaware of pwa-node as an option, maybe I missed it in the release docs.

However, setting it to pwa-node like so:

`      "type": "pwa-node",
      "nodeVersionHint": 12,`

Causes the debugger in vscode to fail to attach.

```
internal/modules/cjs/loader.js:662
    throw err;
    ^

Error: Cannot find module '"c:/Users/aboyne/AppData/Local/Programs/Microsoft'
Require stack:
- internal/preload
```


Setting those debug options to 
```
      "type": "node",
      "nodeVersionHint": "12.0.0",
```

allows the application to start, but i get warnings in the launch.json.

**Comment by andyboyne** [comment]
Update:

Settings the nodeVersionHint to the string "12.0.0" works with "pwa-node", however I now get "Incorrect Type. Expected Number" in the launch.json.

**Comment by connor4312** [comment]
Yea, that should be given as a number, not a string

**Comment by andyboyne** [comment]
... but if I give it as a number it fails to launch with: 

```
internal/modules/cjs/loader.js:662
    throw err;
    ^

Error: Cannot find module '"c:/Users/aboyne/AppData/Local/Programs/Microsoft'
Require stack:
- internal/preload
```

**Comment by connor4312** [comment]
That means you should set `nodeVersionHint` at 10 rather than 12

**Comment by andyboyne** [comment]
how would i know any of this?

**Comment by connor4312** [comment]
This is there reference issue: https://github.com/microsoft/vscode/issues/102035#issuecomment-656801666

Detection should automatically work in the latest nightly, so manual adding the hint will no longer be necessary.
