### ISSUE TITLE
Webview wrapper debug state gets out of sync

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode-js-debug#664]
**Describe the bug**
Sometimes the wrapper is out of sync with the processes list below it 
![image](https://user-images.githubusercontent.com/4544166/88560625-63207080-cffc-11ea-886f-cc6c4ee14977.png)
![image](https://user-images.githubusercontent.com/4544166/88560647-6ae01500-cffc-11ea-9d0d-5e0730c53ed6.png)

**To Reproduce**
1. Set a bunch of breakpoints in various ext host functions
2. Press continue you will see sometimes the state is in sync other times it isn't

**Log File**
[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode-js-debug/files/4982858/vscode-debugadapter-0.json.gz)
[vscode-debugadapter-1.json.gz](https://github.com/microsoft/vscode-js-debug/files/4982859/vscode-debugadapter-1.json.gz)

**VS Code Version:** Version: 
1.48.0-insider (user setup)
Commit: 731f9c25632dbbf01ee3a7892ad9d2791fe0260c
Date: 2020-07-24T05:57:10.466Z
Electron: 9.1.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Additional context**
On JS-debug nightly

**Comment by connor4312** [comment]
I noticed this is actually an issue in VS Code -- VS code wants to hide the badge of the parent session when it's no paused and has no children. I fixed this, but I wonder if maybe we should always show "running" now that we have compact sessions (so debuggers can generally hide logical wrapper sessions). cc @isidorn

**Comment by isidorn** [comment]
@connor4312 yes, I think we could always show the `running` badge. Can you file an issue for this? Thanks
