### ISSUE TITLE
WW Extension Host: "No debug adapter, can not send 'terminate'"

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-js-debug#665]
JS debug with webworker ext host sometimes looses connection to host. 

I think I close the extension development window, but js debug doesn't automatically detach, so I end up in a state where I cannot "detach" without reloading the window. 

![image](https://user-images.githubusercontent.com/8586769/88597830-fc5f7f00-d01c-11ea-82a1-477341547e81.png)

**Comment by connor4312** [comment]
Thanks for the issue, this is the same as https://github.com/microsoft/vscode/issues/102037 (but good to have another repro case)

/duplicate

**Comment by JacksonKearl** [comment]
> /duplicate
