### ISSUE TITLE
Unbound breakpoint using VS Code for MAC (1.47.3) when debugging with Chrome

### ISSUE THREAD

**Issue by ah6511** [microsoft/vscode-js-debug#672]
After upgrading to 1.47, now I can't debug Angular app with Chrome on Mac using VS Code for MAC b/c the breakpoints are unbound. I tried to follow https://github.com/microsoft/vscode/issues/102493 and no luck.
[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode-chrome-debug/files/4995058/vscode-debugadapter-0.json.gz)
[vscode-debugadapter-1.json.gz](https://github.com/microsoft/vscode-chrome-debug/files/4995059/vscode-debugadapter-1.json.gz)

- VS Code Version: 1.47.3
- Log file (set `"trace": true` in launch config):

Steps to reproduce:

1. launch.json:
{
"name": "Launch using Chrome",
  "request": "launch",
  "type": "pwa-chrome",
  "url": "http://localhost:4200",
   "sourceMaps": true,
   "trace": true,
   "resolveSourceMapLocations": [
        "${workspaceFolder}/**",
        "!**/node_modules/**"
    ],
  "webRoot": "${workspaceFolder}"
}
2.

**Comment by connor4312** [comment]
```
"resolveSourceMapLocations": [
"${workspaceFolder}/",
"!/node_modules/**"
],
```

This is a [glob pattern](https://globster.xyz/), so just `${workspaceFolder}` won't match anything. It looks like these are actually (close to) the default js-debug values, so you should be safe to just delete this line.

Let us know if you still have issues.
