### ISSUE TITLE
Could not attach to main target

### ISSUE THREAD

**Issue by cruzeflute** [microsoft/vscode-js-debug#674]
My project can be debugged on my old computer, but can't be debugged on my new computer, showing an error:

> Error procession launch:Error:Could not attach to main target
at c:\Users\cr\AppData\Local\Programs\Microsoft VS
Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:1:33351
at async _.prepareLaunch (c:\Users\cr\AppData\Local\Programs\Microsoft VS 
Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:15:2620406)
at async _.launch (c:\Users\cr\AppData\Local\Programs\Microsoft VS 
Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:15:2621006)
at async t.Binder.captureLaunch (c:\Users\cr\AppData\Local\Programs\Microsoft 
VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:73:25725)
at async t.Binder._launch (c:\Users\cr\AppData\Local\Programs\Microsoft VS 
Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:73:25296)
at async Promise.al (index 6)
at async t.Binder._boot (c:\Users\cr\AppData\Local\Programs\Microsoft VS 
Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:73:245556)
at async t.default._onMessage (c:\Users\cr\AppData\Local\Programs\Microsoft 
VS 
Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:15:2459787)

my launch.json:

> {
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceRoot}/bin/",
            "file": "${workspaceRoot}/bin/index.html",
            "userDataDir": "${workspaceRoot}/.cr/chrome",
            "runtimeArgs": [
				"--allow-file-access-from-files",
				"--allow-file-access-frome-files",
				" --disable-web-security"
			],
			"sourceMaps": true,
			"sourceMapPathOverrides": {
				"src/*": "${workspaceRoot}/src/*"
			}
        }
    ]
}

VS Code:1.47.3
Debugger for Chrome:4.12.9
OS:Windows 10
Goole Chrome:83.0.4103.61

**Comment by connor4312** [comment]
This is fixed in the latest [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) 🙂
