### ISSUE TITLE
Feature Request: Log Points - Source Maps

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode-js-debug#681]
# Context
I implemented [an extension](https://github.com/hediet/vscode-realtime-debugging) that displays logs next to the source.
It used to work very well with logpoints:

![logpoints](https://user-images.githubusercontent.com/2931520/89204343-3c42db00-d5b6-11ea-82c4-8699354ae81c.gif)

However, in the new debug adapter, log points no longer emit their source origin with the `output` event. Instead, they report a `*.cdb` file as their source:
```json
{"seq":173,"type":"event","event":"output","body":{"category":"stdout","output":"11\n","source":{"name":"<node_internals>/logpoint-ac95189.cdp","path":"<node_internals>/logpoint-ac95189.cdp","sourceReference":633563558},"line":1,"column":9}}
```

Ordinary console logs and log points in the old node debug adapter emit this event:
```json
{"seq":172,"type":"event","event":"output","body":{"category":"stdout","output":"10\n","source":{"name":"index.js","path":"c:\\dev\\demo\\index.js","sourceReference":0},"line":11,"column":17}}

```

It would be awesome if I could make my extension work again with logpoints.

The content of such a cdb file looks like this:
```js
console.log("%O", (() => {
  try {
    return i;
  } catch (e) {
    return e.stack || e.message || String(e);
  }
})())
//# sourceURL=logpoint-ac95189.cdp
```

# Request

It would be awesome if you could make it possible again to retrieve the file and line the log point was created for from the output event.
One way to do this could be by adding some meta information to the cdp file:
```js
// meta: { "sourceFile": "C:\\dev\\demo\\index.js", "line": 10 }
console.log("%O", (() => {
  try {
    return i;
  } catch (e) {
    return e.stack || e.message || String(e);
  }
})())
//# sourceURL=logpoint-ac95189.cdp
```

Btw. this new debug adapter is awesome! It is a huge step forward for the debugging experience of javascript!

**Comment by hediet** [comment]
Logpoints / conditions are an ideal way to add temporary modifications to the source. I think they are way too underused for their potential.
I'm planning to create an extension that will make it much easier to add/modify/remove (conditional) log/breakpoints. 

Logpoints with side effects could also be used to let local objects escape so that they can be monitored during the following execution of the program. This is very useful for services that are rarely instantiated and held in local variables.

**Comment by connor4312** [comment]
I agree. Thanks for the good issue. I'm looking forward to seeing what you build 🙂

**Comment by connor4312** [comment]
Will be fixed in the next nightly build today at 5PM PST

**Comment by connor4312** [comment]
To verify: add a logpoint breakpoint, verify that the source position on the right hand side in the debug terminal is inside the source in which it's logged and not an ephemeral script.

**Comment by hediet** [comment]
Yes, thank you very much! [My realtime debugging extension](https://github.com/hediet/vscode-realtime-debugging) started to work with logpoints again without any change in the extension, so I assume everything works ;)

**Comment by connor4312** [comment]
thanks for confirming :)
