### ISSUE TITLE
Unbound breakpoint

### ISSUE THREAD

**Issue by splowman-FormFast** [microsoft/vscode-js-debug#682]
**Describe the bug**
Breakpoints are not getting bound (hit) for Angular 9 apps.

**To Reproduce**
1. Create an Angular 9 app with multiple applications
2. Create breakpoints
3. Notice the scripts are loaded correctly and you can break when creating a breakpoint in the loaded scripts but not the original source code

This issue exists for both chrome and edge.  This only started happening after latest VS code upgrade.

launch.json file
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
      {
          "type": "chrome",
          "request": "launch",
          "name": "Launch Chrome against localhost",
          "url": "http://localhost:4202",
          "webRoot": "${workspaceFolder}"
      }
  ]
}

**Comment by connor4312** [comment]
Please try the [nightly extension](https://github.com/microsoft/vscode-js-debug#nightly-extension) and see if this works there. If not, please provide a trace log using the instructions in the issue template.

**Comment by splowman-FormFast** [comment]
[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode-js-debug/files/5019309/vscode-debugadapter-0.json.gz)
I replaced the debugger extension with the nightly build one.  Same issue.  I then added a trace and enclosed the log for that trace here.

**Comment by connor4312** [comment]
I see you have two breakpoints in a folder `lib/gx-designer`, but there are no files from that folder being parsed at all. Perhaps something in your build setup is not generating sourcemaps for these files.

**Comment by splowman-FormFast** [comment]
The only change made is an upgrade to VS Code and then it fails.  I see that a few others are having this issue as well.

**Comment by connor4312** [comment]
Are you able to share a reproduction case for this -- either the repo where it happens or a simpler test case?

**Comment by splowman-FormFast** [comment]
No, sorry.  I wouldn't be allowed to share our code and it's in a private repo.  I can hit breakpoints if I navigate to the ts file in the 'Loaded Scripts' area but can't hit breakpoints on the original source code so I know the code files are loaded.  There just seems to be a disconnect between the loaded files and the source code files.

**Comment by connor4312** [comment]
Ah, okay, gotcha. What's the path of the .ts file in the "Loaded Scripts" view versus the expected one on disk? It sounds like they're different, so we can fix the issue by rectifying that difference.

**Comment by splowman-FormFast** [comment]
They are exactly the same paths.

**Comment by connor4312** [comment]
Can you add a `debugger;` statement inside the expected file where you place the breakpoint, and once you hit that grab the trace log and share it?

**Comment by splowman-FormFast** [comment]
[vscode-debugadapter-1.json.gz](https://github.com/microsoft/vscode-js-debug/files/5022951/vscode-debugadapter-1.json.gz)
I added the statement debugger: and it stopped on the loaded script file but not the original file.

**Comment by connor4312** [comment]
Okay, thanks! This looks like an issue that I believe I fixed this month. Can you use the nightly and send a new log? The log you sent up here https://github.com/microsoft/vscode-js-debug/issues/682#issuecomment-668288979 is from the non-nightly/stable versions.

**Comment by splowman-FormFast** [comment]
[vscode-debugadapter-3.json.gz](https://github.com/microsoft/vscode-js-debug/files/5023023/vscode-debugadapter-3.json.gz)
![image](https://user-images.githubusercontent.com/60358735/89314362-2c230e00-d63f-11ea-9c03-f07f0a0d5932.png)
![image](https://user-images.githubusercontent.com/60358735/89314404-393ffd00-d63f-11ea-9c95-a832db9eaff6.png)

The nightly debugger is installed and the stable version is disabled.  The issue is the same.

**Comment by connor4312** [comment]
Okay, thanks! I will look into this

**Comment by connor4312** [comment]
Also, you may be able to get around the issue for the moment by setting `"enableContentValidation": false`

**Comment by splowman-FormFast** [comment]
Thanks for the reply.  I get a property not allowed error when adding "enableContentValidation": false.  I'll just wait for a fix and put debugger; statements in place of breakpoints until then.

**Comment by ikilinc** [comment]
I have the same issue, its a angular 8 application generated with ng cli. My application is running inside WSL2.

i noticed that the breakpoint bounding works with edge but not with chrome, settings are the same.

{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch Edge",
      "request": "launch",
      "type": "pwa-msedge",
      "url": "http://localhost:4200",
      "webRoot": "${workspaceFolder}"
    },
    {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome against localhost",
      "url": "http://localhost:4200",
      "webRoot": "${workspaceFolder}"
    }
  ]
}

debuging with chrome dont work.
![image](https://user-images.githubusercontent.com/9822842/89382161-a2387b00-d6fa-11ea-8a2f-0fa9dee0fb73.png)

microsoft edge
![image](https://user-images.githubusercontent.com/9822842/89382280-e3308f80-d6fa-11ea-987f-e155f7325617.png)

**Comment by ikilinc** [comment]
@splowman-FormFast  if you have windows, try it to launch with edge, maybe firefox would work too.

**Comment by splowman-FormFast** [comment]
I have the same issue with Edge

**Comment by connor4312** [comment]
@splowman-FormFast it looks like your build is creating some interesting sourcemaps. For example you have a breakpoint in `designer.store.ts` which has a source URL like

```
webpack:///D:/repos/ProjectY.Angular/libs/gx-designer/feature-designer/src/lib/state/designer.store.ts
```

Which we map to 

```
D:/repos/ProjectY.Angular/D:/repos/ProjectY.Angular/libs/gx-designer/feature-designer/src/lib/state/designer.store.ts
```

using the default source map path override. Meanwhile you have other normal maps where `webpack:///` contains a relative path. You could try adjusting the the sourceMapPathOverrides to something like this to account for it:

```json
{
  "webpack:///${workspaceFolder}/*": "${workspaceFolder}/*",
  "webpack:///*": "${workspaceFolder}/*",
}
```
