### ISSUE TITLE
NodeJS debugging - VS Code Stable: Freezing, VS Code Insider: Exits Prematurely

### ISSUE THREAD

**Issue by Jebtrix** [microsoft/vscode-js-debug#695]
**Describe the bug**
When using internalConsole debugger and _lively_ console.log output the debugger will either freeze or exit prematurely. I encountered it with a simple cli utility I was working on but for simplicity I used the example code from issue [#103511](https://github.com/microsoft/vscode/issues/103511) which exhibits the same results.

```
for(let i = 0; i < 20000; i++)
{
    console.log(i);
}

```

**Log File**

|  VS Code | NodeJS vers  | JavaScript Debugger (Nightly)  |  Debugger Behavior | Trace Log  |
| ------------ | ------------ | ------------ | ------------ | ------------ |
| Stable v1.47.3 | v12.8.3  | Enabled  | Freezes  | [Trace Log](https://github.com/microsoft/vscode-js-debug/files/5053830/TRACE_vscode-1.47.3-stable_NodeJS-v12.8.3_Nightly-Extension.gz) |
| Stable v1.47.3 | v14.7.0  | Enabled  | Freezes  | [Trace Log](https://github.com/microsoft/vscode-js-debug/files/5053835/TRACE_vscode-1.47.3-stable_NodeJS-v14.7.0_Nightly-Extension.gz) |
| Stable v1.47.3 | v12.8.3  | Disabled  | Freezes  | [Trace Log](https://github.com/microsoft/vscode-js-debug/files/5053838/TRACE_vscode-1.47.3-stable_NodeJS-v12.8.3.gz) |
| Stable v1.47.3 | v14.7.0  | Disabled  | Freezes  | [Trace Log](https://github.com/microsoft/vscode-js-debug/files/5053840/TRACE_vscode-1.47.3-stable_NodeJS-v14.7.0.gz) |
| Insider v1.48.0 | v12.8.3  | Enabled  | Exits Prematurely | [Trace Log](https://github.com/microsoft/vscode-js-debug/files/5053857/TRACE_vscode-1.48.0-insider_NodeJS-v12.8.3_Nightly-Extension.gz) |
| Insider v1.48.0 | v14.7.0  | Enabled  | Exits Prematurely | [Trace Log](https://github.com/microsoft/vscode-js-debug/files/5053854/TRACE_vscode-1.48.0-insider_NodeJS-v14.7.0_Nightly-Extension.gz) |
| Insider v1.48.0 | v12.8.3  | Disabled  | Exits Prematurely | [Trace Log](https://github.com/microsoft/vscode-js-debug/files/5053860/TRACE_vscode-1.48.0-insider_NodeJS-v12.8.3.gz) | 
| Insider v1.48.0 | v14.7.0  | Disabled  | Exits Prematurely | [Trace Log](https://github.com/microsoft/vscode-js-debug/files/5053862/TRACE_vscode-1.48.0-insider_NodeJS-v14.7.0.gz) |

**VS Code Version:** 
Version: 1.47.3 (user setup)
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Version: 1.48.0-insider (user setup)
Commit: 2277c8e2a3e1cc630a6397301ba54a1dccd8a60d
Date: 2020-08-07T11:32:09.993Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by connor4312** [comment]
Wow, that's one good issue report, thank you!

The freezing issue you're seeing is https://github.com/microsoft/vscode/issues/103545.

The premature exit you're seeing is a different issue -- the program exits, but it takes time to flush output to VS Code. As of https://github.com/microsoft/vscode-js-debug/commit/02f9147456d23bdda8f81c55679060af995b2b1f we wait a little while for the flush to happen, but there's still a timeout which is hit.

It's my intention to refactor some of the console log handling, particularly for https://github.com/microsoft/vscode-js-debug/issues/412, but I will look at improving this as well. Particularly, for simple string-only logs we don't need to run async operations to display the log, so the two step claim-and-emit process can be optimized.

**Comment by Jebtrix** [comment]
Since my utility is cli I have to enable "console": "integratedTerminal" in launch.json to give user input. Debugger Console displays/mirrors terminal output and functions correctly in this configuration. Only default internalConsole does it. I noticed this by chance working on project from different PC with different launch.json. I look forward to the refactor!
