### ISSUE TITLE
The debugger has stopped working under Docker when update vscode to 1.47.x

### ISSUE THREAD

**Issue by lunagarciaquantion** [microsoft/vscode-js-debug#696]
**Describe the bug**

Before update, I have this config:
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Moonshine2",
      "type": "node",
      "request": "attach",
      "port": 5850,
      "address": "localhost",
      "localRoot": "${workspaceRoot}/moonshine2",
      "remoteRoot": "/home/node/app",
      "cwd": "${workspaceFolder}/app/index.js",
      "protocol": "inspector",
      "restart": true
    }
  ]
}
```
The last config, runs correctly in 1.46 or less. But when vscode has updated to 1.47.x, debugger not work. The docker console show _Debugger attached_. But in the debug console in vscode show _Lost connection to debugee, reconnecting in 1000ms_.

Any idea?

**To Reproduce**
1. Upgrade vscode to 1.47.3
2. Run debug

**VS Code Version:** 1.47.3

**Additional context**
- OS: Ubuntu 20.04

**Comment by connor4312** [comment]
Please collect a trace log using the instructions in the issue template 🙂

**Comment by connor4312** [comment]
Ah, nevermind, I see you emailed it to me.

Please try using our [nightly extension](https://github.com/microsoft/vscode-js-debug#nightly-extension), I believe the issue you're running into is fixed there.

**Comment by lunagarciaquantion** [comment]
Yes, works fine :tada::tada::tada:! 
Thank u. :smiley:

I close bug.
