### ISSUE TITLE
Unbound breakpoint when Debug: Open Link command is used

### ISSUE THREAD

**Issue by jkohlin** [microsoft/vscode-js-debug#701]
**Describe the bug**
When trying the new feature _Debug: Open Link command_ in VS Code 1.48, red breakpoints turns into a white oulined breakpoint with the tooltip "Unbound breakpoint". The problem then is that the code doesn't break at the breakpoint and hence won't let me debug the code in VS code.
I'm running a local server via a npm run dev script `cross-env NODE_ENV=development webpack-dev-server --open --inline --hot`

**To Reproduce**
1. copy your localhost url
2. open _Command palette_ 
3. Type _debug: open link_ and press Enter
4. open a js file and click in the line number gutter to add a breakpoint

**Log File**

**VS Code Version:** 1.48.0

**Additional context**
Running on a Mac with MacOS 10.15.6

**Comment by connor4312** [comment]
Thanks for the issue. Do you already having a launch config for your project? If so, and if you've applied any changes or configuration to that, you may need to also set them in the link debugging mode (via the setting `debug.javascript.debugByLinkOptions`).

If not, please collect a trace log using the instructions in the issue template and I'll be happy to figure out what's wrong 🙂

**Comment by jkohlin** [comment]
> Do you already having a launch config for your project? If so, and if you've applied any changes or configuration to that

I don't think I have any launch config for my project, and wouldn't know what to put in `debug.javascript.debugByLinkOptions`. Where do I add `"trace": true`?

**Comment by jkohlin** [comment]
![image](https://user-images.githubusercontent.com/4112881/90399547-66f36000-e09b-11ea-94e6-2ab0baa79a27.png)
Is this how I do that?

**Comment by connor4312** [comment]
Adding `"debug.javascript.debugByLinkOptions": { "trace": true }` to your settings

**Comment by jkohlin** [comment]
Here's the log file: [vscode-debugadapter-4.json.gz](https://github.com/microsoft/vscode-js-debug/files/5103591/vscode-debugadapter-4.json.gz)

Strangely it works intermittently, I just can't figure out why. This log is from one of those non successful times

**Comment by connor4312** [comment]
It looks like you're debugging a Vue up. Currently, they don't generate sourcemaps that we can reliably map back to the source files. I've opened https://github.com/vuejs/vue/issues/11023 on them to try to improve this. Once that happens we will be able to make breakpoints work reliably.

**Comment by bartocc** [comment]
`vscode: Version: 1.50.1`
`js-debug-nightly: v2020.10.1317`

---

I've just hit what looks like to be the same issue, with the difference that my breakpoints bound when using `Debug: Open Link` from the command palette and **not bound** when `cmd+click`ing a URL in the terminal (normal or js debug terminal)

I've got the following `launch.json` file, and breakpoints are correctly bound when debugging with it:

```json
{
  "configurations": [
    {
      "name": "Launch Chrome",
      "type": "pwa-chrome",
      "request": "launch",
      "url": "http://localhost:4200",
      "sourceMapPathOverrides": {
        "ember-cli-babel-sourcemap-bug/*": "${workspaceFolder}/app/*"
      }
    }
  ]

}
```

and the following `settings.json` file:

```json
{
  "debug.javascript.debugByLinkOptions": {
    "trace": true,
    "enabled": "always",
    "webRoot": "${workspaceFolder}/dist",
    "sourceMapPathOverrides": {
      "ember-cli-babel-sourcemap-bug/*": "${workspaceFolder}/app/*"
    }
  }
}
```

Any idea why `cmd+click` fails ?

Here's the trace after a `cmd+click` : 
[vscode-debugadapter-6.json.gz](https://github.com/microsoft/vscode-js-debug/files/5386890/vscode-debugadapter-6.json.gz)

**Comment by connor4312** [comment]
@bartocc thanks for the log and info. [JavaScript strike again](https://github.com/microsoft/vscode-js-debug/commit/e9d330f7c04ae51c37bc3a946b16ec7643fa8d80?w=1).

Should be fixed in the next [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension).

**Comment by bartocc** [comment]
awesome 👍

**Comment by bartocc** [comment]
And I confirm it is now working with `v2020.10.1517`
