### ISSUE TITLE
Auto-attach not working 

### ISSUE THREAD

**Issue by ep1cman** [microsoft/vscode-js-debug#702]
**Describe the bug**
When running node via the integrated terminal the auto attach feature is not working.

**To Reproduce**
1. Create empty folder with single javascript file called `test.js` e.g:
```
let a = "foo"; //Breakpoint here
console.log(a);
```
2. Open folder in VS code
3. Open integrated terminal
4. run `node test.js`
5. script runs without attaching debugger

Doing the above using the "Javascript Debug Terminal" works as expected

**VS Code Version:** 1.48.0

**Additional context**
I have "Only Auto Attach Explicit" disabled and "Use Preview" enabled.

**Comment by connor4312** [comment]
At the moment, auto attach only works when running with the `--inspect` flag, e.g. `node --inspect test.js`. See here for more information: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_auto-attach-feature

We're reevaluating the ability to have global (non-explicit) auto attach as a plan item this month (https://github.com/microsoft/vscode/issues/104735)

**Comment by connor4312** [comment]
Tracking this in https://github.com/microsoft/vscode-js-debug/issues/703, subscribe there for updates 🙂
