### ISSUE TITLE
Chrome Spins Up "New Instance"

### ISSUE THREAD

**Issue by say25** [microsoft/vscode-js-debug#705]
When I seem to use `launch.json` and type `pwa-chrome`, a new instance of Chrome without any of my Chrome extensions is launched. Is there a way for it to use the "normal" Chrome?

**Comment by connor4312** [comment]
You _could_ configure `userDataDir` to point to your user data directory, wherever it's located (will vary by OS and setup). However, doing so requires that you have no other instances of the browser launched. If you do, then when VS Code launches Chrome it will 'merge' with the running browser and won't apply the command line arguments we need to enable debugging.
