### ISSUE TITLE
Window has crashed when breakpoint is set

### ISSUE THREAD

**Issue by pedroassis** [microsoft/vscode-js-debug#712]
Issue Type: <b>Bug</b>

When I set a breakpoint before debugging vscode will not start the app, and eventually crashes with the same error as the issue below.

If I start the app with no breakpoints the app will start, but later added breakpoints will not work.

Breakpoints show as unbound, even if I start without breakpoints.

Instance of vscode helper is eating 15GB of memory.

With the dev tools open vscode stopped with a warning of possible memory leak in the line below.

https://github.com/microsoft/vscode/blob/4c526744f5372ab7f7a82865a19fbc6489546ae7/src/vs/base/parts/ipc/common/ipc.ts#L274

Debugging other smaller (less code) projects still works.

https://github.com/microsoft/vscode/issues/105019

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T08:03:27.059Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.13.2
flutter|Dar|3.13.2
gitblame|wad|4.2.0

</details>

**Comment by connor4312** [comment]
Thanks for the info! js-debug has a behavior where we scan the workspace for source maps before launching the program. Normally this is very fast, but if you have a super large workspace it could take a while.

If you don't need sourcemaps for your project (or to verify whether this is the case) you can set `"outFiles": []` in your launch.json. This will prevent any sourcemap scanning. Alternately, you can set outFiles to the [glob pattern](https://globster.xyz/) for the specific files you want to scan.

**Comment by pedroassis** [comment]
@connor4312 thanks for the help, that worked.

I don't have any source maps for this project, but vscode was scanning the ui sourcemaps

**Comment by connor4312** [comment]
We'll now show a warning after some amount of time scanning the outFiles

**Comment by pedroassis** [comment]
@connor4312 thx for the work!
