### ISSUE TITLE
Debugger of multiple extensions does not work after VSCode 1.46.0

### ISSUE THREAD

**Issue by veredcon** [microsoft/vscode-js-debug#714]
**Describe the bug**
Version: 1.48.0 (user setup)
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T07:50:42.600Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

I had the following launch.json which has always been working for me:
 {
      "name": "Name of Launch",
      "type": "extensionHost",
      "request": "launch",
      "runtimeExecutable": "${execPath}",
      "args": [
        "--extensionDevelopmentPath=/Users/path/repos/vscode-wing-cf-tools/wing-vsix",
        "--extensionDevelopmentPath=/Users/path/repos/vscode-wing-run-config/wing-vsix",
        "--extensionDevelopmentPath=/Users/path/repos/vscode-wing-cap-run"
      ],
      "outFiles": [
        "/Users/path/repos/vscode-wing-cf-tools/wing-vsix/out/**/*.js",
        "/Users/path/repos/vscode-wing-run-config/wing-vsix/out/**/*.js",
        "/Users/path/repos/vscode-wing-cap-run/bundle/**/*.js"
      ],
      "preLaunchTask": "npm: webpack"
    }

I need to debug multiple extensions that depend on one another.
After VSCode was updated to be 1.47 it stopped working. When I downgraded it to 1.45 it got back working. 
Me and my colleagues were downgrading to VScode 1.45 as a temporary workaround to allow us continue debugging with that configuration.
However now I'm not able to really go back to this version anymore and my work is blocked since I cannot debug.
(The oldest extension I can use for the JavaScript Debugger is 1.46.0 which is not working for me and I couldn't find older versions.)

The above configuration resides in launch.json of the "vscode-wing-cap-run" extension. Only breakpoints in this extension are set properly and stops.
However, on the other extensions **I get "Unbound breakpoint"** when I set breakpoints.
(vscode-wing-cf-tools and vscode-wing-run-config)

The other extensions are for sure activated as I see the views they contribute in VSCode.

**To Reproduce**
I don't get any error just cannot set breakpoints anymore.

**Log File**
I added "trace": true but could not see it printed location to log file in the debug console.

**VS Code Version:** 1.46.0 and up

**Additional context**

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/105075
