### ISSUE TITLE
ms-vscode.js-debug\src\hash.bundle.js launched repeatedly?

### ISSUE THREAD

**Issue by cyraid** [microsoft/vscode-js-debug#721]
**Describe the bug**
When debugging in Chrome, I see the Windows 10 hour glass pop up many times, and you can't unsee it when you do. Am I the only one that it happens to?

**To Reproduce**
1. Run an app (angular serve?) on Chrome debug.
2. Open Task Manager.
3. Sort by disk usage.
4. See the wonderful hourglass on your mouse as you see vscode with "ms-vscode.js-debug\src\hash.bundle.js" gets moved to the top every time the hourglass comes.

**Log File**

No log.

**VS Code Version:** 1.48.1

**Additional context**

**Comment by connor4312** [comment]
Content hashing is needed to validate whether files are disk are the same as those in the runtime. However, for sourcemapped files we only check for existence and don't hash anything, so without a log I'm not sure why you'd be hitting this so heavily in an Angular app.

Not sure if there's anything actionable here.

**Comment by cyraid** [comment]
I'm fine with it using some disk, but what is it launching? Does it need to launch a process every time it does something? Can you not have something just run in the background?

**Comment by connor4312** [comment]
It should reuse the same process, and shut it down only if there were no new files to hash for 30 seconds.

**Comment by cyraid** [comment]
Could there be an option to keep it running?

**Comment by connor4312** [comment]
It starts again after 30 seconds if no one uses it. I'm not convinced that's an issue, though. Launching processes on Windows is not the fastest thing in the world, but is not a noticable amount of load. Definitely not enough to justify having an option for it...

**Comment by cyraid** [comment]
It's fast to start, but you see the hour glass on the mouse pop up which was the whole issue. No other ide while debugging you'll see the hour glass on the mouse distract you over, and over, and over, and over, and over..

**Comment by cyraid** [comment]
Also, if it's just gonna start again in 30 seconds, why bother closing it down?

**Comment by connor4312** [comment]
> Also, if it's just gonna start again in 30 seconds, why bother closing it down?

We don't know whether it's going to be used again in 30 seconds. For most programs, they'll hash their scripts during startup and never hash anything again, at least until the program is restarted.

**Comment by cyraid** [comment]
What about for apps that watch files? ng serve for example?

**Comment by connor4312** [comment]
In that case, it will be launched once when the page refreshes given that it's been > 30 seconds since the page was last loaded.

**Comment by cyraid** [comment]
Would you be able to create a project with ng (just a starter won't take too long at all), and use npm start / ng serve and then verify behavior with running debug in chrome and having the mouse visible? Isn't it incredibly distracting?

**Comment by connor4312** [comment]
I don't observe that in a basic ng app. Because everything is served from sourcemaps, it hashes nothing (as expected) and as of 000465166a592cae19b191346ddbb7443565a86f we will never start a hash process at all. As mentioned above, without a log file file I do not know what hashes your app is doing, and the hashes it does do will only happen when the page is reloaded unless you're continuously loading scripts from somewhere.
