### ISSUE TITLE
Browser crashes during debugging

### ISSUE THREAD

**Issue by dfdumaresq** [microsoft/vscode-js-debug#727]
Issue Type: <b>Bug</b>

After I launch my C#/Typescript stack and log into the browser , it crashes.
If I open Developer Tools, I see:
Activating extension 'ms-vscode.js-debug-nightly' failed: command 'extension.pwa-node-debug.npmScript' already exists.

Extension version: 2020.8.2017
VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:09:08.021Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

This is from the Developer Console log

[1598637004359.log](https://github.com/microsoft/vscode-js-debug/files/5143502/1598637004359.log)

**Comment by connor4312** [comment]
Make sure you follow steps 1 and 2 here which will fix the "activating extension" error https://github.com/microsoft/vscode-js-debug#nightly-extension.

If you continue to have issues, please let me know and collect a trace log using the instructions from the issue template.

**Comment by dfdumaresq** [comment]
Thanks for the quick reply, @connor4312 . I have followed the steps above but am having the same issue with the browser crashing. I'm attaching the omnisharp.log. 

I am not sure what you mean by "collect a trace log using the instructions from the issue template.' Since I don't see any instructions related to a trace log. So I followed [this](https://code.visualstudio.com/docs/cpp/enable-logging-cpp) 

Hope this is what you want. 
[omnisharp.log](https://github.com/microsoft/vscode-js-debug/files/5144208/omnisharp.log)
[csharp.log](https://github.com/microsoft/vscode-js-debug/files/5144226/csharp.log)

By the way, the issue occurs in Chrome but not in Firefox.

**Comment by connor4312** [comment]
These are the instructions:

>If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by dfdumaresq** [comment]
I've added 
      "logging": {
        "trace": true,
        "browserStdOut": true,
        "engineLogging": false,
        "exceptions": true,
        "programOutput": true,
        "moduleLoad": false
      },
No log file mentioned in the C# Debug Console.

Will try restarting VScode

**Comment by connor4312** [comment]
The `trace` property should be added to the top level of your chrome or edge launch config, and the location will be written to the debug console for that configuration.

**Comment by dfdumaresq** [comment]
Thanks for clarifying. I've sent the file to your email address above.

**Comment by dfdumaresq** [comment]
I've also sent "vsdb-ui crash report" to your email.

**Comment by dfdumaresq** [comment]
And lastly, I've sent razor.log to your email.

**Comment by connor4312** [comment]
Thanks for the logs. I see that we get this on stderr from Chrome:

```
[0828/150753.498168:WARNING:crash_report_exception_handler.cc(240)] UniversalExceptionRaise: (os/kern) failure (5)
```

This is not something under our control as a debugger -- I'd recommend filing an issue with the Chromium project, instructions: https://www.chromium.org/for-testers/bug-reporting-guidelines/reporting-crash-bug

**Comment by dfdumaresq** [comment]
Thanks, Connor!

**Comment by dfdumaresq** [comment]
Connor, unrelated, but maybe you can point me in the right direction.
I have a persistent issue with Typescript performance in VSCode. It renders VSCode unusable for long periods of time. 
There are over 10 High CPU issues open for this and the oldest is Feb, 2019. 
Any suggestions on how to get some action on this?
https://github.com/cybertim/vscode-gengetset/issues

**Comment by connor4312** [comment]
It looks like some of the features that extension provides (auto imports and organize imports) are built in to VS Code. Getters/setters could also be done via snippets fairly easily. For 'Easily create a contructor based on privates' -- personally I prefer the `constructor(private foo: Bar)` syntax which avoids that at all.

But ultimately that's a 3rd party extension and it's up to the author to action on those issues.

**Comment by dfdumaresq** [comment]
Okay - thanks. I'll see if I can do without it. All the best and stay safe!

**Comment by connor4312** [comment]
Thanks, likewise 🙂 

One more thing -- you have a crash ID from `chrome://crashes` that I can share with the Chrome team?

**Comment by dfdumaresq** [comment]
Sure, hope this helps:

Local Crash Context: | 35d4473b-a66b-40a7-bcaa-c2d51af97196

**Comment by connor4312** [comment]
Thanks! I got a report from another user, seems like it's an issue that they're aware of and have/will be  fixed in Chrome 86  https://bugs.chromium.org/p/chromium/issues/detail?id=1123329#c10

You may be able to use Chrome Canary if the fix is published there (instructions https://github.com/microsoft/vscode-js-debug/issues/729#issuecomment-683367574)

**Comment by dfdumaresq** [comment]
Thanks for the tip but here's a happy thing: I've since found that I like the way the Firefox extension handles debugging in VSCode much better than Chrome. 
(Ever since Chrome took over my desktop, it seems like I've been looking for a reason to switch back to FF, Found one! ;)

**Comment by connor4312** [comment]
Glad you found something that works!

I'm curious what things you like (other that most FOSS-iness) that the Firefox extension has that this / the Chrome debugger is missing or does differently.

(also -- over the last few months there has been an effort at Firefox to support the Chrome Debug Protocol, so it's possible that js-debug could eventually support FF directly as well...)

**Comment by dfdumaresq** [comment]
Sorry for the late reply, Connor. 
One big plus was that the FF extension offered pathMappings to my source when I added the configuration to launch.json. 
Also it stays loaded between debugging sessions, saving time by not having to restart the browser every time.
