### ISSUE TITLE
debug.javascript.autoAttachSmartPattern requires autoAttach settings restart

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-js-debug#731]
Refs: https://github.com/microsoft/vscode/issues/105771

Hover over debug.javascript.autoAttachSmartPattern settings. Notice:

>You may need to toggle Auto Attach to "disabled" and then "on" again for changes in this setting to take effect

There are two things which I dislike here
1) Restart of another settings is required - can't we do this automatically
2) Uncertanty. If the user has to change the setting tell him that definetly, not with a "may"

**Comment by joaomoreno** [comment]
The use of _may_ here is so distressing. Please let's just implement this setting in a way that we don't need this disclaimer at all:


>You may need to toggle Auto Attach to "disabled" and then "on" again for changes in this setting to take effect

**Comment by connor4312** [comment]
Yes, I will take care of this today

**Comment by connor4312** [comment]
We'll now refresh the variables when changed. We also check them when switching to an old workspace. If you had different variables in the old workspace (which are persisted in the environment vars) you will see the ⚠️ sign come up in the terminal after a few seconds, requiring you to relaunch the terminal for those to apply.
