### ISSUE TITLE
debug.javascript.autoAttachSmartPattern not sure if exclude or include pattern expected

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-js-debug#734]
Refs: https://github.com/microsoft/vscode/issues/105771

Look at the example: node_modules is provided with an exclude `!` pattern and `KNOWN_TOOLS` are provided with no exclude pattern. How should I input my new filter I am not sure from the setting description.

Also I feel like this should not be exposed to the users. We should have a good default and only add this if our smartness does not work. Which old node debug somehow succeeded in doing.

![Screenshot 2020-09-01 at 11 52 32](https://user-images.githubusercontent.com/1926584/91835488-be6fff00-ec49-11ea-9a77-6c3f9b5c14eb.png)

**Comment by connor4312** [comment]
> Also I feel like this should not be exposed to the users. We should have a good default and only add this if our smartness does not work. Which old node debug somehow succeeded in doing.

The old node debug only attached when explicitly given `--inspect` flags. The "smart" mode is new to js-debug.

I would like to have some good defaults, but I don't think those exist. It's also somewhat common in complex projects to have their own test runners or scripts that wrap test runners, like we do in VS Code. Depending on the project structure these might appear in node_modules (like `vscode-test`) which we exclude from attachment by default. For this reason I didn't want to have an unconfigurable set of attachment patterns.

> Look at the example: node_modules is provided with an exclude ! pattern and KNOWN_TOOLS are provided with no exclude pattern. How should I input my new filter I am not sure from the setting description.

I'm having trouble simplifying it while keeping it concise. Is

>If one of these glob patterns matches the Node.jsentrypoint script in smart `#debug.javascript.autoAttachFilter#` mode, we will debug that process.

better? Or any suggestions?

**Comment by isidorn** [comment]
1. Do we store the values of settings in our telemetry? If yes you could. check what users set this setting to and from those figure out what defaults make sense?
2. When you fix the other issue and remove the "Note" part there will be more space to add more clarifying text

How about
"Configure glob patterns for excluding scripts from JavaScript Auto Attach mode. These patters are only applied when debug.javascript.autoAttachFilter is set to `smart`. Read more about glob patterns [here](link to docs where glob patters are quickly explained and you mention KNOWN_TOOLS - similar to https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options)."


As for the wording maybe @weinand can help as well

**Comment by connor4312** [comment]
I reworded it slightly more and linked to a docs section https://github.com/microsoft/vscode-docs/blob/vnext/docs/nodejs/nodejs-debugging.md#auto-attach-smart-patterns
