### ISSUE TITLE
Breakpoints and stepping on dynamic embedded script files has several issues

### ISSUE THREAD

**Issue by digeff** [microsoft/vscode-js-debug#736]
1. Create a ASP.NET project with a <script> inside an .cshtml file
2. Try to stop on the script by using a debugger; statement, the debugger shows the wrong place
3. Try to set breakpoints on the dynamic script file: They don't work because we set the breakpoints relative to the script, and chrome expect breakpoints relative to the html file (when we setbreakpointbyurl)

Attaching the project where this happens on VS Code and a log too (inside the zip).
[CSHTML WebApp.zip](https://github.com/microsoft/vscode-js-debug/files/5172033/CSHTML.WebApp.zip)

**Comment by connor4312** [comment]
js-debug has no way to match the positions in the source file up with those in the cshtml, so breakpoints will never work. The right solution for this would be for the asp.net server to create a small inline sourcemap that fixes the positions and references the correct locations inside the cshtml file. Outside of adding this or some other kind of annotation, I do not see a way for us to be able to reliably match up those content scripts.

However I made a fix to correct the source padding so at last the location is correct (in step 2).

![](https://memes.peet.io/img/20-09-85580ff0-c009-4b86-84f5-d160b6c77d6e.png)
