### ISSUE TITLE
Debugger for Chrome (4.12.10) with Angular7 Application (that uses SOAP) make Chrome crashes

### ISSUE THREAD

**Issue by dpasquali** [microsoft/vscode-js-debug#739]
**Describe the bug**
After launching 'ng serve' from the Terminal, I debug my Angular 7 App using Debugger for Chrome (as I usually do) ("type": "chrome", "request": "launch", "name": "Launch Chrome against localhost "," url ":" http: // localhost: 4200 "," webRoot ":" $ {workspaceFolder} "). 
Application debugging starts correctly, the browser loads the Login page and logs in (using Soap methods), but soon after, when the application loads its operating environment and executes several Soap calls using a javascript library, after a second Chrome crashes by closing and debugging it stops.
It started giving errors two days ago, and I don't think it depends on the latest changes made to my code, because it behaves in the same way when launching in debug the same project compiled in Angular 6 with code older than months.
Running the application without debugging, or using the Firefox debugger, the error does not occur.

**To Reproduce**

**Log File**

[vscode-debugadapter-2.zip](https://github.com/microsoft/vscode-js-debug/files/5188897/vscode-debugadapter-2.zip)

**VS Code Version:**  1.48.2

**Additional context**

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-js-debug/issues/729. The Chrome team has indicated this will be fixed in the next version, and it should work on Chrome Canary (instructions: https://github.com/microsoft/vscode-js-debug/issues/729#issuecomment-683367574). Ref: https://bugs.chromium.org/p/chromium/issues/detail?id=1123329
