### ISSUE TITLE
Debugger attaches multi-times, and will run into the same port in --inspector-brk and can't attach anymore

### ISSUE THREAD

**Issue by lazybonee** [microsoft/vscode-js-debug#740]
**Describe the bug**
When I debug with --inspector, it will attach many times with different port but seems to perform normally.
***Debug with --inspector***
![221599658980_ pic_hd](https://user-images.githubusercontent.com/11715201/92606594-b1a47880-f2e5-11ea-815c-baf87972fd69.jpg)
When I debug with --inspector-brk, it will listen to the same port and can't attach anymore, the debugger will stop.
***Debug with --inspector-brk***
![241599659456_ pic_hd](https://user-images.githubusercontent.com/11715201/92607326-8ff7c100-f2e6-11ea-9f46-47374fa876e0.jpg)

What I have tried: I tried to remove -brk and add stopOnEntry in launch.json, but it didn't stop at entry. And the debugger will always attach many times.

1. Open TS node application
2. Add launch configuration
3. Run Launch via NPM

**Log File**

**VS Code Version:** 1.48.2
**Additional context**
Does this issue occur when all extensions are disabled?: Yes
Background:  I  installed code runner plugin and  I'm not sure if it caused the abnormal behavior, so I uninstalled VSCode completely and reinstall it as follows.
rm -fr ~/Library/Preferences/com.microsoft.VSCode.helper.plist 
rm -fr ~/Library/Preferences/com.microsoft.VSCode.plist 
rm -fr ~/Library/Caches/com.microsoft.VSCode
rm -fr ~/Library/Caches/com.microsoft.VSCode.ShipIt/
rm -fr ~/Library/Application\ Support/Code/
rm -fr ~/Library/Saved\ Application\ State/com.microsoft.VSCode.savedState/
rm -fr ~/.vscode/
rm -fr /Applications/Visual\ Studio\ Code.app

**Comment by connor4312** [comment]
This is working as intended; js-debug will debug all processes in the tree.

To use stopOnEntry, you need to invoke the `program` directly in your launch.json. You can do that with something like

```json
{
  "type": "node",
  "request": "launch",
  "name": "Launch my Program",
  "env": {
    "NODE_ENV": "development",
    "IS_ONLINE": "1",
    "TS_NODE_PROJECT": "src/tsconfig.json"
  },
  "runtimeArgs": ["-r", "ts-node/register"],
  "program": "${workspaceFolder}/src/index.ts",
  "stopOnEntry": true
}
```

**Comment by lazybonee** [comment]
Thank you for the configuration code, it works smoothly! 
However I am curious  about two questions.

1. What do you mean by all processes in the tree? I have no idea how I started so many processes.

2. I have read this explanation.

> This debugger connects differently that the old debugger, which unfortunately is not compatible with --inspect-brk being called in a nested script: we connect to processes by asking Node to --require a "bootloader" file before user code, and adding --inspect-brk will break in the bootloader before it's able to call back to vscode saying it's there to debug! If --inspect-brk is given directly in the runtimeArgs, we can rewrite it correctly, but since it's being invoked through npm in this case we can't do that.

> 
I wonder how my partner's debugger process will works just fine under "--inspector-brk" flag without require a "bootloader".
Backgroud: vscode-version: 1.48.2.  (after update) 

![image](https://user-images.githubusercontent.com/11715201/92683814-7c8c3a80-f366-11ea-9f80-a5ccef08385d.png)

**Comment by connor4312** [comment]
1. We debug all Node.js processes launched by a program. You're running an npm script, so the processes we debug are:
    - npm itself 
    - `cross-env`, which is also a node script
    - and finally your program

       This behavior is extremely useful when dealing with programs that launch subprocesses, or launch a cluster of workers.

1. The explanation is slightly outdated. It is still generally incompatible, but we have a shim to detect running npm scripts with `--inspect-brk` which falls back to an older direct-attach mode with less features. A warning is printed to the debug console in this case.

also, in the upcoming release (tomorrow) we put in a change to hide some of the ugly debug spam that you have in your screenshot.
