### ISSUE TITLE
extension is disabled in WSL

### ISSUE THREAD

**Issue by luhc228** [microsoft/vscode-js-debug#741]
After installing the extension, it can't be used. The extension is also disabled but the detail page is enabled.

![image](https://user-images.githubusercontent.com/44047106/91400219-de7e7780-e871-11ea-818f-4b62a414acfc.png)

**Comment by connor4312** [comment]
Chrome is a UI extension and will always be disabled in WSL. You no longer need it, though you may need to set your launch `type` to `pwa-chrome` instead of `chrome` if it isn't installed.
