### ISSUE TITLE
Breakpoints are no longer hit when using the latest chrome debugger in vscode

### ISSUE THREAD

**Issue by thegecko** [microsoft/vscode-js-debug#743]
**Describe the bug**

Breakpoints are no longer hit when using the latest chrome debugger in vscode.
This could be due to using symlinked folders in projects (where this bug has been encountered)

**To Reproduce**
1. Use a project which relies on symlinks in the source (e.g. a monorepo with hoisted libraries)
2. Set a breakpoint in the source
3. Use the latest chrome debugger with a `launch` config
4. Launch and debug the project

**Log File** Attached:

[vscode-chrome-debug.working.txt](https://github.com/microsoft/vscode-js-debug/files/5197202/vscode-chrome-debug.working.txt)
[vscode-debugadapter-2.failing.json.gz](https://github.com/microsoft/vscode-js-debug/files/5197203/vscode-debugadapter-2.failing.json.gz)

**VS Code Version:** 1.48.0

**Additional context**
Chrome debugger: Version: 4.12.10
macOS: 10.14.5
Works correctly when setting `debug.javascript.usePreview` to false (no longer the default)

**Comment by connor4312** [comment]
Please include the log file. Thanks!

**Comment by connor4312** [comment]
@thegecko it looks like your webpack config uses a mix of absolute and local paths, such as `webpack:////Users/thegecko/Projects/tmp/theia/packages/web-ide-extension/src/frontend/contribution.ts` for your breakpoint, but there's also urls like `webpack:////src/common/parser/Params.ts`.

I think you can fix this by adding something like this to your launch config:

```js
"sourceMapPathOverrides": {
	"webpack:////src/*": "${workspaceFolder}/*", // more specific, will take priority
	"webpack:////*": "/*", // anything not inside src, resolve absolutely
},
```

**Comment by thegecko** [comment]
Thanks for the info @connor4312 

I can confirm this addition fixes the issue so is a usable workaround. I assume this is still a regression, however?

**Comment by connor4312** [comment]
It's a change because of a new default patter (`'webpack://?:*/*': `${webRoot}/*`,`) that was introduced to fix another common webpack pattern case. In the old debugger, the default override created an overridden path like:

```
//Users/thegecko/Projects/tmp/theia/packages/web-ide-extension/src/frontend/contribution.ts
```

With joined with the webroot, the double slashes would cause the absolute URL to work. But now the override maps to

```
/Users/thegecko/Projects/tmp/theia/packages/web-ide-extension/src/frontend/contribution.ts
```

without the double slashes, so joining the path doesn't reset it in the same way.

**Comment by thegecko** [comment]
As this is a regression / change in behaviour, perhaps it should be documented?

**Comment by connor4312** [comment]
I've added a default to handle absolute paths like this, in the linked commit
