### ISSUE TITLE
Support customizing the color of the flamegraph

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#756]
We got some feedback that users wanted to better match the flamegraph coloring to their theme. I tried some scheme to automatically pick an existing color from the theme, but didn't have good results. I think in part because we don't have a singular "flame"-like color, for example I tried using the border color of input validation errors, but on some themes this didn't work very well.

Kai suggested adding a new color for this that themes should customize. I'm not sure what it should be named, maybe just a "vibrant" color?

**Comment by misolori** [comment]
Since we are introducing webviews in custom views, I'd imagine we'll be getting a lot more data visualization extensions so having a set of chart accent colors would work in both scenarios. Thinking of something like `chart.accentOne` or `chart.accentBlue` like the terminal colors?

**Comment by connor4312** [comment]
Yea, that'd be good -- I can use that for the sidebar visualizer, where I'll have multiple lots, as well https://github.com/microsoft/vscode-js-debug/issues/755

**Comment by RandomFractals** [comment]
not sure what you are proposing here: that those settings become standard vscode styles. 

Probably would not cover vast number of data viz extensions.

**Comment by RandomFractals** [comment]
you probably want to look at this repo for a comprehensive list of styles you'll need to make charts themeable: https://github.com/vega/vega-themes

**Comment by misolori** [comment]
@RandomFractals thanks for the heads up about how themes work in Vega. Our goal here is to start to create a baseline of chart colors that extensions can reference in webviews. We can't possibly create a token for every color that exists but the thought is we can start with primary colors and then if needed we can shift the hue of these colors if we need additional colors. Thanks to your feedback, we're also considering foreground and grid lines as well.

**Comment by connor4312** [comment]
Adopted the colors in https://github.com/microsoft/vscode-js-profile-visualizer/commit/5d8e5eb20e5543eae8f773f3f27365ed6d0bdb78
