### ISSUE TITLE
Crash when logging into AWS

### ISSUE THREAD

**Issue by toschlog** [microsoft/vscode-js-debug#757]
My app crashes when trying to authenticate using AWS Cognito.  It only happens with the new debugger; if "Use the new in-preview JavaScript debugger for Node.js and Chrome" is set to false it does not crash.

I have made a sample React app that is as simple as I can get it.  To set up:
1. User create-react-app to create a new app
2 Drop in the attached App.js and package.json
3. Run "npm install" to get the AWS code
4. Put valid values in the cognitoConfig object and the call to Auth.signIn()

[aws-test.zip](https://github.com/microsoft/vscode-js-debug/files/5220740/aws-test.zip)
[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode-js-debug/files/5220742/vscode-debugadapter-0.json.gz)

**To Reproduce**
1. "Start Debugging" from Visual Studio Code
2. Click on "login" in the browser window.  The window will go away and there will be no indication of what went wrong.

Because this uses authentication code, I've had to remove a bunch of information from my test app.  Hopefully you will have access to Cognito so you can reproduce.

I've attached the verbose log.

**VS Code Version:**
Version: 1.49.0 (system setup)
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:22:08.892Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by connor4312** [comment]
Thanks for the good report.

This duplicates https://github.com/microsoft/vscode-js-debug/issues/729. The Chrome team has indicated this will be fixed in the next version, and it should work on Chrome Canary (instructions: https://github.com/microsoft/vscode-js-debug/issues/729#issuecomment-683367574). Ref: https://bugs.chromium.org/p/chromium/issues/detail?id=1123329

**Comment by toschlog** [comment]
Hmm...so maybe I didn't need to spend two hours making a simple test program :(  Anyway, I'm glad to help.  Thanks!

**Comment by connor4312** [comment]
Yea -- though I really do appreciate the effort! It would make my life much easier if everyone spent time creating test programs for their issues❤️
