### ISSUE TITLE
Auto attach onlyWithFlag does not attach onto --inspect-brk flag

### ISSUE THREAD

**Issue by artu-ole** [microsoft/vscode-js-debug#761]
**Describe the bug**
New debugger with `"debug.javascript.autoAttachFilter": "onlyWithFlag"` does not seem to attach onto nodejs processes started from terminal with `--inspect-brk` flag. Contrary to how old debugger attached. 

**To Reproduce**
1. Set `"debug.node.autoAttach": "on"`
2. Set `"debug.javascript.autoAttachFilter": "onlyWithFlag"`
3. Try `node --inspect-brk .\test.js` in terminal (powershell in my case)

**VS Code Version:** 1.49.0

**Comment by connor4312** [comment]
This is an effect of how the new auto attach system works. Starting with --inspect-brk pauses in our bootloader, before it has a chance to tell VS Code that we have a process to attach to. You can safely use `--inspect`, omitted the brk, since auto attach will now always attach before the program starts.

**Comment by artu-ole** [comment]
@connor4312 this among the [other](https://github.com/microsoft/vscode-js-debug/issues/754) [plethora](https://github.com/microsoft/vscode-js-debug/issues/752) of [undocumented regressions](https://github.com/microsoft/vscode/issues/106803) and [changes](https://github.com/microsoft/vscode/issues/106849) in behavior is frankly a big ball of mud thrown into developers' faces with the new debugger. 
I should not be forced to change dozens of package.json scripts because you decided to throw last bit of backwards compatibility out of the window. 
New debugger is still as rough and raw as the day it was released and quickly pulled from mainstream branch and it's been way too early to take `debug.javascript.usePreview` setting out. My 2¢.

**Comment by connor4312** [comment]
Thank you for your feedback
