### ISSUE TITLE
Auto attach click wording

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-js-debug#762]
When clicking on `Auto Attach: Off` in the status bar.

<img width="455" alt="Screen Shot 2020-09-17 at 5 59 11 AM" src="https://user-images.githubusercontent.com/2193314/93473530-f8c4d780-f8aa-11ea-829b-3ff67c633b17.png">

Thoughts:

- Main thing: Grammar could be improved on "so can not"
- Why is "node" quoted?
- Should we be using "your" here?

**Comment by connor4312** [comment]
Thanks 👍 

> Why is "node" quoted? 

It's the binary name, but backticks would be better

> Should we be using "your" here?

I think so, but I renamed it to `PATH` to be more explicit that it's the system path, not just some random path
