### ISSUE TITLE
Support selecting on multi-root workspace

### ISSUE THREAD

**Issue by roddolf** [microsoft/vscode-js-debug#765]
**Is your feature request related to a problem? Please describe.**
When using `Debug: Create JavaScript Debug Terminal` and having a multi-root workspace is frustrating that the created terminal is always on the first root directory.

**Describe the feature you'd like**
It would be better to be able to select in which directory create the debug terminal like the normal integrated terminal does.

**Comment by connor4312** [comment]
Thanks for the suggestion, this will be in the next [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension)
