### ISSUE TITLE
"Auto-attach: Smart" attaches to all npm commands

### ISSUE THREAD

**Issue by andrewbranch** [microsoft/vscode-js-debug#768]
**Describe the bug**
The new auto-attach functionality auto-attaches to everything I do with `npm` (e.g. `npm install`). I use [tj/n](https://github.com/tj/n) to manage my node installations, and I thought that meant that my `npm` lived in a folder that was not `node_modules`, but it looks like I was wrong about that:

```zsh
% ls -la `which npm`
lrwxr-xr-x  1 andrew  admin  38 May 18 17:51 /usr/local/bin/npm -> ../lib/node_modules/npm/bin/npm-cli.js
```

**To Reproduce**
1. I’m guessing you might need a node installation similar to mine? `brew install n; n stable`
2. Set auto-attach to "Smart"
3. Run "Reload Window" after changing auto-attach setting (this is probably a separate bug)
4. Run `npm i` in the built-in console

**VS Code Version:** 1.50.0-insider (f943318042a3b9229049aea86cea04d0ff9c8210)

**Comment by connor4312** [comment]
Thanks for the report
