### ISSUE TITLE
Chrome browser is closed with all tabs after Stop Debug button clicked

### ISSUE THREAD

**Issue by Lazarencjusz** [microsoft/vscode-js-debug#771]
I am running chrome in debug mode, everything works, new tab is created, breakpoints works. 

But when I hit stop debug button in VS Code, all browser is closed. I can't find any option for that to close only created tab.

**Comment by connor4312** [comment]
There's an option for this (`cleanUp`). However this currently causes some issue, see https://github.com/microsoft/vscode-js-debug/issues/555

**Comment by Lazarencjusz** [comment]
@connor4312 that's what I need, thanks
