### ISSUE TITLE
Auto-attaches to vscode

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#783]
- Auto attach: Smart
- In a terminal, run `code-insiders`
- It briefly starts a debug session, probably attaching to the CLI process, then stops when that process quits because vscode is already running

Maybe that can be excluded by default too

**Comment by connor4312** [comment]
Can you confirm you're running a recent version of js-debug and a new bootloader? (Per workspace, the first time attachment runs it will update the bootloader file -- uses the old one for the first attachment).

I added this logic earlier to prevent this: https://github.com/microsoft/vscode-js-debug/blob/9c12e58d838616ffe2ac06d412349a7e3c63c6bb/src/targets/node/bootloader.ts#L207-L211

**Comment by roblourens** [comment]
Yes, latest nightly and it happens multiple times in one workspace `code-insiders` is `/usr/local/bin/code-insiders`

**Comment by roblourens** [comment]
`/usr/local/bin/code-insiders -> /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/bin/code`

**Comment by connor4312** [comment]
Can you ping me to screenshare sometime today? I have the exact same setup, but for me smart attach is fine 🤔
