### ISSUE TITLE
Prints "read byte 1"

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#789]
- vscode repo
- Start `./scripts/code.sh` in a terminal with auto attach: smart
- See unexpected output

![image](https://user-images.githubusercontent.com/323878/95264477-3cdd3500-07e4-11eb-8b7d-73167b4bba54.png)

I see this logged from the js-debug bootstrap bundle

**Comment by connor4312** [comment]
This indicates the attach command is failing -- what/is anything logged in the Developer Tools in the vscode window?

**Comment by roblourens** [comment]
I was seeing this for awhile earlier but I don't see it at the moment and don't have any errors saved or anything. If there's nothing to be done then you can close it.

**Comment by connor4312** [comment]
Okay. If you see that again, please grab the devtools log. It's coming from [here](https://github.com/microsoft/vscode/blob/master/extensions/debug-auto-launch/src/extension.ts#L246-L247)
