### ISSUE TITLE
OS level NODE_OPTIONS env variable is not respected

### ISSUE THREAD

**Issue by shahar-h** [microsoft/vscode-js-debug#790]
**Describe the bug**
When defining NODE_OPTIONS env variable at OS level it is being overriden when starting debug session.

**To Reproduce**
1. Clone this repo
2. Add to `Extension` launch config:
```
"env": {
    "NODE_OPTIONS": "--use-openssl-ca"
}
```
3. Run extension launch config
4. In the extension development host  create index.js file that contains `console.log(process.env.NODE_OPTIONS)`
5. Create the following launch config:
```
 {
       "name": "Launch Program",
       "program": "${workspaceFolder}/index.js",
       "request": "launch",
       "skipFiles": [
          "<node_internals>/**"
       ],
       "type": "node"
 }
```
6. Run it with Debug › JavaScript: Use Preview enabled - `--require "c:/Users/i318734/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js" ` is displayed.
7. Run it with Debug › JavaScript: Use Preview disabled - `--use-openssl-ca` is displayed.

I would expect that NODE_OPTIONS OS value will be concatenated to the new value instead of being replaced.
My use case is to load certificates from the OS certificate store by default for any node process instead of using the bundled NodeJS certificate store. 

**Log File**

**VS Code Version:** 1.47.3

**Additional context**

**Comment by connor4312** [comment]
Thanks for the issue, this will be in the next [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension)

**Comment by shahar-h** [comment]
Will it be included in the next patch (v1.50.3)?

**Comment by connor4312** [comment]
No, it'll be in 1.51.0

**Comment by shahar-h** [comment]
Thanks, do you know when v1.51.0 will be released?

**Comment by connor4312** [comment]
Early next month
