### ISSUE TITLE
Debugger auto attaches when running 'yo' in terminal

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-js-debug#794]
Issue Type: <b>Bug</b>

**Repro**
1. With "debug.javascript.autoAttachFilter": "smart"
1. In VS Code terminal, run `yo code`

**Bug**
The debugger starts:

<img width="1198" alt="Screen Shot 2020-10-08 at 12 03 02 AM" src="https://user-images.githubusercontent.com/12821956/95421056-dc401c00-08f9-11eb-9dab-ac23689d200d.png">

Extension version: 2020.10.717
VS Code version: Code - Insiders 1.50.0-insider (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T00:58:35.624Z)
OS version: Darwin x64 19.6.0

**Comment by connor4312** [comment]
I don't have this behavior, can you confirm where the `yo` script lives, and also make sure it happens if you attach twice in the same workspace? (The bootloader is uploaded lazily, so you can have an old version in your workspaceStorage until the next time you attach)

**Comment by mjbvz** [comment]
It's from nvm: `/Users/matb/.nvm/versions/node/v12.14.0/bin/yo`

Not sure what the second part means. Just attach to any process twice? Or run yo and have it auto attach twice?
