### ISSUE TITLE
What should I do to debug Chrome in same window?

### ISSUE THREAD

**Issue by leonkong** [microsoft/vscode-js-debug#795]
When I use new js-debug to replace vscode-chrome-debug extension, I Found a little different between new js-debug and vscode-chrome-debug extension.When I use vscode-chrome-debug extension, I can debug A project in a chrome window, then I debug B project, it will open a new tab in same chrome window. When I use new js-debug, it will open a new window, not a new tab in same window. With new js-debug(setting.json "debug.javascript.usePreview": true), what should I do to open new tab in same chrome window, not open a new window?

**Comment by leonkong** [comment]
launch.json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome localhost",
            "url": "http://localhost:8000",
            "webRoot": "${workspaceFolder}",
        }
    ]
}

**Comment by connor4312** [comment]
To do this you can set a `userDataDir` in your launch.json. By default we keep a data dir per-workspace, so that any changes or plugins to Chrome can be made to one project without unintentionally bringing them into other projects where those changes might not be needed or desired.
