### ISSUE TITLE
How do interested users keep up to date with changes?

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode-js-debug#797]
This is certainly one of my favourite extensions in the VSCode ecosystem. I see it mentioned in the main release notes also. But I think unless I actively check this repo I may miss some new feature additions and changes.

For instance this new command is useful https://github.com/microsoft/vscode-js-debug/issues/260#issuecomment-705891014 but I wouldn’t have known about that without being subscribed to the issue, or hoping it was mentioned in the VSCode 1.51 release, or.. hoping the readme stays up to date with every change that goes through.

Should there be a changelog? Or move into a “releases” format?
My intention isn’t to slow down development as I see the continuous development works well here, but if there’s some way we can stay up to date that would be useful.

Interested in thoughts.

**Comment by connor4312** [comment]
I think this is a good idea, the release notes are higher level. I'll start keeping a changelog.md for this repo, thanks for the suggestion.

**Comment by jasonwilliams** [comment]
@connor4312 loving the changelog, it’s made life a lot easier and awesome to see some great changes happening too.
