### ISSUE TITLE
Cannot attach to browser on windows

### ISSUE THREAD

**Issue by jeiea** [microsoft/vscode-js-debug#799]
**Describe the bug**
vscode does not attach to chrome while macos does attach with same configuration.
windows error message is
![image](https://user-images.githubusercontent.com/4188984/95805767-2170ad80-0d41-11eb-9129-6d6fdb79b6e5.png)

**To Reproduce**
1. save `vscode/launch.json` with the following.
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "pwa-chrome",
      "request": "launch",
      "name": "Launch Chrome against localhost",
      "url": "http://localhost:8080",
      "webRoot": "${workspaceFolder}",
      "preLaunchTask": "npm start",
      "userDataDir": "${workspaceFolder}/.vscode/chrome",
      "cleanUp": "onlyTab",
      "port": 9239,
      "trace": true
    }
  ]
}
```
2. Press F5 on windows

**Log File**
[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode-js-debug/files/5368448/vscode-debugadapter-0.json.gz)
[vscode-debugadapter-1.json.gz](https://github.com/microsoft/vscode-js-debug/files/5368449/vscode-debugadapter-1.json.gz)

**Environment**
```
Version: 1.50.0 (system setup)
Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
Date: 2020-10-07T06:10:52.432Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

**Additional context**
vscode debug console content
```
Verbose logs are written to:
d:\...\AppData\Roaming\Code\logs\20201013T092308\exthost1\ms-vscode.js-debug\vscode-debugadapter-4.json.gz
[16168:6740:1013/104440.572:ERROR:tcp_socket_win.cc(352)] bind() returned an error: �׼��� ���ѿ� ���� ������ ���Ͽ� �׼����� �õ��߽��ϴ�. (0x271D)
[16168:6740:1013/104440.576:ERROR:tcp_socket_win.cc(352)] bind() returned an error: �׼��� ���ѿ� ���� ������ ���Ͽ� �׼����� �õ��߽��ϴ�. (0x271D)
[16168:6740:1013/104440.576:ERROR:devtools_http_handler.cc(297)] Cannot start http server for devtools.
```

**Comment by connor4312** [comment]
Thanks for the issue. This appears to be a problem in Chrome, please open an issue and they can help root cause the issue: https://bugs.chromium.org/p/chromium/issues/entry
