### ISSUE TITLE
Debugger crashes after short amount of time with cryptic error message

### ISSUE THREAD

**Issue by jassmith** [microsoft/vscode-js-debug#800]
**Describe the bug**
After starting the debugger and using my app to attempt to log in, the debugger will crash causing all network traffic to simply hang.

**To Reproduce**
1. Press F5 in my project
2. Attempt to log in using Google Auth

**Log File**

[vscode-debugadapter-14.json.gz](https://github.com/microsoft/vscode-js-debug/files/5368535/vscode-debugadapter-14.json.gz)

**VS Code Version:**  1.50

**Additional context**
My process is running inside of a docker container inside of WSL 2. VSCode is using the WSL 2 remote extension to connect.  This is the launch config I need to use to get the source maps working:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Debug Glide",
            "url": "http://localhost:3000",
            "disableNetworkCache": true,
            "trace": true,
            "webRoot": "${workspaceFolder}",
            "sourceMapPathOverrides": {
                "/*": "/home/jason/code/*"
            },
        }
    ]
}
```

No idea if that helps. The map path override is due to the docker container having a different path to the files than vscode sees.

**Comment by connor4312** [comment]
What error message do you see / what do you mean by 'crashing'?

**Comment by jassmith** [comment]
Thats from the trace I attached above. I don't know why it happens and googling got me nowhere.

**Comment by jassmith** [comment]
Is there something more I can provide? After that error everything just kind of stops working. Chrome stops issuing network requests, nothing loads, etc.

**Comment by jassmith** [comment]
Just following up to see what more info I can provide.

**Comment by connor4312** [comment]
Thanks, apologies for the delay.

Would it be possible to [record a gif](https://gifcap.dev/) of you logging in with and without the debugger attached? In the log you sent it I don't see anything abnormal -- looks like the login iframe gets destroyed (after successful login?) and then that's the end of the logs.

**Comment by jassmith** [comment]
I will make you a recording. Long and short when the debugger is attached the iFrame closes and then everything stops working. I can't even reload the page. When the debugger is attached everything proceeds as normal.

**Comment by connor4312** [comment]
Ping

**Comment by jassmith** [comment]
Im sorry I don't have time to make the video because I lost the branch with the debugger config. Closing the issue to avoid cluttering your repo.
