### ISSUE TITLE
Launch Chrome configuration gives Unable to Attach to browser error

### ISSUE THREAD

**Issue by bernardolk** [microsoft/vscode-js-debug#803]
**Describe the bug**
Whenever i try launching chrome using the standard config it gives an "Unable to attach to browser" error.
Note that i am not even trying to attach to the browser, but to launch it.

**To Reproduce**
1. Use this configuration in launch.json
```
{
         "name": "Launch Chrome",
         "request": "launch",
         "type": "pwa-chrome",
         "url": "http://localhost:3000",
         "webRoot": "${workspaceFolder}"
      },
```
2. Select configuration 'Launch Chrome' in run tab
3. See error

**VS Code Version:** 1.48

**Comment by connor4312** [comment]
Can you please collect a trace log using the instructions in the issue template?

**Comment by bernardolk** [comment]
I am afraid nothing shows up on debug console, it doesn't even start the debugging session.

**Comment by connor4312** [comment]
To clarify `trace: true` should be a property beside the name/request/type properties in your launch config.

**Comment by bernardolk** [comment]
Thanks, here is the log file.

[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode-js-debug/files/5392978/vscode-debugadapter-0.json.gz)

**Comment by connor4312** [comment]
Thanks for the logs. What version of Chrome do you have running locally?

**Comment by bernardolk** [comment]
Version 86.0.4240.75 (Official Build) (64-bit)

**Comment by connor4312** [comment]
Okay, thanks. It looks like Chrome is closing the debug connection. But I also notice you're a couple months behind in updates, I suggest updating VS Code (latest is 1.50.x) and seeing if the problem still occurs.

**Comment by jakubnavratil** [comment]
Maybe this helps:
https://github.com/microsoft/vscode-js-debug/issues/896#issuecomment-745215503

**Comment by connor4312** [comment]
Closing since we haven't heard back.
