### ISSUE TITLE
Optional configuration option for logging stdout/stderr of runtimeExecutable to debug console

### ISSUE THREAD

**Issue by chillophil** [microsoft/vscode-js-debug#804]
## What I wanted to do
Actually I tried to setup a launch configuration to run a (npm) script via "runtimeExecutable" (in fact: "ng serve") while additionally utilizing "serverReadyAction" for executing the "debugWithChrome" action when a specific pattern is matched in the output.

<details>
<summary>Original approach (launch.json)</summary>

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Angular Serve",
            "type": "pwa-node",
            "request": "launch",
            "runtimeExecutable": "npx",
            "args": [
                "ng",
                "serve"
            ],
            "skipFiles": [
                "<node_internals>/**"
            ],
            "serverReadyAction":{
                "pattern": "http://localhost:([0-9]+)",
                "uriFormat": "http://localhost:%s",
                "action": "debugWithChrome",
				"webRoot": "${workspaceFolder}"
            }
        }
    ]
}
```

</details>

## Why it failed
Unfortunately "serverReadyAction" (still) only recognizes patterns in the "debug console" (via DAP resp. "DebugAdapterTracker") and the output of the "npx ionic serve" command does not appear within the "debug console".

## What I did (workaround)
As a workaround I wrote a small node script, which uses a "shell" (in this case the "cmd.exe" for Windows) to execute the actual desired program via "child_process.spawn" and makes all output available in the "debug console" via console.log etc.

Then I launched that script as "pwa-node program", which in turn spawns - based on its "args" - the actual "ng serve" command.

<details>
<summary>Workaround node script (spawn.js)</summary>

```
const { spawn } = require("child_process");

const cmd = spawn("cmd.exe", [
    '/C',
    process.argv.slice(2).join(" ")
], { cwd: process.cwd() });

cmd.stdout.on('data', (data) => {
    console.log(`${data}`);
});

cmd.stderr.on('data', (data) => {
    console.error(data.toString());
});

cmd.on('close', (code) => {
    console.log(`Child process exited with code: ${code}`);
});

cmd.on('error', (err) => {
    throw err;
});
```

</details>

I had to take the indirect step via "cmd.exe", because "child_process.spawn" apparently does not add/try (executable) suffixes automatically, i.e. I would had to provide "ionic.cmd" to "child_process.spawn" instead of just "ionic" like I would do in any terminal.

<details>
<summary>Workaround launch configuration (launch.json)</summary>

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Angular Serve",
            "type": "pwa-node",
            "request": "launch",
            "program": "${workspaceFolder}/spawn.js",
            "args": [
                "npx",
                "ng",
                "serve"
            ],
            "skipFiles": [
                "<node_internals>/**"
            ],
            "serverReadyAction":{
                "pattern": "http://localhost:([0-9]+)",
                "uriFormat": "http://localhost:%s",
                "action": "debugWithChrome",
				"webRoot": "${workspaceFolder}"
            }
        }
    ]
}
```

</details>

## What I wish for / request
Provide a configuration option to enable logging of stdout/stderr from "runtimeExecutable" to "debug console".

## Why I wish for it
Even though the workaround woks as expected, it is not very pleasant and not intuitive.

**Comment by connor4312** [comment]
Thanks for the detailed issue. This is available today via the `"outputCapture": "std"` option in your launch.json. Let me know if that works for you.

**Comment by chillophil** [comment]
> This is available today via the `"outputCapture": "std"` option in your launch.json.

Well, I guess I overlooked that one. :upside_down_face:

That works for me! :+1:
