### ISSUE TITLE
Unable to debug the Angular Application from VS code

### ISSUE THREAD

**Issue by GaneshSingaravelu** [microsoft/vscode-js-debug#805]
Hi All,

I am getting below error when I tried to debug my application. Please do the needful

**"Cannot connect to the target at localhost:9222: Could not connect to debug target at https:\\localhost:9222: Promise was canceled"**

launch.json

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to Chrome",
            "port": 9222,
            "request": "attach",
            "type": "pwa-chrome",
            "webRoot": "${workspaceFolder}"
        },
        {
            "type": "pwa-chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:4200",
            "webRoot": "${workspaceFolder}"
        }
    ]
}

Thanks,
**Ganesh. S**

**Comment by connor4312** [comment]
This means that your browser was not launched in debug mode -- we couldn't connect to it on the given port. Please make sure [it's launched correctly](https://blog.chromium.org/2011/05/remote-debugging-with-chrome-developer.html).
