### ISSUE TITLE
Auto attach timeout causing a miss in breakpoint hits

### ISSUE THREAD

**Issue by EmperorRXF** [microsoft/vscode-js-debug#806]
## Environment Info:
Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

---

## Issue:
I'm having an issue with javascript debugging using the new "auto attach" feature set to "with flag".

I'm using typescript with tsc-watch, and have defined a script in my package.json as follows:
`"start:debug": "tsc-watch --onSuccess \"node --inspect dist/index.js\""`

This works fine in one project but not in another.

The only difference is one is rather small, and the other is rather large and takes a significant time for tsc-watch to compile the code (i.e. > 10 secs.)

basically for the large project I'm seeing an output like below (note the `timeout` and the error about auto activate):
```
PS C:\Projects\service> yarn start:debug

3:43:51 PM - Starting compilation in watch mode...


3:44:03 PM - Found 0 errors. Watching for file changes.
Debugger listening on ws://127.0.0.1:9229/f744f378-e653-4369-89d3-2def85404d7c
For help, see: https://nodejs.org/en/docs/inspector
timeout

Error activating auto attach, please report to https://aka.ms/js-dbg-issue
graphile-migrate: Already up to date
[2020-10-20T10:14:11.183Z]: Running current.sql
[2020-10-20T10:14:11.199Z]: current.sql unchanged, skipping migration
[2020-10-20T10:14:11.209Z]: Finished (25ms)
Debugger attached.
```

but eventually the debugger gets attached (as seen at the end of the log). But this is too late and my Breakpoints have already been passed by.

Is there anyway I could increase this "timeout" shown above (I'm not sure what timeout this really is)?

BTW, I don't have any debug configuration in my launch.json. I'm just relying on the vscode auto-attach feature here.

**Comment by connor4312** [comment]
I don't have a good understanding of why this is happening. The 'heaviest' thing is actually activation of the extension, which could exceed the 5 second timeout, but that should only happen on the first attach (per workspace).

In the linked commit I bumped the timeout to 10 seconds (will be in the [next nightly](https://github.com/microsoft/vscode-js-debug#nightly-extension)) which may resolve this for you.

**Comment by isidorn** [comment]
@EmperorRXF can you reproduce this with the latest vscode insiders?

**Comment by EmperorRXF** [comment]
I can't seem to recreate it on vscode-insiders. Also on my regular vscode, the issue went away after I disabled the "Jest Test Explorer" (kavod-io.vscode-jest-test-adapter) extension =/

Can't figure out how they can be connected, but when I disable it it's all good, but the issue comes back if I enabled. But since it's also working find in code-insider, I guess it's fine

**Comment by connor4312** [comment]
It could be that the compilation caused the jest test explorer to do some expensive work in the extension host thread, preventing js-debug from being able to receive the command and start debugging.
