### ISSUE TITLE
Logpoints are not bound after navigating in tab

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#807]
- Debug vscode web UI
- Set a logpoint, see that it works
- Navigate the tab to some other url
- Click "back"
- The logpoints do not work
- If I unset and reset the logpoints, then they work

**Comment by roblourens** [comment]
Same for normal breakpoints

**Comment by connor4312** [comment]
Noticed this was slow and made some significant perf improvements in https://github.com/microsoft/vscode-js-debug/commit/b20937a7c46b30027885a7063af7402f8caac403 and https://github.com/microsoft/vscode-js-debug/commit/cc389d8fa99bf3fc8c1eb1798fb38a23fd074d81
