### ISSUE TITLE
Debugging package.json scripts doesn't work if npm.packageManager isn't set

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#808]
- Try to debug an npm script

![image](https://user-images.githubusercontent.com/323878/96632602-cb65b200-12cc-11eb-9be6-a6ef9ba4abcb.png)

From https://github.com/microsoft/vscode/issues/102050 cc @alexr00

**Comment by connor4312** [comment]
I left a comment on the PR, but one suggestion would be for the npm package to expose a command js-debug could call to resolve the package manager name in a given workspace/folder. If you think that's a good approach I can add it tomorrow.
