### ISSUE TITLE
Cannot successfully specify runtimeExecutable to point to alternate chrome installation in launch.json

### ISSUE THREAD

**Issue by jerryasher** [microsoft/vscode-js-debug#809]
**Describe the bug**

**To Reproduce**

1. With a create-react-app
2. And this launch.json 

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "pwa-chrome",
            "request": "launch",
            "name": "Launch Chrome Beta against localhost",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceFolder}",
            "runtimeExecutable": "/opt/google/chrome-unstable/google-chrome-unstable",
        }, 
    ]
}

```

running on Ubuntu 20.04, under WSL2 on Win 10

with google-chrome-unstable installed at /opt/google/chrome-unstable/google-chrome-unstable

Trying to launch the debugger by 

A. closing all chrome beta windows
B. clicking on the green triangle next to "RUN" in the debug panel

An alert box pops up:

Visual Studio Code  
Unable to attach to browser
[open launch.json] [cancel]

In the lower right corner a message pops up:

[Error running browser: spawn /opt/google/chrome-unstable/google-chrome-unstable]

NOTE:

This works okay if I uncheck in the settings Debug > JavaScript: Use Preview and thus use the old debugger

NOTE:

I like debugging against different versions of chromium. This example is with a version installed in WSL2, but I would also like to debug against Windows: Chrome, Chrome Beta and Chrome Canary.

**Log File**

**VS Code Version:** Replace me!
Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Additional context**

**Comment by connor4312** [comment]
> running on Ubuntu 20.04, under WSL2 on Win 10

The browser is launched on the UI Side (host machine), so you want to install the browser there and it should have a path like `C:/Progam File/...`.

If you want to _actually_ launch your browser within WSL and use something like VNC or X window forwarding to see it, you can add `"browserLaunchLocation": "workspace"` to your launch.json.

**Comment by jerryasher** [comment]
Thanks for taking a look at this @connor4312, your help did get this to work, specifically,

```
{
  "type": "chrome",
  "request": "launch",
  "name": "Launch Chrome Beta against localhost",
  "url": "http://localhost:3000",
  "webRoot": "${workspaceFolder}",
  "runtimeExecutable": "C:/Program Files/Google/Chrome Beta/Application/chrome.exe",
}, 

```

launched the debugger and connected to chrome beta running under **windows**

and this config, with `type: pwa-chrome` 

```
{
  "type": "pwa-chrome",
  "request": "launch",
  "name": "Launch Chrome Beta against localhost",
  "url": "http://localhost:3000",
  "webRoot": "${workspaceFolder}",
  "runtimeExecutable": "/opt/google/chrome-unstable/google-chrome-unstable",
  "browserLaunchLocation": "workspace",
}, 
  
```

launched the debugger and connected to chrome beta running under **wsl2**

great!

Where's the right place to make documentation suggestions?  It would be nice if these configs were a bit more explicitly documented, with examples given, and made easier to find.

The other area I stumbled on was understanding the url and port are malleable and the url/port that the various vscode "add configuration" steps provides for me have to be changed to actually fit what webpack (or whatever) is set to use.
