### ISSUE TITLE
Extension debugging is broken in the latest nightly

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-js-debug#811]
Trying to debug with the latest nightly causes the extension host in the Extension Development Host window to crash on startup.

Also debugging VS Code, I can't get any breakpoints to hit in the extension host (but there is no crash).

Switching back to the non-nightly fixes both issues.

**Comment by connor4312** [comment]
Fixed in https://github.com/microsoft/vscode-js-debug/commit/6c372683d1dcb4e986be244635edd8f11fdc9a82 and published
