### ISSUE TITLE
scopes: hash.bundle.js process unexpectedly exited

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#813]
- Debugging "Launch VS Code"
- Hit a breakpoint in "snippetController2.ts"

![image](https://user-images.githubusercontent.com/323878/96908310-52439780-1451-11eb-92f1-a7ba555cf00b.png)

**Comment by connor4312** [comment]
Can you collect a trace log?

**Comment by roblourens** [comment]
[vscode-debugadapter-1.json.gz](https://github.com/microsoft/vscode-js-debug/files/5424586/vscode-debugadapter-1.json.gz)

**Comment by roblourens** [comment]
I noticed that I had a pending update for the extension, so I reloaded, and now it works

**Comment by connor4312** [comment]
Oh, yea, probably related to https://github.com/microsoft/vscode-js-debug/issues/811. Thanks for the report!
