### ISSUE TITLE
Do not copy "serverReadyAction" property for integrated terminals

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-js-debug#814]
Do not copy "serverReadyAction" property for integrated terminals

**Comment by roblourens** [comment]
I can't create a codespace for the original reported repo, I get an error

> `ERROR: for codespaces-compose_node_1  Cannot create container for service node: conflicting options: host type networking can't be used with links. This would result in undefined behavior`

Can you explain what I need to verify this?

**Comment by connor4312** [comment]
Steps:

1. Use the server ready action tutorial https://code.visualstudio.com/docs/editor/debugging#_automatically-open-a-uri-when-debugging-a-server-program
1. Running it, the webpage should open once
1. Add `console: "integratedTerminal"` to the launch config
1. Run it again and verify that the webpage still only opens once
