### ISSUE TITLE
Please update the documentation for launch.json configurations to launch and connect to various chrome family browsers

### ISSUE THREAD

**Issue by jerryasher** [microsoft/vscode-js-debug#815]
See #809 for background...

I ran across a couple of stumbling blocks trying to get the new vscode debugger to launch and connect to Chrome.

The biggest issue I had was understanding that when vscode creates a launch.json for me, it doesn't understand the stack I am using and provide a correct url and port.  To be specific, it creates a url spec of localhost:8080 while I am using a create-react-app where the url and port should be localhost:3000

How am I, Joe Random user who doesn't know what the launch.json is really specifying to know that that url you provide me is just plain wrong?  As in, it's more wrong to provide the user a url with port of 8080, than to provide nothing and tell the user to fill that url in for themselves.

So that done, I like to debug in various alternate chrome browsers, including chrome beta, google-chrome-unstable, chrome canary, some of which run under windows on the UI side, and some of which run from wsl2

I found the following properties, neither of which were well documented for the current, newest debugger:

+ type -- should it be chrome or pwa-chrome?
+ runtimeExecutable should it be:
  + "C:\Program Files\Google\Chrome Beta\Application\chrome.exe"
  + "C:\\Program Files\\Google\\Chrome Beta\\Application\\chrome.exe"
  + "/mnt/c/Program Files/Google/Chrome Beta/Application/chrome/exe"
  + "/opt/google/chrome-unstable/google-chrome-unstable"

and then a kindly gent, @connor4312 suggested I could use the WSL2 google-chrome-unstable if I added in a `"browserLaunchLocation": "workspace"` pair.

It would be nice if launch.json configurations were documented for the current debugger and had several examples provided...

**Comment by connor4312** [comment]
Launch options are documented here: https://github.com/microsoft/vscode-js-debug/blob/master/OPTIONS.md

I would like to provide some smarter auto-config that detect things like CRA, getting closer to "zero-knowledge debugging" is a goal. At the moment this is partially filled with entrypoints like `Debug: Open Link`.

As for examples... I definitely see the value but am unsure about discoverability. I would wager that 90% of users just google "vscode debug create react app" and find our [existing tutorials](https://code.visualstudio.com/docs/nodejs/reactjs-tutorial#_debugging-react) or other of many blog posts and guides. You didn't notice the OPTIONS.md in this repo, so I think it's unlikely that Joe Random would find an EXAMPLES.md, and certainly not as easily as they would googling for their `<framework> vscode debug`.

**Comment by jerryasher** [comment]
> https://github.com/microsoft/vscode-js-debug/blob/master/OPTIONS.md

> You didn't notice the OPTIONS.md in this repo, so I think it's unlikely that Joe Random would find an EXAMPLES.md, and certainly not as easily as they would googling for their <framework> vscode debug.

Thanks, this is helpful, and you're right, I never stumbled it across it... So I am not sure how easily discoverable this options page is, and you're right, I never would have found a Examples.md page either.

Maybe I've filed this issue at the wrong place.  It is indeed the documentation at https://code.visualstudio.com/docs/ that I think needs updating.  When I click on "report issues" there, it takes me to

https://github.com/Microsoft/vscode/issues

and there I think I've been told to file vscode-js-debug isses here!

So, sigh, where should I file documentation issues for vscode-js-debug documentation at code.visualstudio.com?

Anyway had I found it that options page, I probably would have thought:

+ "https://github.com/microsoft/vscode-js-debug/blob/master/" "blob"? That's a weird URL to be looking at for authoritative documentation. I might hope to find documentation for options laid out more typically in a section of https://code.visualstudio.com/docs, where I might find 

  + concepts
  + specifiication
  + examples

https://github.com/microsoft/vscode-js-debug/blob/master/OPTIONS.md doesn't really provide typical documentation features: toc, search, glossary, or an indication of how this fits in context

And then too, I would have also thought the documentation here is sparse and not fleshed out for noobs, beginners or the like, as an example:

https://github.com/microsoft/vscode-js-debug/blob/master/OPTIONS.md#browserlaunchlocation

> browserLaunchLocation  
Forces the browser to be launched in one location. In a remote workspace (through ssh or WSL, for example) this can be used to open the browser on the remote machine rather than locally.

>Default value:
"workspace"

there is no real information here what acceptable values for browserLaunchLocation look like, windows paths, wsl2 paths, host paths, target paths, file url paths, etc.

----
https://github.com/microsoft/vscode-js-debug/blob/master/OPTIONS.md#port-1

> port

> Port for the browser to listen on. Defaults to "0", which will cause the browser to be debugged via pipes, which is generally more secure and should be chosen unless you need to attach to the browser from another tool.

I know what a port number is, I do not know what "for the browser to listen on"

+ is it some internal debugging api?
+ is it the port in the URL that various web backends expose their endpoints on as modified by webpack or proxies or docker or ?

It seems to be the latter, it would be good if there was some overview of just what is going on, and what this port means, so that the information can be derived.

Anyway, thanks
