### ISSUE TITLE
Blazor page gets stuck after opening new tab [It seems related to hitting some breakpoints]

### ISSUE THREAD

**Issue by digeff** [microsoft/vscode-js-debug#819]
**Describe the bug**
Web-page gets stuck after opening a new tab, and trying to navigate in the original page (It's probably paused)
This issue was reported originally on VS at https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1238459
I verified that it also happens on vs-code, so I'm moving it here.

**To Reproduce**
1. Create a new Blazor WebAssembly project. (Or use the one I'm attaching)
2. Set 2 breakpoints at line10(private int) & line14(currentCount++) of "Pages\Counter.razor".
3. Using Chrome/MSEdge Browser debug Project
4. Navigate the web page to the fetch-data page.
5. Click "About" button in web page.
6. Back to web page, all menu can't be clicked & it can't be reloaded successfully.

[BlazorApp14.zip](https://github.com/microsoft/vscode-js-debug/files/5447016/BlazorApp14.zip)
[log when broken - vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode-js-debug/files/5447019/log.when.broken.-.vscode-debugadapter-0.json.gz)
[log when it works - vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode-js-debug/files/5447021/log.when.it.works.-.vscode-debugadapter-0.json.gz)

**Comment by connor4312** [comment]
This no longer appears to happen in the most recent version of js-debug/blazor.
