### ISSUE TITLE
Failed console.assert(this._pausedForSourceMapScriptId === scriptId);

### ISSUE THREAD

**Issue by digeff** [microsoft/vscode-js-debug#82]
One was 13 and the other 14.
![image](https://user-images.githubusercontent.com/14098140/68708224-1c5f1900-0548-11ea-8fd3-8c8caee49e59.png)

**Comment by digeff** [comment]
Got the same thing with undefined now:
![image](https://user-images.githubusercontent.com/14098140/68708308-4dd7e480-0548-11ea-8c4b-edc1b1cdd9ff.png)

**Comment by connor4312** [comment]
Do you have a reliable repro for this or a project where this often happens? I haven't noticed this assertion failing before but I might just have not happened to see it in the console.

**Comment by digeff** [comment]
I don't. Sorry :/

**Comment by connor4312** [comment]
I haven't seen this at all. It may have been a bug that's since been fixed. I'm going to close it out unless we can get a repro on it, or log.
