### ISSUE TITLE
Debugging Cypress Test Script using VScode Chrome Debugger 

### ISSUE THREAD

**Issue by Nesay-hub** [microsoft/vscode-js-debug#821]
Hi Could you can please share sample project  for Debugging Cypress Test Script using VScode Chrome Debugger  for any WebSite given URL not the Application locally

**Comment by connor4312** [comment]
There are quite a few guides out there, .e.g https://medium.com/guidesmiths-dev/how-to-configure-visual-studio-code-for-test-debugging-39d0d7f24d79

**Comment by Nesay-hub** [comment]
So sorry sir , I did followed the link  https://medium.com/guidesmiths-dev/how-to-configure-visual-studio-code-for-test-debugging-39d0d7f24d79 but could not able to achieve  it does not show to bebugging the given URL of any Website it has example for local project like App.js. Please help me on this,I request
