### ISSUE TITLE
Support Debugger for Chrome extension

### ISSUE THREAD

**Issue by nguyenyou** [microsoft/vscode-js-debug#822]
Following this tutorial https://code.visualstudio.com/docs/nodejs/reactjs-tutorial#_debugging-react to debug ReactJS, however, inside the devcontainer, the **Debugger for Chrome** extension couldn't attach to browser:

![image](https://user-images.githubusercontent.com/38455472/97398488-eb752100-191d-11eb-9b4e-d1acf887257f.png)

Is this a bug or a feature's not yet supported?

---

OS: Ubuntu 20.04
Docker: 19.03.12
VSCode: 1.50.1

Extensions:
Remote-Containers: ms-vscode-remote.remote-containers v0.145.1
Debugger for Chrome: msjsdiag.debugger-for-chrome v4.12.11

Steps to reproduce:

1. Create and open an empty folder
2. Ctrl+P => Remote-Containers: Add Development Container Configuration Files => Choose Node.js => 12
3. Ctrl+P => Remote-Containers: Reopen in container
4. Open terminal: `$ npx create-react-app myapp`
5. `$ cd myapp && yarn start`
6. https://code.visualstudio.com/docs/nodejs/reactjs-tutorial#_set-a-breakpoint
7. https://code.visualstudio.com/docs/nodejs/reactjs-tutorial#_configure-the-chrome-debugger
8. Then press F5 or the green arrow to launch the debugger and open a new browser instance. 
==> Unable to attach to browser

**Comment by connor4312** [comment]
This is supported. What is your launch config, and how is the browser being launched?

**Comment by nguyenyou** [comment]
@connor4312 I've just updated the steps to reproduce issue. Please take a look.

**Comment by connor4312** [comment]
Thanks for the info. Are you able to debug Chrome outside of the devcontainer (you can test this by using the `Debug: Open Link` command with VS Code opened in a local folder)

**Comment by nguyenyou** [comment]
Outside the devcontainer => Debug: Open Link => the Chrome browser is open, the react app is running, however, the break point didn't work. It didn't stop at the breakpoint.

**Comment by connor4312** [comment]
Thanks, you could grab a trace log using these instructions?

> If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
> ⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by likt0r** [comment]
Hi 

is there a solution for this problem?
I am able to debug locally, but not in my devcontainer enviroment.
I try to debug not react instead it is an nuxt app, but it should make no difference
I added trace:true to the launch.json and here is the log file.

[vscode-debugadapter-a304ca82.json.gz](https://github.com/microsoft/vscode-js-debug/files/5883825/vscode-debugadapter-a304ca82.json.gz)

Would love to debug from my devcontainer :)

Greetings
