### ISSUE TITLE
Add option to continuously retry for restarting chrome attach debugging

### ISSUE THREAD

**Issue by nikitalita** [microsoft/vscode-js-debug#827]
**Is your feature request related to a problem? Please describe.**
Add the option to continuously retry for chrome attachment, even if the process has exited.

**Describe the feature you'd like**

This is kind of hard to explain, so let me show you my use case:

[This is my `launch.json`.](https://gist.github.com/nikitalita/0da18b4065a5b92304824391910c212d)

In order to speed up iterative development of my Electron app, I have `webpack --watch` set up, and I am using [electronmon](https://github.com/catdad/electronmon) to launch the app. Electronmon is a tool to restart either the renderer process or the main process whenever the watched code changes. It's very handy, as I can see my changes in action almost instantly whenever I save.

For debugging, I have a compound debugging setup to debug both the main and the renderer process. The main process `pwa-node` debugger launches, the renderer process `pwa-chrome` debugger attaches.

Now, when electronmon restarts the renderer process, this works fine; the renderer debugger has `restart` enabled, and its target hasn't been destroyed, so it will reattach just fine. However, whenever electronmon restarts the main process, it necessarily has to terminate the renderer process. While the main process debugger doesn't quit, when the renderer bugger tries to reattach, it just retries once and then just exits.

What I'd like to be able to do here is just have the chrome debugger retry for attachment, even if the process has terminated. Maybe something similar to `maxAttempts` and `delay` restart options like the `pwa-node` target has?

**Trace log**
Even though it looks like this is intended behavior, for references' sake, here is a trace log of what happens when trying the above. This only has the renderer trace log; I'd include both the main and renderer trace logs, but trace logs for compound targets are broken, see #825 .

[vscode-debugadapter-6.json.gz](https://github.com/microsoft/vscode-js-debug/files/5460621/vscode-debugadapter-6.json.gz)
(Using the `/^(?:(?!\bSourceMap\b|\bsource map\b|\bloadedSource\b|\bCreating source\b|\bscriptParsed\b).)+$/m` regex will filter out all the souce loading log entries and make it easier to view this)

I made changes to the renderer code to make electronmon restart the renderer process, and then made changes to the main code to make it restart the main process. The chrome debugger attached fine in the former case, but not the latter.

Here's the point in the logs when the main process restarts and takes down the renderer process:
![image](https://user-images.githubusercontent.com/69168929/97623190-89caba80-19e2-11eb-96ed-2c4a2bf9f084.png)

I'm not quite sure why exactly it's quitting here; It may be just detecting the target has been destroyed but I'm not sure of the mechanics of target destruction here. Either way, again, this looks like intended behavior.

**Comment by nikitalita** [comment]
BTW, if what I'm doing here is dumb or if there's a better option that would obviate the need for this, please let me know.

**Comment by connor4312** [comment]
This should now work, let me know if not.
