### ISSUE TITLE
Better experience for the diagnostic tool in remote

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#828]
With https://github.com/microsoft/vscode/issues/109507, it pastes the path to an html file to my clipboard. This is ok but I have to do some work to see the nice html file. A couple other suggestions

- Open a webview with the diagnostic tool
- Start a server to serve the html, and then I think you should be able to trigger the port forwarding and local browser with openExternal

**Comment by connor4312** [comment]
I think I'll do the webview approach. That will make the branding suggestions @misolori mentioned a lot easier as well, since then I will have access to the user's theme variables.
