### ISSUE TITLE
Allow prompt for which browser tab to attach to

### ISSUE THREAD

**Issue by JoeLudwig** [microsoft/vscode-js-debug#830]
I'm developing a project that involves multiple tabs at once, but usually when I want to debug something I only want to debug one of those tabs. Unfortunately the new debugger attaches to all chrome instances that match the debugger port number in launch.json. That means I get all the debug output from all tabs combined into one Debug Console, and it's difficult to tease out which tab caused which output.

The behavior in the old chrome debug extension was to prompt with a list of tab titles, and that worked much better for me. I could attach, and then pick the tab I wanted, much I like I would use the Attach window in native Visual Studio to attach to a single process.

I can see where attaching to more than one tab at the same time would be useful. Maybe selecting one behavior or the other could be an option?

If I want to narrow down to a single tab I can detach from everything but the one I want, but that doesn't pull the other tabs' output from the Debug Console window, so it doesn't help with that problem at all:
![image](https://user-images.githubusercontent.com/303656/97811896-5aaa8800-1c32-11eb-9193-d24bfd048590.png)

**Comment by connor4312** [comment]
You can do this by adding `"targetSelection": "pick"` to your launch.json which will result in identical behavior to the old debugger 🙂

**Comment by JoeLudwig** [comment]
Great!  Was that documented somewhere? I couldn't find anything on the available options for the new debugger.

It also annoys VS Code (but does seem to work):
![image](https://user-images.githubusercontent.com/303656/98263751-0823e100-1f3c-11eb-8ae7-2bd6b05067b4.png)

**Comment by connor4312** [comment]
It's in [OPTIONS.md](https://github.com/microsoft/vscode-js-debug/blob/master/OPTIONS.md). You can change your `type` to `pwa-chrome` instead of `chrome` so that options are validated against the new debugger.
