### ISSUE TITLE
Unable to attach debugger

### ISSUE THREAD

**Issue by exhaler** [microsoft/vscode-js-debug#831]
**Describe the bug**
After upgrading to node 12.19.0, I am no longer able to attach my Node.js debugger in VS Code. The following error is displayed:
![debug err](https://user-images.githubusercontent.com/45597942/97897694-25d42900-1d37-11eb-9815-c38ea8fdbc1d.jpg)

**To Reproduce**
1. Upgrading to node 12.19.0,
2. Press F5 in VS Code
3. See error

**Log File**
[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode-js-debug/files/5476809/vscode-debugadapter-0.json.gz)

**VS Code Version:**
Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Additional context**
Here is the `launch.json` configuration that is used:
`{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach to Node Functions",
      "type": "node",
      "request": "attach",
      "port": 9229,
      "preLaunchTask": "func: host start --verbose"
    }
  ]
}
`

Installing the nightly build does has same error

**Comment by connor4312** [comment]
I'm not seeing any such error in the log file you provided.

However this just means that there's nothing listening on that port; your process is not being launched in debug mode, or if it is it's not listening on that port.

**Comment by exhaler** [comment]
hmm it was working fine before, any other info i can send you?

**Comment by connor4312** [comment]
Make sure it's being launched in debug mode and successfully listening on the port. Local firewalls/antivirus can also sometimes block connections.

**Comment by exhaler** [comment]
Uninstalling Azure Function Core Tools and then reinstalling it fixed the problem.

Thanks for the help @connor4312
