### ISSUE TITLE
Feature request: remote/device debugging

### ISSUE THREAD

**Issue by richardszalay** [microsoft/vscode-js-debug#835]
Debugging against a device (either Chrome or an in-app browser) via the Chrome/Edgium dev tools is quite tedious: bring up the dev tools, select "Remote Devices" from the "..." menu, wait for device to appear, select it, click 'Inspect' on the appropriate instance.

It would be nice to have a "Remote Device" launch/debug option in VSCode that at least skips straight to the device/instance selection part of the experience.

**Comment by connor4312** [comment]
This actually has worked for a while in the new debugger.
