### ISSUE TITLE
Allow runtimeExecutable to be set globally

### ISSUE THREAD

**Issue by raulfpl** [microsoft/vscode-js-debug#836]
There should be a way to set the `runtimeExecutable` as a user config for the extension. That way you could set it up once instead of doing it for every new project, in case you don't have Chrome installed to one of the default paths.

**Comment by connor4312** [comment]
This can now be done via the `debug.javascript.defaultRuntimeExecutable` setting. Note that this happens at config resolution time, so for the moment only works with `pwa-` prefixed configs (e.g. if you have a launch type named `node`, then rename it to `pwa-node`)

**Comment by jtsom** [comment]
Just FYI... I added this
```
    "debug.javascript.defaultRuntimeExecutable": {
      "pwa-node": "node",
      "pwa-chrome": "dev"
    }
```
to my settings and that launched my Dev Chrome BlazorWasm application just fine.

Thanks!
