### ISSUE TITLE
Support ability to jump to symbol definition from Variables and Watches views

### ISSUE THREAD

**Issue by sandipchitale** [microsoft/vscode-js-debug#838]
- VS Code Version: 1.32.1

Steps to reproduce:

1.  Debug and go to Variables or Watch window.
2. The values and types for various objects are show.
3. Hookup the type of the value to the Go to Symbol in Workspace (CTRL+T) of VS Code to be able to jump to the declaration.

![image](https://user-images.githubusercontent.com/3310939/54317273-f0962880-459f-11e9-93ec-1b267e6c1e77.png)

Eclipse JDT debugger supports this for Java in Variables and Expressions (aka Watch) views - Open Actual Type

**Comment by sandipchitale** [comment]
For https://github.com/microsoft/vscode-js-debug/issues/838#issue-735587588 wont the Source map help in any way?

**Comment by starball5** [comment]
Related: https://code.visualstudio.com/updates/v1_93#_jump-to-variable-definition

**Comment by connor4312** [comment]
Ah, yes, thanks for the ping. This would be covered by https://github.com/microsoft/vscode-js-debug/pull/2056
