### ISSUE TITLE
Support showing network requests with stacktraces in debug console

### ISSUE THREAD

**Issue by junalmeida** [microsoft/vscode-js-debug#839]
Bring to vscode the chrome DevTools feature of showing stacktrace in debug console messages and the network connections panel.

**Comment by RedMickey** [comment]
Hello, with respect to showing network requests, it would be really great if the extension could display network traffic like Google Chrome does in the Network tab. I think It would be quite useful to have an ability to track network requests while debugging in VS Code. It could look like, for example, in the Flipper debugger.
![image](https://user-images.githubusercontent.com/33267199/103127390-a150b780-46a2-11eb-9f1d-0922957ba179.png)

**Comment by t-fritsch** [comment]
Hello @connor4312 👋

Just saw this issue was closed, but could you elaborate on why it is now considered "out-of-scope" ? 
It's surprising for an issue that has been posted 5 years ago and that was added to the backlog 3 years ago. Is it a technical limitation ?
thanks

**Comment by connor4312** [comment]
Ah, I realize the original issue scope is more narrow than the last comment (which would be out of scope). We could do simple logging of network requests/errors.

**Comment by t-fritsch** [comment]
thanks ! 🙏

**Comment by vish01** [comment]
Is there any update on this? It would be really nice if we can see the network requests going through. I'd appreciate if there's any other way to debug this. I can log the response and the request being sent but I can't see the API call itself going through.

**Comment by connor4312** [comment]
Yes: https://github.com/microsoft/vscode-js-debug/pull/2053
