### ISSUE TITLE
pm2 integration

### ISSUE THREAD

**Issue by dpkirchner** [microsoft/vscode-js-debug#846]
Currently, the node debug extension parses `ps` output (on Darwin/Linux) to list processes by pid, ppid, executive name (e.g. `/usr/local/bin/node`), arguments. This works fine for node processes that are run from a regular ol' command line, but not when using pm2. The issue appears to be that pm2 overwrites `process.title` with a string which has two effects: 1) `process.title` replaces the command and wipes the arguments and 2) the title doesn't include the `--inspect*` flags if set.

One way we can get around this is by conditionally looking up processes and pids using `pm2` itself. There's a `jlist` command that returns the process list in a machine-readable format:

```
pm2 jlist | jq -r '.[] | select(.pm2_env.exec_interpreter == "node") | "\(.pid), \(.name), \(.pm2_env.exec_interpreter), \(.pm2_env.pm_exec_path)"' | less
45555, private/xxx, node, /Users/dpk/Documents/git/project/api/private-xxx/index.js
45556, private/zzz, node, /Users/dpk/Documents/git/project/api/private-zzz/index.js
45557, private/yyy, node, /Users/dpk/Documents/git/project/api/private-yyy/index.js
```

(for the record I'm not suggesting converting the JSON output to flat strings, just doing this to show some of the useful, available keys.)

Ideally the `PickProcess` output would include the exec path and pid, and if available the debug port, just as it does with the `ps` based output. It may also or instead be useful to have a way to plug in a command that the extension can use to get a pid list in a specific format, for users that don't use `pm2`.

I don't personally know how to approach this or how to contribute to extensions, but if this would be something that might be accepted I can try to figure it out.

**Comment by connor4312** [comment]
This hasn't been a popular issue (on +1 over 3 years), so I don't plan on tackling it unless that changes
