### ISSUE TITLE
Enhancement: make debugger respect user-defined extension settings

### ISSUE THREAD

**Issue by Antonius-S** [microsoft/vscode-js-debug#848]
Currently extension doesn't respect user-defined non-standard extension settings neither from `files.associations` nor `\VSCode\resources\app\extensions\javascript\package.json`. Would be nice if it did.
Goal: to have an ability to launch JS files with non-standard extension, f.ex. `*.njs` or whatever (to distinguish Node sources from browser JS and shell JS).

**Comment by connor4312** [comment]
js-debug has done this for a little while now
