### ISSUE TITLE
[Heads-up] Upcoming WebAssembly Debugging changes in CDP

### ISSUE THREAD

**Issue by bmeurer** [microsoft/vscode-js-debug#853]
Following up on https://github.com/Microsoft/vscode-chrome-debug-core/issues/193, I wanted to give everyone here a heads up that we are in the process of changing the way WebAssembly is exposed via the CDP (Chromium DevTools Protocol). Previously we had exposed individual functions as so-called *fake scripts* via the protocol, in a way that the engine gives you a text format. In the future we'll only expose one script per Wasm module, and will not provide the text format anymore, but only the raw Wasm wire bytes.

The Chromium DevTools front-end is going to turn that into text format instead, probably leveraging an improved version of https://github.com/wasdk/wasmparser (which is also used in Firefox DevTools).

Part of this is that source locations will be consistently represented in terms of Wasm wire byte offsets. http://bit.ly/devtools-wasm-interface contains background information around these changes.

cc @rreverser @hashseed

**Comment by connor4312** [comment]
Thanks for the issue, this seems relatively straightforward to support. Let's do it.

**Comment by connor4312** [comment]
We adopted this a while ago
