### ISSUE TITLE
Conditional breakpoints not working when debugging Blazor WASM projects

### ISSUE THREAD

**Issue by EricCornelson** [microsoft/vscode-js-debug#855]
**Describe the bug**

Conditional breakpoints are not working when debugging Blazor WASM projects.

**To Reproduce**
1. Create a new Blazor project with `dotnet new blazorwasm`
2. Set a conditional breakpoint in `Pages/Counter.razor` in the `IncrementCount` function, on line 14 with the condition `currentCount == 10`
3. Start debugging
4. Navigate to the counter page and click the "Increment Count" button.
5. The breakpoint will hit on every click, even though the condition is not satisfied

**Log File**
[blazorlog.txt](https://github.com/microsoft/vscode-js-debug/files/5526301/blazorlog.txt)

**VS Code Version:** 
Version: 1.51.0-insider (user setup)
Commit: fce8fc82cacf0b4e2a18c633b6c6f3058702a5c9
Date: 2020-11-02T19:45:32.796Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by connor4312** [comment]
Please open this issue for the blazor folks -- we send the breakpoint with its condition, it's up to the runtime, not js-debug, to determine when its condition is met.

**Comment by EricCornelson** [comment]
Will do!
