### ISSUE TITLE
Smart auto-attach behavior

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-js-debug#856]
Version: 1.52.0-insider
Commit: 40558fc8e13dbdceee5f4a9ad3fc661b9f8dae15
Date: 2020-11-11T16:52:26.859Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15

I had an issue with GH auth token in a Codespace that revealed the following problem:
1) clone a repo from GH
2) remove the GH credentials from your keychain; the CLI now does not have any valid access token
3) open the cloned folder in VS Code
4) ensure auto-attach is configured as `smart`
4) in VS Code, sign into GH for example for setting sync
5) Run `git fetch` in the integrated terminal
-> the VS Code git credential helper kicks in which calls into the VS Code GitHub auth provider
-> The debugger auto-attaches to the credential helper

**Comment by connor4312** [comment]
hm, on Windows I didn't hit this, and on OSX I was blocked by

<img width="612" alt="image" src="https://user-images.githubusercontent.com/2230985/98988881-227e3180-24dd-11eb-9b3f-d48df0354b9d.png">

(cc @RMacfarlane)

Can you try the following to get more info?

1. `echo $NODE_OPTIONS`
1. Open the file and add `console.log(process.argv);`
1. git fetch again, and share the printed path to the credential helper

**Comment by connor4312** [comment]
I'm not sure why I didn't think of this approach initially, but I have changed auto attach to attach only to files in the workspace, except for well-known tools (e.g. mocha). This is in contrast what we did before where we attempt to attach to everything except things we intentionally block, and have convoluted logic to do so.

**Comment by connor4312** [comment]
note for verifiers: if you had auto attach on previously, js-debug will 'install' the new variables and bootloader the first time you auto attach after updating. So you may need to auto attach and then reopen/reload the terminal.
