### ISSUE TITLE
Auto attach in remote

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#857]
- Auto attach is "Smart"
- Connect to an SSH remote, open a terminal
- It prints an error while nvm is initializing

```
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '"/Users/roblou/Library/Application'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at Module._preloadModules (internal/modules/cjs/loader.js:824:12)
    at preloadModules (internal/bootstrap/node.js:601:7)
    at startup (internal/bootstrap/node.js:273:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `nvm use --delete-prefix v10.15.3 --silent` to unset it.
roblou@robfast:~$ vim ~/.bashrc 
roblou@robfast:~$ printenv | grep Library
NODE_OPTIONS=--require "/Users/roblou/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode.js-debug-nightly/bootloader.js" 
```

That path is pointing at my local machine. I don't know why that would happen. js-debug is installed on the remote.

![image](https://user-images.githubusercontent.com/323878/99020644-e2867100-2513-11eb-8e26-f36990f75bdf.png)

**Comment by connor4312** [comment]
This should only be able to happen if you previously used a Node version >=12, and then later downgraded to 10.

**Comment by roblourens** [comment]
Oh sorry, I think we talked about this already. I wasn't changing versions but I just changed the default from 10 to 12 and it works now. I don't know whether having 12 in a local window and 10 in a remote confused it somehow though.
