### ISSUE TITLE
Unable to set breakpoints (unbound breakpoint), using chrome debugger, WSL2 + Ubuntu

### ISSUE THREAD

**Issue by TomYeoman** [microsoft/vscode-js-debug#858]
**Describe the bug**

I'm unable to place debugger statements using WSL 2, With ubuntu. I get the message "Unbound Breakpoint" when trying to place any breakpoints 

**To Reproduce**

Using the launch config 

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "WSL Chrome",
      "type": "chrome",
      "request": "launch",
      "url": "http://localhost:3000",
      "webRoot": "${workspaceFolder}/src",
    }
  ]
}
```

On a fresh create-react-app project, I'm always unable to place a breakpoint, rather it's always set as "unbound breakpoint". 

following these steps to reproduce - 
- Create react app `npx create-react-app my-app` and move to folder `cd my-app`
- Start server `yarn start`
- Press F5, with my `launch.json` open, using the following script 

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "WSL Chrome",
      "type": "chrome",
      "request": "launch",
      "url": "http://localhost:3000",
      "webRoot": "${workspaceFolder}/src",
    }
  ]
}
```

I've also tried setting the "sourceMapPathOverrides" to ` "/*": "/__vscode-remote-uri__/*"` as i've seen suggested on numerous posts, with no luck  (E.G https://stackoverflow.com/questions/61953992/breakpoints-not-working-debugging-react-app-in-chrome-through-visual-studio-code/62207696#62207696)

![image](https://user-images.githubusercontent.com/14075632/99459535-2a4b3500-2926-11eb-9ecd-a63e7b6222c0.png)

It seems I CAN trigger a debugger within the editor, via using the "debugger" statement, rather than clicking on an actual breakpoint. The file the break appears in, however isn't my source

![image](https://user-images.githubusercontent.com/14075632/99460023-fc1a2500-2926-11eb-83d3-52481a89e9cb.png)

Debugger statement triggers in > `/home/wsl-tom/git/project`
Actual file where debugger was written > `//wsl$/Ubuntu-18.0/home/wsl-tom/git/project`

I tried using the sourceMapPathOverrides rule of >  `"/home/wsl-tom/*": "//wsl$/Ubuntu-18.0/home/wsl-tom/*",`, however it still triggers in wrong file. And I also still have the "unbound breakpoint" issue

**Log File**

Here's a log, of me selecting the breakpoint once the debugger is running
[vscode-debugadapter-4.json.gz](https://github.com/microsoft/vscode-js-debug/files/5556678/vscode-debugadapter-4.json.gz)

-->

![image](https://user-images.githubusercontent.com/14075632/99460541-ee18d400-2927-11eb-9f18-9d5e110c0346.png)

**Comment by connor4312** [comment]
I cannot reproduce this using the instructions provided. 

It looks like for you cra/webpack is embedding an absolute path to your script, e.g. `/home/wsl-tom/git/side-projects/keyboard-trainer/src/App.tsx`, which we trust and assume is correct. You'll want to fix this somehow, by either causing it to generate normal relative paths (cra doesn't allow you to configure much of anything, not sure if this is possible) or use the remoteRoot/localRoot properties to map the disk paths.
