### ISSUE TITLE
Should it debug Workers (Node worker_threads)?

### ISSUE THREAD

**Issue by matthiasg** [microsoft/vscode-js-debug#859]
I am using `const { Worker } = require('worker_threads')` in node 14/15 and cannot seem to get any debugging to work in vs code (1.51.1). I tried the standard debugger, starting via "Debug: Debug NPM Script", and the Javascript Debugger Nightly v2020.11.1117.

Whatever I do I can debug the main process all the way to the postMessage call, not more. I do not see any threads in the debugger and cannot step into the other thread either.

**Comment by connor4312** [comment]
Node.js sadly does not support debugging worker_threads. Feel free to subscribe to / add your 👍 to https://github.com/nodejs/node/issues/26609
