### ISSUE TITLE
When a target gets created and destroyed very fast, we end up in a "weird" state

### ISSUE THREAD

**Issue by digeff** [microsoft/vscode-js-debug#86]
![image](https://user-images.githubusercontent.com/14098140/68795782-7faf8080-0606-11ea-8c0e-20e86813c9f8.png)

The target gets created and destroyed very fast. The DAP sends the terminated event before we get the initialize request. After that, the DA doesn't respond the initialize but still sends loadSources events.

VS doesn't accept messages like continued when it thinks that the DA is still initializing.

[vscode-debugadapter.json](https://github.com/microsoft/vscode-pwa/files/3843021/vscode-debugadapter.json.txt)

**Comment by roblourens** [comment]
Hey @digeff, have you verified that this still reproes, since lots has changed, and if so can you share a script that reproes it?

**Comment by connor4312** [comment]
I try to repro this best I could by adding a hook to immediately disconnect sessions when VS Code started them

```js
vscode.debug.onDidStartDebugSession(session => {
  session.customRequest('disconnect', { restart: false });
});
```

I found one edge case (https://github.com/microsoft/vscode-js-debug/commit/311666373ecf10beecd208a8382c8ba4349daa7b) but it seems like the changes for https://github.com/microsoft/vscode-js-debug/issues/229 may have taken care of this as well. Please let me know if you still run into issues and/or have a repro for this.
