### ISSUE TITLE
[Feature] Allow to work with  vscode-browser-preview on codespace

### ISSUE THREAD

**Issue by congzhangzh** [microsoft/vscode-js-debug#863]
**Is your feature request related to a problem? Please describe.**

chrome debug does not work on codespace/online.visualstudio.com, even when I use headless browser

**Describe the feature you'd like**

make   *vs code codespace* + *vscode-live-server*  + * vscode-browser-preview * + *chrome debug/attach* works together on  codespace/online.visualstudio.com

Allow to work with in codespace/online.visualstudio.com,  as vscode-browser-preview plugin allow work on codespace which be mark as a remote scene， chrome plugin block it itself.

Btw, vscode-browser-preview works on codespace in browser, it's even faster than codespace's auto forward browser,  and support protocol like websocket(as it's real browser and has no proxy), which make many cool scene work, it's especially useful when work with vscode-live-server plugin

ref:
1. https://github.com/auchenberg/vscode-browser-preview
2. https://github.com/ritwickdey/vscode-live-server
3. https://developers.google.com/web/updates/2017/04/headless-chrome

**Comment by connor4312** [comment]
Thanks for the issue. We've been talking about doing something like this for codespaces.

**Comment by congzhangzh** [comment]
Cool!

Tks

**Comment by qinezh** [comment]
@connor4312 we have the same feature request. Do we have timeline or roadmap for it? I believe it would be an important feature for the daily development on Codespaces, especially when we develop/debug a frontend web app. Is it possible for us to raise its priority as it's still in Backlog? Thanks~

**Comment by mmiscool** [comment]
Any word on this. 

I am interested in using codespaces for front end development. If there was a method or browser extension that could link the built in chrome debugger to the browser based VScode instance that would be really nice.

**Comment by connor4312** [comment]
> chrome debug does not work on codespace/online.visualstudio.com, even when I use headless browser

You can set `browserLaunchLocation: "workspace"` to force the browser to try to launch/attach in the remote workspace instead of locally.

I don't have any plans in the forseeable future to make this work on web.
