### ISSUE TITLE
Debugger scans whole forlder for source maps when sourceMaps option is false.

### ISSUE THREAD

**Issue by Megabyteceer** [microsoft/vscode-js-debug#866]
**Describe the bug**
I don use js generation and have project with a lot of .js code. At debugging start browser freezes for a minute, and processMonitor shows that vscode scans js files. Documentation says that outFiles option used only if sourcrMaps is enabled. Adding empty pattern in to outFiles solves the problem, but it is not very obvious. Maybe if vscode have no find any sourcemaps ask user to disable scanning?

**VS Code Version:** 1.51.1

**Additional context**

**Comment by Megabyteceer** [comment]
That was fast. Thank you : )

**Comment by syvuilliot** [comment]
the option "sourceMaps: false" seems to be ignored again, since I need to configure "outFiles: []" to disable sourceMaps scanning to prevent very long startup of debugger in a js only repo

This is true since vscode 1.69
