### ISSUE TITLE
Exclude fragments from urlFilter matching

### ISSUE THREAD

**Issue by yrtimiD** [microsoft/vscode-js-debug#869]
Attach to chrome with remote debug fails without any error message since code 1.51.1. In 1.50 all worked fine.
Chrome version is latest 57.0.4280.66, started with `--remote-debugging-port=9222` and inspector is available from other chrome on http://localhost:9222/

**To Reproduce**
1. use linked launch.json
2. start chrome with `--remote-debugging-port=9222` 
3. Code -> Run -> select "Attach to Chrome" -> click play button

in 1.50 debugger toolbar appears and "Call stack" is populated with available pages, 
in 1.51.1 debugger toolbar appears without "disconnect" button, and nothing in "Call Stack"

**Log File**
[launch.json and debugadapter.json](https://gist.github.com/yrtimiD/b2732b311000a6fd2cc702269256d754)

**VS Code Version:** 1.51.1

**Additional context**
"Launch in chrome" still works perfectly.

**Comment by connor4312** [comment]
Can you try with the [nightly build](https://github.com/microsoft/vscode-js-debug/#nightly-extension)? I think the changes in https://github.com/microsoft/vscode-js-debug/issues/834 should fix this. In 1.50 (or maybe 1.49, I forget) we briefly introduced a change that made this work, but rolled it back with https://github.com/microsoft/vscode-chrome-debug/issues/719#issuecomment-705072583.

**Comment by connor4312** [comment]
Actually, I think it will still not work. Basically you want the url to actually be exactly `http://localhost/#`, or alternatively specify a `urlFilter` like `http://localhost/*`

**Comment by yrtimiD** [comment]
@connor4312 , specifying "url" **exactly** as in browser made it work. In my case it was `"url": "http://localhost/#"`.
Adding `"urlFilter": "http://localhost/*"` instead of `url` also fixes the issue.

**Comment by connor4312** [comment]
Actually I realized I already fixed this in https://github.com/microsoft/vscode-js-debug/issues/840. It's been released as of VS Code 1.52.
