### ISSUE TITLE
Debugger does not stop at any breakpoint; vscode reports unbound breakpoints

### ISSUE THREAD

**Issue by joma74** [microsoft/vscode-js-debug#870]
**Describe the bug**

**To Reproduce**
1. git clone https://github.com/joma74/wd-base-ws-one.git --branch vscode-js-debug-unbounded-breakpoints-issue
2. yarn
3. Set breakpoints at ./postcss.config.js L4; node_modules/.bin/parcel L3; node_modules/tailwindcss/lib/cli.js L4;
4. Debug View -> "Launch Parcel"
4. Every Breakpoints are classified as "Unbound breakpoint", Breaks nowhere

Console Output
```
 /usr/bin/env 'NODE_OPTIONS=--require /usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js --inspect-publish-uid=http' 'VSCODE_INSPECTOR_OPTIONS={"inspectorIpc":"/tmp/node-cdp.23962-1.sock","deferredMode":false,"waitForDebugger":"","execPath":"/home/joma/bin/node","onlyEntrypoint":false,"autoAttachMode":"always","fileCallback":"/tmp/node-debug-callback-5aa18ac44d41djoma@edison:wd-base-ws-one (vscode-js-debug-unbounded-breakpoints-issue=) $  /usr/bin/env 'NODE_OPTIONS=--require /usr/share/code/resources/app/extes-vscode.js-debug/src/bootloader.bundle.js --inspect-publish-uid=http' 'VSCODE_INSPECTOR_OPTIONS={"inspectorIpc":"/tmp/node-cdp.23962-1.sock","deferredMode":false,"waitForDebugger":"","execPath":"/home/joma/bin/node","onlyEntrypoint":false,"autoAttachMode":"always","fileCallback":"/tmp/node-debug-callback-5aa18ac44d41d79c"}' /home/joma/bin/node --nolazy node_modules/.bin/parcel --port 9500 index.html 
Debugger attached.
Server running at http://localhost:9500 
⠋ Building...Debugger attached.
Debugger attached.
Debugger attached.
⠴ Building hmr-runtime.js...Debugger attached.
Debugger attached.
✨  Built in 1.69s.
```

**Log File**

[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode-js-debug/files/5611381/vscode-debugadapter-0.json.gz)

**VS Code Version:** 1.51.1

**Additional context**
```
joma@edison:wd-base-ws-one (vscode-js-debug-unbounded-breakpoints-issue=) $ node -v
v14.9.0
```

**Comment by connor4312** [comment]
- node_modules/.bin/parcel is symlinked to the real cli script, so you need to pass `--preserve-symlinks-main` in your runtimeArgs like you would debugging other symlinked modules https://nodejs.org/api/cli.html#cli_preserve_symlinks_main 
- `node_modules/tailwindcss/lib/cli.js` is not imported in the program run by parcel. I don't see a postcss.config.js in the repo, and similarly this isn't reported as being loaded anywhere by Node

Let us know if you have any other questions
