### ISSUE TITLE
Unbound breakpoint in VS Code when serving a different configuration

### ISSUE THREAD

**Issue by Jackdhaigh** [microsoft/vscode-js-debug#872]
### My issue

I have an Angular application that I am trying to debug in [VS Code][1].

Currently when I serve the application e.g. `ng serve` my breakpoints are bound and the breakpoints get hit:

[![enter image description here][2]][2]

However, when I serve via a different configuration e.g. `ng serve -c qa` or `ng serve -c uat` the breakpoints become unbound:

[![enter image description here][3]][3]

Is there a reason why the breakpoints become unbound? How can I get the breakpoints to hit when serving with different environment configurations?

**To Reproduce**
1. Set a breakpoint in a `.ts` file where the breakpoint, in theory, should be bound
1. `ng serve -c ENVIRONMENT`
1. Observe that the breakpoint becomes unbound

## Log File
N/A

## VS Code Version:
`2020.10.2217`

### `launch.json` configuration:

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome against localhost",
      "url": "http://localhost:4200",
      "webRoot": "${workspaceFolder}"
    }
  ]
}
```

### Sample environment configuration `angular.json`:

```
"uat": {
  "fileReplacements": [
    {
      "replace": "src/environments/environment.ts",
      "with": "src/environments/environment.uat.ts"
    }
  ],
  "optimization": true,
  "outputHashing": "all",
  "sourceMap": false,
  "extractCss": true,
  "namedChunks": false,
  "extractLicenses": false,
  "vendorChunk": false,
  "buildOptimizer": true,
  "budgets": [
    {
      "type": "initial",
      "maximumWarning": "2mb",
      "maximumError": "5mb"
    },
    {
      "type": "anyComponentStyle",
      "maximumWarning": "6kb",
      "maximumError": "10kb"
    }
  ]
},
```

### Software versioning:

- [Visual Studio Code][1] `1.50.1`
- [Chrome][4] `83.0.4103.122`
- [Debugger for Chrome][5] `4.12.11`
- [JavaScript Debugger (Nightly)][6] `2020.10.2217`

  [1]: https://code.visualstudio.com/
  [2]: https://i.stack.imgur.com/FoWjS.png
  [3]: https://i.stack.imgur.com/yBmie.png
  [4]: https://www.google.com/intl/en_uk/chrome/
  [5]: https://github.com/Microsoft/vscode-chrome-debug
  [6]: https://github.com/microsoft/vscode-js-debug

**Comment by connor4312** [comment]
I see that you have `"sourceMap": false,`. Without sourcemaps we cannot map source location to their compiled locations, or vise versa.

**Comment by Jackdhaigh** [comment]
Thanks, I should have spotted that, sorry to waste your time.

**Comment by banyanscott** [comment]
Thanks for asking the question. It saved time for me! :)

**Comment by Vitruvius21** [comment]
I am using Angular 15 and Node 18. I have the same issue but my "sourceMap" under development configuration is "true", yet breakpoints are unbound.


`"architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "configurations": {
            "production": {
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "500kb",
                  "maximumError": "1mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "2kb",
                  "maximumError": "4kb"
                }
              ],
              "outputHashing": "all"
            },
            "development": {
              "buildOptimizer": false,
              "optimization": false,
              "vendorChunk": true,
              "extractLicenses": false,
              "sourceMap": true,
              "namedChunks": true
            }
          },
          "defaultConfiguration": "development"
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "configurations": {
            "production": {
              "browserTarget": "savings-app-osiris:build:production"
            },
            "development": {
              "browserTarget": "savings-app-osiris:build:development"
            }
          },
          "defaultConfiguration": "development"
        }
      }`

**Comment by SirZanty** [comment]
@Vitruvius21 I have the same issue

**Comment by bchaitanus** [comment]
I have the same issue
