### ISSUE TITLE
Debugged node process does not die when stopping debugging

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#873]
Debug something like this

```js
setInterval(() => {
    console.log(process.pid);
}, 1000)
```

With simple launch config

```json
{
            "type": "pwa-node",
            "request": "launch",
            "name": "Run",
            "trace": true,
            "program": "${file}"
},
```

[vscode-debugadapter-ad56950b.json.gz](https://github.com/microsoft/vscode-js-debug/files/5624963/vscode-debugadapter-ad56950b.json.gz)

Then kill it, it takes a few seconds for the debug widget to disappear. `ps ax | grep pid`, I see the process is still alive

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-js-debug/issues/864
