### ISSUE TITLE
JavaScript Debugger extension error: listen ENOTSUP: operation not supported on socket

### ISSUE THREAD

**Issue by ferenckv** [microsoft/vscode-js-debug#874]
**Describe the bug**
I get this error message
`listen ENOTSUP: operation not supported on socket /mnt/c/Users/username/AppData/Local/Temp/node-cdp.799-1.sock`
when trying to debug a project using Javascript debugger extension.

It also happens if I try to `Create Javascript debugger terminal` and if I use launch.json. 

**VS Code Version:** 1.51.1 with WSL remote.

**Comment by ferenckv** [comment]
I found the issue. I have setup `WSLENV=TMP/up`.

I'll leave this open just in case this could be considered an actual bug despite my config problem. Feel free to close it if not.

**Comment by connor4312** [comment]
Thanks for the info. I don't think there's anything I want to do here; this is the only report I've seen off this, and we use sockets in the tmpdir in other places as well.

Let me know if you run into any other issues.
