### ISSUE TITLE
autoAttachChildProcesses Not Allowed in extensionHost Configuration

### ISSUE THREAD

**Issue by dsanders11** [microsoft/vscode-js-debug#876]
**Describe the bug**

I'm not sure if this is the correct repo for this issue, apologies if it's not. When using the `extensionHost` debugger configuration type, the property `autoAttachChildProcesses` ("Property autoAttachChildProcesses is not allowed.") is shown as not being valid in the configuration, even though it does take effect if used.

So either the configuration schema isn't correct, or the feature isn't supported but works anyway. I hope it's the former, since the feature is very useful.

![image](https://user-images.githubusercontent.com/5820654/100815670-591edc00-33f9-11eb-959f-647e2e680b4f.png)

**To Reproduce**

1. Go to `.vscode/launch.json` for an extension
2. Add `autoAttachChildProcesses` to the debugger configuration.
3. Observe that the property is decorated as not allowed.

**VS Code Version:** 1.51.1

**Comment by connor4312** [comment]
That feature should work, I added a section to COMMON_PROBLEMS describing the scenario you're hitting: https://github.com/microsoft/vscode-js-debug/blob/master/COMMON_PROBLEMS.md#my-configuration-property-shows-as-invalid

Let me know if that resolves it for you.

**Comment by dsanders11** [comment]
Changing `type` to `pwa-extensionHost` does make the warning go away, and does appear to be functionally the same.

It's unfortunate, since that's not readily apparent for users. It took me a bit to even find this repo and know that it was the right one (was pointed this direction by someone), so I fear others are unlikely to find that documentation. I understand there's not an easy solution though.

I'll go ahead and close this issue since `pwa-extensionHost` does fix the warning, and is the workaround for it.
