### ISSUE TITLE
WSL2: Debugger hits unexisting breakpoints quickly and then continues

### ISSUE THREAD

**Issue by ialexi-bl** [microsoft/vscode-js-debug#877]
**Describe the bug**

I attach a debugger to the new MS Edge to a running react app and don't set any breakpoints. When I reload a page, there is a sequence of breakpoints that hit for a fraction of a second and immediately continue. This is very annoying, mainly because in doing so it reveals the "Sources" panel in developer tools all the time although I want "Console" tab to be open. 

Some observations:
1. It happens only when I set at least one breakpoint before reloading the page. When I just start the debugger, everything is fine, but when I create a breakpoint then delete it and reload the page, this happens
2. It also happens when I use logpoints, but not always. It happened on the main project where I discovered the issue, but it didn't when I tried to reproduce it on an empty CRA project (it didn't happen when hitting log points, but it did when reloading page)
3. It also happens in chrome or when launching chrome/edge instead of attaching to existing process

This doesn't happen in a project on Windows, only on WSL

**To Reproduce**

1. Create empty `create-react-app` project
2. `npm run start`
3. Set a breakpoint anywhere
4. Open page in browser
5. Remove breakpoint
6. Reload page

**Log File**
[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode-js-debug/files/5629755/vscode-debugadapter-0.json.gz)

**VS Code Version:** 1.52.0-insider, the same thing happened on earlier versions

**Comment by connor4312** [comment]
Thanks for the bug, duplicates https://github.com/microsoft/vscode-js-debug/issues/597
