### ISSUE TITLE
Auto attach to v8 failed

### ISSUE THREAD

**Issue by FishOrBear** [microsoft/vscode-js-debug#878]
the v8 code
```
V8Inspector* CreateV8Inspector(int32_t Port, void* InContextPtr)
{
    v8::Local<v8::Context>* ContextPtr = static_cast<v8::Local<v8::Context>*>(InContextPtr);
    return new V8InspectorClientImpl(Port, *ContextPtr);
}
};
```

I use manual f5 to attach to the process.
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "attach",
            "name": "Launch",
            "protocol": "inspector",
            "port": 9229,
            "sourceMaps": true,
            "trace": true
        }
    ]
}

```

But using automatic append has no effect.

I hope it can be automatically attached to V8 running in an external program, can you help me?

**Comment by FishOrBear** [comment]
![Uploading image.png…]()

**Comment by connor4312** [comment]
Please include a reproduction case

**Comment by FishOrBear** [comment]
repo:https://github.com/chexiongsheng/puerts_unreal_demo

This itself is a ue4 project. For convenience, I have compiled a program that can be run directly. You can open the program directly, and then press F5 in vscode to connect to it.

http://download.qcad.cc/WindowsNoEditor.zip

**Comment by FishOrBear** [comment]
http://download.qcad.cc/09-38-11.mp4

**Comment by connor4312** [comment]
Ah okay I see. I misread the original request

> But using automatic append has no effect.

Auto attach uses environment variables specific to Node.js, namely NODE_OPTIONS to --require a bootloader script that Node.js executes prior to running the user script. You can see this if you run `echo $NODE_OPTIONS` in a terminal where auto attach is enabled.

If you want the same to work for your custom invokation of V8, you'll need to look at that environment variable and do the same thing.
