### ISSUE TITLE
Support terminate request for better kill behavior

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#881]
Is this like the thing that's supposed to happen with the terminateRequest? From what I remember, the DA can opt in to first get a terminateRequest whenthe user clicks the stop button, then if the program doesn't terminate, the user can click the stop button a second time and the DA can try again with the stronger signal. https://github.com/Microsoft/vscode/issues/57018#issuecomment-415156959

_Originally posted by @roblourens in https://github.com/microsoft/vscode-js-debug/issues/630#issuecomment-738988895_

**Comment by fishLogic25** [comment]
Is this the correct thread for requesting the ability to specify the terminate signal with one like SIGTERM instead of SIGKILL?

**Comment by connor4312** [comment]
This is already possibly by specifying `"killBehavior": "polite"` in your launch.json

**Comment by fishLogic25** [comment]
Thanks for the response! I see the "Property killBehavior not allowed" when I add this to my launch.json. I am attempting to use this with the debug type: cppdbg. I was looking for the docs about this on the vscode site [here](https://code.visualstudio.com/docs/editor/debugging#_launchjson-attributes) but do not see mention of this. Any help would be appreciated.

**Comment by connor4312** [comment]
The C++ debugger is a separate project; this is the JavaScript debugger. You'll want to open an issue for them: https://github.com/microsoft/vscode-cpptools

**Comment by jbriales** [comment]
I tried `"killBehavior": "polite"` both in the official extension and nightly version, and it did not work in any case. 'Stop' still seems to just kill the process.
Where exactly should I add this option within `launch.json` and since when is it enabled/available?

**Comment by connor4312** [comment]
Can you share a small example repo or gif (https://gifcap.dev/) with what you're trying?

**Comment by Technoguyfication** [comment]
I'm getting a bit of a weird issue using polite kill behavior on Windows. When I use `forceful` kill behavior, it kill the process immediately as expected. However when using `polite`, the process doesn't stop at all. It doesn't even appear to receive the signal at all. This only happens on Windows systems, when I debug the project on my Macbook everything works exactly as expected. I've tested on my Windows desktop and laptop, same behavior on both systems.

I should mention I'm using Typescript, I'm not sure if that's related to the issue or not.

launch.json:
```json
{
	"type": "pwa-node",
	"request": "launch",
	"name": "Launch Program",
	"skipFiles": [
		"<node_internals>/**"
	],
	"program": "${workspaceFolder}/src/index.ts",
	"preLaunchTask": "tsc: build - tsconfig.json",
	"outFiles": [
		"${workspaceFolder}/build/**/*.js"
	],
	"envFile": "${workspaceFolder}/.env",
	"outputCapture": "std",
	"internalConsoleOptions": "openOnSessionStart",
	"killBehavior": "polite"
}
```

Sample index.ts:
```ts
process.on("SIGINT", () => terminate());
process.on("SIGTERM", () => terminate());

function terminate() {
	console.log("Shutting down...");
	process.exit(0);
}

function wait() {
	setTimeout(wait, 10000);
}

wait(); // wait forever until the process is killed
```

The process isn't even receiving the kill signal on Windows as far as I can tell, it looks like it spins up a few node processes when debugging and _one_ of them may be dying when debugging is stopped, but it's not the main process.

**Comment by rahbari** [comment]
Even with polite killBehavior, debugger console is disconnected from process as soon as Stop is pressed and debugging session is stopped even if process is still running. This behavior creates several problems.

Any message after stop is not printed to the debug consol:
`process.on("SIGTERM", () => console.log('TERM'));` // TERM won't be printed

If node process never stops, debugging session ends anyway and the process must be killed in activity monitor.
And when restarting, If the process is using a port it won't be free when the second one is started.
  
It's a better to wait for the process to exit and show a kill button after the stop is pressed in polite mode.

**Comment by connor4312** [comment]
We've since adopted this
