### ISSUE TITLE
Add a way to get the log line number when console.log has been wrapped by a custom function

### ISSUE THREAD

**Issue by bzuillsmith** [microsoft/vscode-js-debug#882]
**Is your feature request related to a problem? Please describe.**
I am working on a TS express app and the logger will use a custom `ConsoleTransport` class that wraps `console.log`. Now whenever it outputs to the debug console, the line number shows the code within my `ConsoleTransport` class. I added the file to `skipFiles` of the launch config with the hope that it would ignore that file and perhaps show me the top call in the stack that was not ignored, but it did not.

    // my launch.json configuration
    {
            "name": "Run Backend",
            "type": "node",
            "request": "launch",
            "runtimeArgs": ["--nolazy", "-r", "ts-node/register", "-r", "tsconfig-paths/register"],
            "args": ["./src/index.ts", "--transpile-only"],
            "cwd": "${workspaceFolder}/backend",
            "internalConsoleOptions": "openOnSessionStart",
            "skipFiles": [
                "<node_internals>/**",
                "node_modules/**",
                "${workspaceFolder}/backend/src/modules/logger/ConsoleTransport.ts"
            ],
            "env": {
                // ommitted
            }
    }

All the suggestions online show hacky or confusing ways of binding to console.log and/or overriding it which just feels wrong and unintuitive to me.

**Describe the feature you'd like**
I would love for it to use the first part of the stack that is not included in the `skipFiles` array or some way to tell the debugger to not use the strict line it called console.log but instead some custom function.

**Comment by connor4312** [comment]
Can you share more details around the logger you use, or a small example repo? I'm not totally clear what the output or output structure are.

**Comment by bzuillsmith** [comment]
I'm actually using the winston logger, but a custom console transport because theirs doesn't work with the debug console. I got it working with the debug console but now the line numbers all show my custom Console transport class.

**Comment by connor4312** [comment]
Can you share the custom transport?

**Comment by bzuillsmith** [comment]
I can do that in about an hour as I'm away from my desk, but it's literally their transport but with the console._stdout lines removed (and the of statements around them so it calls console.log)

**Comment by bzuillsmith** [comment]
//Modified winston Console logger to use console.log so it works with debugge
    'use strict';

    import os from 'os';
    import { LEVEL, MESSAGE } from 'triple-beam';
    import TransportStream from 'winston-transport';
    import winston from 'winston';

    /**
     * Transport for outputting to the console.
     * @type {Console}
     * @extends {TransportStream}
     */
    export class ConsoleTransport extends TransportStream {
        
        name: string;
        stderrLevels: object;
        consoleWarnLevels: object;
        eol: string;

        /**
         * Constructor function for the Console transport object responsible for
         * persisting log messages and metadata to a terminal or TTY.
         * @param {!Object} [options={}] - Options for this instance.
         */
        constructor(options: winston.transports.ConsoleTransportOptions = {}) {
            super(options);

            // Expose the name of this Transport on the prototype
            this.name = 'console';
            this.stderrLevels = this._stringArrayToSet(options.stderrLevels);
            this.consoleWarnLevels = this._stringArrayToSet(options.consoleWarnLevels);
            this.eol = options.eol || os.EOL;

            this.setMaxListeners(30);
        }

        /**
         * Core logging method exposed to Winston.
         * @param {Object} info - TODO: add param description.
         * @param {Function} callback - TODO: add param description.
         * @returns {undefined}
         */
        log(info, callback) {
            setImmediate(() => this.emit('logged', info));

            // Remark: what if there is no raw...?
            if (this.stderrLevels[info[LEVEL]]) {

                console.error(info[MESSAGE]);

                if (callback) {
                    callback(); // eslint-disable-line callback-return
                }
                return;
            } else if (this.consoleWarnLevels[info[LEVEL]]) {
                
                console.warn(info[MESSAGE]);

                if (callback) {
                    callback(); // eslint-disable-line callback-return
                }
                return;
            }

            console.log(info[MESSAGE]);

            if (callback) {
                callback(); // eslint-disable-line callback-return
            }
        }

        /**
         * Returns a Set-like object with strArray's elements as keys (each with the
         * value true).
         * @param {Array} strArray - Array of Set-elements as strings.
         * @param {?string} [errMsg] - Custom error message thrown on invalid input.
         * @returns {Object} - TODO: add return description.
         * @private
         */
        _stringArrayToSet(strArray: string[], errMsg?: string): object {
            if (!strArray)
                return {};

            errMsg = errMsg || 'Cannot make set from type other than Array of string elements';

            if (!Array.isArray(strArray)) {
                throw new Error(errMsg);
            }

            return strArray.reduce((set, el) => {
                if (typeof el !== 'string') {
                    throw new Error(errMsg);
                }
                set[el] = true;

                return set;
            }, {});
        }
    };

And the abridged code from another file to configure it with winston and export a logger:

    options.transports = [
        new ConsoleTransport({
            level: 'debug',
            format: format.combine(format.colorize(), format.errors({ stack: true }), format.simple()),
            handleExceptions: true
        }),
        new winston.transports['MongoDB'](mongoTransportOptions)
    ];
    
    export default winston.createLogger(options);

And of course I use it in various places to like `mylogger.log('message here', meta);

and it looks like this in the debugger 

    info: Application is starting in 'development' mode.                     backend/src/modules/logger/ConsoleTransport.ts:73
    info: A message somewhere else.                                          backend/src/modules/logger/ConsoleTransport.ts:73

**Comment by connor4312** [comment]
Thanks, I see what you mean.

I think your intuition to use skipFiles is the right approach. I've updated the debugger so that the location shown in log messages will be the first file that isn't matched by the `skipFiles`.

**Comment by bzuillsmith** [comment]
Amazing! Thanks so much for the quick work, I look forward to using it.

**Comment by bzuillsmith** [comment]
Just gave Insiders 1.53.0 a try and I'm still getting the skipped file line number. Pretty much the same setup as discussed above. I'm not sure what to do to debug it on my end. Feel free to send me a DM if you want to do a quick video/screen share to work it out. Otherwise let me know how I can be of help to debug this.

**Comment by connor4312** [comment]
Insiders doesn't use the nightly release -- you'll want to install the nightly js-debug build manually.

**Comment by bzuillsmith** [comment]
Ah got it. Would help if I read the readme, I apologize.

So now I have it running and I get line numbers within a node_module like `backend/node_modules/winston-transport/index.js:103`. This happens with or without my skip file line for my custom transport. Same config and code as above. I also tried changing the node_modules skip file to `backend/node_modules/**` and to `${workspaceFolder}/backend/node_modules/**` but the output is the same.

**Comment by connor4312** [comment]
I think you want `${workspaceFolder}/backend/node_modules/**/*.js` in order to match the glob. With that it should work, I think -- I remember testing using the code you sent last week

**Comment by bzuillsmith** [comment]
Ah, yes. That does the trick. Also I was hitting restart on the debug session which apparently uses the same cached launch config. It is working as expected with the glob pattern you just gave. Thanks a ton!

**Comment by connor4312** [comment]
sure thing, thanks for filing the issue and verifying :)
