### ISSUE TITLE
Debugging NodeJs from remote location using inspector protocol, cannot sourcemap

### ISSUE THREAD

**Issue by qkhanhpro** [microsoft/vscode-js-debug#886]
**Describe the bug**
Problem debugging NodeJs from remote location using inspector protocol

**To Reproduce**
Have a node project running inside K8S

1/ Folder structure
/dist
/src

2/ Distribution
`babel src --out-dir dist --copy-files --source-maps inline`
Start with
`node dist/main`

3/ Enable remote debugging 
`kill - USR1 <node_process>`
`port-forward` 9229

**Debugging process**
launch.json file
```
{
    "version": "0.2.0",
    "configurations": [
      {
        "type": "node",
        "request": "attach",
        "name": "Debug: service",
        "sourceMaps": true,
        "smartStep": true,
        "protocol": "inspector",
        "port": 9229,
        "restart": true,
        "address": "0.0.0.0",
        "skipFiles": [
          "<node_internals>/**",
          "<node_modules>/**"
        ]
      }
    ]
  }
```
- Inline sourcemap, decoded: 
`"{"version":3,"sources":["../src/app.service.js"],"names":["AppService"],"mappings":";;;;;;;;;;;;;AAAA;;;;IAGaA,U,WADZ,yB;;;;;;;+BAEY;AACT,aAAO,eAAP;AACD","sourcesContent":["import { Injectable } from '@nestjs/common';\n\n@Injectable()\nexport class AppService {\n  getHello() {\n    return 'Hello World!!';\n  }\n}\n"]}"`
- The debugger can attach to node process
- Distribution source can be loaded, breakpoints can be set
- Original source can not be loaded, as seen in the "loaded script" section

![image](https://user-images.githubusercontent.com/10443536/101725319-fa392100-3ae2-11eb-8c08-57d1ec0accae.png)

**VS Code Version:**
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:44:48.716Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-56-generic

**Additional context**
Using Chrome dev tool for NodeJs, Original source can be detected
![image](https://user-images.githubusercontent.com/10443536/101725528-69af1080-3ae3-11eb-8477-b664d1d70bf9.png)

However, as I put the breakpoint inside the original source, Chrome can not hold that breakpoint. It is set to the correct line in the built source instead ( From there I can only debug the built source, not the original source )

Did I do anything wrong? Is this a problem with the debuggers or NodeJs's inspector protocol itself?
How should debugging production code, running remotely ( often inside K8s or docker ) be done?

**Comment by connor4312** [comment]
Unless the paths are exactly the same between your local machine and image in k8s, you'll need to set the remoteRoot/localRoot to tell the debugger how to map paths between the two places. Check out https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_remote-debugging

**Comment by qkhanhpro** [comment]
> Unless the paths are exactly the same between your local machine and image in k8s, you'll need to set the remoteRoot/localRoot to tell the debugger how to map paths between the two places. Check out https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_remote-debugging

Actually I did try to config that and didn't work as I expected
Here is my structure inside image
![image](https://user-images.githubusercontent.com/10443536/101730849-55701100-3aed-11eb-953f-ecf9efd6ea24.png)

Here is my working dir
![image](https://user-images.githubusercontent.com/10443536/101731906-e7c4e480-3aee-11eb-987c-0c456bcd6cc2.png)


I tried multiple version. with/without trailing slash...
```
{
    "version": "0.2.0",
    "configurations": [
      {
        "type": "node",
        "request": "attach",
        "name": "Debug: service",
        "sourceMaps": true,
        "smartStep": true,
        "protocol": "inspector",
        "port": 9229,
        "restart": true,
        "address": "0.0.0.0",
        "skipFiles": [
          "<node_internals>/**",
          "<node_modules>/**"
        ],
        "localRoot": "/home/khanhdq/work/orders",
        "remoteRoot": ""
      }
    ]
  }
```

**Comment by connor4312** [comment]
Ok, thanks. Can you grab a trace log using the instructions in the issue template? That will help me diagnose further.

**Comment by qkhanhpro** [comment]
> Ok, thanks. Can you grab a trace log using the instructions in the issue template? That will help me diagnose further.

Thanks for the help.
This is the version with source root set to root folder that contains both /src and /dist
[sourceRootSetToRoot.json.gz](https://github.com/microsoft/vscode-js-debug/files/5670961/sourceRootSetToRoot.json.gz)


I did test out more and see that one configuration that produce something is to have both roots set to /dist folder ( by using identical build command on local and remote )
Then I am able to put the debugger at some specific point ( In my local source code! ) **which later, like Chrome, always step into the distribution code**

![image](https://user-images.githubusercontent.com/10443536/101735736-df6fa800-3af4-11eb-8468-960a9bfa8fa4.png)

Here is the log trace in that case
[DistributionAsSourceRoot.json.gz](https://github.com/microsoft/vscode-js-debug/files/5671008/DistributionAsSourceRoot.json.gz)

**Comment by qkhanhpro** [comment]
I added an example to illustrate what I mention above

The debugging point I set in my source code
![image](https://user-images.githubusercontent.com/10443536/101737907-109da780-3af8-11eb-86e5-c62d0dbcce82.png)
at getCaterogy function, using step-into
it moves into compiled distribution code
![image](https://user-images.githubusercontent.com/10443536/101738119-46db2700-3af8-11eb-81a6-93a4fd99d4aa.png)

**Comment by connor4312** [comment]
That would indicate to me that the sourcemaps being generated are not very good quality, or malformed in some way. What tool and configuration are you using to create them?

**Comment by qkhanhpro** [comment]
I think its babel
```
    "@babel/cli": "^7.10.5",
    "@babel/core": "^7.6.2",
    "@babel/node": "^7.6.2",
    "@babel/plugin-proposal-class-properties": "^7.10.4",
    "@babel/plugin-proposal-decorators": "^7.6.0",
    "@babel/plugin-transform-runtime": "^7.6.2",
    "@babel/preset-env": "^7.6.2",
    "@babel/runtime": "^7.6.2",
```

the build command is "babel src --out-dir dist --copy-files --source-maps"
Maybe I can try to create a minimal repo and give you access to that?

**Comment by qkhanhpro** [comment]
The minimal repo can be found here 
https://github.com/qkhanhpro/minimal-node-debug/tree/master/.vscode
Normally I just do 

docker build -t my-image .
docker run -p 3000:3000 -p 9229:9229 my-image

The url is http://localhost:3000/api/v1
We can put some debug point in app.controller and app.service to see the behaviour of debugger
Then I can attach to the application and see that all my debugging points jumps around erratically and also into the distribution code

The development-local way, using
`npm run start:dev` however, behave as it should

**Comment by qkhanhpro** [comment]
Now the issue look like described here 
https://github.com/microsoft/vscode/issues/19973

**Comment by connor4312** [comment]
It looks like this is a side-effect of downleveling async/await in babel. They create a bunch of extra code as you see, and apparently create sourcemaps that don't work well around async/await.

I'd recommend not downleveling async/await. It's quite slow, and all Node.js versions since 7.10 support async/await natively.
