### ISSUE TITLE
skipFiles not working on attach if program does not use require()

### ISSUE THREAD

**Issue by gordonmleigh** [microsoft/vscode-js-debug#887]
**Describe the bug**
The skipFiles setting is ignored when attaching to a process.

**To Reproduce**
See [repro repository](https://github.com/gordonmleigh/debug-bork) case 3a and 3b.

**Log File**
See [repro repository](https://github.com/gordonmleigh/debug-bork) `case3*.log.json`

**VS Code Version:**

Version: 1.52.0-insider
Commit: dbbf7079b20b3036b3ff5ac2e2106b84dd3c6d66
Date: 2020-12-10T16:23:20.433Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**also tried on:**

Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**Additional context**

See the linked repository for debugger launch settings and repro code.

**Comment by connor4312** [comment]
For some reason it seems like `require` never gets defined, so we are unable to look up the built-in modules. Not sure what's going on.

**Comment by connor4312** [comment]
Looked at this some more. I don't see a way to do this easily, and cases where skipFiles are used in Node, in "attach" mode, _and_ where the program also does not require anything is going to be very rare. So I do not plan to fix this.
