### ISSUE TITLE
Step Into ignored code stops debugging on node 14 rather than stepping over

### ISSUE THREAD

**Issue by gordonmleigh** [microsoft/vscode-js-debug#888]
**Describe the bug**
Step Into on `console.log` with `node_internals` ignored stops debugging rather than stepping over.

**To Reproduce**
See [repro repository](https://github.com/gordonmleigh/debug-bork) case 1.

**Log File**
See [repro repository](https://github.com/gordonmleigh/debug-bork) `case1*.log.json`

**VS Code Version:**

Version: 1.52.0-insider
Commit: dbbf7079b20b3036b3ff5ac2e2106b84dd3c6d66
Date: 2020-12-10T16:23:20.433Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**also tried on:**

Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**Additional context**

See the linked repository for debugger launch settings and repro code.

**Comment by connor4312** [comment]
It continues the program which then terminates. This seems like it may be a regression in 14, since 15 is back to the Node 12 behavior. Continuing in  #889
