### ISSUE TITLE
(Question) Does vscode-js-debug support private class fields?

### ISSUE THREAD

**Issue by leonardoraele** [microsoft/vscode-js-debug#892]
Private class fields doesn't appear in the "Variables" sidebar. I noticed v8 does have a method for reading private properties of objects, but it's in experimental stage: https://chromedevtools.github.io/devtools-protocol/v8/Runtime/#method-getProperties

Do I have to enable use of experimental api or something like this to see private fields; or is it just not implemented yet?

Example:
```js
class Subject
{
	publicValue = 'not so secret';
	#secretValue = 'my secret';
}

const subject = new Subject();
```

![example](https://i.imgur.com/bibB38h.png)

**Comment by leduyquang753** [comment]
It's now 2023 and I still can't see the fields in either the _Variables_ tab nor _Watch_ (`this.#stuff` throws "`SyntaxError`": Private field `#stuff must be declared in an enclosing class."). Is there something I need to do to enable the feature?

**Comment by connor4312** [comment]
This works for me, please make sure you're up to date on your debugger version

![image](https://github.com/microsoft/vscode-js-debug/assets/2230985/f9d33434-53cd-491e-855c-34070ffaa137)

**Comment by leduyquang753** [comment]
It turns out the compiler target was not high enough so TypeScript converted the `#` properties into name-mangled ones instead and those did not show in the debugger.
