### ISSUE TITLE
Can't attach to a subprocess in --inspect-brk mode on Linux and macOS on Node.js v15

### ISSUE THREAD

**Issue by RedMickey** [microsoft/vscode-js-debug#895]
Hello, this is [React Native Tools](https://github.com/microsoft/vscode-react-native) team. [We faced a problem while attaching to a subprocess](https://github.com/microsoft/vscode-react-native/issues/1465) launched in `--inspect-brk` mode. The problem is that the subprocess fails while `js-debug` is attaching to it. The problem is reproduced only on Linux and macOS on Node.js v15.x.

**To Reproduce**
We prepared a small demo for this issue.
1. Create a plain Node.js project
1. Add the following files there
    * Main.js
        ```js
        const cp = require('child_process');

        let port = 9224;
        console.log(port);
        let debuggeeProcess = cp.spawn("node", [`--inspect-brk=${port}`, `${__dirname}/subprocess.js`], {
          stdio: ["pipe", "pipe", "pipe", "ipc"],
        });

        debuggeeProcess.on("message", d => {
          console.log(d.toString());
        });
        debuggeeProcess.on("exit", d => {
          console.log("exit");
        });
        debuggeeProcess.on("close", d => {
          console.log("close");
        });
        debuggeeProcess.stdout.on("data", d => {
          console.log(d.toString());
        });

        setInterval(() => {
          console.log("testMain");
        }, 2000);
        ```

    * subprocess.js

        ```js
        setInterval(() => {
            console.log("testSubprocess");
        }, 1500);
        ```

1. Set a breakpoint on the `console.log("testSubprocess");` line
1. Run `Main.js` file in the terminal or via a `pwa-node` launch scenario
1. Attach to the subprocess on the 9224 port
    ```json
        {
            "name": "Attach",
            "port": 9224,
            "request": "attach",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "type": "pwa-node"
        }
    ```

After that the subprocess should fail, and you'll see something like this in console:

```log
testMain
testMain
exit
close
testMain
testMain
```

However if we remove `brk` in the spawn configuration and leave only the `--inspect` part, we can successfully attach to the subprocess.

**Log File**
[vscode-debugadapter-2b00893a.json.gz](https://github.com/microsoft/vscode-js-debug/files/5694513/vscode-debugadapter-2b00893a.json.gz)

**VS Code Version:** 1.53.0-insider, 1.52.0

**Additional context**
We investigated this problem and found out that a subprocess in `brk` mode fails after it gets the following CDP message([here in the code](https://github.com/microsoft/vscode-js-debug/blob/master/src/targets/node/nodeAttacher.ts#L223-L230)):

```jsonc
[2020-12-11 11:06:52] [Reply From Debugger To Target] {
  "id": 1009,
  "method": "Runtime.evaluate",
  "params": {
    "contextId": 1,
    "returnByValue": true,
    "expression": "typeof process === 'undefined' ? 'process not defined' : Object.assign(process.env, {\"NODE_OPTIONS\":\"--require \\\"/Users/user/Documents/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js\\\" --unhandled-rejections=warn\",\"VSCODE_INSPECTOR_OPTIONS\":\"{\\\"inspectorIpc\\\":\\\"/var/folders/yh/l05v9hvd6g3_6cspqq2n3nd00000gn/T/node-cdp.19043-4.sock\\\",\\\"ppid\\\":0,\\\"deferredMode\\\":false,\\\"waitForDebugger\\\":\\\"\\\",\\\"execPath\\\":\\\"/Users/user/.nvm/versions/node/v15.4.0/bin/node\\\",\\\"onlyEntrypoint\\\":false,\\\"autoAttachMode\\\":\\\"always\\\",\\\"requireLease\\\":\\\"/var/folders/yh/l05v9hvd6g3_6cspqq2n3nd00000gn/T/node-debug-callback-b02caabb52674d7b\\\"}\"})\n//# sourceURL=eval-78ac757a.cdp\n"
  }
}
```

We were able to fix the incorrect behavior by changing the expression part of the CDP message. We added the additional check which is already present in some other CDP `Runtime.evaluate` messages.

```diff
- typeof process === 'undefined' ? 'process not defined' : Object.assign
+ typeof process === 'undefined' || process.pid === undefined ? 'process not defined' : Object.assign
```

**Comment by connor4312** [comment]
Interesting. I can't reproduce it here, but I'll trust your fix. I know there are 'weird' things that can happen when trying to interface with node built-ins early on in attachment.

Since you can reproduce it, please let me know if the [next nightly](https://github.com/microsoft/vscode-js-debug#nightly-extension) works for you.

**Comment by SounD120** [comment]
Hi @connor4312 . I just tested the fix on the demo above and on the extension case that was broken before - it works good now on Node.js 15 for both cases. Thanks.
