### ISSUE TITLE
Cannot launch chrome debug

### ISSUE THREAD

**Issue by jakubnavratil** [microsoft/vscode-js-debug#896]
**Describe the bug**
I'm unable to launch chrome without specifiing `runtimeExecutable`:
```javascript
{
        "name": "Launch",
        "request": "launch",
        "type": "pwa-chrome",
        "url": "http://localhost:4200",
        "webRoot": "${workspaceFolder}",
        // "runtimeExecutable": "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe"
},
```
![image](https://user-images.githubusercontent.com/7920929/102200710-7ce82480-3ec5-11eb-9df9-4420213eab50.png)

No matter if type is `pwa-chrome` or `chrome`.
No matter if I got chrome running or not. 
Path to installed chrome seems normal to me. This worked some time ago but suddenly stopped.
Is there any way to make this work without specifiing `runtimeExecutable`? I dont know how debugger starts chrome, maybe I can help by placing some symlink somewhere.

**Log File**
[vscode-debugadapter-d2adc0be.json.gz](https://github.com/microsoft/vscode-js-debug/files/5694986/vscode-debugadapter-d2adc0be.json.gz)

**VS Code Version:** Latest insiders - but long lasting problem

**Comment by jakubnavratil** [comment]
Well I figured it out:
I had dual installation in %AppData%/Local/Google/Chrome
I deleted it and now it works!

**Comment by connor4312** [comment]
Glad you got it figured out!
