### ISSUE TITLE
Unresponsive control buttons - Debugger for Chrome v4.12.11

### ISSUE THREAD

**Issue by gkapris** [microsoft/vscode-js-debug#900]
Hello,

I have been using Chrome debbuger v 4.12.11 on an Angular 11 project. After pointing the breakpoint and started debugging it would stop executing the code. The only way to close the debugger was to close the hole application of VSCode.

I updated to Chrome debugger v 4.12.10 and it works just fine.

I am not sure if there is a conflict with one of my other extensions or a bug.

I hope I was helpful.

**Comment by connor4312** [comment]
Please include information and log file using the instructions in the issue template. Thanks!

**Comment by gkapris** [comment]
After some testing, I found out that there wasn't a problem with the debugger but with the compiler of Angular and my code.
Sorry for the inconvenience and thank you for your time.
