### ISSUE TITLE
Could not load source map from acorn.js.map on Node 15

### ISSUE THREAD

**Issue by vsDizzy** [microsoft/vscode-js-debug#903]
Debug console is polluted with warning message.

![image](https://user-images.githubusercontent.com/5798340/103988037-17224c00-5196-11eb-84b5-c8ec9db7e8d1.png)

**To Reproduce**
1. Create bare `ts-node` project with `launch.json`
or clone [this repo](https://github.com/vsDizzy/bug-vscode-js-debug)
2. install packages
3. press `F5`
4. See `DEBUG CONSOLE`

**Log File**
[vscode-debugadapter-a63519d1.json.gz](https://github.com/microsoft/vscode-js-debug/files/5785827/vscode-debugadapter-a63519d1.json.gz)

**VS Code Version:** 1.52.1

**Comment by Flam3rboy** [comment]
@connor4312 how did you solve this issue?

**Comment by connor4312** [comment]
This was a bug in js-debug with Node >=15. It's fixed in the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) and will be released to stable [next week](https://github.com/microsoft/vscode/issues/114896).

**Comment by rayfoss** [comment]
Was an issue for me with node loaders. I just had to ignore internal code
```
"resolveSourceMapLocations": [
        "${workspaceFolder}/**",
        "!**/node_modules/**",
        "!node:internal/**"
      ]
```
