### ISSUE TITLE
Allow specifying request options for reading sourcemaps

### ISSUE THREAD

**Issue by llgcode** [microsoft/vscode-js-debug#904]
**Describe the bug**
Could not debug typescript.
Because of this issue:
`Could not read source map for https://xxxxx.com:8423/xxxxx/App.js: Unexpected 503 response from https://xxxxxx:8423/xxxxx/App.js.map: unable to verify the first certificate`

It's ok if I inline source map into javascript file ( `"inlineSourceMap": true`) but I would like to have separate file for source map. 

The certificate (used for https) is not a self signed certificate it is an internal corporate certificate. In pre-production we also have authentication on javascript file so I guess it would not work if vscode try to download the mapping file by itself. The mapping file is already in the workspace.
Can't understand why the source file (javascript)  is loaded correctly (using chrome developper protocol or loaded file locally I guess) but not the associated mapping file attached to it.

**VS Code Version:** 1.51.1 and Nightly build
Thanks for your help

**Comment by connor4312** [comment]
Yea, we make the request ourselves to get the sourcemap. The devtools in Chrome use their network stack which probably has your cert trusted (or bypassed). However we can't make use of this without terrible hacks in js-debug.

I've added a new user setting that lets you specify request options, for example:

```
"debug.javascript.resourceRequestOptions": {
  "https": {
    "rejectUnauthorized": false
  }
}
```

These options are merged and passed into the [got](https://github.com/sindresorhus/got#api) options object, so you could even pass in a custom PEM-encoded CA if you wanted ([https options section](https://github.com/sindresorhus/got#advanced-https-api)).

**Comment by llgcode** [comment]
Ok,
I have tested with nightly build and it works well :-)
I guess it will be available in next release of vscode.
For pre-production environment (with authentication) I need to check on my side a more precise use case. 

Thank for your support.
