### ISSUE TITLE
(Question) Should blackboxing/skipFiles apply to stack traces in the debug console?

### ISSUE THREAD

**Issue by fabiankaestner** [microsoft/vscode-js-debug#906]
Should the skipFiles property in the launch.json file also hide the files from debug console stacktraces?
I am using the sentry library which replaces the console.log function, thus changing the stack traces to always originate from the sentry library file. In the chrome console, this can be solved by blackboxing the library file. I have added the file to the skipFiles property in my launch.json:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceFolder}/src",
            "skipFiles": [
                "**/instrument.ts"
            ]
        }
    ]
}
```

I have tried running console.trace() and setting a breakpoint inside an ignored javascript file. The breakpoint triggered outside the javascript file, but the console showed the origin of console.trace() to be the file that should be ignored.

Is this intended behaviour? If so, is there the possibility of including this feature?

**Comment by connor4312** [comment]
I'll take a look at what they're doing. To confirm you're taking about [this sdk](https://docs.sentry.io/platforms/javascript/) (not their older raven library)?

**Comment by fabiankaestner** [comment]
Hi, thanks for your quick response.
Yes, this is the SDK I'm using (v5.15.5). Disabling the library's breadcrumb collection from console fixes this issue, so I am pretty sure they just replace the global console.log function and call it on their own afterwards, leading to the "false" stacktrace.

Initializing avoids the false stacktrace, but of course prevents Sentry from collecting the debug information:
```javascript
Sentry.init({
    dsn: process.env.REACT_APP_SENTRY_DSN,
    integrations: [
        new Sentry.Integrations.Breadcrumbs({
            console: false,
        }),
    ],
});
```

**Comment by connor4312** [comment]
Hi, apologies for the delay.

This does work, but we don't resolve sourcemaps in node_modules by default, and Sentry doesn't ship with original sources anyway, which would prevent us from resolving anyway. So you just want to change from `**/instrument.ts` to `**/instrument.js`.
