### ISSUE TITLE
run "extension and auto launch" failed

### ISSUE THREAD

**Issue by yFeii** [microsoft/vscode-js-debug#907]
**Describe the bug**

**To Reproduce**
1. download project
2. npm install
3. npm run compile
4. run : extension and auto launch

**Log File**

**VS Code Version:** 1.52.1

**Additional context**

after run command，vscode open extension host window, then log error：

Activating extension 'vscode.debug-auto-launch' failed: Cannot find module '/Users/didi/opensource/vscode/vscode/extensions/debug-auto-launch/out/extension'
Require stack:
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js.

**Comment by connor4312** [comment]
`extension and auto launch` is for debugging the [`debug-auto-launch` built-in](https://github.com/microsoft/vscode/tree/master/extensions/debug-auto-launch) extension that provides auto attach capabilities. It requires the `vscode` repo be cloned beside js-debug.
