### ISSUE TITLE
Breakpoints are incorrect/unbound when attempting to debug pre-compiled typescript files using mocha.

### ISSUE THREAD

**Issue by mschnee** [microsoft/vscode-js-debug#909]
**Describe the bug**
Given
- We have pre-compiled all of our source and test files, written in typescript

And:
- We want to debug using a specific test file

Expected Behavior:
- Breakpoints set in the source files and unit test files are respected.

Actual Behavior:
- The breakpoints are unbound, and source maps do not appear to be used.

**To Reproduce**
1. `git clone https://github.com/mschnee/debug-breakpoint-example`
2. `npm install`
3. Open the folder in Visual Studio Code
4. Set breakpoints in `src/index.unit.ts`
5. Focus the unit test file and launch the "Debug Current Test File" target. 
  5.1. __Note that the debugger stops on the `debugger;` statement in the compiled file, not on any breakpoints in the source file__
6. Launch the "Debug Specific Test File" target, 
  6.1  __Note that the debugger stops on the `debugger;` statement in the compiled file, not on any breakpoints in the source file__

**VS Code Version:** 
```
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:32:10.090Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-62-generic snap
```

**vscode-js-debug version**
Nightly

**Log File**
[vscode-debugadapter-1398388e.json.gz](https://github.com/microsoft/vscode-js-debug/files/5825338/vscode-debugadapter-1398388e.json.gz)

# The Problem

Given the two launch configurations
```json
{
  "type": "node",
  "request": "launch",
  "name": "Debug Current Test File",
  "program": "${workspaceFolder}/bin/mocha-current-file",
  "args": [
    "${file}"
  ],
  "outFiles": [
    "${workspaceFolder}/dist"
  ],
  "sourceMaps": true,
},
{
  "type": "node",
  "request": "launch",
  "name": "Debug Specific Test File",
  "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
  "args": [
    "${workspaceFolder}/dist/index.unit.js"
  ],
  "outFiles": [
    "${workspaceFolder}/dist"
  ],
  "runtimeArgs": ["--nolazy","--trace-deprecation","--trace-warnings"],
  "trace": true,
  "sourceMaps": true,
  "console": "integratedTerminal",
  "internalConsoleOptions": "neverOpen",
}
```

## Examples
Given these breakpoints:
![setup](https://user-images.githubusercontent.com/1375316/104827780-8216f700-5816-11eb-9901-852a91d5dafc.png)

## When not using the preview.
```jsonc
// settings.json
{
    "debug.javascript.usePreview": false,    
}
```
![preview-false](https://user-images.githubusercontent.com/1375316/104827789-8d6a2280-5816-11eb-9fd6-16e268e0ca8b.png)

Note how we are currently stopped on the breakpoint in the source file.

## When using the preview
```jsonc
// settings.json
{}
```
![with-preview](https://user-images.githubusercontent.com/1375316/104827793-96f38a80-5816-11eb-8167-2058434d79de.png)

Note how we are currently stopped on the `debugger;` line in the __compiled distfile__ [./dist/index.unit.js](./dist/index.unit.js)

## Optional:
The file [./bin/mocha-current-file.js](./bin/mocha-current-file) does the following:
  - consumes the `${file}` argument, which is the currently focused file in the vscode editor.  In this example, it is `src/index.unit.ts`
  - determines the name and location of the compiled typescript file, in this case, `dist/index.unit.js`
  - Shows an (unfollowed) example of a setup where there might be complicated "before all test" setup, e.g. for cleanly creating and tearing down databases.
  - invokes mocha through `require('mocha/lib/cli').main(['dist/index.unit.js])`

# Additional Notes
You can substitute your favorite test framework, this also happens with Jest and AVA, however the affect is the same on both.

Also, having a `${compiledFile}` expansion instead of just `${file}` and then having to determine where the actual compiled file is, in this case, would be a fantastic feature in Code.

**Comment by connor4312** [comment]
Thanks for the issue. In your config, you have outFiles set to

```
"outFiles": [
  "${workspaceFolder}/dist"
],
```

However, this is a [glob pattern](https://globster.xyz/), which would only match a file named "dist".

You can fix this by changing your outFiles to

```
"outFiles": [
  "${workspaceFolder}/dist/**/*.js"
],
```

or by just omitting it (which we recommend nowadays since we have fast automatic discovery)
