### ISSUE TITLE
Breaks client-side recaptcha v2 challenge from CRA app

### ISSUE THREAD

**Issue by SomervilleTom** [microsoft/vscode-js-debug#912]
**Describe the bug**
While open on an app created by `create-react-app`, a `recaptcha v2` "I am not a robot" challenge cannot be verified. The same app works fine when run in "Debugger for Firefox" and works fine on a Chrome browser opening the same app after that app is launched from the command line.

**To Reproduce**
1. Open VSC on remote system using `Remote -- SSH` extension with tunnel on port 3000 back to host.
2. Use `create-react-app` to create example app using the `react-google-recaptcha` package. Set callbacks for `onChange`, `onExpired`, and `onErrored` in JSX for component. The attached `index.zip` file contains the `index.js` that I used for this example.
3. Add configuration to `launch.json` as per guidance in the README.MD. 
4. Start app using builtin-terminal: `npm start`. Wait for popups to clear and close any browser instances that are opened.
5. Invoke the "Launch Chrome against localhost" item from the `Run` window.
6. Attempt to verify the resulting challenge. Nearly all attempts will fail (I've seen one or two successes in dozens of failures). No callbacks are invoked. Nothing is reported at the console.

**Log File**
[vscode-debugadapter-1f7ba258.json.gz](https://github.com/microsoft/vscode-js-debug/files/5851724/vscode-debugadapter-1f7ba258.json.gz)

⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**VS Code Version:** Version 1.52.1 (system setup)

**Additional context**
I see the same behavior when using `react-recaptcha` and `reaptch`. I'm using recaptcha credentials that work fine a jQuery form running under Apache on the same VM.

When I run the same app from the command line (`npm shell`) and open a regular Chrome browser on the designated port (`https://my.domain.name:3000`), the challenge works fine and reports the resulting token on the console as expected. This is necessary to continue the next step of the recaptcha flow (sending the token to the google API with my secret token).

The target system is an Amazon EC2 instance running CentOS 7. My local dev system is a Windows 10 Pro system.

**Example index.js (see step 2 above):** [index.zip](https://github.com/microsoft/vscode-js-debug/files/5851774/index.zip)

**Comment by SomervilleTom** [comment]
FYI, I found typos in the callbacks (`$(aValue)` rather than the correct `${aValue}`). These don't affect the bug, but need to be in place for the app to properly report the various callback values on the console.

**Comment by connor4312** [comment]
I'm not able to reproduce this using the sample or the [demo site](https://www.google.com/recaptcha/api2/demo). In a quick scan of the captcha code I don't see anything that would obviously be looking out for a debugger (e.g. no references to `navigator.webdriver`). You may have more luck reaching out to the Google support team, I don't think there's anything I can do here.
