### ISSUE TITLE
Node version detection failing with anyenv

### ISSUE THREAD

**Issue by KenshiroNiioka** [microsoft/vscode-js-debug#914]
**Describe the bug**

I tried to debug a project, but it did not work well.

**To Reproduce**

1. I created launch.json by referring to the [following URL](https://code.visualstudio.com/docs/editor/debugging#_launch-configurations) and selected `Node.js(preview)`.
2. I only modified the program part.
3. I tried to start from Run view.
4. it did not work.

**Log File**

[vscode-debugadapter-23c1959a.json.gz](https://github.com/microsoft/vscode-js-debug/files/5865321/vscode-debugadapter-23c1959a.json.gz)

**VS Code Version:**

```
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

**Additional context**

_Originally posted by @KenshiroNiioka in https://github.com/microsoft/vscode-js-debug/issues/543#issuecomment-762169069_

@connor4312 
Sorry it took so long.
I tried output Log with `"trace": true`.
Please check the content.

**Comment by connor4312** [comment]
Thanks. It looks like this must be some quirk in anyenv. We execute `"/Users/niioka-kenshiro/.anyenv/envs/nodenv/shims/node --version` which outputs "v15.3.0", and then actually running the program is using an older Node version. That, or anyenv is mangling the environment variables.

**Comment by KenshiroNiioka** [comment]
Thanks for confirming.
Does this mean that it is difficult to debug in my environment at the moment?
If there is a workaround, could you please let me know?

**Comment by connor4312** [comment]
You can set `"nodeVersionHint": 10` in your launch.json, or update your node.js version to >= 12

**Comment by KenshiroNiioka** [comment]
Thanks.
I specified the parameters you gave me and debug is worked.
I think it will contribute greatly to the research.
Thank you for a long time.
Once I have achieved my goal, it is time to move on.

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "pwa-node",
            "request": "launch",
            "name": "Launch Program",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}/myProjectDir/index.js",
            "nodeVersionHint": 10
        }
    ]
}
```

**Comment by connor4312** [comment]
This works for me, but you will need to make sure that the `anyenv init` is placed such that its environment variables are applied to VS Code.
