### ISSUE TITLE
Cisco AMP for Endpoints Connector flags "Debugger for Chrome" as a virus

### ISSUE THREAD

**Issue by TheAifam5** [microsoft/vscode-js-debug#915]
Hi,

while I was working, I noticed a popup with the AV notifying me that something has been found, checked the path and as in the screenshot, shows that the file corresponds to the "Debugger for Chrome" extension. Checked the release looks like that a new version of "Debugger for Chrome" has been released (v4.12.12).

Somehow Cisco's AMP for Endpoints Connector flags it as a virus and deletes it.
![image](https://user-images.githubusercontent.com/2192274/105910019-9cc44980-6028-11eb-853c-6ba2a17afb3e.png)

To verify if that's maybe other anomaly, I've deleted the extension and installed it again and AMP deleted it again.

OS: macOS 10.15.7

PS. I'm not allowed to mess around with AV, like adding an exception for the file because I do not own the hardware. 

Best regards,
TheAifam5

**Comment by connor4312** [comment]
You can uninstall the `Debugger for Chrome` extension if you update your launch.json types to be `pwa-chrome` instead of `chrome`.

This should be the second-to-last update for the Debugger for Chrome extension -- the remaining change will be to deactivate the Debugger for Chrome entirely.

**Comment by TheAifam5** [comment]
Thank you, didn't know that. I will close the issue.
