### ISSUE TITLE
After switching to the vscode-js-debug preview, Google warns that "This browser or app may not be secure."

### ISSUE THREAD

**Issue by joejordan** [microsoft/vscode-js-debug#918]
**Describe the bug**
Upon clearing all browser data in my Chrome debugger instance, Google began complaining with a "Couldn't sign you in. This browser or app may not be secure" error as seen here:
https://pbs.twimg.com/media/EsqvRa8XMAE4OCv?format=png&name=small

This error appeared any time I attempted to login to ANY Google service within the launched Chrome instance.

Once I turned off the new built-in preview debugger and reverted to the long-used Chrome debugger, the Google warnings went away and was able to sign in again. My launch.json Chrome entry uses a separate profile:
`    {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome against localhost",
      "url": "http://localhost:3333",
      "webRoot": "${workspaceFolder}",
      "userDataDir": "${workspaceFolder}/out/chrome",
      "skipFiles": [
        "${workspaceFolder}/node_modules/**/*.js",
        "<node_internals>/**/*.js"
      ],
    },
`

**To Reproduce**
0. Ensure built-in debugger preview is disabled
1. Set up a separate Chrome profile using the old Chrome debugger VS Code plugin
2. Ensure you are signed in to Google
3. Enable the debugger preview in VS Code
4. Launch debugger with preview debugger plugin 
5. Clear all browser data and ensure Chrome has no ties to Google account
6. Close and re-launch debugger
7. Attempt to sign into a Google service
8. Google warns that they "Couldn't sign you in" because "This browser or app may not be secure."

**VS Code Version:** 1.51.1

**Comment by connor4312** [comment]
That is bizarre.

Can you confirm the version of Chrome you're using is up to date? A cursory search indicates that this can sometimes be caused by old Chrome versions, though I don't know why it would differ between debuggers.

**Comment by joejordan** [comment]
@connor4312 I spent the majority of last week trying to figure out what the heck was going on with this, a real nightmare. 

I thought it might be related to a Chrome update so I tried multiple versions going back to version 80 with no success. Fresh Chrome re-installs, including wiping user data and settings, again with no success. Even tried replicating my dev environment on another system, thinking my main PC was just cursed by Google. Nope, I was able to replicate the issue on my secondary system.

It was only after I started looking at the debuggers themselves that I noticed that VS Code seems to have recently enabled the built-in debugger preview by default, and the corresponding Chrome debugger plugin I was using was now checking to see if the debugger was enabled, and if so would pass the debugging buck to the internal debugger instead.

**Comment by connor4312** [comment]
After some experimentation, it seems this is caused by using `--remote-debugging-pipe` in the new debugger. Ironically this is more secure than the previous `--remote-debugging-port`, but causes the 'security' check on chrome.

You can have the debugger use the old port style by adding `"port": 12345` (any open port) to your launch config. Let me know if that works for you.

**Comment by joejordan** [comment]
You found it. Was able to toggle between Google saying the browser is insecure and being able to login without issue by simply adding the port option.

Where in the Google chain do you think this should be reported? I haven't seen many people hit this issue yet but at least it's  replicable.

**Comment by connor4312** [comment]
Okay, thanks for confirming! I opened an issue on Chromium and will see what they have to say: https://bugs.chromium.org/p/chromium/issues/detail?id=1173641

I'm going to close issue, because:

- the only action we could take here is using port debugging by default, which I don't want to do for security reasons
- there's an easy workaround by using port debugging. I'll add this to our COMMON_PROBLEMS.md for others to reference.

**Comment by alaconda** [comment]
Hello, 

Running into the same issue in one of my older web apps in vscode, but can't seem to figure out what to do.  

I have tried

- Setting `--remote-debugging-port` under "runtimeArgs".  Same warning "This browser or app may not be secure.".
- Add `"port": 3000"`.  This will launch to page "about:blank" and it will crash a few seconds later.

Wondering if anyone can share their launch.json to work around this issue.

Thanks in advanced!

**Comment by javabr** [comment]
Hello!
has anybody figured out how to workaround this problem?

**Comment by denik1981** [comment]
The solution proposed about changing the port works well for me but I'm not sure how to assign a different port in the action triggered by **serverReadyAction**.

I have 3 debugger configurations, Client, Server, and Full-Stack for a NextJS app. The Client config can benefit from receiving a **port** key to bypass this issue but I cannot do the same in the FullStack configuration.
```json
  {
      "name": "Next.js: debug full stack",
      "type": "node-terminal",
      "request": "launch",
      "command": "npm run dev",
      "console": "integratedTerminal",
      "serverReadyAction": {
        "pattern": "started server on .+, url: (https?://.+)",
        "uriFormat": "%s",
        "action": "debugWithChrome"
      }
  }
  
  ```
  
  How can I assign the port in the above setting?

**Comment by connor4312** [comment]
Documentation: https://code.visualstudio.com/docs/editor/debugging#_automatically-open-a-uri-when-debugging-a-server-program

**Comment by denik1981** [comment]
@connor4312 Yes, I read the docs and they don't show a way to address my question, that's why I'm asking.

`serverReadyAction` is a predefined tiny set of actions that don't give the developer the freedom of choosing which port to use when the browser launches.

**Comment by denik1981** [comment]
Thanks, @connor4312! It works but I would say is not very intuitive. Vscode Intellisense always helped me set the configuration I need but not in this case.  At first, the `startDebugging` action doesn't show up among all if you don't provide a `name` key that references the debug configuration you wish to launch.

**Comment by thiras** [comment]
@denik1981 could you please share your working configuration?

**Comment by Rinconx64** [comment]
``` json
{
      "name": "Next.js: debug full stack",
      "type": "node-terminal",
      "request": "launch",
      "command": "npm run dev",
      "serverReadyAction": {
          "pattern": "started server on .+, url: (https?://.+)",
          "uriFormat": "%s",
          "action": "openExternally" <--- Apply this 👌
      }
}
```

**Comment by dev-vinicius-andrade** [comment]
The

> ```json
> {
>       "name": "Next.js: debug full stack",
>       "type": "node-terminal",
>       "request": "launch",
>       "command": "npm run dev",
>       "serverReadyAction": {
>           "pattern": "started server on .+, url: (https?://.+)",
>           "uriFormat": "%s",
>           "action": "openExternally" <--- Apply this 👌
>       }
> }
> ```
The problem with this aproach is that we can't bind breakpoits, is there any other alternatives?

**Comment by jghaines** [comment]
It seems that this error can be suppressed by providing a `port` in launch.json.  From the original example

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:3333",
            "webRoot": "${workspaceFolder}",
            "userDataDir": "${workspaceFolder}/out/chrome",
            "skipFiles": [
                "${workspaceFolder}/node_modules/**/*.js",
                "<node_internals>/**/*.js"
            ],
            "port": 9876
        }
    ]
}```
