### ISSUE TITLE
Debug session caught exception toggle gets stuck

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode-js-debug#919]
Issue Type: <b>Bug</b>

1. Start debugging VS Code
2. Set it to break on caught exceptions
3. Trigger something that causes a caught exception
4. Uncheck the box
5. Trigger something that causes a caught exception again
6. 🐛 It stops at the caught exception even though the box isn't checked.

VS Code version: Code - Insiders 1.53.0-insider (e1c818a171168eedf78b62fdc7f4e3458d5dea7c, 2021-02-03T08:22:02.267Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (5.55GB free)|
|Process Argv|--crash-reporter-id 7170f6db-7270-442f-945e-4508c02991d4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.14
EditorConfig|Edi|0.16.4
codespaces|Git|0.6.1
vscode-pull-request-github|Git|0.22.0
remote-containers|ms-|0.158.0
remote-ssh|ms-|0.63.0
remote-ssh-edit|ms-|0.63.0
vscode-remote-extensionpack|ms-|0.20.0
js-debug-nightly|ms-|2021.2.117
vscode-github-issue-notebooks|ms-|0.0.60
vscode-markdown-notebook|ms-|0.0.13
debugger-for-chrome|msj|4.12.12

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30208930
wsl2prompt:30219162
vstry244:30244315
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorer:30219166
openfilemenucf:30219169
pythonvsded773:30223139
pythonvspyt600cf:30251589
core-portspanel:30233467
coreuntitledfile:30249963

```

</details>

**Comment by connor4312** [comment]
Having some trouble hitting this. If you can reproduce easily, can `"trace": true` to the `Launch VS Code Internal` config and share the resulting log file?

/jsDebugLogs

**Comment by lramos15** [comment]
[vscode-debugadapter-c18a7a94.json.gz](https://github.com/microsoft/vscode-js-debug/files/5945392/vscode-debugadapter-c18a7a94.json.gz)

The exact repro I use is
1. Launch OSS through the debugger
2. Make an untitled file and type in it 
3. Tick break on caught exceptions
4. Trigger `Reopen Editor With`, this will cause it to break on a couple of exceptions
5. Untick the break on exception box
6. Redo step 4
7. 🐛 It breaks on the exceptions again
