### ISSUE TITLE
Debugger can be slow on jest tests, is the default outFiles filter working?

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode-js-debug#920]
**Describe the bug**
Im trying to debug Jest tests, and I've noticed that the debugger is really slow and takes a long time to start up. The first thing i did was try `profileStartup": true` so i could see where time is being spent.

It looks like `waitForDebugger` is the issue, sometimes it spends 40 seconds there.

![image](https://user-images.githubusercontent.com/936006/107068863-0be42f80-67d9-11eb-9f26-c0c9d915cc07.png)

The next thing i tried was running the diagnostics to see what was being loaded. There were over 1669 sources loaded.
I didn't have `outFiles` set as i belive that already defaults to ignoring `node_modules`. But i set it manually and still had the same result. 

Below is what i get both with and without outFiles set.

![image](https://user-images.githubusercontent.com/936006/107069133-67aeb880-67d9-11eb-8a35-849ba8879589.png)

Config:
```json
    {
      "name": "Jest",
      "type": "pwa-node",
      "request": "launch",
      "cwd": "${workspaceFolder}/ui/web",
      "runtimeArgs": [
        "../node_modules/.bin/jest",
        "--runInBand"
      ],
      "outFiles": [
        "${workspaceFolder}/ui/web/**/*.js",
        "!**/node_modules/**"
      ]
    }
```

Im assuming the reason is the node_modules traversal, but it seems to do this regardless of what i set.

Edit: Since writing this ive managed to scope down outfiles further and its working faster, but it still picks up loads of node_modules.

VSCode 1.53.0

**Comment by connor4312** [comment]
Having scripts loaded inside node_modules is not concerning, and isn't directly affected by outFiles. outFiles configures where we'll scan for (and resolve) sourcemaps, but even if sourcemap handling is turned off we still receive information from the runtime and track scripts in the node_modules.

A log and/or [extension host profile](https://www.nicoespeon.com/en/2019/11/fix-vscode-extension-performance-issue/) would be useful here 🙂

**Comment by connor4312** [comment]
Let me know if you're still running into this/have more info for it

**Comment by jasonwilliams** [comment]
Yeah i think this is resolved for now thanks

**Comment by alexya** [comment]
@jasonwilliams could you please share with us how you resolve this issue? I met a similar issue.

**Comment by jasonwilliams** [comment]
Hey @alexya i don’t remember the specifics, but it may have been fixed in an update. It may also be worth using a fast builder (esbuild) for jest if you’re using something like typescript. You should be able to run profiles and see where time is being spent
