### ISSUE TITLE
vscode vue debugging with chrome doesn't work in default debugger (Use Preview)

### ISSUE THREAD

**Issue by intrex1311** [microsoft/vscode-js-debug#922]
I have been at this for days now of internet searching and decided to post what I have in hopes of finding someone who can figure out what is going on here. I have tried and examined the output of every possible iteration of sourcemappathoverrides. This seems to be the main issues with the debugging recipes from vue. Those have to be modified for your code structure. I have also tried changing the configs in babel, webpack, babel-loader and all of the internal vscode files. Right now I have it so that I can reliable jump into breakpoints if I turn off the use preview javascript debugger in vscode. While this works it takes minutes (I am not exaggerating) to hit a breakpoint in vscode. While this is going on vscode is completely unresponsive. when the default debugger (use preview) is enabled the breakpoints that get hit in the code are instantly hit but not where I placed them originally. Once the code starts you are unable to put breakpoints in many locations. I know that this indicates a sourcemap issue but the same sourcemaps work perfectly when reverting to the old javascript debugger. This is my current configuration.

![image](https://user-images.githubusercontent.com/78804725/107376361-cca72e80-6ab7-11eb-8f69-d089675490ba.png)

This is my webpack config (I just recently added the babel-loader section which doesn't make any difference)

```
// webpack.config.js

module.exports = {
  // ...
  entry: {
    "app": "src/main.js"
  },
  //mode: 'development',
  rules: [
    {
      test: /\.m?js$/,
      exclude: /(node_modules|bower_components)/,
      use: {
        loader: 'babel-loader',
        options: {
          presets: [
            '@vue/app'
          ]
        }
      }
    }
  ]
};
```
This my vue.config (I have tried changing publicpath, compress, chaingwebpackoptions with no luck)

```
const CopyPlugin = require('copy-webpack-plugin')

module.exports = {

  pages: {
    index: {
      entry: 'src/index.js',
      template: 'public/index.html',
      filename: 'index.html'
    }
  },
  devServer: {
    clientLogLevel: 'warning',
    hot: true,
    contentBase: 'dist',
    compress: false,
    open: true,
    overlay: { warnings: false, errors: true },
    publicPath: '/',
    quiet: true,
    watchOptions: {
      poll: false,
      //I want to be able to jump into node_modules to debug
      ignored: /node_modules/
    }
  },
  chainWebpack: config => {
    config.plugins.delete('prefetch-index'),
    config.module
      .rule('vue')
        .use('vue-loader')
          .tap(args => {
            args.compilerOptions.whitespace = 'preserve'
          })
  },
  productionSourceMap: false,
  assetsDir: './assets/',
  configureWebpack: {
    devtool: 'source-map',
    plugins: [
      new CopyPlugin({
        patterns: [
          { from: 'src/assets/img', to: 'assets/img' },
          { from: 'src/assets/logos', to: 'assets/logos' },
          { from: 'src/assets/fonts', to: 'assets/fonts' }
        ],
      }),
    ]
  }
}
```
this is my jsonconfig (just recently commented out the webpack.config. It doesn't matter either way)

```
{
    /*"include": [
      "webpack.config.js"    
    ],*/
    "compilerOptions": {
      "sourceMap": true
    }
  }
```
my babel config (originally I had no "env" section. Adding this made no difference)

```
module.exports = {
  "env":{
    "development":{
      "sourceMaps":true,
      "retainLines":true,
    }
  },
  presets: [
    '@vue/app'
  ]
}
```
this is my launch config (this is where I spent the most time. I tired every combination under the sun of sourcemappathoverrides and webroot with or without /src). The sourcemap binding in the logs appear to be correct but breakpoints jump around from where they are dropped or aren't able to be set at all.

```
{
    "version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "request": "launch",
      "trace":"verbose",
      //also right click on your chrome icon and add this to the target field (--remote-debugging-port=9222)
      "port": 9222,
      "name": "vuejs: chrome",
      "url": "http://localhost:8080",
      "webRoot": "${workspaceFolder}",
            "breakOnLoad": true,
            "sourceMapPathOverrides": {
              "webpack:/*": "${webRoot}/*",
              "/src/*": "${webRoot}/*",
              "/./~/*": "${webRoot}/node_modules/*"
            },
      "preLaunchTask": "vuejs: start"
    }
  ]
  }
```
and finally my task to launch chrome after the app starts running

```
{
    "version": "2.0.0",
    "tasks": [
      {
        "label": "vuejs: start",
        "type": "npm",
        "script": "serve",
        "isBackground": true,
        "presentation": {
          "reveal": "always",
          "panel": "shared",
        },
        "problemMatcher": {
          "owner": "typescript",
          "fileLocation": "relative",
          "pattern": {
            "regexp": "^([^\\s].*)\\((\\d+|\\,\\d+|\\d+,\\d+,\\d+,\\d+)\\):\\s+(error|warning|info)\\s+(TS\\d+)\\s*:\\s*(.*)$",
            "file": 1,
            "location": 2,
            "severity": 3,
            "code": 4,
            "message": 5
          },
          "background": {
            "activeOnStart": true,
            "beginsPattern": ".",
            "endsPattern": "App running at",
          }
      }

      }
      
    ]
}
```

**Comment by connor4312** [comment]
Thanks for the issue. It's currently not possible for us to set breakpoints in Vue apps correctly for TypeScript components; follow https://github.com/vuejs/vue/issues/11023 for updates.

**Comment by intrex1311** [comment]
I was under the impression all of the components in here are javascript.  I don't have any .ts files in the project.  running  tsc -v in the terminal results in "The term 'tsc' is not recognized as the name of a cmdlet".  There are also no typescript dev dependencies in my dependencies in my package.json.  Are you seeing something in my configs that indicates typescript that I am missing? 

` "dependencies": {
    "@glidejs/glide": "^3.4.1",
    "axios": "^0.21.1",
    "bootstrap-vue": "^2.21.2",
    "chart.js": "2.9.4",
    "core-js": "^3.8.2",
    "firebase": "^8.2.3",
    "v-contextmenu": "^2.9.0",
    "video.js": "^7.10.2",
    "vue": "^2.6.12",
    "vue-autosuggest": "^2.2.0",
    "vue-headroom": "0.10.1",
    "vue-i18n": "^8.22.4",
    "vue-light-gallery": "^1.0.1",
    "vue-line-clamp": "^1.3.2",
    "vue-perfect-scrollbar": "^0.2.1",
    "vue-quill-editor": "^3.0.6",
    "vue-radial-progress": "^0.3.2",
    "vue-router": "^3.4.9",
    "vue-runtime-helpers": "^1.1.2",
    "vue-scrollto": "^2.20.0",
    "vue-select": "^3.11.2",
    "vue-shortkey": "^3.1.7",
    "vue-simple-calendar": "^5.0.0",
    "vue-slider-component": "^3.2.11",
    "vue-switches": "^2.0.1",
    "vue-yandex-maps": "^0.10.9",
    "vue2-dropzone": "^3.6.0",
    "vue2-google-maps": "^0.10.7",
    "vuedraggable": "^2.24.3",
    "vuejs-datepicker": "^1.6.2",
    "vuelidate": "^0.7.6",
    "vuetable-2": "^1.7.5",
    "vuex": "^3.6.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^4.5.10",
    "@vue/cli-plugin-router": "^4.5.10",
    "@vue/cli-plugin-vuex": "^4.5.10",
    "@vue/cli-service": "^4.5.10",
    "copy-webpack-plugin": "^6.0.3",
    "node-sass": "^4.14.1",
    "sass-loader": "^9.0.2",
    "vue-loader": "^15.9.3",
    "vue-template-compiler": "^2.6.12"
  },`

**Comment by connor4312** [comment]
Ah, I saw the tsmatcher in your task so assumed there was TS in your build. Two things:

1. Try removing the `sourceMapPathOverrides` from your config. This is _usually_ not necessary to specify and the defaults are pretty good.
2. If that doesn't work, please share a log file using the instructions in the issue template so I can see precisely what's happening.

**Comment by intrex1311** [comment]
Thanks Connor, 

I just removed the sourceMapPathOverrides element completely from launch.json but left everything else is the same.  It has the same behavior as when I had the element in there. 

I opened the app with the run debug arrow and then navigated to a page at /src/views/admin/services/index.vue .   The breakpoint I set in vscode was on line 136 but it stops at line 36 in that file.  The line it stops on isn't even part of the script tag it is in the template section.  This is the same behavior as with the sourcemapoverrides but with one small difference.  Now when I put a break point on a line in this file while the project is running it accepts it and stays red.  When I had the overrides vscode wouldn't even accept the breakpoint and it would show a white circle saying unverified breakpoint.  

[vscode-debugadapter-1dd86728.json.gz](https://github.com/microsoft/vscode-js-debug/files/5953204/vscode-debugadapter-1dd86728.json.gz)

**Comment by intrex1311** [comment]
Hey Conner, 

As I have been trying to work on this project today I should have also added that it takes minutes (somtimes 5 minutes) to get into the breakpoint in vscode when a page is displayed in chrome that has the breakpoint on it.  It is close to unusable in my project at least.  

It isn't hardware or resource related either.  I am on a beastly development machine.  Its pretty close to the fastest hardware you can purchase on a laptop as of 6 months ago.

**Comment by intrex1311** [comment]
That is happening when I am using the non use preview debugger obviously.   The breakpoints in the user preview debugger break into vscode instantly but they are just in the wrong place in the code as per my other posts.

**Comment by connor4312** [comment]
Thanks for the logs. Although you aren't using TypeScript, something in your setup is creating sourcemaps in the same way that TypeScript does that make us unable to accurately debug them. I don't know enough about Vue's internals to be able to pinpoint what this is.

Please follow/upvote https://github.com/vuejs/vue/issues/11023.
