### ISSUE TITLE
How to consume Debug Adapter / debugServerMain.ts outside of VSCode?

### ISSUE THREAD

**Issue by mickaelistria** [microsoft/vscode-js-debug#926]
I'm willing to replace the usage of node-debug & node-debug2 modules in Eclipse Wild Web Developer by the newer js-debug module.
However, I didn't find out how to actually start the debug adapter. For node-debug, I could "extract" the module from VSCode, import it in Wild Web Developer and then run `node node-debug2/out/src/nodeDebug.js` to start the debug adapter and talk DAP with it; but with js-debug, I don't know what would be a similar entry point. I tried `node ms-vscode.js-debug/src/extension.js` but this requires VSCode running apparently. I found the very interesting `debugServerMain.ts` class but don't find it in the final distribution in VSCode.
Is there another command I should try? Or is the debugServerMain just removed in the distribution (so I should build vscode-js-debug myself) ?

**Comment by connor4312** [comment]
This thread should provide you some pointers: https://github.com/microsoft/vscode-js-debug/issues/902

Also related (to making it easier to consume) https://github.com/microsoft/vscode/issues/116730

**Comment by mickaelistria** [comment]
Thanks.
So do I get it right that currently, the vscode-js-debug adapter needs to be built locally in order to be used out of VSCode? There is no "ready-to-go" distribution? (cc @pretentious7)

**Comment by connor4312** [comment]
That's right. What would your ideal 'ready to go' distribution look like? An npm package?

**Comment by mickaelistria** [comment]
Yes, a npm package would be great.

**Comment by pretentious7** [comment]
> That's right. What would your ideal 'ready to go' distribution look like? An npm package?

Yes please, this would be ideal, linking to within .vscode after a bunch of confusing steps is not great.

**Comment by mickaelistria** [comment]
About going to npm.js, although it would be awesome, it IMO has to be done properly (defining upstream and downstream dependency relationships, with LS being as downstream as possible). If not done properly, the module may face same issue as https://github.com/microsoft/vscode/issues/117013 and can become too easily out-of-date and less useful than expected.

**Comment by connor4312** [comment]
js-debug is pretty standalone and ships (in an extension) as a set of standalone webpacked js files

**Comment by mickaelistria** [comment]
Any news here? Is there a standalone npm package for the debug adapter? If not, any ETA? Thanks in advance!

**Comment by vominhtien300991** [comment]
Your Google verification code is 594816

**Comment by MAST1999** [comment]
Hey, I was looking for a way to use `vscode-js-debug` in other places as well and I ended up here.

Are there any updates?

**Comment by zulus** [comment]
I found interesting task in gulp: dapDebugServer

Is this possible to release package for example @vscode/js-debug-dap-server, same for flatSessionBundle and/or vsDebugServerBundle ?

**Comment by connor4312** [comment]
Forgot to duplicate this into https://github.com/microsoft/vscode-js-debug/issues/1388

We now publish a compliant pure-DAP server that works for clients that support the `startDebugging` request. This is in the assets in each release on Github as `js-debug-dap-<version>.tar.gz` https://github.com/microsoft/vscode-js-debug/releases

**Comment by mickaelistria** [comment]
Thank you very much for pointing to this assert @connor4312 , it's exactly what was needed and I'm happy to report we're already successfully adopting it for Eclipse Wild Web Developer as a replacement to node-debug2!
