### ISSUE TITLE
how to pretty eval code?

### ISSUE THREAD

**Issue by gbkhero** [microsoft/vscode-js-debug#929]
hello everyone! when i debug js code, i found vscode can pretty file code, but when eval code, the pretty debug command not effect, can someone help me?

**Comment by connor4312** [comment]
I'm not sure what you're asking, can you clarify?

**Comment by gbkhero** [comment]
thanks! connor4312, i'm sorry! my english is poor! when debugging eval code, in "Command Palette", the "Debug: Pretty print for debugging" command not pretty anyting?

**Comment by connor4312** [comment]
I see. I'm not sure if this works in eval, I'll look at it.

**Comment by gbkhero** [comment]
ok, thank you very much!

**Comment by connor4312** [comment]
This will be fixed in the next [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension)

**Comment by gbkhero** [comment]
Okay, Thank you for your effort.
