### ISSUE TITLE
auto-attach broken

### ISSUE THREAD

**Issue by ilanc** [microsoft/vscode-js-debug#931]
**Describe the bug**
The auto-attach feature is not working for me. It used to work but stopped working about 2 weeks ago. `node --inspect-brk` works - but requires you to hit F5 twice - once to attach the debugger, once to start running - which is sub-optimal :)

I'm running ubuntu 18 - haven't had an opp. to try ubuntu 20. I don't have other machines to try on.

**To Reproduce**

using auto-attach
```sh
git clone https://github.com/ilanc/debugger.git
cd debugger
code .
# set a breakpoint in ./app.js
node --inspect app.js # <= auto-attach set to always in .vscode/settings.json - but doesn't
```
using IDE
- in vscode > debugger
- pick "Launch Program"
- run
- should hit breakpoint - but doesn't

**Log File**

added 2 files:
- [vscode-debugadapter-482348c5.json.gz](https://github.com/microsoft/vscode-js-debug/files/6077327/vscode-debugadapter-482348c5.json.gz)
- [vscode-debugadapter-d2af42fe.json.gz](https://github.com/microsoft/vscode-js-debug/files/6077328/vscode-debugadapter-d2af42fe.json.gz)

**VS Code Version:**

```txt
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:44.518Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.4.0-66-generic
```

**Additional context**

**Comment by ilanc** [comment]
here's another log file - nb this one creagted from `node --inspect-brk` and is much longer.
[vscode-debugadapter-16038aa9.json.gz](https://github.com/microsoft/vscode-js-debug/files/6077381/vscode-debugadapter-16038aa9.json.gz)

**Comment by connor4312** [comment]
I'm not able to reproduce this issue. From what you're saying it sounds like Node may not be waiting for the debugger to initialize before executing. Since you're using nvm, it would be easy to try a more recent 14.x release -- can you do so?

**Comment by ilanc** [comment]
Howdy, I tried with lts i.e. node 14.16.0 and same issue

**Comment by ilanc** [comment]
Ah man - I tried to record a screencast and now its working. FFS. No idea what changed. You can close this issue.

**Comment by ilanc** [comment]
Hi @connor4312, I've got some more info on this.

nvm worked initially, then stopped working after a while for no apparent reason. I've been getting by with `--inspect-brk` for a bit, but that stopped working today.

I tried a new approach - I removed nvm and installed node directly. It's working now, but - here's the clincher - i see a suspicious looking icon in the terminal (exclamation mark in top right corner) which I fear to press. Here's the full text of the popup on that icon:

```log
Extensions want to make the following changes to the terminal's environment:

VSCODE_INSPECTOR_OPTIONS=${env:VSCODE_INSPECTOR_OPTIONS}:::{"inspectorIpc":"/tmp/node-cdp.8434-1.sock.deferred","deferredMode":true,"waitForDebugger":"","execPath":"/usr/bin/node","onlyEntrypoint":false,"autoAttachMode":"onlyWithFlag"}
Relaunch terminal
```

Here's a screenshot:
![Screenshot from 2021-03-30 11-58-49](https://user-images.githubusercontent.com/1793957/112971963-0ad3dc80-9150-11eb-8152-a056019af230.png)

I think this could be our culprit. I'm not pushing that icon until I know how to un-_fix_ it if it winds up breaking my debugger. What are the `VSCODE_INSPECTOR_OPTIONS`? and where are they saved?

**Comment by connor4312** [comment]
The VSCODE_INSPECTOR_OPTIONS are set by the debugger and are required to hook up auto attach. It should not break auto attach.

**Comment by ilanc** [comment]
What do you mean by "required to hook up auto attach"? Auto attach is working just fine, the only slight annoyance is the warning icon.

I'll try accept what the warning is saying tomorrow. If the debugger stops working after setting this, then what? Is there a way to undo the `changes to the terminal's environment`

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
