### ISSUE TITLE
Cannot debug web worker code

### ISSUE THREAD

**Issue by mike-lischke** [microsoft/vscode-js-debug#932]
**Describe the bug**
Even though I have enabled the vscode-js-debug preview in my settings in vscode I still cannot debug web worker code. Breakpoints aren't validated (stay gray) and execution doesn't hold. 

My project is a web app created with CRA and uses Typescript. I'm working with Firefox as my frontend. Normal debugging and execution works fine, which leads me to think the configuration is ok. I just cannot set a breakpoint in one of my web workers and have vscode stop there.

**To Reproduce**
Create a web app which uses Typescript (not sure if React/Babel/Webpack is relevant here) and add a web worker to it. Add a message handler in the worker, which sends back a message to the app. Then set a breakpoint in the handler. Send a message to the web worker and you should receive the reply from the worker, however vscode does not stop on the break point.

**VS Code Version:** 

Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:45:54.515Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

**Comment by connor4312** [comment]
js-debug doesn't debug firefix, what does your launch.json look like?

**Comment by mike-lischke** [comment]
I'm not saying that js-debug should/will debug FF, but that this browser is where I render my app, in case this plays a role here. The basic statement here is: breakpoints do not work in web worker code, in vscode. My launch config is:

```json
        {
            "type": "firefox",
            "request": "launch",
            "name": "Launch MSG on FF - single user",
            "url": "https://localhost:3001?token=236d84bc-5965-11eb-b3f9-003ee1ce36e8",
            "webRoot": "${workspaceFolder}",
            "clearConsoleOnReload": true,
            "preLaunchTask": "tsc: watch",
            "keepProfileChanges": false,
            "reAttach": true,
            "profile": "dev",
            "enableCRAWorkaround": true,
            "firefoxArgs": [
                //"-devtools",
            ]
        },
```

**Comment by connor4312** [comment]
You probably want to open this issue on the [Firefox Developer Tools](https://github.com/firefox-devtools/vscode-firefox-debug) repo.

Although Firefox has been working towards CDP support that would let js-debug debug it too, currently this adapter only debugs Chromium-based browsers with the launch types `chrome`, `pwa-chrome`, and `pwa-msedge`.

**Comment by mike-lischke** [comment]
Aha, I totally missed that Firefox is not supported. Would help a lot if that fact would more prominently mentioned in the readme, even though it clearly says what is supported. But I just didn't expect that FF is not supported right now and therefore probably silently assumed it :-) Thanks for your time, anyway.
