### ISSUE TITLE
Error [ERR_INSPECTOR_ALREADY_ACTIVATED]

### ISSUE THREAD

**Issue by bonjourjoel** [microsoft/vscode-js-debug#933]
Hi,

I'm getting this error since vscode self-updated to 1.54.0. I believe it happens once for each worker because i have 7 times this error and I have 7 workers. I speak about Node.js workers.
I program in typescript and I use source maps to debug. I compile with tsc. I have Windows10 family.

Regards.

Version: 1.54.0 (user setup)
Commit: 42e27fe5cdc58539dad9867970326a297eb8cacf
Date: 2021-03-03T02:17:36.640Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Error in the js-debug bootloader, please report to https://aka.ms/js-dbg-issue: Error [ERR_INSPECTOR_ALREADY_ACTIVATED]: Inspector is already activated. Close it with inspector.close() before activating it again.
    at Object.inspectorOpen (inspector.js:137:11)
    at bootloader.bundle.cdp:7:4920
    at bootloader.bundle.cdp:7:6147
    at Object.<anonymous> (bootloader.bundle.cdp:7:6347)
    at r (bootloader.bundle.cdp:1:110)
    at bootloader.bundle.cdp:1:902
    at Object.<anonymous> (bootloader.bundle.cdp:1:912)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)

**Comment by connor4312** [comment]
Please collect some trace logs using the instructions in the issue template

**Comment by bonjourjoel** [comment]
Do you have a link to this "issue template" please?

**Comment by connor4312** [comment]
ah, apologies, I see the link in the console bypasses the template. Here are the instructions:

> If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by bonjourjoel** [comment]
Very well! One more precision: I'm not sure but one guess is: It would happen after i would use a "throw" instruction. Or maybe a coincidence.

[vscode-debugadapter-4465ff13.json.gz](https://github.com/microsoft/vscode-js-debug/files/6088217/vscode-debugadapter-4465ff13.json.gz)

**Comment by connor4312** [comment]
Thanks, found the issue. You can use tomorrow's [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) to get around this. I will also put it in the VS Code recovery release coming in a few days.
