### ISSUE TITLE
The .scripts command

### ISSUE THREAD

**Issue by mellester** [microsoft/vscode-js-debug#934]
**Is your feature request related to a problem? Please describe.**
I am having problems getting my soucemaps paths to align correctly. Because of  the complexities of my stack and how hard it is to parse the trace logs myself. (Breakpoints pointing to hot reload code instead the actual code. Even though I can set breakpoints in the debug viewer)

**Describe the feature you'd like**
They earlier debugger had a feature called `.script`  which showed the mapping in the debug console.
This seems like a useful feature.

**Comment by connor4312** [comment]
There is a new command for this, *Debug: Create Diagnostic Information for Current Session*
