### ISSUE TITLE
Client + Server debugging ->Vscode debugger is mixed up

### ISSUE THREAD

**Issue by bonjourjoel** [microsoft/vscode-js-debug#935]
Hi, it's me again :)

I am reporting a very anoying bug in vscode's debugger, which makes it difficult to debug a server/client configuration.

I run/debug a node.js server opening a server websocket. Then i run/debug a cordova client connecting to the server with a websocket of its own. When i close Chrome's window, the server process crashes with exit(1) and no other explanation, while the client process hangs forever untill I kill it.

I have searched what was happening because I'm new to these technologies and I have found out it was a bug in vscode's debugger and not in my code. I attach with this bug report a minimal reproducer project which contails all the code needed to fix. I have added a detailed step-by-step procedure to create the project and reproduce the bug, as well as a screenshot showcasing the reproducable issues.
Because I have tried to fix it myself in my code, I have found a few hints that I send you with the bug report in case you could use them to make a fix.

Best regards.

===============================================================

$> cordova create hello com.example.hello HelloWorld
$> cd hello
$> cordova platform add browser
$> npm init
# type enter, enter, enter, enter
$> code .
# Menu File > New File with the following content:
    setInterval(()=>{console.log(new Date().toLocaleTimeString() + " server is alive")}, 2000);  
# Then save this new file as "server.ts" in the worskspace directory "hello"
# Install vscode extension "Cordova Tools"
# Open the RUN AND DEBUG panel; create 2 launch configurations like this:
    {
        // Use IntelliSense to learn about possible attributes.
        // Hover to view descriptions of existing attributes.
        // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
        "version": "0.2.0",
        "configurations": [
            {
                "name": "SERVER - Launch Program",
                "type": "pwa-node",
                "request": "launch",
                "skipFiles": [
                    "<node_internals>/**"
                ],
                "program": "${workspaceFolder}//server.ts",
                "outFiles": [
                    "${workspaceFolder}/**/*.js"
                ]
            },
            {
                "name": "CLIENT - Run Browser",
                "type": "cordova",
                "request": "launch",
                "platform": "browser",
                "target": "chrome",
                "simulatePort": 8000,
                "livereload": true,
                "cwd": "${workspaceFolder}",
                "sourceMaps": true
            },
        ]
    }
# Run "SERVER - Launch Program" by clicking the green arrow
# Run "CLIENT - Run Browser" by clicking the green arrow
# When both are running, close the window of Chrome

Result of this procedure:
===> SERVER process stops with exit code 1 (and nothing else is explained)
===> CLIENT process hangs until force-closed

What I would expect instead:
===> SERVER process hangs until force-closed
===> CLIENT process stops with exit code 0

Before I found out it was a vscode bug, I searched what was wrong, so there are a few fixing hints I can give you:
- If I close the server process first, the client process doesn't hang.
- If I open a new Tab on chrome, and I close the first one opened by codova ext, the server doesn't exit(1)
- If I run the server in the console, and the client using the debug view, i get the expected result: server process stays alive, client process is ended

===============================================================

[hello.zip](https://github.com/microsoft/vscode-js-debug/files/6093622/hello.zip)
[reproduce-me.txt](https://github.com/microsoft/vscode-js-debug/files/6093623/reproduce-me.txt)
![reproduce-me](https://user-images.githubusercontent.com/78134277/110179051-b6b33200-7e07-11eb-83b6-88ae86b42950.png)

**Comment by connor4312** [comment]
Thanks for the detailed steps! Please open this issue over on the [cordova repo](https://github.com/microsoft/vscode-cordova). They should be able to help you more.
