### ISSUE TITLE
Debugger doesn't kill node process

### ISSUE THREAD

**Issue by jpike88** [microsoft/vscode-js-debug#936]
**Describe the bug**

**To Reproduce**
1. Run a node process using type:"node"
2. hit Stop
3. Node process in background does not get terminated, I have to manually find it and kill it each time.

have reverted to older debugger for now.

**VS Code Version:**
Version: 1.54.1

P.S I feel like there's definitely performance issues in general... is this preview plugin heavier on the performance/memory front?

**Comment by connor4312** [comment]
Please collect logs using the instructions in the issue template
