### ISSUE TITLE
Blazor WebAssembly debugger cannot launch an Edge version other than stable

### ISSUE THREAD

**Issue by DL444** [microsoft/vscode-js-debug#941]
**Describe the bug**

**Blazor WebAssembly debugger cannot launch an Edge version other than stable because the launch.json config for `blazorwasm` does not support `runtimeExecutable` property.**

When you try to launch the debugger, the following message is shown:

> Unable to launch browser: "Unable to find Edge version stable. Available auto-discovered versions are: ["dev"]. You can set the "runtimeExecutable" in your launch.json to one of these, or provide an absolute path to the browser executable."

Adding `runtimeExecutable` in launch.json results in VSC reporting the following error, and the problem is not mitigated.

> Property runtimeExecutable is not allowed.

**To Reproduce**

1. Create a ASP.NET Blazor WebAssembly project and open it in VSC.

2. Create the default Blazor WebAssembly run task, which can be something like this:

    ```json
    {
        "name": "Launch and Debug Standalone Blazor WebAssembly App",
        "type": "blazorwasm",
        "request": "launch",
        "cwd": "${workspaceFolder}",
        "browser": "edge"
    }
    ```

3. Start the debugger from VSC.

4. The web app starts but browser does not launch. The error message shows a while later.

**Log File**

[Download](https://redirectfuncstorage.blob.core.windows.net/items/vscode-debugadapter-808b21aa.json.gz)

**VS Code Version:** 1.54.1

**Comment by connor4312** [comment]
Please open this issue over on https://github.com/dotnet/aspnetcore-tooling
