### ISSUE TITLE
Support forwarded port attributes

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#942]
See https://github.com/microsoft/vscode/issues/115616

**Comment by alexr00** [comment]
Is everything required to test this already available in JS Debug Nightly? I'm still seeing 3 ports get forwarded:

![image](https://user-images.githubusercontent.com/38270282/112316614-8d215400-8cab-11eb-8612-4e213781774e.png)

My steps:
1. Connect to a container for microsoft/vscode-remote-try-node.
2. Install ms-vscode.js-debug-nightly in the container and disable the built-in JS Debug extension.
3. F5.

I debugged a bit, and the results I'm getting back from the portsAttributesProviders only show one port getting ignored:
![image](https://user-images.githubusercontent.com/38270282/112317410-4f70fb00-8cac-11eb-9c61-dad85aeb0795.png)
I think that those other ports are known about by JS Debug. Can they also be ignored?

**Comment by connor4312** [comment]
Thanks, fixed it!

**Comment by alexr00** [comment]
Works beautifully!
