### ISSUE TITLE
(Question) Is debugging symlinked package in chrome supported?

### ISSUE THREAD

**Issue by doehyunbaek** [microsoft/vscode-js-debug#944]
Hi.
Let's say I have a React application named A and node-module B that it uses which is symlinked.

Directory structure is like /A and /A/node_modules/B(symlinked with yarn link).

Can I break into breakpoints I made in a file of B while I'm debugging workspace opened with A debugging with Chrome/ Edge?

There seems to be some discussion of support in Node environment but I have not really found any discussion on Chrome debugging.

Thanks in advance.

**Comment by connor4312** [comment]
I'm not sure. It would depend on how your build tool generates the sourcemaps -- which path it references. Webpack at least in extremely configurable in this way. If you try this out and run into problems let me know.

**Comment by doehyunbaek** [comment]
Our react app made with CRA seems to use default webpack setting found in react-scripts. Do you suspect there is some problem with webpack not generating source map to be used for debugging?

**Comment by connor4312** [comment]
Yea, it looks like the `create-react-app` configuration dereferences symlinks. To get around this you can use the `sourceMapPathOverrides`. The `Debug: Create Diagnostic Information` can help you see the source paths and indicate what overrides you might need.
