### ISSUE TITLE
Add support for WebExtensions

### ISSUE THREAD

**Issue by lonr** [microsoft/vscode-js-debug#945]
**Is your feature request related to a problem? Please describe.**
No

**Describe the feature you'd like**
Add support for WebExtensions

[VS Code Debugger for Firefox](https://github.com/firefox-devtools/vscode-firefox-debug)

**Comment by connor4312** [comment]
Seems like there are two things here:

1. We need to attach to browser-level frames and service workers, currently we filter and only attach to `page` types. This is easy to fix.
2. Sources in extensions get some random URL prefix like `chrome-extension://gmocgbpbnimoncfocnbhifkbmcicoaef/service-worker.js`. We don't have any way to map this in the debugger, and it seems like having a definite ID is [not trivial](https://stackoverflow.com/questions/23873623/obtaining-chrome-extension-id-for-development). 

I don't plan to support this in the foreseeable future, though if anyone has better solutions to #2, I'm happy to reconsider.

**Comment by victoralvelais** [comment]
@connor4312 #1794 shows that we can load an unpacked extension with `runtimeArgs`. Could we load an extension from our specified directory and then match the extension with the [manifest keys](https://developer.chrome.com/docs/extensions/reference/manifest)? This wouldn't be as foolproof as setting a static ID but I think it would be easier for us to navigate at this time and cover most use cases.

**Comment by MoeBazziGIT** [comment]
Second this

**Comment by noorez** [comment]
Is there any possibility of reconsidering adding support for this? 

Can something be borrowed if at all possible from: https://github.com/firefox-devtools/vscode-firefox-debug which does support debugging web extensions?

**Comment by noorez** [comment]
@connor4312 , I have a PR now #2361 which I think addresses your concerns above. Will you be able to take a look through and offer some feedback?
