### ISSUE TITLE
Don't enable auto attach if the system's node version is too old to support it

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-js-debug#946]
I'm seeing this when I enable auto attach on wsl:

![image](https://user-images.githubusercontent.com/2193314/111631426-9cd30100-87b0-11eb-9ba7-88306b2ff32e.png)

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/118259. You'll want to toggle auto attach to disabled -> reenabled if the old bootloader is any workspaces.
