### ISSUE TITLE
Error when running nodejs app (npm test)

### ISSUE THREAD

**Issue by strarsis** [microsoft/vscode-js-debug#947]
````
Debugger listening on ws://127.0.0.1:46185/05be73ee-cc53-4636-a999-1de2510d7945
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Error in the js-debug bootloader, please report to https://aka.ms/js-dbg-issue: Error [ERR_INSPECTOR_ALREADY_ACTIVATED]: Inspector is already activated. Close it with inspector.close() before activating it again.
    at Object.inspectorOpen (inspector.js:137:11)
    at bootloader.bundle.cdp:7:4964
    at bootloader.bundle.cdp:7:6191
    at Object.<anonymous> (bootloader.bundle.cdp:7:6391)
    at r (bootloader.bundle.cdp:1:110)
    at bootloader.bundle.cdp:1:902
    at Object.<anonymous> (bootloader.bundle.cdp:1:912)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32
````

**Comment by connor4312** [comment]
Can you check whether this happens in the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension)? There are no repro steps in this issue but I fixed the issue you're probably hitting already.

**Comment by strarsis** [comment]
@connor4312: Thanks! I first downloaded the Insider/Nightly of VSCode main application itself - and first assumed the bug being still there. Then I read your post and noticed that the link leads to an extension for which the nightly build should be installed.

So I disabled the old/stable debugging extension, installed the nightly one and enabled it. But sadly, node debugging still logs the same warning/error.

**Comment by connor4312** [comment]
Okay, can you please provide reproduction steps?

**Comment by strarsis** [comment]
OK, so I use latest stable VSCode on WSL 2 on Windows 10.
- git cloned the [svgo](https://github.com/svg/svgo) repository, opened it in VSCode.
- Switched to latest node version in VSCode terminal (`nvm use lts/*`) (`v14.16.0`).
- Installed the dependencies (`npm install`).
- Finally I invoked `npm test`.
Here the debugger attaches and logs the error.

**Comment by connor4312** [comment]
Okay, thanks. It sounds like you're using auto attach. In this case, you'll want to run just `node` first (once) so update the bootloader, either using the nightly VS Code build or in the next version of VS Code that will come out next week.
