### ISSUE TITLE
Debugging node.js apps leads to unbound breakpoints

### ISSUE THREAD

**Issue by matthesinator** [microsoft/vscode-js-debug#948]
**Describe the bug**
When trying to debug a node application, breakpoints become unbound. This is independent from the method used, I tried:
* Attach by Process ID
* Attach to Port
* Launch Program
* Auto Attach

**Log File**

[vscode-debugadapter-940e5a4c.json.gz](https://github.com/microsoft/vscode-js-debug/files/6188861/vscode-debugadapter-940e5a4c.json.gz)

**VS Code Version:** 1.54.3
**Node Version:** v14.16.0

**Additional context**
Attach by Process ID gives me a choice between three processes. One of these is node with the `--inspect` flag. Selecting this, leads to an Error: `Could not connect to debug target at http://localhost:0: Promise was canceled`

**Comment by connor4312** [comment]
Check out the "symlinks" FAQ here https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_can-i-debug-if-im-using-symlinks

This month with https://github.com/microsoft/vscode-js-debug/issues/776, the debugger will start warning you about these cases automatically.
