### ISSUE TITLE
Could not read sourcemap ECONNREFUSED

### ISSUE THREAD

**Issue by JM-Mendez** [microsoft/vscode-js-debug#949]
**Describe the bug**
I'm using remote debugging to launch a session for an app in a windows vm. I can connect to the launched browser, view the loaded scripts in the `scripts` panel, and the logs show that the source files are being loaded. But loading the corresponding sourcemap fails with an ECONNREFUSED 503 error. I can also view the sourcemap when pasting the url directly in the browser.

I could share logs, but I'd have to remove file paths (or rename them). I'm at a loss, anyone have any ideas? 

**VS Code Version:**  1.54.3

**Comment by connor4312** [comment]
Logs would be useful

**Comment by JM-Mendez** [comment]
I would love to add logs, but can't because of the file paths. Still, I think the issue was with my vm and have since moved away from that setup.

**Comment by connor4312** [comment]
Okay. Ultimately sourcemaps are requested by js-debug, so if there's not a good path from where vscode is running to where sourcemaps are hosted, there can be issues. Though there are a few ways to configure their retrieval if you run into this again.
