### ISSUE TITLE
Debugging workers results in "Error in the js-debug bootloader"

### ISSUE THREAD

**Issue by zastrowm** [microsoft/vscode-js-debug#950]
Launching the following script from within vscode:

```
const assert = require('assert');
const {
  Worker, MessageChannel, MessagePort, isMainThread, parentPort
} = require('worker_threads');
if (isMainThread) {
  const worker = new Worker(__filename);
  const subChannel = new MessageChannel();
  worker.postMessage({ port: subChannel.port1 }, [subChannel.port1]);
  subChannel.port2.on('message', (value) => {
    console.log('received:', value);
  });
} else {
  parentPort.once('message', ({port}) => {
    assert(port instanceof MessagePort);
    console.log("over here");
    port.postMessage('the worker is sending this');
    port.close();
  });
}
```

Resulted in the following error:

> Error in the js-debug bootloader, please report to https://aka.ms/js-dbg-issue: Error [ERR_INSPECTOR_ALREADY_ACTIVATED]: Inspector is already activated. Close it with inspector.close() before activating it again.
    at Object.inspectorOpen (inspector.js:137:11)
    at bootloader.bundle.cdp:7:4920
    at bootloader.bundle.cdp:7:6147
    at Object.<anonymous> (bootloader.bundle.cdp:7:6347)
    at r (bootloader.bundle.cdp:1:110)
    at bootloader.bundle.cdp:1:902
    at Object.<anonymous> (bootloader.bundle.cdp:1:912)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)

Version info:

> Version: 1.54.1
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:42:18.719Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-js-debug/issues/933, please update to the latest version of VS Code.
