### ISSUE TITLE
Debugger doesn't stop at function breakpoint 

### ISSUE THREAD

**Issue by DJviolin** [microsoft/vscode-js-debug#952]
**Describe the bug**
Debugger doesn't stop at function breakpoints in a Node.js (Koa) application.

**To Reproduce**
1. Create function breakpoints to `next()` function in a Koa application.
2. Run debugger
3. Program executes until the end, debugger doesn't halt the execution.

**Log File**

[vscode-debugadapter-d919bdc7.json.gz](https://github.com/microsoft/vscode-js-debug/files/6195907/vscode-debugadapter-d919bdc7.json.gz)

**VS Code Version:** 1.55.0-insider

**Additional context**

Example repository provided: https://github.com/DJviolin/js-debug-issue

Screenshot:
![Clipboard02](https://user-images.githubusercontent.com/5021728/112287627-dc0bc100-8c8c-11eb-983f-3421bf1ead34.png)

**Comment by connor4312** [comment]
JavaScript debugging does not support function breakpoints.
