### ISSUE TITLE
Immediate 

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-js-debug#956]
Version 1.54.2

Start vscode to empty workbench with a system node on 6 (I was testing some stuff 🙃). Immediately get this notification:
![image](https://user-images.githubusercontent.com/8586769/112680326-78b79580-8e2a-11eb-8700-5f06764cc066.png)

It'd be better if this only showed when someone actually tries to debug.

**Comment by connor4312** [comment]
dupes https://github.com/microsoft/vscode-js-debug/issues/957
