### ISSUE TITLE
Immediate "Node version is outdated" notification on startup.

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-js-debug#957]
Version 1.54.2

Start vscode to empty workbench with a system node on 6 (I was testing some stuff 🙃). Immediately get this notification:
![image](https://user-images.githubusercontent.com/8586769/112680326-78b79580-8e2a-11eb-8700-5f06764cc066.png)

It'd be better if this only showed when someone actually tries to debug.

**Comment by connor4312** [comment]
Do you have auto attach on? If so, this is as intended.

**Comment by JacksonKearl** [comment]
It's "smart"

**Comment by RMacfarlane** [comment]
I'm seeing a similar notification on startup when `debug.javascript.autoAttachFilter` is set to "smart":
<img width="469" alt="Screen Shot 2021-04-30 at 9 20 34 AM" src="https://user-images.githubusercontent.com/3672607/116724339-65ea3080-a995-11eb-84f6-d1c7af467652.png">

**Comment by connor4312** [comment]
@RMacfarlane that's by design. The bug was that we showed a less helpful message (the generic debug message). Instead we want to show that specific message.
