### ISSUE TITLE
Let error notification open th ecodespace itself

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-js-debug#960]
![image](https://user-images.githubusercontent.com/8586769/113095064-ad6b7a00-91a7-11eb-9d70-d98d57b4fb09.png)

It'd be nice to have a "Open codespace in desktop" button here

**Comment by connor4312** [comment]
Backlog pending linked issue

**Comment by connor4312** [comment]
From GH last august:

> Given that we haven't heard any other requests from customers, and this is not likely to be implemented in the near future, I'm going to close this as won't fix for now.
