### ISSUE TITLE
VS Code Chrome debugging in WSL2 stopped working after 1.55.0 (March) upgrade

### ISSUE THREAD

**Issue by borisg-me** [microsoft/vscode-js-debug#963]
After upgrading to VSCode 1.55.0, launching a Chrome run configuration (```Debug: Client``` below) fails with ```Error running browser: connect ECONNREFUSED 127.0.0.1:53091``` The last three digits of the port number (53091 here) are different every time. I verified this is caused by the upgrade by upgrading a second machine, which immediately started failing in the same manner.

Launching ```Debug: Server``` and connecting Chrome to it works just fine, so I can still use Chrome DevTools for debugging, but not VSCode anymore.

Also, a new "ghost" run configuration appeared in the RUN AND DEBUG dropdown. So instead of
```
Debug: Server (purchasereq)
Debug: Client (purchasereq)
...
```
it now shows
```
Debug: Server (purchasereq)
Debug: Client (purchasereq)
Debug: Client
...
```
(```purchasereq``` is my workspace name)

I can't find this ghost configuration anywhere.

I am running Ubuntu in WSL2.

```launch.json```
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "pwa-node",
      "request": "launch",
      "name": "Debug: Server",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "program": "${workspaceFolder}/dist/server/server.js",
    },
    {
      "type": "pwa-chrome",
      "request": "launch",
      "name": "Debug: Client",
      "url": "http://localhost:3000/purchase-req",
      "webRoot": "${workspaceFolder}",
    },
  ]
}

**Comment by connor4312** [comment]
Please see https://github.com/microsoft/vscode/issues/120227#issuecomment-812007561
