### ISSUE TITLE
Debugging a project supported by parcel results in error

### ISSUE THREAD

**Issue by dzx-dzx** [microsoft/vscode-js-debug#967]
**Describe the bug**
After attempting to initialize the debugging process from `npm scripts`, the following error continuously pop up.

**To Reproduce**
1. Go to `NPM SCRIPTS`
2. Click on debug button from `start`
3. See error

**Log File**
```
@parcel/workers: Cannot find module '"c:/Users/321/AppData/Local/Programs/Microsoft'
Require stack:
- internal/preload
Error: Cannot find module '"c:/Users/1/AppData/Local/Programs/Microsoft'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at Function.Module._load (internal/modules/cjs/loader.js:742:27)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1221:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:446:5)
    at MessagePort.<anonymous> (internal/main/worker_thread.js:122:5)
    at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:353:41)   
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26) 
```

**VS Code Version:** 1.55.1

**Additional context**

**Comment by connor4312** [comment]
This can be solved by updating to Node 12 or newer.

**Comment by dzx-dzx** [comment]
> 
> 
> This can be solved by updating to Node 12 or newer.

My node version is v14......?

**Comment by connor4312** [comment]
Ok, please collect a log file using the instructions in the issue template.

**Comment by dzx-dzx** [comment]
> 
> 
> Ok, please collect a log file using the instructions in the issue template.

No `launch.json` has been created, should I create one?

**Comment by dzx-dzx** [comment]
[Uploading vscode-debugadapter-5b76e5a5.json.gz…]()

**Comment by dzx-dzx** [comment]
[vscode-debugadapter-da98c5e6.json.gz](https://github.com/microsoft/vscode-js-debug/files/6303126/vscode-debugadapter-da98c5e6.json.gz)

**Comment by connor4312** [comment]
Thanks, this is actually an error in Parcel (which leads to the same error message that _can_ happen with end of life Node.js versions). I've opened an issue on them here: https://github.com/parcel-bundler/parcel/issues/6123

**Comment by dzx-dzx** [comment]
> 
> 
> Thanks, this is actually an error in Parcel (which leads to the same error message that _can_ happen with end of life Node.js versions). I've opened an issue on them here: [parcel-bundler/parcel#6123](https://github.com/parcel-bundler/parcel/issues/6123)

Including the most recent LTS vrsion? That's surprising...But still, thanks.
