### ISSUE TITLE
run [Extension] failed

### ISSUE THREAD

**Issue by yFeii** [microsoft/vscode-js-debug#968]
**Describe the bug**

**To Reproduce**
1. download project
2. disable @builtin @id:ms-vscode.js-debug
3. npm install
4. npm run compile
5. run : extension 

**Log File**

![image](https://user-images.githubusercontent.com/24515770/114664225-f7b73400-9d2d-11eb-864c-2658a6c34b2e.png)

**VS Code Version:** 1.55.2

**Additional context**
 how can i debug this project[vscode-js-debug]？
I noticed the mock debug[https://code.visualstudio.com/api/extension-guides/debugger-extension#the-mock-debug-extension] can debug  extension and markdown file in  new extension host window  by  selecting Extension Launch Configuration。
 I want to  debug  vscode-js-debug too。so I tried run 'Extension'。

**Comment by connor4312** [comment]
> disable @Builtin @id:ms-vscode.js-debug

You disabled the debugger, so the error you see is expected.

If you wanted to install the nightly version, make sure to follow the last two steps in [the instructions](https://github.com/microsoft/vscode-js-debug#nightly-extension)
