### ISSUE TITLE
A DAP launcher/option to stick to single session plain DAP mode

### ISSUE THREAD

**Issue by mickaelistria** [microsoft/vscode-js-debug#969]
See discussion on https://github.com/microsoft/vscode-js-debug/issues/902#issuecomment-819095548 .
To make the Debug Adapter reusable by other clients (in place of node-debug2), we need a way to start the Debug Adapter in a "plain DAP" mode where the vanilla DAP workflow works, eg without need to interact with non-DAP standard `attachedDebugSession` requests. This basically means ignoring everything related to sessions in the public facade.
A suggestion is to add a `--runInBand` flag (to flatSessionLauncher I guess).

**Comment by robbienohra** [comment]
any update on this?

**Comment by mickaelistria** [comment]
> You could implement some ad-hoc 'adapter adapter' that would only be able to evaluate when a frameId is given, and implement similar scoping or rough-fitting for other DAP features. 

Most DAP-able clients would pass a `frameId` as the DAP spec can suggest. So it's a pity that this debugger cannot support that case and cannot "just work" if plain DAP is used and `frameId` is set. I think the limitations like the one you mention here are not really blockers for DAP support as they are not really part of the typical DAP spec or usage.
I believe most people here are not looking for full support of all vscode-js-debug feature over DAP, but just 1 easy way to use a subset of vscode-js-debug over DAP, instead of node-debug2.
