### ISSUE TITLE
Overaggressive helper

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-js-debug#970]
In vscode core, set breakpoint, run code, stop at breakpoint, remove breakpoint, this appears:
![image](https://user-images.githubusercontent.com/8586769/114792320-ff320980-9d3c-11eb-8c60-78c56072b0ce.png)

Once it happens once, it seems to then happen at every launch.

**Comment by connor4312** [comment]
- Avoid showing the suggester if the notification is already open
- Use a global event on verification so that compound launch configs aren't triggered incorrectly
