### ISSUE TITLE
Error activating auto attach

### ISSUE THREAD

**Issue by dbkaynor** [microsoft/vscode-js-debug#971]
debugger listening on ws://127.0.0.1:49747/d1f96e85-8251-41fd-8075-6c37289d6c0d
For help, see: https://nodejs.org/en/docs/inspector
read byte 1

Error activating auto attach, please report to https://aka.ms/js-dbg-issue

**Comment by connor4312** [comment]
Thanks for the issue, can you please run the `Toggle Developer Tools` command and let me know if you see any errors in the Console there?

**Comment by inromualdo** [comment]
I have the same problem. This is the error in Developer Tools.
<img width="555" alt="Screenshot 2021-04-20 at 5 17 28 AM" src="https://user-images.githubusercontent.com/12269482/115336978-17b87e80-a198-11eb-9066-f2313159c12b.png">

**Comment by connor4312** [comment]
Okay, thanks, do you see anything above that error message or is that it?

**Comment by inromualdo** [comment]
That it is

**Comment by connor4312** [comment]
Ok, thanks. I've made some changes so that any errors in that command will show as a notification. Please try next [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) (available when this comment is five hours old) and, if you still get an error, let me know what it is.
