### ISSUE TITLE
Unable to add address autofill data

### ISSUE THREAD

**Issue by StanleyDharan** [microsoft/vscode-js-debug#972]
**Describe the bug**

**To Reproduce**
1. Go to `chrome://settings/addresses`
2. Make sure `Save and fill addresses` is turned on
3. Click the `Add` button
4. Nothing will happen

**Log File**
`[6982:775:0420/105718.654721:ERROR:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'countryCode' of undefined", source: chrome://resources/polymer/v3_0/polymer/polymer_bundled.min.js (1)
Uncaught TypeError: Cannot read property 'countryCode' of undefined`

**VS Code Version:**  1.55.2
**Additional context**

**Comment by connor4312** [comment]
This is an issue in Chrome, see https://bugs.chromium.org/p/chromium/issues/detail?id=1166293

**Comment by StanleyDharan** [comment]
@connor4312 Im reading through that issue, there doesn't seem to a definitive answer or work around, do you know of any I could try?

**Comment by connor4312** [comment]
You can set `userDataDir: false` in your launch configuration to avoid creating a separate profile. However note that you will need to close your browser before you start debugging due to the way Chrome manages its sessions.
