### ISSUE TITLE
Error: could not attach to main target when trying to launch Chome from dev container

### ISSUE THREAD

**Issue by RaddishIoW** [microsoft/vscode-js-debug#974]
**Describe the bug**
I receive the error `could not attach to main target` when trying to launch Chrome to debug when running in a dev container.
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/7757254/115544215-399a2a00-a29a-11eb-80a4-60d917b575ba.png">

Launching from a local workspace (not in a dev container) works perfectly.

My launch.json config is:
```
{
      "name": "Launch Chrome",
      "request": "launch",
      "type": "pwa-chrome",
      "url": "http://localhost:8080",
      "sourceMaps": true,
      "outFiles": [
        "${workspaceFolder}/**/*.js",
        "${workspaceFolder}/**/*.ts",
        "${workspaceFolder}/**/*.jsx",
        "${workspaceFolder}/**/*.tsx",
        "!**/node_modules/**"
      ]
    }
```

**To Reproduce**
1. Launch VS Code with a dev container, with a checkout in a container volume.
2. Run webpack dev server
3. Attempt to run "Launch Chrome" debug config

**Log File**

**VS Code Version:** 1.56.0-insider (shown in screenshot) and 1.55.2

**Comment by connor4312** [comment]
Please collect a log file using the instructions in the issue template

**Comment by RaddishIoW** [comment]
My apologies - I did enable tracing as instructed, but did not receive output the first time I ran the debug command, so I did not have a log to upload.
I have just tried again and have the attached log.
[vscode-debugadapter-3d3ae0c5.json.gz](https://github.com/microsoft/vscode-js-debug/files/6353788/vscode-debugadapter-3d3ae0c5.json.gz)

**Comment by connor4312** [comment]
It looks like Chrome is being quite slow to respond to our request to attach. You can try increasing the `timeout` in the launch.json, otherwise I suggest opening an issue for the Chromium team.

**Comment by RaddishIoW** [comment]
Thank you - I can confirm that increasing the timeout to 20000ms solved the error, and allows me to debug again.

**Comment by erickodeny-gif** [comment]
Thanks helpful
