### ISSUE TITLE
Adopt icon in contributed terminal

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-js-debug#975]
JS Debug Terminal should use `debug` as the `icon`:

https://github.com/microsoft/vscode/blob/a3d61cb025150d0ceb1d825fcbd268bda2aacf52/src/vs/workbench/contrib/terminal/common/terminal.ts#L611-L611

**Comment by connor4312** [comment]
I added this assuming https://github.com/microsoft/vscode/issues/122061 will get in

**Comment by mjbvz** [comment]
@connor4312 I tested using `v2021.4.2917` of the nightly extension but did not see this working.

Reopening but let me know if I was not testing correctly

**Comment by connor4312** [comment]
@mjbvz where did you look? Currently this appears on the profile selector: https://memes.peet.io/img/21-04-22fb5a48-43fc-4da5-9ba8-2c87f33772f9.png

**Comment by mjbvz** [comment]
Oh ok, I was looking in the terminal tabs. Verified it appears in the profile selector

**Comment by starball5** [comment]
something about this might have regressed. I see a bash icon in VS Code 1.78.1 on Ubuntu, and [someone else is seeing a PowerShell icon](https://stackoverflow.com/q/76229398/11107541). Should I create an issue ticket? Or is this by design?

**Comment by Tyriar** [comment]
Thanks @starball5, created https://github.com/microsoft/vscode/issues/182303
