### ISSUE TITLE
Debugger keeps sending telemetry CDP requests to a debuggee in an infinite loop

### ISSUE THREAD

**Issue by RedMickey** [microsoft/vscode-js-debug#981]
Hello,
I'm a maintainer of [React Native Tools](https://github.com/microsoft/vscode-react-native) VS Code extension. The extension is used for debugging React Native applications. Under the hood the extension uses `vscode-js-debug` debugger to debug javascript apps.

**Describe the bug**
While debugging React Native applications, we found out that `js-debug` sends [the CDP request](https://github.com/microsoft/vscode-js-debug/blob/main/src/targets/node/nodeLauncherBase.ts#L521-L529) to a debuggee to get some data for telemetry. `js-debug` keeps sending that request, in case the debuggee returns `process not defined` string. Due to the peculiarities of debugging [React Native Hermes](https://reactnative.dev/docs/hermes) applications the debuggee always returns `process not defined` string as a result.
```
[Reply From Debugger To Target] {
  "id": 1043,
  "method": "Runtime.evaluate",
  "params": {
    "contextId": 1,
    "returnByValue": true,
    "expression": "typeof process === 'undefined' || process.pid === undefined ? 'process not defined' : ({ processId: process.pid, nodeVersion: process.version, architecture: process.arch })\n//# sourceURL=eval-8907f309.cdp\n"
  }
}

[Reply From Target To Debugger] {
  "result": {
    "result": {
      "type": "string",
      "value": "process not defined"
    }
  },
  "id": 1043
}
```

Therefore, `js-debug` sends the `Runtime.evaluate` request in an infinite loop [here](https://github.com/microsoft/vscode-js-debug/blob/main/src/targets/node/nodeLauncherBase.ts#L517-L556). 
This behavior doesn't break debugging, but it could reduce performance.

It might make sense to add several retries to get process data in [`gatherTelemetryFromCdp`](https://github.com/microsoft/vscode-js-debug/blob/main/src/targets/node/nodeLauncherBase.ts#L517-L556) function (e.g. like [here](https://github.com/microsoft/vscode-js-debug/blob/main/src/targets/node/nodeAttacher.ts#L225-L246)) to prevent infinite sending of the CDP request.

**To Reproduce**
1. Prepare the development environment for React Native Android apps using [this guide](https://reactnative.dev/docs/environment-setup)
2. Create a plain RN app using the command `npx react-native init AwesomeProject`
3. Enable Hermes engine for Android following [the guide](https://reactnative.dev/docs/hermes#android)
4. Launch the RN app using the command `npx react-native run-android`
5. Open the project in VS Code and create the debugging configuration:
  ```
    {
      "type": "pwa-node",
      "request": "attach",
      "name": "Attach pwa-node",
      "port": 8081,
      "resolveSourceMapLocations": ["**", "!**/node_modules/**"],
      "continueOnAttach": true
    }
  ```
6. Attach to the application using the created debugging configuration
7. After that `js-debug` should attach to the app. Breakpoint won't work since some additional processing is need (this is implemented in React Native Tools extension), but debugging console should work correctly
8. Then you can set a breakpoint in `gatherTelemetryFromCdp` function [here](https://github.com/microsoft/vscode-js-debug/blob/main/src/targets/node/nodeLauncherBase.ts#L540), and it will be reached over and over again after the successful attachment

**Log Files:** [vscode-debugadapter-c33e8880.json.gz](https://github.com/microsoft/vscode-js-debug/files/6397860/vscode-debugadapter-c33e8880.json.gz), [CDPlogs.txt](https://github.com/microsoft/vscode-js-debug/files/6397908/CDPlogs.txt)

**VS Code Version:**  1.55.2

**Comment by connor4312** [comment]
sure, I think giving up after half a second or so is fine
