### ISSUE TITLE
WSL2 chrome debug with Error running browser: connect ECONNREFUSED 127.0.0.1:53579

### ISSUE THREAD

**Issue by Agamennon** [microsoft/vscode-js-debug#982]
**Describe the bug**
WSL2 chrome debug not possible, browser opens for a moment then closes, with messege:

> Error running browser: connect ECONNREFUSED 127.0.0.1:53579 

**To Reproduce**
1. On windows 10, install WSL2
2. Install VSCODE  (insiders or stable)
3. Try debug javascript

launch.json:
```
  {
        "name": "Launch Chrome",
        "request": "launch",
        "type": "pwa-chrome",
        "url": "http://localhost:5000",
        "trace": true,
        "webRoot": "${workspaceFolder}"
      },
```
**Log File**
[vscode-debugadapter-00e1f992.json](https://drive.google.com/file/d/1wBNxTNnaesXDtLYAA44rKP-47shwqV6a/view?usp=sharing)

Vscode -> 1.56.0-insider
Javacript Debugger (Nightly) v2021.4.2617

**Additional context**
Curiously installing older versions of the javascript debugger also give the same error, even versions 3 months old
Also installing older versions of  Debugger for chrome and Remote WSL also fails with the same error

**Comment by zzjin** [comment]
same isssue here with same vscode version and js debug version.

**Comment by connor4312** [comment]
I could not reproduce this before, but for some reason tonight I could. It seems there's some latency (in WSL?) before the port is available to connect to. We'll now retry for 5 seconds which seems to fix this issue for me.

**Comment by connor4312** [comment]
Verifier: easiest way is to:

1. Open any folder in WSL2
2. Use the `Debug: Open Link` command
3. Verify the browser attaches successfully

**Comment by Agamennon** [comment]
As far as i can tell it's fixed and working as intended,  @connor4312 great job, thank you!

**Comment by GaboFrontDev** [comment]
I just changed the type to "edge" and it works. Maybe changing it to just "chrome" might work

**Comment by mpiorowski** [comment]
Not working for me, still getting ECONNREFUSED debugging browsers in WSL2, and i am trying all the config presented here. Got the java script debbuger (nightly) isntalled

**Comment by eladavron** [comment]
Still happening to me :-( Any updates on this?

**Comment by umer-ilyas** [comment]
getting this error on vs code `version 1.66.2`

**Comment by eladavron** [comment]
> umer

Same

**Comment by jmietola** [comment]
Also experiencing this issue. Wish this would get fixed. I like the WSL but so far too many issues have been rising.

**Comment by swtrse** [comment]
No solution but some things I noticed.
As I already told it works sometimes and closing chrome and stopping the debugger and hit F5 again solves the problem after 10-15 tries.
What I noticed in the popup message vscode shows (not always, and not always the same) that each try uses a different port to connect the debugger.
I do not have the time to look into it but I suspect that this ports are blocked and at times the debug is working a port that is not blocked is used.

**Comment by neilmendoza** [comment]
Getting this error on 1.76.1. Workaround is to open from explorer rather than WSL shell but would be nice if it wasn't broken.

**Comment by timothy3001** [comment]
The problem vanished for me when I created a new WSL2 "distro". Since then I never had these issues. 

You might wanna try this.

(I find the name distro rather confusing, but it's the naming of microsoft for the WSL2 containers so to say i guess)

**Comment by derekjtong** [comment]
When I click on Run and Debug, I get sent to `file:///root/wsl-projects/project1/index.html`

However, I want to go to `file://wsl.localhost/Ubuntu/root/wsl-projects/project1/index.html`

If I copy paste in the second to URL, it works fine.

**Comment by KamranAghlami** [comment]
> When I click on Run and Debug, I get sent to `file:///root/wsl-projects/project1/index.html`
> 
> However, I want to go to `file://wsl.localhost/Ubuntu/root/wsl-projects/project1/index.html`
> 
> If I copy paste in the second to URL, it works fine.

This is a late reply, but for future people with same situation, I fixed it by opening `C/C++ DevTools Support Options
` (click on the extension and select Extension options) and added the following as a path substitution:
```
"/" -> "file://wsl.localhost/Ubuntu/"
```

Then went to the DevTools settings(Cogwheel at top-right of DevTools panel), and enabled `Allow DevTools to load resources, such as source maps, from remote file paths.`.

Reloaded the DevTools and now my sources can be found.
