### ISSUE TITLE
Cannot generate a valid debug trace file.

### ISSUE THREAD

**Issue by cramhead** [microsoft/vscode-js-debug#986]
**Describe the bug**
When I attempt to debug with the `"trace": true` property set in the launch configuration the resulting `*.gz`is not openable.

**To Reproduce**
1. Go to 'launch.json'
2. Set trace true
``` {
      "type": "node",
      "request": "attach",
      "name": "Attach to docker",
      // Re-attach when node process restarts
      "restart": true,
      "protocol": "auto",
      "skipFiles": ["<node_internals>/**", "node_modules/**"],
      "port": 9209,
      "localRoot": "${workspaceFolder}",
      "remoteRoot": "/usr/src/app",
      "trace": true
    },
```
3. Start debug
4. See debug console for path to generated file
5. Attempt open or `gunzip` fails

**Log File**

[vscode-debugadapter-f5545d41.json.gz](https://github.com/microsoft/vscode-js-debug/files/6411952/vscode-debugadapter-f5545d41.json.gz)

**VS Code Version:**  1.55.2
3c4e3df9e89829dce27b7b5c24508306b151f30d
x64

**Additional context**
I'm running macOS 10.15.7 (19H524)

I tried opening with gunzip 
```
gunzip vscode-debugadapter-f5545d41.json.gz
gunzip: vscode-debugadapter-f5545d41.json.gz: unexpected end of file
gunzip: vscode-debugadapter-f5545d41.json.gz: uncompress failed
```
and Archive Utility 
![image](https://user-images.githubusercontent.com/386035/116822363-4e48ae80-ab33-11eb-922a-976d6c71eb69.png)

**Comment by connor4312** [comment]
That's fine. The file isn't terminated cleanly, but most tools like the `gunzip` cli and https://microsoft.github.io/vscode-pwa-analyzer/index.html work with it.

**Comment by cramhead** [comment]
Thanks for the link @connor4312, the vsdoce-pwa-analyzer was able to open the file, even when gunzip was not able to.
