### ISSUE TITLE
RFC - Support using launch task name as terminal title

### ISSUE THREAD

**Issue by danielgary** [microsoft/vscode-js-debug#990]
**Is your feature request related to a problem? Please describe.**
When launching multiple Node debug instances, multiple integrated terminal sessions are spawned, but they all use the same default Node Debug Console title, and they are not always spawned in the same order if you use the compound tasks.  This makes it difficult to determine which of the terminals is the one you are looking for.

![image](https://user-images.githubusercontent.com/5438098/117299405-21034580-ae3e-11eb-9d1c-a0ced9b2928e.png)

**Describe the feature you'd like**
Use the launch task name as the terminal title.  This would provide a much better experience for developers and the name field is already required for all launch tasks.
![image](https://user-images.githubusercontent.com/5438098/117299666-67f13b00-ae3e-11eb-8079-2071b6c52ff3.png)

**Comment by danielgary** [comment]
I could also imagine prefixing it with node.label so it would look like this:
```Node.js - Debug API```
```Node.js - Debug Docs```
```Node.js - Debug Webapp```

**Comment by connor4312** [comment]
Good idea!

**Comment by danielgary** [comment]
Which would you rather see?  Prefixed with Node.js or just the task name?

**Comment by connor4312** [comment]
I'd prefer just the task name

**Comment by danielgary** [comment]
There seems to be an issue here.  It works for the first startup, but it doesn't close the terminal windows when you stop debugging, which means after a few runs you have a bunch of duplicates.

This is still better than just Node Debug Console, but is there a configuration option to make the integrated terminals close after debugging?  Ideally if a terminal was created for a debug session, you would want it to close when you're done debugging?  Although you might want to reference some output.

Would it be possible to look for a terminal instance that isn't currently running with the same name as the task and reuse that terminal instance?  If there aren't any available instances, just spawn a new instance.

**Comment by connor4312** [comment]
> is there a configuration option to make the integrated terminals close after debugging

No, but there is a feature request for something along those lines https://github.com/microsoft/vscode/issues/63813

I think the best way for this would be for VS Code core to rename the terminal if gets a new `runInTerminal` request with a different name -- opened an issue for that https://github.com/microsoft/vscode/issues/123189. I would be happy to accept the PR in js-debug and then make that change in core later.

**Comment by danielgary** [comment]
OK.  I will take a look at reusing terminal instances.  Looks like that would alleviate some of the complaints in microsoft/vscode#63813 as well.

**Comment by aeschli** [comment]
Verified in the vscode repo: In the 'Run and Debug' dropdow, chose 'Node...' and pick 'Run script: xy.'. Verify that the opened terminal title is 'Run script: xy.'

Please speak up if that are not valid steps to verify the issue.
