### ISSUE TITLE
Feature Request: Toggle Source Map Support While Debugging

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode-js-debug#995]
Sometimes, something is weird (*) and it would be nice to disable source map support ad hoc without needing to restart the debugger.

If TypeScript code is being debugged, execution is paused on a certain line, and some "JS Debug: Toggle Source Map" command is called, it would be nice if VS Code would immediately continue debugging the JavaScript source (and vice versa).

(*) weirdness can be caused by
* TypeScript code is modified after transpilation (which includes the scenario of a build tool that died silently): The code you see does not match the code that is executed.
* TypeScript produces invalid source maps
* Some webpack plugin/custom transformer screwed up

**Comment by connor4312** [comment]
Added this a bit ago, I think this was a duplicate
