### ISSUE TITLE
Feature-Request: Allow sourcemaps from external https server (i.e. azure devops symbol server)

### ISSUE THREAD

**Issue by dannyvv** [microsoft/vscode-js-debug#997]
## Summary
I am working on allowing SourceMaps to be uploaded to Azure DevOps symbol server using the [https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/index-sources-publish-symbols?view=azure-devops](PublishSymbols task). My prototype fully works with Edge and Chrome debugging. It unfortunately does not work with VsCode at the moment as it seems VsCode blocks http/https based sourcemap url's.
I would love to make this work in VsCode debugging

Would this be an acceptable/welcome change?
I would be more than happy to contribute any/all coding needed for this.

This is related to: #425 since ADO will require authentication.

## Details
Sourcemaps are normally annotated with the URL comments like: 
`//# sourceMappingURL=foo.js.map`
When the symbols are stored on Azure DevOps symbol backend the url would be:
`//# sourceMappingURL=https://artifacts.dev.azure.com/ms/_apis/symbol/symsrv/foo.js/AB0CB42A3AC3C5C80C/foo.js`
Please let me know if you'd like more background on this work, I can share a gist.

Unfortunately there is code in [sourceMapRepository.ts Line 62](
https://github.com/microsoft/vscode-js-debug/blob/2994e0576d17a54e11132f92945039dd827e0d78/src/common/sourceMaps/sourceMapRepository.ts#L62)
```ts
/**
 * Generates source map metadata from a path on disk and file contents.
 * @param compiledPath -- Absolute path of the .js file on disk
 * @param fileContents -- Read contents of the file
 */
export const createMetadataForFile = async (compiledPath: string, fileContents?: string) => {
  // <snip for brevity>

  if (!sourceMapUrl.startsWith('data:') && !sourceMapUrl.startsWith('file://')) {
    return;
  }

```
that short-circuits http based source maps

I have not investigated the code much further than the quoted lines and wanted to start a dialog with the team as soon as possible...  
I don't know what the best strategy would be: 
* Allow this to return https based locations (see security/privacy concerns). 
  * This might require a bunch of downstream changes if it turns out that the operations are going to be all based on file-io and make those work on network and/or buffers
* In this logic perform the download (to an http-cache) and return the cached file location

Before diving into the code I'd love to learn what the thoughts are from the experts.

### Authentication
This is already touched on by #425 for websites with Auth, and any improvements there would apply here. I don't know if I have the full bandwidth to implement all authentication schemes proposed in that issue, but am more than happy to contribute the required 

### Security / Privacy concerns
I can understand that this might raise security / privacy concerns as now VsCode will send out a 'ping' to fetch the source map to a potentially different server and this could be used to track people, know when folks attach VsCode as a debugger, etc... I would love to learn your opinions here. 

I was thinking of mitigating these concerns by one of or all:
* requiring an opt-in setting in `launch.json`:
    ```js
    {
        "type": "pwa-node",
        "request": "launch",

        // New setting, defaults to false
        "allowExternalSourceMaps": true
     }
    ```   
* requiring a allow-list of url patterns in the user's or project's `settings.json`:
    ```js
    {
         "debug.javascript.allowedExternalSourceMapURLs": [
             "https://dev.azure.com/**",
        ]
    }
    ```
* For usability: Present a toast if a source map is opened that does not meet the criteria to more easily add the configuration entries

**Comment by connor4312** [comment]
This already works in general. What you're hitting is the filter that only loads maps for sources in the working directory, which is used to avoid loading sourcemaps for library or external code. You can set `resolveSourceMapLocations: null` to remove this filter

**Comment by dannyvv** [comment]
Thank you @connor4312: Sorry I did not find that flag! That setting indeed makes http/https based source maps work!
I'll follow the other issue for Authentication against ADO.

Closing this issue.
